### PR TITLE
fix failing grunt tests

### PR DESCRIPTION
**Pull request by andidev**
as discussed in mail conversation
https://groups.google.com/forum/?hl=en#!topic/jhipster-dev/sEicbdFdYlw

### CODE REVIEW

**Comment by jdubois** [comment]
@andidev can you also test with XAuth authentication?
I have a 
```
Services Tests  Auth should call LocalStorageService.clearAll on logout FAILED
```

**Comment by jdubois** [comment]
@andidev same thing with OAuth2 authentication

**Comment by andidev** [comment]
I'll have a look at it right away

**Comment by andidev** [comment]
Done!

**Pull request merged**
