### PR TITLE
Heroku updates

### PR DESCRIPTION
**Pull request by jkutner**
* Set `maximumPoolSize` for Hikari (instead of `max-active`)
* Enable Async Liquibase on Heroku

### CODE REVIEW

**Comment by jkutner** [comment]
With these changes, a JHipster app starts up in as little as 24 seconds on Heroku (but more like 30-40 on average). Very awesome.

**Comment by mraible** [comment]
I tried these changes on my www.jhipster-book.com application. After deploying, it failed to startup in 120 seconds the first time, then succeeded the 2nd time.

```
2015-11-06T21:23:02.432329+00:00 app[web.1]: [INFO] org.jhipster.book.Application - Started Application in 64.534 seconds (JVM running for 83.325)
```

+1 for these changes, but it doesn't seem to decrease startup time that much for me.

**Comment by jkutner** [comment]
do you have a feeling for what the slow point is? Is it because you have actual models and stuff?

**Comment by mraible** [comment]
Looking at the startup log below, it looks like New Relic and setting up the WebConfigurer are taking the longest.

* New Relic (21:39 to 22:07): 28 seconds
* Logging, Async, WebConfigurer: (22:07 to 22:29): 22 seconds
* Datasource, Liquibase (22:30 to 22:40): 10 seconds
* Cache Config (22:43 to 22:52): 9 seconds
* Thymeleaf Config (22:54 to 23:02): 8 seconds

```
2015-11-06T21:21:36.822556+00:00 heroku[web.1]: Starting process with command `java -javaagent:newrelic.jar -jar target/*.war --spring.profiles.active=prod,heroku --server.port=42693 --jhipster.metrics.jmx.enabled=false --spring.datasource.maximumPoolSize=5`
2015-11-06T21:21:39.101859+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2015-11-06T21:21:39.107042+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx768m -Dfile.encoding=UTF-8
2015-11-06T21:21:39.974619+00:00 app[web.1]: Nov 6, 2015 21:21:39 +0000 [3 1] com.newrelic INFO: New Relic Agent: Loading configuration file "/app/./newrelic.yml"
2015-11-06T21:22:07.895686+00:00 app[web.1]: [INFO] org.jhipster.book.Application - Starting Application on 37e4a74f-40fa-4087-819f-3a0791c15831 with PID 3 (started by u19074 in /app)
2015-11-06T21:22:07.895844+00:00 app[web.1]: [DEBUG] org.jhipster.book.Application - Running with Spring Boot v1.3.0.RC1, Spring v4.2.2.RELEASE
2015-11-06T21:22:07.896009+00:00 app[web.1]: [INFO] org.jhipster.book.Application - The following profiles are active: prod,heroku
2015-11-06T21:22:19.390014+00:00 app[web.1]: [DEBUG] org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider found via system property
2015-11-06T21:22:20.002661+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.AsyncConfiguration - Creating Async Task Executor
2015-11-06T21:22:20.686657+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.MetricsConfiguration - Registering JVM gauges
2015-11-06T21:22:29.345981+00:00 app[web.1]: [INFO] org.jhipster.book.config.WebConfigurer - Web application configuration, using profiles: [prod, heroku]
2015-11-06T21:22:29.346119+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.WebConfigurer - Initializing Metrics registries
2015-11-06T21:22:29.363814+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.WebConfigurer - Registering Metrics Filter
2015-11-06T21:22:29.371840+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.WebConfigurer - Registering Caching HTTP Headers Filter
2015-11-06T21:22:29.386895+00:00 app[web.1]: [INFO] org.jhipster.book.config.WebConfigurer - Web application fully configured
2015-11-06T21:22:29.364191+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.WebConfigurer - Registering Metrics Servlet
2015-11-06T21:22:29.379689+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.WebConfigurer - Registering static resources production Filter
2015-11-06T21:22:30.711883+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.HerokuDatabaseConfiguration - Configuring Heroku Datasource
2015-11-06T21:22:34.761667+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.DatabaseConfiguration - Configuring Liquibase
2015-11-06T21:22:34.817362+00:00 app[web.1]: [WARN] org.jhipster.book.config.liquibase.AsyncSpringLiquibase - Starting Liquibase asynchronously, your database might not be ready at startup!
2015-11-06T21:22:40.263208+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.liquibase.AsyncSpringLiquibase - Started Liquibase in 5444 ms
2015-11-06T21:22:43.751662+00:00 app[web.1]: [WARN] org.hibernate.cache.ehcache.AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.jhipster.book.domain.Tag]; using defaults.
2015-11-06T21:22:43.818978+00:00 app[web.1]: [WARN] org.hibernate.cache.ehcache.AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.jhipster.book.domain.Entry]; using defaults.
2015-11-06T21:22:43.869261+00:00 app[web.1]: [WARN] org.hibernate.cache.ehcache.AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.jhipster.book.domain.Entry.tags]; using defaults.
2015-11-06T21:22:43.782958+00:00 app[web.1]: [WARN] org.hibernate.cache.ehcache.AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.jhipster.book.domain.Blog]; using defaults.
2015-11-06T21:22:43.833934+00:00 app[web.1]: [WARN] org.hibernate.cache.ehcache.AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.jhipster.book.domain.Tag.entrys]; using defaults.
2015-11-06T21:22:43.891906+00:00 app[web.1]: [WARN] org.hibernate.cache.ehcache.AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.jhipster.book.domain.Blog.entrys]; using defaults.
2015-11-06T21:22:52.258607+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.CacheConfiguration - Starting Ehcache
2015-11-06T21:22:52.262062+00:00 app[web.1]: [DEBUG] org.jhipster.book.config.CacheConfiguration - Registering Ehcache Metrics gauges
2015-11-06T21:22:53.250590+00:00 app[web.1]: [INFO] org.jhipster.book.Application - Running with Spring profile(s) : [prod, heroku]
2015-11-06T21:22:54.305764+00:00 app[web.1]: [INFO] org.jhipster.book.config.ThymeleafConfiguration - loading non-reloadable mail messages resources
2015-11-06T21:23:02.404846+00:00 heroku[web.1]: State changed from starting to up
2015-11-06T21:23:02.432577+00:00 app[web.1]: [INFO] org.jhipster.book.Application - Access URLs:
2015-11-06T21:23:02.432329+00:00 app[web.1]: [INFO] org.jhipster.book.Application - Started Application in 64.534 seconds (JVM running for 83.325)
2015-11-06T21:23:02.432579+00:00 app[web.1]: ----------------------------------------------------------
2015-11-06T21:23:02.432580+00:00 app[web.1]: 	Local: 		http://127.0.0.1:42693
2015-11-06T21:23:02.432581+00:00 app[web.1]: 	External: 	http://172.16.251.70:42693
2015-11-06T21:23:02.432581+00:00 app[web.1]: ----------------------------------------------------------
```

**Comment by jkutner** [comment]
Oh New Relic, yea that's a killer. I'm going to reach out to the folks who develop the agent and see if we can improve it.

**Pull request merged**
