### PR TITLE
fix javadoc error

### PR DESCRIPTION
**Pull request by rabiori**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by rabiori** [comment]
Can someone explain why the Travis is failing?

**Comment by pascalgrimaud** [comment]
random failures
Just restarted the build

**Comment by rabiori** [comment]
thank you very much

**Comment by rabiori** [comment]
@pascalgrimaud it seems to have failed again...

**Comment by pvliss** [comment]
Restarted it once more

**Comment by rabiori** [comment]
@pvliss ty ty

**Comment by pvliss** [comment]
Thank you for your first contribution @rabiori

**Comment by rabiori** [comment]
welcome :)

**Pull request merged**
