### PR TITLE
fix datetime picker for zoned datetime

### PR DESCRIPTION
**Pull request by deepu105**
I have used a [directive wrapper](https://github.com/Gillardo/bootstrap-ui-datetime-picker)  for ui-bootstrap datepicker and timepicker, there is no cleaner way to do this unless we switch from uib-bootstrap altogether which doesnt seem worth it.

also upgraded to latest ui-bootstrap. 
put in some tweaks to make the calender look better
fix https://github.com/jhipster/generator-jhipster/issues/2537

### CODE REVIEW

**Comment by deepu105** [comment]
demo-date

**Comment by deepu105** [comment]
@moifort what program do you use to capture gif from screen? I was trying few but they aren't that good and I forgot what I was using sometime back

**Comment by moifort** [comment]
I have a mac, I use LICEcap, it’s very ugly, but it’s far the best (for me)

**Comment by deepu105** [comment]
thanks, I tried its better than what i used :)

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@jhipster/developers does any one have any objections? if not ill merge this

**Comment by mraible** [comment]
+1

**Comment by pascalgrimaud** [comment]
+1

**Comment by deepu105** [comment]
@jdubois @atomfrede @gmarziou are you guys ok with this?

**Comment by jdubois** [comment]
No time to test, but the video is cool and the lines of code are small -> let's do it!

**Pull request merged**
