### PR TITLE
Improved user management

### PR DESCRIPTION
**Pull request by gzsombor**
Couple of fixes for the user management:
 - add ability to change the password of the user
 - fix adding, and removing roles from the user - caution was taken to avoid removing ROLE_USER
 - localization of the roles
 - couple of helper methods added to User, Authority
etc

### CODE REVIEW

**Comment by deepu105** [comment]
@gzsombor i dont like the localization of role names, it makes it even more

**Comment by deepu105** [comment]
@gzsombor sorry i accidentally closed this. Have reopened

I kind of dont like the localization of role names it makes it even more tightly coupled and hard wired into code so if we decide to implement a dynamic role management this would be difficult to tackle. I feel that the role names should be left as it is

**Comment by gzsombor** [comment]
Yes, the current naming is misleading, based on wikipedia : https://en.wikipedia.org/wiki/Role-based_access_control . Because which JHipster - and Spring does, is checking and validating permissions, and not roles. Role is a group of low-level permissions. I would be very happy, if we could move from the current user - authority structure to a more generic user - role (with subject) - permission structure. But until then, believe me, you don't want to give a UI to users, where they can see strings like 'ROLE_X_Y_Z' instead of a more human friendly 'Manage A and B'.

**Comment by deepu105** [comment]
Ok the entire role thingy needs improvement anyway so until thats its fine
i guess. Once the user management is released lets start discussing on how
the roles can be done. Ill open an issue and post what I have done
currently there and we can discuss for alternate ideas improvements etc
there

**Comment by jdubois** [comment]
I'm sorry but in the PR there is a new mapper, and a PageDTO, so that's a lot of new common stuff, we should discuss this first.
I don't think they are needed here, the current code is close to being OK without it.

**Comment by jdubois** [comment]
I've copied some parts of this in the code I'm going to push, so I'm closing this.

I still need to work on the authorities, and copy what you did here, by the way.

**Pull request closed without merging**
