### PR TITLE
Migration from Joda Time to Java 8 Time

### LINKED ISSUE #1158: Use Java 8 Date Time API instead of JodaTime
If Java 8 is selected as Java runtime, it it better to use Java 8 Date API(JSR310) instead of the joda.

There some some points needs to be aligned with Java 8 and JSR310.

1. Spring date conversion and formatting by conversion service and @DateFormat
2. Jackson JSON desearialization and serialization should be compatible with AngularJS date filter.
3. JPA  Date conversion which can be done by JPA 2.1 @Convertor

### PR DESCRIPTION
**Pull request by deepu105**
Migration from Joda Time to Java 8 Time

opening on behalf of @ygrenzinger

Fix #1158

### CODE REVIEW

**Comment by ygrenzinger** [comment]
I cross finger. Another 2 hours doing some git rebase --continue.

**Comment by ygrenzinger** [comment]
Sadly there is a bug remaining in the Entity generation for "DateTime"

**Comment by ygrenzinger** [comment]
@deepu105 this commit seems to be the last one.

I have invested lots of time in this pull request (merge is not easy) so hope it will do the work !

**Comment by ygrenzinger** [comment]
LocalDate use a Date object on browser/JS side and I don't think if it's the best option. I think we can have TimeZone mindfuck and a simple yyyy-MM-dd could be simpler. 

But I have keeped the Date and used an OFFSET_DATETIME formatter to deserialize on the Java side.

**Comment by ygrenzinger** [comment]
As soon the pull request is accepted, I think there is some improvement to do (like maybe removing totally jadira or some Jackson annotation)

**Comment by jdubois** [comment]
@ygrenzinger unfortunately we are blocked until we keep Java 7 support -> this is becoming really an issue, I'm going to propose to make it EOL with the next release

**Comment by deepu105** [comment]
:+1: @jdubois may be you can provide a java 7 maintenance branch for fixes for those who still use it

**Comment by ygrenzinger** [comment]
@jdubois I am glad to help and provide feedback as I have finished a project with JHipster and Java 8.

However every merge with yeoman generation scripts seems to be painful and error prone :(

**Comment by jdubois** [comment]
@ygrenzinger that would be great! Hopefully we should suppress Java 7 in September, we'll see what the stats are after the holidays.

**Comment by afedulov** [comment]
@jdubois, sorry, I might not be aware of something already thoroughly discussed: is support for Java 7 planned to be dropped?

**Comment by jdubois** [comment]
@adejanovski it will of course be dropped at some point, but I don't know when yet. I'm working full time for a client at the moment, and such a big migration can't be done without me working a couple of weeks on the project.
Anyway, I don't recommend using Java 7!

**Comment by jdubois** [comment]
I just merged it at https://github.com/jhipster/generator-jhipster/commit/b102b1c3c3c0ce5c06e497fba95acf7f6e7eef45

-> I don't know why this isn't marked as "merged"... I did a "stash", I hope it didn't mess up the Git process!!

**Pull request closed without merging**
