### PR TITLE
Updated the JCore dep to v1.4.1

### LINKED ISSUE #6779: Exporting/importing a JDL file loses the "jpaMetamodelFiltering" property
I have a model with  "jpaMetamodelFiltering": true

When I export jdl (jhipster export-jdl model.jdl) after import the file generated (jhipster import-jdl model.jdl) I expected that the same code and  the same definitions in .jhipster\file.json. But it's not true  all files contem  "jpaMetamodelFiltering": false,
but the correct is  "jpaMetamodelFiltering": true

### PR DESCRIPTION
**Pull request by MathieuAA**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X] Tests are added where necessary
- [X] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Hopefully fixes #6779 

It seems the `package-lock` file was not updated in a short while...

### CODE REVIEW

**Comment by MathieuAA** [comment]
It seems some builds fail, I'll look into it tomorrow

**Comment by pascalgrimaud** [comment]
@MatthieuAA : no worry about failed builds. It's not related to your PR

**Comment by MathieuAA** [comment]
@pascalgrimaud I'm not sure about that. The failed tests are pretty clear. Anyway, I'm closing this one. I have to release another version for Gael's issue, so I'm going to make another PR.

**Comment by pascalgrimaud** [comment]
Deepu merged accidentally this https://github.com/jhipster/generator-jhipster/pull/6771

It is fixed now by https://github.com/jhipster/generator-jhipster/pull/6784

**Comment by MathieuAA** [comment]
@pascalgrimaud Ok! Well, I'll do my thing, roll a new release for JCore, and submit a PR.
If my tests fail again, I'm blaming you ;)

**Pull request closed without merging**
