### PR TITLE
Added Elasticsearch properties

### PR DESCRIPTION
**Pull request by bonhamcm**
Added Elasticsearch properties to remove the root-level data directory

See https://github.com/jhipster/generator-jhipster/pull/1713 for discussion.

### CODE REVIEW

**Comment by jdubois** [comment]
I'm sorry but I don't agree:

- By default we don't configure this -> we always use the default configuration for each third-party lib, unless it creates a serious issue. Here, by default, you will use an external ES instance, which looks good to me in production.
- In "dev" mode, we configure it specifically (see the application-dev.yml which does the same thing as you) so we use an in-memory instance (like what we do with H2)

So I would like to leave our configuration the way it is, unless I'm missing something?

**Comment by andidev** [comment]
Okey I agree that this maybe is not the correct solution. But then at least we should add the data dir to gitignore as in #1713 since the data dir will be created in the root of the project when running mvn test.

**Comment by bonhamcm** [comment]
@jdubois Perhaps I was not specific enough that this pull request was changing the Elasticsearch properties for the ```app/templates/src/test/resources/config/_application.yml``` file that is used during unit tests since that's the root-level ```data``` directory appeared after running ```maven clean install```. Either we move the ```data``` directory underneath ```target``` like this pull request or add it to ```.gitignore``` like in #1713. Or do you have another solution?

**Comment by andidev** [comment]
I'm reopening this and merging it cause of #1853

**Comment by bonhamcm** [comment]
Thank you @andidev !

**Pull request merged**
