### PR TITLE
Add gradle-modernizer-plugin to detect legacy/deprecated API usage

### PR DESCRIPTION
**Pull request by gzsombor**
This plugin is a wrapper around modernizer-maven-plugin, but works in Gradle.
 
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by atomfrede — APPROVED** [review]
Will restart the build. Failing ones are not gradle based.

**Comment by mshima** [comment]
I am just wondering if we dropped Java 8 support with maven change.

**Comment by gzsombor** [comment]
The JAVA_VERSION is already set to 11 here: 
https://github.com/jhipster/generator-jhipster/blob/f2d29b607ee7d66deb7e00cf4c672ceb9f7a63e7/generators/java/constants.cjs#L22

So I guess, we've already required Java 11 to build and run

**Comment by mshima** [comment]
Default is Java 11. But compatible with java 8.
https://github.com/jhipster/generator-jhipster/blob/ec1cd00ca77bb10a7b16334ecf69b76954022b99/generators/java/constants.cjs#L23

But I am neutral to the Java 8 drop.

**Comment by gzsombor** [comment]
I don't thinks JAVA_COMPATIBLE_VERSIONS is used anywhere, so it's not relevant as we set maven-compiler-plugin/target to 11, so you cant compile your app on Java 8 (the java compiler doesn't know the target version), and neither can you run on Java 8 - as the JVM doesn't understand the newer bytecode version.
 So, out of the box, a generated JHipster app already needs Java 11 at least, what has changed, is that it's a bit more work to make it compatible with Java 8.

**Comment by atomfrede** [comment]
Agree, not sure if we have a hard policy. Java 11 by default (see https://github.com/jhipster/generator-jhipster/pull/12021) but it could be used with Java 8, at least that's was the intention. As Java 17 is around the corner I think we could drop the possibility to switch to java 8 without changing some code.

**Comment by mshima** [comment]
> I don't thinks JAVA_COMPATIBLE_VERSIONS is used anywhere

https://github.com/jhipster/generator-jhipster/blob/d2df83756f7aa9c146c0c8fcd022626f5e063bdd/generators/server/templates/pom.xml.ejs#L1353
https://github.com/jhipster/generator-jhipster/blob/d2df83756f7aa9c146c0c8fcd022626f5e063bdd/generators/server/templates/build.gradle.ejs#L58

**Comment by gzsombor** [comment]
> > I don't thinks JAVA_COMPATIBLE_VERSIONS is used anywhere
> 
> https://github.com/jhipster/generator-jhipster/blob/d2df83756f7aa9c146c0c8fcd022626f5e063bdd/generators/server/templates/pom.xml.ejs#L1353
> 
> https://github.com/jhipster/generator-jhipster/blob/d2df83756f7aa9c146c0c8fcd022626f5e063bdd/generators/server/templates/build.gradle.ejs#L58

Yes, that's what I'm talking about, the JAVA_COMPATIBLE_VERSIONS variable is not used anywhere, the maven-enforcer-config and the gradle config are hard coded

**Pull request merged**
