### PR TITLE
Define a constant instead of duplicating this literal "You have misco…

### PR DESCRIPTION
**Pull request by sgrillon14**
…nfigured your application! " 3 times.

SONAR: Duplicated string literals make the process of refactoring error-prone, since you must be sure to update all occurrences. On the other hand, constants can be referenced from many places, but only need to be updated in a single place.

### CODE REVIEW

**Comment by jdubois** [comment]
C'mon, this is a log message, so there is no risk with this text String. We have 1 more line of code for nothing, and it's harder to understand...

**Comment by deepu105** [comment]
@sgrillon14 was there a warning from sonar on this?

**Comment by sgrillon14** [comment]
I use Sonar on my JHipster application. I take advantage of the information sent by Sonar to cleaning the code generated by the generator. I have often met people who critique this generator by saying that the code generated is not clean. I think that the generated code is already well , I wanted remove errors found by Sonar these pernonnes not criticize the generator.

**Comment by deepu105** [comment]
Ok, I guess since this doesnt cause any issue we could merge

**Comment by cbornet** [comment]
LOL It's because there is a "+" between the log strings to make them multiline. Otherwise the log Strings would have been different...
On the other hand I must say I like to have a 0 sonar issue code.

**Comment by jdubois** [comment]
Having a big laugh at people criticizing the "non clean code" of the generator for this specific use-case: if they can't read code, and can't think for themselves, they should better do another job!!!
I could just modify the String and Sonar wouldn't see anything anymore... That's so easy to trick Sonar, anybody should understand it's just a tool, and without a human with a brain to understand the code, its reports are useless.

**Comment by deepu105** [comment]
@jdubois so what to do with this PR?

**Comment by jdubois** [comment]
let's just change the String, so that everyone is happy in the end...

**Comment by deepu105** [comment]
The log messages are already different, I dont know why this gives Sonar warning in the first place

**Comment by deepu105** [comment]
@sgrillon14 Thanks and Sorry

**Comment by deepu105** [comment]
I changed the string

**Pull request closed without merging**
