### PR TITLE
#6169 Fixed annotation processors in IntellIj

### LINKED ISSUE #6169: Running gradle application by IntellIj
##### **Overview of the issue**

When I run application (jHipster) by command linie (gradlew) everything is working but when I try run application with IntellIJ (by button).  For this same error I can't run unit test in IDE. 
My sample project with this error in github: https://github.com/Patresss/jHipster

##### **Motivation for or Use Case**

I want to run my application by IntellIj and run unit test

##### **Reproduce the error**

```
2017-07-24 21:43:13.313 DEBUG 4312 --- [  restartedMain] c.e.c.E.p.t.d.S.preferredDivisions       : Close successful.
2017-07-24 21:43:13.493 ERROR 4312 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in com.patres.timetable.service.DivisionService required a bean of type 'com.patres.timetable.service.mapper.DivisionMapper' that could not be found.


Action:

Consider defining a bean of type 'com.patres.timetable.service.mapper.DivisionMapper' in your configuration.


Process finished with exit code 0
```

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/4315
https://github.com/jhipster/generator-jhipster/issues/5748

##### **Suggest a Fix**

I thing that is a problem with mapstruct but I have no idea how to fix it.
##### **JHipster Version(s)**

4.6.2

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.patres.timetable",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.2",
    "baseName": "Test",
    "packageName": "com.patres.timetable",
    "packageFolder": "com/patres/timetable",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "18817051906d7b75a7c8c96ac82de44228e55742",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "pl"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
entity Division {
    name String required,
    shortName String,
    numberOfPeople Long,
    colorBackground String,
    colorText String
}

paginate all with pagination
service all with serviceClass

dto * with mapstruct
```

##### **Browsers and Operating System**

Windows 10, Google Chrome

- [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by Patresss**
Fixed problem with annotation processors in IntellIj. Now users can run application and unit test by button in IntellIJ,

Added plugin net.ltgt.apt.
see https://plugins.gradle.org/plugin/net.ltgt.apt

Fix #6169

### CODE REVIEW

**Comment by atomfrede** [comment]
Thanks. Will check what happens when using eclipse when I am back from holiday.

**Comment by deepu105** [comment]
Dont we use the plugin already in the mapstruct.gradle file? I didn't check
on my fone now

**Comment by Patresss** [comment]
@deepu105 I can see this plugin in dependencies:
`classpath "net.ltgt.gradle:gradle-apt-plugin:0.9"`
But in my application this is not enough. I have to add this lines to run project in IntellIj:
```
plugins {
    id 'net.ltgt.apt' version '0.9'
}

apply plugin: 'idea'
apply plugin: "net.ltgt.apt"
```

I'm not very familiar with Gradle, but I know this solution works in my project. So it would be better that a person with Gradle's experience look at this solution.

**Comment by deepu105** [comment]
Need to check this

**Comment by atomfrede** [comment]
I am also on mobile only but the apt plugin must be there already otherwise
compilation via command line won't work.

Am 27.07.2017 8:07 vorm. schrieb "Deepu K Sasidharan" <
notifications@github.com>:

> Need to check this
>

**Comment by deepu105** [comment]
@Patresss the plugin is applied in the mapstruct.gradle file and the file is appplied in main gradle.build
`apply from: 'gradle/mapstruct.gradle'`

Probably the difference in behaviour is from applying the `idea` plugin. can you remove
```
plugins {
    id 'net.ltgt.apt' version '0.9'
}
apply plugin: "net.ltgt.apt"
```

and check with just `apply plugin: 'idea'` ?

**Comment by Patresss** [comment]
@deepu105 Yes, You are right. I removed plugin "net.ltgt.apt" and I left only line:
`apply plugin: 'idea'`
It was enough for the application to start properly. I added new commit. Thank You!

**Comment by deepu105** [comment]
@atomfrede merge this if once you check eclipse. LGTM

**Comment by atomfrede** [comment]
Will Check tomorrow.

Am 30.07.2017 11:29 nachm. schrieb "Deepu K Sasidharan" <
notifications@github.com>:

**Comment by deepu105** [comment]
@jhipster/hipsters  Guys can anyone verify if this works in intelliJ and doesnt cause any issue in eclipse? I'm bit occupied with other stuff

**Comment by atomfrede** [comment]
I will try it this evening. But in another project I added both idea and
eclipse plugin and it works just fine for me using idea and a friend using
eclipse. But will try it with jhipster master branch.

Am 06.08.2017 12:01 nachm. schrieb "Deepu K Sasidharan" <
notifications@github.com>:

**Comment by atomfrede** [comment]
I applied both plugins (eclipse and idea) and could import and run the app from both ides without any problems. I also updated the apt plugin for gradle to the latest version, but I can do another PR for that.

**Comment by deepu105** [comment]
Ok lets do it then

**Pull request merged**
