### PR TITLE
Remove CustomParameterizedException

### PR DESCRIPTION
**Pull request by cbornet**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

You can achieve the same functionality as CustomParameterizedException with a Problem exception. Eg:

```java
throw Problem.builder()
                .withStatus(Status.BAD_REQUEST)
                .with("param0", "param0_value")
                .with("param1", "param1_value")
                .build();
```
so I propose to remove CustomParameterizedException as per Policy 2.

### CODE REVIEW

**Comment by PierreBesson** [comment]
@cbornet You should add some info in the docs here by completing this page : https://www.jhipster.tech/managing-server-errors/

**Comment by DanielFran** [comment]
@cbornet Maybe you can add a test with an example?

**Comment by cbornet** [comment]
That would be testing the Problem lib which already has its own tests. Not sure it has a lot of value...

**Comment by DanielFran** [comment]
ok, was just thinking about the migration, so people have an example... otherwise I am fine with the documentation update that should include an example.

**Comment by jdubois** [comment]
Thanks @cbornet and anyway this kind of code should be in the framework, not generated

**Pull request merged**
