### PR TITLE
Mark created_date as non updatable

### PR DESCRIPTION
**Pull request by andreasfranz**
Mark created_date as non updatable, since it should never be changed after initial creation

### CODE REVIEW

**Comment by andreasfranz** [comment]
Could someone please advise me why the Travis checks failed? Following the steps in the documentation they run on my local machine.

**Comment by jdubois** [comment]
I just looked at the first failed build, it looks like you have a JUnit error in `io.github.jhipster.sample.service.UserServiceIntTest` - do you know how to execute the Travis tests on your machine?

**Comment by cbornet** [comment]
It’s because one of the tests needs to update the creation date

**Comment by andreasfranz** [comment]
@cbornet Thanks for the info, but it sounds kind of strange to me that the only reason to not mark it as `updatable=false` is a test.

**Comment by deepu105** [comment]
If you can find another way to test it then we can merge this. May some
reflection magic or something?

**Comment by jdubois** [comment]
This is really annoying to close this because of a test!!! But indeed I can't find another solution, and the test is important

**Comment by andreasfranz** [comment]
I thought about this again, I think I might have a solution and will try to implement it later.

**Comment by jdubois** [comment]
I'm closing this as this has been stuck for 3 weeks and isn't very important - but that's definitely stupid to make it updatable only for tests!!

**Comment by cbornet** [comment]
One way to do it could be to create a dedicated class to get the current time that is overridden during tests. Not too hard to do I think.

**Pull request closed without merging**
