### PR TITLE
Tasks that executes with the ExceptionHandlingAsyncTaskExecutor are not being wrapped - fixed #2714

### LINKED ISSUE #2714: ExceptionHandlingAsyncTaskExecutor  execute is not wrapping the task
The execute is not wrapping the task with the exception handling:

Should be:
```
@Override
    public void execute(Runnable task) {
        executor.execute(createWrappedRunnable(task));
    }
```

### PR DESCRIPTION
**Pull request by ezraroi**
[Review on Reviewable](https://reviewable.io/reviews/jhipster/generator-jhipster/2715)

### CODE REVIEW

**Comment by jdubois** [comment]
Can you write a real title describing what this is doing ?

**Comment by ezraroi** [comment]
This method:
```
@Override
    public void execute(Runnable task) {
        executor.execute(task);
    }
```

Is not using the wrapper that catches all exceptions during task execution

**Comment by jdubois** [comment]
Yes, we need to discuss this on the ticket, but still the PR must have a title that explains what it does.

**Comment by jdubois** [comment]
OK I still need to check if this class is useful, but I'm trusting you for the wrapper!

**Pull request merged**
