### PR TITLE
Add on option to report actuator metrics in the logs

### PR DESCRIPTION
**Pull request by PierreBesson**
The goal is to retrieve useful metrics that are not already reported by Dropwizard metrics. It will be especially useful for retrieve circuit breakers metrics.

I tried to make this as simple as possible. I'm not a big fan of my "exclusion list" but I don't see a better way.

### CODE REVIEW

**Comment by gmarziou** [comment]
> I'm not a big fan of my "exclusion list" but I don't see a better way.

I'm a bit confused by these 2 sources of metrics, we have those coming from dropwizard and these coming from actuator, the 2 lists overlap.
Your approach is to build an exclusion list to exclude from actuator the ones that are already reported by dropwizard, shouldn't it be the opposite as actuator is the spring boot standard?

**Comment by cbornet** [comment]
Actually, the spring-cloud metrics should use dropwizard when detected on the classpath but it doesn't seem to be the case.
As for the exclusion, maybe we need to find (write?) a metric reader more appropriate than the MetricsEndpointMetricReader

**Comment by cbornet** [comment]
@PierreBesson Since you initially want metrics from Spectator, can you try replacing MetricsEndpointMetricReader by SpectatorMetricReader ?

**Comment by cbornet** [comment]
And probably you need to annotate the SpectatorMetricReader bean  as @ExportMetricReader

**Comment by cbornet** [comment]
@gmarziou I finally understood ! All dropwizard metrics are exported to public metrics so we just need to deactivate (remove) the dropwizard's slf4jreporter and not filter on the public metrics. This way we get more metrics so :+1: for me

**Comment by cbornet** [comment]
We could also prepare some support for the other exporters available in SB (statsd, redis, openTSDB, JMX) instead of the dropwizard's reporter (graphite, spark)

**Comment by gmarziou** [comment]
@cbornet Awesome!

**Comment by cbornet** [comment]
Arf ! Just saw an issue in this plan : dropwizard's TIMER metrics will be split in multiple metrics so this will generate much more logs...

**Comment by PierreBesson** [comment]
@gmarziou I share your concern for the loss of performance of this solution.

Actually, the issue is that spring boot actuator metrics and dropwizard metrics don't have the same format and don't do the same thing. Dropwizard being the more complete solution, we should not move away from it.
Actuator metrics are are less complete than dropwizard metrics, supporting only COUNTER and GAUGE and not TIMER and HISTOGRAM as those are Dropwizard specific.

For Actuator metrics, logging reporting of the metrics coming from dropwizard is too naive, which result in too many logs. They are not really designed to be reported through the logs. I think they want you to access them through the `/metrics` endpoint with some query to filter them. Hence why they are organised hierarchically.

**Comment by PierreBesson** [comment]
@cbornet Using SpectatorMetricReader is working !
If no one object, I will switch my PR to report only metrics from Spectator Metrics. So it will only be for microservices.
Too bad, we won't have Public Metrics but they are not really needed for us because we already have dropwizard metrics.

@cbornet, Yes spring boot have other exporters but I think that those are not as good as passing through logstash which already have many output plugins.

**Comment by PierreBesson** [comment]
As we have decided not to report all metrics from the endpoint, I'm closing this PR and opening a new one that concerns only Circuit Breakers metrics for microservices and gateways.

**Pull request closed without merging**
