### PR TITLE
Fix Backslashes in validation patterns are not escaped in 'translateValues'

### LINKED ISSUE #4966: Backslashes in validation patterns are not escaped in `translateValues`
##### **Overview of the issue**

Backslashes in validation patterns are not escaped in the `translateValues` causing an unrecoverable client-side error.

##### **Motivation for or Use Case**

Add a valid pattern to a field, here a "non blank" pattern.

##### **Reproduce the error**

1. Generate an entity X with the validation pattern `^.*[\\S]+.*$` (see attachment below)
2. Open the `Create a new X` dialog
3. A JavaScript error is raised and all translated texts are blank 

##### **Related issues**

n/a

##### **Suggest a Fix**

The associated input field has a generated `translateValues="{ pattern: '^.*[\S]+.*$' }"` which is wrong: it should be `translateValues="{ pattern: '^.*[\\S]+.*$' }"` with 2 backslashes.

##### **JHipster Version(s)**

Master branch, commit 16e2184748a39d300bae2eaeb57856e4650d0370

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

[yo-rc.json](https://github.com/jhipster/generator-jhipster/files/730281/yo-rc.json.zip)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

[Platform.json](https://github.com/jhipster/generator-jhipster/files/730286/Platform.json.zip)

##### **Browsers and Operating System**

Chrome

### PR DESCRIPTION
**Pull request by ddidier**
Fix #4966

### CODE REVIEW

**Comment by jdubois** [comment]
Oh thanks @ddidier !!
I'm merging this now, as I was just testing the issue, so it's going to be easy for me to validate

**Comment by jdubois** [comment]
@ddidier not sure it works.... Now I can write anything in my field, like "toto". Can you check?

**Comment by jdubois** [comment]
@ddidier in fact `^.*[\\S]+.*$` forces me to write an `S`, and I think what you meant is that no whitespace should be validated.

**Comment by ddidier** [comment]
@jdubois not sure I understand. My goal is to force the field to be NOT blank, so yes, `toto` is valid.
The double backslash `^.*[\\S]+.*$` is only for the translation parameter, not the validation itself which remains single `^.*[\S]+.*$`. Thank you.

**Comment by jdubois** [comment]
Oh OK that should be fine, thanks @ddidier

**Pull request merged**
