### PR TITLE
[angular] Polish file and class names in Angular part

### LINKED ISSUE #10220: Polish file and class names in Angular part
##### **Overview of the issue**

Issues I discovered when refactoring imports in Angular part (barrel remove in #10185):

* inconsistent component and service class prefixes: components and services are mainly without prefix, but some of them have prefix `<%=jhiPrefixCapitalized%>`: `AlertErrorComponent`, `AlertComponent`, `ConfigurationComponent`, `ConfigurationService`, `DocsComponent`, `GatewayComponent`, `HealthModalComponent`, `HealthCheckComponent`, `HealthService`, `LoginModalComponent`, `MainComponent`, `MetricsMonitoringComponent`, `MetricsService`, `TrackerComponent`, `TrackerService`  
Why such difference? I think it would be good practice to use one style, so 2 possible solutions:
    * either remove prefix `<%=jhiPrefixCapitalized%>` from all components and services
    * or add prefix `<%=jhiPrefixCapitalized%>` to all components and services

* modules are prefixed differently, with prefix `<%=angularXAppName%>`, why this prefix is different, maybe use the same prefix `<%=jhiPrefixCapitalized%>` as used in components and services? If prefix will be removed from all components and services then this inconsistency will disappear, then only prefix `<%=angularXAppName%>` remains in use and this is not the case any more.

* as standard, service files have suffix `.service.ts`, but one file is different: `user-route-access-service.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/auth/user-route-access-service.ts.ejs - dash instead of point before service), suggestion: rename this file to `user-route-access.service.ts`

* some class or file names doesn't follow general name convention:
    * register service class name is `Register` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/account/register/register.service.ts.ejs#L26), suggestion: rename this class to `RegisterService` (other service classes are ending with suffix Service)
    * in `health.component.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/admin/health/health.component.ts.ejs#L29) class name is `HealthCheckComponent`, suggestion: rename this to `HealthComponent`
    * in `metrics.component.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/admin/metrics/metrics.component.ts.ejs#L28) class name is `MetricsMonitoringComponent`, suggestion: rename this to `MetricsComponent`
    * better name for file `errorhandler.interceptor.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/errorhandler.interceptor.ts.ejs#L26) is `error-handler.interceptor.ts` (class name inside this is `ErrorHandlerInterceptor`)
    * in file `auth-jwt.service.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/auth/auth-jwt.service.ts.ejs#L31) class name is `AuthServerProvider`, suggestion: rename class to `AuthJwtService`
    * in `langauge.helper.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/language/language.helper.ts.ejs#L31) class name is `JhiLanguageHelper`, suggestion: rename class to `LanguageHelper`
    * in `login.component.ts` (https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/shared/login/login.component.ts.ejs#L32) class name is `LoginModalComponent`, suggestion:
        * change `login.component.ts` to `login-modal.component.ts`
        * change `login.component.html` to `login-modal.component.html`

##### **Motivation for or Use Case**

Using unified style makes code better readable and avoids confusions why some files or classes are named not logically.

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #10220 

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mshima** [comment]
Must cleanup every renamed file.

**Comment by qmonmert** [comment]
> Must cleanup every renamed file.

@mshima I don't understand, can you show me an example ?

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/blob/0b1b36e6d4c1ac50af278ad2e873f5b88a02b475/generators/cleanup.js#L112-L113
Remove renamed files for upgrades.

**Comment by qmonmert** [comment]
> https://github.com/jhipster/generator-jhipster/blob/0b1b36e6d4c1ac50af278ad2e873f5b88a02b475/generators/cleanup.js#L112-L113
> 
> 
> Remove renamed files for upgrades.

@mshima yes @pascalgrimaud explain to me :)

**Comment by qmonmert** [comment]
@mshima do you think that you can merge this PR ? :)

**Comment by mshima** [comment]
Unless the team decides otherwise, you should use `removeFile`.
`renameFile` uses git mv, it was implemented due to a broken git state at case insensitive filesystem, caused by `en-us` => `en-US`.
We don’t do git operations if not required.
Would be great if you could rename `renameFile` to `gitMoveFile`.

**Comment by qmonmert** [comment]
@mshima is it ok if I use removeFile otherwise renameFile ?

**Comment by mshima** [comment]
> @mshima is it ok if I use removeFile otherwise renameFile ?

You should use `removeFile` instead of `renameFile`.

**Comment by qmonmert** [comment]
> > @mshima is it ok if I use removeFile otherwise renameFile ?
> 
> You should use `removeFile` instead of `renameFile`.

@mshima done :)

**Comment by mshima** [comment]
@qmonmert looks good to me, but I will let an angular expert merge it.

**Comment by qmonmert** [comment]
> @qmonmert looks good to me, but I will let an angular expert merge it.

@mshima ok

**Comment by qmonmert** [comment]
@avdev4j if @wmarques is not available, we can ask @chrisdns maybe ?

**Comment by avdev4j** [comment]
I've added @chrisdns (aka the "BG") for a review

**Comment by chrisdns** [comment]
seems good to me 👍

**Comment by qmonmert** [comment]
@avdev4j you can merge ?

**Comment by mshima** [comment]
@qmonmert can you take a look at https://github.com/hipster-labs/jhipster-daily-builds/runs/960500583?check_suite_focus=true, seems related.

**Comment by qmonmert** [comment]
@mshima indeed it's a bug, I made a PR https://github.com/jhipster/generator-jhipster/pull/12220

**Pull request merged**
