### PR TITLE
update to ejs 2 3 4 space and tab slurp support

### PR DESCRIPTION
**Pull request by andidev**
Refactored some code to use `<%_ _%>` space/tap/line slurp

### CODE REVIEW

**Comment by andidev** [comment]
Would be nice to merge this as soon as possible to avoid messy merge conflicts

**Comment by atomfrede** [comment]
I can't create new projects anymore. When removing `_`  everything works fine. Do I need to update anything?

``
SyntaxError: Unexpected token if in /home/fred/git/generator-jhipster/app/templates/_bower.json while compiling ejs``

**Comment by gzsombor** [comment]
I've noticed the same, I had to upgrade with npm, probably you can try it as well.

**Comment by andidev** [comment]
Sorry next time I'll mention this since this seem to occur each time a node dependency is added or updated. 

npm install in the generator-jhipster project will probably fix your issues as gzombor mentions.

**Comment by atomfrede** [comment]
No problem, I assumed some npm problem. Will try it later and also adapt the gradle build files to the new syntax.

**Pull request merged**
