### PR TITLE
Make entity angular controllers and router ui states more unique to avoid name clashes

### LINKED ISSUE #2645: Make entity angular controllers and router ui states more unique to avoid name clashes
* **Overview of the issue and Motivation for or Use Case**

When generating an entity, lets say Workplace, the following angular controllers are generated for the entity views:
```
WorkplaceController
WorkplaceDeleteController
WorkplaceDetailController
WorkplaceDialogController
```

The ui router state used is `workplace`.

This is a problem when I would like to create general page representing a Workspace. Then the WorkplaceController and the ui router state `workplace` is occupied.

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
 ```
{
    "relationships": [],
    "fields": [],
    "changelogDate": "20160118060622",
    "dto": "no",
    "service": "no",
    "pagination": "no"
}
```

* **Suggest a Fix**

Change the name of the controllers to

 ```
EntityWorkplaceController
EntityWorkplaceDeleteController
EntityWorkplaceDetailController
EntityWorkplaceDialogController
```

and ui router state to: `entity.workplace`.

### PR DESCRIPTION
**Pull request by andidev**
fix #2645

### CODE REVIEW

**Comment by deepu105** [comment]
Ci builds are failing

**Comment by deepu105** [comment]
@andidev with this you can remove the Jhipster reserved keywords as they were added to prevent route clash, since you are changing entity routes here it will not clash with existing Jhipster routes and hence no need to prohibit those names for entity

**Comment by andidev** [comment]
JHipster reserved keyworks removed.

I'll fix merge conflicts later today.

Where can I find the CI build entity tests? Did not manage to find them anywhere.

**Comment by cbornet** [comment]
@andidev  [Here](https://github.com/jhipster/generator-jhipster/tree/master/travis/samples)

**Comment by jdubois** [comment]
We have lots of CI issues at the moment, Travis looks to have problem -> don't worry too much, I'll run force the tests to run again and if you have a real bug I will post a comment

**Comment by andidev** [comment]
There is a real bug here I'll fix it later. For some reason the test-entity.js file is missing in my master branch and I thereby forgott to adjust the tests.

**Comment by andidev** [comment]
So this is ready to be merged now. Please review it when time allows.

**Pull request merged**
