### PR TITLE
Global enum

### LINKED ISSUE #12407: Vue: global enum
##### **Overview of the issue**

Similar to what was done for Angular, the enum should be global for Vue applications too, instead of beeing duplicated in each entities

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/9920
https://github.com/jhipster/generator-jhipster/pull/10015

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #12407 

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
LGTM.
`enum.model.ts.ejs` looks identical at the 3 frameworks.
I am wondering if we should put it inside common for a better convergence.

**Comment by qmonmert** [comment]
> LGTM.
> `enum.model.ts.ejs` looks identical at the 3 frameworks.
> I am wondering if we should put it inside common for a better convergence.

@mshima maybe we can merge this PR and try that in an other PR :)

**Comment by mshima** [comment]
I will let someone review vue code and merge.

**Comment by qmonmert** [comment]
> LGTM.
> `enum.model.ts.ejs` looks identical at the 3 frameworks.
> I am wondering if we should put it inside common for a better convergence.

@mshima I did what you said :)

**Comment by mshima** [comment]
@qmonmert thanks.
The vue code looks right and the tests are passing, merging.

**Comment by mshima** [comment]
Just forgot, let’s trigger angular/react ci.

**Pull request merged**
