### PR TITLE
skip serverSideOptions prompt if no choices are available

### PR DESCRIPTION
**Pull request by ruddell**
Trying to select an option fails (no options are available) when generating:
 - A UAA microservice with no database
 - A JWT microservice with MongoDB

### CODE REVIEW

**Comment by jdubois** [comment]
- don't merge this: there will soon be a new option for everyone, Kafka !
- there's a bug somewhere: jwt + MongoDB should have the Elasticsearch
option

Let me have a look.

Le 19 sept. 2016 10:39 PM, "Jon Ruddell" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
@jdubois merging this should be ok in either case as it will not impact addition of kafka question. Anyway ill let you decide it

**Comment by jdubois** [comment]
@deepu105 yes I'm more worried that the ES option does not show up for JWT + MongoDB

**Comment by jdubois** [comment]
Turns out we don't support MongoDB + Elasticsearch. Shouldn't be hard to do, I don't know why...
Anyway -> I'm going to have a look at merging this and adding Kafka at the same time, so not sure about what will end up here.

**Comment by deepu105** [comment]
Ya thats something else we need to look at. Let me check the conditions
later

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
- OK so the current check is correct
- I still have an edge case with Kafka where I need this

-> I'm merging it

**Pull request merged**
