### PR TITLE
Migrate options to camel case only.

### PR DESCRIPTION
**Pull request by mshima**
Removing kebab case support because:
- We are using camel for some options, kebab for others.
- Probably we are using different case for the same option in different generators.
- commander only generates camel case.
- Its confusing having both cases.
- Camel case is easier to use.

Related to https://github.com/jhipster/generator-jhipster/issues/11896

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@pascalgrimaud no, commander converts `--skip-install` into `skipInstall:true`, only changing the handling.
Cli options keeps intact:
https://github.com/jhipster/generator-jhipster/blob/1dd4804f585c46c104a106be4e1fad713e43554b/test/cli/cli.spec.js#L144-L162

**Comment by pascalgrimaud** [comment]
it's totally perfect so !
thanks @mshima

**Comment by mshima** [comment]
This is required due to complexity involved in having 2 keys for the same config.
@pascalgrimaud the problem is that is a breaking changes for blueprints when they use `this.options['skip-install']` instead of `this.options.skipInstall`.
Maybe we can consider to apply kebab case when composing with blueprints for jhipster 7, to reduce breaking changes, and remove for jhipster 8.

**Comment by pascalgrimaud** [comment]
> This is required due to complexity involved in having 2 keys for the same config.

I totally agree with you. I just asked for documentation, to not forget it, as we'll have a lot of new stuff :)
About breaking change, we can, as it's a major version. We simply need to document it, then it will be ok.

**Pull request merged**
