### PR TITLE
Remove CSS Option

### LINKED ISSUE #8150: Remove the SASS question and remove CSS option
Remove CSS option and provide SASS with CSS support as the default. 
This should be fine for new applications
For upgrading apps, generate SCSS and warn the user to choose between existing CSS or new SCSS files based on their preference

### PR DESCRIPTION
**Pull request by wmarques**
Fixes #8150 
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by fleboulch** [comment]
@wmarques what are the motivations to remove this option?

**Comment by wmarques** [comment]
@fleboulch This was discussed in #8150 .
The motivations are:
* Reduce complexity by generating only one type of stylesheets
* SCSS is far more used, the issues we had with `node-sass` are now resolved by the sass implementation in Dart

**Comment by deepu105** [comment]
May be PR title is misleading

**Comment by wmarques** [comment]
@deepu105 Yep I edited it 😄 
I will probably need some help on the sub-gen part... What do we intend to do? An additional question if the user was using CSS ?

**Comment by fleboulch** [comment]
After updating the title of your PR, I better understand what you want to do (I didn't look at the code but I was just wondering why SCSS would have been removed)!
👍

**Comment by wmarques** [comment]
Hope this will make the tests pass...
I'm going on little vacations so I won't be able to finish it until Tuesday included 😞 

The things that has to be done IMO are:
- Make CI green ofc
- Add `upgrade` sub-gen support to handle version upgrade (don't know if this is needed as it's a major version so a breaking change isn't surprising for me)

If you want to help on this don't hesitate to push on my branch !

**Comment by deepu105** [comment]
We can't handle all upgrade issues for major version so should be ok

**Comment by jdubois** [comment]
I restarted the build but it is still failing, it's weird there's an option with VueJS...

**Comment by wmarques** [comment]
i'm back, let me check this :)

**Comment by wmarques** [comment]
I don't know why the build is failing on a strange timeout error... @jhipster/developers does anyone have a clue on this?

**Comment by DanielFran** [comment]
Restarted the travis job failing...

**Comment by pascalgrimaud** [comment]
The error is real: you could easily reproduce it locally with `npm run test:unit test/upgrade.spec.js`
Looks like it is stuck with these logs:

```
➜ npm run test:unit test/upgrade.spec.js

> generator-jhipster@5.8.2 test:unit /home/pgrimaud/projects/jhipster/generator-jhipster
> mocha --timeout 20000 --slow 0 --reporter spec "test/upgrade.spec.js"



  JHipster upgrade generator
    default application
Generating JHipster application in directory: /tmp/024198a6d2943f8ff14a1b7d4b35461b15dc8169
Upgrading the JHipster application
5.8.2
true
master
Basculement sur la nouvelle branche 'jhipster_upgrade'
npm WARN saveError ENOENT: no such file or directory, open '/tmp/024198a6d2943f8ff14a1b7d4b35461b15dc8169/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/tmp/024198a6d2943f8ff14a1b7d4b35461b15dc8169/package.json'
npm WARN 024198a6d2943f8ff14a1b7d4b35461b15dc8169 No description
npm WARN 024198a6d2943f8ff14a1b7d4b35461b15dc8169 No repository field.
npm WARN 024198a6d2943f8ff14a1b7d4b35461b15dc8169 No README data
npm WARN 024198a6d2943f8ff14a1b7d4b35461b15dc8169 No license field.

+ generator-jhipster@5.8.2
added 513 packages from 330 contributors and audited 3743 packages in 40.8s
found 10 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
/tmp/024198a6d2943f8ff14a1b7d4b35461b15dc8169/node_modules/.bin
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: withEntities: true, force: true, skipInstall: true, skipGit: true, insight: false, from-cli: true, with-entities: true, skip-install: true, skip-git: true


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v5.8.2
Application files will be generated in folder: /tmp/024198a6d2943f8ff14a1b7d4b35461b15dc8169
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...

? Which *Framework* would you like to use for the client? (Use arrow keys)
❯ Angular 
  React
```

**Comment by pascalgrimaud** [comment]
I fixed it with: https://github.com/jhipster/generator-jhipster/pull/9350/commits/cb626ce4efeb4d76e4216de3fff713a81fa70e8f
We need to keep `useSass: true` for now, otherwise, the user won't be able to upgrade their application.

To reproduce the original issue:
- use `v5.8.2` branch
- try to generate the application with this config - `useSass: true/false` is missing:

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ODE5MmQ0ZjQ1NjhkZjY1Nzc1YTMyNWJjNWZkZWZiZDdmZGMwZDZjN2YxYTlhOTRkMDQ0ZDQyYjFlMTJmNDJjMmQxMDQ2NjdiODkzNjJjOWE5ZmM0MzM5ZTljMjhkMzM1OWI5Y2ExYWMzMTUyNzk3NmMxZmNiOGZiNWJhY2YzZWU=",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
```
- you will be stucked at the question:

```
This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...

? Which *Framework* would you like to use for the client? (Use arrow keys)
❯ Angular 
  React 
```

That's the reason why `useSass: true` should still be saved in `.yo-rc.json`.
It can be removed later, once v6 is released :-)

**Comment by wmarques** [comment]
Wow thanks alot @pascalgrimaud !

**Pull request merged**
