### PR TITLE
[React] Start to use Hooks (here in the header)

### PR DESCRIPTION
**Pull request by qmonmert**
Do you think that it will be good to use **Hooks** in React components ?

Here I began to use **useState** and **useEffect** in the file: header.tsx

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
Yes definitely, I think we should progressively migrate to use new features. Would you be willing to do the migration? if so please open a ticket and i'll assign some bounty on it

**Comment by qmonmert** [comment]
@deepu105 yes I'm interested! I join the JHipster team so I will have time :)

**Comment by deepu105** [comment]
Ok please create an issue to track it

**Comment by qmonmert** [comment]
@deepu105 I created the issue #9891

**Pull request merged**
