### PR TITLE
languages adjusts

### PR DESCRIPTION
**Pull request by mshima**
fixes https://github.com/jhipster/generator-jhipster/issues/24125

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
Unfortunately, I don’t have my laptop with me for the weekend, so I'm unable to test this.

**Comment by atomfrede** [comment]
It seems like it's not working. Did

```
gh pr checkout 24181
rm -rf node_modules
npm ci
npm link
```

In sample folder `jhipster` and, selecting `english` as native language, `french` is still selected by default for the additional languages.

I also checked `jhipster --install-path` in the sample folder, it points correctly to my local git clone (`~git/github/jhipster/generator-jhipster/dist`). So maybe I am doing something wrong, but it seems still to be not correct.

**Comment by mshima** [comment]
Should we don't pre-select additional languages?

**Review by mraible — APPROVED** [review]

**Comment by mraible** [comment]
> Should we don't pre-select additional languages?

In previous versions, there were no pre-selected languages. This PR's "selected at the top" logic makes it more obvious. I'm OK with it, but I prefer the old way with no pre-selected.

**Comment by mshima** [comment]
I am slightly inclined to have en/fr as additional languages.
Why?
- this is something configurable though jdl.
- configurable by prompt (only once)
- `jhipster --defaults` shows i18n capabilities by default.

downsides:
- need to select languages in jdl
- need to deselect languages in prompt

Just need to remove these 3 lines:
https://github.com/jhipster/generator-jhipster/blob/80b511d76321beb209e6f4316aa5dce663ac37d9/jdl/jhipster/default-application-options.ts#L167-L169

@DanielFran any opinion?

**Comment by DanielFran** [comment]
@mshima In my opinion, we should not pre-select or only pre-select default system language if that is the case.
I understand it simplifies tests, but the user experience is more important here.

**Review by DanielFran — APPROVED** [review]

**Pull request merged**
