### PR TITLE
Fix missing required validation on relationship on React

### LINKED ISSUE #9128: Missing Required validation on Relationship using React
##### **Overview of the issue**

I created a sample monolithic application with React and when I created a **required** relationship between two entities I noticed that the client is not validating the required field.

##### **Motivation for or Use Case**

It works on angular but not on React.

##### **Reproduce the error**

1. Generate application with configuration given below.
2. Generate the entities and the relationship given below the configuration.
3. Try to create a *Payment* without selecting a *Loan*.

Relationship UI code

##### **Related issues**

Did not found any. 

##### **Suggest a Fix**

We need to put validations in relationships fields as they are in normal inputs.

##### **JHipster Version(s)**

5.8.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.fragmento.pickmykid",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "5.8.0",
    "applicationType": "monolith",
    "baseName": "pickmykid",
    "packageName": "com.fragmento.pickmykid",
    "packageFolder": "com/fragmento/pickmykid",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": ["es"]
  }
}

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Payment {
  date ZonedDateTime required
}
entity Loan {
  externalBankId String unique
}
relationship OneToMany {
  Loan{payment} to Payment{loan required}
}

dto Payment, Loan with mapstruct
paginate Payment, Loan with pagination
service Payment, Loan with serviceClass

</pre>
</details>

##### **Browsers and Operating System**

Mac OS, Happens on all browsers
-   [✅] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by clement26695**
Add required parameter for required relationship

Fix #9128

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by clement26695** [comment]
I also noticed that valiation feedbacks are not shown in React, as we use AvInput and not AvField. Is there a reason to use AvInput instead of AvField ?

**Comment by clement26695** [comment]
Of course !

**Comment by deepu105** [comment]
@clement26695 probably it was missed, feel free to update

**Comment by deepu105** [comment]
also there is a merge conflict

**Comment by clement26695** [comment]
I noticed today that some changes were made that affect this issue. 

I tested once again the issue, and now an error message is displayed in a small pop up now, which says "Validation error on the server".

If I'm correct, all validation is made on the server side. Should I still add the validation on the client side ?

**Comment by ruddell** [comment]
We should still validate required fields in the client for good user experience

**Comment by jdubois** [comment]
Yes we do 2 validations:

- On the server side is the "real" validation: you can't bypass it, and it's usually more advanced
- On the client side it's a "cosmetic" validation: this is for the end-user to have something nice displayed to him

Aside from the package-lock.json conflict this looks good to me - @clement26695 I'm not sure about your last comment, can you do an update on this? Still I'm merging this, so that would be another PR.

**Pull request merged**
