### PR TITLE
adding path as argument to UriComponentsBuilder

### LINKED ISSUE #9690: Broken Link header
##### **Overview of the issue**

The `Link` header in api responses does not include the full base path.

##### **Motivation for or Use Case**

This prevents the use of the header to get the next page of a result set, or number of pages.

##### **Reproduce the error**

Create an app with the following config...
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "",
    "clientFramework": "react",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-swagger-cli",
        "version": "3.0.1"
      },
      {
        "name": "generator-jhipster-audit-helper",
        "version": "1.0.3"
      },
      {
        "name": "generator-jhipster-administration-database",
        "version": "1.0.4"
      },
      {
        "name": "generator-jhipster-jgitver",
        "version": "0.1.0"
      }
    ],
    "enableTranslation": false
  }
}

```
1. Open dev tools
2. Login to a jhipster app.
3. Administration >> User Management
The `Link` header does not include full path.

`Link: <http://localhost:8080?sort=id%2Casc&page=0&size=20>; rel="last",<http://localhost:8080?sort=id%2Casc&page=0&size=20>; rel="first"`

##### **Related issues**

Issues with the Link header have been reported previously, but I believe this particular issue is new due to new usage of UriComponentsBuilder from spring-web to generate this link in jhipster 6.

##### **Suggest a Fix**

Modify io.github.jhipster.web.util.PaginationUtil to get the correct info from UriComponentsBuilder...

However, it looks like org.springframework.web.util.ServletUriComponentsBuilder isn't getting the full path.
`org.springframework.web.util.UrlPathHelper.getPathWithinServletMapping` returns a blank string.

##### **JHipster Version(s)**

6.0.0

##### **JHipster configuration**

Configuration is above

##### **Browsers and Operating System**

MacOS 10.14.4, Google Chrome 74.0.3729.131
-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by duderoot**
according to [spring-projects/spring-framework/#21449](https://github.com/spring-projects/spring-framework/issues/21449)
one need to specify the path

fixes #9690

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
@duderoot have you tired the [solution proposed by @gordolio](https://github.com/jhipster/generator-jhipster/issues/9690#issuecomment-490170584) ? It looks better to me.

**Comment by duderoot** [comment]
@cbornet you are right. The proposal from @gordolio  looks nicer. I will have a look into that tonight

**Comment by cbornet** [comment]
Actually I did another PR supporting both MVC and Webflux and fixing another bug.

**Comment by duderoot** [comment]
@cbornet looks much nicer you solution. I was able to run the application with your solution. I will close this PR.

**Pull request closed without merging**
