### PR TITLE
add more tests to utils.spec.js

### PR DESCRIPTION
**Pull request by kedevked**
adding more tests to utils.spec.js

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by kedevked** [comment]
@deepu105, you can cancel the merge and I will do another one with a good name

**Comment by deepu105** [comment]
No need to do another, just edit the title from the PR page

**Comment by jdubois** [comment]
Could you edit the title and write something clear?

**Comment by kedevked** [comment]
@jdubois and @deepu105 , I edited the PR title.

**Pull request merged**
