### PR TITLE
add support for 2 more languages

### PR DESCRIPTION
**Pull request by vivekmore**
added i18n support for 2 languages

- Hindi
- Marathi

### CODE REVIEW

**Comment by deepu105** [comment]
Thank you

**Comment by jdubois** [comment]
Thanks & can you also add them in the documentation?

**Comment by vivekmore** [comment]
Just managed to get jekyll installed on my windows laptop.
I'll update the appropriate section(s) on  jhipster/jhipster.github.io soon.

**Comment by jdubois** [comment]
thanks @vivekmore but I've already done it :-)

**Comment by vivekmore** [comment]
no worries  (-:

**Pull request merged**
