### PR TITLE
Lazy load account module

### PR DESCRIPTION
**Pull request by vishal423**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by kaidohallik** [comment]
Currently `translation-not-found` in account module pages if i18n is enabled. Currently this dirty hack is needed to add into **AccountModule** as this is in AdminModule and in entity modules:
```
  constructor(private languageService: JhiLanguageService, private languageHelper: JhiLanguageHelper) {
    this.languageHelper.language.subscribe((languageKey: string) => {
      if (languageKey) {
        this.languageService.changeLanguage(languageKey);
      }
    });
  }
```
But I hope that we can:
1. merge jhipster/ng-jhipster#107
2. release new version of the `ng-jhipster`
3. update #10069 with the new version of the `ng-jhipster` and resolve conflicts there
4. merge #10069 
5. merge new upstream master into this PR

Then no need to add this dirty hack.

**Comment by kaidohallik** [comment]
Currently step 1 is done (jhipster/ng-jhipster#107 is merged). Moving on is blocked in step 2 (new version of `ng-jhipster` is not released).  
Would it be possible to do the release of the `ng-jhipster`? Maybe give the rights to @vishal423 to do `ng-jhipster` releases if @vishal423 and project leads agree? Then maybe @vishal423 can do the release?

**Comment by vishal423** [comment]
As dependent PR got merged, I am merging it as well. If you observe an issue, feel free to raise a ticket.

**Comment by kaidohallik** [comment]
This is working fine in my testing, thanks @vishal423

**Pull request merged**
