### PR TITLE
remove in memory variables from entity json

### LINKED ISSUE #1753: Call methods in templates instead of creating properties in entity jsons
Instead of creating json properties to hold data needed in the templates we should create methods that can be called from the templates to get the data wanted.

The property `fieldNameCapitalized`, `fieldNameUnderscored`, `fieldInJavaBeanMethod` is today stored in each field, e.g.
```json
  "fields": [
    {
      "fieldId": 1,
      "fieldName": "data",
      "fieldNameCapitalized": "Data",
      "fieldNameUnderscored": "data",
      "fieldInJavaBeanMethod": "Data",
      "fieldValidate": false,
      "fieldType": "String",
      "fieldIsEnum": false
    }
  ],
```

and then used in the templates as e.g.
```
    @Field("<%=fields[fieldId].fieldNameUnderscored %>")<% } %>
    private <%= fields[fieldId].fieldType %> <%= fields[fieldId].fieldName %>;
```

instead of using properties we should expose the methods in the template context that does the capitalization, etc. e.g.
```
    @Field("<%=underscored(fields[fieldId].fieldName) %>")<% } %>
    private <%= fields[fieldId].fieldType %> <%= fields[fieldId].fieldName %>;
```

This will make the entity jsons a lot more cleaner.

I think we can replace the following properties with methods as well
```
    "fieldsContainOwnerManyToMany": false,
    "fieldsContainOwnerOneToOne": true,
    "fieldsContainOneToMany": false,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "fieldsContainDate": false,
    "fieldsContainBlob": false,
```

### PR DESCRIPTION
**Pull request by andidev**
I have done some heavy testing where I tested to generate all field types and relationships available for SQL and CASANDRA databases. I have compared the output of the generated source code before changes with after changes and they are the same. So the code should be ok to merge.

fix #1753

### CODE REVIEW

**Comment by deepu105** [comment]
Plz include a test with translation disabled as well

**Comment by gzsombor** [comment]
Nice ! :+1:

**Comment by andidev** [comment]
There is need to test translation disabled since it won't affect the the entity json file. Unless I have missed something? I have only made changes to entity/index.js file.

**Comment by jdubois** [comment]
This looks really great!!! I'm merging this first, and then do all my testing for the next version

**Pull request merged**
