### PR TITLE
update jhipster core to 7.0.0

### PR DESCRIPTION
**Pull request by atomfrede**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
FYI, the tests failed for:

```
  870 passing (6m)
  2 failing

  1) JHipster generator export jdl
       exports entities to a JDL file without argument
         "before all" hook:
     Uncaught Error: An error occurred while exporting to JDL: Cannot read property 'conversion' of undefined
TypeError: Cannot read property 'conversion' of undefined
      at Environment.error (node_modules/yeoman-environment/lib/environment.js:243:40)
      at module.exports.error (generators/generator-base.js:1499:18)
      at module.exports.convertToJDL (generators/export-jdl/index.js:51:26)
      at Object.<anonymous> (node_modules/yeoman-generator/lib/index.js:546:23)
      at /home/runner/work/generator-jhipster/generator-jhipster/node_modules/run-async/index.js:25:25
      at new Promise (<anonymous>)
      at /home/runner/work/generator-jhipster/generator-jhipster/node_modules/run-async/index.js:24:19
      at /home/runner/work/generator-jhipster/generator-jhipster/node_modules/yeoman-generator/lib/index.js:547:9
      at processImmediate (internal/timers.js:456:21)

  2) JHipster generator export jdl
```

**Comment by MathieuAA** [comment]
I'm fixing it right now

**Comment by atomfrede** [comment]
Thanks, I don't have my laptop with me!

**Comment by MathieuAA** [comment]
That should fix it, thanks @atomfrede for the PR!

**Comment by atomfrede** [comment]
Not sure whats going on with the react builds (just clicked rerun jobs to trigger a run of the failed job), since then it can't checkout anymore. Will merge this as import jdl worked  and export was fixed by @MathieuAA 's fix.

**Pull request merged**
