### PR TITLE
Remove HttpHeaders import for Cassandra

### PR DESCRIPTION
**Pull request by SudharakaP**
Minor fix to remove the HttpHeaders import for Cassandra since it's not used and we get the following warning;
```
[INFO]   2:24  warning  'HttpHeaders' is defined but never used  @typescript-eslint/no-unused-vars
[INFO] 
[INFO] ✖ 1 problem (0 errors, 1 warning)
```
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@SudharakaP might need also to switch to cassandra-unit 4.3.1.0
https://github.com/jsevellec/cassandra-unit/wiki/Changelog#4310

**Comment by SudharakaP** [comment]
@DanielFran : Good idea. I'll try to do that today; we'll if it helps with https://github.com/jhipster/generator-jhipster/issues/11169

**Comment by DanielFran** [comment]
@SudharakaP I created a branch with the update in jhipster bom project and will try to push the update directly to your branch.
Is it ok?

**Comment by SudharakaP** [comment]
@DanielFran : Yes absolutely, please go ahead. Thank you. :smile:

**Comment by DanielFran** [comment]
@SudharakaP Might need some updates in packages...

**Comment by SudharakaP** [comment]
@DanielFran : That doesn't seem to fix our problem, but I think it works without any additional problems. :smile:

**Comment by DanielFran** [comment]
Needed to change:
import com.datastax.driver.core.Cluster;
import com.datastax.driver.core.Session

by
com.datastax.oss.driver.api.core.CqlSession

**Comment by SudharakaP** [comment]
@DanielFran : Seems that doesn't work either isn't.... hmm..... I have another idea that I am trying in my local, will see how it goes... :thinking:

**Comment by DanielFran** [comment]
@clun Might need your help on this ;)

**Comment by DanielFran** [comment]
@SudharakaP Probably broken the integration between cassandra-unit and testcontainer with my changes :P

**Comment by SudharakaP** [comment]
@DanielFran : No worries, feel free to revert them. I've changed the title back to the previous one. Thanks for helping me with this one. I have some tests running in my local and so far they seem to be working fine. Will update you guys soon. :smile:

**Comment by SudharakaP** [comment]
@DanielFran : Shall we revert the bom version and the JHI_LIB_BRANCH too? :smile:

**Comment by DanielFran** [comment]
@SudharakaP since we already update Cassandra to 3.11.5, and this library is used for testing we should use the latest version that is the expected for this version.

**Comment by SudharakaP** [comment]
@DanielFran : Yes agreed, but don't you think that the `JHI_LIB_BRANCH` should be master? Because when this PR is merged, we don't want the workflows to be triggered from the `cassandra` branch isn't? :smile:

**Comment by DanielFran** [comment]
@SudharakaP Will merge on jhipster lib master branch as soon as is it working.
Until there, it allow me to make other updates and validating that there are no impacts...

**Comment by SudharakaP** [comment]
@DanielFran : Ah, got it. No problems. :+1:

**Comment by SudharakaP** [comment]
@DanielFran : I think we can now revert the remaining test commits in this pull request now that https://github.com/jhipster/generator-jhipster/issues/11169 is done and the probably we can merge this one. 😄

**Comment by DanielFran** [comment]
@SudharakaP Updated PR.

**Comment by SudharakaP** [comment]
@DanielFran : Thanks Daniel. 👍

**Comment by DanielFran** [comment]
@Relaunched angular tests due to failing tests

**Pull request merged**
