### PR TITLE
[heroku] Add max pool size for HikariCP

### PR DESCRIPTION
**Pull request by jkutner**
It looks like Hikari uses a different prop for max active connections.

### CODE REVIEW

**Comment by mraible** [comment]
Why is the max connections set to 5 when the max allowed is 20?

https://devcenter.heroku.com/articles/heroku-postgres-plans#hobby-tier

**Comment by jkutner** [comment]
So it will work with both postgres and cleardb (which should actually support 10 but i've gone under in case people want to scale up).

I'd prefer to keep it "too low" so that it works on the first try. Then people can adjust as need. Does that seem like a good way to go?

**Comment by mraible** [comment]
If your goal is to make things work on the first try, I think it's OK to keep it low. Of course, it'd be awesome if it did work on the first try. I tried with the latest version and it still times out at 60 seconds. Maybe AsyncLiquibase should be enabled for the heroku profile?

**Comment by jkutner** [comment]
@mraible oh you're still getting time outs? I've actually found that it's successful most of the time now.

Regardless, I'm working on async liquibase right now.

**Comment by mraible** [comment]
Yep, I updated www.jhipster-book.com with the latest release a week or two ago. It doesn't have issues because the app is set to 120 seconds. I just restarted it to see how long it takes and it took just over a minute. It only has three entities.

```
[INFO] org.jhipster.book.Application - Started Application in 57.501 seconds (JVM running for 65.788)
```

On a related note, I do see messages like the following in my logs frequently. I'm on a 2X Dyno ($50/month).

```
2015-11-06T17:39:54.563302+00:00 heroku[web.1]: Process running mem=1068M(103.9%)
2015-11-06T17:39:54.563302+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
```

How is your async liquibase different from the existing one?

https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/java/package/config/liquibase/_AsyncSpringLiquibase.java

**Comment by jkutner** [comment]
Closing this, i have another PR coming in with async and stuff

**Pull request closed without merging**
