### PR TITLE
fix lint in generator-transform

### PR DESCRIPTION
**Pull request by avdev4j**
little esLint fix to generator-transform.js

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by avdev4j** [comment]
To be honest, I don’t know. I tried to launch « npm test » and got an error about this lint error. 

Does my local config is correct ? Or it’s a problem from our lint-fix phase ? 

I was surprised too... 

Envoyé de mon iPhone

**Comment by deepu105** [comment]
Can you run the prettier task and see, I guess may be you didn't setup a
pre commit hook for prettier

**Comment by avdev4j** [comment]
I will do it this morning. I’ll let you know

**Comment by deepu105** [comment]
Look at my other commet in
https://github.com/jhipster/generator-jhipster/pull/9247#issuecomment-462675210

Thanks & Regards,
Deepu

**Pull request merged**
