### PR TITLE
Add cache entry listener logger for ehcache

### PR DESCRIPTION
**Pull request by DanielFran**
Depends on https://github.com/jhipster/jhipster/pull/300

Fix https://github.com/jhipster/generator-jhipster/issues/9871

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@henri-tremblay If you can review also, would be awesome. Thanks

**Comment by henri-tremblay** [comment]
@DanielFran Will do today hopefully. Can I know why we need a listener? They are in general not recommended since they have a noticeable performance impact.

**Comment by DanielFran** [comment]
This is just for logging and it is configured asynchronustly

**Comment by henri-tremblay** [comment]
So, I would really not do that by default. As a way to debug the content of the cache.

1. When adding a listener, Ehcache goes in a different mode, a slower mode, to be able to call the listeners
2. A toString on a value can be quite slow. And could also trigger the cache when it's a Hibernate object. I'm afraid of sneaky bugs

**Comment by PierreBesson** [comment]
Same for me, I don't like this solution. I'm sure there is a better way to log cache put and evict operations for debugging.

**Comment by DanielFran** [comment]
OK, many thanks for the review.
Since there is no agreement to use it, no problem I close it.

**Pull request closed without merging**
