### PR TITLE
Fix protractor e2e with Keycloak 12.x

### PR DESCRIPTION
**Pull request by vishal423**
Related to #14253 
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks @vishal423 ! I'm restarting the daily builds right now, to check it

**Comment by mraible** [comment]
The error element's CSS changed on Keycloak's login form. I'll create a PR to fix.

**Comment by mraible** [comment]
Nevermind, it looks like this PR already has the fix I tried locally. I was able to do `jhipster jdl blog-oauth2` and have all tests pass after changing to `#input-error`.

**Comment by pascalgrimaud** [comment]
yes, it is fixed @mraible 
See https://github.com/hipster-labs/jhipster-daily-builds/actions/workflows/vue-maven-sql.yaml :-)

**Pull request merged**
