### PR TITLE
chore : limit no. of packages installed

### PR DESCRIPTION
**Pull request by Rajpratik71**
Removing unneeded packages , Using Official  repository for packages

This will help to remove unneeded package from dependency

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Comment by mraible** [comment]
I'm curious - why do you add the following to your PRs:

```
Signed-off-by: Pratik Raj rajpratik71@gmail.com
```

Isn't this you? You're signing off on your own pull request? I think this would make sense if someone else "signed off" for you. However, it doesn't make sense that you're approving your own PR.

**Comment by Rajpratik71** [comment]
> I'm curious - why do you add the following to your PRs:
> 
> ```
> Signed-off-by: Pratik Raj rajpratik71@gmail.com
> ```
> 
> Isn't this you? You're signing off on your own pull request? I think this would make sense if someone else "signed off" for you. However, it doesn't make sense that you're approving your own PR.

This is automatic and generally every Opensource projects require this while many other marks it compulsory and many tools also support automatically adding in commit message before committing .

This is a like signature to changes that i done and take responsibility.

I think this does arise any issue or concern.

**Comment by mshima** [comment]
Can you fix conflicts?
The added ppa does not provides package for openjdk 11 anymore.
https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa.

**Comment by Rajpratik71** [comment]
> Can you fix conflicts?
> The added ppa does not provides package for openjdk 11 anymore.
> https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa, actually is provided by openjdk lts, but is outdated.

done

**Pull request merged**
