### PR TITLE
Remove anonymous user filter in user management

### PR DESCRIPTION
**Pull request by flaviencathala**
https://github.com/jhipster/generator-jhipster/issues/5052

### CODE REVIEW

**Comment by deepu105** [comment]
what about filtering it on the backend?

**Comment by flaviencathala** [comment]
@deepu105 I don't really know how to make a clean fix for this on the backend, maybe @jdubois have an idea on how to do a clean filter ?

**Comment by jdubois** [comment]
Yes we need to filter it in the backend -> this is just a "where" clause to remove the "anonymous" user when you do a "findAll", it shouldn't be very complex

**Comment by hdurix** [comment]
@flaviencathala I can do it on the backend this weekend if you want.

**Comment by jdubois** [comment]
@hdurix +1 yes do it, @flaviencathala is more a front-end person, that will be more efficient

**Comment by hdurix** [comment]
I have added a PR on your [branch](https://github.com/flaviencathala/generator-jhipster/pull/4) @flaviencathala.

However, the anonymous user is not filtered with MongoDB. There is a case-sensitive issue with this database, both on master and on my PR: the anonymous user is created with an uppercase letter (only with MongoDB) and the current application works only with lowercase.

You can see on master branch:

- The check for hiding anonymous user is done with `anonymoususer` (see https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angularjs/src/main/webapp/app/admin/user-management/_user-management.controller.js#L59)
- The anonymous user is created with `anonymousUser` (see https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/dbmigrations/_InitialSetupMigration.java#L72)
- The audit event is not inserted if the user login is `anonymoususer` (see https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/repository/_CustomAuditEventRepository.java#L26)

I can do a quick fix on this PR by ignoring case (something like `findAllByLoginIgnoreCaseNot` instead of `findAllByLoginNot`) but I reckon the problem is deeper: some unwanted audit events might be inserted in database.
Moreover I think it's dangerous to just change the case in the initial setup migration script because it could break JHipster upgrade mechanism (I don't know if there is some hash file check like liquibase `databaseChangeLog`).

Anyway, maybe it would be better to create a new issue for that?

**Comment by jdubois** [comment]
@hdurix the correct name is `anonymoususer` (all lower case), as this is a required name for Spring Security.
So the solution for me is to change the set up script in MongoBee (the one you listed, at https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/dbmigrations/_InitialSetupMigration.java#L72 ). I don't think there is a checksum here (there is one with Liquibase, I don't think MongoBee does the same), but anyway it's a bug so let's change this (and if people have existing databases, it will be annoying but they will need to migrate them).

-> @hdurix  can you do it? And then I'll check with @flaviencathala to merge everything tomorrow

**Comment by hdurix** [comment]
Yes no problem I'll do it today.

**Comment by hdurix** [comment]
I added a commit on the branch to correct this.

**Comment by flaviencathala** [comment]
I think this is ready to be merged !

**Pull request merged**
