### PR TITLE
Renamed the service sub-generator to spring-service

### PR DESCRIPTION
**Pull request by clarenced**
- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
@clarenced sorry there was already a PR https://github.com/jhipster/generator-jhipster/pull/6451 that did this change which was merged. Thanks anyway

**Comment by clarenced** [comment]
Oh ok @deepu105 , I did not see there was already a PR for this.

**Comment by clarenced** [comment]
Do you have other issues that I can work on @deepu105 ?

**Comment by deepu105** [comment]
You could try to do any of this https://github.com/jhipster/generator-jhipster/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest

**Pull request closed without merging**
