### PR TITLE
#20987 Fix cors issue for external UI

### PR DESCRIPTION
**Pull request by pierre-filliolaud**
As suggested in issue #20987 , this fix add CORS OPTIONS permitAll to SecurityConfiguration to allo external UI to connect to Hipster backend.

.requestMatchers(HttpMethod.OPTIONS, "/**").permitAll()

---

Please make sure the below checklist is followed for Pull Requests.

- [X] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by Tcharl** [comment]
Even OPTION should be protected by CORS I think: I would disable it for 'dev' profile, but keep it active for 'prod'.
I think that there's a need to improve the spring config files to handle both cases (local dev vs prod)

**Comment by pierre-filliolaud** [comment]
Hi @Tcharl, the goal of this PR is just to fix CORS 'dev' env config running with an external UI. 
@mraible,@Tcharl Feel free to close it if it does not match with JHipster goals. :)

**Comment by mraible** [comment]
@pierre-filliolaud This PR has a lot of code formatting changes that I don't believe are necessary. Can you please fix this PR so it only has the relevant changes. Also, can you please provide steps to reproduce the problem this fixes?

**Comment by Tcharl** [comment]
Hi @pierre-filliolaud ,

Let me try to describe what I meant (sorry to not have been clear enough).

Jhipster has basically 2 spring profiles: dev and prod (can start with `./mvnw -Pdev` or `./mvnw -Pprod`.
The way you whitelisted the OPTION verb is valid for both profiles (no matter the environment).
A better solution would be to activate this whitelisting only for Spring's `dev` profile but to disable it for `prod`(it's a potential security threat for production).

How to achieve it? I don't really know the best way (didn't tried to tweak this authz object dynamically), but I'll try to activate this `.requestMatchers(HttpMethod.OPTIONS, "/**").permitAll()` conditionnally (i.e. using [`@Profile("dev")`](https://github.com/jhipster/generator-jhipster/blob/fc5142b3696690ac4f150bebcece7a446fec89a1/generators/server/templates/src/main/java/package/config/AsyncConfiguration.java.ejs#L40) or [through code](https://github.com/jhipster/generator-jhipster/blob/c4a30bcf67bee70c4d312fc4321e98ad8c4eb7d4/generators/server/templates/src/main/java/package/Application.java.ejs#L67))

**Comment by mraible** [comment]
When I talked to @rwinch about https://github.com/jhipster/generator-jhipster/pull/20107#issuecomment-1302220190, he mentioned the following:

- The line with `HttpMethod.OPTIONS` is probably not necessary since this is handled by `CorsFilter`

That's why I removed it.

**Comment by DanielFran** [comment]
@pierre-filliolaud closing the PR since the customisation can be done directly on the configuration.
Thanks anyway

**Pull request closed without merging**
