### PR TITLE
CI: fix OpenJDK 11 with Azure

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/pull/9789#issuecomment-495738745

@pvliss : it should be fixed now. Thanks for finding this!

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@pvliss : Is this replacement really needed ?
I want to avoid modifying the generated code as much as possible : it would mean for our end users, it doesn't work out of the box. For me, this line is just for compatibility, so keeping value to 8 should be ok. Or maybe I'm wrong

**Comment by pvliss** [comment]
@pascalgrimaud You are right it is not required. Personally I change it but maybe you are right that we should not modify it by default. Should we merge this then and in case someone has a different opinion then do another PR?

**Comment by pascalgrimaud** [comment]
yes please you can merge this :)

**Comment by pascalgrimaud** [comment]
FYI, Daily Builds has been fixed too: https://github.com/hipster-labs/jhipster-daily-builds/commit/3958fc3767a35fadb6936bdefcea41c6551f063a

**Comment by pvliss** [comment]
Cool! Again, thanks a lot Pascal!!!

**Comment by pvliss** [comment]
Great!!!

**Pull request merged**
