### PR TITLE
Fixes related to skipServer option

### PR DESCRIPTION
**Pull request by mshima**
- Move reactive prompt to server generator.
- Fix regeneration with skipServer option.

Related to https://github.com/jhipster/generator-jhipster/issues/13055

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by kaidohallik — COMMENTED** [review]
Below are test results.

`reactive` question is not asked, this is ok.

`.yo-rc.json` includes: `"packageName": "com.mycompany.myapp",` and other unrelated server information - is this possible to exclude unrelated information from `.yo-rc.json`?

`client` and `entity-client` subgenerators are depending on `authenticationType` and `databaseType` options - seems that in `--skip-server` should ask those questions instead of applying default values?

Regenerating doesn't generate server code any more - this is fixed.

**Comment by mshima** [comment]
> `.yo-rc.json` includes: `"packageName": "com.mycompany.myapp",` and other unrelated server information - is this possible to exclude unrelated information from `.yo-rc.json`?

Possible related to:
https://github.com/jhipster/generator-jhipster/blob/50348e6b3f7548480d23265f56ab7b41a9a36fb0/generators/generator-base.js#L2640-L2651
Can be as easy as testing skipClient/skipServer and instead of load defaultConfig, load serverDefaultConfig/clientDefaultConfig.
But I don't consider a bug, so priority is low.

> `client` and `entity-client` subgenerators are depending on `authenticationType` and `databaseType` options - seems that in `--skip-server` should ask those questions instead of applying default values?

In those cases we should require cli option, adding a prompt for them is not worth:
- the prompt belongs to another generator, I don't like mixing generators.
- rarely used.

**Comment by kaidohallik** [comment]
> Can be as easy as testing skipClient/skipServer and instead of load defaultConfig, load serverDefaultConfig/clientDefaultConfig.
> But I don't consider a bug, so priority is low.

In old versions only related options were saved to `.yo-rc.json` - so it would be nice not to add this also in current version.
I tried also upgrading some older version and if `skipServer=true` then generator starts asking unrelated questions about package name etc. Sample:
```
{
  "generator-jhipster": {
    "jhipsterVersion": "6.9.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "sql",
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": ["et", "en", "ru"],
    "skipServer": true,
    "blueprints": [],
    "skipCommitHook": true,
    "creationTimestamp": 1577520421451
  }
}
```
Try run `jhipster --force` on this config.

> In those cases we should require cli option, adding a prompt for them is not worth:
> 
> * the prompt belongs to another generator, I don't like mixing generators.
> * rarely used.

Agree, cli option is ok.

**Comment by mshima** [comment]
> In old versions only related options were saved to `.yo-rc.json` - so it would be nice not to add this also in current version.

I removed setting every config defaults, let's see if tests passes.

> Try run `jhipster --force` on this config.

@kaidohallik are you sure that you used this PR's branch? I couldn't reproduce.

**Comment by mshima** [comment]
> I removed setting every config defaults, let's see if tests passes.

It failed, I will take a look at this another time.

**Comment by kaidohallik** [comment]
> > Try run `jhipster --force` on this config.
> 
> @kaidohallik are you sure that you used this PR's branch? I couldn't reproduce.

You are right, this branch fixes that. I could reproduce in main branch but not in this branch.  
So merge this PR and deal with polishing `.yo-rc.json` later?

**Comment by mshima** [comment]
> So merge this PR and deal with polishing `.yo-rc.json` later?

Yep. Changed from fixes to related.

**Review by kaidohallik — APPROVED** [review]
Thanks @mshima

**Pull request merged**
