### PR TITLE
Bengali (bn) Language folder added. Translation added for most of the…

### PR DESCRIPTION
**Pull request by AfzalH**
… files.

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks @AfzalH for your 1st contribution to the project.

Can you add your language to this file: https://github.com/jhipster/generator-jhipster/blob/master/travis/samples/ngx-default/.yo-rc.json#L19 plz ? So it will be tested

**Comment by jdubois** [comment]
Thanks & congrats from me also @AfzalH !

Can you also add it to https://github.com/jhipster/jhipster.github.io/blob/master/pages/installing_new_languages.md so it's listed officially on the website?

**Comment by AfzalH** [comment]
Added!

**Comment by pascalgrimaud** [comment]
So strange, no Travis builds for this one

**Comment by pascalgrimaud** [comment]
I will test it manually and merge as soon as it's done

**Comment by pascalgrimaud** [comment]
It seems to work well, but you need to add the language in this file: https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-constants.js#L102-L111

Otherwise, the language won't appear during the prompt

**Comment by AfzalH** [comment]
Added!

**Comment by pascalgrimaud** [comment]
I merge too quickly, there were some issues I fixed here:
https://github.com/jhipster/generator-jhipster/pull/8256

I added one missing file

**Pull request merged**
