### PR TITLE
priority to "url: '/{login}/edit'" vs "url: '/user/:login'"

### PR DESCRIPTION
**Pull request by ctamisier**
fix the edition of the user with 'user' login.
The side effect is that we can't have a user called 'edit'.

### CODE REVIEW

**Comment by ctamisier** [comment]
This issue does not occur on jhipster 3.12.1 (occurs in master branch), so I guess this PR would be just a workaround..
So ignore this PR I would say, but the problem is here..

**Comment by jdubois** [comment]
OK, I confirm the issue, I didn't know that (please create a ticket before, explaining the issue, so we know what you are correcting)

**Comment by ctamisier** [comment]
ok I will create an issue with more details, actually the problem is also in jhipster 3.12.1 but it does not occur the same way..

**Comment by jdubois** [comment]
No, I mean do it next time -> here I understand the issue, I'm going to work on it, no worries

**Comment by jdubois** [comment]
Oh, you just moved the route, that's easy :-)
OK I'm merging this without even testing :-)

**Comment by jdubois** [comment]
yes we'll need to disable that, but that's not a huge priority

**Pull request merged**
