### PR TITLE
Bump version to 5.8.2

### PR DESCRIPTION
**Pull request by pvliss**
After release of 5.8.2 we need to bump the version in master as well otherwise `npm test` fails for the upgrade sub-gen.

Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Oh I forgot the master branch, thanks a lot!

**Comment by pvliss** [comment]
Thanks @jdubois

**Comment by murdos** [comment]
Just wondering if you could also fix the test to not fail for that: could you provide the details of the error?

**Comment by pvliss** [comment]
@murdos Certainly just give me a few minutes. You can also reproduce this by simply changing the jhipster version in `package.json` to a version lower than the current release, e.g. 5.8.1. The gist of it is that in case there are merge conflicts(which in this case there are) then the tests for git gommits performed fail. See https://github.com/jhipster/generator-jhipster/blob/91f72b8e41aa4f8bc4c760233007abd4a34261fd/test/upgrade.spec.js#L65 and https://github.com/jhipster/generator-jhipster/blob/91f72b8e41aa4f8bc4c760233007abd4a34261fd/test/upgrade.spec.js#L140.

I guess if we can detect the case where a conflict arises then we could change the test to assert the correct commit count

**Comment by pvliss** [comment]
So here is sample output for the second test:
```bash
INFO! Congratulations, JHipster execution is complete!
Auto-merging README.md
Auto-merging .yo-rc.json
CONFLICT (content): Merge conflict in .yo-rc.json
Automatic merge failed; fix conflicts and then commit the result.
.yo-rc.json
      ✓ creates expected files for default configuration (1ms)
3
      2) generates expected number of commits
      ✓ still contains blueprint information (1ms)
...
...
...

2) JHipster upgrade generator
       blueprint application
         generates expected number of commits:
      AssertionError: expected '3' to equal '5'
      + expected - actual
      -3
      +5      
      at Context.it (test/upgrade.spec.js:148:37)

```
#### Reproduction steps
To reproduce I did the following:
1. Change version to 5.8.1 at https://github.com/jhipster/generator-jhipster/blob/master/package.json
2. Run the following commands to make sure everything is properly resolved:
```
rm package-lock.json && rm -rf  node_modules/ && npm install && npm link
```
3. Executed tests with `npm test`

**Comment by murdos** [comment]
Thanks! :)
I'm not sure we should change something in the unit test. Because there's indeed no (good) reason for having merge conflicts in the context of the unit tests.

**Pull request merged**
