### PR TITLE
Email Pattern Leads To Importing JDL Failure Due To A JavaScript Error

### PR DESCRIPTION
**Pull request by akang**
---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
This PR is empty

**Comment by akang** [comment]
Sorry about that. Here it is

**Comment by akang** [comment]
Sorry but what is the workflow after the PR is created? Should I close it or..?

**Comment by DanielFran** [comment]
@akang The first time you merged the branch you loose all your dev.... If you look at https://github.com/jhipster/generator-jhipster/pull/16180/files you will see that there is no changes available (so "PR is empty").

**Comment by akang** [comment]
> @akang The first time you merged the main branch you loose all your dev.... If you look at https://github.com/jhipster/generator-jhipster/pull/16180/files you will see that there is no changes available (so "PR is empty").

I do see the changes in the PR tho unless I am missing something?

Screenshot 2021-09-08 at 4 04 16 PM

**Comment by akang** [comment]
Ok. I think I know why there aren't any files in the PR. It's cause it was merged a while back already. So I will close this PR. Perhaps someone else can close the issue if it's verified as complete. 

Thanks

**Pull request closed without merging**
