### PR TITLE
Add html to prettier

### LINKED ISSUE #13090: Enable prettier for html files.
##### **Overview of the feature request**

We should consider enabling prettier for html files at the generator.

##### **Motivation for or Use Case**

Standardise html formatting.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by swarajsaaj**
HTML files will now be included in prettier command

Fix #13090

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by mshima — APPROVED** [review]
LGTM.

**Comment by mshima** [comment]
@swarajsaaj move html extension to inside skipClient condition.
I don't think there is any html on backend only.

**Comment by swarajsaaj** [comment]
> 
> 
> @swarajsaaj move html extension to inside skipClient condition.
> I don't think there is any html on backend only.

@mshima  I could find `src/main/resources/templates/error.html` in backend, also some mail templates are there for usermanagement apps in `src/main/resources/templates/mail/`

**Comment by gmarziou** [comment]
> I could find `src/main/resources/templates/error.html` in backend, also some mail templates are there for usermanagement apps in `src/main/resources/templates/mail/`

But these are Thymeleaf templates, I'm not sure prettier can do a good job with them although I did not check.
I have same doubts about Angular templates, usually code formatters are not comfortable with template syntax.

**Comment by swarajsaaj** [comment]
> 
> 
> > I could find `src/main/resources/templates/error.html` in backend, also some mail templates are there for usermanagement apps in `src/main/resources/templates/mail/`
> 
> But these are Thymeleaf templates, I'm not sure Prettier can do a good job with them although I did not check.
> I have same doubts about Angular templates, usually code formatters are not comfortable with template syntax.

@gmarziou I think for thymeleaf most of syntax is inserted as attributes to HTML elements (with a prefix namespace), so they should not interfere with formatting.

For Angular templates, Prettier seems to have support for `*.component.html` files since v1.15 https://prettier.io/blog/2018/11/07/1.15.0.html

**Comment by mshima** [comment]
@gmarziou you can see the result at https://github.com/jhipster/generator-jhipster/pull/13252/checks?check_run_id=1542973740 (MERGE: project diff section).

Backend files are the first. Looks ok to me.

**Comment by gmarziou** [comment]
Thanks for the examples, output is consistent and works well with templates.

It's just that I'm not a big fan of the way Prettier formats html which uses much more vertical space than original formatting.

```html
            <input
              type="password"
              class="form-control"
              id="newPassword"
              name="newPassword"
              placeholder="{{ 'global.form.newpassword.placeholder' | translate }}"
              formControlName="newPassword"
              data-cy="resetPassword"
              #newPassword
            />
```
or

```html
<html
  xmlns:th="http://www.thymeleaf.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.thymeleaf.org"
  th:lang="${#locale.language}"
  lang="en"
>
```

Also embedded CSS formatting does not look familiar to me, I would keep `body, p { `rather than inserting a new line like below:

```css
      @media only screen and (max-width: 280px) {
        body,
        p {
```

**Comment by mshima** [comment]
Not a big fan either, but overall is better with prettier enabled IMO.

**Comment by gmarziou** [comment]
Agreed, let's favor style consistency.

**Comment by swarajsaaj** [comment]
@mshima @gmarziou Can you please help why "npm test" is failing in the CI (https://github.com/jhipster/generator-jhipster/pull/13252/checks?check_run_id=1546315589) ? I am not sure how this timeout error can be due to html prettier change, or is it due to some other issue?

**Comment by mshima** [comment]
Try to increase timeout to 40000 at:
https://github.com/jhipster/generator-jhipster/blob/7b07d282a4186ea58ae9d7884ecb8226be23e6f3/.mocharc.js#L5

Enabling prettier at html can make the generation slower.

**Comment by swarajsaaj** [comment]
@mshima I have tried increasing 30000ms to 90000ms in steps, but still it seems slow.

**Comment by swarajsaaj** [comment]
@mshima Finally found the hidden problem, under the hood in test prettier was getting stuck due to a syntax error in `HelloVue.html`, `<meta>` was enclosed in a nested meta tag instead of a `<head>`, thanks for the help :)

**Comment by DanielFran** [comment]
@swarajsaaj Thanks for the contribution!

**Comment by mshima** [comment]
Great job finding the error.
I actually didn’t help.

**Pull request merged**
