### PR TITLE
Rename modulname.js files to modulename.state.js

### LINKED ISSUE #2883: Rename modulename.js file wich contains the states to modulename.state.js
Now that we follow john papa styleguide should'nt we rename the module file containing the states according to:

**Health module before change**
```
health
  health.controller.js
  health.js
  health.modal.controller.js
  health.modal.html
  health.service.js
  health.html
```

**Health module after change**
```
health
  health.controller.js
  health.state.js
  health.modal.controller.js
  health.modal.html
  health.service.js
  health.html
```

### PR DESCRIPTION
**Pull request by andidev**
fix #2883

### CODE REVIEW

**Comment by deepu105** [comment]
@andidev just realized that the standard practice and john papa style for these are `modulename.routes.js` what do you think. I also think that routes makes more sense than state

**Comment by andidev** [comment]
Yes I saw that to a time after I did the refactoring. I agree. Let change it to routes then.

**Comment by deepu105** [comment]
For clarity it should be `module.route.js`

**Comment by gmarziou** [comment]
Well in angular-ui router they should be states, routes are for the standard router I guess.

**Comment by deepu105** [comment]
Ya but even projects using ui touter are naming it route as its the angular
terminology,  say for example angular fullstack generator

**Pull request merged**
