### PR TITLE
Use absolute path for static images.

### PR DESCRIPTION
**Pull request by CGarces**
With relative paths files are hashed, and cause miss hit from caches, in my case I'm using a CDN.

Related to https://github.com/jhipster/jhipster.github.io/pull/1248 

~~I have changed and tested the angular application. Please confirm if I should modify also the other web frameworks.~~

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by atomfrede** [comment]
Thanks for the contribution. If possible it would be great to update react and vue as well.

**Comment by CGarces** [comment]
done.

**Comment by atomfrede** [comment]
Can you check why the compilation fails for react and vue with `Can't resolve '/content/images/jhipster_family_member_1.svg'`

**Comment by CGarces** [comment]
I'll check vue & react in a few days after the hollidays.

**Comment by CGarces** [comment]
Fixed VUE, but after the change relative urls on CSS no longer works.
If not is the desire behavior I can revert it and keep VUE as is, images are hashed or duplicates in the worse case.

Before the change
image
image

After the change

image

**Comment by CGarces** [comment]
Fixed React changing the css-loader options, like Vue

**Comment by atomfrede** [comment]
@CGarces I restarted the failied build, but it looks good, all other vue related pipelines are ok. Can you check the conflict? I think afterwards this is fine for merge

**Comment by CGarces** [comment]
I have rebased the PR.
I can't Identify the root cause for the error at https://github.com/jhipster/generator-jhipster/actions/runs/3794496601/jobs/6626003614
Last build has failed due a timeout at  https://github.com/jhipster/generator-jhipster/actions/runs/3942797909/jobs/6746876977

**Pull request merged**
