### PR TITLE
Fix page number generation when using different page sizes

### LINKED ISSUE #2625: Pagination bug
Pagination is not showing the appropriate number of pages for me.
You can reproduce this issue with  the user management page, or any entity you decide to create with linked pagination : if you try to reduce the page size from 20 to lets say 5 (for example in user-management.controller.js), and add a couple of entities just for testing, you'll expect to find at least 2 pages but I can still see only 1 page, with obviously missing items.

Sorry i've been blocking on that issue without beeing able to explain myself the root cause... if anyone could tell me if you have the same problem or any lead to solve it, it would help a lot. Thx.

(using JHipster Generator v2.26.2 with Chrome, and MongoDB)

### PR DESCRIPTION
**Pull request by ruddell**
Adds a scope variable for page size, allows ui-boostrap paging directives to display the correct number of pages

Fix #2625

### CODE REVIEW

**Comment by geraldhumphries** [comment]
+1

Only recommendation is that you also remove `itemsPerPage` from `_uib-pager.config.js` and `_uib-pagination.config.js`.

Another possible approach is to inject uibPaginationConfig/uibPagerConfig into the controller, and use the config's `itemsPerPage`:
```
{page: $scope.page - 1, size: uibPaginationConfig.itemsPerPage}
```

This way `itemsPerPage` can be configured globally and overridden on a per-controller basis where needed. In this case, I would probably not refer to `items-per-page` in the html because it would be redundant unless the user needs to override it.

**Comment by deepu105** [comment]
I think the idea was to do it in global config file rather than define for each controller and overide manually only for ones required @geraldhumphries since you did original PR you have any comment on this?

**Comment by geraldhumphries** [comment]
@deepu105 see my suggested approach in my first comment. It would make the api calls in the controllers also follow the globally configured page size (and can be overridden by following the suggestion @ruddell made in his comment in #2625) but I don't know if injecting config objects into controllers like that is considered best practice.

**Comment by ruddell** [comment]
I like your suggestion of using the config files more than my original change.  It's definitely neater and easier to follow. I've added those changes.

The default page size returned from the server is 20 so the default itemsPerPage on the client should always be 20, even if we set it individually.  uib-pagination defaults to 10 if no other value is provided.

**Comment by deepu105** [comment]
Im not sure if it is a proper way to inject config in a controller, may be
it should be a Constant, I guess having a controller scope variable was
much better than injecting a config

Thanks & Regards,
Deepu

**Comment by ruddell** [comment]
I think the scope variable is the most simple/effective way, but I will defer the decision to one of you.

**Comment by deepu105** [comment]
I prefer what we currently have as it works for most people. Why fix if not
broken?

If someone wants to override defaults that can be easily done, may it
should be just documentation update

**Comment by ruddell** [comment]
The uib-pagination update changed how the page numbers are generated.  Changing the query size in the past was as simple as changing 20 to 10, now it requires several steps and looking up documentation on ui-bootstrap.

In my case, I didn't notice that the number of pages was no longer based on the query until someone mentioned to me the pagination was broken.  I submitted this pull request because I found out I wasn't the only one confused by the update.

**Comment by deepu105** [comment]
let me take a closer look

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Ok I had a closer look here is what needs to be done.

1. create a new angular constant file for pagination called `pagination.constants.js` in the forms folder along side `_uib-pager.config.js` and `_uib-pagination.config.js`.
2. set the items per page value in the constant
3. inject the constant in existing `_uib-pager.config.js` and `_uib-pagination.config.js` blocks and use that
4. Inject the same constant in entity only when pagination is enabled & user management page and use it 

This way your issue will be solved and we will be following proper angular practice. If you can make this change ill be happy to merge it.

**Comment by deepu105** [comment]
@ruddell is this ready? seems good to me

**Comment by ruddell** [comment]
Yes sorry forgot to comment that I made the changes

**Comment by deepu105** [comment]
no worries

**Pull request merged**
