### PR TITLE
provide maven wrapper support

### LINKED ISSUE #2080: Add Maven Wrapper for Maven projects
We currently include the Gradle Wrapper with Gradle projects. It'd be good to include the Maven wrapper as well.

https://github.com/bdemers/maven-wrapper

This way, developers can start with JHipster without having to install Maven. 

Spring Initializr added this recently:

https://github.com/spring-io/initializr/commit/be8ee1964fa02a2ca726e6d768869bd757ff8968

### PR DESCRIPTION
**Pull request by jreyes**
Provide the maven wrapper with every Maven project so that the regular
`mvnw` command can be used.

Fix #2080

### CODE REVIEW

**Comment by atomfrede** [comment]
I think you need to exclude the wrapper jar file from ``gitignore`` (at least we are doing that for the gradle wrapper):

``!gradle/wrapper/gradle-wrapper.jar``

**Comment by jreyes** [comment]
Yes, you are correct, added to gitignore

**Comment by gzsombor** [comment]
Why it's needed? The maven build works just fine without adding a new jar from an obscure project.

**Comment by mraible** [comment]
It's like the Gradle Wrapper. Users wouldn't need to install Maven.

**Comment by gmarziou** [comment]
@jreyes don't forget the doc

Team, how are we going to reflect this change in documentation?
I mean should we add the wrapper alternative for each maven instruction like:

'mvn spring-boot:run` or 'mvnw spring-boot:run`

Or have only one command used (mvnw?) and add a global note stating that mvn commande be used in place of mvnw?

**Comment by mraible** [comment]
I'd vote for using "mvn" and "gradle" with a note about wrapper commands.
Then again, if we depend on certain versions of Maven/Gradle, we should
specify the wrapper commands or add a note to the docs.

**Comment by gzsombor** [comment]
I've never saw a maven project, where a wrapper is used. It's just like if we add a jvm installer to the project, just for the developers who don't  have one already. 
 It's a waste of time and resources, and this usage is not the main stream / default, as everyone else is doing it

**Comment by mraible** [comment]
I just think we should be consistent b/w build tools. We provide a Gradle
wrapper by default. Users don't have to use it and can easily delete.

**Comment by deepu105** [comment]
I dont have much experience with maven so i have no comments here, but i
certainly like gradle wrapper its the default way i have always used it and
its the easiest i would say but then again its official and recommended by
gradle not sure abt maven wrapper

**Comment by gzsombor** [comment]
The customs with gradle is to include a wrapper script, but with maven it's against the official way. And with JHipster, we try to stick to the upstream defaults.
Maybe there are java developers, who doesn't have maven yet, but they rather get that tool ASAP, and learn how to use it

**Comment by atomfrede** [comment]
You're right a java developer has maven installed. But I worked with a designer on an application (not jhipster) and he had no idea about maven, so providing a wrapper would be much easier in that case.

**Comment by jdubois** [comment]
- yes the wrapper is quite an unknown project, but it's supposed to become official at some point (from my understanding)
- yes Java developer usually don't need this, but it's not mandatory -> I think it can help quite a lot of people, and it won't do any harm otherwise as you can still use Maven normally

**Comment by pnreddysvu** [comment]
Maven wrapper is officially added to spring boot 1.3. Will be available in next release.

**Comment by jreyes** [comment]
@gmarziou done, but need a confirmation on the way to go about documentation. I went with the 'mvnw' command with the global 'mvn' note  

jreyes/jhipster.github.io@278aca893ed8ebdcd2373e57b27838c4bd16603b

**Comment by jdubois** [comment]
@jreyes @gmarziou for the documentation I would keep the standard "mvn" command. That's how most people will use it. But we should document "mvnw" in the setup instructions.

**Comment by jdubois** [comment]
OK, let's merge this and document later -> anyway it doesn't change anything, as the "mvn" command still works

**Pull request merged**
