### PR TITLE
Travis: some minor improvements

### PR DESCRIPTION
**Pull request by pascalgrimaud**
- rename app folder with gradle and psql
- try to optimize order to speedup the global time
- simply use -DskipTests without true value

### CODE REVIEW

**Comment by deepu105** [comment]
@pascalgrimaud we still have a lot of INFO and DEBUG logs on the travis builds which makes it very difficult to scroll through to find errors. Is it possible to set some environment variable in travis script so that only WARNING and above logs are printed for everything? cc @jdubois

**Comment by deepu105** [comment]
may be something like this http://stackoverflow.com/a/6307666/1273312

**Comment by pascalgrimaud** [comment]
I think we can reduce more. 
Anyway, the log info or debug are not important, right ? only the final result is important IMO

**Comment by jdubois** [comment]
Yes I just changed the log level for tests today -> it was wrong anyway, the `logback-test.xml` which was supposed to work according to the Spring doc only worked when running tests in an IDE (and were not working with Maven!).
So that should be OK now.

**Pull request merged**
