### PR TITLE
Add integration tests for LogsResource and ProfileInfoResource

### PR DESCRIPTION
**Pull request by pascalgrimaud**
It is not totally perfect, but I think it's better than nothing:
- add LogsResourceIntTest
- add ProfileInfoResourceIntTest
- fix some indentation

### CODE REVIEW

**Comment by jdubois** [comment]
Great!!!! I hope this will make https://sonarqube.com/dashboard/?id=1054756 go past the 80% bar (we are currently at 79,5% !!! And the "recommended" metric is 80%)

**Comment by pascalgrimaud** [comment]
Not sure this code will increase the coverage by 0.5%, it's a lot :crossed_fingers: 

But what I see is:
- UserResource : 19.2%
- AccountResource : 31.6%

These classes are important and we can improve the coverage!
I'll try to do it

**Comment by pascalgrimaud** [comment]
@jdubois : 80.2% coverage!!!

**Comment by jdubois** [comment]
Excellent!!!!!
Out of 1730 projects in Sonar, we are in the 3 projects with AAA, 80% coverage, >10k of code:
https://sonarqube.com/projects?coverage=1&maintainability=1&reliability=1&security=1&size=3

**Pull request merged**
