### PR TITLE
Gradle explicit versions

### PR DESCRIPTION
**Pull request by atomfrede**
I've aligned all dependencies when using ``gradle``. I've considered ``mvn`` build as the "leading" system, therefore I've downgraded ``jackson`` to ``2.4.6`` for example. Furthermore I've enforced some versions, such that for ``compile`` and ``test`` the same versions are used. Additionally I've corrected some excludes.

bildschirmfoto von 2015-08-18 07-28-51

### CODE REVIEW

**Comment by deepu105** [comment]
@atomfrede I thought hikariCP 2.4.0 doesnt aupport java 7?  I thought the support was stopped in 2.3.9 can you confirm plz?

Also why are we downgrading joda time and jacson instead of upgrading it in maven build? 

Sorry if my questions are naive

**Comment by andidev** [comment]
2.4.0 works for java 8 and java 7. 
Author of HikariCP commented on this, seehttps://github.com/jhipster/generator-jhipster/issues/1872

**Comment by atomfrede** [comment]
@deepu105 [Hikari 2.4.x is the](https://github.com/brettwooldridge/HikariCP) ``Java 7 and Java 8 maven artifact`` 
I've used the lower versions from maven because they are the _blessed dependencies_ and I was not sure which one to choose so I choose the lower ones. Maybe we should agree upon how to handle third party dependencies (I would try to use the newest ones as long as there are no problems with it)

**Comment by jdubois** [comment]
We should follow the Spring Boot dependencies, as they do a great first level of testing, and only upgrade/downgrade if we find an issue.

**Comment by atomfrede** [comment]
I can setup a list comparing spring-boot - jhipster versions but I think at the moment we only changed

* liquibase
* hikari

**Pull request merged**
