### PR TITLE
Use fixed dependency: terser 3.14.1

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to:
- https://github.com/jhipster/generator-jhipster/pull/9174#issuecomment-460085476
- https://github.com/webpack-contrib/terser-webpack-plugin/issues/66

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud Probably this needs to be done also in v5?

**Comment by pascalgrimaud** [comment]
I think yes, because all generated project with v5 will be broken

**Comment by DanielFran** [comment]
@pascalgrimaud Since this fix seems OK, can it be merged in master?

**Comment by pascalgrimaud** [comment]
@DanielFran : yes, you can merge my 2 PRs !

**Pull request merged**
