### PR TITLE
Update liquibase to 3.8.0 and liquibase_hibernate to 3.8

### PR DESCRIPTION
**Pull request by DanielFran**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
Actually waiting for https://liquibase.jira.com/projects/CORE/issues/CORE-3472 to be solved

**Comment by DanielFran** [comment]
@atomfrede I added you as reviewer since I was not able to test the gradle changes.

**Comment by DanielFran** [comment]
Using liquibase-maven-plugin the parameter prefer.internal.xsd=true seems working fine, but not using liquibase integration with spring.

**Comment by DanielFran** [comment]
Issue has been fixed in liquibase side, changelog xsd files are now available...

**Comment by DanielFran** [comment]
@pmverma @atomfrede Can you confirm liquibase diff works fine for you?

**Comment by atomfrede** [comment]
@DanielFran Give a moment, going to check that right now

**Comment by atomfrede** [comment]
It didn't work, the generated changeset contained only dropped tables and constraints. But I also didn't manage to make ti work with maven with an exception:

```
[WARNING] Unknown database: Hibernate
[INFO] Performing Diff on database jhipster @ jdbc:postgresql://localhost:5432/jhipster (Default Schema: public)
[INFO] Error getting default schema
java.lang.NullPointerException
```

**Comment by DanielFran** [comment]
@atomfrede I was able to implement tests with maven to confirm it is not working too... sorry for that!
The update work, the diff not. :(

Will try to fix the issue, probably using same workaround existing today.

Migth consider creating tests for it, justo do not know how I can add changes to pom/gradle just for testing internally, changes that should not appears when we create the app.

@pascalgrimaud Any suggestion?

**Comment by DanielFran** [comment]
Seems like since liquibase 3.7 that diff always fails with error "javax.persistence.PersistenceException: Unable to resolve persistence unit root URL: class path resource [] cannot be resolved to URL because it does not exist" that is not fixed in 3.8 ever.

So closing this PR!

**Comment by pascalgrimaud** [comment]
it's strange that the liquibase diff failed since 3.7
I didn't follow in details this ticket, but is it a known bug ? maybe we miss some extra config ?

**Pull request closed without merging**
