### PR TITLE
Use color banner for JHipster on startup

### PR DESCRIPTION
**Pull request by mraible**
Spring Boot 1.3 added support for color banners. It's kinda hip!

Inspired by http://stackoverflow.com/questions/33797009/how-to-change-spring-boot-logo-to-nyan-cat

Here's some screenshots of what this looks like. 

black-terminal

white-terminal

### CODE REVIEW

**Comment by mraible** [comment]
I chose green for J b/c of Java and Spring Boot's logo is green. I used red for Angular and Magenta for Bootstrap to try and match the project's respective logos.

**Comment by jdubois** [comment]
In that case I'll do the J in "Spring green" and the Hipster in "AngularJS
red", it would be easier to understand.

**Comment by mraible** [comment]
Made some color and indent improvements. Screenshow below:

screen shot 2015-11-20 at 1 01 43 am

**Comment by mraible** [comment]
Screenshot with :: at end and space after emoji.
screen shot 2015-11-20 at 1 05 48 am

**Comment by jdubois** [comment]
Looking good !

**Comment by jdubois** [comment]
Hang on, you spellt Hipster wrong!!!!

**Comment by jdubois** [comment]
It happens to me all the time, I wonder if we could make a "JHiptser" generator just for fun

**Comment by pascalgrimaud** [comment]
tips : you can add [ci skip] at the end of commit msg to avoid full travis-ci build ;)

**Comment by mraible** [comment]
Ha! Good catch on the spelling @jdubois. Corrected screenshot:
screen shot 2015-11-20 at 1 22 50 am

**Comment by deepu105** [comment]
@mraible you beat me to it I was working on it :) anyway this looks much better :+1:

**Comment by gzsombor** [comment]
We could integrate a nice ascii art generator to automatically generate a banner based on the app name :wink:

**Comment by jdubois** [comment]
Merged, but @mraible we should also have the same banner at https://github.com/jhipster/generator-jhipster/blob/master/app/index.js#L35 for consistency

**Comment by mraible** [comment]
@gzsombor Auto-generating a banner from the app name would be pretty cool.

@jdubois I agree it'd be nice to have the same banner in `index.js`. I looked at that file and skipped modifying it as it seemed like converting it would be quite a bit harder.

**Comment by jdubois** [comment]
@mraible oh yes, I did the current version, I confirm it's harder :-)

**Comment by gmarziou** [comment]
Good work @mraible !
Regarding generating the banner with the app name, I suppose someone will complain that it does not always fit within 80 chars wide terminals :)

**Pull request merged**
