### PR TITLE
WIP: Feature: clientInterface entity option

### PR DESCRIPTION
**Pull request by KCL-TelferAA**
There are certain instances where you may not want to expose endpoints for some entities. This pull request allows a developer to exclude generation of the RESTful resource files for specified entities.

The following code will generate RESTful resources for only entities `B` and `C`:
```jdl
entity A
entity B
entity C

clientInterface A
```

The following code will only generate RESTful resources for entity `A`:
```
entity A
entity B
entity C

clientInterface * except A
```

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
This is something planned, but I think adding this to jdl like this creates some noise.
We probably need something more generic.

See https://github.com/jhipster/generator-jhipster/issues/14416.
IMO an entity annotation is enough.

**Comment by mshima** [comment]
And there is a rfc adding to jdl:
https://github.com/jhipster/generator-jhipster/pull/18152/files

**Comment by KCL-TelferAA** [comment]
> This is something planned, but I think adding to jdl like this creates some noise. We probably need something more generic.
> 
> See #14416. IMO an entity annotation is enough.

Hi @mshima,

Thanks for your quick reply. I didn't realize that I targeted the main upstream repository, but the feedback is good.

I thought about an annotation, but wasn't seeing how to get that done. I'll look at your suggestions and send another PR when I get the chance.

**Comment by KCL-TelferAA** [comment]
> And there is a rfc adding to jdl:
> https://github.com/jhipster/generator-jhipster/pull/18152/files

@mshima,

Looking at the following from the RFC
> Blueprint with additional options will have to override objects definiton: an overridable api should be provided at the generator-core level to let the blueprint developer to add its own attributes at each level

I understand the approach, but I'm not clear on how blueprints work. Is there a simplified explanation of how blueprints work and do you have an ideal reference implementation you'd like me to consider?

**Comment by Tcharl** [comment]
Hi @KCL-TelferAA,

This RFC is just stating that you should basically use inclusive syntax instead of negative ones, not giving any reco on how to achieve it: it bring much more composability this way

e.g. `restResources A` instead of `noRestResource * expect A`.

**Comment by KCL-TelferAA** [comment]
@mshima, this work should be complete, but I'm getting some test failures that I'm not sure how to resolve:

```
  7852 passing (3m)
  325 pending
  7 failing

  1) generator - client
       composing
         with translation disabled
           should compose with jhipster:common:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (generators/client/generator.spec.mts:71:9)
      at process.processImmediate (node:internal/timers:476:21)

  2) generator - client
       composing
         with translation enabled
           should compose with jhipster:common:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (generators/client/generator.spec.mts:95:9)
      at process.processImmediate (node:internal/timers:476:21)

  3) generator - client
       composing
         without cypress
           should compose with jhipster:common:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (generators/client/generator.spec.mts:119:9)
      at process.processImmediate (node:internal/timers:476:21)

  4) generator - client
       composing
         with cypress
           should compose with jhipster:common:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (generators/client/generator.spec.mts:146:9)
      at process.processImmediate (node:internal/timers:476:21)

  5) generator - client
       composing
         with cypress
           should compose with jhipster:cypress:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (generators/client/generator.spec.mts:152:9)
      at process.processImmediate (node:internal/timers:476:21)

  6) needle API Angular angular generator : JHipster with blueprint
       "before all" hook for "entity menu contains the entity added by needle api":
     Error: Timeout of 50000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (<path-to-project>/generator-jhipster/test/needle-api/needle-client-angular-generator.spec.mts)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7)

  7) generator - upgrade
       default application
         "before all" hook for "generated git commits to match snapshot":
     Error: Something went wrong while generating project! Error: Command failed: "Unknown command: "bin"
To see a list of supported npm commands, run:
  npm help
/jhipster" --with-entities --force --skip-install --skip-git --ignore-errors --no-insight --skip-checks
      at UpgradeGenerator._generate (file:///<path-to-project>/generator-jhipster/generators/upgrade/generator.mjs:197:13)
      at UpgradeGenerator._regenerate (file:///<path-to-project>/generator-jhipster/generators/upgrade/generator.mjs:213:10)
      at UpgradeGenerator.prepareUpgradeBranch (file:///<path-to-project>/generator-jhipster/generators/upgrade/generator.mjs:427:16)
```
Can you provide any assistance?

Also, do you have a slack channel or some space to communicate with contributors?

**Pull request closed without merging**
