### PR TITLE
Use jhipster dependencies master 3.10.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by pascalgrimaud**
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
Restarted failing webflux tests

**Comment by DanielFran** [comment]
Reverted spring-cloud version to Hoxton.SR4, should fix the issue with webflux-gateway-oauth2

**Comment by DanielFran** [comment]
Closed/Reopen to launch full tests again

**Comment by pascalgrimaud** [comment]
Thanks @DanielFran

**Pull request merged**
