### PR TITLE
Add Angular Controller Specs

### PR DESCRIPTION
**Pull request by trevershick**
Moved health.controller.spec.js from account/ to admin/
Refactored spec generation in index.js
Added tests to ensure files are generated
refactored password.controller.spec.js to match new controller specs
 - fixed the spyOn return values.
 - .and.returnValue should return a promise.
added a helper to call module beforeEach globally instead of putting it
 in every test.
refactored settings.controller.spec.js to use jasmine mock objects
added global helper functions to mock out /api/account and /i18n/*.json

### CODE REVIEW

**Comment by deepu105** [comment]
Looks neat and better than before +1

**Comment by deepu105** [comment]
Looks neat and better than before +1
I also like the way you have napped the templates from an array :)

**Comment by trevershick** [comment]
This is an attempt to establish a pattern for DI and mocking within the Angular specs.  If this is agreeable then i'll continue to write tests in this way and get full coverage (or as close as possible) with the rest of the application.

**Comment by jdubois** [comment]
Looks like some really neat code!

- In the index.js, can you also remove the old Health files? Have a look at the "removefile" method, used line 1093 at the moment
- this is quite a lot of changes, and I'm currently quite busy on the Spring Boot 1.3 side -> can other people from the dev team read again your code? @deepu105 did you have a close enough look, is it OK for you?

**Comment by andidev** [comment]
Correct me if I'm wrong but the remove is not needed since it is only the template that is moved.

**Comment by jdubois** [comment]
@andidev it is to remove the files for users who have generated their app with an older version

**Comment by andidev** [comment]
Yes but still I think that only the source location is changed and not the destination. I'll investigate it later.

**Comment by trevershick** [comment]
Right @andidev, the src (template) location was changed, not the destination on the user's path.

**Comment by andidev** [comment]
I see some minor tab issues in _password.controller.spec.js
We are using 4 spaces for tabs (soft tabs) in JHipster. Looks like there is a mixure of 2 spaces and 4 spaces in _password.controller.spec.js and maybe other files as well (haven't checked them all).

@trevershick
Could you fix this?

**Comment by trevershick** [comment]
@andidev - yep. sorry about that. I'll reformat those specs.  I'll commit the reformattings as a second commit in the PR.  It's been my experience that mixing reformatting and regular change commits can be a nightmare...

**Comment by trevershick** [comment]
Done.
You can verify the second commit is whitespace only with [this link](https://github.com/jhipster/generator-jhipster/commit/2d851e4222c2dbb5295a12efc5c38f137f0f0d77?w=0)

**Comment by deepu105** [comment]
Looks good enough to be merged +1

**Pull request merged**
