### PR TITLE
Create auto labeler workflow

### PR DESCRIPTION
**Pull request by mshima**
This PR creates a workflow for auto labeling based on the files the PR changes.
Doesn't cover every file, since this doesn't have been discussed yet.

Next steps for automation:
- create a team for every theme, based on https://docs.google.com/spreadsheets/d/1fac4Uxv3bKr0rNmgg1WXv67CE_6nfHEPIuCp-_iU-uA/edit#gid=0
- Add the team as reviewer using https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mshima** [comment]
Looks like it doesn't work for forks https://github.com/actions/labeler/issues/12.

Closing.

**Comment by mshima** [comment]
@DanielFran maybe it's time to recreate this PR.

The original problem has a fix:
```
on:
- pull_request_target
```
https://github.com/actions/labeler#create-workflow.

**Comment by DanielFran** [comment]
Now that labels are used due to the changelog, I am ok with it.

**Comment by pascalgrimaud** [comment]
Yes good idea

**Pull request closed without merging**
