### PR TITLE
add skip bower option

### PR DESCRIPTION
**Pull request by deepu105**
adds a flag to skip bower, useful when a client does not need bower, like for eg, React does things with npm instead of bower

### CODE REVIEW

**Comment by jdubois** [comment]
I see you've modified the Gradle build for that, don't you need to do the same thing for the Maven build?

**Comment by deepu105** [comment]
Oh totally forgot maven :P, ill add it

**Comment by deepu105** [comment]
@jdubois i couln't find where its done in the pom file, i couldnt see anything like that done there could you point the line if you know?

**Comment by deepu105** [comment]
probably maven doesnt have a gulp setup as well

**Comment by jdubois** [comment]
Have a look at the yeoman-maven-plugin it's out there

**Comment by deepu105** [comment]
ya i saw that its only for grunt and gulp, where is the bower task defined?
is it default in the plugin?

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes it is, and by the way we need to upgrade it to version 0.5

**Comment by deepu105** [comment]
im not a maven guy so not sure how to it here, can someone help

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
this is not required since we are removing grunt so closing

**Pull request closed without merging**
