### PR TITLE
Update spring-boot to 2.1.9.RELEASE, other dependencies and docker images

### PR DESCRIPTION
**Pull request by DanielFran**
Fix jhipster/generator-jhipster#10544

Depends on https://github.com/jhipster/jhipster/pull/424

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
Waiting spring-boot version available in maven repository!

**Comment by DanielFran** [comment]
Version is now available in maven repository: https://search.maven.org/artifact/org.springframework.boot/spring-boot/2.1.9.RELEASE/jar

**Comment by DanielFran** [comment]
Close/Reopen to launch tests

**Comment by DanielFran** [comment]
@pascalgrimaud It seems that we have again some issues with Travis cache!
You can see the error shown in https://travis-ci.org/jhipster/generator-jhipster/jobs/592769618#L4304:
````sh
[ERROR] Plugin org.springframework.boot:spring-boot-maven-plugin:2.1.9.RELEASE or one of its dependencies could not be resolved: Failure to find org.springframework.boot:spring-boot-maven-plugin:jar:2.1.9.RELEASE in https://maven-central.storage-download.googleapis.com/repos/central/data/ was cached in the local repository, resolution will not be reattempted until the update interval of google-maven-central has elapsed or updates are forced
````

Since in jhipster bom everything was OK (so I already merged it) and here in azure everthing is OK also, can you please clean cache of this PR, please?

Thanks

**Comment by pascalgrimaud** [comment]
I really don't understand what happened with Travis here...

**Comment by pascalgrimaud** [comment]
Ok, the culprit is Travis.
See https://travis-ci.community/t/disable-google-maven-central/5301

It used google-maven-central, which is probably a mirror and isn't sync yet with the official one.

**Comment by DanielFran** [comment]
Yep, I saw it yesterday. Strange is that on jhipster bom side I did not had this issue....
Thanks

**Comment by pascalgrimaud** [comment]
See https://travis-ci.community/t/continuous-maven-repo-403/3908/13 too

**Pull request merged**
