### PR TITLE
Node sass

### LINKED ISSUE #1469: Using node-sass instead of the ruby sass
Using Docker I noticed that is missing ruby in the Dockerfile, I put line of the configuration in Dockerfile but I think interesting to use the node-sass, am I wrong?

### LINKED ISSUE #1527: Use Node-sass instead of compass
Use Node-sass instead of compass as node-sass has better performance then compass and this will remove the ruby dependency for JH

Detailed discussion in below issue
https://github.com/jhipster/generator-jhipster/issues/1469#issuecomment-105192134

### PR DESCRIPTION
**Pull request by deepu105**
Switch to node-sass from compass

for grunt use grunt-sass plugin
for gulp use gulp-sass plugin

refactor `useCompass` variable to `useSass` for clarity

remove all reference of compass
add backward compatibility for existing compass users

Fix #1469
Fix #1527

### CODE REVIEW

**Comment by deepu105** [comment]
@gmarziou can you review this plz
@jdubois plz merge once reviewed

Its better to add this in next release after 2.20

**Comment by deepu105** [comment]
`The command "nvm install 0.12" failed and exited with 3 during .`

this is from travis , is it becoz of node-sass? can someone check this plz, im not getting any error in my setup (windows 10)

**Comment by gmarziou** [comment]
@deepu105  I also prefer useSass but what will happen to an existing .yo-rc.json? Will the useCompass  setting be automatically converted or is this a manual step to be dine by the project owner?

There are also some parts of the doc to update, I can help.

Sorry I don't know travis but the node version to be used by travis is configured in the .travis.yml file which you did not change. Maybe it's a temporary travis problem? Is there a way to retry?

**Comment by deepu105** [comment]
@gmarziou 
this line should take care of that
https://github.com/deepu105/generator-jhipster/commit/0bf29da4336a5f5f4c2e384cb1b6f6b7b259dc4c#diff-2018087f584c4398b5c3a23fc0e5f9dbR384

**Comment by gmarziou** [comment]
Great, I knew I could have missed it ;)

**Comment by deepu105** [comment]
@jdubois is it possible to rerun the failed travis check?

**Comment by gmarziou** [comment]
I adapted the docs except for your tip about concurrence in build

**Comment by deepu105** [comment]
Travis passed :smile:  mysterious :stuck_out_tongue_winking_eye:

**Comment by deepu105** [comment]
@gmarziou I guess the tip is fine as thats more relevant for concurrent, node sass already very fast so no use in a concurrent task

**Pull request merged**
