### PR TITLE
Upgrade springfox to 2.3.1 and enhance swagger-ui

### PR DESCRIPTION
**Pull request by cbornet**
Adds auth headers (such as CSRF,OAuth, ...) to springfox swagger-ui index.html (not using the webjar)
THis way we get all features from springfox such as support for multiple dockets.

### CODE REVIEW

**Comment by PierreBesson** [comment]
:+1: This is great ! I had realized that springfox needed to be upgraded to have multiples APIs in Swagger UI but I didn't know how to do what code needed to be added since in the springfox example they serve swagger-ui with the webjar. This is the real solution to [this](https://github.com/jhipster/jhipster-experimental-microservices/issues/7).

We absolutely need the "multiple dockets" springfox feature for our microservice gateway in order to aggregate automatically all the microservices swagger docs.

**Comment by cbornet** [comment]
Yes that's because of micro-services that I did this :smile: !

**Comment by cbornet** [comment]
Combine that with swagger code generation and it starts to make a fine cocktail !

**Comment by deepu105** [comment]
Awesome

**Pull request merged**
