### PR TITLE
Fix react development server and add GitHub action for dynamic workflows.

### PR DESCRIPTION
**Pull request by mshima**
- Fixes react development server
  - Update npm scripts
  - Update webpack config
  - Disable source-map to workaround https://github.com/jhipster/generator-jhipster/issues/16116
- Add build-matrix action to allow dynamic workflows for modularized tests
- Add trailing `--` to composite npm scripts.
  - Allows scripts to call others scripts passing escaped parameters (-- --arg) correctly.
Without needing double escaping `-- -- --arg`
- Add Dev Server workflow for testing webpack-devserver, browser sync and dev profile.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by Tcharl** [comment]
Reviewed, looks OK

**Comment by mshima** [comment]
Approved merging.

**Comment by deepu105** [comment]
@mshima I have assigned a bounty for this, please claim the same

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/52030

**Comment by pascalgrimaud** [comment]
@mshima : approved

**Pull request merged**
