### PR TITLE
Add microfrontend support to angular.

### PR DESCRIPTION
**Pull request by mshima**
Closes https://github.com/jhipster/generator-jhipster/issues/10189

- Needs --microfrontend option `jhipster jdl microservice.jdl --microfrontend`
- i18n is not loading.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
Wahoo! I'll take a look at this in a few hours.

**Comment by mraible** [comment]
I tried `jhipster jdl reactive-ms --microfrontend` and the `npm install` takes a lot longer than it used to. 

The creation process usually takes around 2 minutes, but this takes quite a bit longer. 

Screen Shot 2021-06-12 at 2 56 11 PM

**Comment by mraible** [comment]
Doh! This was probably caused by my Time Machine backup running. I killed it and tried again. It still seems to take twice as long as it did before.

Screen Shot 2021-06-12 at 3 14 40 PM

**Comment by mraible** [comment]
After generating everything, if I run the following command, things fail.

```
cd gateway
./gradlew
```

The error is:

```
[webpack-cli] Error: Cannot find module './webpack.microfrontend'
Require stack:
- /Users/mraible/reactive-stack/gateway/webpack/webpack.common.js
- /Users/mraible/reactive-stack/gateway/webpack/webpack.dev.js
- /Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/bootstrap.js
- /Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/bin/cli.js
- /Users/mraible/reactive-stack/gateway/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/mraible/reactive-stack/gateway/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/Users/mraible/reactive-stack/gateway/webpack/webpack.common.js:137:5)
    at module.exports (/Users/mraible/reactive-stack/gateway/webpack/webpack.dev.js:15:16)
    at /Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/webpack-cli.js:1565:43
    at Array.map (<anonymous>)
    at evaluateConfig (/Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/webpack-cli.js:1557:24)
    at /Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/webpack-cli.js:1589:21
    at async Promise.all (index 0)
    at async WebpackCLI.resolveConfig (/Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/webpack-cli.js:1587:38)
    at async WebpackCLI.createCompiler (/Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/webpack-cli.js:2045:22)
    at async WebpackCLI.buildCommand (/Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/webpack-cli.js:2173:20)
    at async Command.<anonymous> (/Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/webpack-cli.js:850:25)
    at async Promise.all (index 1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mraible/reactive-stack/gateway/webpack/webpack.common.js',
    '/Users/mraible/reactive-stack/gateway/webpack/webpack.dev.js',
    '/Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/webpack-cli.js',
    '/Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/lib/bootstrap.js',
    '/Users/mraible/reactive-stack/gateway/node_modules/webpack-cli/bin/cli.js',
    '/Users/mraible/reactive-stack/gateway/node_modules/webpack/bin/webpack.js'
  ]
}

> Task :webapp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webapp'.
> Process 'command '/Users/mraible/reactive-stack/gateway/.gradle/npm/npm-v7.16.0/bin/npm'' finished with non-zero exit value 2
```

**Comment by mshima** [comment]
Can you try with `--interactive` flag?

**Comment by mraible** [comment]
How do I use `--interactive`? If I do `./gradlew --interactive`, it fails.

```
Unknown command-line option '--interactive'.
```

**Comment by mshima** [comment]
Let me try with your jdl.

**Comment by mshima** [comment]
@mraible `jhipster jdl reactive-ms` is using vue client.

**Comment by mshima** [comment]
CI is using jhipster `--workspaces --monorepository --interactive --microfrontend --skip-jhipster-dependencies` flags.
But I think only `--microfrontend` is required.

`--workspaces` is for microservices npm scripts.
`--monorepository` for diff.
I am testing removing `--interactive` flag.

**Comment by mraible** [comment]
@mshima You're brilliant! I removed the `clientFramework` line from my JDL and I'm trying again. BRB.

**Comment by mraible** [comment]
@mshima It's really impressive that `npm run e2e` passes when running from the `gateway` project! I do see the i18n issue, but it's cool that e2e tests pass regardless. You are amazing!

Screen Shot 2021-06-12 at 4 28 54 PM

The only thing I think this is missing is the ability to develop the UI for the microservice as a standalone project. For example, it should be possible to start the `blog` app on `http://localhost:8081` and view/iterate on its UI. 

Screen Shot 2021-06-12 at 4 29 48 PM

**Comment by mshima** [comment]
> For example, it should be possible to start the `blog` app on `http://localhost:8081` and view/iterate on its UI.

Using `npm start` shows the ui, but I don’t think it successfully login.
I didn’t go that far.

**Comment by mraible** [comment]
I tried `npm start`. It spits out a couple of warnings but is otherwise successful:

```
Warning:
/Users/mraible/reactive-stack/blog/src/main/webapp/app/app-routing.module.ts
  7:10  warning  'Authority' is defined but never used               @typescript-eslint/no-unused-vars
  9:10  warning  'UserRouteAccessService' is defined but never used  @typescript-eslint/no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

** Angular Live Development Server is listening on localhost:4201, open your browser on http://localhost:4201/ **
```

Then, it results in an invalid redirect URI from Keycloak. Maybe the `start` script should have a `--port 8081` flag like we use [for Ionic](https://github.com/oktadev/ionic-jhipster-starter/blob/main/ionic.starter.json#L12)?

```
"start": "ng serve --port 8081",
```

If I add this and go to `http://localhost:8081/login`, I see the following:

Screen Shot 2021-06-12 at 4 59 45 PM

**Comment by mshima** [comment]
> If I add this and go to `http://localhost:8081/login`, I see the following:

I don’t think login is exposed in microservices.
But you are the expert in this case.

maybe is possible do redirect to gateway api at:
https://github.com/jhipster/generator-jhipster/blob/0cf6ad72084883a43432660c3337dc397b2f68df/generators/client/templates/angular/webpack/proxy.conf.js.ejs#L38

**Comment by mshima** [comment]
> maybe is possible do redirect to gateway api at:
> 
> https://github.com/jhipster/generator-jhipster/blob/0cf6ad72084883a43432660c3337dc397b2f68df/generators/client/templates/angular/webpack/proxy.conf.js.ejs#L38

It works.

For now we will need to require gateway for login, api route, liquibase, anything else?

**Comment by mraible** [comment]
One issue I discovered is you can't modify the blog's files and get hot-reloading. The change is recognized in the blog project and recompilation happens, but the gateway is not aware of it and doesn't refresh the browser. If you manually refresh, it works.

**Review by mraible — APPROVED** [review]

**Comment by mshima** [comment]
I will create a new PR with patches to microfrontend to don't make this PR bigger.

>  It still seems to take twice as long as it did before.

It generates client files for every microservice.

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/43096.

**Comment by pascalgrimaud** [comment]
@mshima : approved

**Comment by gmarziou** [comment]
@mshima where can I find some documentation about this new option?

**Comment by mshima** [comment]
@gmarziou, there isn't any yet, it was merged as a prototype.
What kind of information are you looking for?

Microfrontend is not officially supported by angular, so this is really a feature preview.

Where to improve?
- Try to make the menu lazy, so the gateway will not have to know every microservice entity, only the microservice.
Should simplify the discovery logic I've applied to link gateway and microservice like https://github.com/jhipster/generator-jhipster/blob/fd3fffdea58955caf0c941f71ae26addf5b83545/generators/client/templates/angular/src/main/webapp/declarations.d.ts.ejs#L5-L12
- Shared ng-jhispter: module federation provides shared libraries support, so that a single instance of a library is shared.
We are currently using common lib without treating it as a library, this makes difficult to share and some part may be using more than one instance.
So we should refactor the common code and create some public apis for common code, even generate it as a package.
The following should be reduced to a at most 3 entries.
https://github.com/jhipster/generator-jhipster/blob/fd3fffdea58955caf0c941f71ae26addf5b83545/generators/client/templates/angular/webpack/webpack.microfrontend.js.ejs#L64-L138
- A microservice doesn't run at it's own, we should implement a way to run the gateway inside a docker instance and use the Microfrontend from dev web server to make easier to develop microservices.
- We may want to move e2e to microservice side too.

I think we should add something like the following to the docs, but not sure were to put:
### Microfrontend feature preview.

JHipster provides experimental microfrontend using webpack module federation and angular framework with the `--microfrontend` flag.

More information about module federation can be found at https://webpack.js.org/concepts/module-federation/ and https://webpack.js.org/plugins/module-federation-plugin
Angular microfrontend proposal can be tracked at https://github.com/angular/angular-cli/issues/17556.

**Comment by gmarziou** [comment]
Thanks it helps, I did not understand this was a prototype.

About where to put the doc, I would say that if it's specific to Angular then it should be put here: https://www.jhipster.tech/using-angular/

If other frameworks provide similar feature, I guess that some introduction about the common architecture choices should have its own chapter like microservices.

For instance, production deployment is not clear yet to me. I thought that each microservice would serve its won microfrontend but it seems I'm completely wrong.

Also, I did not play with it yet, so I'm not sure where the source files are located, on the gateway?

**Comment by mshima** [comment]
> I thought that each microservice would serve its won microfrontend but it seems I'm completely wrong.

Yes, each microservice serves its own microfrontend, they have a complete frontend + its entities.
When running using gateway, only the entity part is (should) be loaded.
But the microservice doesn't exposes authentication api, so it's not possible to run on its own.
Maybe we should expose that too.

How this module federation works?
- Most of webpack optimizations must be disabled. We really don't know every feature a microservice uses from a lib, so the lib should be complete.

This is the webpack chunk from https://github.com/jhipster/generator-jhipster/runs/2865151618:
- gateway
```
Lazy Chunk Files                                                                                                             | Names     |      Size
85
node_modules_fortawesome_free-solid-svg-icons_index_es_js.6ec15aafe65cbc619857.js                                            | -         | 657.02 kB
86
node_modules_angular_core___ivy_ngcc___fesm2015_core_js.59ea6211cbcf1d644e9d.js                                              | -         | 235.97 kB
87
default-node_modules_ng-bootstrap_ng-bootstrap___ivy_ngcc___fesm2015_ng-bootstrap_js.90e8e73b2d8d95420615.js                 | -         | 224.73 kB
88
src_main_webapp_app_admin_metrics_metrics_module_ts.cc6d914f5167690e9fbd.js                                                  | -         |  75.75 kB
89
src_main_webapp_bootstrap_ts.b90235a7fc4a1fee54dd.js                                                                         | -         |  72.42 kB
90
default-node_modules_angular_router___ivy_ngcc___fesm2015_router_js.e23b76a4c8cbbd680cdb.js                                  | -         |  72.05 kB
91
default-node_modules_angular_forms___ivy_ngcc___fesm2015_forms_js.9ebd231be203ebce70b1.js                                    | -         |  58.81 kB
92
default-node_modules_angular_common___ivy_ngcc___fesm2015_common_js.a7fd5ef4503df2a9eb1f.js                                  | -         |  55.99 kB
93
node_modules_rxjs__esm2015_operators_index_js.55249f1bff48b5856f76.js                                                        | -         |  50.21 kB
94
node_modules_fortawesome_fontawesome-svg-core_index_es_js.b173371485dc94662234.js                                            | -         |  38.76 kB
95
default-node_modules_rxjs__esm2015_internal_AsyncSubject_js-node_modules_rxjs__esm2015_intern-0da67e.f3facb28422a1ab8c625.js | -         |  36.02 kB
96
default-node_modules_angular_platform-browser___ivy_ngcc___fesm2015_platform-browser_js.0bb6cdaaaccb7b1e53b8.js              | -         |  23.76 kB
97
default-node_modules_angular_common___ivy_ngcc___fesm2015_http_js.40358b978ed77f66a700.js                                    | -         |  19.12 kB
98
default-node_modules_ngx-translate_core___ivy_ngcc___fesm2015_ngx-translate-core_js.fca37b3aae9fe4013846.js                  | -         |  14.81 kB
99
src_main_webapp_app_admin_health_health_module_ts.10ecb97128f2c1a2985b.js                                                    | -         |  11.57 kB
100
default-node_modules_fortawesome_angular-fontawesome___ivy_ngcc___fesm2015_angular-fontawesome_js.2439680d0f31b8b0d872.js    | -         |  11.25 kB
101
src_main_webapp_app_admin_configuration_configuration_module_ts.1b81c427ae33a4930129.js                                      | -         |  10.12 kB
102
node_modules_rxjs__esm2015_index_js.1f25beb9ebc41bff869f.js                                                                  | -         |   9.69 kB
103
default-node_modules_ngx-webstorage___ivy_ngcc___fesm2015_ngx-webstorage_js.a40e7f7b300bddc59ef7.js                          | -         |   9.57 kB
104
src_main_webapp_app_admin_gateway_gateway_module_ts.9addbe88f1f24b809deb.js                                                  | -         |   9.21 kB
105
src_main_webapp_app_admin_logs_logs_module_ts.575a0e7d7223214d07df.js                                                        | -         |   9.17 kB
106
default-node_modules_ngx-infinite-scroll___ivy_ngcc___modules_ngx-infinite-scroll_js.238536e764484a004e29.js                 | -         |   6.86 kB
107
node_modules_dayjs_dayjs_min_js.2eac7d0a73c81a811d78.js                                                                      | -         |   6.25 kB
108
common.5b08dbc5aa2638d89de2.js                                                                                               | common    |   2.69 kB
109
src_main_webapp_app_admin_admin-routing_module_ts.2d8f66dc7df5de4227f1.js                                                    | -         |   1.29 kB
110
src_main_webapp_app_admin_docs_docs_module_ts.58b76b578e36f77e9e4c.js                                                        | -         | 986 bytes
111
node_modules_ngx-translate_http-loader___ivy_ngcc___fesm2015_ngx-translate-http-loader_js.03432ec2eb6e172cd3ed.js            | -         | 399 bytes
112
```
- blog
```
Lazy Chunk Files                                                                                                             | Names     |      Size
326
node_modules_fortawesome_free-solid-svg-icons_index_es_js.349a9dfb1741d07ef558.js                                            | -         | 657.01 kB
327
node_modules_angular_core___ivy_ngcc___fesm2015_core_js.a7581b19a8fac0a061f8.js                                              | -         | 235.97 kB
328
default-node_modules_ng-bootstrap_ng-bootstrap___ivy_ngcc___fesm2015_ng-bootstrap_js.fc2b878ce826e40e95ba.js                 | -         | 224.72 kB
329
default-node_modules_angular_router___ivy_ngcc___fesm2015_router_js.7625132d655c3e9c4661.js                                  | -         |  72.05 kB
330
default-node_modules_angular_forms___ivy_ngcc___fesm2015_forms_js.a4cf66a8fe95ece3f537.js                                    | -         |  58.81 kB
331
src_main_webapp_bootstrap_ts.504e206e5a21ea6e1e81.js                                                                         | -         |  57.83 kB
332
default-node_modules_angular_common___ivy_ngcc___fesm2015_common_js.6d06261195d418e207d7.js                                  | -         |  55.99 kB
333
default-src_main_webapp_app_entities_blog_post_post_module_ts.0d9214252e8930139736.js                                        | -         |  50.32 kB
334
node_modules_rxjs__esm2015_operators_index_js.5b21a2a19a3eb71f6dd0.js                                                        | -         |  50.20 kB
335
default-src_main_webapp_app_entities_blog_blog_blog_module_ts.f94720e51fb8b75c8f3c.js                                        | -         |  44.58 kB
336
node_modules_fortawesome_fontawesome-svg-core_index_es_js.b128a518c87a0ad2d9e8.js                                            | -         |  38.75 kB
337
default-node_modules_rxjs__esm2015_internal_AsyncSubject_js-node_modules_rxjs__esm2015_intern-0da67e.646accdd8d72d72fbd8c.js | -         |  36.01 kB
338
default-src_main_webapp_app_entities_blog_tag_tag_module_ts.dcef5ffede86dcb0a616.js                                          | -         |  30.72 kB
339
default-node_modules_angular_platform-browser___ivy_ngcc___fesm2015_platform-browser_js.0f590764a53e9245d4ec.js              | -         |  23.76 kB
340
default-node_modules_angular_common___ivy_ngcc___fesm2015_http_js.be7e26e4d0f35fab3f17.js                                    | -         |  19.11 kB
341
default-node_modules_ngx-translate_core___ivy_ngcc___fesm2015_ngx-translate-core_js.6e48674909c9e0b43583.js                  | -         |  14.80 kB
342
default-src_main_webapp_app_core_auth_user-route-access_service_ts-src_main_webapp_app_core_u-31daed.673792eadb4469052494.js | -         |  11.61 kB
343
default-node_modules_fortawesome_angular-fontawesome___ivy_ngcc___fesm2015_angular-fontawesome_js.44faace8ba4f960e9874.js    | -         |  11.25 kB
344
node_modules_rxjs__esm2015_index_js.41ff7d24c925ff7d1298.js                                                                  | -         |   9.68 kB
345
default-node_modules_ngx-webstorage___ivy_ngcc___fesm2015_ngx-webstorage_js.b8813aa722409ce6c58b.js                          | -         |   9.57 kB
346
common.d2086cb1832645d8e0fb.js                                                                                               | common    |   8.20 kB
347
default-node_modules_ngx-infinite-scroll___ivy_ngcc___modules_ngx-infinite-scroll_js.c110ff8013b00d1455b1.js                 | -         |   6.86 kB
348
node_modules_dayjs_dayjs_min_js.6e437a037d2ec897c0a5.js                                                                      | -         |   6.24 kB
349
node_modules_ngx-translate_http-loader___ivy_ngcc___fesm2015_ngx-translate-http-loader_js.f96a27eeaea2682e3b3f.js            | -         | 393 bytes
350
src_main_webapp_app_config_pagination_constants_ts.ae04a84a9ef241dd109f.js                                                   | -         | 249 bytes
351
src_main_webapp_app_config_input_constants_ts.33514505fa7d45311853.js                                                        | -         | 238 bytes
352

```

I'm not sure why the names aren't equal, used to be in angular 11, probably some config fine tuning.
So when loading tag entity from blog microservice entity inside a gateway, the frontend should only load `default-src_main_webapp_app_entities_blog_tag_tag_module_ts.dcef5ffede86dcb0a616.js` and reuse everything else.

**Comment by mraible** [comment]
I think we should consider adding an app shell and login to a microservice when microfrontends is selected. That way, you could develop it independently. For OAuth, the backend should only need two changes:

- Add oauth2Login() to security config
- Add Keycloak Docker Compose and related files

**Pull request merged**
