### PR TITLE
Add SB cloud connectors starter

### LINKED ISSUE #4346: [FEATURE] Add SpringBoot cloud connectors starter
##### **Overview of the issue**

Add SpringBoot cloud connectors starter
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-cloud-connectors/1.4.1.RELEASE

##### **Motivation for or Use Case**

It will reduce dependencies in pom.

##### **Suggest a Fix**

I can create a PR.

##### **JHipster Version(s)**

version 3.9.1

### PR DESCRIPTION
**Pull request by nkolosnjaji**
Add spring boot cloud connectors starter for maven and gradle

FIX #4346

### CODE REVIEW

**Comment by jdubois** [comment]
I see it also adds the Heroku connector, can you check if this makes a difference for our Heroku sub-generator?
Code is at https://github.com/jhipster/generator-jhipster/tree/master/generators/heroku

**Comment by nkolosnjaji** [comment]
sure, I will give it a try

**Comment by gmarziou** [comment]
I'm not sure but it seems this adds dependencies but to depdencyMaganement section like when importing a pom so does it mean that an app not using Heorku will get heroku jars anyway.

**Comment by nkolosnjaji** [comment]
@gmarziou yes, herorku jars will be included. I think it is not a problem because jhipster includes cloudfondry jars(even if it doesn't use them)  and not everybody is going to deploy apps to CF. Anyway, it's good to include all connectors because once you build the app, you can move it to different cloud providers.

**Comment by jdubois** [comment]
That's basically what we already do, but in fact I'm not happy with that... How big are those JARs? I don't want to have too much useless stuff in our generated app.
We could add them in the pom when we run the sub-generators -> that wasn't the case at the time it was coded, but we now have an API for that.

**Comment by nkolosnjaji** [comment]
I give few tries with heroku generator without luck. I didn't add credit card to my herou account so it must be some weird combination with my account type when generator tries to create db

**Comment by nkolosnjaji** [comment]
heroku cloud connector jar is 7Kb.

https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-heroku-connector/1.2.3.RELEASE

**Comment by jdubois** [comment]
OK, then it would be cleaner to add those JARs with the sub-generator (same thing for Cloud Foundry), but that's so small that we don't really care... Let's do this.

**Comment by jdubois** [comment]
I'm restarting your build because it failed, but this is probably a Travis issue... So I probably won't be able to merge it now, but +1 for me (as long as the build passes!)

**Comment by pascalgrimaud** [comment]
I think it's a Travis issue on the new build uaa. I need to investigate why it failed so often...

**Comment by jdubois** [comment]
I don't understand what happened: GitHub sent an error when I clicked on the merge button, and now the PR isn't merged but the code is in the master... So this looks OK and I'm closing this, but very weird...

**Comment by pascalgrimaud** [comment]
@nkolosnjaji : maybe it's because you didn't configure your local git configuration with appropriate name + email ??
We can see it in: https://github.com/jhipster/generator-jhipster/pull/4349/commits
There is no link to your github account

**Comment by nkolosnjaji** [comment]
oh yes :(

I was using github with my ssh key... Now I added that email to my github acc. Do I need to do anything more ?

**Comment by pascalgrimaud** [comment]
I dont know, maybe try your config in one of your own repositories to confirm

**Pull request closed without merging**
