### PR TITLE
fix jhipster/generator-jhipster#6353

### PR DESCRIPTION
**Pull request by pierre-filliolaud**
- Please make sure the below checklist is followed for Pull Requests.

- [X] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X] Tests are added where necessary
- [X] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

This fix is for issue #6353.

### CODE REVIEW

**Comment by jdubois** [comment]
Sorry I just merged #6356 a few seconds ago, which does the same thing - next time please write a better title, I didn't understand what this was, that's why I missed it

**Comment by pierre-filliolaud** [comment]
Hi @jdubois, 
sorry about that. I tried to find a way to write good title for PR but I did not find any pattern for that.
Title: Fix module-name#issue-number

Could you please add a title sample (or title pattern) as default comment?

Regards,
Pierre

**Comment by jdubois** [comment]
In fact it's me who is sorry @pierre-filliolaud as I missed your PR, which was there earlier. Typically we put in the title what the PR does (like #6356 ), and can copy/paste some title from the original ticket.

**Comment by pierre-filliolaud** [comment]
No problem :)

**Comment by jdubois** [comment]
Well, as it was your first contribution, it wasn't very nice from me! Also, it's bad for our stats, I'd like to reach 400 contributors :-)

**Comment by pierre-filliolaud** [comment]
Sorry, I am already count as contributor. I know without any commit yet but hope to contribute more (BigChainDb...). :-/

**Comment by jdubois** [comment]
Oh, this is because your have the "first time GitHub contributor" on this PR

**Comment by deepu105** [comment]
@jdubois Ya but still doesn't count towards a total number of contributors :) what happens if we open this and merge it?

**Comment by jdubois** [comment]
Oh that would be cheating @deepu105 , let me try

**Comment by jdubois** [comment]
Looks OK :-)

**Comment by deepu105** [comment]
ha ha ya but its totally fair to @pierre-filliolaud

**Comment by pierre-filliolaud** [comment]
Thank you guys!

**Pull request merged**
