### PR TITLE
Adding DB Check before running entity subgenerator

### LINKED ISSUE #3267: Should not allow to generate entity when DB is none
##### **Overview of the issue**

When attempting to generate a new entity on a fresh JHipster project there are multiple failures.  

Adding a new field to the entity never asks for a data type and is always "undefined".  This appears to cause multiple issues downstream when trying to generate the object (which never gets created).

I can post all of the traces if you like, but I"m pretty sure that they are all due to the missing data type for the new field.

Note that this only seems to happen on the "microservice" project type.

##### **JHipster Version(s)** 

3.0.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "corey",
    "packageName": "com.goldstartransportation.loadorg.web",
    "packageFolder": "com/goldstartransportation/loadorg/web",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": "no",
    "buildTool": "gradle",
    "jwtSecretKey": "asdfasdfa",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "skipClient": true,
    "skipUserManagement": true,
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

This never gets created

##### **Reproduce the error** 

Create new app using yo jhipster
Attempt to add a new entity

### PR DESCRIPTION
**Pull request by wmarques**
Fix #3267 
I'm not fan of my warning message but I couldn't find a better one, if you guys have a better one please let me know

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Maybe exit immediatly, instead ?

**Comment by deepu105** [comment]
This.env.error exists immediately

**Comment by pascalgrimaud** [comment]
I'm tired :tired_face: you're right

**Comment by deepu105** [comment]
Im changing the error message btw :wink:

**Pull request merged**
