### PR TITLE
extract all option in their dedicated constant files

### PR DESCRIPTION
**Pull request by Tcharl**
Set the different constants in their dedicated 'types' file in order to reuse them in all js files and templates.

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by Tcharl** [comment]
It looks like I messed up with rebasing, and have no real way to fix it...

**Comment by pascalgrimaud** [comment]
It should clean the history:
- save your current branch
- reset --hard upstream/main
- cherry pick your commit

**Comment by Tcharl** [comment]
Thank you @pascalgrimaud , made the trick :-)

**Comment by Tcharl** [comment]
OK to merge: CI errors are timeouts...

**Review by MathieuAA — APPROVED** [review]
LGTM, thanks

**Pull request merged**
