### PR TITLE
use formstate instead of classes for validation

### LINKED ISSUE #3703: "show-validation" directive is not in sync with the input validation
##### Form Validation Issue

This bug is seen for all form validations

##### Appears on all Forms (Dialogs)

Form group unnecessarily turns red even when the input box has correct data

##### All Versions

This is there in all versions of JHipster.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
{
  "generator-jhipster": {
    "jhipsterVersion": "3.4.0",
    "baseName": "XXXX",
    "packageName": "XXX",
    "packageFolder": "XXX",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "XXX",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
Default App

##### **Browsers and Operating System** 
Firefox on Windows and Linux

##### **Reproduce the error** 
1. On Home Page, From Menu, Go to Sign In and Forgot Password
2. Enter abc@g. **No error in this value - CORRECT**
3. Enter backspace 
4. Screen will have abc@ and it will show validation errors. But there is no Red Border for Form Group. 
5. Now enter a character "g". Screen should show abc@g. Now the Red border appears - AFTER validation errors disappear. **No Error in this value - RED BORDER INCORRECT**
6. This is a disconnect. Red Border should have appeared along with error message in Step 4 and disappear in Step 5, whereas it appeared freshly in Step 5.
7. This happens in ALL forms ALL fields and is more prominent for other validations.

##### **Related issues** 

Not Applicable

##### **Suggest a Fix** 

**The problem is most probably because of the screen value and model value not being in sync.**

See Code and Screenshots below

This is the code which is causing the problem: src/main/webapp/app/components/form/show-validation.directive.js.

```
                if ($inputs.length > 0) {
                    $inputs.each(function() {
                        var $input = angular.element(this);
                        scope.$watch(function() {
                            return $input.hasClass('ng-invalid') && $input.hasClass('ng-dirty');
                        }, function(isInvalid) {
                            $formGroup.toggleClass('has-error', isInvalid);
                        });
                    });
                }
```

noerror

error

### PR DESCRIPTION
**Pull request by atomfrede**
close #3703

### CODE REVIEW

**Comment by ruddell** [comment]
Tested and it works for me. 👍 Nice fix to a longstanding issue

**Comment by atomfrede** [comment]
Then let's Merge it.

**Comment by jdubois** [comment]
Great job! I couldn't find this solution!

**Comment by gvsrini** [comment]
Good job indeed!

**Pull request merged**
