### PR TITLE
[react] React v17.0 First RC / Migrate Enzyme to Testing Library

### PR DESCRIPTION
**Pull request by qmonmert**
React v17.0 First Release Candidate is available: **17.0.0-rc.0** 🚀 
[https://reactjs.org/blog/2020/08/10/react-v17-rc.html](https://reactjs.org/blog/2020/08/10/react-v17-rc.html)

This version is not compatible with Enzyme ❌
I speak with **Dan Abramov** on Twitter and he encourages to use Testing Library rather than Enzyme ✅

So in this PR, I used the new RC and I migrated Enzyme to Testing Library 🛠

image

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
Relaunched tests

**Comment by qmonmert** [comment]
> Relaunched tests

ok

**Comment by MathieuAA** [comment]
Having tested both, I must say testing library is great!

**Comment by mshima** [comment]
@qmonmert if @testing-library/react is the way to go, you should consider creating a PR migrating react 16 to it.

**Comment by qmonmert** [comment]
@mshima I will do that

**Comment by qmonmert** [comment]
@mshima PR to migrate Enzyme to Testing Library https://github.com/jhipster/generator-jhipster/pull/12261

cc @MathieuAA

**Comment by qmonmert** [comment]
@mshima @MathieuAA @DanielFran @pascalgrimaud I close this PR because now we upgrade Enzyme to Testing Library in this PR https://github.com/jhipster/generator-jhipster/pull/12261 so I opened a PR to migrate to React v17 https://github.com/jhipster/generator-jhipster/pull/12270

**Pull request closed without merging**
