### PR TITLE
Add gitter badge to README

### PR DESCRIPTION
**Pull request by cbornet**

### CODE REVIEW

**Comment by jdubois** [comment]
I don't want to add lots of badges here -> my goal is to redirect everyone to the main jhipster.github.io site, and have everything at one place.

Then I haven't used the chat for VERY long, and it looks quite active, that's a good surprise!

**Comment by cbornet** [comment]
OK. Then this PR can be closed.
Though I don't know if a lot of people go to the "Help and bugs" page of  jhipster.github.io to find the link to the chat room... They eventually open a useless issue on gh...

**Comment by jdubois** [comment]
Yes, they don't read the guidelines, that's a huge problem

**Comment by pascalgrimaud** [comment]
I love badges with http://shields.io/ but we shouldn't add too much of them.
Travis is the most important, but maybe https://img.shields.io/npm/v/generator-jhipster.svg too ?

**Comment by cbornet** [comment]
Then maybe there could be a direct link to the "Help and bugs" page from the README

**Comment by jdubois** [comment]
@cbornet yes we should:

- Have one single page that explains everything clearly -> that's the help & bugs page
- Everywhere needed, link to this page

**Pull request closed without merging**
