### PR TITLE
[React] Add ability to login with OAuth

### PR DESCRIPTION
**Pull request by mraible**
This PR makes it possible to login with OAuth when you've selected that option.

@deepu105 This works and shows the user logged in on the homepage. However, it doesn't seem to pass `isAuthenticated` correctly to the `Header` component. Can you please take a look and see if you can fix it?

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
Yes I can look at it tomorrow

**Comment by mraible** [comment]
Nevermind, I got it working! 🎉 https://twitter.com/mraible/status/972247018218409984

**Comment by jdubois** [comment]
Congrats!

**Comment by mraible** [comment]
This doesn’t work with Okta yet, so I still have some work to do.

**Comment by deepu105** [comment]
@mraible we can improve it seperately

**Comment by mraible** [comment]
@deepu105 I discovered my issue with Okta was caused by having the following setting:

```
export SECURITY_OAUTH2_RESOURCE_JWK_KEY_SET_URI="https://dev-158606.oktapreview.com/oauth2/default/v1/keys"
```

Once I commented that out, everything works!

**Comment by deepu105** [comment]
awesome, maybe we can document it


Thanks & Regards,
Deepu

**Pull request merged**
