### PR TITLE
allow javadoc comments before and after enum values

### LINKED ISSUE #15185: jdl enum section cannot have java comments
##### **Overview of the issue**
Javadoc comments /** this style */ are not allowed for enum values.

Stacktrace:

```
error: Syntax error message:
        MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
Error during import-jdl: Error: MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
Error: MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
    at throwErrorAboutInvalidToken (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\parsing\api.js:85:9)
    at throwParserError (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\parsing\api.js:72:5)
    at getCst (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\parsing\api.js:57:5)
    at Object.parse (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\parsing\api.js:40:15)
    at callApiMethod (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\readers\jdl-reader.js:98:30)
    at parse (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\readers\jdl-reader.js:84:25)
    at Object.parseFromFiles (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\readers\jdl-reader.js:43:10)
    at parseFiles (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\jdl-importer.js:129:20)
    at createImporterFromFiles (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\jdl\jdl-importer.js:61:19)
    at JDLProcessor.importJDL (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\cli\import-jdl.js:356:18)
ERROR! Error during import-jdl: MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
Error: Error during import-jdl: MismatchedTokenException: Found an invalid token '/** comment */', at line: 43 and column: 20.
        Please make sure your JDL content does not use invalid characters, keywords or options.
    at module.exports (C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\cli\import-jdl.js:482:27)
    at C:\Users\Joro\AppData\Local\nvs\node\14.17.0\x64\node_modules\generator-jhipster\cli\jdl.js:61:49
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
```

##### **Motivation for or Use Case**

Documentation state:
"Just like relationships, entities and fields, commenting is possible for enums, with the same rules."

https://www.jhipster.tech/jdl/enums

##### **Reproduce the error**

Try to add Javadoc comment for a enum value. 

##### **JHipster Version(s)**

JHipster 7.0.1

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
Example JDL part:
enum NonWorkingDayType2 {
  OFFICIAL_HOLIDAY /** comment */,
  COMPANY_NON_WORKING_DAY
}
  </pre>
  </details>

##### **Browsers and Operating System**

Windows 10 

- [X ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by nomuna**
Fix #15185

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by MathieuAA** [comment]
LGTM, I have one question: do you want the comments to appear in the generated files as well?
If that's the case, then a bit more work is needed.

**Comment by nomuna** [comment]
@MathieuAA As far as the description of this bug goes the issue is that the parser is causing an issue
since the grammar doesn't allow comments next to the enum values. There is no information if they want it in the 
generated java code.

They are right that it was documented as possible but not really working.

Current state is that even the comments on enum itself is also not carried over to the java code.

```sh
/** This comment will be taken into account */
enum Country {
  // But not this one!
  FRANCE
}
```

As I understood in this issue, there is no information if they want the comments to be in the generated java classes. So as for this specific case the PR is complete, I think?

In #14869 they want it in the swagger info. I am not even sure if it is doable. So I guess my PR only solves the 
parser issue for #14869. So may be I should update my PR to remove the 'Fix #14869' from the comment.

Example from #14869

```sh
enum myEnum { V1 /** value1 */, V2 /**value2 */, V3 }
```

Their example doesn't contain a javadoc for V3. As a rule for javadoc the comment should precede the enum keys but they 
write it in the back which makes me think we should may be just allow javadoc in front of an enum key.

**Comment by MathieuAA** [comment]
@nomuna great, thanks!

**Review by MathieuAA — APPROVED** [review]

**Comment by MathieuAA** [comment]
> In #14869 they want it in the swagger info. I am not even sure if it is doable. So I guess my PR only solves the
parser issue for #14869. So may be I should update my PR to remove the 'Fix #14869' from the comment.

it would be a good idea :)

**Comment by nomuna** [comment]
Hi @MathieuAA,

do you have a write access? Are you supposed to merge it or should I request for someone in the jhipster chat?

Have a nice day.

**Pull request merged**
