### PR TITLE
Grab latest SolutionStackName dynamically (see #1863) and add PostgreSQL support to AWS subgen

### PR DESCRIPTION
**Pull request by wuethrich44**
(Sry author name is broken)

### CODE REVIEW

**Comment by jdubois** [comment]
I can't test this, so I can believe you it's correct :-)

**Comment by wuethrich44** [comment]
Thanks next database will be oracle. @jdubois Do you have any stats about the subgenerator usage?

**Comment by jdubois** [comment]
@wuethrich44 yes it's unfortunately very low (68 this month).
I'm guessing people are not ready to run something that would provision boxes for them, with their credit card enabled: if there is any bug or hidden stuff, that would cost them money.
We would need to have something that "certifies" this is working correctly.

**Comment by wuethrich44** [comment]
Ok that's sad...

We should have a sponsored account and proper tests against the AWS API. I can do that but only if I have a proper account. Could you do some advertising (e. g. Twitter) to get a sponsored account?

**Comment by jdubois** [comment]
We've already had a couple of people who proposed to sponsor this, but I don't know how a free project like ours could get any sponsor's money, or spend it...

**Comment by wuethrich44** [comment]
Aha ok I understand but I only need an access key with some permissions so I think this should be possible because it's no "money" :grin: Is it possible that I can contact some of these people or don't you want a sponsored account?

**Comment by jdubois** [comment]
Yes, at least I know that @mraible was interesting in sponsoring an AWS account, you can ask him

**Pull request merged**
