### PR TITLE
Change modal and progressbar in metrics & health screens to directives

### PR DESCRIPTION
**Pull request by deepu105**
Change modal and progressbar in metrics & health screens to angular ui directives
this makes health and metrics screens cleaner and less boilerplate code

### CODE REVIEW

**Comment by jdubois** [comment]
@deepu105 I'm not merging this until you tell me it's ok!

**Comment by deepu105** [comment]
@jdubois this is definitely better than what we had before, i have been doing this way always, anyway as gzombor suggested ill split the modal to seperate html file and will push another commit to this pull, you can merge after that

**Comment by deepu105** [comment]
@jdubois I have changed the code to make modals into separate files as per suggestion by @gzsombor 

I have tested with both dev and prod profile, you can merge if you think its ok

**Comment by jdubois** [comment]
All this work for 22 lines less :-)

**Comment by deepu105** [comment]
@jdubois couldn't stand seeing a non directive component when it was available on stack anyway :D

**Pull request merged**
