### PR TITLE
Added .idea to the ignored files for jhipster-upgrade

### PR DESCRIPTION
**Pull request by Ckram**
Pull request for the issue https://github.com/jhipster/generator-jhipster/issues/5618

### CODE REVIEW

**Comment by cbornet** [comment]
We should find a more generic solution for this. Your IDE could be Eclipse or VSCode and the files to ignore would be different.

**Comment by Ckram** [comment]
Maybe we can do it with each of them, Or ignore all the files/directories starting with a dot ?

**Comment by deepu105** [comment]
What about reading the .gitignore file of the project and ignoring them along with the current ones?

**Comment by jdubois** [comment]
Those other solutions would be very hard to do... Ignoring just a few files like this looks a lot easier to me, and at least that fixes the issue right now, so I'm happy with it.

**Pull request merged**
