### PR TITLE
fix the newline in the service implementation

### PR DESCRIPTION
**Pull request by massimosiani**
Hi, this is a tiny fix for the ServiceImpl.java template. Just adding a newline, as the result bothers me a little.
Let me know if you want me to open an issue.

Thank you for your job!
Massimo

### CODE REVIEW

**Comment by DanielFran** [comment]
This should be merged in master and v5 branch

**Comment by murdos** [comment]
You're right, @DanielFran . 
@massimosiani : Could you rebase your branch on branch v5.x_maintenance ?
We'll merge it on maintenance branch, and I guess we'll regularly merge fixes from maintenance branch to master.

**Comment by murdos** [comment]
Thanks @massimosiani !

**Comment by DanielFran** [comment]
@massimosiani can you create another PR for master branch?

**Comment by massimosiani** [comment]
@DanielFran of course, give me a couple of hours please.

**Pull request merged**
