### PR TITLE
Fix Swagger UI for Microservices

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix https://github.com/jhipster/generator-jhipster/issues/8328

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
I'm sorry @pascalgrimaud but this is only a partial fix. The BasePathRewriting filter was there for a reason, without it the "try it out" button won't work at all.

Please leave me some time to try to fix it instead. I'm aware of the problem since about a week but I have not had the time to recreate and debug this properly. It's just a matter of adding some code to fix the unzipping of the swagger json docs.

**Comment by pascalgrimaud** [comment]
Oh ok, @PierreBesson : I didn't try to add some entities yet.
I will test with entities. If it doesn't work, we need to keep this class and recode some part to be consistent with the new SendResponseFilter

**Comment by pascalgrimaud** [comment]
Here all my analyze: https://github.com/jhipster/generator-jhipster/issues/8328#issuecomment-425416985

**Comment by pascalgrimaud** [comment]
Just tested with entities and the "Try it out" button works fine.

**Comment by PierreBesson** [comment]
Maybe for the gateway but not for the microservices.

**Comment by pascalgrimaud** [comment]
My tests:
Registry -> "Try it out" works for itself, Gateway and Microservice
Gateway -> "Try it out" works for itself and Microservice

**Comment by PierreBesson** [comment]
I don't believe it ! Can you paste your json response from `/microservice/v2/api-docs` ?

**Comment by pascalgrimaud** [comment]
capture d ecran de 2018-09-28 14-58-42

capture d ecran de 2018-09-28 14-59-46

capture d ecran de 2018-09-28 14-59-28

capture d ecran de 2018-09-28 15-00-32

**Comment by PierreBesson** [comment]
Sorry for not believing you 😛 but I need to see the full json including the "basePath" field.

**Comment by pascalgrimaud** [comment]
Registry -> Gateway

```
{
    "swagger": "2.0",
    "info": {
        "description": "gateway API documentation",
        "version": "0.0.1",
        "title": "gateway API",
        "contact": {},
        "license": {}
    },
    "host": "localhost:8761",
    "basePath": "/services/gateway/gateway:2dfca934a631e783a7c17a75b2b9641b",
    "tags": [
        {
            "name": "account-resource",
            "description": "Account Resource"
        },
        {
            "name": "gateway-resource",
            "description": "Gateway Resource"
        },
        {
            "name": "user-jwt-controller",
            "description": "User JWT Controller"
        },
        {
            "name": "user-resource",
            "description": "User Resource"
        }
    ],
    "paths": {
        "/api/account": {
            "get": {
                "tags": [
                    "account-resource"
                ],
                "summary": "getAccount",
                "operationId": "getAccountUsingGET",
                "produces": [
                    "*/*"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            },
            "post": {
                "tags": [
                    "account-resource"
                ],
                "summary": "saveAccount",
                "operationId": "saveAccountUsingPOST",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "userDTO",
                        "description": "userDTO",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/account/change-password": {
            "post": {
                "tags": [
                    "account-resource"
                ],
                "summary": "changePassword",
                "operationId": "changePasswordUsingPOST",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "passwordChangeDto",
                        "description": "passwordChangeDto",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/PasswordChangeDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/account/reset-password/finish": {
            "post": {
                "tags": [
                    "account-resource"
                ],
                "summary": "finishPasswordReset",
                "operationId": "finishPasswordResetUsingPOST",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "keyAndPassword",
                        "description": "keyAndPassword",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/KeyAndPasswordVM"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/account/reset-password/init": {
            "post": {
                "tags": [
                    "account-resource"
                ],
                "summary": "requestPasswordReset",
                "operationId": "requestPasswordResetUsingPOST",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "mail",
                        "description": "mail",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/activate": {
            "get": {
                "tags": [
                    "account-resource"
                ],
                "summary": "activateAccount",
                "operationId": "activateAccountUsingGET",
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "name": "key",
                        "in": "query",
                        "description": "key",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/authenticate": {
            "get": {
                "tags": [
                    "account-resource"
                ],
                "summary": "isAuthenticated",
                "operationId": "isAuthenticatedUsingGET",
                "produces": [
                    "*/*"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            },
            "post": {
                "tags": [
                    "user-jwt-controller"
                ],
                "summary": "authorize",
                "operationId": "authorizeUsingPOST",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "loginVM",
                        "description": "loginVM",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginVM"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/JWTToken"
                        }
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/gateway/routes": {
            "get": {
                "tags": [
                    "gateway-resource"
                ],
                "summary": "activeRoutes",
                "operationId": "activeRoutesUsingGET",
                "produces": [
                    "*/*"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/RouteVM"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/register": {
            "post": {
                "tags": [
                    "account-resource"
                ],
                "summary": "registerAccount",
                "operationId": "registerAccountUsingPOST",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "managedUserVM",
                        "description": "managedUserVM",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ManagedUserVM"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/users": {
            "get": {
                "tags": [
                    "user-resource"
                ],
                "summary": "getAllUsers",
                "operationId": "getAllUsersUsingGET",
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "name": "offset",
                        "in": "query",
                        "required": false,
                        "type": "integer",
                        "format": "int64"
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Page number of the requested page",
                        "required": false,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "pageNumber",
                        "in": "query",
                        "required": false,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "pageSize",
                        "in": "query",
                        "required": false,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "paged",
                        "in": "query",
                        "required": false,
                        "type": "boolean"
                    },
                    {
                        "name": "size",
                        "in": "query",
                        "description": "Size of a page",
                        "required": false,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "sort",
                        "in": "query",
                        "description": "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.",
                        "required": false,
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi"
                    },
                    {
                        "name": "sort.sorted",
                        "in": "query",
                        "required": false,
                        "type": "boolean"
                    },
                    {
                        "name": "sort.unsorted",
                        "in": "query",
                        "required": false,
                        "type": "boolean"
                    },
                    {
                        "name": "unpaged",
                        "in": "query",
                        "required": false,
                        "type": "boolean"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/UserDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            },
            "post": {
                "tags": [
                    "user-resource"
                ],
                "summary": "createUser",
                "operationId": "createUserUsingPOST",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "userDTO",
                        "description": "userDTO",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            },
            "put": {
                "tags": [
                    "user-resource"
                ],
                "summary": "updateUser",
                "operationId": "updateUserUsingPUT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "userDTO",
                        "description": "userDTO",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserDTO"
                        }
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/users/authorities": {
            "get": {
                "tags": [
                    "user-resource"
                ],
                "summary": "getAuthorities",
                "operationId": "getAuthoritiesUsingGET",
                "produces": [
                    "*/*"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            }
        },
        "/api/users/{login}": {
            "get": {
                "tags": [
                    "user-resource"
                ],
                "summary": "getUser",
                "operationId": "getUserUsingGET",
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "name": "login",
                        "in": "path",
                        "description": "login",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "user-resource"
                ],
                "summary": "deleteUser",
                "operationId": "deleteUserUsingDELETE",
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "name": "login",
                        "in": "path",
                        "description": "login",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                },
                "deprecated": false
            }
        }
    },
    "definitions": {
        "JWTToken": {
            "type": "object",
            "properties": {
                "id_token": {
                    "type": "string"
                }
            },
            "title": "JWTToken"
        },
        "KeyAndPasswordVM": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                }
            },
            "title": "KeyAndPasswordVM"
        },
        "LoginVM": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 4,
                    "maxLength": 100
                },
                "rememberMe": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50
                }
            },
            "title": "LoginVM"
        },
        "ManagedUserVM": {
            "type": "object",
            "properties": {
                "activated": {
                    "type": "boolean"
                },
                "authorities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdBy": {
                    "type": "string"
                },
                "createdDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "email": {
                    "type": "string",
                    "minLength": 5,
                    "maxLength": 254
                },
                "firstName": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 50
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "imageUrl": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 256
                },
                "langKey": {
                    "type": "string",
                    "minLength": 2,
                    "maxLength": 6
                },
                "lastModifiedBy": {
                    "type": "string"
                },
                "lastModifiedDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "lastName": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 50
                },
                "login": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50,
                    "pattern": "^[_.@A-Za-z0-9-]*$"
                },
                "password": {
                    "type": "string",
                    "minLength": 4,
                    "maxLength": 100
                }
            },
            "title": "ManagedUserVM"
        },
        "PasswordChangeDTO": {
            "type": "object",
            "properties": {
                "currentPassword": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                }
            },
            "title": "PasswordChangeDTO"
        },
        "RouteVM": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "serviceId": {
                    "type": "string"
                },
                "serviceInstances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ServiceInstance"
                    }
                }
            },
            "title": "RouteVM"
        },
        "ServiceInstance": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "port": {
                    "type": "integer",
                    "format": "int32"
                },
                "scheme": {
                    "type": "string"
                },
                "secure": {
                    "type": "boolean"
                },
                "serviceId": {
                    "type": "string"
                },
                "uri": {
                    "$ref": "#/definitions/URI"
                }
            },
            "title": "ServiceInstance"
        },
        "URI": {
            "type": "object",
            "properties": {
                "absolute": {
                    "type": "boolean"
                },
                "authority": {
                    "type": "string"
                },
                "fragment": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "opaque": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "port": {
                    "type": "integer",
                    "format": "int32"
                },
                "query": {
                    "type": "string"
                },
                "rawAuthority": {
                    "type": "string"
                },
                "rawFragment": {
                    "type": "string"
                },
                "rawPath": {
                    "type": "string"
                },
                "rawQuery": {
                    "type": "string"
                },
                "rawSchemeSpecificPart": {
                    "type": "string"
                },
                "rawUserInfo": {
                    "type": "string"
                },
                "scheme": {
                    "type": "string"
                },
                "schemeSpecificPart": {
                    "type": "string"
                },
                "userInfo": {
                    "type": "string"
                }
            },
            "title": "URI"
        },
        "User": {
            "type": "object",
            "required": [
                "activated",
                "login"
            ],
            "properties": {
                "activated": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string",
                    "minLength": 5,
                    "maxLength": 254
                },
                "firstName": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 50
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "imageUrl": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 256
                },
                "langKey": {
                    "type": "string",
                    "minLength": 2,
                    "maxLength": 6
                },
                "lastName": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 50
                },
                "login": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50,
                    "pattern": "^[_.@A-Za-z0-9-]*$"
                },
                "resetDate": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "title": "User"
        },
        "UserDTO": {
            "type": "object",
            "properties": {
                "activated": {
                    "type": "boolean"
                },
                "authorities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdBy": {
                    "type": "string"
                },
                "createdDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "email": {
                    "type": "string",
                    "minLength": 5,
                    "maxLength": 254
                },
                "firstName": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 50
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "imageUrl": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 256
                },
                "langKey": {
                    "type": "string",
                    "minLength": 2,
                    "maxLength": 6
                },
                "lastModifiedBy": {
                    "type": "string"
                },
                "lastModifiedDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "lastName": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 50
                },
                "login": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50,
                    "pattern": "^[_.@A-Za-z0-9-]*$"
                }
            },
            "title": "UserDTO"
        }
    }
}
```

**Comment by deepu105** [comment]
Magic detected? 🤪

**Comment by pascalgrimaud** [comment]
Closing in favor of https://github.com/jhipster/generator-jhipster/pull/8417

**Pull request closed without merging**
