### PR TITLE
fix RTL styles and merge all copies of rtl.scss

### LINKED ISSUE #12682: RTL: CSS Fine tuning is needed for all frameworks
##### **Overview of the issue**

Some elements on the app are still not mirrored correctly. E.g., The `Development` ribbon stays on the left, while it should move to the right, etc.

##### **Motivation for or Use Case**

Better support for RTL languages

##### **Reproduce the error**

Create a jhipster app for angular/react/vue with support for an RTL language such as Arabic

##### **Related issues**

This is a followup to #12384. 

##### **Suggest a Fix**

1. Add more `[dir=rtl]` rules to `rtl.scss` as needed
2. There are now 3 exact copies of the same file `rtl.scss`. For better maintenance, it is desired to move this file to a common folder and reuse it for all 3 frameworks

##### **JHipster Version(s)**

6.10.3

##### **Browsers and Operating System**

Windows 10, Chrome, Firefox

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by yehudab**
Fix includes mirroring of the ribbon as well as better spacing on the top navigation bar.
Merge all 3 `rtl.scss` files into a single copy, now under `templates/common`.
Removed redundent `text-align` for vue footer component, which was not necessary.

Fix #12682

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by yehudab** [comment]
@pascalgrimaud 
I see that one test failed. Doesn’t look related to my code, maybe “normal” e2e flakiness? Should I rebase and push for a new run?

**Comment by pascalgrimaud** [comment]
@yehudab : no, I'm restarting the build

**Comment by yehudab** [comment]
Looks like it failed again, Same test, but in a different steps: `GENERATION: project` this time, `E2E: Run` in the previous run.
Any idea why?

**Comment by yehudab** [comment]
Third time is a charm. Finally passed!

**Comment by pascalgrimaud** [comment]
thanks @yehudab

**Comment by yehudab** [comment]
Happy to help

**Pull request merged**
