### PR TITLE
Spring boot 1 3

### PR DESCRIPTION
**Pull request by jdubois**
Creating a PR as discussed in #2117

### CODE REVIEW

**Comment by mraible** [comment]
+1

**Comment by andidev** [comment]
@jdubois 
Most prabably this is not a JHipster issue but after regenerating a project with the current master branch I get `UTF-8` encoding issues with the login name when trying to login. Thus I can't login with logins containing non ascii characters
JHipster actually does not allow UTF-8 in the login name but I have modified this in my project and it worked perfectly in 2.22.0 version and before.

Earlier when it worked I got the following in the console log when trying to login:
```
[DEBUG] com.forskolenatet.security.UserDetailsService - Authenticating trädgårdengrodan
```

and now I get
```
[DEBUG] com.forskolenatet.security.UserDetailsService - Authenticating trÃ¤dgÃ¥rdengrodan
```

This issue does however not occur in the entity REST controllers when saving entities or anywhere else in the app.

Do you know if we have removed some UTF-8 configuration lately? Most probably it is Spring Boot that have made some changes. Though I though that they try to default to UTF-8 (but I'm really not sure about this).

**Comment by jdubois** [comment]
@andidev strange!! But this is important to test & debug!!

**Comment by andidev** [comment]
I did debug it and I found that the username contained invalid characters in the first request created by guess tomcat. I'm not an expert in how this works but it seems to me that it is a tomcat configuration that is wrong. I'm gonna try to create a spring boot issue about this.

**Comment by andidev** [comment]
I've investigated this a bit further and created an spring-boot issue for this, see spring-projects/spring-boot#4228

**Comment by andidev** [comment]
Okey so it looks like this issue is fixed in spring-boot 1.3.0.RC1 and the RC1 release is overdue 4 days so I guess it should be released soon.

**Comment by cbornet** [comment]
spring-boot 1.3.0.RC1 is out :-) !

**Pull request merged**
