### PR TITLE
This improves the JDL import test for the CI by adding more cases

### PR DESCRIPTION
**Pull request by pvliss**
As discussed in #9212, I have added more entities and relationships that cover more test cases that I have copied over from https://github.com/pvliss/jhipster-core/blob/64786e8429b68e3ff0fbfd6384723340ca205456/test/test_files/big_sample.jdl.

This will cause the CI builds to fail and an upgrade to jhipster-core that contains https://github.com/jhipster/jhipster-core/pull/304 will be needed in order for everything to pass successfully

Relates to #9212 and #9202 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pvliss** [comment]
This will need also need the update to jhipster-core 3.6.11 in order to pass the CI which contains https://github.com/jhipster/jhipster-core/pull/305.

**Comment by pascalgrimaud** [comment]
There is this error in logs:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/sample/domain/JobHistory.java:[173,17] cannot find symbol
  symbol:   method getJobHistories()
  location: variable employee of type io.github.jhipster.sample.domain.Employee
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/sample/domain/JobHistory.java:[179,17] cannot find symbol
  symbol:   method getJobHistories()
  location: variable employee of type io.github.jhipster.sample.domain.Employee
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57.738 s
[INFO] Finished at: 2019-02-20T17:53:52+11:00
[INFO] ------------------------------------------------------------------------
```

**Comment by pvliss** [comment]
Yes. Thanks @pascalgrimaud. I am going to check it

**Comment by pvliss** [comment]
There was another unidirectional `@ManyToMany` left in the JDL which are not currently supported. I have removed it and now this should pass. Hopefully :pray:

**Comment by DanielFran** [comment]
Closing/Reopening to launch tests again

**Comment by pascalgrimaud** [comment]
Not a random failure.
We still have an issue with the new JDL file:

```
[INFO] ERROR in src/main/webapp/app/entities/job/job-detail.component.html(1,1234): : Property 'employee' does not exist on type 'IEmployee'.
[INFO] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 2
[ERROR] npm ERR! jhipster-sample-application@0.0.0 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.prod.js" "--profile"`
[ERROR] npm ERR! Exit status 2
```

**Comment by pvliss** [comment]
Yes, while the serve part is working now there is some issue with Angular. Will investigate

**Comment by DanielFran** [comment]
Closing/Reopening to launch tests

**Pull request merged**
