### PR TITLE
Liquibase foreign key relationship column names  

### LINKED ISSUE #27598: Liquibase: Incorrect creation of new foreign key relationships during schema updates
##### **Overview of the issue**
When adding a new Foreign Key relationship, the generated changelogs fail to be applied, especially, if the other entity side has an id column not named "id", but e.g. "uuid". In our case, we even had that foreign key already and tried to re-create that with some more options (like CASCADE). The generator successfully detected the need to recreate the foreign keys, but the new ones as part of the updated_entity_constraints produces wrong column name references (and maybe more).

##### **Motivation for or Use Case**
Should be possible to apply updates to schema involving changes in foreign keys.

##### **Reproduce the error**
1. have an initial jdl and entities on the other side have an id field named "uuid" and generate changelog (and more) via `jhipster jdl`
2. change jdl to have a new foreign key and run jhipster jdl
3. try to apply liquibase changelog / start up application
4. Failure during startup

Here are some stripped sample jdls.

Step 1:
```
entity D {
   status String
   @Id uuid UUID
}

entity L {
   comment String
   status String
   date Instant
}

relationship ManyToOne {
   L{data}
      to
   D{log}
}
```

Step 2:
```
entity D {
   status String
   @Id uuid UUID
}

entity L {
   comment String
   status String
   date Instant
}

relationship ManyToOne {
   L{data}
      to
   @OnDelete("CASCADE") @OnUpdate("CASCADE") 
   D{log}
}
```

##### **Suggest a Fix**
This is because the logic in the update changelog files to construct the attributes for the addForeignKeyContraint works differently than in the add changelog for the initial changelog.
Not working:
https://github.com/jhipster/generator-jhipster/blob/330d2a4dca1b2bed1d43489c4d9728d2876f21f6/generators/liquibase/templates/src/main/resources/config/liquibase/changelog/updated_entity_constraints.xml.ejs#L114-L118

--> hardcoded "_id", no matter, if the actual other entity has a different column name as id, therefore having a different column name in the current entity

Working:
https://github.com/jhipster/generator-jhipster/blob/330d2a4dca1b2bed1d43489c4d9728d2876f21f6/generators/liquibase/templates/src/main/resources/config/liquibase/changelog/added_entity_constraints.xml.ejs#L32-L41

Especially line 38-41 being relevant, but I guess the rest may also be important....

##### **JHipster Version(s)**
8.7.1

##### **JHipster configuration**

To provide all information we need, you should run `jhipster info` in the project root folder (or workspaces root for microservices), and
copy/paste the result here.
`jhipster info` removes sentitive information like rememberKey, jwtSecretKey. Double check if there is any other sensitive info.

As alternative you can add a JDL wrapped in below structure

  <details>
  <summary>JDL definitions</summary>
  <pre>
     JDL content here
  </pre>
  </details>

The information is mandatory for bug reports. This will allow us to use automated tests and genarate the broken sample using `jhipster from-issue` command.

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by OmarHawk**
Fixes #27598 and adds additional conditions to the existing tests (which were missing)

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
Can you please run `npm run update-snapshots` and commit/push the changes?

**Comment by OmarHawk** [comment]
ok, understood, but I considered that already. :-)

**Comment by OmarHawk** [comment]
I have moved the working logic from the `add constraints` into an own partial template, and use that to be included in both the add and update contraints

**Comment by mshima** [comment]
Liquibase changelog should be polished, you can see in ng-default sample compare:
```diff
a/src/main/resources/config/liquibase/changelog/20160208210109_added_entity_constraints_TestCustomTableName.xml
  @@ -10,6 +10,9 @@
       -->
       <changeSet id="20160208210109-2" author="jhipster">
   
  +
  +
  +
           <addForeignKeyConstraint baseColumnNames="test_entity_id"
                                    baseTableName="test_custom_table_name_entity"
                                    constraintName="fk_test_custom_table_name_entity__test_entity_id"
  diff --git b/src/main/resources/config/liquibase/changelog/20160208210110_added_entity_constraints_TestEntity.xml a/src/main/resources/config/liquibase/changelog/20160208210110_added_entity_constraints_TestEntity.xml
  index e4385fd..dcb84bf 100644
  --- b/src/main/resources/config/liquibase/changelog/20160208210110_added_entity_constraints_TestEntity.xml
  +++ a/src/main/resources/config/liquibase/changelog/20160208210110_added_entity_constraints_TestEntity.xml
  @@ -10,6 +10,9 @@
       -->
       <changeSet id="20160208210110-2" author="jhipster">
   
  +
  +
  +
           <addForeignKeyConstraint baseColumnNames="user_one_to_many_id"
                                    baseTableName="test_entity"
                                    constraintName="fk_test_entity__user_one_to_many_id"
  @@ -37,5 +40,8 @@

```

**Comment by OmarHawk** [comment]
> Liquibase changelog should be polished, you can see in ng-default sample compare:

I see, will fix it :-)

**Comment by OmarHawk** [comment]
I do have now less empty lines, do you think, it is alright @mshima? Or does it have to be the exact same way as before?

**Review by DanielFran — APPROVED** [review]

**Comment by mshima** [comment]
I think we should keep the same blank lines to avoid unnecessary diff when upgrading applications, specially changelogs.

**Comment by OmarHawk** [comment]
> I think we should keep the same blank lines to avoid unnecessary diff when upgrading applications, specially changelogs.

Added the empty line again in the `add constraints` changelog file. Hope it looks alright now :-)

**Comment by OmarHawk** [comment]
Reverted the last change regarding the empty line in the add template - please check the Merge Request again @DanielFran, @mshima , whether you are OK with it: I really don't think it makes sense to have a parameter named `createEmptyLines: true` as part of a template in order to have empty lines in `add` case, but not in the `update` case.
The benefit of having it combined into one template is larger than having some (even less!) useless empty lines.

**Comment by mshima** [comment]
Updated files as not not overridden.
There is no problem on changing format.

**Comment by OmarHawk** [comment]
ok, interesting that after the change it shows no changes anymore now. I'd have assumed that with adding the empty lines within the template, it would now produce empty lines in the `update constraint` files...

**Comment by OmarHawk** [comment]
I'll update the snapshots onec more, if you are OK with it - then the MR should become green :-)

**Comment by mshima** [comment]
@OmarHawk projects are identical now, should be ok to merge.
Please update snapshots.

**Comment by OmarHawk** [comment]
Done and squashed the excess commits so that the merge contains only a single commit and looks cleaner.

**Review by mshima — APPROVED** [review]

**Comment by OmarHawk** [comment]
Hope it is alright to claim this: https://opencollective.com/generator-jhipster/expenses/225277

**Comment by DanielFran** [comment]
@OmarHawk approved

**Pull request merged**
