### PR TITLE
Treat reset.json as template.

### PR DESCRIPTION
**Pull request by tan9**

### CODE REVIEW

**Comment by gmarziou** [comment]
Could you explain what problem you solve ?

**Comment by tan9** [comment]
@gmarziou, reset.json contains template syntax introduced by the inclusion of angular2 feature. However, generated resource in locale other than English will be as-is to the template, becoming an invalid JSON.

**Comment by gmarziou** [comment]
OK, so it should be renamed as _reset.json as the other templates.

**Comment by gmarziou** [comment]
OK thanks. Please fix the conflict.

**Comment by tan9** [comment]
@gmarziou , conflict resolved :)

**Pull request merged**
