### PR TITLE
Workaround for eclipse not activating dev profile by default and hence having issue #9175

### LINKED ISSUE #9175: compile error (missing javax.Servlet and Undertow) while importing in eclipse
##### **Overview of the issue**

importing a jhipster project does not compile in eclipse, but compiles in maven

Eclipse complains about missing class: javax.servlet.ServletException

~~~
The type javax.servlet.ServletException cannot be resolved. 
It is indirectly referenced from required .class 
files	WebConfigurerTest.java	/test-1/src/test/java/com/mycompany/myapp/config	

The project was not built since its build path is incomplete. 
Cannot find the class file for javax.servlet.ServletException. 
Fix the build path then try building this project
~~~

Adding 

~~~xml
		<dependency>
		    <groupId>javax.servlet</groupId>
		    <artifactId>javax.servlet-api</artifactId>
		    <scope>provided</scope>
		</dependency>
~~~

solved this first error, but there is 16 others (all concerning undertow) after:

~~~
The type io.undertow.Undertow$Builder cannot be resolved. It is indirectly referenced from required .class files	WebConfigurer.java
~~~

Adding this solves the remaining errors:

~~~xml
	 <dependency>
        	<groupId>org.springframework.boot</groupId>
	        <artifactId>spring-boot-starter-undertow</artifactId>
	        <scope>provided</scope>
	  </dependency>
~~~


##### **Motivation for or Use Case**

using eclipse..

##### **Reproduce the error**

create empty jhipster project, choosing maven
then import in eclipse using "import ... > existing maven project" 

eclipse version : 2018-12, with jdk8, standard eclipse java, no plugins

##### **Related issues**

##### **Suggest a Fix**

adding this in the pom.xml solves the issue:

~~~xml
		<dependency>
		    <groupId>javax.servlet</groupId>
		    <artifactId>javax.servlet-api</artifactId>
		    <scope>provided</scope>
		</dependency>
		<dependency>
        	<groupId>org.springframework.boot</groupId>
	        <artifactId>spring-boot-starter-undertow</artifactId>
	        <scope>provided</scope>
	    </dependency>
~~~

##### **JHipster Version(s)**

JHipster version v5.8.1

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator                                                                       
                                                                                                                        
##### **JHipster Version(s)**                                                                                           
                                                                                                                        
```                                                                                                                     
test-1@0.0.0 D:\test-jhispter\test1                                                                        
`-- generator-jhipster@5.8.1                                                                                            
                                                                                                                        
```                                                                                                                     
                                                                                                                        
                                                                                                                        
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**                                     
                                                                                                                        
                                                                                                                        
<details>                                                                                                               
<summary>.yo-rc.json file</summary>                                                                                     
<pre>                                                                                                                   
{                                                                                                                       
  "generator-jhipster": {                                                                                               
    "promptValues": {                                                                                                   
      "packageName": "com.mycompany.myapp",                                                                             
      "nativeLanguage": "en"                                                                                            
    },                                                                                                                  
    "jhipsterVersion": "5.8.1",                                                                                         
    "applicationType": "monolith",                                                                                      
    "baseName": "test1",                                                                                                
    "packageName": "com.mycompany.myapp",                                                                               
    "packageFolder": "com/mycompany/myapp",                                                                             
    "serverPort": "8080",                                                                                               
    "authenticationType": "jwt",                                                                                        
    "cacheProvider": "ehcache",                                                                                         
    "enableHibernateCache": true,                                                                                       
    "websocket": false,                                                                                                 
    "databaseType": "sql",                                                                                              
    "devDatabaseType": "h2Disk",                                                                                        
    "prodDatabaseType": "postgresql",                                                                                   
    "searchEngine": false,                                                                                              
    "messageBroker": false,                                                                                             
    "serviceDiscoveryType": false,                                                                                      
    "buildTool": "maven",                                                                                               
    "enableSwaggerCodegen": false,                                                                                      
    "clientFramework": "angularX",                                                                                      
    "useSass": true,                                                                                                    
    "clientPackageManager": "npm",                                                                                      
    "testFrameworks": [],                                                                                               
    "jhiPrefix": "jhi",                                                                                                 
    "entitySuffix": "",                                                                                                 
    "dtoSuffix": "DTO",                                                                                                 
    "otherModules": [],                                                                                                 
    "enableTranslation": true,                                                                                          
    "nativeLanguage": "en",                                                                                             
    "languages": [                                                                                                      
      "en"                                                                                                              
    ]                                                                                                                   
  }                                                                                                                     
}                                                                                                                       
</pre>                                                                                                                  
</details>                                                                                                              
                                                                                                                        
                                                                                                                        
##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**            
                                                                                                                        
<details>                                                                                                               
<summary>JDL entity definitions</summary>                                                                               
                                                                                                                        
<pre>                                                                                                                   
                                                                                                                        
</pre>                                                                                                                  
</details>                                                                                                              
                                                                                                                        
                                                                                                                        
##### **Environment and Tools**                                                                                         
                                                                                                                        
java version "1.8.0_202"                                                                                                
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)                                                                   
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)                                                        
                                                                                                                        
git version 2.17.0                                                                                                      
                                                                                                                        
node: v10.15.1                                                                                                          
                                                                                                                        
npm: 6.4.1                                                                                                              
                                                                                                                        
yeoman: 2.0.5                                                                                                           
                                                                                                                        
yarn: 1.13.0                                                                                                            

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

none

##### **Browsers and Operating System**

Windows 10. 
browsers: any (compile time error)

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by pmverma**
Fix #9175.
Since profile id `eclipse` will be activated by default in eclipse IDE, dependency has been included there.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
@jhipster/developers Is there something preventing us to set the dependency in `<dependencies />` instead of `<build />` ? I think gradle already does it this way !

**Comment by PierreBesson** [comment]
@cbornet +1, this would be a better solution. And can we remove the cc profile as well.

**Comment by jdubois** [comment]
- Yes let's remove "cc" I don't think anybody uses it
- And for the "build" part: this was probably coded by me, and as far as I know it can be moved without any issue

**Comment by pmverma** [comment]
@cbornet @PierreBesson @jdubois I think we should better create a new issue & PR for cleaning and refactoring `pom.xml` file. Let's close this PR.

I am not expert in configuring the `pom.xml` but I can help in it.
Is it only removing the `cc` profile and moving the dependency declaration inside `<dependencies />`?

**Comment by atomfrede** [comment]
I would say create a separate PR for removing th cc profile and cleaning up the pom.

**Comment by mraible** [comment]
Closing as requested by @pmverma.

**Comment by pmverma** [comment]
@mraible Sorry for my english. I meant to merge and close. This PR is still meant for #9175.
Can you please merge it?

**Pull request merged**
