### PR TITLE
Read hikari conf from application.yml

### PR DESCRIPTION
**Pull request by cbornet**
See #2769 

Note : it uses spring.datasource.hikari : this is not the current path for 1.3.2 but will be in 1.4.0
Now all Hikari configs are accessible by configuration. Eg :
```yaml
spring.datasource.hikari.connection-test-query: SELECT 1 FROM DUAL
```

### CODE REVIEW

**Comment by cbornet** [comment]
The CI is down ! It looks related to file generation. Can someone have a look ?

**Comment by cbornet** [comment]
@jdubois I think it comes from https://github.com/jhipster/generator-jhipster/commit/709032516305f33bdf520fd4fb47486c00ff4b57. Can you have a look ?

**Comment by jdubois** [comment]
Yes it's my fault.
Le 5 févr. 2016 6:15 PM, "Christophe Bornet" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
Ill check if its still broken

**Comment by deepu105** [comment]
it passed

**Comment by deepu105** [comment]
seems GTM can we merge it

**Comment by jdubois** [comment]
OK, if it works the same, that's better!
But @cbornet don't you need to remove also the configuration in the class JHipsterProperties ?

**Comment by cbornet** [comment]
@jdubois you're right ! That's dead code now !

**Pull request merged**
