### PR TITLE
Update Consul to 1.2.0

### PR DESCRIPTION
**Pull request by DanielFran**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@PierreBesson can you please take a look?

See also https://github.com/jhipster/consul-config-loader/pull/12

Thanks

**Comment by PierreBesson** [comment]
Thank you @DanielFran, can you upgrade to consul 1.2 (see: https://www.hashicorp.com/blog/consul-1-2-service-mesh). And it seems like Consul is now integrating a service mesh ! Any idea how to integrate it with JHipster ?

**Comment by DanielFran** [comment]
@PierreBesson, I can update to 1.2.0, it was released today!

About service mesh it seems beta and it is not yet recommended for Production: https://github.com/hashicorp/consul/blob/v1.2.0/CHANGELOG.md.

Maybe it is better to wait to add this configuration? WDYT?

**Comment by PierreBesson** [comment]
Yes and it looks like those are changes to the service API if we want to benefit from it we would need to wait for spring cloud to integrate the feature.

**Comment by DanielFran** [comment]
@PierreBesson It is done!

I will update also jhipster/consul-config-loader#12

**Comment by jdubois** [comment]
Did you test it with a couple of microservices?

**Comment by DanielFran** [comment]
@jdubois I just tested with 1 microservice.

**Comment by PierreBesson** [comment]
I'm on it @jdubois.

**Pull request merged**
