### PR TITLE
Update archunit-junit5 version to 1.0.0

### PR DESCRIPTION
**Pull request by frascu**
I updated ArchUnit version from `0.22.0` to `1.0.0`. 

In order to handle the braking changes, I upgraded following the list in the description published in the releases [1.0.0](https://github.com/TNG/ArchUnit/releases/tag/v1.0.0) and [1.0.0-rc1](https://github.com/TNG/ArchUnit/releases/tag/v1.0.0-rc1).

The breaking change I found is the following one:
- `layeredArchitecture()` now forces to decide how to deal with dependencies by adding .considering...Dependencies() in the beginning of the declaration. To restore the old behavior declare it as ` layeredArchitecture().consideringAllDependencies()` (see https://github.com/TNG/ArchUnit/pull/892)

Therefore I upgraded `TechnicalStructureTest.java.ejs`
from:
```java
    @ArchTest
    static final ArchRule respectsTechnicalArchitectureLayers = layeredArchitecture()
        .layer("Config").definedBy("..config..")
```
to:
```java
    @ArchTest
    static final ArchRule respectsTechnicalArchitectureLayers = layeredArchitecture()
        .consideringAllDependencies()
        .layer("Config").definedBy("..config..")
```

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@frascu Can you sign the CLA?

**Comment by frascu** [comment]
> @frascu Can you sign the CLA?

Done

**Review by atomfrede — APPROVED** [review]
Looks good. Strange some unrelated tests are not passing. Let's restart the build

**Comment by DanielFran** [comment]
Restarting tests

**Comment by mshima** [comment]
O think there is a slf4j conflict.
Probably maven is resolving to v1.7 (spring-boot dependency)
And gradle is resolving to v2 (archunit dependency)

**Review by DanielFran — APPROVED** [review]

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
Thanks @frascu for the contribution

**Pull request merged**
