### PR TITLE
Update to prettier 3

### PR DESCRIPTION
**Pull request by emilpaw**
Fixes #22781

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by emilpaw** [comment]
@DanielFran Do you have an idea why the backend tests of `generate-blueprint` and `database-changelog-liquibasebackend` fail with following message?
```
Error:  Failed to execute goal io.github.git-commit-id:git-commit-id-maven-plugin:6.0.0:revision (default) on project jhipster-sample-application: Could not get HEAD Ref, are you sure you have some commits in the dotGitDirectory (currently set to /home/runner/work/generator-jhipster/generator-jhipster/app/.git)? -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

This does not seem related to my changes.

**Comment by mshima** [comment]
@emilpaw the project step is failing to create git repository due to lint-staged/husky and prettier.
Git repository is empty at backend step.

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
Thanks @emilpaw 
Do not forget the bug bounty

**Comment by emilpaw** [comment]
@mshima Thanks for the help.

Thanks @DanielFran for the swift review.

**Comment by emilpaw** [comment]
Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/179303

Thanks :)

**Pull request merged**
