### PR TITLE
New CLI flag to disable fake data generation

### LINKED ISSUE #9661: Make fake data optional
##### **Overview of the issue**

The generation and use of fake data should be optional, and should be proposed by prompt, either as a global choice or as a per entity choice.

##### **Motivation for or Use Case**

The generator writes data files on the the same place real data are usually put for production (`src/main/resources/config/liquibase/data`).
There are also open issues with fake data, such as #9579

##### **JHipster Version(s)**

6.0.0

### PR DESCRIPTION
**Pull request by murdos**
Fixes #9661

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by murdos** [comment]
Declined feature

**Comment by pascalgrimaud** [comment]
@murdos : this PR has some conflict, can you resolve it plz ? Then the title still contains 'WIP'. Tell me once it's ready to be reviewed so I can test and merge it
Thanks a lot ! ❤

**Comment by murdos** [comment]
@pascalgrimaud : It's ready for review 😉

**Comment by pascalgrimaud** [comment]
Thanks, I'll review and test it asap, to include it in the next release

**Comment by pascalgrimaud** [comment]
Just tested and it works well.
Thanks @murdos !

**Pull request merged**
