### PR TITLE
Profile switches for no-swager and no-liquibase

### PR DESCRIPTION
**Pull request by deepu105**
profile switches to disable liquibase/swagger

For jar|war it can be added as `--spring.profiles.active=prod|dev,no-liquibase|no-swagger`

For Gradle local bootRun `./gradlew -Pno-liquibase -Pno-swagger` or `./gradlew -Pprod -Pno-liquibase -Pno-swagger`

Can someone check for maven local run 

part of #3151 but no-cache seems to be tougher than I thought will do it as a seperate PR

### CODE REVIEW

**Comment by PierreBesson** [comment]
I tested it. It works for the war. Some configuration should be done for maven in the pom.xml so that it would work the same as with gradle. Does anyone have an idea on how to do that ?

**Comment by deepu105** [comment]
my maven skills suck so i need help on that

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@jhipster/developers can anybody do this for maven, should this be done using maven profiles like [here ](http://stackoverflow.com/questions/7513319/maven-command-line-arguments)or is there a better way?

**Comment by jdubois** [comment]
Oh we should do this before our 3.0 release!
Le 23 mars 2016 2:57 AM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
@deepu105 you can't "merge" several Maven profiles like you do with Gradle. Yes, Gradle is more powerful :-)
So basically you can only do this at runtime. I'm updating the documentation accordingly.

**Pull request merged**
