### PR TITLE
Some formatting with Prettier

### PR DESCRIPTION
**Pull request by pascalgrimaud**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by murdos** [comment]
@pascalgrimaud : what is the benefit of formatting templates, whereas we could just dynamically apply prettier during generation as already done for typescript, json, yml... ?

**Comment by pascalgrimaud** [comment]
@murdos : waiting the v7, unless all team agree to put prettier-java for v6.x ?

**Comment by murdos** [comment]
I still don't understand: if we're waiting for v7, then why are we manually formatting templates in v6? 
Then end result is the same for our users: the formatting of the generated code will change.

**Comment by pascalgrimaud** [comment]
There are several steps for including prettier-java in JHipster project:
- add prettier-java for formatting before writing the file
- add hook for formatting before commit

The 1st part is not a breaking change I think.
The 2nd is, as it will change all the specific code.

For the 1st part, I just don't have time to do the appropriate code to use prettier-java before writing file in disk. So it's simply the quickest way for my current need (like https://github.com/jhipster/generator-jhipster/pull/11278)

But if you disagree with this PR, no worry :)
I'm closing this and will use it in my own fork.

**Comment by mshima** [comment]
> @pascalgrimaud : what is the benefit of formatting templates, whereas we could just dynamically apply prettier during generation as already done for typescript, json, yml... ?

It is easier to understand and do the modifications.

**Comment by mshima** [comment]
> There are several steps for including prettier-java in JHipster project:
> 
> * add prettier-java for formatting before writing the file
> * add hook for formatting before commit
> 
> The 1st part is not a breaking change I think.
> The 2nd is, as it will change all the specific code.
> 
> For the 1st part, I just don't have time to do the appropriate code to use prettier-java before writing file in disk. So it's simply the quickest way for my current need (like #11278)

The only difference I see is the size of the changes.

I think it would be nice to have prettier enabled with a flag.

**Comment by pascalgrimaud** [comment]
Yes agree @mshima but it requires some work to do, related to https://github.com/jhipster/generator-jhipster/issues/10641
So then, let's discuss on this ticket https://github.com/jhipster/generator-jhipster/issues/10641

I'm closing this PR as you don't find these changes usefull

**Pull request closed without merging**
