### PR TITLE
Criteria copy method and constructor (to check)

### PR DESCRIPTION
**Pull request by Blackdread**
See issue #9084

It requires https://github.com/jhipster/jhipster/pull/182 to be merged first to fully test generated code (otherwise will not compile)

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
@Blackdread this causes a compilation issue while launching some unit tests, can you check?

**Comment by Blackdread** [comment]
Yes.

**Comment by Blackdread** [comment]
All good ;)

**Comment by DanielFran** [comment]
Thanks @Blackdread

**Pull request merged**
