### PR TITLE
Fix 3455 Removing illegal HR tags from details view.

### PR DESCRIPTION
**Pull request by adam-ho**
fix https://github.com/jhipster/generator-jhipster/issues/3455

### CODE REVIEW

**Comment by deepu105** [comment]
Please add the css in the sass file as well. Also yser management detail might have same issue.

Also the css tweak shouldn't be generuc, ot should be only for the dl used for entity detail. May be add a specific class so that all dl are not affected

**Comment by adam-ho** [comment]
- User management doesn't use HR, so that's okay
- This style isn't generic, only applied to .dl-horizontal, so as a result user management detail view is not consistent with entities detail view. I think it's a good thing. However, if someone wants to use different styles for .dl-horizontal across the project, they can customise the CSS (which they do anyway).
- Which sass file do you refer to?

**Comment by adam-ho** [comment]
@deepu105 Looks like there is some flake with the test : https://travis-ci.org/jhipster/generator-jhipster/jobs/125316929
`Timed out waiting for the WebDriver server at http://127.0.0.1:54793/hub`
Have you seen this before?

**Comment by adam-ho** [comment]
Actually I thought about it and modifying the style isn't a good idea as we are modifying Bootstrap style for no good reason. The new style may or may not look better than the base style and people would need to figure out why and how we are different from Bootstrap. We are a generator framework so shouldn't be too opinionated about style.

So all in all, I would remove the HR because it generates invalid HTML but keep the original DL DT DD Bootstrap style in place and let the users customise it if they want to.

What do you think?

**Comment by deepu105** [comment]
My point is I don't want you to override the bootstrap style but on the detail page I do want the bottom borders by default. So we should add a specific class the the parent dl `<dl class="dl-horizontal entity-detail">` and add custom style to that class. SO if someone doesn't want that they can just remove the class

**Comment by adam-ho** [comment]
Yepp, I can live with that - added the jh-entity-details class.

**Comment by deepu105** [comment]
you missed the sass file. I have update it anyways

**Pull request merged**
