### PR TITLE
Fix marketplace when there is an empty author

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix https://github.com/jhipster/generator-jhipster/issues/5563

### CODE REVIEW

**Comment by deepu105** [comment]
fix seems ok but do we really need to show the auther name here? To me just name and description might be sufficient

**Comment by pascalgrimaud** [comment]
Author name is not needed, so I agree with you. 
Do you want me to remove it ?

**Comment by deepu105** [comment]
Lets just remove and keep it simple

**Comment by pascalgrimaud** [comment]
Done!

**Pull request merged**
