### PR TITLE
Use config property "jhipster.clientApp.name" and `enableTranslation` flag when using HeaderUtil methods

### PR DESCRIPTION
**Pull request by pvliss**
This PR along with https://github.com/jhipster/jhipster/pull/188 are an attempt to fix issue #9282.

The JHipster PR will need to be merged first and then this one in order for everything to work properly

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pvliss** [comment]
Also maybe we could add more tests to avoid this in the future. Will check tomorrow

**Comment by cbornet** [comment]
This change makes my app crash:
```
2019-02-20 00:42:18.563  WARN 29523 --- [  restartedMain] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cacheConfiguration' defined in file [/home/cbornet/workspace/jhipsterapps/reactive/target/classes/com/mycompany/myapp/config/CacheConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'io.github.jhipster.config.JHipsterProperties': Could not bind properties to 'JHipsterProperties' : prefix=jhipster, ignoreInvalidFields=false, ignoreUnknownFields=false; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'jhipster' to io.github.jhipster.config.JHipsterProperties
2019-02-20 00:42:18.580 ERROR 29523 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target [Bindable@37a4492 type = io.github.jhipster.config.JHipsterProperties, value = 'provided', annotations = array<Annotation>[@org.springframework.boot.context.properties.ConfigurationProperties(ignoreUnknownFields=false, ignoreInvalidFields=false, value=jhipster, prefix=jhipster)]] failed:

    Property: jhipster.clientapp.name
    Value: reactive
    Origin: class path resource [config/application.yml]:136:26
    Reason: The elements [jhipster.clientapp.name] were left unbound.

Action:

Update your application's configuration
```

**Comment by cbornet** [comment]
`JHipsterProperties` is configured with `ignoreUnknownFields = false` so you can't add fields to `jhipster.*` without adding them also in the class.

**Comment by pvliss** [comment]
Hello @cbornet. You are right that in some cases this problem occurs. See also https://travis-ci.org/jhipster/generator-jhipster/jobs/495668745. I reproduced locally using the `ngx-mongodb-kafka-cucumber` sample and the fix seems to be to also add the `jhipster.clientApp.name` property to the test `application.yml` as well.  I will do a new PR to fix this. Would you mind testing it as well locally. Thanks.

**Comment by cbornet** [comment]
I don't think this is enough. You have to create the fields in `JHipsterProperties`

**Comment by pascalgrimaud** [comment]
@cbornet : I think it's already the case, isn't it ?
https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/JHipsterProperties.java#L69

**Comment by cbornet** [comment]
Mm... It seems I don't have the latest snapshot. I'll have a look.

**Comment by cbornet** [comment]
The latest SNAPSHOT of jhipster-dependencies is from 02/15. Any reason it's not up-to-date ?

**Comment by pascalgrimaud** [comment]
Not sure, but I think it's Julien who makes release / snapshot to Artifactory.
Locally, I need to clone `jhipster/jhipster` (or update my fork) and then, launch `./mvnw clean install -Dgpg.skip=true`. Otherwise, it won't work

**Comment by cbornet** [comment]
Oh OK. I thought the SNAPSHOT was pushed automatically.

**Comment by jdubois** [comment]
If you need a snapshot release just ping me directly - I'm doing one right now just in case. It has to be signed with PGP, not sure we can automate this.

**Comment by cbornet** [comment]
We do automated releases of openapi-generator. It's not me who contributed it and I know it's a pain to setup so probably not worth it.

**Pull request merged**
