### PR TITLE
fix error when creating an user without an authority

### PR DESCRIPTION
**Pull request by rkohel**
When creating a new user without an authority a NullPointerException was thrown.

### CODE REVIEW

**Comment by jdubois** [comment]
- A user without any authority is strange, he should at least have ROLE_ANONYMOUS ?
- In that case the authorities collection could be empty, but not null

Are you sure of this issue? Can give a little bit more explanation?

**Comment by rkohel** [comment]
Please try the following:

* Generate an application with a sql database

* Go to: Administration -> User management -> Create a new user
* Login: newuser
* Email: newuser@localhost
* **Don't select any profiles!**
* Save

**Comment by jdubois** [comment]
Oh indeed! And that means there is also an issue in the admin screen -> for me if no profile is selected you should have "ROLE_ANONYMOUS"

**Comment by rkohel** [comment]
* Should in this case "ROLE_ANONYMOUS" also be written to the jhi_user_authority table?
Then we must also add "ROLE_ANONYMOUS" to liquibase\authorities.csv.
The default user "anonymousUser" should also get "ROLE_ANONYMOUS" by adding (2,"ROLE_ANONYMOUS") to liquibase\users_authorities.csv.
Also the cql\create-tables.cql, mongeez\authorities.xml and mongeez\users.xml must be extented accordingly.

* Or should it just be displayed as "ROLE_ANONYMOUS" in the Users screen, if an user doesn't have any authority?

**Comment by jdubois** [comment]
Sorry, I'm wrong in fact.
"ROLE_ANONYMOUS" is for users who are not logged in.
For a logged in user, you can give him whatever role you want -> giving him no role at all doesn't make much sense, but I suppose that's a possibility

**Pull request merged**
