### PR TITLE
Set PostgreSQL as default database

### PR DESCRIPTION
**Pull request by agaspardcilia**
Not my biggest PR but it was mentioned in #10958.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
@jhipster/developers Does this need to wait for v7?

**Comment by DanielFran** [comment]
I added label v7 but for me this can be merged

**Comment by pascalgrimaud** [comment]
In my opinion, it's mainly for people who want to try or do demo, so you can press "enter enter enter" with the cli. There is no breaking change.

Then, if we decide to switch to PostgreSQL by default, there are more work than simply this change:
- change all default config in CI to use and test more PostgreSQL
- do the same thing in jhipster-daily-builds
- change the behavior in jhipster-online
- do the change in all other blueprint backend (kotlin, nodejs, quarkus, etc.)

Because, if it becomes our default database, it must be tested more.

**Comment by agaspardcilia** [comment]
Alright, I thought things mentioned in the road map were agreed upon, looks like there not... I'll close the PR for now and open a ticket to discuss that then.

**Pull request closed without merging**
