### PR TITLE
[React] Downgrade webpack-dev-server (error)

### PR DESCRIPTION
**Pull request by qmonmert**
Revert https://github.com/jhipster/generator-jhipster/commit/3e25a056b38d60285397155e478fcbc7286178e1#diff-45ad775caf02ce958066eda2b4a911763e810750a9dfaf3ca618a09306bbed87

`npm start` not working with the new version
image

Without `--inline`, there is an other error
image

Need a fix to upgrade
Doc is here https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by deepu105** [comment]
are you on an LTS of Node?

**Review by deepu105 — APPROVED** [review]
I dont remember having issues wth this, unless this was updated recenly. ANyway ok to downgrade

**Comment by qmonmert** [comment]
> are you on an LTS of Node?

node 14.16.0

**Comment by qmonmert** [comment]
> I dont remember having issues wth this, unless this was updated recenly. ANyway ok to downgrade

did you test since 4 days ?

**Comment by mraible** [comment]
I can confirm this happens with the latest `main` branch.

My Node version:

```
➜  react-app git:(main) node --version
v14.17.0
```

If I downgrade like this PR has, it works.

**Review by mraible — APPROVED** [review]

**Pull request merged**
