### PR TITLE
Added simple Heroku tests

### PR DESCRIPTION
**Pull request by jkutner**
Making an offering to the CI Gods that this passes on Travis.

### CODE REVIEW

**Comment by deepu105** [comment]
Seems like the almighty Travis aint happy yet, there was a timeout. I restarted the build

**Comment by jkutner** [comment]
I think the current CI error is my fault. the Stubbing of child_process is interfering with the Docker-Compose test.

**Comment by deepu105** [comment]
May be resetting the stub in afterTest might help

**Comment by jkutner** [comment]
@deepu105 green! 🎉

**Comment by jdubois** [comment]
Awesome!

**Pull request merged**
