### PR TITLE
use @NotBlank instead of @NotNull for the login

### PR DESCRIPTION
**Pull request by ctamisier**
fix for sonar warning about @NotNull

https://github.com/jhipster/generator-jhipster/pull/5609

### CODE REVIEW

**Comment by ctamisier** [comment]
This PR conflicts with https://github.com/jhipster/generator-jhipster/pull/5627

**Comment by sendilkumarn** [comment]
I closed the other.

**Comment by cbornet** [comment]
@pascalgrimaud did you see https://github.com/jhipster/generator-jhipster/pull/5609#issuecomment-295587193 ?

**Comment by pascalgrimaud** [comment]
Sorry, I didn't read it closely.
@cbornet : so do you think we should stay as before, without @NotBlank and without @NotNull ?

**Comment by cbornet** [comment]
No, keep @NotNull and exclude the sonar rule.
If we consider the sonar rule valid, we shouldn't replace NotNull by NotBlank just because it's not detected.

**Comment by pascalgrimaud** [comment]
Can you PR your proposal @cbornet plz ? but do you think everybody would be ok for excluding a Sonar rule ?

As you suggested in the Mailing List, It would be good to have a sonar analyze before merging PR, to try to  keep our Sonar Analyze as best as possible: https://sonarqube.com/dashboard?id=io.github.jhipster.sample%3Ajhipster-sample-application
But it's hard to find time for everyone...

**Comment by cbornet** [comment]
I can PR but I would like to have others opinion before.
@jhipster/developers

**Comment by jdubois** [comment]
Unfortunately it should work with Sonar "out of the box", otherwise people will have all those "bugs" after generation.

**Comment by cbornet** [comment]
Well, we already exclude some sonar rules if I'm not mistaken

**Comment by jdubois** [comment]
I know one, but that was a bug in Sonar, so I sent them a bug report and discussed the issue with the Sonar team on their mailing list : so this is supposed to be temporary, until they fix it.

**Comment by cbornet** [comment]
The thing is : it seems weird to me to use NotBlank instead of NotNull just to avoid being detected by Sonar.
The issue still exists, it's just that Sonar doesn't detect it because nobody wrote the rule yet. And it could change tomorrow...

**Comment by Tcharl** [comment]
I'm not for the NotBlank: it's a good practice to stick to the reference instead of vendor specific stuff

**Pull request merged**
