### PR TITLE
WIP: Fakerjs 8: address replace by location

### PR DESCRIPTION
**Pull request by qmonmert**
Related to #22853 

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]

**Comment by qmonmert** [comment]
@DanielFran I wrote `WIP` because I think there is a bug ...

**Comment by DanielFran** [comment]
@qmonmert sorry did not see the update to WIP. 😎
Better to put as draft, this will avoid any mistake.

**Comment by qmonmert** [comment]
yes but I see the bug after creating the PR 🙂

**Comment by DanielFran** [comment]
Is it better to rollback or this is something you can fix?

**Comment by qmonmert** [comment]
Better to rollback because I don't have the solution right now

**Pull request merged**
