### PR TITLE
generator-jhipster-6263 Access control policy is not working - remove…

### PR DESCRIPTION
**Pull request by lchayoun**
…d enclosing if statement

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by lchayoun** [comment]
for #6263

**Comment by lchayoun** [comment]
@jdubois maybe I don't follow, but in order to make swagger work (because it is blocked by the AccessControl) you added a check that all gzipped responses will be allowed?

HttpStatus.FORBIDDEN.value() is not enough, you can check RibbonRoutingFilter and SimpleHostRoutingFilter, the shouldFilter() function will return false on several cases, one of them is that sendZuulResponse is true.

in case we decided to deny a request based on access control, we want to stop the routing.

**Comment by gmarziou** [comment]
@marcelinobadin you were the one who wrote #3940 to fix issue #3933, maybe you can join the discussion?

**Comment by jdubois** [comment]
Please note that I didn't write this filter, so maybe there's something I don't understand - but I just tested and I totally agree with you.
I really don't know what happened here - so thanks for testing, and I'm merging this!

**Pull request merged**
