### PR TITLE
Disable Couchbase and move WebFlux and Infinispan out of beta

### PR DESCRIPTION
**Pull request by mraible**
Disable Couchbase as a prompt so v7 does not prompt users. Can be re-enabled once [Couchbase for Spring Boot 2.4](https://github.com/jhipster/generator-jhipster/pull/14184) is fixed.

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
@jhipster/developers Are y'all OK with moving WebFlux, Neo4j, and Infinispan out of beta?

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/issues/13797 seems a blocker for Neo4j.

**Comment by mraible** [comment]
@mshima I added a bug bounty to the issue. I'm also seeing issues with Neo4j when running `jhipster jdl reactive-ms` and running e2e tests. They fail when talking to the blog app that uses Neo4j. If I change the gateway to use Cypress, the tests still fail. These tests passed with beta 1.

**Comment by jdubois** [comment]
At least Webflux should be stable now, but I’m not totally sure of its current quality level.

**Comment by atomfrede** [comment]
Regarding the neo4j issue I will check with Michael and Gerrit. I remember something similar when we implement it and I think it's something how neo4j/neo4j spring integration handles relations. So maybe we need to prevent using dtos to always have the full object.

**Comment by pascalgrimaud** [comment]
Webflux -> we have no choice, because our gateway is by default with Reactive. It's pretty well tested with the JDL daily builds, so I'm confident, we can remove "beta"
Infinispan -> very few feedbacks, so I think it works

Neo4J -> not sure it's ready yet, we still have some issues
Couchbase -> broken for a while

**Comment by mraible** [comment]
@pascalgrimaud I re-added Beta to Neo4j.

**Pull request merged**
