### PR TITLE
fixing build warning (error :P) - in angularx 

### PR DESCRIPTION
**Pull request by sendilkumarn**
- Please make sure the below checklist is followed for Pull Requests.
#6124 
- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
I have already fixed it by enabling type check so this is not required anymore

**Comment by sendilkumarn** [comment]
The warning below is in our master 
screen shot 2017-07-16 at 10 13 01 pm

That is fixed by this commit

The warning is 
screen shot 2017-07-16 at 10 12 54 pm

**Comment by deepu105** [comment]
We need `no-use-before-declare` so removing it is not the solution issue is that it needs type checking, and I enabled it and it was working when running `yarn lint` now I added it only for yarn lint step but not for ts-lint loader so I think we need to enable it for ts-lint loader as well

**Comment by deepu105** [comment]
so we need to add `options: { typeCheck: true }` to 
```
{
            test: /\.ts$/,
            enforce: 'pre',
            loaders: 'tslint-loader',
            options: { typeCheck: true },
            exclude: ['node_modules', new RegExp('reflect-metadata\\' + path.sep + 'Reflect\\.ts')]
        }
```

**Comment by deepu105** [comment]
can you try it?

**Comment by deepu105** [comment]
Also since we run tslint on both prod and dev the rule can be moved to common file I guess

**Comment by sendilkumarn** [comment]
Let me have a look

**Pull request closed without merging**
