### PR TITLE
generate simpler build.gradle.

### PR DESCRIPTION
**Pull request by nobusugi246**

### CODE REVIEW

**Comment by deepu105** [comment]
Sorry but this is not how we do our main gradle file and hence is not consistent, I dont see any value in this. cc @atomfrede

**Comment by atomfrede** [comment]
Yes, its not the current case, but I also considered to switch to ``group:name:version``, but I'm not sure how versions are handled from ``gradle.properties`` in that case.

**Comment by atomfrede** [comment]
I'll try to check if we can use the simplified version with dynamic version in the main generator on the weekend.

**Comment by nobusugi246** [comment]
Thanks for this discussion. I think many gradle users feel comfortable this simplified version. In case of dynamic version, please use "(double quotations) instead of '(single quotations) like this,
<pre>
classpath "org.springframework.boot:spring-boot-gradle-plugin:${spring_boot_version}"
</pre>

**Comment by atomfrede** [comment]
@nobusugi246 Thanks for the hint :)
@deepu105 I think I'm going to change the the gradle dependencies to the shorter format: ``compile 'com.fasterxml.jackson.core:jackson-core:2.7.3'`` When adding dependencie from maven central you can just copy and paste the dependency. Or do you have any objections?

**Comment by deepu105** [comment]
@atomfrede I dont have any objections please go ahead

**Pull request merged**
