### PR TITLE
Update npm dependencies of the generator

### PR DESCRIPTION
**Pull request by pvliss**
This PR updates the npm packages of the generator.

Updated all packages with available minimum and patchupdates and all of the packages that had a major upgrade **except** `tabtab ` which causes tests to fail.

All major upgrades have been done in separate commits and links to changelogs have been added in the commit comments.

Relates to #9285 

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pvliss** [comment]
I use [npm-check](https://github.com/dylang/npm-check) (awesome tool btw) to help somewhat automate the procedure and it reports the following missing dependencies used by the aws sub-generators:
```
aws-sdk                  😟  MISSING!  Not installed.
                         😟  PKG ERR!  Not in the package.json. Found in: /generators/aws/lib/aws.js, /generators/aws-containers/aws-client.js, /generators/aws-containers/lib/cloudFormation.js, /generators/aws-containers/lib/ecr.js, /generators/aws-containers/lib/ssm.js

progress                 😟  PKG ERR!  Not in the package.json. Found in: /generators/aws/lib/s3.js, /generators/aws-containers/aws-client.js

ora                      😟  MISSING!  Not installed.
                         😟  PKG ERR!  Not in the package.json. Found in: /generators/aws-containers/aws-client.js, /generators/aws-containers/lib/utils.js

```
It seems weird to me that these are not declared while the aws sub-generators seem active. Are these left out on purpose?

**Comment by pascalgrimaud** [comment]
indeed, it's strange for aws

**Comment by pvliss** [comment]
Thanks @pascalgrimaud. So should I add them?

**Comment by ruddell** [comment]
We do some weird trick so those packages are only installed if you run the AWS subgenerator.  I'd be careful updating them without testing a deploy to AWS: https://github.com/jhipster/generator-jhipster/blob/9e6a072451954cbd62c0fb4f626f2c53939db793/generators/aws-containers/aws-client.js#L67-L97

**Comment by pvliss** [comment]
Thanks @ruddell . So it is handled differently and npm-check simply does not detect it. So no need to update them

**Pull request merged**
