### PR TITLE
Fix packaging for Microservices

### PR DESCRIPTION
**Pull request by pascalgrimaud**
I hope it will fix https://github.com/jhipster/generator-jhipster/issues/6741

_____

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
The build passed. I checked the logs. We need to see why the build was green for this case earlier

**Comment by pascalgrimaud** [comment]
Thanks Deepu.
Yes, I will work later on the Travis part

Le 26 nov. 2017 12:14 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by erikkemperman** [comment]
Sorry guys, this was my fault! Any idea yet why Travis passed despite this error?

**Comment by pascalgrimaud** [comment]
No worry.

Travis passed because:
- `mvnw package` generated a war and exit 0 (instead of another number), although there is a failure in the build process
- the war is generated but it is corrupted
- there was no curl on Microservices, to test if the microservice started correctly, fixed by https://github.com/jhipster/generator-jhipster/pull/6749

**Pull request merged**
