### PR TITLE
Official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
See: https://github.com/gradle/wrapper-validation-action

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Many thanks @JLLeitschuh :heart: Did that already for our [generated ci templates](https://github.com/jhipster/generator-jhipster/blob/master/generators/ci-cd/templates/github-ci.yml.ejs#L22) and wanted to do it for the generator itself! Going to merge this as there is currently some flakiness for the react test.

**Comment by JLLeitschuh** [comment]
> Did that already for our generated ci templates

I did! That's what inspired me to contribute this here directly.

Also, something that your whole team may find interesting. If you have some security work that you want do do and are looking to finance. Google is offering grants to OSS that are looking to make significant security changes to their projects.

https://security.googleblog.com/2019/12/announcing-updates-to-our-patch-rewards.html

Nice work guys!

**Comment by atomfrede** [comment]
> Also, something that your whole team may find interesting. If you have some security work that you want do do and are looking to finance. Google is offering grants to OSS that are looking to make significant security changes to their projects.
> 
> https://security.googleblog.com/2019/12/announcing-updates-to-our-patch-rewards.html

CC @jdubois @pascalgrimaud @deepu105 @mraible maybe we can do something? What do you think?

**Comment by deepu105** [comment]
I guess no harm in trying if others feel the same

**Pull request merged**
