### PR TITLE
update webdriver to support chrome 76

### PR DESCRIPTION
**Pull request by vishal423**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
@pascalgrimaud, any idea on how to fix this on travis?

> 
> Get:1 http://dl.google.com/linux/chrome/deb stable/main amd64 google-chrome-stable amd64 77.0.3865.75-1 [62.3 MB]
> 
> Fetched 62.3 MB in 0s (62.9 MB/s)
> 
> dpkg-deb: error: archive '/var/cache/apt/archives/google-chrome-stable_77.0.3865.75-1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
> 
> dpkg: error processing archive /var/cache/apt/archives/google-chrome-stable_77.0.3865.75-1_amd64.deb (--unpack):
> 
>  subprocess dpkg-deb --control returned error exit status 2
> 
> Errors were encountered while processing:
> 
>  /var/cache/apt/archives/google-chrome-stable_77.0.3865.75-1_amd64.deb
> 
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> apt-get.diagnostics
> 
> apt-get install failed
> 
> The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install google-chrome-stable" failed and exited with 100 during .

**Comment by pascalgrimaud** [comment]
Sorry, I don't know... 
Travis seems not working well the last days, compared to Azure DevOps. 
And now, we have GitHub Actions too so I should give a try to this

**Comment by vishal423** [comment]
@pascalgrimaud, I have updated the `Travis` OS base image to `bionic` and that seems to solve the build issue.

On a side note, travis supports five parallel jobs and I think we should leverage that at least. We can move remaining jobs to other CI environments and also optimize the current build pipeline

**Comment by pascalgrimaud** [comment]
good job @vishal423 !

**Pull request merged**
