### PR TITLE
make translation an option during generation

### LINKED ISSUE #1416: Feature Request: Can Angular Translate be an option while generating an app?
Instead of making Angular translate and everything related to translate default, can it be an option while generation? I know I can just remove the default french translation and work but still for just using English the entire translation services riding on top of everything is unnessery right? that too with the occasional fliker of foo.some.title

### PR DESCRIPTION
**Pull request by deepu105**
changes to have an option during generation and supporting changes to
strip unwanted translation directives and filters fromhtml and js files

2nd PR for the translation changes following https://github.com/jhipster/generator-jhipster/pull/1537

Fix #1416

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois please take a look

**Comment by jdubois** [comment]
I tried to merge this PR, the result is in https://github.com/jhipster/generator-jhipster/tree/deepu105-jh-translate-fix-part2

- Resolved the conflicts during merge
- Upgraded the code to Yeoman 0.20.1
- Corrected the unit test

However, when running "grunt test", I have lots of errors, so for the moment I'm giving up

**Comment by deepu105** [comment]
@jdubois  I guess it was based on your code before yeoman 0.20, ill take a look and rebase to latest master

**Comment by jdubois** [comment]
@deepu105 yes it was, so those errors are normal

**Comment by deepu105** [comment]
dont worry, ill work on it tomorrow and push a new commit

On Mon, Jun 8, 2015 at 11:27 PM, Julien Dubois <notifications@github.com>
wrote:

> @deepu105 <https://github.com/deepu105> yes it was, so those errors are
> normal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/pull/1544#issuecomment-110040938>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by jdubois** [comment]
@deepu105 don't forget to use what I pushed in the https://github.com/jhipster/generator-jhipster/tree/deepu105-jh-translate-fix-part2 branch, as I've already done a lot of work, and that's not easy if you haven't done a Yeoamn 0.20.1 migration yet :-)

**Comment by deepu105** [comment]
@jdubois sure ill work on top of that, I followed your changes for yeoman 0.20 closeley so i guess I know where these are failing

**Comment by deepu105** [comment]
@jdubois done fixed the issues, merged with the deepu105-jh-translate-fix-part2 branch and rebased to master.
tested with gradle and maven builds, tried few combinations and all working fine

**Comment by deepu105** [comment]
i dont know which would be easy for you to merge hence i have given a PR to the merged branch as well https://github.com/jhipster/generator-jhipster/pull/1587
so plz take which is comfortable for you

**Comment by jdubois** [comment]
Merged!

**Pull request closed without merging**
