### PR TITLE
chore(Travis): javadoc warnings closure

### LINKED ISSUE #3901: Javadoc warnings
We are recently seeing a lot of Javadoc warnings in the travis build. we need to fix these.

```
19 warnings
[WARNING] Javadoc Warnings
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/config/DefaultProfileUtil.java:31: warning: no @return
[WARNING] public static String getDefaultActiveProfiles(){
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/config/DefaultProfileUtil.java:47: warning: no @param for app
[WARNING] public static void addDefaultProfile(SpringApplication app) {
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/service/LabelService.java:92: warning: no @param for pageable
[WARNING] public Page<Label> search(String query, Pageable pageable) {
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/FieldTestInfiniteScrollEntityResource.java:160: warning: no @param for pageable
[WARNING] public ResponseEntity<List<FieldTestInfiniteScrollEntity>> searchFieldTestInfiniteScrollEntities(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/FieldTestInfiniteScrollEntityResource.java:160: warning: no @throws for java.net.URISyntaxException
[WARNING] public ResponseEntity<List<FieldTestInfiniteScrollEntity>> searchFieldTestInfiniteScrollEntities(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/FieldTestPagerEntityResource.java:160: warning: no @param for pageable
[WARNING] public ResponseEntity<List<FieldTestPagerEntity>> searchFieldTestPagerEntities(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/FieldTestPagerEntityResource.java:160: warning: no @throws for java.net.URISyntaxException
[WARNING] public ResponseEntity<List<FieldTestPagerEntity>> searchFieldTestPagerEntities(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/FieldTestPaginationEntityResource.java:160: warning: no @param for pageable
[WARNING] public ResponseEntity<List<FieldTestPaginationEntity>> searchFieldTestPaginationEntities(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/FieldTestPaginationEntityResource.java:160: warning: no @throws for java.net.URISyntaxException
[WARNING] public ResponseEntity<List<FieldTestPaginationEntity>> searchFieldTestPaginationEntities(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/LabelResource.java:153: warning: no @param for pageable
[WARNING] public ResponseEntity<List<Label>> searchLabels(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/LabelResource.java:153: warning: no @throws for java.net.URISyntaxException
[WARNING] public ResponseEntity<List<Label>> searchLabels(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/OperationResource.java:160: warning: no @param for pageable
[WARNING] public ResponseEntity<List<Operation>> searchOperations(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/OperationResource.java:160: warning: no @throws for java.net.URISyntaxException
[WARNING] public ResponseEntity<List<Operation>> searchOperations(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/TestInfiniteScrollResource.java:167: warning: no @param for pageable
[WARNING] public ResponseEntity<List<TestInfiniteScroll>> searchTestInfiniteScrolls(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/TestInfiniteScrollResource.java:167: warning: no @throws for java.net.URISyntaxException
[WARNING] public ResponseEntity<List<TestInfiniteScroll>> searchTestInfiniteScrolls(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/TestPagerResource.java:167: warning: no @param for pageable
[WARNING] public ResponseEntity<List<TestPager>> searchTestPagers(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/TestPagerResource.java:167: warning: no @throws for java.net.URISyntaxException
[WARNING] public ResponseEntity<List<TestPager>> searchTestPagers(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/TestPaginationResource.java:167: warning: no @param for pageable
[WARNING] public ResponseEntity<List<TestPagination>> searchTestPaginations(@RequestParam String query, Pageable pageable)
[WARNING] ^
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/web/rest/TestPaginationResource.java:167: warning: no @throws for java.net.URISyntaxException
[WARNING] public ResponseEntity<List<TestPagination>> searchTestPaginations(@RequestParam String query, Pageable pageable)
[WARNING] ^
```

### PR DESCRIPTION
**Pull request by sendilkumarn**
fixes #3901

### CODE REVIEW

**Comment by deepu105** [comment]
its failing build


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Is all warnings taken care of?

**Comment by sendilkumarn** [comment]
I am checking on that, i.e., haven't removed WIP.

Lot of methods were missing java doc. I think we have to add those.

**Comment by deepu105** [comment]
Ok i didn't find any further error in the travis build for javadoc so i thought all was well. Can you check the travis log

**Comment by deepu105** [comment]
didnt I merge this?

**Comment by deepu105** [comment]
I this there is only one more warning left for no i18n case
```
1 warning
[WARNING] Javadoc Warnings
[WARNING] /home/travis/app/src/main/java/com/mycompany/myapp/service/LabelService.java:92: warning: no @param for pageable
[WARNING] public Page<Label> search(String query, Pageable pageable) {
[WARNING] ^
```

**Comment by sendilkumarn** [comment]
@deepu105  there are few other warnings too. You can merge this when i remove `WIP`

**Comment by sendilkumarn** [comment]
@deepu105 done 👍

**Comment by jdubois** [comment]
It's my fault: I don't think JavaDoc adds much information. If your method
names and parameter names are good, they do a much better job than the
JavaDoc, and don't become obsolete as fast (as JavaDoc must also be
maintained!).

- we should better remove the JavaDoc checks, rather than add documentation
- there's a good chapter on this in Uncle Bob's "clean code" book

Le 1 août 2016 4:32 AM, "Sendil Kumar N" <notifications@github.com> a
écrit :

**Comment by sendilkumarn** [comment]
agree for javadocs checking 👍

**Comment by atomfrede** [comment]
I also don't like extensive javadocs. Its even worse to enforce javadocs. So if we decide to remove all javadoc from generated code thats fine for me. Good talk by @bkimminich http://no-comments.kimminich.de/#/ what are good, useful comments.

**Comment by sendilkumarn** [comment]
You want to close this ? or remove java docs completely?

**Comment by jdubois** [comment]
I'm merging this, because most of them make sense. But then we should remove the check from the build, as indeed we are not going to document each parameter (they should have a clear name instead).

**Pull request merged**
