### PR TITLE
add pathingJar task to Gradle

### LINKED ISSUE #4323: CreateProcess error=206, The filename or extension is too long.
##### **Overview of the issue**

Gradle `bootRun` task of generated microservice gateway applicaton fails on Windows due to the limit of [Windows’ CreateProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425%28v=vs.85%29.aspx) function. Classpath length of default gateway application exceeds that limit if too much framework selected.

For more info:
http://tuhrig.de/gradles-bootrun-and-windows-command-length-limit/

`gradlew --stacktrace` output:
``` text
...
:bootRun FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':bootRun'.

> A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe''
> ..
> Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bootRun'.
> ..
> Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
>         ... 6 more

BUILD FAILED
```
##### **Motivation for or Use Case**

Generated microservice gateway application cannot be run on Windows.
##### **Reproduce the error**

Generate a microservice gateway application on Windows with preferences of following `.yo-rc.json` file
##### **Related issues**

`_gatling.gradle` has this issue solved #1514 
##### **Suggest a Fix**

Add `pathingJar` task to `_build.gradle` and make `bootRun` dependent to it

http://tuhrig.de/gradles-bootrun-and-windows-command-length-limit/
##### **JHipster Version(s)**

3.9.1/master
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

``` yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

There is no entity, only default gateway application
##### **Browsers and Operating System**

Windows only

### PR DESCRIPTION
**Pull request by mehmet-aslan**
fix #4323

### CODE REVIEW

**Comment by deepu105** [comment]
cc @atomfrede

**Comment by atomfrede** [comment]
I don't know that plugin, but if it works that would be awesome. Need to check on my windows machine in the next couple of days.

**Comment by pascalgrimaud** [comment]
For information, the travis build failed (on uaa build) because your branch is older than 3.9.1

**Comment by mehmet-aslan** [comment]
I rebased but it still fails. I don't think my change is causing this but I don't understand why it fails.

**Comment by atomfrede** [comment]
Sorry didn't had much time to test it on windows, if someone else finds time to check, feel free to go.

**Comment by jdubois** [comment]
The issue is that nobody here has Windows :-)
So we are stuck here!

**Comment by deepu105** [comment]
I have windows but dont have enough time to test this. Will try after next
week

Thanks & regards,
Deepu

**Comment by geraldhumphries** [comment]
I tried this out, it works well. I ran into #4323 last week and this solved it.

**Comment by atomfrede** [comment]
thanks @geraldhumphries for testing!

**Comment by geraldhumphries** [comment]
I recommend doing some more testing before this is merged. I remember having an issue where my dependencies were not updated until I ran `gradle clean`, which is something I didn't have to do without a pathing jar. I am using old versions of both Gradle (2.6) and JHipster (2.27.0).

**Comment by geraldhumphries** [comment]
Never mind, after some more testing it works perfectly. It must have just been a fluke.

**Comment by jdubois** [comment]
OK, let's merge this!

**Comment by sometxdude** [comment]
I just did a fresh install of JHipster 6.0.0 on Windows 10 using Java 11 and Gradle, and I am getting this same path length error.   Looking at my build.gradle, I don't see a pathingJar task in there.  Is this a regression?

**Pull request merged**
