### PR TITLE
Fix popup sign (react)

### PR DESCRIPTION
**Pull request by qmonmert**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Fix bug : #10368

### CODE REVIEW

**Comment by vishal423** [comment]
@qmonmert, can you rebase against master?

**Comment by qmonmert** [comment]
@vishal423 done, but why ?

**Comment by vishal423** [comment]
@qmonmert, because doing that will fix the build and we can merge this PR :smile:

**Comment by qmonmert** [comment]
@vishal423 good reason 🙂

**Pull request merged**
