### PR TITLE
Fix gradle bootJar with dev profile

### LINKED ISSUE #23327: Generated application won't start with `springBootVersion-3.1.3`; throws java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
##### **Overview of the issue**

Hi
I have used the attached .yo.rc.json to generate a sample app to validate 3.1.3 introduction. after building the application with `./gradlew clean -Pdev bootJar` the application wont start with `java -jar build/libs/sample-rest-0.0.1-SNAPSHOT.jar`
Here is the error I get: 
``` Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at com.sample.platform.SampleRestApp.main(SampleRestApp.java:68)
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 9 more ```


##### **Motivation for or Use Case**

Application won't start

##### **Reproduce the error**

basic generation flow and used the attached jdl for sample entities

##### **Related issues**

not aware of any

##### **Suggest a Fix**

Will add as comments if i find any...

##### **JHipster Version(s)**

latest commits of the  branch `main` and commit  `6db9e9e8`.
I suspect, this is something to do with Spring-boot-`3.1.3`, if I change the version to `3.1.2` it works fine...


##### **JHipster configuration**
jhipster info
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0-beta.2

Welcome to the JHipster Information Sub-Generator


```
sample-rest@0.0.1-SNAPSHOT /home/jhipster/app/biskate/tm-trial
└── generator-jhipster@8.0.0-beta.2
```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "applicationType": "monolith",
  "authenticationType": "oauth2",
  "baseName": "sampleRest",
  "blueprints": [],
  "buildTool": "gradle",
  "cacheProvider": "infinispan",
  "clientFramework": "react",
  "clientTheme": "none",
  "creationTimestamp": 1692556734396,
  "cypressAudit": true,
  "cypressCoverage": null,
  "databaseType": "sql",
  "devDatabaseType": "mysql",
  "devServerPort": 9060,
  "dtoSuffix": "DTO",
  "enableGradleEnterprise": null,
  "enableHibernateCache": true,
  "enableSwaggerCodegen": false,
  "enableTranslation": true,
  "entities": [
    "WishList",
    "Address",
    "Category",
    "Customer",
    "Product"
  ],
  "entitySuffix": "",
  "gradleEnterpriseHost": null,
  "jhiPrefix": "tm",
  "jhipsterVersion": "8.0.0-beta.2",
  "languages": [
    "en"
  ],
  "lastLiquibaseTimestamp": 1693197946000,
  "messageBroker": false,
  "microfrontend": false,
  "microfrontends": [],
  "nativeLanguage": "en",
  "otherModules": [],
  "packageFolder": "com/sample/platform",
  "packageName": "com.sample.platform",
  "pages": [],
  "pkType": "UUID",
  "prodDatabaseType": "mysql",
  "reactive": false,
  "searchEngine": "elasticsearch",
  "serverPort": null,
  "serverSideOptions": [
    "searchEngine:elasticsearch"
  ],
  "serviceDiscoveryType": false,
  "skipCheckLengthOfIdentifier": false,
  "skipClient": false,
  "skipFakeData": false,
  "skipUserManagement": true,
  "testFrameworks": [
    "cypress",
    "gatling",
    "cucumber"
  ],
  "websocket": false,
  "withAdminUi": true
}
</pre>
</details>


##### **Environment and Tools**

openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

git version 2.25.1

node: v18.17.1
npm: 9.6.7

'docker' command could not be found

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity WishList {
  title String required
  restricted Boolean
}
entity Address {
  address1 String
  address2 String
  city String
  postcode String required maxlength(10)
  country String required maxlength(2)
}
entity Category {
  description String required
  sortOrder Integer
  dateAdded LocalDate
  dateModified LocalDate
  status CategoryStatus
}
entity Customer {
  firstName String
  lastName String
  email String
  telephone String
}
entity Product {
  title String required
  keywords String
  description String
  rating Integer
  dateAdded LocalDate
  dateModified LocalDate
}
enum CategoryStatus {
  AVAILABLE,
  RESTRICTED,
  DISABLED
}

relationship OneToMany {
  WishList{product(title)} to Product{wishList}
  Customer{wishList(title)} to WishList{customer}
  Customer{address} to Address{customer}
}
relationship ManyToOne {
  Category{parent} to Category
}
relationship ManyToMany {
  Category{product(title)} to Product{category}
}

dto WishList, Address, Category, Customer, Product with mapstruct
paginate WishList, Address, Category, Customer, Product with infinite-scroll
service WishList, Address, Category, Customer, Product with serviceClass
search WishList, Address, Category, Customer, Product with elasticsearch
filter WishList, Address, Category, Customer, Product

</pre>
</details>


Congratulations, JHipster execution is complete!
If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Thanks for using JHipster!

[.yo-rc.json](https://github.com/jhipster/generator-jhipster/files/12450442/yo-rc.json.txt)
<!--
To provide all information we need, you should run `jhipster info` in the project root folder, and
copy/paste the result here.
The `.yo-rc.json` file generated in the root folder is mandatory for bug reports. This will help us to replicate the scenario.
You should remove any sensitive information like the rememberMe key or the jwtSecretKey key.
---
If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
     JDL content here
  </pre>
  </details>
-->

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

MACOS - Ventura - 13.4.1 
JDK - openjdk version "17.0.8.1" 2023-08-24

- [X] Checking this box is mandatory (this is just to show you read everything)

<!-- Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate -->

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #23327 

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by qmonmert** [comment]
@DanielFran not sure if it is the best solution 🙂

**Comment by atomfrede** [comment]
We loose the devtools functionality with that for gradle, right?

**Comment by DanielFran** [comment]
Yes, so it seems not the good option

**Comment by atomfrede** [comment]
As bootjar works with the production profile we don't need to do something. bootRun should work with dev profile and devtools. Bootjar does not include devlopmentOnly dependecies (if I am not mistaken). If we want that we need to add these dependencies to the task.

**Comment by qmonmert** [comment]
with `maven` I try to build jar with the `dev` profile and it seems working

**Comment by atomfrede** [comment]
Even more strange. I guess somehow related how dependencies are resolved (maybe). Would need some more deep digging in whats causing the classpath issue with the restart classloader

**Comment by qmonmert** [comment]
I just tried again on the main branch and I no longer reproduce the bug 🧐

**Pull request closed without merging**
