### PR TITLE
Fix docker-compose subgen: miss semicolon

### PR DESCRIPTION
**Pull request by pascalgrimaud**
thanks @sdoxsee

### CODE REVIEW

**Comment by PierreBesson** [comment]
It was the end of the week, sorry for the mistakes, I will run eslint next time..

**Comment by pascalgrimaud** [comment]
no pb @PierreBesson !
You did a crazy week, with a perfect meetup ! be proud ! ;-)

**Comment by sdoxsee** [comment]
yes. no problem @PierreBesson! You and the team are doing great work. Keep it up! 👍 (and i only discovered it because i've been breaking the build with my PR :P)

**Comment by deepu105** [comment]
how come this originally passeg `npm test` as i had a lint hook on `pre-test`

**Comment by pascalgrimaud** [comment]
Dont worry Deepu, the npm test failed
It was just merged too fast

**Comment by deepu105** [comment]
Oh ok :)

Thanks & Regards,
Deepu

**Pull request merged**
