### PR TITLE
allow searchEngine with boolean value at entities

### PR DESCRIPTION
**Pull request by mshima**
Closes https://github.com/jhipster/generator-jhipster/pull/22867.
Fixes https://github.com/jhipster/generator-jhipster/issues/22866.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@sbouchex can you check if this PR fixes https://github.com/jhipster/generator-jhipster/issues/22866?

**Comment by sbouchex** [comment]
@mshima Does not work in the tests:

My "Tutu" entity is:
`{
  "changelogDate": "20230816200717",
  "entityTableName": "tutu",
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String"
    }
  ],
  "name": "Tutu",
  "pagination": "no",
  "readOnly": false,
  "relationships": [],
  "searchEngine": true,
  "service": "no"
}
`
And I'm getting the following error:
`[INFO] - Generating browser application bundles (phase: setup)...
[INFO] ✔ Browser application bundle generation complete.
[INFO] ✔ Browser application bundle generation complete.
[INFO]
[INFO] Error: src/main/webapp/app/entities/tutu/service/tutu.service.ts:55:13 - error TS2552: Cannot find name 'catchError'. Did you mean 'RTCError'?
[INFO]
[INFO] 55       .pipe(catchError(() => scheduled([new HttpResponse<ITutu[]>()], asapScheduler)));
[INFO]                ~~~~~~~~~~
[INFO]
[INFO]   node_modules/typescript/lib/lib.dom.d.ts:17908:13
[INFO]     17908 declare var RTCError: {
[INFO]                       ~~~~~~~~
[INFO]     'RTCError' is declared here.
[INFO]
[INFO]
[INFO] Error: src/main/webapp/app/entities/tutu/service/tutu.service.ts:55:30 - error TS2304: Cannot find name 'scheduled'.
[INFO]
[INFO] 55       .pipe(catchError(() => scheduled([new HttpResponse<ITutu[]>()], asapScheduler)));
[INFO]                                 ~~~~~~~~~
[INFO]
[INFO]
[INFO] Error: src/main/webapp/app/entities/tutu/service/tutu.service.ts:55:71 - error TS2304: Cannot find name 'asapScheduler'.
[INFO]
[INFO] 55       .pipe(catchError(() => scheduled([new HttpResponse<ITutu[]>()], asapScheduler)));
[INFO]                                                                          ~~~~~~~~~~~~~
[INFO]
[INFO]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
`

**Comment by sbouchex** [comment]
@mshima Java problem now...

`
[INFO] Hibernate JPA 2 Static-Metamodel Generator 6.2.5.Final
[INFO] /home/seb/test-jh/src/main/java/com/mycompany/myapp/config/LocaleConfiguration.java: /home/seb/test-jh/src/main/java/com/mycompany/myapp/config/LocaleConfiguration.java uses or overrides a deprecated API.
[INFO] /home/seb/test-jh/src/main/java/com/mycompany/myapp/config/LocaleConfiguration.java: Recompile with -Xlint:deprecation for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/seb/test-jh/src/main/java/com/mycompany/myapp/web/rest/TutuResource.java:[187,34] cannot find symbol
  symbol:   method search(java.lang.String)
  location: variable tutuRepository of type com.mycompany.myapp.repository.TutuRepository
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.323 s

`

**Comment by mshima** [comment]
I don't think `true` value for searchEngine is supported, it should be `elasticsearch` or `couchbase`.
At backend searchEngineAny is not a valid value since implementation should be elasticsearch or couchbase.
Is there any documentation that `true` value can be used at searchEngine?

**Comment by sbouchex** [comment]
@mshima Look good for me

**Review by DanielFran — APPROVED** [review]

**Pull request merged**
