### PR TITLE
Request to update liquibase

### PR DESCRIPTION
**Pull request by maheshkaranjkar**
Hi Guys,

request you ti kindly upgrade liquibase dependency that we are using currently to latest one.

I am requesting this because, we are using mssql with Jhipster and with and its working properly with latest jar. Exept initial load at first load we need to use default liquibase jar.

Also I am sorry If i made any mistake while raising PR, as I am raising PR on first time.

Thanks & Regards
Mahesh

### CODE REVIEW

**Comment by gmarziou** [comment]
@maheshkaranjkar  your PR pushes 110 commits, please change it

**Comment by gmarziou** [comment]
Also, did you test it with maven and gradle?

**Comment by atomfrede** [comment]
It changes much more than the liquibase version.

**Comment by gmarziou** [comment]
@atomfrede should we close this one and ask @maheshkaranjkar to propose a new one?

**Comment by maheshkaranjkar** [comment]
@gmarziou I have tested it using maven, its working properly (Like creating tables in database.)
Surely I will will change this request if possible or create new one ..
Can you guys please guide me which branch I should compare with master.

Regards
Mahesh

**Comment by maheshkaranjkar** [comment]
Sorry Guys my bad, did wrong comparison while raising PR.
Request you to kindly ignore or close this PR. Also please guide me in same regard if I want to get this PR what criteria should i use to raise request.

Apology for inconvenience and thanks for you help.

Cheers
Mahesh !!

**Comment by gmarziou** [comment]
Did you have a look at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

**Comment by deepu105** [comment]
@maheshkaranjkar check if the liquibase version in this PR suits your need https://github.com/deepu105/generator-jhipster/commit/deb93e1f83d911d0655133e133b967200d4c9bfa

**Comment by maheshkaranjkar** [comment]
@deepu105  yes pr suits for me, How can I update Jhipster to get this changes.

Or do I need to latest stable release of jhipster.

Thanks & Regards
Mahesh

**Comment by deepu105** [comment]
its not merged yet so once merged you can either use the master branch or wait for the release

**Pull request closed without merging**
