### PR TITLE
use correct couchbase reactive repository base class

### LINKED ISSUE #11611: Reactive Couchbase microservice fails to start
##### **Overview of the issue**

I created a Couchbase microservice as part of the following JDL:

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    databaseType neo4j,
    devDatabaseType neo4j,
    prodDatabaseType neo4j,
    enableHibernateCache false,
    reactive true,
    searchEngine elasticsearch,
    serviceDiscoveryType eureka,
    testFrameworks [protractor]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    databaseType couchbase,
    devDatabaseType couchbase,
    prodDatabaseType couchbase,
    enableHibernateCache false,
    reactive true,
    searchEngine elasticsearch,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    reactive true
    searchEngine elasticsearch,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog
```

When I try to run the `blog` microservice, it fails:

```
2020-04-21 10:31:47.247  WARN 36895 --- [  restartedMain] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'blogResource' defined in file [/Users/mraible/reactive/blog/target/classes/com/okta/developer/blog/web/rest/BlogResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.okta.developer.blog.repository.BlogRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2020-04-21 10:31:47.499 ERROR 36895 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.okta.developer.blog.web.rest.BlogResource required a bean of type 'com.okta.developer.blog.repository.BlogRepository' that could not be found.


Action:

Consider defining a bean of type 'com.okta.developer.blog.repository.BlogRepository' in your configuration.
```

##### **Motivation for or Use Case**

You should be able to use Couchbase in a reactive microservice.

##### **Reproduce the error**

See JDL above.

##### **JHipster Version(s)**

master branch as of 10:33AM MDT on Tue, 21 April, 2020

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by atomfrede**
This PR 

* uses `ReactiveN1qlCouchbaseRepository` instead of `ReactiveCouchbaseSortingRepository` for entity repositories
* extend the reactive entity repository template to support Neo4j database

closes #11611

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by murdos** [comment]
Could you also enable couchbase entities in webflux tests, by replacing `none` by `couchbase` please? 
https://github.com/jhipster/generator-jhipster/blob/a9454b016e4c27bffdd92b75d229b5fbe1315515/.github/workflows/webflux.yml#L83
and https://github.com/jhipster/generator-jhipster/blob/a9454b016e4c27bffdd92b75d229b5fbe1315515/.github/workflows/webflux.yml#L88

**Comment by mraible** [comment]
@murdos I made your requested changes to this PR.

**Comment by atomfrede** [comment]
> @murdos I made your requested changes to this PR.

Just wanted to do it, thanks @mraible :heart:

**Comment by mraible** [comment]
@atomfrede FWIW, the missing commons codec dependency is caused by https://github.com/jhipster/jhipster/pull/679.

**Comment by atomfrede** [comment]
> @atomfrede FWIW, the missing commons codec dependency is caused by [jhipster/jhipster#679](https://github.com/jhipster/jhipster/pull/679).

Did a rebase against master, let's see what ci thinks

**Comment by atomfrede** [comment]
Regarding the now failing tests, these is the error I get when running it locally

```
java.lang.ClassCastException: class rx.Observable cannot be cast to class java.lang.Void (rx.Observable is in unnamed module of loader 'app'; java.lang.Void is in module java.base of loader 'bootstrap')
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoMapFuseable] :
	reactor.core.publisher.Mono.map(Mono.java:3046)
	io.github.jhipster.sample.web.rest.EntityWithPaginationAndDTOResource.deleteEntityWithPaginationAndDTO(EntityWithPaginationAndDTOResource.java:150)
Error has been observed at the following site(s):
	|_     Mono.map ⇢ at io.github.jhipster.sample.web.rest.EntityWithPaginationAndDTOResource.deleteEntityWithPaginationAndDTO(EntityWithPaginationAndDTOResource.java:150)
	|_ Mono.flatMap ⇢ at org.springframework.web.reactive.result.method.annotation.ResponseEntityResultHandler.handleResult(ResponseEntityResultHandler.java:128)
	|_   checkpoint ⇢ Handler io.github.jhipster.sample.web.rest.EntityWithPaginationAndDTOResource#deleteEntityWithPaginationAndDTO(String) [DispatcherHandler]
Stack trace:
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
		at rx.internal.reactivestreams.SingleAsPublisher$SingleAsPublisherSubscriber.onSuccess(SingleAsPublisher.java:86)
		at rx.internal.operators.OnSubscribeSingle$1.onCompleted(OnSubscribeSingle.java:55)
		at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
		at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
		at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
		at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
		at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
		at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
		at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
		at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
		at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
		at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
		at rx.internal.producers.SingleProducer.request(SingleProducer.java:75)
		at rx.Subscriber.setProducer(Subscriber.java:211)
		at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
		at rx.Subscriber.setProducer(Subscriber.java:205)
		at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
		at rx.Subscriber.setProducer(Subscriber.java:205)
		at rx.Subscriber.setProducer(Subscriber.java:205)
		at rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:103)
		at com.couchbase.client.core.endpoint.AbstractGenericHandler.completeResponse(AbstractGenericHandler.java:508)
		at com.couchbase.client.core.endpoint.AbstractGenericHandler.access$000(AbstractGenericHandler.java:86)
		at com.couchbase.client.core.endpoint.AbstractGenericHandler$1.call(AbstractGenericHandler.java:526)
		at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)
```

Doing a `.then` instead of `.map` works fine, not sure what other effects that would have. I think for a void mono it doesn't make a difference, or does it?

**Comment by tchlyah** [comment]
> https://github.com/jhipster/generator-jhipster/pull/11421#issuecomment-619746678 Nice work @tchlyah Do you have an idea regarding my comment in #11637? If you are okay with it we can merge #11637 first and have a look at the remaining issue afterwards.

I took a quick look, it seems that [SimpleReactiveCouchbaseRepository#delete()](https://github.com/spring-projects/spring-data-couchbase/blob/761c88703b31b3ff14edf0769ce9e03191c24568/src/main/java/org/springframework/data/couchbase/repository/support/SimpleReactiveCouchbaseRepository.java#L207) responds with an empty Observable, which seems not handled by [ReactiveWrapperConverters#toWrapper()](https://github.com/spring-projects/spring-data-commons/blob/093ff7268de95cb559779c16d68cdf18c5e417ee/src/main/java/org/springframework/data/repository/util/ReactiveWrapperConverters.java#L188). Maybe we need to create an issue in [spring-projects/spring-data-commons](https://github.com/spring-projects/spring-data-commons)

For now I agree with the `then()` approche instead of `map()` for delete methods.

**Comment by atomfrede** [comment]
Thanks @Tcharl I suspected something as it obviously works for mongo.

**Comment by tchlyah** [comment]
> Thanks @Tcharl I suspected something as it obviously works for mongo.

I think you meant me: @tchlyah 😅

**Comment by atomfrede** [comment]
> > Thanks @Tcharl I suspected something as it obviously works for mongo.
> 
> I think you meant me: @tchlyah sweat_smile

:facepalm: Of course

**Pull request merged**
