### PR TITLE
Use Prettier to format YAML

### LINKED ISSUE #8805: Use Prettier for yaml
##### **Overview of the issue**

Prettier is currently used for json, ts, css and scss, but and yaml is also supported.

##### **Motivation for or Use Case**

The YAML part of #8709. Standardise the format of more files. An issues with YAML files is that placeholders become [unordered lists][3], e.g. [`password:`][2] becomes `? password`. We could overcome this by commenting out the keys without values (as suggested [here][5]), but some files would need to be reformatted so that the alignment is still correct. [A comment character and a space][6] will be added for each line that is commented out. 

##### **Reproduce the error**

N/A

##### **Related issues**

None found

##### **Suggest a Fix**

Update YAML files that are affected by Prettier, i.e. they will be off src when generated, so that they will be formatted correctly when Prettier is applied, e.g. the cors part of application.yml.ejs changes from

```yaml
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: "*"
        #allowed-headers: "*"
        <%_ if (authenticationType === 'session') { _%>
        #exposed-headers: "Link,X-Total-Count"
        <%_ } else { _%>
        #exposed-headers: "Authorization,Link,X-Total-Count"
        <%_ } _%>
        #allow-credentials: true
        #max-age: 1800
```

to
```yaml
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    # cors:
    #     allowed-origins: "*"
    #     allowed-methods: "*"
    #     allowed-headers: "*"
          <%_ if (authenticationType === 'session') { _%>
    #     exposed-headers: "Link,X-Total-Count"
          <%_ } else { _%>
    #     exposed-headers: "Authorization,Link,X-Total-Count"
          <%_ } _%>
    #     allow-credentials: true
    #     max-age: 1800
```

##### **JHipster Version(s)**

```
prototype@0.0.0 
`-- generator-jhipster@5.5.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "example",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.17.1.windows.2

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

-   [X] Checking this box is mandatory (this is just to show you read everything)

[2]: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application-dev.yml.ejs#L93
[3]: http://yaml.org/spec/1.2/spec.html#id2761292
[5]: https://github.com/jhipster/generator-jhipster/issues/8709#issuecomment-437836030
[6]: https://github.com/jhipster/generator-jhipster/issues/8709#issuecomment-437866649

### PR DESCRIPTION
**Pull request by Fydon**
Added formatting of YAML files to Prettier, formatted comments in YAML files so that they end up in the correct indentation and changed YAML files that are formatted with an indent of 2 space to 4

Fix #8805

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@Fydon can you also include yaml files to format for example Helm files available in Kubernetes folder? Thanks

**Comment by murdos** [comment]
Changes in packages.json.ejs is fine. But the change of formatting in templates is not required.
Instead, you should add the yml extension to this line: https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base-private.js#L1304 so YAML files will be prettified during the project generation.

It's way better to let Prettier fix our templates on the fly than to maintain prettified templates ;)

**Comment by Fydon** [comment]
@DanielFran my current pull request request focuses on the current definition of applying Prettier to the src  folder. In my project I've extented formatting to the entire project, but with the Prettier ignore file slightly tweaked.

@murdos Some of the formatting is for consistency, so technically unnecessary, but other formatting is due to Prettier formatting comments to where the YAML is now incorrect, leaving the new user lost when their project is broken when they uncomment. Therefore I felt it worth testing the output and tweaking the comments to be positioned where we would expect them to be, rather then where Prettier has put them. This is why leaving Prettier as a post process could cause problems.

**Comment by Fydon** [comment]
Is the generator using the Prettier from [package.json at the root][1]? The React and Angular package.json files are now using the latest versions, so I don't know why the builds started failing with the error `No parser could be inferred for file: src/main/docker/app.yml` when I [added this change][2] to have Prettier run after generation.

[1]: https://github.com/jhipster/generator-jhipster/blob/master/package.json#L72
[2]: https://github.com/jhipster/generator-jhipster/pull/9281/files#diff-91b6e279be2fc1afcd139dd1bb31712bR1304

**Comment by murdos** [comment]
> 
> 
> Is the generator using the Prettier from the [package.json at the root](https://github.com/jhipster/generator-jhipster/blob/master/package.json#L72)? 

Yes. So I guess we should update to the latest version here too.
Could you do that? Thanks.

**Comment by Fydon** [comment]
Yes I'll update that.

Should I update [`eslint-config-prettier` and `eslint-plugin-prettier`][2] as well? Would that mean that I should also update eslint and the other related dependencies?

As a result of updating Prettier for React, I also updated [`tslint` and `tslint-config-prettier`][1], which makes them the same as Angular.

[1]: https://github.com/jhipster/generator-jhipster/pull/9281/files#diff-23480048875e90ad8d9b6e2d4e74bed0R157
[2]: https://github.com/jhipster/generator-jhipster/blob/9f4f760c400d48cb523460d3c8baca57a6ab59f2/package.json#L87

**Comment by murdos** [comment]
> 
> 
> Should I update [`eslint-config-prettier` and `eslint-plugin-prettier`](https://github.com/jhipster/generator-jhipster/blob/9f4f760c400d48cb523460d3c8baca57a6ab59f2/package.json#L87) as well? Would that mean that I should also update eslint and the other related dependencies?

Yeah, please update them too.

**Comment by Fydon** [comment]
Sure. Updated them. I've looked through the change logs, but didn't see any problems: [eslint][1], [eslint-config-prettier][2], [eslint-plugin-import][3] and [eslint-plugin-prettier][4].

[1]: https://github.com/eslint/eslint/blob/master/CHANGELOG.md
[2]: https://github.com/prettier/eslint-config-prettier/blob/master/CHANGELOG.md
[3]: https://github.com/benmosher/eslint-plugin-import/blob/master/CHANGELOG.md
[4]: https://github.com/prettier/eslint-plugin-prettier/blob/master/CHANGELOG.md

**Comment by Fydon** [comment]
What is the reason for setting [eslint-plugin-prettier to error][1] on files not conforming to the Prettier formatting? I thought the Prettier formatting would be applied as a post process to "fix" any files. I assume that this is resulting in [this test failing][2].

[1]: https://github.com/jhipster/generator-jhipster/blob/master/.eslintrc.json#L8
[2]: https://travis-ci.org/jhipster/generator-jhipster/jobs/496245939#L1471

**Comment by Fydon** [comment]
1. Following on from my previous comment, should we use something like `lint-staged` to force running `eslint --fix` or Prettier on commit?
2. Should I include `.yml` in [package.json][1] so that `.travis.yml` and `azure-pipeliness.yml` are formatted by Prettier?

I've now run `eslint --fix` so that the tests should pass.

[1]: https://github.com/jhipster/generator-jhipster/pull/9281/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R39

**Comment by murdos** [comment]
> 
> 
>     1. Following on from my previous comment, should we use something like `lint-staged` to force running `eslint --fix` or Prettier on commit?

We don't do that for other files, so no.

>
>     2. Should I include `.yml` in [package.json](https://github.com/jhipster/generator-jhipster/pull/9281/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R39) so that `.travis.yml` and `azure-pipeliness.yml` are formatted by Prettier?

I'm not sure.
@pascalgrimaud : what do you think?

> 
> 
> I've now run `eslint --fix` so that the tests should pass.

Great! Could you also resolve the conflicts? Then we should be able to merge.

**Comment by pascalgrimaud** [comment]
I'm ok for formatting the Travis and Azure file, used for our Continuous Integration, if it doesn't break anything :-)

**Comment by Fydon** [comment]
I've now also applied the formatting to the Travis and Azure files.

@murdos I only suggested `lint-staged` because that is what the [Angular][1] and [React][2] projects generated by this project use, but sure I'll leave it as is.

I've resolved the conflicts, which included `package-lock.json`. I can't tell for certain what the result of dependencies are for `package-lock.json`, so I instead used npm to provide a valid `package-lock.json` with the resolved `package.json` file. I'll wait for the tests to complete, but probably should rather merge current changes into my branch and then push my branch again to minimise the differences.

[1]: https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/package.json.ejs#L158
[2]: https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/package.json.ejs#L181

**Comment by Fydon** [comment]
I've rebased my changes to the latest master even though all the tests passed, as it probably results in a better `package-lock.json`.

**Comment by murdos** [comment]
Thanks Fydon ! 👍

**Pull request merged**
