### PR TITLE
Update jhipster-react version to 0.24.0

### PR DESCRIPTION
**Pull request by DanielFran**
Related with https://github.com/jhipster/generator-jhipster/issues/20849
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by qmonmert** [comment]
I thin we need to upgrade `react-hook-form` in https://github.com/jhipster/react-jhipster

**Comment by DanielFran** [comment]
@mshima, thanks for the fix.
Do you know why there was no issue targetting directly jhipster/react-jhipster main branch?

**Comment by mshima** [comment]
Probably because libs was not updated: https://github.com/jhipster/react-jhipster/commit/c67f560a13a31210614023f07cc516a4d45cb79c.

To avoid this problem we can:
- check if libs is updated at ci.
- use prepare script to build libs on demand.

**Comment by DanielFran** [comment]
@mshima Can you do a PR to fix that so that we can create a new version with the new PR available?

**Comment by mshima** [comment]
@DanielFran sure, but v0.24.0 release is ok, no need for v0.24.1.
We need to fix to install from git only.

**Comment by DanielFran** [comment]
@mshima Wanted to create a new version 0.25.0 with https://github.com/jhipster/react-jhipster/pull/94, so will wait that your changes are merged

**Pull request merged**
