### PR TITLE
Update docker image version

### PR DESCRIPTION
**Pull request by DanielFran**
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
plz @DanielFran, use your fork instead of directly upstream. So it won't trigger twice the builds :-D

**Comment by mshima** [comment]
@pascalgrimaud or name it with skip_ci_ prefix 😄

**Comment by pascalgrimaud** [comment]
@mshima : I saw it in all your branch name. Cna you explain to me the tips plz ? What does skip_ci do ?

**Comment by mshima** [comment]
@pascalgrimaud I've added this rule to every workflow except `generator.yml`.
https://github.com/jhipster/generator-jhipster/blob/160de3f1b1f9debcf779e66986a12c46affa7b66/.github/workflows/angular.yml#L23-L25

- Our personal repository has only 20 parallels workers
- Each push have almost 40 build taking ~18 min each.
- It would take 35 min to finish each push.

**Comment by pascalgrimaud** [comment]
So if I understand well:
- each time you pushed to your branch, GitHub Actions doesn't trigger the build as it's ignored
- only pull request will launch builds

Am I correct ?

**Comment by mshima** [comment]
> Am I correct ?

Yes, I always use PRs to test due to
- selective builds
- diff of generated source.

**Comment by pascalgrimaud** [comment]
nice to know this
thanks for the information @mshima :)

**Pull request merged**
