### PR TITLE
Fix i18n templates path when using a blueprint

### LINKED ISSUE #9459: Using noI18n with a blueprint throw an exception
##### **Overview of the issue**
When we generate a new project with a blueprint and choose to not have i18n the generator throw an exception when generate files.

##### **Motivation for or Use Case**
Avoid the exception ;) and make possible to have both blueprint and noi18n.

##### **Reproduce the error**
Run `jhipster --blueprint myBlueprint` where myBlueprint is a known blueprint (previously linked with npm in dev mode). When the question `Would you like to enable internationalization support?` is asked choose "no".

When files are generates an exception is raised :
```Error: /Users/aviard/projects/jhipster-myBlueprint/generator-jhipster-myBlueprint/generators/languages/templates/src/main/webapp/i18n/en/home.json.ejs doesn't exist```

Of course JHipster is looking for i18n files in my blueprint instead of the main generator project.

We must load them from JHipster. 

##### **Related issues**
none

##### **Suggest a Fix**
In utils.js instead of use relative path to store the languages templates path use an abslolute one.

From
```
const LANGUAGES_MAIN_SRC_DIR = `../../languages/templates/${constants.CLIENT_MAIN_SRC_DIR}`;
```

To
```
const LANGUAGES_MAIN_SRC_DIR = `${__dirname}/languages/templates/${constants.CLIENT_MAIN_SRC_DIR}`;
```

Also remove `path.join(generator.sourceRoot(), filename)` when resolve the filename.

the whole called stack is:
generatorBase: copyTemplate() 
=> utils: copyWebResource() 
=> utils: replaceTranslation() or replacePlaceholders() or replaceTitle()
=> utils: geti18nJson()

##### **JHipster Version(s)**
5.8.2

##### **JHipster configuration**

> {
  "generator-jhipster-myBlueprint": {
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "debugVsCodeFolder",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZjdjZjdkMGRjZDVjMzNhYWNkYmRkNjZkMDFkYzUyYWJjNzU2MDYzMTEzMzA3YWJjYmQ4NTVlYWEyNTc3YmRhMGExZTE1N2I2Y2RlYmU3ZjBiNmM0Njc2ZmVlYTg1M2UzMTQ5ZjZiZjRjMmM2MjYwNTQxNjU4YzdiYmI3MWQ5NDk=",
    "useLogm": true,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "enableTranslation": false
  },
  "generator-jhipster": {
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "debugVsCodeFolder",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-myBlueprint",
        "version": "0.0.0"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprint": "generator-jhipster-myBlueprint",
    "blueprintVersion": "0.0.0"
  }
}

##### **Browsers and Operating System**
Mac OS X

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by avdev4j**
Fix #9459
-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
Can this be merged?

**Comment by avdev4j** [comment]
hi @mraible 
This fix a bug encountered in my blueprint project. But I can't reproduce with an empty blueprint.
Anyway I think it's better to use global variable like `__dirname`.

We could merge it or take time to find where the problem come from.

**Comment by jdubois** [comment]
If it helps you @avdev4j let's do this - you're spending all your time at work on a blueprint, you know more than any of us

**Comment by deepu105** [comment]
@avdev4j were there unit tests for this already? if not can you add some as the change might introduce side effects on some other use case

**Pull request merged**
