### PR TITLE
Map oauth realm and client roles. Fixes #11361

### LINKED ISSUE #11361: OAuth realms roles and client roles do not work together
##### **Overview of the issue**

In our setup we use Keycloak as SSO server for OAuth. If you use realm roles together with client roles the JHipster application is unable to obtain the client roles

##### **Motivation for or Use Case**

A combination of realm and client roles should be possible since the are just roles with different scope.

##### **Reproduce the error**

Configure both realm and client roles for a user. The client roles will not be available to the application.

##### **JHipster Version(s)**
6.6.0

##### **JHipster Version(s)**

```
#######@0.0.1-SNAPSHOT ######
└── generator-jhipster@6.6.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "#####",
      "nativeLanguage": "de",
      "microservicePath": "../#####/"
    },
    "jhipsterVersion": "6.6.0",
    "applicationType": "gateway",
    "baseName": "#####",
    "packageName": "#####",
    "packageFolder": "#####",
    "serverPort": "8082",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "yarn",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "de"],
    "blueprints": [],
    "creationTimestamp": 1579530224774
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

git version 2.25.0

node: v13.1.0

npm: 6.12.1

yeoman: 2.0.0

yarn: 1.22.0

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

macOS Catalina 10.15.3
Chrome 80.0.3987.116

-   [ x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by andreasfranz**
-   Fixes #11361
-   Please make sure the below checklist is followed for Pull Requests.

-   [ x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ x] Tests are added where necessary
-   [ x] Documentation is added/updated where necessary
-   [ x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
@andreasfranz, can you provide more details on how it solves the issue? As per my understanding, the `group` claim was for `Okta` and the `roles` claim was for `Keycloak`. 

To fix the issue, you might require a change in default realm configurations to cleanup the `jhipster` client scope.

**Comment by andreasfranz** [comment]
@vishal423 Are are currently migrating to Keycloak 9.0.1. Therefore we checked the integration with our JHipster applications. Somehow the client roles weren't mapped correctly anymore. The realm roles e.g.  Keycloak's default `uma_authorization` and `offline_access` realm roles appear in the `groups` part of the claim and the client roles appear in the `roles`.

**Comment by vishal423** [comment]
@andreasfranz, sorry, I still don't get you. Can you please provide an `access token` response that contains the `groups` claim?

**Comment by andreasfranz** [comment]
> @andreasfranz, sorry, I still don't get you. Can you please provide an `access token` response that contains the `groups` claim?
This is from my code breakpoint
```
claims = {Collections$UnmodifiableMap@20606}  size = 13
 "sub" -> "a######-######-######-######-######3"
 "address" -> {LinkedHashMap@21260}  size = 0
 "email_verified" -> {Boolean@21262} true
 "roles" -> {ArrayList@21241}  size = 5
  key = "roles"
  value = {ArrayList@21241}  size = 5
   0 = "ROLE_D######"
   1 = "ROLE_USER"
   2 = "ROLE_######"
   3 = "ROLE_ADMIN"
   4 = "ROLE_D######"
 "groups" -> {ArrayList@21265}  size = 2
  key = "groups"
  value = {ArrayList@21265}  size = 2
   0 = "offline_access"
   1 = "uma_authorization"
 "preferred_username" -> "######"
 "given_name" -> "######"
 "locale" -> "en"
 "upn" -> "######"
 "langKey" -> "en"
 "name" -> "######"
 "family_name" -> "######"
 "email" -> "######"
```

**Comment by mraible** [comment]
Your 'groups` values look like scopes. `offline_access` is one of the [optional scopes in OIDC](https://openid.net/specs/openid-connect-basic-1_0.html#Scopes).

**Comment by andreasfranz** [comment]
image
@mraible those two are just realm roles

**Comment by vishal423** [comment]
@andreasfranz, I believe the response you pasted is of `UserInfo` claims and not that of the `access token` claims. Have you associated client roles with the user info response? Also, the `groups` claim in the response is coming due to the `microprofile-jwt` client scope and the default mapping of that is with the realm roles.

In either case, your PR is not fixing the issue to fetch client roles and associate those with the access token/user info/id token.

**Comment by mraible** [comment]
I don't think this is necessary, that's why I've closed the issue it references. Please re-open if you believe differently.

**Pull request closed without merging**
