### PR TITLE
Elasticsearch should not be generated for all entities, only for those which are actually marked with it

### PR DESCRIPTION
**Pull request by ko5tik**
Search artifacts shall be generated only when entity  explicitely specifies then
See ticket:
Fix https://github.com/jhipster/generator-jhipster/issues/17142

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by ko5tik** [comment]
Just to remind -  would please somebody review this?

**Comment by mraible** [comment]
Thanks for the PR! People are more likely to review this when all CI tests are passing.

**Comment by pascalgrimaud** [comment]
@ko5tik : can you have a look on git history plz ? It's not normal to have 164 additional commits here. Plz update your branch or rebase

**Comment by ko5tik** [comment]
Will have to sort my commits out.    Somehow fetching upstream did not work as intendet

**Comment by ko5tik** [comment]
Created new branch which is  in synch

**Comment by ko5tik** [comment]
Branch recreated, all CI tests re green
========[] Lines game back in Appstore - check it out! []===============
https://play.google.com/store/apps/details?id=de.pribluda.games.android.lines

Blog:  https://www.pribluda.de

**Comment by RDsideNow** [comment]
I dont think this one is fixed.  Elastic search is still generated for all entities instead of only the ones marked in Jhipster 7.5.0.

**Comment by ko5tik** [comment]
Checked with angular frontend -   works as intendet

**Comment by mshima** [comment]
@RDsideNow its related to microservice only.
Monoliths are still opt-out, will generate for every entity if not disabled.

**Comment by RDsideNow** [comment]
paginate * with pagination
dto * with mapstruct
filter *
search Message with elasticsearch

application {
  config {
    baseName appgateway,
    applicationType gateway,
    packageName com.appgateway,
    serverPort 8080,
    serviceDiscoveryType eureka,
    authenticationType oauth2,
    cacheProvider hazelcast,
    enableHibernateCache false,
    databaseType sql,
    devDatabaseType postgresql,
    prodDatabaseType postgresql,
    enableSwaggerCodegen false,
    searchEngine elasticsearch,
    buildTool gradle,
    messageBroker kafka,
    clientPackageManager npm,
    testFrameworks [
          gatling,
          cucumber,
          cypress
        ],
    enableTranslation true,
    nativeLanguage en,
    languages [
          fr,
          es,
          en
        ],
    jhiPrefix jhi,
    dtoSuffix DTO,
    clientFramework angularX
  }
  entities *
}

application {
  config {
    baseName messaging,
    applicationType microservice,
    packageName com.messaging,
    serverPort 10004,
    serviceDiscoveryType eureka,
    authenticationType oauth2,
    cacheProvider hazelcast,
    enableHibernateCache false,
    databaseType sql,
    devDatabaseType postgresql,
    prodDatabaseType postgresql,
    enableSwaggerCodegen false,
    searchEngine elasticsearch,
    buildTool gradle,
    messageBroker kafka,
    clientPackageManager npm,
    testFrameworks [
          gatling,
          cucumber,
          cypress
        ],
    enableTranslation true,
    nativeLanguage en,
    languages [
          fr,
          es,
          en
        ],
    jhiPrefix jhi,
    dtoSuffix DTO,
    clientFramework angularX
  }
  entities Message, MessageTemplate
}

entity Message {
	sourceId String,
    sourceType MessageSourceType required,
	sentFrom String required,
    sendTo String required,
    subject String,
    content TextBlob required
}

enum MessageSourceType {
	ORDER,
    VENDOR
}

entity MessageTemplate {
	name String unique required,
    subject String,
    sourceType MessageSourceType required,
    content TextBlob required
}

relationship ManyToOne {
	Message{messageTemplate(name)} to MessageTemplate
}

microservice Message, MessageTemplate with messaging

This is the JDL i used.

Both the backend and frontend generated for all entities not just the message entity

**Comment by ko5tik** [comment]
It is imporant to see what is in the entity  files located under .jhipster in respective applications.

**Comment by RDsideNow** [comment]
This is the message.json

{
  "name": "Message",
  "fields": [
    {
      "fieldName": "sourceId",
      "fieldType": "String"
    },
    {
      "fieldName": "sourceType",
      "fieldType": "MessageSourceType",
      "fieldValues": "ORDER,VENDOR",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "sentFrom",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "sendTo",
      "fieldType": "String",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "subject",
      "fieldType": "String"
    },
    {
      "fieldName": "content",
      "fieldType": "byte[]",
      "fieldTypeBlobContent": "text",
      "fieldValidateRules": ["required"]
    }
  ],
  "relationships": [
    {
      "relationshipType": "many-to-one",
      "otherEntityName": "messageTemplate",
      "otherEntityRelationshipName": "message",
      "relationshipName": "messageTemplate",
      "otherEntityField": "name"
    }
  ],
  "entityTableName": "message",
  "dto": "mapstruct",
  "pagination": "pagination",
  "service": "serviceClass",
  "jpaMetamodelFiltering": true,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "applications": ["appgateway", "messaging"],
  "microserviceName": "messaging",
  "searchEngine": "elasticsearch",
  "clientRootFolder": "messaging",
  "databaseType": "sql",
  "changelogDate": "20220106003111"
}

**Comment by RDsideNow** [comment]
this is the messageTemplate.json

{
  "name": "MessageTemplate",
  "fields": [
    {
      "fieldName": "name",
      "fieldType": "String",
      "fieldValidateRules": ["unique", "required"]
    },
    {
      "fieldName": "subject",
      "fieldType": "String"
    },
    {
      "fieldName": "sourceType",
      "fieldType": "MessageSourceType",
      "fieldValues": "ORDER,VENDOR",
      "fieldValidateRules": ["required"]
    },
    {
      "fieldName": "content",
      "fieldType": "byte[]",
      "fieldTypeBlobContent": "text",
      "fieldValidateRules": ["required"]
    }
  ],
  "relationships": [],
  "entityTableName": "message_template",
  "dto": "mapstruct",
  "pagination": "pagination",
  "service": "serviceClass",
  "jpaMetamodelFiltering": true,
  "fluentMethods": true,
  "readOnly": false,
  "embedded": false,
  "applications": ["appgateway", "messaging"],
  "microserviceName": "messaging",
  "clientRootFolder": "messaging",
  "databaseType": "sql",
  "changelogDate": "20220106003011"
}

**Comment by RDsideNow** [comment]
Screen Shot 2022-01-11 at 8 12 39 PM
Screen Shot 2022-01-11 at 8 16 17 PM

**Pull request closed without merging**
