### PR TITLE
Refactor the entity -> ResponseEntity(...) conversion, to remove a co…

### PR DESCRIPTION
**Pull request by gzsombor**
…uple of lines of code, and optimize

 the user updating, to avoid the 2 separate transactions - one for the update, and one for the load.

### CODE REVIEW

**Comment by gzsombor** [comment]
@deepu105 , @jdubois : what do you think?

**Comment by deepu105** [comment]
I'm ok with it. since @jdubois is refactoring common code to the lib I'll wait for his opinion here

**Comment by jdubois** [comment]
Yes the code look better. I didn't check for the transaction, but I trust you, and that's indeed better.

My main concern is the use for this new utility class - I'm not a big fan of using a utility class everywhere. Anyway, that's was why I was waiting to have #4674 closed before commenting: this should go in the lib, and then that's less of an issue.

**Comment by gzsombor** [comment]
Yes, it's a primary candidate for the lib 👍 :)

**Comment by deepu105** [comment]
then may be we can merge it and then move it to lib

**Comment by jdubois** [comment]
Just wait a little bit, I guess we can already merge the lib, I'm just waiting for some feedback

**Comment by jdubois** [comment]
Now the library is merged, @gzsombor can you refactor your PR?

**Comment by deepu105** [comment]
please hold on refactoring as I'm refactoring the entity folder structure

**Comment by deepu105** [comment]
The source folder structure have changed so you might wanna update them

**Comment by gzsombor** [comment]
I've moved to util class to the jhipster library. Unfortunately this means, that this pull request can't be merged until a new jhipster release is come out !

**Comment by gzsombor** [comment]
@jdubois : could you do a jhipster-lib release?

**Comment by jdubois** [comment]
@gzsombor done! Should be on Maven Central in less than 2 hours.

**Comment by gzsombor** [comment]
Thanks, it seems now it's mergeable !

**Pull request merged**
