### PR TITLE
Correct typos (breaking changes for v7)

### PR DESCRIPTION
**Pull request by vivekmore**
Continuation of #10788 (for next major release)

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by avdev4j** [comment]
hi @vivekmore 
I wonder if we should go further and rename the generator base function `aski18n` while we introduce breaking changes.

WDYT

**Comment by vivekmore** [comment]
> I wonder if we should go further and rename the generator base function `aski18n` while we introduce breaking changes.


I like it - I don't remember if there was a reason for leaving it out of my PR.
I've updated my PR with your suggested change, hopefully the PR build doesn't break

**Comment by avdev4j** [comment]
I think we will have break issues with modules and blueprints that will still use the old methods.

**Comment by vivekmore** [comment]
> I think we will have break issues with modules and blueprints that will still use the old methods.

yes I thought that was clear from the title (these are breaking changes)

**Comment by avdev4j** [comment]
hi @vivekmore 
I just wanted to confirm you that there is a risk to have breaking issues for some blueprints. unfortunately I don't know which blueprint can be affected, maybe none.

**Pull request merged**
