### PR TITLE
#11088 replace email validation regex with the keycloak one

### LINKED ISSUE #11088: ConstraintViolation on valid e-mail addresses
##### **Overview of the issue**
A ConstraintViolation can be thrown if a given email address like example+alias@gmail.com get validated with the given validation regex pattern.

But keycloak doesn't have a problem with the given e-mail addresses. 
Because the plus char doesn't make the mail invalid.
So it might be the best solution to use the same regex pattern like keycloak does.

See: https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/services/validation/Validation.java#L45

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/Constants.java.ejs#L28

INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
generator-jhipster@6.6.0 /home/xxx/generator-jhipster
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

git version 2.17.1

node: v12.13.1

npm: 6.12.1

Docker version 19.03.5, build 633a0ea838

docker-compose version 1.17.1, build unknown

### PR DESCRIPTION
**Pull request by jepp-igus**
Fix #11088

### CODE REVIEW

**Comment by jepp-igus** [comment]
WIP

**Comment by ruddell** [comment]
The errors in the CI show that this change expects all logins to be in email format.  For other auth types (such as JWT), logins are not emails.  Would adding a `+` to the login regex solve the issue?

**Comment by jepp-igus** [comment]
> The errors in the CI show that this change expects all logins to be in email format. For other auth types (such as JWT), logins are not emails. Would adding a `+` to the login regex solve the issue?

Thank you for your reply.

There might be the case, that someone wants to login with his "nickname". The login name "admin" wouldn't be possible anymore after changing regex for the login name.
In my case, I'm using the login attribute with e-mail addresses.

Also thought about changing the regex again, but it would't be compliant with the keycloak one.

I need to rethink about this..

**Comment by DanielFran** [comment]
Closed/Reopening to launch tests again...

**Comment by pascalgrimaud** [comment]
closing this, in favor of https://github.com/jhipster/generator-jhipster/pull/11450

**Pull request closed without merging**
