### PR TITLE
Sync db dialects across generator

### PR DESCRIPTION
**Pull request by pmverma**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
Agree with @murdos.
And probably better place is in generator constants...

**Comment by pmverma** [comment]
Thank you, @murdos and @DanielFran.
Totally agree with you.
Will do so in another PR.

**Comment by deepu105** [comment]
Guys, I hope these are not breaking changes?

**Comment by pmverma** [comment]
I think not because I used dialect versions from `application-prod.yml` to update other places.
However, MySQL and MariaDB now use their own dialect with the latest dialect version.

**Pull request merged**
