### PR TITLE
Fix #2663 - join cucumber, integration and unit reports

### LINKED ISSUE #2663: CucumberTest override report test generated by Unit Test and Integration Test
When run gradle test, the report generated in build/reports/tests only show the results for Cucumber Test.

I'm doing a PR for this problem.

### PR DESCRIPTION
**Pull request by phouverneyuff**

### CODE REVIEW

**Comment by deepu105** [comment]
@phouverneyuff next time plz put the fix #2663 keyword in the PR body and not in the title plz

**Comment by deepu105** [comment]
does this not affect Maven build?

**Comment by phouverneyuff** [comment]
Maven don't have cucumber test and integration/unit test running separately. So, I guess no.

**Comment by pascalgrimaud** [comment]
Not sure about that : https://github.com/jhipster/generator-jhipster/pull/2589

**Comment by phouverneyuff** [comment]
Someone know do the something with maven?

@lordlothar99 Can you confirm if with maven you have problem with test report. 
Look the issue #2663 please.

**Comment by lordlothar99** [comment]
hi @phouverneyuff , I'm having a look at that

**Comment by lordlothar99** [comment]
I just tested test reports generation with maven on 2.27.0 : all reports are generated in "target/surefire-reports" directory. Everything is fine with maven in my point of view

**Comment by phouverneyuff** [comment]
So, the problem with test reports just happen with gradle.
@deepu105 I guess that's ok to merge

**Pull request merged**
