### PR TITLE
Support for session auth in reactive apps

### PR DESCRIPTION
**Pull request by cbornet**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Note : no support for remember-me (the checkbox is still present in the front but has no effect)

### CODE REVIEW

**Comment by cbornet** [comment]
My idea was to first generate them and move them to the framework later when we put the reactive option out of experimental. But I can do it right now if you prefer.

**Comment by jdubois** [comment]
@cbornet I don't think they do any harm in the framework... Do you think there could be some bad side effect? Otherwise just do it the simplest way for you - if it's easier in the generator for you, let's keep those as you did

**Comment by cbornet** [comment]
I can put them into the framework, no problem. I guess we just have to set the `spring-mvc` and `spring-webflux` deps as provided.

**Comment by DanielFran** [comment]
Closing/Reopening to launch tests after merged https://github.com/jhipster/jhipster/pull/198

**Comment by jdubois** [comment]
Thanks @cbornet as https://github.com/jhipster/jhipster/pull/198 is merged that should be OK!

**Comment by jdubois** [comment]
I've deployed the updated JAR dependencies and framework 3.0.0-SNAPSHOT so I'm merging this.

**Pull request merged**
