### PR TITLE
Use table name for constraints and join tables

### PR DESCRIPTION
**Pull request by rubensa**
Custom table names should be used to generate restrictions (foreign
keys, for example) and join tables (if they are needed).

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Closes: #8609

### CODE REVIEW

**Comment by jdubois** [comment]
Oh that's clever, indeed we should have done that from the start, thanks @rubensa !
I'm doing some small tests as I don't think many people use that feature, so that shouldn't be an issue for most people, and then I'll merge it.

**Comment by jdubois** [comment]
Thanks @rubensa !

**Comment by rubensa** [comment]
> Thanks @rubensa !

Thanks to you @jdubois

**Comment by rubensa** [comment]
Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/6406

**Pull request merged**
