### PR TITLE
Restructure main generator

### PR DESCRIPTION
**Pull request by deepu105**
This ones gonna be crazy :)

Split the main generator into two, so that main generator actually composes these two to offer current behaviour

- `jhipster:server` : same as `jhipster --skip-client`
- `jhipster:client` : generates an angular webapp alone

both options have many flags that can be passed on

this is to faciliate easy maintanance once microservices are in.

The authentication part and user-management also needs to be moved to its own generator if possible

### CODE REVIEW

**Comment by moifort** [comment]
giphy

**Comment by moifort** [comment]
I don't know whats happen @deepu105 but since more than one month you work like a crazy!!!

:+1: :+1:  :+1:

**Comment by deepu105** [comment]
coz i finished my last project and back to sales team and this month has been less work so more time for this :)

**Comment by deepu105** [comment]
@jdubois sorry for restructuring again, plz take a quick look if possible. I have merged your recent commits as well. this will be better for maintenance for us

**Comment by deepu105** [comment]
btw i generated apps with current master and compared output with this to make sure nothing has changed in what is generated.

the gradle build would fail again, would need someone to chmod gradlew and mvnw files coz im on windows

**Comment by deepu105** [comment]
I promise no more restructuring for this release :)

**Comment by deepu105** [comment]
@jdubois This is causing too many merge conflicts and its a bit tough to manually resolve so merging (rebased twice today and it took more time than what i took to do the original changes) this once CI is complete. I have tested this enough already and we can test further on master

**Comment by deepu105** [comment]
all passed, seems doing CHMOD on files from git bash on windows works

**Comment by jdubois** [comment]
That's really an awesome work Deepu!!! Unfortunately I don't have the time
to review this now, will do as soon as I have some free time.
Le 4 févr. 2016 6:13 AM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
@jdubois I have merged it any way to avoid any conflicts, once you have a look at the diff let me know if any change is needed and ill do it

**Pull request merged**
