### PR TITLE
Upgrade to spring-boot 1.5.9 and mapstruct to 1.2.0.Final

### PR DESCRIPTION
**Pull request by DanielFran**
See http://mapstruct.org/news/2017-10-18-mapstruct-1_2_0_Final-is-out/

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
Align versions with jhipster-dependencies 0.1.0: upgrade spring-boot to 1.5.9 https://github.com/jhipster/jhipster-dependencies/pull/23

**Comment by erikkemperman** [comment]
FYI we’ll also need some changes to adapt to new Hazelcast when jhipster-generator is released with the new spring-platform and spring-boot. I have those figured out already.

**Comment by erikkemperman** [comment]
@DanielFran Maybe you should change the title of this PR, it's more about upgrading spring-platform / spring-boot right? Of course this PR has to wait until a new release of jhipster-dependencies is out with those changes in, and then it will be 0.1.1 or 0.2.0.

**Comment by pascalgrimaud** [comment]
@DanielFran : no worry, don't hesitate to ask advice, reviews etc.

Thanks and congrats for your 1st contribution !

**Comment by erikkemperman** [comment]
All right, it looks like jhipster-dependencies is now released at 0.1.4 with the platform upgrade in it:
https://github.com/jhipster/jhipster-dependencies/commit/c99496994853efd7064a0f86171853c2ff04fd0f

But to work in the generator, we'll also need a patch to accommodate the new Hazelcast version. If you want to copy/paste, please feel free, I've got the needed changes here:
https://github.com/erikkemperman/generator-jhipster/commit/673b5c59c9dfec87ae6d2b3e71fbafbf3b7920e4

**Comment by jdubois** [comment]
Thanks @erikkemperman - I didn't see your comment yesterday, but that's all merged now, so it should be good

**Pull request merged**
