### PR TITLE
WIP [Angular] Upgrade Webpack

### PR DESCRIPTION
**Pull request by qmonmert**
14 late versions

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@qmonmert please see https://github.com/jhipster/generator-jhipster/blob/ea922e77a568818408bebfeff0ef4a10b999c7a5/.github/dependabot.yml#L28-L29

v12 has is in branch v12.2.x now:
https://github.com/angular/angular-cli/blob/3040fde07088ea81966d32e48412f832f24294be/packages/angular_devkit/build_webpack/package.json#L16

Why is that a problem?
`@angular-devkit/build-webpack` will alway instantiate `webpack@5.50.0`.
If others modules instantiates different webpack plugins that resolves to other webpack version, the result is unexpected.
We had several problems over the time with this.

The best scenario is for us to remove the webpack dependency and rely on npm to do the deduplication.
But npm wasn't resolving webpack version uniquely by the time I've tested, causing this problem.
The only fix I found was to add webpack dependency that matches the `@angular-devkit/build-webpack` one.

**Comment by mshima** [comment]
Like the one dev server is failing:
```
(node:2798) UnhandledPromiseRejectionWarning: TypeError: The 'compilation' argument must be an instance of Compilation
```
`Compilation` from `webpack@5.50.0` is different from `Compilation` from `weppack@5.64.0.`.

**Comment by qmonmert** [comment]
@mshima ok thanks

**Comment by mshima** [comment]
Still not resolved:
```
% npm ls webpack
npm-test@0.0.1-SNAPSHOT /Users/mshima/aplicacoes/npm_test
├─┬ @angular-devkit/build-angular@12.2.13
│ ├─┬ @angular-devkit/build-optimizer@0.1202.13
│ │ └── webpack@5.64.0 deduped
│ ├─┬ @ngtools/webpack@12.2.13
│ │ └── webpack@5.64.0 deduped
│ ├─┬ babel-loader@8.2.2
│ │ └── webpack@5.64.0 deduped
│ ├─┬ circular-dependency-plugin@5.2.2
│ │ └── webpack@5.64.0 deduped
│ ├─┬ copy-webpack-plugin@9.0.1
│ │ └── webpack@5.50.0 deduped
│ ├─┬ css-loader@6.2.0
│ │ └── webpack@5.64.0 deduped
│ ├─┬ css-minimizer-webpack-plugin@3.0.2
│ │ └── webpack@5.64.0 deduped
│ ├─┬ less-loader@10.0.1
│ │ └── webpack@5.64.0 deduped
│ ├─┬ mini-css-extract-plugin@2.4.2
│ │ └── webpack@5.64.0 deduped
│ ├─┬ postcss-loader@6.1.1
│ │ └── webpack@5.64.0 deduped
│ ├─┬ sass-loader@12.1.0
│ │ └── webpack@5.64.0 deduped
│ ├─┬ source-map-loader@3.0.0
│ │ └── webpack@5.64.0 deduped
│ ├─┬ style-loader@3.2.1
│ │ └── webpack@5.64.0 deduped
│ ├─┬ stylus-loader@6.1.0
│ │ └── webpack@5.64.0 deduped
│ ├─┬ terser-webpack-plugin@5.1.4
│ │ └── webpack@5.64.0 deduped
│ ├─┬ webpack-dev-middleware@5.0.0
│ │ └── webpack@5.64.0 deduped
│ ├─┬ webpack-dev-server@3.11.2
│ │ ├─┬ webpack-dev-middleware@3.7.3
│ │ │ └── webpack@5.50.0 deduped
│ │ └── webpack@5.50.0 deduped
│ ├─┬ webpack-subresource-integrity@1.5.2
│ │ └── webpack@5.64.0 deduped
│ └── webpack@5.50.0
├─┬ @angular-devkit/build-webpack@0.1202.13
│ ├─┬ webpack-dev-server@3.11.3
│ │ ├─┬ webpack-dev-middleware@3.7.3
│ │ │ └── webpack@5.64.0 deduped
│ │ └── webpack@5.64.0 deduped
│ └── webpack@5.64.0
├─┬ browser-sync-webpack-plugin@2.3.0
│ └── webpack@5.64.0 deduped
├─┬ copy-webpack-plugin@9.1.0
│ └── webpack@5.64.0 deduped
└─┬ eslint-webpack-plugin@3.1.1
  └── webpack@5.64.0 deduped
```

**Pull request closed without merging**
