### PR TITLE
workaround consul-loader startup at m1

### PR DESCRIPTION
**Pull request by mshima**
Workaround https://github.com/jhipster/generator-jhipster/issues/20598

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
@mshima Is there a particular CI job that shows this works?

**Comment by mshima** [comment]
@mraible at both microservices tests with consul, containers starts successfully.

**Comment by mraible** [comment]
Since we own the [consul-config-loader](https://github.com/jhipster/consul-config-loader) project, wouldn't it be better to publish a version that works with Apple Silicon? I'm guessing we already do this for JHipster Registry, but I might be wrong.

**Comment by mshima** [comment]
Yes, registry is compatible with arm64.
I will try to update the consul-loader.

**Pull request closed without merging**
