### PR TITLE
Bumped font awesome dependencies

### PR DESCRIPTION
**Pull request by vishal423**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
React as well please if applicable

**Comment by vishal423** [comment]
I created this PR specific to angular as corresponding changes in `ng-jhipster` are already in place. In absence of this, you would see peer version mismatch warnings during installation.

I will check on react side and will sync in separate PR, if applicable.

**Comment by vishal423** [comment]
updated for react as well :)

**Comment by jdubois** [comment]
Thanks @vishal423 !

**Pull request merged**
