### PR TITLE
fix generation of FK constraints for @ManyToMany

### LINKED ISSUE #9050: CI test broken after merge of "Singularize JoinColumn names in ManyToMany #8815"
##### **Overview of the issue**

CI test broken for configuration:  `JHI_APP=ngx-psql-es-noi18n JHI_PROFILE=prod JHI_PROTRACTOR=1 JHI_ENTITY=sqlfull`

after merge of  #8815 - Singularize JoinColumn names in ManyToMany.

See travis logs at : https://travis-ci.org/jhipster/generator-jhipster/jobs/478594259

##### **Motivation for or Use Case**

The generated Liquibase "xxx_added_entity_constraints_*.xml" for `@ManyToMany` relationships are invalid and hence the build fails.

##### **Reproduce the error**

Generate new app using sample `sqlfull`

##### **Related issues**

Relates to #8447 

##### **Suggest a Fix**

Will submit a PR that fixes the problem

##### **JHipster Version(s)**

Current master - 5.7.3

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by pvliss**
Fixes #9050

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pvliss** [comment]
@DanielFran Oh cool. Did not realize you were also looking at it but as I have fixed it locally before adding the issue I submitted the PR

**Comment by DanielFran** [comment]
@pvliss I merge the PR and figure out after the issue but its was to late...😴 and I neede the sleep a litle 😂

**Comment by pvliss** [comment]
@DanielFran That's ok. No harm done. One can always fix locally and report back as in this case. I only realized the issue after I rebased my PR and show the build was failing, so I started debugging it as I though it was my fault and I had already slept more than enough :smile:

**Comment by pvliss** [comment]
@DanielFran Thanks for merging :+1:

**Comment by pascalgrimaud** [comment]
thanks so much, guys !

**Pull request merged**
