### PR TITLE
Indent

### PR DESCRIPTION
**Pull request by agoncal**
- Here add what you have done
I am at the bar with @pascalgrimaud and @PierreBesson and we are having fun with Guiness, Leffe and  (fu$*`%$^p) Yarn Link

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
ahahah cheers :beers:

**Comment by pascalgrimaud** [comment]
the build is green, so let's merge

**Comment by deepu105** [comment]
But its ok since you guys are having fun :)

**Comment by jdubois** [comment]
Yes thanks to Prettier you can code while being drunk, it will correct your mistakes :-)

**Comment by pascalgrimaud** [comment]
yes, we saw it !!!
Prettier is really nice

Le 31 janv. 2018 8:45 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Pull request merged**
