### PR TITLE
updated bootstrap4 and ng-bootstrap

### LINKED ISSUE #4928: [Enhance] Upgrade to Bootstrap 4.0.0 to latest release
Upgrade bootstrap to 4.0.0-alpha.6 or latest and update ng-bootstrap to latest.

BS4 alpha 6 has some breaking changes. Flexbox is now default hence it disrupts our UI.

We need to move `navbar-toggleable-md` class from inner div to the nav element
We also need to add below to navbar.css/scss for getting link colors back
```
.jh-navbar a:not(.dropdown-item) {
    color: rgba(255, 255, 255, 0.7);
}

.jh-navbar a:not(.dropdown-item):hover {
    color: #ffffff;
}
```

There seems to be float issues as normal css float wont work in flexbox
In dialog headers the order of close btn and header text needs to be swapped

### PR DESCRIPTION
**Pull request by sendilkumarn**
adds bootstrap4.alpha 6
and 
upgrades ng-bootstrap to alpha 20

`navbar ` is revamped in bootstrap4's latest version.
fix #4928

### CODE REVIEW

**Comment by deepu105** [comment]
Ill test it tomorrow

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
fix for #4928

**Comment by sendilkumarn** [comment]
Interesting tag was again reverted to badge which is not documented in the document :/

**Comment by deepu105** [comment]
I have fixed the remaining issues and entity subgen :)

**Pull request merged**
