### PR TITLE
Improve Docker image cache usage by reordering commands in app template Docker file

### PR DESCRIPTION
**Pull request by smasset**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by smasset** [comment]
With current app Dockerfile template, there is little usage of Docker image cache as the application war file (which is the most frequently changing artefact in the build) is added first.

**Comment by smasset** [comment]
Hard to write automated tests for this but here are docker build output from two successive builds with the current template:

| First build | Second build |
| ------------ | ------------- |
| `Building rone-app` | `Building rone-app` |
| `Step 1/5 : FROM openjdk:8-jre-alpine` | `Step 1/5 : FROM openjdk:8-jre-alpine` |
| ` ---> b36ec9de53a8` | ` ---> b36ec9de53a8` |
| `Step 2/5 : ENV SPRING_OUTPUT_ANSI_ENABLED ALWAYS JHIPSTER_SLEEP 0 JAVA_OPTS ""` | `Step 2/5 : ENV SPRING_OUTPUT_ANSI_ENABLED ALWAYS JHIPSTER_SLEEP 0 JAVA_OPTS ""` |
| ` ---> Running in 6e23601aa8a5` | **` ---> Using cache`** |
| ` ---> 0460e2488473` | ` ---> 0460e2488473` |
| `Removing intermediate container 6e23601aa8a5` |  |
| `Step 3/5 : ADD *.war /app.war` | `Step 3/5 : ADD *.war /app.war` |
| ` ---> 132ddc08baea` | ` ---> cc03c5444504` |
| `Step 4/5 : EXPOSE 8080` | `Step 4/5 : EXPOSE 8080` |
| ` ---> Running in a10085ecaea3` | ` ---> Running in 527df88976e4` |
| ` ---> 7e4306b9e720` | ` ---> 8541078c860d` |
| `Removing intermediate container a10085ecaea3` | `Removing intermediate container 527df88976e4` |
| `Step 5/5 : CMD echo "The application will start in ${JHIPSTER_SLEEP}s..." &&     sleep ${JHIPSTER_SLEEP} &&     java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.war` | `Step 5/5 : CMD echo "The application will start in ${JHIPSTER_SLEEP}s..." &&     sleep ${JHIPSTER_SLEEP} &&     java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.war` |
| ` ---> Running in ada2fd351a48` | ` ---> Running in 6ca843c52a77` |
| ` ---> 87de37bd0212` | ` ---> 263627cecc3e` |
| `Removing intermediate container ada2fd351a48` | `Removing intermediate container 6ca843c52a77` |
| `Successfully built 87de37bd0212` | `Successfully built 263627cecc3e` |
| `Successfully tagged rone:latest` | `Successfully tagged rone:latest` |

**Comment by smasset** [comment]
Here are the output from two successive builds with the updated template

| First build | Second build |
| - | - |
| `Building rone-app` | `Building rone-app` |
| `Step 1/5 : FROM openjdk:8-jre-alpine` | `Step 1/5 : FROM openjdk:8-jre-alpine` |
| ` ---> b36ec9de53a8` | ` ---> b36ec9de53a8` |
| `Step 2/5 : ENV SPRING_OUTPUT_ANSI_ENABLED ALWAYS JHIPSTER_SLEEP 0 JAVA_OPTS ""` | `Step 2/5 : ENV SPRING_OUTPUT_ANSI_ENABLED ALWAYS JHIPSTER_SLEEP 0 JAVA_OPTS ""` |
| ` ---> Using cache` | ` ---> Using cache` |
| ` ---> 0460e2488473` | ` ---> 0460e2488473` |
| `Step 3/5 : CMD echo "The application will start in ${JHIPSTER_SLEEP}s..." &&     sleep ${JHIPSTER_SLEEP} &&     java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.war` | `Step 3/5 : CMD echo "The application will start in ${JHIPSTER_SLEEP}s..." &&     sleep ${JHIPSTER_SLEEP} &&     java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.war` |
| ` ---> Running in f1bb4ee556e0` | **` ---> Using cache`** |
| ` ---> 09e9342c675e` | ` ---> 09e9342c675e` |
| `Removing intermediate container f1bb4ee556e0` |  |
| `Step 4/5 : EXPOSE 8080` | `Step 4/5 : EXPOSE 8080` |
| ` ---> Running in 34561f76e923` | **` ---> Using cache`** |
| ` ---> cb39a2a832f8` | ` ---> cb39a2a832f8` |
| `Removing intermediate container 34561f76e923` |  |
| `Step 5/5 : ADD *.war /app.war` | `Step 5/5 : ADD *.war /app.war` |
| ` ---> cde5b10cd9b5` | ` ---> 93ed80aac0ad` |
| `Successfully built cde5b10cd9b5` | `Successfully built 93ed80aac0ad` |
| `Successfully tagged rone:latest` | `Successfully tagged rone:latest` |

**Comment by pascalgrimaud** [comment]
LGTM and thanks for all explanations.

**Comment by smasset** [comment]
No pb. The hardest part was getting the right markdown

**Comment by jdubois** [comment]
This is indeed awesome! Can't wait to try this, thanks @smasset & congrats on your first PR!

**Comment by gmarziou** [comment]
Awesome, great first PR!

**Comment by smasset** [comment]
Thanks for merging it so quickly

**Pull request merged**
