### PR TITLE
Simplify SecurityConfiguration templates

### PR DESCRIPTION
**Pull request by cbornet**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
As I'm going to do a release today, @cbornet are you confident about this? And if you remove `MicroserviceSecurityConfiguration`, shouldn't this be cleaned up by Yeoman in https://github.com/jhipster/generator-jhipster/blob/master/generators/cleanup.js ?

**Comment by cbornet** [comment]
I have done a lot of tests but as this is sensitive/security, I think it's better to wait for the next release.
There's no need to cleanup since MicroserviceSecurityConfiguration is renamed to SecurityConfiguration.

**Comment by jdubois** [comment]
For the cleanup: people who upgrade would then have both files, which would lead to problems

**Comment by cbornet** [comment]
No I mean this PR doesn't change anything to the name of the files that are generated. It's always `SecurityConfiguration.java`. `MicroserviceSecurityConfiguration` is only an ejs template, not a Java file.

**Comment by jdubois** [comment]
Oh sorry, this has changed! Thanks @cbornet

**Comment by jdubois** [comment]
Yes let's do this

**Pull request merged**
