### PR TITLE
Chore/move to async for prompts

### PR DESCRIPTION
**Pull request by sendilkumarn**
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary - NA
-   [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary - NA
-   [x] Documentation is added/updated where necessary - NA
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by avdev4j** [comment]
Hi @sendilkumarn 
what is the main pros to move to async function instead of using "done()"?

**Review by mshima — APPROVED** [review]
LGTM

**Comment by mshima** [comment]
> Hi @sendilkumarn
> what is the main pros to move to async function instead of using "done()

I see the following reasons:
- more linear, in this case 1 level is not too much.
- better error handling: promises should have a catch block.
- easier then promise notation `new Promise().then(resolved => done(undefined, resolved), error => done(error))`

**Comment by sendilkumarn** [comment]
All that @mshima told + more readability

**Pull request merged**
