### PR TITLE
Update to Angular 5

### PR DESCRIPTION
**Pull request by sendilkumarn**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by Tcharl** [comment]
Now, there's an issue with ng-jhipster.
I really do not understand how it works: it says that its not able to inject JhiAlert dependencies, but nothing has changed until the old ngjh version.
Do someone has an idea?

**Comment by sendilkumarn** [comment]
@Tcharl what is the error ?

**Comment by Tcharl** [comment]
Angular is not able to instantiate JhiAlertService due to missing constructor parameter injectable

**Comment by jmesa-sistel** [comment]
Are you testing AOT?
More changes are needed to build using AOT.
For example aot folder will not created, now it is done in memory, so app.main-aot.ts has to be changed:
Fom:
`import { Gulliver2AppModuleNgFactory } from '../../../../target/aot/src/main/webapp/app/app.module.ngfactory';`
To:
`import { Gulliver2AppModuleNgFactory } from './app.module.ngfactory';`

Also webpack.prod.js has to be adapted tsConfigPath instead tsConfig
Also: ([angular/issues/11580](https://github.com/angular/angular/issues/11580#issuecomment-327338189))
```
new webpack.ContextReplacementPlugin(
                /(.+)?angular(\\|\/)core(.+)?/,               
                utils.root('src/main/webapp/app'), {}
            ),

```
And more changes are required. I can not build AOT properly, I have more errors.

**Comment by deepu105** [comment]
Guys can somebody summarize what are the outstanding issues here? I can try to take a look

**Comment by jmesa-sistel** [comment]
After update ng-hjipster to 0.3.0 to use angular5, seems that there is a circular reference, and now angular 5 compiler report a runtime error:
Can't resolve all parameters for JhiAlertService: (?, ?, ?).
I have tried to fix it but I have not found how to fix it. Not sure if the problem is in ng-hjipster or in the generated app.

AOT:
I have been able to manage to build AOT modifying a little webpack.prod.js, now app.main-aot.ts has to be deleted. To build AOT the only way I have found is adding entryModule option in NgcWebpackPlugin with mainPath is not working for me, I get a lot of info in this issue (https://github.com/angular/angular/issues/20216)

**Comment by iuliust** [comment]
I too have this error :
Can't resolve all parameters for JhiAlertService: (?, ?, ?).

**Comment by sendilkumarn** [comment]
closing this on favor of #6789

**Comment by sendilkumarn** [comment]
@iuliust  It will be solved in the new version.

@jmesa-sistel  Please look at the latest version, it is because angular expects the dependencies to be explicit from ng5

**Pull request closed without merging**
