### PR TITLE
Upgrade to Angular 6

### PR DESCRIPTION
**Pull request by wmarques**
Still WIP, need to check if I correctly migrated the rxjs imports.
I wanted to remove the `rxjs-compat` dependency but some libs aren't rxjs6 compliant (ngx-webstorage, ngx-infinite-scroll)...

TODO:
* Migrate angular cli config file to new format
* Upgrade injection using the [new DI injection ](https://angular.io/guide/dependency-injection)?

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by wmarques** [comment]
Seems that we cannot use a custom webpack build with angular-cli... When I try to `ng eject` an Angular 6 app generated with Angular CLI 6, it tells me that the support for `eject`has been removed 😞

**Comment by wmarques** [comment]
I don't know how to be still angular CLI compliant, it always generate the component under a wrong path even if I specifiy `src/main/webapp`as the root src directory in the `angular.json` file...

**Comment by sendilkumarn** [comment]
@wmarques that seems weird, `eject` is removed in v6, with the idea of using it via `angular-cli.json`

**Comment by sendilkumarn** [comment]
@wmarques lets list the issues that we have currently on this probably in a doc, what say?

**Comment by wmarques** [comment]
@sendilkumarn Yes, strange... If you guys have any idea about adapting the angular.json file to make it work..
Sure, we can merge this once I've resolved the conflict and then I will work on migrating to the new DI injection syntax :)

**Comment by wmarques** [comment]
Let me rebase again, the travis build fails doesn't seem related to my PR...

**Comment by thainan10** [comment]
@wmarques have you tried to follow the steps of this Angular helper [website](https://update.angular.io/) to upgrade the version?

**Comment by wmarques** [comment]
I think we can merge this and I'll start migrating on [the new DI injection system](https://angular.io/guide/dependency-injection#singleton-services) on a next PR, we also need the ng-jhipster lib to migrate

**Comment by pascalgrimaud** [comment]
Congrats @wmarques for the hard work !

**Comment by wmarques** [comment]
Well I had enough time to move to the new Dependency Injection so I merged my work on this PR, let me know if you have any feedbacks

**Comment by pascalgrimaud** [comment]
Travis back to red since your last commit, sorry @wmarques

**Comment by jdubois** [comment]
@pascalgrimaud it's probably my fault, it's corrected now, @wmarques can you rebase?

**Comment by pascalgrimaud** [comment]
@wmarques : fyi, there are some conflicts after the merge of your other PR https://github.com/jhipster/generator-jhipster/pull/7634

**Comment by jdubois** [comment]
This looks all good, let's merge it as this can't be in a separate branch for long (we'll get lots of conflicts)

**Comment by sendilkumarn** [comment]
@wmarques great work 👏 It would be awesome to get the stats after this

**Comment by jdubois** [comment]
@wmarques just one issue: when you do some responsive tests (putting the app in a small window, in fact), the menu doesn't show up :-(
This is probably because of your changes, could you check?

**Comment by deepu105** [comment]
@wmarques does the new DI affect lazy loading? Since many services are in root now?

**Pull request merged**
