### PR TITLE
exclude node_modules  dir in idea project

### PR DESCRIPTION
**Pull request by rover12421**
https://www.jhipster.tech/configuring-ide-idea/

can remove "Exclude directories" node

### CODE REVIEW

**Comment by jdubois** [comment]
Oh that's awesome, I'd love to have this in Maven (but I don't think it's as easy to do)

**Comment by atomfrede** [comment]
@rover12421 Great, never thought of that. Thx.

**Comment by atomfrede** [comment]
@rover12421 Great, never thought of that. Thx.

**Comment by pvliss** [comment]
Just my 2 cents. I am using IntelliJ IDEA Ultimate 2018.3.2 and the `node_modules` directory is excluded by the IDE by default. I even tested selecting the dir, then clicking on "Mark as--> Not excluded" and then refreshed the project (Re-import for Maven and Refresh all Gradle projects) and the folder was automatically added to the excluded folders list by IntelliJ. So this step seems to be no longer necessary

**Comment by pvliss** [comment]
Oh it might be because of the .gitignore file. Will check

**Comment by atomfrede** [comment]
For me too, but it doesn't hurt to make it explicit because I remember older versions which didn't ignore `node_modules` (maybe it depends on installed js tools/plugins).

**Comment by pvliss** [comment]
> For me too, but it doesn't hurt to make it explicit because I remember older versions which didn't ignore `node_modules` (maybe it depends on installed js tools/plugins).

I definitely agree as other maybe using older versions.

Out of interest though I re-checked this time generating projects skipping git ,
e.g: 
```bash
jhipster --force --no-insight --skip-checks --with-entities --skip-git --skip-commit-hook --from-cl
```
and then removing the .gitignore file manually. For both Maven ad Gradle and IDEA still seems to auto-exclude the node_modules dir although it also marks it as a 'library root' and continues to index it.

@rover12421's change is also properly excluding the dir and seems to be no longer indexed or marked as library root which makes the loading of the project a lot faster

**Comment by pvliss** [comment]
It definitely makes project loading faster but it also seems to disable auto-completion, code navigation, etc. for the frontend development, which seems kind of expected as the folder is no longer indexed. I believe that many users will not be happy with that.

@atomfrede  can you please also check? Maybe I am missing something

**Pull request merged**
