### PR TITLE
fix: From Yarn 1.0 scripts don't require "--" for options to be forwarded

### PR DESCRIPTION
**Pull request by aneri90**
This PR resolve Yarn warning 

`From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.`

while remaining compliant to npm syntax.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
Very clever idea @aneri90. I have wanted to do it before but didn't think this could be done with a simple EJS variable.
I'm just waiting for the tests to pass and we will merge it in time for the JHipster 5 release.

**Comment by jdubois** [comment]
Awesome!! And sorry you seem to have conflict with some of my recent changes... If you don't have time I'll do it

**Comment by PierreBesson** [comment]
It's OK, we don't impose anything. You have the choice of merge or rebase to synchronize your branch,

**Comment by PierreBesson** [comment]
The build failure is actually from the master branch so so I'm merging this.

**Pull request merged**
