### PR TITLE
Move app prompts to a new module.

### PR DESCRIPTION
**Pull request by mshima**
Instead of making app blueprint compatible https://github.com/jhipster/generator-jhipster/issues/9692

Move prompts to a new blueprint compatible module.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@mshima : thanks a lot for your last contributions and PR
As you modified the core system for improving the blueprint, your PRs need to be reviewed and tested closely. We do our best so please, plz be patient :-)

**Comment by avdev4j** [comment]
hi @mshima 
IMHO your PR has a high value and need to be closely reviewed. I think this is a way we have to go. In the past, I tried to find a good solution to manage app prompts by providing a way to define default values and override them in blueprints.

As you can see I failed ;), so I'm very interested in what you suggest.

Another way I found is to use this library:
https://www.npmjs.com/package/yeoman-option-or-prompt

To wrap prompts and provide a way to define the answer directly from the command line. I have not tested yet, but is it a way, for you, we should consider?

**Comment by mshima** [comment]
> hi @mshima
> IMHO your PR has a high value and need to be closely reviewed. I think this is a way we have to go. In the past, I tried to find a good solution to manage app prompts by providing a way to define default values and override them in blueprints.
> 
> As you can see I failed ;), so I'm very interested in what you suggest.

jhipster workflow is messy right now =/.
I am trying to improve it with https://github.com/jhipster/generator-jhipster/pull/10527, https://github.com/jhipster/generator-jhipster/pull/10554, https://github.com/jhipster/generator-jhipster/pull/10587 and this PR.

We really should enable DEBUG=yeoman:* on CI and update yeoman-generator as soon https://github.com/yeoman/generator/pull/1128 is merged and released. This will improve debugging a lot.

> 
> Another way I found is to use this library:
> https://www.npmjs.com/package/yeoman-option-or-prompt
> 
> To wrap prompts and provide a way to define the answer directly from the command line. I have not tested yet, but is it a way, for you, we should consider?

The idea is good, but I don't think so.
It would be an alternative for https://github.com/jhipster/generator-jhipster/pull/10493. 
Current state will open up configs too much and expose many bugs.
When the workflow is fixed and improved config validation is on place, then it would be great.

**Comment by mshima** [comment]
@avdev4j can you review https://github.com/jhipster/generator-jhipster/pull/10587?
This PR contains that PR because I have found those problems after creating this PR.

It will make this PR simpler.

**Comment by murdos** [comment]
Closing this PR since #9692 has been fixed.

**Pull request closed without merging**
