### PR TITLE
Add serverPort for Docker Compose and OAuth 2.0

### LINKED ISSUE #8311: Docker Compose sub-generator stacktrace when generating microservices + OAuth 2.0
##### **Overview of the issue**

I generated a microservices architecture that uses OAuth 2.0 for authentication. This is part of a demo I do for my "Microservices for the Masses" presentation. Today, when I tried to create a Docker Compose configuration, I found it spits out a stack trace. 

I believe this is caused by the fact that the Docker containers are not built, but it used to spit out a much nicer error message with commands on how to build them.

```
Checking Docker images in applications' directories...
ls: no such file or directory: /Users/mraible/apps/blog/target/docker
ls: no such file or directory: /Users/mraible/apps/store/target/docker
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! Copying template realm-config/jhipster-realm.json.ejs failed. [ReferenceError: /Users/mraible/.nvm/versions/node/v8.11.3/lib/node_modules/generator-jhipster/generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:736
    734|       "id": "1eabef67-6473-4ba8-b07c-14bdbae4aaed",
    735|       "clientId": "web_app",
 >> 736|       "rootUrl": "http://localhost:<%= serverPort %>",
    737|       "adminUrl": "http://localhost:<%= serverPort %>",
    738|       "surrogateAuthRequired": false,
    739|       "enabled": true,
```

##### **Motivation for or Use Case**

It worked the last time I tried it, which was Aug 14, 2018, with JHipster 5.1.0. I know because that's when I last updated [this blog post](https://developer.okta.com/blog/2018/03/01/develop-microservices-jhipster-oauth).

##### **Reproduce the error**

Create a microservices architecture with OAuth 2.0, then run the Docker Compose sub-generator.

##### **Related issues**

Possibly related to https://github.com/jhipster/generator-jhipster/pull/8176, since Keycloak files were changed. 

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/mraible/apps/gateway
└── generator-jhipster@5.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.3.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (Zulu 8.31.0.1-macosx) (build 1.8.0_181-b02)
OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-macosx) (build 25.181-b02, mixed mode)

git version 2.15.2 (Apple Git-101.1)

node: v8.11.3

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

### PR DESCRIPTION
**Pull request by mraible**
Fixes #8311.

### CODE REVIEW

**Comment by vishal423** [comment]
@mraible , Instead of adding new variable, can you check if replacing `"http://localhost:<%= serverPort %>"` with `<%- keycloakRedirectUri %>` fixes the issue (2 occurrences). I missed doing this while upgrading configurations

**Comment by mraible** [comment]
@vishal423 - that won't work because `<%- keycloakRedirectUri %>` is set to something like `http://localhost:8080/*`.

**Comment by vishal423** [comment]
yeah, that contain extra `/*` in the end. Looking at code and usage, I am not sure if we really need variable for port as that would always map to `8080`

**Comment by pascalgrimaud** [comment]
@vishal423 : you're right here, but I think we have a problem when using the docker-compose sub generator with this configuration:
- microservice gateway with oauth2 + server port different from 8080

**Comment by vishal423** [comment]
@pascalgrimaud, I don't see an issue because in docker-compose sub-generator, we always map gateway/monolithic application port number (which could be different) to 8080. So, keeping this constant in realm configuration would be cleaner at moment (which was before as well). Also, `keycloakRedirectUri`, seems to be redundant and can be constant.

**Pull request merged**
