### PR TITLE
Don't use query parameter for password reset

### LINKED ISSUE #1729: Reset password finish is posting the password in the URL querystring instead of body
On the second phase of resetting your password (finish), the new password and key are being posted to the server as part of the querystring instead of the request body.

Is this not a security problem? e.g. URLs may be stored in web server request logs?

### PR DESCRIPTION
**Pull request by atomfrede**
Resetkey and new password are posted as bodyparam

Fix #1729

### CODE REVIEW

**Comment by jdubois** [comment]
I understand the issue, then having a new file just for that is annoying... Besides I'm not even sure it should be in the "domain" package

**Comment by atomfrede** [comment]
I was not sure too :) But had no better place. What about an inner class?

**Comment by gzsombor** [comment]
If I were you, I would put that class into web/rest/dto package, and name as '...DTO', just for consistency

**Comment by jdubois** [comment]
I like the inner class, as this won't be used elsewhere, but indeed we usually put this in the DTO package, so it would be more consistant -> this should be further discussed (but I agree on the general idea, this should be implemented)

**Comment by atomfrede** [comment]
I like the inner class, so it can't be used elsewhere (maybe we can name it something like ``KeyAndPasswordDTO``).

**Comment by jdubois** [comment]
@atomfrede agreed, but then we are not consistent with the LoggerDTO, for example -> should we refactor?

**Comment by atomfrede** [comment]
KeyAndPassword are now a DTO

**Comment by deepu105** [comment]
@atomfrede I guess you need to do a rebase?

**Comment by atomfrede** [comment]
Yes 😀 will try it today, yesterday was no time left.

**Pull request merged**
