### PR TITLE
update ng-jhipster and react-jhipster

### PR DESCRIPTION
**Pull request by ruddell**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I'm testing this, and there is a lot of errors during `npm test`

**Comment by pascalgrimaud** [comment]
I'm on it and trying to fix it

**Comment by pascalgrimaud** [comment]
I forgot the magic tips about updating the PR
So I did a PR against @ruddell's branch: https://github.com/ruddell/generator-jhipster/pull/1

**Comment by jdubois** [comment]
Awesome @pascalgrimaud but I guess @ruddell is sleeping now (given his time zone), so your built succeeded but I don't have it and can't merge this PR....

I think I'm going to merge this and then apply your patch on it.

**Comment by pascalgrimaud** [comment]
Yes, my Azure build succeeded: https://dev.azure.com/pascalgrimaud/generator-jhipster/_build/results?buildId=279&view=logs
If you can merge and cherry-pick my fix, it would be cool

**Comment by jdubois** [comment]
I'm trying to do it, but that's not easy :-(

**Comment by pascalgrimaud** [comment]
Do you want me to do it ?

**Comment by jdubois** [comment]
It should be OK, can you have a look? Tons of Git magic :-)

**Comment by pascalgrimaud** [comment]
Looks good! Thanks Julien. I'm going to do some quick tests locally:
- default react app
- react noi18

**Comment by jdubois** [comment]
Thanks a lot, I'm testing too, and then let's release!

**Comment by ruddell** [comment]
Thanks for taking care of this while I was sleeping 👍

**Pull request merged**
