### PR TITLE
Change docker compose file version number from 2.2 to 2 for elasticsearch

### LINKED ISSUE #9442: Starting the app with docker-compose up is failing because of version mismatch.
##### **Overview of the issue**

An application generated with current master branch (including v5.8.0 and >) will fail to start with `docker-compose -f src/main/docker/app.yml up` because of version mismatch.

```
ERROR: Version mismatch: file ./src/main/docker/app.yml specifies version 2.0 but extension file ......../src/main/docker/elasticsearch.yml uses version 2.2

```
##### **Motivation for or Use Case**

Application should start normally with docker-compose.

##### **Reproduce the error**

1. Generate a fresh app with current master
2. Run `./mvnw package -Pprod verify jib:dockerBuild`
3. Run `docker-compose -f src/main/docker/app.yml up`

##### **Related issues**

PR https://github.com/jhipster/generator-jhipster/pull/9065

##### **Suggest a Fix**

If there is no any special requirement to specify the version `2.2` in `elasticsearch.yml` then I would suggest to use version as `2`.
@pvliss should know it better as he has fixed some CI issue in the same commit done for version upgrade.

https://github.com/jhipster/generator-jhipster/commit/e0df187dcc0a492768d29b8b2a253dd5a9876f09#diff-48f10816873d8282f0bc1e95e245580a
 

##### **JHipster Version(s)**

```
filter@0.0.0 /Users/sierra/github/pmverma/filter
└── generator-jhipster@5.8.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "filter",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.17.2 (Apple Git-113)

node: v10.14.2

npm: 6.7.0

yeoman: 2.0.5

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by pmverma**
Fixes #9442

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by ruddell** [comment]
@pvliss I see in https://github.com/jhipster/generator-jhipster/commit/e0df187dcc0a492768d29b8b2a253dd5a9876f09#diff-48f10816873d8282f0bc1e95e245580a you updated to `2.2`, was there a specific reason we need `2.2`?

**Comment by pmverma** [comment]
This PR is ready to be merged.

**Comment by pmverma** [comment]
Thanks @ruddell .

**Comment by pvliss** [comment]
Thanks @pmverma and @ruddell

**Pull request merged**
