### PR TITLE
Align deps with Spring Boot 1.5.1

### PR DESCRIPTION
**Pull request by erikkemperman**
Ref. https://github.com/jhipster/generator-jhipster/issues/5045#issuecomment-281356924

Tests are [passing](https://travis-ci.org/erikkemperman/generator-jhipster/builds/203813272).

Remove some version strings so that we implicitly get (and keep getting) the ones from `spring-boot-dependencies`.

### CODE REVIEW

**Comment by jdubois** [comment]
Unfortunately there is a conflict with your previous PR

**Comment by erikkemperman** [comment]
That was to be expected I suppose. I'll rebase now!

**Comment by jdubois** [comment]
Thanks! I'll merge this quickly -> I'm going to do some complete tests now anyway, so I might as well test with all those changes

**Comment by erikkemperman** [comment]
@jdubois Thanks for quick review :-) There's another minor PR coming in, let me rebase and push.

**Comment by jdubois** [comment]
Oh OK! I'm full testing mode now, so that's perfect

**Comment by erikkemperman** [comment]
[Here](https://github.com/jhipster/generator-jhipster/pull/5275) it is :-) I didn't wait for all tests to finish on Travis for this branch, but it was about halfway through and all green.

**Pull request merged**
