### PR TITLE
Redux 5.0.0

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #24480 

Tests based on https://github.com/reduxjs/redux-toolkit/blob/635d6d5e513e13dd59cd717f600d501b30ca2381/src/tests/createAsyncThunk.test.ts

TODO:
- [x] skip tests
- [x] update dependencies
- [x] remove redux-thunk 
- [x] some refacto (duplication ...)

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
@qmonmert Should [this dependabot PR](https://github.com/jhipster/generator-jhipster/pull/24485) be closed in favor of this PR?

**Comment by qmonmert** [comment]
@mraible yes there are changes to do with Redux 5.0.0

**Comment by mraible** [comment]
@qmonmert All tests pass! Are you interested in including this in 8.1.0? If so, I'd merge now and move the other items to other issues.

**Comment by qmonmert** [comment]
@mraible like I said in the description, it is not finished, there is again a lot of work

**Review by DanielFran — APPROVED** [review]

**Comment by qmonmert** [comment]
@DanielFran https://opencollective.com/generator-jhipster/expenses/177821  🙂

**Comment by DanielFran** [comment]
@qmonmert approved

**Comment by qmonmert** [comment]
@DanielFran thanks

**Pull request merged**
