### PR TITLE
Prefer project scoped node/npm binaries over global binaries

### PR DESCRIPTION
**Pull request by mshima**
Closes https://github.com/jhipster/generator-jhipster/issues/14249

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by atomfrede — APPROVED** [review]
This looks good. Should we merge it?

**Comment by DanielFran** [comment]
@mshima is it OK to merge?

**Review by DanielFran — APPROVED** [review]

**Comment by mshima** [comment]
IMO yes.

Worth noting:
- Gradle will match maven behavior and use a local version of node/npm.
It will fail at apple silicon due to https://github.com/node-gradle/gradle-node-plugin/issues/154.
Sadly the user will have to disable npmInstall.
- I couldn't implement .npmw wrapper for gradle because gradle plugin creates a versioned path to npm binary.

cc @atomfrede

**Comment by atomfrede** [comment]
Good to know. Nevertheless let's merge it.

**Comment by mshima** [comment]
The failures seems related to https://github.com/npm/cli/issues/2715.

**Comment by atomfrede** [comment]
So related to https://github.com/jhipster/generator-jhipster/issues/14934

**Pull request merged**
