### PR TITLE
CI: remove entities related to TestPager

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Following https://github.com/jhipster/generator-jhipster/pull/10760 by @murdos 

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
Travis checks seem to regulary fail...

**Comment by MathieuAA** [comment]
What about the `11-generate-entities.sh` file handling entities for such relationships?

**Comment by pascalgrimaud** [comment]
@MathieuAA : no it's not a random failure. The error is:

```
Can't add invalid relationship. Error: In the Many-to-Many relationship from TestCustomTableName to User, only bidirectionality is supported for a Many-to-Many relationship.
```

It is related to `jhipster info` which uses export-jdl

**Comment by MathieuAA** [comment]
Ah! I can't get my head around different CIs checking different things...

**Comment by MathieuAA** [comment]
I'm not sure about how to handle this case:
  - keep the error throwing thing, and change the JDL file
  - or remove the thrown error, add a warning and make it bidirectional...

**Comment by MathieuAA** [comment]
@pascalgrimaud I have the fix, gonna test it out

**Comment by MathieuAA** [comment]
Okay, this is a tough one.
I've handled the "export path" (what should fix this issue). However, when reimporting the exported JDL, the same thing will happen:

> I'm not sure about how to handle this case:
    - keep the error throwing thing, and change the JDL file
    - or remove the thrown error, add a warning and make it bidirectional...

**Comment by pascalgrimaud** [comment]
@MathieuAA : this PR is just following another one https://github.com/jhipster/generator-jhipster/pull/10760 because the entity TestPager was removed, because of duplicated with another one

**Comment by pascalgrimaud** [comment]
Merging this, as I got 2 approuvements

**Pull request merged**
