### PR TITLE
new line after (and only) methods declaration in mappers

### PR DESCRIPTION
**Pull request by ctamisier**
Currently a generated mapper looks like this:

```
    @Mapping(source = "organismeDeFormation.id", target = "organismeDeFormationId")
    @Mapping(source = "organismeDeFormation.nom", target = "organismeDeFormationNom")

    @Mapping(source = "etablissement.id", target = "etablissementId")
    @Mapping(source = "etablissement.nom", target = "etablissementNom")
    FormationDTO toDto(Formation formation);

    @Mapping(source = "organismeDeFormationId", target = "organismeDeFormation")

    @Mapping(source = "etablissementId", target = "etablissement")
    Formation toEntity(FormationDTO formationDTO);
    default Formation fromId(Long id) {
        if (id == null) {
            return null;
        }
        Formation formation = new Formation();
        formation.setId(id);
        return formation;
    }
```
This PR is to make it looks like this:

```
    @Mapping(source = "organismeDeFormation.id", target = "organismeDeFormationId")
    @Mapping(source = "organismeDeFormation.nom", target = "organismeDeFormationNom")
    @Mapping(source = "etablissement.id", target = "etablissementId")
    @Mapping(source = "etablissement.nom", target = "etablissementNom")
    FormationDTO toDto(Formation formation); 

    @Mapping(source = "organismeDeFormationId", target = "organismeDeFormation")
    @Mapping(source = "etablissementId", target = "etablissement")
    Formation toEntity(FormationDTO formationDTO); 
    
    default Formation fromId(Long id) {
        if (id == null) {
            return null;
        }
        Formation formation = new Formation();
        formation.setId(id);
        return formation;
    }
```

### CODE REVIEW

**Comment by ctamisier** [comment]
If I am not wrong https://github.com/jhipster/generator-jhipster/commit/e5a537b22e9249ddbe42b557a2d6ab3efffe2499 and https://github.com/jhipster/generator-jhipster/commit/feb9056e87b27a33d7488f5e2af37a20a3cdc09b fix this formatting so we can close this PR right ?

**Comment by ctamisier** [comment]
done

**Comment by jdubois** [comment]
Oh sorry I didn't see this - I have issues on this file for our OIDC support, so I cleaned it up, but I should have merged your PR instead

**Comment by ctamisier** [comment]
no problem !

**Pull request closed without merging**
