### PR TITLE
Entity indexing shall happen in separate transaction

### LINKED ISSUE #17488: Implement new interfaces for ElasticSearch Entity indexing
##### **Overview of the feature request**

Current logic for entity indexing:

```java
    public RecordingDTO save(RecordingDTO recordingDTO) {
        log.debug("Request to save Recording : {}", recordingDTO);
        Recording recording = recordingMapper.toEntity(recordingDTO);
        recording = recordingRepository.save(recording);
        RecordingDTO result = recordingMapper.toDto(recording);
        recordingSearchRepository.save(recording);
        return result;
    }
```
Has a major flaw - it does not index  that is actually contained in database.   DTO coming from  REST layer may mot contain all the relations (which are managed by other entity)  and thus indexing result will not reflect actual data stored in database.

To overcome this situation,   indexing shall be performed over entity loaded from database in separate  transaction with sufficient isolation level to get real data contained in database.   This may ( shall ) be done asynchronously,   because it involves external rest call to elasticsearch service running in a separate JVM anyway. 

I propose adding 2 methods:

```java
    @Transactional(propagation =  Propagation.REQUIRES_NEW, readOnly = true, isolation = Isolation.READ_COMMITTED)
    public Recording indexRecording(Recording recording) {
        recordingRepository.findOneWithEagerRelationships(recording.getId()).ifPresent(recordingSearchRepository::save);
        return recording;
    }

    /**
     * asynch wrapper
     * @param toBeIndexed
     */
    @Async
    @Transactional(propagation =  Propagation.REQUIRES_NEW, readOnly = true, isolation = Isolation.READ_COMMITTED)
    public void asyncIndexRecording(Recording toBeIndexed) {
        indexRecording(toBeIndexed);
    }
```

And invoke them instead of calling search repository directly

     
##### **Motivation for or Use Case**

I would like index data  to be in synch with actual  data contained in database so search would be accurate. 

##### **Related issues or PR**

did not found

- [x ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ko5tik**
Fix #17488

This is updated version  of:

https://github.com/jhipster/generator-jhipster/pull/17561

I recreated branch so there are less rebase commits

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

This pull request improves querying and indexing of entities - https://github.com/jhipster/generator-jhipster/issues/17488

Additional query methods - pass not only string but also real query objects
Reindexing shall happen in separate transaction with proper isolation - because reindexing incoming DTO will not always get all the data of the object. ( Relations managed on the other side are not transferred from frontend , and there could be changes in related objects )

### CODE REVIEW

**Comment by mraible** [comment]
@ko5tik Can you please rebase. There's a conflict.

**Comment by ko5tik** [comment]
working on it
========[] Lines game back in Appstore - check it out! []===============
https://play.google.com/store/apps/details?id=de.pribluda.games.android.lines

Blog:  https://www.pribluda.de

**Comment by ko5tik** [comment]
Rebased  and pushed , all tests still green.   Generated sources look OK\

**Comment by ko5tik** [comment]
... done
========[] Lines game back in Appstore - check it out! []===============
https://play.google.com/store/apps/details?id=de.pribluda.games.android.lines

Blog:  https://www.pribluda.de

**Comment by mraible** [comment]
Please resolve conflicts.

**Comment by ko5tik** [comment]
....   rebased again
========[] Lines game back in Appstore - check it out! []===============
https://play.google.com/store/apps/details?id=de.pribluda.games.android.lines

Blog:  https://www.pribluda.de

**Comment by mraible** [comment]
@ko5tik Tests are failing and there's a conflict again.

**Comment by ko5tik** [comment]
Well -  it was just 8  or 10 days since  5th rebase..... I will rebase
again tomorrow ( too late now here )
========[] Lines game back in Appstore - check it out! []===============
https://play.google.com/store/apps/details?id=de.pribluda.games.android.lines

Blog:  https://www.pribluda.de

**Comment by Tcharl** [comment]
Turning 385 files changed to green is a challenge! Please insist! this PR is awesome (reviewed 30 files on all, but it's high standard)

**Comment by pascalgrimaud** [comment]
Sorry to tell that, but your rebase is not correct. There can't be 600 commits with 380 files here. It's just impossible.

**Comment by ko5tik** [comment]
Will recreate it again tonight.

========[] Lines game back in Appstore - check it out! []===============
https://play.google.com/store/apps/details?id=de.pribluda.games.android.lines

Blog:  https://www.pribluda.de

**Comment by ko5tik** [comment]
Here we go:

Branch recreated and cherry picked:


https://github.com/jhipster/generator-jhipster/pull/18239
========[] Lines game back in Appstore - check it out! []===============
https://play.google.com/store/apps/details?id=de.pribluda.games.android.lines

Blog:  https://www.pribluda.de

**Comment by DanielFran** [comment]
Superseded by https://github.com/jhipster/generator-jhipster/pull/18239

**Pull request closed without merging**
