### PR TITLE
Mail configuration

### PR DESCRIPTION
**Pull request by pascalgrimaud**
- enable health mail for **monolith** application - related to https://github.com/jhipster/generator-jhipster/issues/3579
- add empty properties for smtp configuration

### CODE REVIEW

**Comment by jdubois** [comment]
I'm not sure about having the healthcheck option different with monoliths and microservices/gateways -> I'd rather have something consistent here

**Comment by pascalgrimaud** [comment]
Ok let's be consistent about `health.mail.enabled: false`
Do I keep the empty configuration for smtp configuration ?

**Comment by jdubois** [comment]
Good question.
I wanted to have it, but now I remember that we always use each technology's "normal" configuration, and then point to each technology's documentation. So basically, this should be a Spring Boot issue, not a JHipster issue.
If we do this for each configuration, then we will end up with the full default Spring Boot configuration file, which is of course the opposite to what Spring Boot is trying to achieve (convention over configuration). So I know many people struggle with this, but I don't think this is a good idea. What do you think?

**Comment by pascalgrimaud** [comment]
You're right, it's well documented in our site and in official spring boot docs, so no need to put configuration in comments.

So this PR is to fix the indentation and change the `application-dev.yml` to add `port: 25`, to be consistent with `application-prod.yml`
=> I can start easily a SMTP server with `docker run -d -p 1080:80 -p 25:25 -t djfarrelly/maildev`

**Pull request merged**
