### PR TITLE
Allow to use TLS in prod mode

### PR DESCRIPTION
**Pull request by jdubois**
-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
@atomfrede it's not the default, it's just that we can now do "mvn -Pprod,tls", and before that wasn't possible.
(and you could do "mvn -Pdev,tls", so that wasn't even consistent)

Can you have a look for Gradle? I'm sorry, I really suck so much at Gradle

**Comment by atomfrede** [comment]
Sure. I already looked at the source, I think we need to add it there too.

**Comment by jdubois** [comment]
Merging as the checks are green and that shouldn't cause any issue.
@atomfrede can you have a look at the Gradle equivalent?

**Comment by atomfrede** [comment]
> Merging as the checks are green and that shouldn't cause any issue.
> @atomfrede can you have a look at the Gradle equivalent?

Yes. No big thing to add.

**Pull request merged**
