### PR TITLE
Add sort function to user management page

### PR DESCRIPTION
**Pull request by sgrillon14**

### CODE REVIEW

**Comment by deepu105** [comment]
Could you merge into a single PR instead of opening two PR for same stuff?

**Comment by deepu105** [comment]
Im talking about #3505

**Comment by pascalgrimaud** [comment]
And if I remember well, Cassandra doesnt have sort/pagination options => so need to confirm this PR won't break user management page with Cassandra

**Comment by sgrillon14** [comment]
I offered the same functionality on user management as the entities (same code for sort). If there is a problem here with Cassandra there will also on entities.

**Comment by pascalgrimaud** [comment]
Just checked right now.
On a Cassandra project, when using "yo jhipster:entity foo", there is no option about sort/pagination, so there is no sort/pagination on entities

What I wanted to say, was "Cassandra option" need to be tested also

**Comment by deepu105** [comment]
It might be a bug on entities as well

**Pull request closed without merging**
