### PR TITLE
Update open-api version

### LINKED ISSUE #14287: Update Open-api generator version to 5.x
##### **Overview of the feature request**

Migrate from 4.3.1 to 5.0.1 (or even 5.1.0 expected in April)

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by Falydoor**
Fix #14287

This PR update the openapi-cli to the latest version (not sure if people use the `openapi-client` generator).

The command was renamed to `openapi-generator-cli` instead of `openapi-generator` with the new version.

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
This will generate code with openapi v3 specs?

**Comment by Falydoor** [comment]
> This will generate code with openapi v3 specs?

Correct, I was able to generate code using this openapi version `"openapi":"3.0.1"`.

**Comment by Falydoor** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/73467

**Comment by pascalgrimaud** [comment]
@Falydoor : approved

**Pull request merged**
