### PR TITLE
Use autoconfigured embedded mongodb

### PR DESCRIPTION
**Pull request by cbornet**
Spring boot 1.3 now autoconfigures the embedded mongodb which leads to a conflict with the current MongoConfiguration.
This PR removes MongoConfiguration and lets Spring Boot do the job.
The mongo version used will be 2.6.10 (111MB will be downloaded first time) unless spring.mongodb.embedded.version is set in application.yml

See #2140

### CODE REVIEW

**Comment by deepu105** [comment]
@cbornet  You are working  a lot on JH, would you like to join the dev
board?

**Comment by jdubois** [comment]
-> looks good, and also fixes #1986 !

I'm merging this, and yes @cbornet we need to talk about adding you to the team!

**Comment by cbornet** [comment]
@jdubois @deepu105 I would gladly join the board. Please vote for me :smile: ! Yes, we can !

**Comment by deepu105** [comment]
@cbornet send me your mail id and real name ill start a vote

**Pull request merged**
