### PR TITLE
fix cypress e2e ci packaging error on copy

### LINKED ISSUE #15146: Cypress e2e CI packaging error on copy
##### **Overview of the issue**

The script for packaging and preparing for e2e is the following (`package.json`):

```json
"postci:e2e:package": "cp build/libs/*SNAPSHOT.$npm_package_config_packaging e2e.$npm_package_config_packaging"
```

If the version is something other than `*SNAPSHOT` this step is failing with `cp: cannot stat 'build/libs/*SNAPSHOT.jar': No such file or directory`.

##### **Motivation for or Use Case**

Be able to run e2e in CI for other versions than `*SNAPSHOT`.

##### **Reproduce the error**

Change the version and run e2e in CI.

##### **Suggest a Fix**

If the `SNAPSHOT` part is not necessary, I could change it to

```
cp build/libs/*.$npm_package_config_packaging e2e.$npm_package_config_packaging
```

and create a PR.

##### **JHipster Version(s)**

7.0.1

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by nomuna**
Fix #15146

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@atomfrede is there an easy way to generate the package with e2e.jar name instead of version.jar like maven?
This copy workaround can conflict if there is more than 1 package.

**Comment by atomfrede** [comment]
Let me check. Don't know for sure right now.

**Comment by atomfrede** [comment]
The property in gradle is `bootJar.archiveFileName`, but I didn't find a way to provide it via cli parameter/flag.

**Comment by mshima** [comment]
Thanks, I couldn't find either back when I did maven change.

Maybe we could delegate to gradle to copy current version.
`./gradlew copy_e2e_jar` to copy `archiveFileName` to e2e.jar.

Seems a bit more complicated.
Merging this one for now.

**Comment by atomfrede** [comment]
:heavy_check_mark: Have already an idea how to do it via cli parameter.

**Pull request merged**
