### PR TITLE
initial OpenShift jHipster generator

### PR DESCRIPTION
**Pull request by srinivasa-vasu**
initial OpenShift jHipster generator

generator templates for the new OpenShift 3.x release.

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois @srinivasa-vasu is a friend of mine and works for Redhat so I guess this can be our official openshift support

**Comment by jdubois** [comment]
Yes that would be awesome! I'll review this when the Travis build is green

**Comment by deepu105** [comment]
@srinivasa-vasu I think something went wrong when you merged master into your branch as the commits from master are appearing here as well. may be you should rebase your branch against master

**Comment by srinivasa-vasu** [comment]
@deepu105 Yeah, I'll chk that out.

**Comment by srinivasa-vasu** [comment]
I think something has gone wrong. Will close this and give a new request.

**Pull request closed without merging**
