### PR TITLE
Replaced pager deprecated option by pagination

### PR DESCRIPTION
**Pull request by MathieuAA**
cc @pascalgrimaud

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
the failures doesn't come from this PR, so I'm merging this

**Comment by SudharakaP** [comment]
@pascalgrimaud @MathieuAA : I might be wrong, but I have a feeling that there's failures happening on the Daily Builds side due to this PR. Correct me if I am wrong. :thinking: 

Example: https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=7316

**Comment by pascalgrimaud** [comment]
@SudharakaP : yes, you're right, all daily builds failed

This PR should fix the 1st issue, related to `pager` / `pagination`
But there is another 2nd issue, related to `npm test`: https://github.com/jhipster/generator-jhipster/issues/10758

**Comment by SudharakaP** [comment]
@pascalgrimaud : Wonderful. Thanks for the info :smile:

**Pull request merged**
