### PR TITLE
Romanian Language Pack

### LINKED ISSUE #1583: Romanian I18n
Adding romanian translation (shortly).

### PR DESCRIPTION
**Pull request by mihaisimi**
Added romanian language.

Fix #1583

### CODE REVIEW

**Comment by mihaisimi** [comment]
Please review and merge.

Regards,
Mihai

**Comment by jdubois** [comment]
Looks good to me, thanks!!!!

**Comment by jdubois** [comment]
Argh... There is still an issue: after installing the language, when you click on the menu from another language, you get "langage.ro" instead of the language name

**Comment by jdubois** [comment]
Sorry, this is my fault
Wrong configuration, everything is good!!!

**Comment by mihaisimi** [comment]
Thank you & team for the awesome job you guys do on the framework. I just started using it and I like it a lot. If there is anything else I can do to help I would be glad to.

**Pull request merged**
