### PR TITLE
Add Workflow to Cleanup Labels [skip ci]

### LINKED ISSUE #11283: Create New Workflow for Label Cleanup
##### **Overview of the feature request**

As per the following discussion, I thought it would be nice to have a workflow that cleans up labels in our issues. So for example once a issue is closed labels like `triage`, `undefined`, `needs-reproduction` and `waiting for information` needs to be automatically removed. 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jhipster-dev/xfrODe_g14U

##### **Motivation for or Use Case**

Cleanup old labels of closed issues. 😄 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by SudharakaP**
Fixes #11283

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mshima** [comment]
I think `area: triage` and `theme: undefined` should be kept.
`status: work in progress` should be removed.

**Comment by pascalgrimaud** [comment]
@SudharakaP : can you have a look at this ticket plz https://github.com/jhipster/generator-jhipster/issues/10198 ?

Not sure it's a good idea to remove 'lack of interest', as it can be interesting to search these kind of ticket one day. Then, same for some other status like major
What do you think ?

**Comment by mshima** [comment]
> @SudharakaP : can you have a look at this ticket plz #10198 ?
> 
> Not sure it's a good idea to remove 'lack of interest', as it can be interesting to search these kind of ticket one day. Then, same for some other status like major
> What do you think ?

@pascalgrimaud I think it should be renamed to `resolution: lack of interest` or `closed: lack of interest`
See https://github.com/jhipster/generator-jhipster/issues/11283#issuecomment-584852687

**Comment by pascalgrimaud** [comment]
good idea ! could you do it plz ?

**Comment by mshima** [comment]
@pascalgrimaud sure.

**Comment by mshima** [comment]
@pascalgrimaud done.

**Comment by pascalgrimaud** [comment]
thanks a lot :) I'm cleaning ticket...

**Comment by mshima** [comment]
@pascalgrimaud I think we should rename:
`area: needs-reproduction` => `status: needs-reproduction`
`area: waiting for information` => `status: waiting for information`

**Comment by pascalgrimaud** [comment]
we could, but what would be the area of new ticket ? `area: triage` with `status: needs-reproduction` ?
Initially, I thought about this workflow, for area:
- triage -> needs-information -> needs-reproduction -> bug
- triage -> enhancement
- triage -> feature

With your change, it would be directly:
- triage -> bug ?

**Comment by SudharakaP** [comment]
Here's my suggestion for labeling. I believe we have a bit too many labels and so how about a cleanup. :smile: 

1) We keep; `area: bug`, `area: documentation`, `area: duplicate`, `area: enhancement`, `area: feature request`, `area: needs-reproduction`, `area: question`, `area: rfc`, `area: waiting for information`  `resolution: lack of interest`, `resolution: should go to module`, `status: good first issue`, `status: help wanted` and `status: needs-discussion`

2) We rename; `area: triage` to just `triage` and remove `theme: undefined` as it's implied when something is in `triage` status there's no theme. 

3) We remove `area: invalid`, `bounty: approved`, `bounty: request`, `changes: major`, `changes: minor`, `pr: needs-change`, `pr: needs-manual-testing`, `pr: needs-review`, `pr: needs-unit-tests`, `pr: bug-fix`, `pr: reviewing`, `resolution: will-do-later`, `status: pr done`, `status: will-be-closed-for-lack-of-info`, `status: work in progress`. 

Most of these labels, I feel aren't used much and reflect intermediary states which when the issue is done needs to be cleaned anyways and could be communicated within the PR comments.

4) We remove labels which reflect versions such as `v6` and `v7` and instead use [milestones](https://help.github.com/en/github/managing-your-work-on-github/about-milestones)

5) The theme labels can stay as they are since they are useful to know what kind of changes are discusses/done. 

Feel free to disagree or suggest any other ideas :smile:

**Comment by SudharakaP** [comment]
> @SudharakaP : can you have a look at this ticket plz #10198 ?
> 
> Not sure it's a good idea to remove 'lack of interest', as it can be interesting to search these kind of ticket one day. Then, same for some other status like major
> What do you think ?

@pascalgrimaud : So did we rename `status: lack of interest` to `resolution: lack of interest` ? Because I see that looking at some issues, such as the one you mentioned that `resolution: lack of interest` was removed. But my PR is not supposed to remove that. :thinking:

**Comment by mshima** [comment]
> @pascalgrimaud : So did we rename `status: lack of interest` to `resolution: lack of interest` ? 

I did.

> 2\. We rename; `area: triage` to just `triage`

Feels strange bug/enhancement/feature with same prefix as need-reproduction/needs-information.

> and remove `theme: undefined` as it's implied when something is in `triage` status there's no theme.

`theme: undefined` is important to keep.
Like this PR theme is something like management, since there is not `theme: management` the fallback is `theme: undefined`

**Comment by SudharakaP** [comment]
@mshima : Thanks for the confirmation about the label renaming. Yes we could keep `theme: undefined`. My main suggestion is to remove the labels we use rarely use, just to make it more cleaner and easier to decide which labels to use. 😄

**Pull request merged**
