### PR TITLE
Use binary options for entity

### PR DESCRIPTION
**Pull request by nonomoho**
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by MathieuAA — APPROVED** [review]

**Comment by deepu105** [comment]
Please claim the bounty once merged

**Comment by MathieuAA** [comment]
@nonomoho @ntorionbearstudio Hello there! You can see the three last commits that add some tests, and enable the options inside the applications.

**Comment by pascalgrimaud** [comment]
Increasing the bounty, so it will be easier to share, as it was a team work during all the day at JHipster Code
Good job all !

**Comment by pascalgrimaud** [comment]
@nonomoho @ntorionbearstudio @MathieuAA : don't hesitate to claim your bounty, for this work, well deserved -> each 100

**Comment by nonomoho** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/25240
Thanks!

**Comment by pascalgrimaud** [comment]
@nonomoho : approved

**Comment by ntorionbearstudio** [comment]
Bounty claimed : https://opencollective.com/generator-jhipster/expenses/25453
Thanks a lot !

**Pull request merged**
