### PR TITLE
Re introduced Docker image cache improvments from #6744

### PR DESCRIPTION
**Pull request by smasset**
These improvements were lost when merging #7722.

@gclayburg, @PierreBesson was this intentional. If not, please refer to #6744 for explanation.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks @smasset 
I'm merging this, but not sure it is used now. Do you see this PR https://github.com/jhipster/generator-jhipster/pull/8409 ?

**Comment by PierreBesson** [comment]
I don't understand. Now that we have migrated to jib, we should not have a Dockerfile anymore, the file should be removed.

**Comment by pascalgrimaud** [comment]
The real PR is https://github.com/jhipster/generator-jhipster/pull/8352

@PierreBesson : see @danielpetisme's question, we didn't answer, so that's why the file is still here:
> Should I remove the existing Dockerfile?
Same as above, Devs are comfortable with it so removing the file right now can be a bit too agressive. Plus I didn't check yet if it's not used somewhere else.

**Comment by smasset** [comment]
Wow, that was quick. Thanks.
@pascalgrimaud, I'll check the mentioned PR.

**Pull request merged**
