### PR TITLE
chore: Bump keycloak to 12.x

### LINKED ISSUE #14231: Update Keycloak to 12.0.x
##### **Overview of the feature request**

See https://www.keycloak.org/2021/03/keycloak-1204-released

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vishal423**
Closes #14231 
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Following this, all OAuth2 daily builds failed with Protractor 
Can you have a look plz @vishal423 ?

**Comment by vishal423** [comment]
@pascalgrimaud, I will try to analyze it later today. Today seems like a never-ending long hectic troubleshooting day 😞

**Comment by vishal423** [comment]
Bounty claimed - https://opencollective.com/generator-jhipster/expenses/36511

**Comment by pascalgrimaud** [comment]
@vishal423 : approved

**Pull request merged**
