### PR TITLE
add entity field type, validation and option tests to travic ci testing

### LINKED ISSUE #2830: Test all entity field types and validation combinations in the Travis CI builds
Today the Travis CI tests only tests generating fields with almost no validation. [EDIT edited this to be true]

To make our CI testing more complete we should test to generate all our field types.
I suggest we generate an Entity containing all our field types with each validation rule, e.g.
```
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "stringField",
            "fieldType": "String"
        },
        {
            "fieldId": 2,
            "fieldName": "stringRequiredField",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 3,
            "fieldName": "stringMinlengthField",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength"
            ],
            "fieldValidateRulesMinlength": 0
        },
        {
            "fieldId": 4,
            "fieldName": "stringMaxlengthField",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldId": 5,
            "fieldName": "stringPatternField",
            "fieldType": "String",
            "fieldValidateRules": [
                "pattern"
            ],
            "fieldValidateRulesPattern": "^[a-zA-Z0-9]*$",
            "fieldValidateRulesPatternJava": "^[a-zA-Z0-9]*$"
        },,
        {
            "fieldId": 6,
            "fieldName": "integerField",
            "fieldType": "Integer"
        },
        {
            "fieldId": 7,
            "fieldName": "integerRequiredField",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 8,
            "fieldName": "integerMinField",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldId": 9,
            "fieldName": "integerMaxField",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        }
        ... other field types and validations
```

Further on this entity could be tested with different entity options e.g. `dto`, `service` and `pagination`. And of course the entity and fields needs to different for the different databases we support.

@jhipster/developers 
This would mostly help us catch compile errors when changing java related entity code. This could be done for relations ass well (which may be more important actually since the code gets more complex there i think).
What do you think of this?
One drawback is that it will slow down the CI build a bit more and maybe the maintenance cost.

### PR DESCRIPTION
**Pull request by andidev**
fix #2830

### CODE REVIEW

**Comment by andidev** [comment]
@jdubois 
Enum tests for Cassandra seems to fail. Do you know if should work with enums and cassandra?

According to jhipster uml it should, see http://jhipster.github.io/jhipster-uml/#annexes

**Comment by jdubois** [comment]
I'm not surprised if they fail: I did the Cassandra code before the enum existed, and I don't know how they would be mapped with Cassandra.
As both options are not widely used, the best solution for me is to remove enum support for Cassandra.

**Comment by jdubois** [comment]
In fact the option is not available through the question/answers menu, so as far as I'm concerned there is no issue. Of course, if you hack the JSON config file and put something else, strange things can happen!

**Comment by andidev** [comment]
Yes that is true! I will remove the tests for cassandra then and create a PR to the docs.

**Comment by andidev** [comment]
Test fails cause of a bug was detected. After that bug is fixed is it possible to rerun the travic ci test for this PR somehow?

**Comment by pascalgrimaud** [comment]
When Travis build failed because timeout -> close/reopen PR to rerun the build

When you want to rerun because there are new modifications in master, your PR won't contain the modification in master, unless you update your PR -> so it will rerun the CI

**Comment by deepu105** [comment]
Rebasing should do the trick

**Pull request merged**
