### PR TITLE
JDL: fixed user management flag passing

### LINKED ISSUE #12366: import-jdl does not respect skipUserManagement cli params or jdl settings
##### **Overview of the issue**

The command stacktrace states that skipUserManagement can be used to enable relationships between a custom defined `User` entity and `Company` entity, however 
JHipster jdl/import-jdl does not accept any form of the setting: neither the command line argument `--skip-user-management`, nor the alternative specifying `// skip-user-management` as first line of JDL file work.

According [JHipster documentation](https://www.jhipster.tech/creating-an-app/#3) `--skip-user-management` should be able to disable automatic generation of `User` and `Authority` entities so that those entities can be used in normal entity relationships.  

```
INFO! Using JHipster version installed globally
INFO! Executing import-jdl test.jdl
INFO! The JDL is being parsed.
warn: In the One-to-Many relationship from Company to User, only bidirectionality is supported for a One-to-Many association. The other side will be automatically added.
Error: Relationships from the User entity is not supported in the declaration between 'User' and 'Company'. You can have this by using the 'skipUserManagement' option.
Error while parsing applications and entities from the JDL Error: Relationships from the User entity is not supported in the declaration between 'User' and 'Company'. You can have this by using the 'skipUserManagement' option.
Error: Relationships from the User entity is not supported in the declaration between 'User' and 'Company'. You can have this by using the 'skipUserManagement' option.
    at checkForForbiddenUseOfUserAsSource (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/relationship_validator.js:89:11)
    at checkForInvalidUseOfTheUserEntity (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/relationship_validator.js:83:3)
    at RelationshipValidator.validate (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/relationship_validator.js:37:5)
    at /usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/business_error_checker.js:158:17
    at /usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_object.js:202:7
    at /usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_relationships.js:90:7
    at Array.forEach (<anonymous>)
    at JDLRelationships.forEach (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_relationships.js:89:20)
    at JDLObject.forEachRelationship (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_object.js:201:24)
    at BusinessErrorChecker.checkForRelationshipErrors (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/business_error_checker.js:157:20)
Error during import-jdl: Relationships from the User entity is not supported in the declaration between 'User' and 'Company'. You can have this by using the 'skipUserManagement' option.
Error: Relationships from the User entity is not supported in the declaration between 'User' and 'Company'. You can have this by using the 'skipUserManagement' option.
    at checkForForbiddenUseOfUserAsSource (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/relationship_validator.js:89:11)
    at checkForInvalidUseOfTheUserEntity (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/relationship_validator.js:83:3)
    at RelationshipValidator.validate (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/relationship_validator.js:37:5)
    at /usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/business_error_checker.js:158:17
    at /usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_object.js:202:7
    at /usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_relationships.js:90:7
    at Array.forEach (<anonymous>)
    at JDLRelationships.forEach (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_relationships.js:89:20)
    at JDLObject.forEachRelationship (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/core/jdl_object.js:201:24)
    at BusinessErrorChecker.checkForRelationshipErrors (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/node_modules/jhipster-core/lib/validators/business_error_checker.js:157:20)
Error: Error during import-jdl: Relationships from the User entity is not supported in the declaration between 'User' and 'Company'. You can have this by using the 'skipUserManagement' option.
    at module.exports (/usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/cli/import-jdl.js:428:31)
    at /usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/cli/jdl.js:93:51
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
---
I attempted to turn on debug logging level

`DEBUG=generator-jhipster:* LOG_LEVEL=debug node --inspect /usr/local/Cellar/jhipster/6.10.1/libexec/lib/node_modules/generator-jhipster/cli/cli.js import-jdl test.jdl --skip-user-management --ignore-application`

The command runs, but it does not change logging level... if someone could tell me the correct syntax, I would be happy to investigate it further to see if I can determine where the breakdown occurs.

##### **Motivation for or Use Case**

For the project I'm working on, I use OIDC/OAuth2 to handle user authentication and identity management, we still need a User representation within our database for data-ownership.   

We need to be able to update entities and regenerate classes as the project evolves, currently this bug blocks us from being able to do that.

##### **Reproduce the error**

`jhipster jdl test.jdl --skip-user-management`
test.jdl is attached in JHipster configuration section

##### **Related issues**

Issue was first opened against JHipster core jhipster/jhipster-core#476, but it seems more suitable to be here as it may not be a problem with JHipster only rather how the classes are generated.

##### **Suggest a Fix**

Skip User Management doesn't work through import jdl at all...  Configuration is not being respected by lower level classes in generator-jhipster.

##### **JHipster Version(s)**

6.10.1

##### **JHipster configuration**

```
// skip-user-management

// application {
//     config {
//         packageName com.test.project.entities
//     }
//     entities *
// }

DEFAULT_MIN_LENGTH = 2
DEFAULT_MAX_LENGTH = 50

entity Company {
    name String required unique minlength(DEFAULT_MIN_LENGTH)
    abbreviation String required unique 
    config String required
    entities String required
    logo String
}

entity User { 
    name String required
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/) 
}

relationship OneToMany {
    Company to User{company(name)}
}

relationship ManyToOne {
    User to Company {user(name)}
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

OSX 10.15

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by MathieuAA**
Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Fixes #12366
Closes #12439

### CODE REVIEW

**Comment by MathieuAA** [comment]
I had to re-run a failing build to have all this PR's check pass :( I'll create an issue if this happens again.

**Review by mshima — COMMENTED** [review]
I missed the test that allows relationship with User when skipUserManagement is true.
```
before(() => {
                         const sourceEntity = new JDLEntity({
                             name: 'Source',
                         });
                         const destinationEntity = new JDLEntity({
                             name: 'User',
                         });
                         const relationship = new JDLRelationship({
                             from: sourceEntity.name,
                             to: 'User',
                             type: RelationshipTypes.ONE_TO_ONE,
                             injectedFieldInFrom: 'other',
                         });
                         const jdlObject = new JDLObject();
                         const application = createJDLApplication({
                             applicationType: ApplicationTypes.MONOLITH,
                             databaseType: DatabaseTypes.SQL,
                             skipUserManagement: true,
                         });
                         jdlObject.addEntity(sourceEntity);
                         jdlObject.addEntity(destinationEntity);
                         jdlObject.addRelationship(relationship);
                         application.addEntityName(sourceEntity);
                         application.addEntityName(destinationEntity);
                         jdlObject.addApplication(application);
                         checker = createValidator(jdlObject);
                     });
```

Probably we should add `Source -> User` and `User -> Source`.

**Comment by MathieuAA** [comment]
Thank you @mshima, I'll complete it tomorrow.

**Review by mshima — APPROVED** [review]
LGTM.

**Pull request merged**
