### PR TITLE
Upgrade jhipster-registry to v6.5.0

### PR DESCRIPTION
**Pull request by pascalgrimaud**
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
I've generated a couple of microservice architectures this morning to test the main branch. It seems I always have to start JHipster Registry twice to get it to stay up. Any idea why this is happening?

**Comment by pascalgrimaud** [comment]
@mraible : is it with JWT or OAuth2 ? I suppose OAuth2 : is it with Keycloak or Okta ?

**Comment by mraible** [comment]
It's with OAuth 2.0 and Keycloak.

**Comment by pascalgrimaud** [comment]
it happens to me if I start registry at the same time than Keycloak, few weeks ago:
- start keycloak
- wait at least 20sec
- start registry

Tell me if it works for you ?

**Comment by mraible** [comment]
That makes sense. Yes, if I start Keycloak and wait before starting the JHipster Registry, it works. Thanks, @pascalgrimaud!

**Comment by pascalgrimaud** [comment]
@mraible : in fact, in an older version of JHipster, it would be possible, as the Registry waited Keycloak to be up, instead of failing immediatly. So something has changed with Spring Boot imo... or it can be a missing configuration

**Comment by mraible** [comment]
In my experience, startup has always failed with Spring Boot + OAuth when the identity provider is not available. It might keep retrying when using WebFlux. I'm not sure.

**Pull request merged**
