### PR TITLE
Load fake blob data correctly

### LINKED ISSUE #9660: Incorrect fake data is being generated for blob
##### **Overview of the issue**

When liquibase load image data, it fails due to type mismatch.

```
2019-05-04 14:48:30.932 ERROR 17765 --- [datatype-task-1] liquibase.changelog.ChangeSet            : Change Set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster failed.  Error: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.
2019-05-04 14:48:30.974 ERROR 17765 --- [datatype-task-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Migration failed for change set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.

liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:100)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:80)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: liquibase.exception.DatabaseException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.
	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:86)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:115)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 12 common frames omitted
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.entity3(id, my_image, my_image_content_type) VALUES(1, '486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572', 'image/png') was aborted: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2184)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:481)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:840)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1538)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at liquibase.statement.BatchDmlExecutablePreparedStatement.executePreparedStatement(BatchDmlExecutablePreparedStatement.java:65)
	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:84)
	... 16 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: column "my_image" is of type bytea but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 76
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	... 23 common frames omitted

```
When I change column data type from

`            <column name="my_image" type="string"/>
`
to 
`            <column name="my_image" type="blob"/>
`, 
it expects some local file to be loaded.

```
2019-05-04 14:55:00.465 ERROR 18061 --- [datatype-task-1] liquibase.changelog.ChangeSet            : Change Set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster failed.  Error: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist
2019-05-04 14:55:00.515 ERROR 18061 --- [datatype-task-1] i.g.j.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: Migration failed for change set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist

liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20190504073238_added_entity_Entity3.xml::20190504073238-1-data::jhipster:
     Reason: liquibase.exception.DatabaseException: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:100)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:80)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: liquibase.exception.DatabaseException: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist
	at liquibase.statement.ExecutablePreparedStatementBase.applyColumnParameter(ExecutablePreparedStatementBase.java:184)
	at liquibase.statement.ExecutablePreparedStatementBase.attachParams(ExecutablePreparedStatementBase.java:111)
	at liquibase.statement.BatchDmlExecutablePreparedStatement.attachParams(BatchDmlExecutablePreparedStatement.java:51)
	at liquibase.statement.ExecutablePreparedStatementBase.execute(ExecutablePreparedStatementBase.java:82)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:115)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 12 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [config/liquibase/changelog/486f6d65204c6f616e204163636f756e74205461626c6520436f6d7075746572] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:195)
	at liquibase.integration.spring.SpringLiquibase$SpringResourceOpener.getResourcesAsStream(SpringLiquibase.java:599)
	at liquibase.statement.ExecutablePreparedStatementBase.getResourceAsStream(ExecutablePreparedStatementBase.java:286)
	at liquibase.statement.ExecutablePreparedStatementBase.toBinaryStream(ExecutablePreparedStatementBase.java:206)
	at liquibase.statement.ExecutablePreparedStatementBase.applyColumnParameter(ExecutablePreparedStatementBase.java:177)
	... 19 common frames omitted

```

##### **Motivation for or Use Case**

Fake data should be generated and loaded correctly.

##### **Reproduce the error**

1. Generate an app
2. Generate an entity with a blog->image field
3. Start the app

~~I havn't tried other sub types which are under blog (during question) but guess it will be similar situation.~~

##### **Related issues**

#9654 

##### **Suggest a Fix**

- 

##### **JHipster Version(s)**

```
datatype@0.0.0 /Users/sierra/github/temp/datatype
└── generator-jhipster@6.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "monolith",
    "baseName": "datatype",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Entity1 {
  name String
}
entity Entity2 {
  name String
}
entity Entity3 {
  myImage ImageBlob required
}
relationship ManyToOne {
  Entity2{entity1(name) required} to Entity1
}

dto Entity1, Entity2, Entity3 with mapstruct
service Entity1, Entity2, Entity3 with serviceImpl

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

git version 2.20.1 (Apple Git-117)

node: v10.14.2

npm: 6.7.0

yeoman: 2.0.6

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by pmverma**
Fixes #9660 
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pmverma** [comment]
I run locally with h2, postgres and mysql with dev profile and it is working fine.
Not sure why IT tests failed because of type mismatch.
I will look into it in next week as I am busy this weekend.

**Comment by jdubois** [comment]
@pmverma the error you have is:
```
Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [description] in table [bank_account]; found [clob (Types#CLOB)], but expecting [varchar(2147483647) (Types#LONGVARCHAR)]

**Comment by pmverma** [comment]
Thanks @jdubois .
I don't want to disable `hibernate.hbm2ddl.auto: validate` in test config file, thats why I am adding a workaround for clob to be longvarchar in case of H2 db.

**Comment by pmverma** [comment]
@pascalgrimaud This PR is ready to review and merge.

**Comment by pascalgrimaud** [comment]
thanks a lot @pmverma !

**Comment by pascalgrimaud** [comment]
@pmverma : I'm merging this, as I think it's fixed, but I have this behavior

Capture d’écran de 2019-05-16 17-50-03
Capture d’écran de 2019-05-16 17-50-20

The `textBlob` displays the path instead of the content.

My config:

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

JDL :
```yaml
entity Toto {
  aaa ImageBlob,
  bbb AnyBlob,
  ccc TextBlob
}
service Toto with serviceClass
```

**Comment by pmverma** [comment]
Actually ccc should load content inside file.

**Pull request merged**
