### PR TITLE
Automatically click all try it out buttons

### LINKED ISSUE #12464: Swagger: disable or remove try it button
##### **Overview of the issue**

When using Swagger, the `try it` button is annoying.
It would be nice if we can remove it and use directly the API, instead of clicking `try it` before

##### **Motivation for or Use Case**

Better UX for dev, no need to click try it, then execute...

##### **Reproduce the error**

- generate a JHipster project
- start it
- go to swagger
- play with API

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by nonomoho**
To be able to execute directly Swagger request, I automatically click all try it out buttons. 

Fix #12464

---

Please make sure the below checklist is followed for Pull Requests.

-   [ x ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ x ] Tests are added where necessary
-   [ x ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ x ] Documentation is added/updated where necessary
-   [ x ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Have you tried the plug-in approach?
Seems cleaner https://github.com/swagger-api/swagger-ui/issues/3725.
And if possible, extract into a different file and load instead of hardcoding, could be an ejs template.

**Comment by cbornet** [comment]
Yes the plug-in approach looks the best.

**Comment by nonomoho** [comment]
The plug-in approach only hide the "Try it out" button but not allow to click on "Execute"

**Comment by mshima** [comment]
@nonomoho 
```
const AlwaysEnableTryItOutPlugin = function(system) {
  const OperationContainer = system.getComponents("OperationContainer");
  return {
    components: {
      TryItOutButton: () => null,
      OperationContainer: class CustomOperationContainer extends OperationContainer {
        constructor(...args) {
          super(...args);
          this.state.tryItOutEnabled = true;
        }
      }
    }
  }
}
```

**Review by pascalgrimaud — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
Just tried it and it works so well !
Good by this `try it` button !
Thanks a lot @nonomoho

**Pull request merged**
