### PR TITLE
Update_Entity.java, Style fix

### PR DESCRIPTION
**Pull request by MathieuAA**
Fixed the style for method #equals.

### CODE REVIEW

**Comment by cbornet** [comment]
+1 this is a sonar major :smile:

**Comment by MathieuAA** [comment]
Wow, is Travis sleeping or something?

**Comment by pascalgrimaud** [comment]
Travis time out... Try to close PR then open it

**Comment by MathieuAA** [comment]
Doesn't work. What if I commit something utterly stupid?

**Comment by pascalgrimaud** [comment]
Build success ! just be patient after closing / reopening ;)

**Comment by MathieuAA** [comment]
You were right, thanks. I, however, am not patient at all!

**Comment by deepu105** [comment]
Its takes more than an hour for all travis build to finish

**Comment by cbornet** [comment]
Actually, it is about 23 minutes. I don't know why Travis says its 1h...

**Comment by pascalgrimaud** [comment]
Yes ~23min because 5 builds work in parallel
The total, displayed by travis, is wrong

**Pull request merged**
