### PR TITLE
Fix many-to-many relations handling

### PR DESCRIPTION
**Pull request by gzsombor**
Modify the order of questions according to the suggestions, and fix a couple of typos in many-to-many handling

### CODE REVIEW

**Comment by jdubois** [comment]
I corrected an import issue (with jsonignore, I will push this ASAP), but still many-to-many relationships are failing -> unit tests fails, and the UI can't save a many-to-many entity (I get an "Unknown column" error)

**Comment by gzsombor** [comment]
What kind of relations do you have for testing? I've tried to fix the issues two many-to-many relations between A and B, and it seemed to work.

**Comment by jdubois** [comment]
I have just a many-to-many relationship, and I'm using the default relationship names

**Comment by jdubois** [comment]
The column name is name of the table, this can't be right:

https://github.com/jhipster/generator-jhipster/blob/master/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml#L47

**Comment by gzsombor** [comment]
This is the default column name for hibernate, when nothing else is defined for a join table. 
During I've found one small issue, that the client sends a JSON with upper case field names in many-to-many selections, which I haven't seen yet, because I've always used a lower case field name. I'm going to fix it asap.

**Comment by jdubois** [comment]
yes but shouldn't this be the name of the relationship? That's what it used to be, and now this part is failing.
I guess you don't have the name of the relationship when you do the owner side, and that is the issue.

I'm doing a many-to-many, and the owner side generates the join table -> this used to work, and now the join table is wrong

**Comment by gzsombor** [comment]
I have the followings:

$ cat .jhipster.Bbbb.json 
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "Aaaa",
            "relationshipNameCapitalized": "Aaaa",
            "relationshipFieldName": "aaaa",
            "otherEntityName": "aaaa",
            "relationshipType": "many-to-many",
            "otherEntityNameCapitalized": "Aaaa",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldNameCapitalized": "Name",
            "fieldNameUnderscored": "name"
        }
    ],
    "fieldsContainOwnerManyToMany": true,
    "fieldsContainOneToMany": false,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "changelogDate": "20150203001807"
}
$ cat .jhipster.Cccc.json 
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "Bbbb",
            "relationshipNameCapitalized": "Bbbb",
            "relationshipFieldName": "bbbb",
            "otherEntityName": "bbbb",
            "relationshipType": "many-to-many",
            "otherEntityNameCapitalized": "Bbbb",
            "otherEntityField": "name",
            "ownerSide": true
        },
        {
            "relationshipId": 2,
            "relationshipName": "Aaaa",
            "relationshipNameCapitalized": "Aaaa",
            "relationshipFieldName": "aaaa",
            "otherEntityName": "aaaa",
            "relationshipType": "many-to-many",
            "otherEntityNameCapitalized": "Aaaa",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldNameCapitalized": "Name",
            "fieldNameUnderscored": "name"
        }
    ],
    "fieldsContainOwnerManyToMany": true,
    "fieldsContainOneToMany": false,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "changelogDate": "20150203003325"
}

The Aaaa entity only contains a name field. 
With this configuration, I do see a T_CCCC_AAAA and T_CCCC_BBBB table, with T_CCCC_ID,AAAAS_ID and T_CCCC_ID,BBBBS_ID fields, which is filled by hibernate, properly.
Even the ui, and the generated integration tests are working well - only a small, client side fix is needed

**Comment by jdubois** [comment]
Sorry, but this is still not working for me... Did you try a "mvn clean test", is it working? I have the same problem here and in the UI, a missing column.

I'm having a look at this.

**Comment by jdubois** [comment]
I'm sorry @gzsombor but I just can't understand how it works:

- It makes my unit tests and UI fail
- I don't understand the internal workings: maybe I'm just tired, but I have tried to solve the unit tests yesterday and today, and I am just getting nowhere, and I think this is because my current code is already too complex

As this is linked to #986 and #905 I think we have a bigger issue. I am also linking this to #1023 and #925 : 

- I am rolling back your changes as I don't want to have the master branch broken for too long
- We need a clear view of all those requirements, and how we could make everything fit together
- This will indeed be a breaking change, and this will probably be our 3.0 version

-> please don't take it personally, I am just rollbacking this as I want to include it into something bigger. But we need to think about it a lot more.

**Comment by gzsombor** [comment]
Interesting, could you send the json files for your app configuration ? 
Couple remarks: 
 - the generated tests doesnt cover the relations, so it's a bit strange, that you got tests failures. Could you tell me, what failed ? 
 - if the column names are not specified for the join table, it is defaulted to source table name+'_id', relation name + '_id'. Because previously the relation name were equal to the destination table name, that's why the previous table is generated with the destination entity

**Comment by jdubois** [comment]
Here is my current configuration, you need to execute those files in the same order:

https://gist.github.com/jdubois/f88505ed4021616a46f6

I just don't understand what isn't working...

**Comment by gzsombor** [comment]
There is one problem, that your config files generated by old hipster, without the relationname, and co, which cause problems with the re-generations (I could fix it easily).
After I encountered the same problem, which you found, that for creating a new 'operation' the server would execute these statements:
```
[DEBUG] com.mycompany.myapp.web.rest.OperationResource - REST request to save Operation : Operation{id=null, description='aaa', date='2015-02-09T04:04:00.000+01:00', amount='5'}
Hibernate: insert into T_OPERATION (id, amount, bankAccount_id, date, description) values (null, ?, ?, ?, ?)
Hibernate: insert into T_OPERATION_LABEL (operations_id, labels_id) values (?, ?)
Hibernate: insert into T_OPERATION_LABEL (operations_id, labels_id) values (?, ?)
```

However, if I create a new entity into this project :
```
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "something",
            "relationshipNameCapitalized": "Something",
            "relationshipFieldName": "something",
            "otherEntityName": "client",
            "relationshipType": "many-to-many",
            "otherEntityNameCapitalized": "Client",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldNameCapitalized": "Name",
            "fieldNameUnderscored": "name"
        }
    ],
    "fieldsContainOwnerManyToMany": true,
    "fieldsContainOneToMany": false,
    "fieldsContainLocalDate": false,
    "fieldsContainCustomTime": false,
    "fieldsContainBigDecimal": false,
    "fieldsContainDateTime": false,
    "changelogDate": "20150203174819"
}
```

Then the exact same server try to use
```
[DEBUG] com.mycompany.myapp.web.rest.BbbbbResource - REST request to save Bbbbb : Bbbbb{id=null, name='AA1'}
Hibernate: insert into T_BBBBB (id, name) values (null, ?)
Hibernate: insert into T_BBBBB_SOMETHING (T_BBBBB_id, somethings_id) values (?, ?)
Hibernate: insert into T_BBBBB_SOMETHING (T_BBBBB_id, somethings_id) values (?, ?)
```

So in one case, it generates the field names with the T_ prefix, and in the other, without that prefix. I have to investigate it further, why it happens.

**Pull request merged**
