### PR TITLE
Update nodejs version to 20.10.0

### PR DESCRIPTION
**Pull request by DanielFran**
Fix https://github.com/jhipster/generator-jhipster/issues/23882

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Tests are failing without been reported.

**Comment by mshima** [comment]
At current state I don't think it will succeed.
Loaders support at node 20 had a big behavior change.

**Comment by mraible** [comment]
@mshima All tests pass. Do you think it's OK to merge?

**Comment by mshima** [comment]
@mraible tests are not passing. `npm test` is failing silently.

**Comment by DanielFran** [comment]
@mshima Are you referring to that issue?
image

**Comment by mshima** [comment]
Success should report:
image

Locally the failure is verbose.

**Comment by mraible** [comment]
@mshima Do you think the CI failures are caused by the Node upgrade?

**Comment by mshima** [comment]
@mraible it's related to how node handles loaders (adds support to typescript and esm mocking).
Typescript loader works as expected, but esm mocking requires global state to keep the mocking state.

Loaders in node 18 and prior versions are considered experimental and are [rc in node 20](https://nodejs.org/docs/latest-v20.x/api/module.html#customization-hooks).

Loaders in node 20 runs in a different thread. The mocking state should be kept in user thread, but the mocking logic is done at the loaders thread.
The communication between the loaders thread and user thread should be reworked to use the thread channels.
This is what needs to be done: https://github.com/testdouble/quibble/compare/v0.6.17...v0.9.0.

We are using https://github.com/node-loaders/loaders/tree/main/workspaces/mock loader for mocking.
It should be updated to give support to node 20.

It should be possible to rework esm mocking since is used in 2 files only.

**Comment by mraible** [comment]
@mshima Will it be possible to provide Node 18 and Node 20 support, or should we make Node 20 the baseline?

**Comment by mshima** [comment]
Support both.

**Comment by mraible** [comment]
I'm gonna keep adding bug bounties until someone stops me. 😜

**Comment by DanielFran** [comment]
@mshima It seems now that the tests break now with details

**Comment by mshima** [comment]
Yes, that's the error.
Node 20 doesn't need to re-execute node apps passing the loader as argument or environment option. It can be registered at runtime.
I was thinking that it was a mocha misbehavior with unhandled exception but now seems to be in wrapper.

**Comment by mraible** [comment]
Any updates that can help move this one along?

**Comment by mshima** [comment]
I will try with vitest.

**Comment by mshima** [comment]
I am doing some tests with vitest and is not a good alternative for the main generator.
This was previously considered in https://github.com/jhipster/generator-jhipster/pull/22108#issue-1707902232.

vitest uses vite pipeline which brings a big overhead over mocha.
We are using vitest in blueprints which has much lower requirements.

JDL tests takes ~7 seconds using mocha and ~32 seconds using vitest in a M1 processor.

We may consider [node:test](https://nodejs.org/api/test.html) as a mocha alternative in the future.

**Comment by mshima** [comment]
There is a script to convert tests to vitest [here](https://github.com/mshima/generator-jhipster/tree/vitest).
If anyone wants to try.

I will switch the mocking lib to quibble and required node 18.19.0 for tests.

**Review by mshima — APPROVED** [review]

**Comment by mshima** [comment]
@DanielFran bounty for related PRs claimed https://opencollective.com/generator-jhipster/expenses/211709

**Pull request merged**
