### PR TITLE
Adding workbox for angular 1 and react

### PR DESCRIPTION
**Pull request by sendilkumarn**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
@mraible will you be able to test this please?

**Comment by mraible** [comment]
Just curious - why are we using the current system for Angular, but not for AngularJS and React? When using Angular CLI, I use [@angular/service-worker](https://medium.com/@webmaxru/a-new-angular-service-worker-creating-automatic-progressive-web-apps-part-1-theory-37d7d7647cc7), maybe that's why?

**Comment by sendilkumarn** [comment]
@mraible there are two main reasons why workbox is selected
1. The approach is more or less same across ng1 / ngx and react
2. since we do all the treeshaking and minification by ourselves, workbox will only focus on handling the js / css /.... files once the build is made

**Comment by sendilkumarn** [comment]
@mraible do you need some more time in testing this here. I would like to merge this 😄

**Pull request merged**
