### PR TITLE
Introduced API media type versioning through angular-vendor-media-type

### PR DESCRIPTION
**Pull request by jmnarloch**
I've introduced support in both frontend and backend for versioned vendor specific media types:

Examples:
text/plain -> text/vnd.jhipster.v1+plain
application/json -> application/vnd.jhipster.v1+json

Spring does not require any specific handling in other to introduce this change. 
On the angular side I had added angular-vendor- media-type extension and customized it so that the generator would populate the base name into it.

I would like to introduce this change and also open the discusion on potential improvments.

References:
http://www.baeldung.com/rest-versioning
http://restcookbook.com/Basics/versioning/
http://pivotallabs.com/api-versioning/
https://www.npmjs.com/package/angular-vendor-media-type

### CODE REVIEW

**Comment by gmarziou** [comment]
Interesting, what iss your particular use case you wanted to address with this change?

I mean this is useful when client and server can evolve separately which is currently not the case for JHipster,.

I am currently working on using JHipster as a backend server for a mobile application, in this case server and mobile are not coupled and so your change would make a lot of sense.

**Comment by deepu105** [comment]
Ya even I dont see what value this adds?

**Comment by gmarziou** [comment]
I wrote [few lines about API versioning](https://github.com/gmarziou/jhipster-ionic/blob/master/README.md#api-versioning) in my jhipster-ionic prototype.

Basically, if client supports a version too old, server can detect it and either decide to reject it so mobile app would ask user to upgrade or to route to another server/controller running older api version if backward compatibility is important for your business case.

It could also make sense if we were splitting server and client in different libs.

**Comment by jmnarloch** [comment]
The whole idea comes from very specific use case. In general what we have done is use part of JHipster to scaffold the project and create the prototype (well in fact we used only the jhipster frontend for the UI prototyping, the backend is already in quite advance state) of cloud native application, As you might guest it has been using versioned API. So due to this mindset I am proposing this change.

I share some of your concerns. Generally I didn't have a idea of introducing versioned API to JHipster in meaning that next release would shift from v1 toward v2. My intention was rather to give a user fully setup versioned REST API which he can use as he pleases.

**Comment by gmarziou** [comment]
Personnally I think it's a good change as it is transparent, if you don't need to version your API then it's OK but if you need it like for a mobile app then it is easy to use. 
However, it would have to be integrated with swagger-ui

**Comment by jmnarloch** [comment]
zrzut ekranu 2015-08-08 o 22 34 13

It looks like it work out of the box.

**Comment by gmarziou** [comment]
Have you clicked on the button 'Try it out'?
As this page is not using angular, requests cannot use your interceptor and there's nothing in your PR about swagger.
Anyway, don't do anything on this part as I'm changing it a lot.

**Comment by jmnarloch** [comment]
Well suprisingly the GET methods work like a charm, POST not so much with message:
```
{
  "timestamp": 1439067173977,
  "status": 403,
  "error": "Forbidden",
  "message": "Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'.",
  "path": "/api/account"
}
```

zrzut ekranu 2015-08-08 o 22 54 29

**Comment by gmarziou** [comment]
I'm working on the CSRF issue.

If the GET works then could it mean that your implementation server-side does not require the new media-type? Have you looked at the request headers in browser console?

**Comment by jmnarloch** [comment]
You are going to be suprised but all works even without intercepting being enabled for this piece, swagger can populate all of this data out of the @RequestMapping#procudes attribute apparently.

**Comment by gmarziou** [comment]
You're right, Springfox introspects the REST controllers to generate the swagger spec file, awesome.

**Comment by jdubois** [comment]
I've had a look at the code and this looks like a good idea to me. My main concern is that is uses https://www.npmjs.com/package/angular-vendor-media-type which was in fact made on purpose by @jmnarloch :

- I don't like to have a component that isn't widely used (please note that I had the same issue with https://www.npmjs.com/package/angular-cache-buster so don't take it personally!). If this is only used by JHipster, maybe at some point we could put all this into a jhipster.js file? @jmnarloch would you be OK with that?
- It also feel strange that for something like this, which looks quite common to me, we need to have something so specific
- Of course this should also be well documented on our website, because most people won't understand why this is done

@jmnarloch the PR currently has a merge issue, can you have a look at it?
@gmarziou do you still have the CSRF issue?
@deepu105 what's your opinion on this?

**Comment by gmarziou** [comment]
@jdubois I just merged it in my local repo and it works great with swagger and csrf, I tested all http verbs on a resource in swagger ui and in unit tests although only in session auth.

@jmnarloch since we migrated to Springfox, we have a swagger.version property in application.yml, I'm wondering whether it could be used for the header too or the other way around (using a java constant for media type and for swagger api version).

I tested also the case where server is in v1 and client is in v2, I created a book entity using the UI and it succeeded with a HTTP 201 Created while I was expecting an HTTP Error 406 Not acceptable, am I missing something?

In the screenshot you can see the request accept header v2 and in response the content type in v1.

screenshot from 2015-08-15 01 23 04

**Comment by deepu105** [comment]
I dont have any specific issue with this, my question was what is the need for this in Jhipster, but if you guys think thats it is useful then i dont have a problem

**Comment by gzsombor** [comment]
I think, it should be optional feature (I mean, this should be asked the user about it in the generation phase), because 
- it introduce a custom mime type, instead of the industry "standard" text/json, which is for me seems like a sign of the NIH syndrome.
- the problem, what it wants to solve is minor, feels minor - I guess, the minority of the users needs this multiple versioned API. And implementing it with URL based separation feels clearer, using /api/1/stuff and /api/2/stuff
- for web clients - where reloading the page is much simpler - it has absolutely no use, for them a REST call - /api/version - which would return the current build number, and a javascript service which would poll regularly, and notifies the the user in an alert to reload, would be awesome.
- if the JHIpster user upgrades their app to the latest JHipster, it would mean, that either he will have two type of REST services - the old ones are using text/json, the new ones are application/vnd.whatever, or he have to modify every old service, to be consistent. I know, upgrading JHipster is not really supported, but we know, that everyone does it.

**Comment by jdubois** [comment]
OK, after reading @deepu105 and @gzsombor I agree this is not a trivial use-case. This goes with my previous comment, why isn't this more widely-used? Probably because most people don't need this.
So this doesn't work with our philosophy of doing simple REST services, as people will first need to learn how this work.
It could indeed be an option of the generator, but I don't like having lots of options, as it complicates maintenance.
I'd like to have a look at what other people are doing, in the Rails, Node.js or Play! communities, maybe I'm missing something here.

**Comment by jmnarloch** [comment]
Hey,
I can see some interesting points. First of all let me say that I had rebase this change and additionally after @gzsombor sugestion introduced Yeoman prompt option (set to false by default). If you decide to merge this change I can squash the commits into one prior that.

@jdubois I do not have anything against including the functionality directly in jhipster, though keep in mind that the extension was written in CoffeeScript, so you would have to use it directly from compiled JavaScript or port it from CoffeeScript (I have plans to port the extension to TypeScript though). Ad 2. If I understand this point corectly, the other option is to hardcode the mime types in your whole application, or to use url versioning, which means basiclly - to hardcode the version in your whole application ;)

@gmarziou this is very interesting finding worth investigating. My guessing is that MappingJackson2HttpMessageConverter by default uses the *json wildcard for matching https://github.com/sitewhere/sitewhere-client/blob/master/src/main/java/com/sitewhere/rest/spring/MappingJackson2HttpMessageConverter.java#L58, although I might be wrong here. Does it mean that at this moment I am unable to define two @RequestMapping#someMethodV1 and #someMethodV2 one with v1 mapped and second with v2? I will try to check this tomorrow.

@gzsombor I had introduced this change as option, so that the user could choose not to enable it. I feel that I was able to close down this change to only two files that "if"-ed, the rest of application looks like intact by this change. In our project we had decided to completly resign from url versioning and not to tied up the client with unecessary burden. I partly agree with your points, so to emphesize again, I work with cloud native applications, were we saw the need for such resolution, so I am not forcing it to everyone. Interesting thought on the JHipster upgrading, I haven't thought about that. From my perspective the upgrade is kind of operation: "take it or leave it" at Yeoman side at least, although if someone is using VCS he should be able to do manual merges.

@jdubois It's up to you, 

I can agree that vast majority of rest API do not use API versioning, though I do not thing that this is their advantage. On other hand there are the industry giants, service providers etc. for which this is very common I guess. Some other thoughts, you probably all heard about Richardson maturity models, though not everyone is using the level 3 - Hypermedia i.e. HATEOAS links, though there are examples like for instance Paypal API: https://developer.paypal.com/docs/integration/direct/paypal-rest-payment-hateoas-links/ that is even bending the original idea and extend it for their own purpose.

A side of that, did you ever though about doing "jhipster cloud starter", maybe based on Spring Cloud? ;)

**Comment by jdubois** [comment]
OK, I've had feedback from various other people, and most of them to something like /api/v1/myendpoint which was my original idea.

- It's easier to understand for everyone, and it's easier to map if you have some load balancer or router in front
- Yes for us that means hard-coding the version, but that's also the idea: you can have 2 endpoints in 2 different methods, next to each other, one being the /v1/ and the other being the /v2/ -> that's what I've always been doing and it's very simple to do. I'm clearly not a REST guru, but I've done this many times and I really don't see why it's bad.
- Anyway we want a very simple model to use from the start, which is what we provide now

I don't like to have PRs opened for too long because they become impossible to merge, and this one does not have the unanimity. Besides, we should have talked about doing this before having the PR, please see the [guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#feature), they are here so that this kind of situation does not happen. This forces us either to accept the change without discussing it, or reject it when something good could have been merged.

-> I'm closing this because of this guideline issue, then yes we could discuss how we could improve JHipster following this idea. This could be an option in the generator, or quite simply a tooltip or a "best practice" document.

**Pull request closed without merging**
