### PR TITLE
Update wiredep to 3.0.0

### PR DESCRIPTION
**Pull request by erikkemperman**
As discussed [here](https://github.com/jhipster/generator-jhipster/commit/4abfbf95eb68dc3f98da72b5b82a75a4513d721c#commitcomment-16440767).

### CODE REVIEW

**Comment by erikkemperman** [comment]
Travis is kind of flaky, it seems to me. Once again, the exact same code passed all tests before!
https://travis-ci.org/erikkemperman/generator-jhipster/builds/112960795

**Comment by deepu105** [comment]
the error seems consistent when I re run
```
bower EMALFORMED    Failed to read /home/travis/app-psql-es-noi18n/bower.json
Additional error details:
Unexpected token }

```

can you check

**Comment by erikkemperman** [comment]
Sure, I'll check when I get to work.

**Comment by erikkemperman** [comment]
Hmm, there was a comma on the wrong side of a `<% if ... %>`. So now I'm wondering why this Travis test passed earlier, as linked above. I just re-checked and it really was the same commit...

Anyway, I fixed `_bower.json`.

**Pull request merged**
