### PR TITLE
Fix webflux compilation.

### PR DESCRIPTION
**Pull request by mshima**
Fixes https://github.com/jhipster/generator-jhipster/issues/12730
Backend CI is not passing due to partial update return status.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@atomfrede can you take a look why patch is giving the following error with webflux?
```
Error:  Tests run: 24, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.358 s <<< FAILURE! - in io.github.jhipster.sample.web.rest.FieldTestPaginationEntityResourceIT
944
Error:  io.github.jhipster.sample.web.rest.FieldTestPaginationEntityResourceIT.partialUpdateFieldTestPaginationEntityWithPatch  Time elapsed: 0.094 s  <<< FAILURE!
945
org.opentest4j.AssertionFailedError: 
946

947
Expecting:
948
 <1E+2>
949
to be equal to:
950
 <100>
951
but was not.
952
	at io.github.jhipster.sample.web.rest.FieldTestPaginationEntityResourceIT.partialUpdateFieldTestPaginationEntityWithPatch(FieldTestPaginationEntityResourceIT.java:1264)
```

**Comment by mshima** [comment]
This PR reverts a change related to reactive.
Makes webflux compile to succeed.
Now it’s failing at patch test introduced at
https://github.com/jhipster/generator-jhipster/pull/12688

Merging to get webflux builds to succeed as soon as possible otherwise we should disable it again.

**Comment by atomfrede** [comment]
Will have a look.

**Comment by atomfrede** [comment]
It looks like the values are correct, but seems like it tries to compare 100 with the scientific notation. Will have a look later today, should be quite easy to fix.

**Comment by mshima** [comment]
@atomfrede thanks

**Pull request merged**
