### PR TITLE
Added common web fonts to security configs

### LINKED ISSUE #22855: Fonts extensions now allowed by default
The new Security Config block everything by default which is great.
However, some extensions are still missing.

I think there should be a better way for allowing static resources, by securing only requests that go to the controller and redirect anything with an extension that is not /api and /management to fetch a resource.

- [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by dinu0000**
fix  #22855

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
Can you please provide a situation that this fixes? We don't include any fonts that match `"/*.woff", "/*.woff2", "/*.ttf", "/*.otf"` by default, so I'm not sure why this is needed.

**Comment by dinu0000** [comment]
This will be useful when user adds custom styles and fonts.

**Comment by mraible** [comment]
> This will be useful when user adds custom styles and fonts.

If a user adds custom fonts, they should also allow them in their security configuration. That's my opinion. I'm not sure we should allow things that a user *might* add.

**Comment by mraible** [comment]
@ dinu0000 This would be better integrated as a tip. Can you please add a PR to the website repo to add this tip?

https://www.jhipster.tech/tips/

I'm closing this PR. Please reopen if you feel strongly that it should be added.

**Comment by dinu0000** [comment]
PR for TIP created https://github.com/jhipster/jhipster.github.io/pull/1300

**Pull request closed without merging**
