### PR TITLE
Upgrade keycloak 22.0.1

### PR DESCRIPTION
**Pull request by BrayanMnz**
Fix #22915
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by BrayanMnz** [comment]
NO ADDITIONAL CONFIGURATION WAS ADDED TO THE BASE REALM IN THIS NEW KEYCLOAK VERSION. 

See the https://www.keycloak.org/2023/07/keycloak-2201-released.html for the list of enhancements and bugs added in this release. 

FYI @DanielFran

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
Thanks @BrayanMnz

**Comment by BrayanMnz** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/154650

**Comment by DanielFran** [comment]
@BrayanMnz approved

**Pull request merged**
