### PR TITLE
refactor table naming convention to underscored

### LINKED ISSUE #1721: SQL Table names should be underscored
SQL table names are currently not underscored, this needs to be fixed.

Ill work on this soon

### PR DESCRIPTION
**Pull request by deepu105**
change table naming to underscored convention

Fix #1721

### CODE REVIEW

**Comment by jdubois** [comment]
@deepu105 I don't want to have the underscores, or to have "_MAPPING" at the end of each mappings, I would rather stay with the default JPA namings.
Note that I did our current mapping a long time ago, and I'm not sure if our current names are the "JPA defaults", but my idea would be that we shouldn't have to write the table names in the first place.
I know it looks better with the underscores, but we are also supposed to use the technologies without adding configurations to them, unless it is necessary

**Comment by deepu105** [comment]
@jdubois but all the tables in the init files are underscored. so i thought it would be consistent and also more readable. Also from below link seems like spring default is underscored

http://stackoverflow.com/questions/29087626/entity-class-name-is-transformed-into-sql-table-name-with-underscores?answertab=votes#tab-top

And anyways since we have the @Table on the entity we are overriding default right?

Btw the _MAPPING is only for oracle when the mapping table name is longer than 30 char and this would help the user to understand the table when the name is shortened

**Comment by deepu105** [comment]
If im not wrong even the hibernate default is underscored right, and we are not following JPA default which will be camel cased table names we are creating tables as all uppercase which is kind of not clean say when something like EMPLOYEESHOPPINGCART is your table

**Comment by deepu105** [comment]
http://docs.spring.io/autorepo/docs/spring-boot/1.1.5.RELEASE/api/org/springframework/boot/orm/jpa/SpringNamingStrategy.html

**Comment by jdubois** [comment]
- You are correct for our "JHI_*" schema, but that's because it comes originally from the Spring Security schema -> I don't know if that's a good idea or not, it's only because at the beginning I just mapped the default Spring Security schema
- OK for the SpringNamingStrategy -> I guess it's better to follow the Spring strategy than the JPA one, as we are so heavily based on Spring
- Yes we always generate the @Table as this is something most people want to change (personally I'm much happier using the default value)
- Sorry for the _MAPPING suffix I didn't see it was only for Oracle, it's a good idea (and if Oracle sucks, we need to provide a solution)
- Camel cased table names are indeed ugly, it will cause problems

-> I need to have a closer look, but OK I need to change my mind
-> Any other feedback from other people? This is quite a big change, for everyone. @deepu105 maybe you should also ask this on the dev mailing list

**Comment by deepu105** [comment]
Ok ill open a thread there as well

**Comment by MatthieuLebigre** [comment]
From my experiences with severall senior DBA, I always seen table names uppercase with undescores.
I'm pretty sure from a DB perspective, this is the default naming.
But I don't know from a JPA perspective. I would say since we use @Table that we should follow DB naming convention.

**Comment by deepu105** [comment]
@jdubois as per your suggestion i have set spring as the default naming strategy.

I have tested with some entity combinations and relationships for SQL and seems to work fine.

I noticed that there is an issue in mapstruct impl where the mapper assumes that all relationships have a DTO and hence compilation fails when i have a dto class with  a non dto relationship, but thats a separate issue and has nothing to do with this change.

@andidev @gmarziou @atomfrede guys can anyone please test some more scenarios please, im really tight on schedule to do more testing

**Comment by andidev** [comment]
I could test this on my jhipster project

**Comment by deepu105** [comment]
Thanks man that would be great

**Comment by andidev** [comment]
just tested it with lots of names with lots of camelbumps and lots of relationships. Seems to work as expected. I feel I can read again :angel:  when I open up the H2 database.

tested jdl
```

entity MultiRelationalEntity{
}
entity OneToOneEntity{
}
entity OneToManyEntity{
}
entity ManyToManyEntity{
}

entity User {

}

relationship ManyToOne{
  MultiRelationalEntity{oneToManyEntity} to OneToManyEntity{multiRelationalEntity}
}
relationship OneToOne{
  MultiRelationalEntity{oneToOneEntity} to OneToOneEntity{multiRelationalEntity}
}
relationship ManyToMany{
  MultiRelationalEntity{manyToManyEntity} to ManyToManyEntity{multiRelationalEntity}
}

relationship OneToOne{
  OneToOneEntity{userEntity(login)} to User{oneToOne}
}
relationship ManyToMany{
  ManyToManyEntity{userEntity(login)} to User{manyToMany}
}



entity MultiRelationalDisplayFieldEntity{
}
entity OneToOneDisplayFieldEntity{
  displayField String
}
entity OneToManyDisplayFieldEntity{
  displayField String
}
entity ManyToManyDisplayFieldEntity{
  displayField String
}
relationship ManyToOne{
  MultiRelationalDisplayFieldEntity{oneToManyDisplayFieldEntity(displayField)} to OneToManyDisplayFieldEntity{multiRelationalDisplayFieldEntity}
}
relationship OneToOne{
  MultiRelationalDisplayFieldEntity{oneToOneDisplayFieldEntity(displayField)} to OneToOneDisplayFieldEntity{multiRelationalDisplayFieldEntity}
}
relationship ManyToMany{
  MultiRelationalDisplayFieldEntity{manyToManyDisplayFieldEntity(displayField)} to ManyToManyDisplayFieldEntity{multiRelationalDisplayFieldEntity}
}

```

**Comment by deepu105** [comment]
Thanks mate :) @jdubois ill add some release note text in the comments
below so that you can put them up when merging this

**Comment by deepu105** [comment]
@jdubois please see if this look ok

Release note:

We have a breaking change with this release of JHipster!
The SQL table names generated now follows the default Spring naming
strategy i.e, `SNAKE_CASE` instead of all `UPPERCASE` names. We have also
made `SpringNamingStrategy` as the hibernate default.
This means more readable table and relationship names. The change applies
to foreign key names and many to many mapping tables as well. For oracle
users we have some work around to overcome the table name length
restrictions. We now shorten the mapping table names and suffix `_mapping`
for long entity names.

For existing users you may want to take note of below.

* For new entities without any relationship to your old entities this
should work with out an issue
* For your existing entities you may want to change the foreign key column
names to proper snake case
* If your new entity has relationship to an old entity you may want to
manually update the old entity table name in the entity java file,
liquibase changelog and of course in the database.

If you face any migration issue feel free to open a ticket with your
jhipster version, your `.yo-rc.json` and entity.json files. we would be
happy to help

**Comment by jdubois** [comment]
I've tested on a (simple) application and it works fine: it looks like everybody agrees on this, and that it's stable, so I'm merging this!

**Pull request merged**
