### PR TITLE
Restructure server side option prompts

### PR DESCRIPTION
**Pull request by deepu105**
Related to #4129

@jdubois take a look and merge if this looks good to you

The options if not selected will be set as `false` instead of `'no'` have added backward compatibility as well.

### CODE REVIEW

**Comment by jdubois** [comment]
I didn't try it yet, but yes that's the idea, totally agree with what you did.

**Comment by jdubois** [comment]
Thanks @deepu105 , let's do this!

**Comment by jdubois** [comment]
@deepu105 it looks OK, but those are not only server-side options, they also generate client-side code -> I will rename the question to just "options"

**Comment by deepu105** [comment]
OK


Thanks & Regards,
Deepu

**Pull request merged**
