### PR TITLE
Upgrade maven to 3.3.9 [ci skip]

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by deepu105** [comment]
Dont you have to upgrade the wrapper binary as well?

**Comment by pascalgrimaud** [comment]
I don't think so, just need to update the properties file

**Comment by deepu105** [comment]
We used to update the bundled jar for gradle so thought it might be same
for maven

**Comment by pascalgrimaud** [comment]
> Once you have a wrapper you can change its version by setting the distributionUrl in .mvn/wrapper/maven-wrapper.properties, e.g.
> `distributionUrl=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.2.1/apache-maven-3.2.1-bin.zip`

Just tested it again:
```
$ ./mvnw -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/pgrimaud/.m2/wrapper/dists/apache-maven-3.3.9-bin/2609u9g41na2l7ogackmif6fj2/apache-maven-3.3.9
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-38-generic", arch: "amd64", family: "unix"
`̀``

**Comment by deepu105** [comment]
ok then :) @atomfrede does gradle behave the same?

**Comment by atomfrede** [comment]
You can do the same for gradle. But gradle has a dedicated task to generate wrapper config for a specific version. Usually I just update the version in build.gradle and execute the wrapper task to get the new wrapper config

**Pull request merged**
