### PR TITLE
Update Angular dependencies

### PR DESCRIPTION
**Pull request by jdubois**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
I spent the evening on this, clearly the tests are wrong, but I have no idea how to solve them.

I'm pretty sure we need to copy our Webpack configuration to `karma.conf.js`:

                        test: /\.ts$/,
                        loaders: [
                            'angular2-template-loader',
                            'awesome-typescript-loader'
                        ],
                        exclude: ['node_modules/generator-jhipster']

But for making the tests pass, I'm really not sure. I followed https://angular.io/docs/ts/latest/guide/testing.html#!#spy-stub very closely and I still have `undefined is not an object` errors when accessing my Spy.

-> I won't have much time for this, and I've already spent hours here, so help is really, really welcome on this part

**Comment by jdubois** [comment]
If someone wants to check this, here is my current code on a sample entity.

- As said above, it's failing with "undefined is not an object"
- I don't understand why I need to create a `FooServiceSpy` - otherwise, the `spyOn` doesn't seem to be able to create the object on the fly

Ping @dancancro as I remember seeing one of his questions on StackOverflow, and he's having the same issues.

```
import { ComponentFixture, TestBed, async, inject } from '@angular/core/testing';
import { OnInit } from '@angular/core';
import { DatePipe } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs/Rx';
import { DateUtils, DataUtils, EventManager } from 'ng-jhipster';
import { Tmp2TestModule } from '../../../test.module';
import { MockActivatedRoute } from '../../../helpers/mock-route.service';
import { FooDetailComponent } from '../../../../../../main/webapp/app/entities/foo/foo-detail.component';
import { FooService } from '../../../../../../main/webapp/app/entities/foo/foo.service';
import { Foo } from '../../../../../../main/webapp/app/entities/foo/foo.model';

describe('Component Tests', () => {

    describe('Foo Management Detail Component', () => {
        let comp: FooDetailComponent;
        let fixture: ComponentFixture<FooDetailComponent>;
        let fooServiceSpy: FooServiceSpy;

        beforeEach(async(() => {
            TestBed.configureTestingModule({
                imports: [Tmp2TestModule],
                declarations: [FooDetailComponent],
                providers: [
                    DateUtils,
                    DataUtils,
                    DatePipe,
                    {
                        provide: ActivatedRoute,
                        useValue: new MockActivatedRoute({id: 123})
                    },
                    FooService,
                    EventManager
                ]
            })
                .overrideComponent(FooService, {
                    set: {
                        providers: [
                            {provide: FooService, useClass: FooServiceSpy}
                        ]
                    }
                })
                .compileComponents()
                .then(() => {
                    fixture = TestBed.createComponent(FooDetailComponent);
                    comp = fixture.componentInstance;
                    fooServiceSpy = fixture.debugElement.injector.get(FooService) as any;
                    fixture.detectChanges();
                });
        }));

        describe('OnInit', () => {
            it('Should call load all on init', () => {

            // WHEN
            comp.ngOnInit();

            // THEN
            expect(fooServiceSpy.find.calls.mostRecent()).toHaveBeenCalledWith(123);
            expect(comp.foo).toEqual(jasmine.objectContaining({id:10}));
            });
        });
    });

});

class FooServiceSpy {

    find = jasmine.createSpy('find').and.callFake(
        () => Promise
            .resolve(true)
            .then(() => Object.assign({}, new Foo(10)))
    );
}
```

**Comment by deepu105** [comment]
Ill take a look at this

**Comment by deepu105** [comment]
This one is driving me crazy. I spent almost half day on this working my way up one error after the another. I hate Angular. Why upgrading to a minor version such a pain. This shouldn't have broken anything but it does. I dont see anything wrong with our tests as they work currently but the error seems illogical

**Comment by jdubois** [comment]
Totally agree. I spent the night on this. We follow the documentation, we have no helpful error message... This is so badly made!!!!
As always the Angular team just does a simple "Hello World" and brags about it in all conferences around the world, but no real use-case works :-(

**Comment by deepu105** [comment]
I need to work today so I give up for now and will try again tomorrow. I guess we can skip this update for next release if this turns out too difficult to fix.

**Comment by deepu105** [comment]
Actually the default tests without any entity is failing as well. I tried upgrading libs in ng-jhipster as well no luck.

**Comment by pascalgrimaud** [comment]
@deepu105 : I don't understand your last message:
> Actually the default tests without any entity is failing as well. I tried upgrading libs in ng-jhipster as well no luck.

Are you talking about `yarn test` ? In Travis, it seems to be OK:
```
.JS 2.1.1 (Linux 0.0.0): Executed 56 of 58 SUCCESS (0 secs / 1.477 secs)
.JS 2.1.1 (Linux 0.0.0): Executed 57 of 58 SUCCESS (0 secs / 1.498 secs)
.JS 2.1.1 (Linux 0.0.0): Executed 58 of 58 SUCCESS (0 secs / 1.524 secs)
PhantomJS 2.1.1 (Linux 0.0.0): Executed 58 of 58 SUCCESS (1.836 secs / 1.524 secs)
JS 2.1.1 (Linux 0.0.0): Executed 58 of 58 SUCCESS (1.836 secs / 1.524 secs)
=============================== Coverage summary ===============================
Statements   : 68.14% ( 1360/1996 )
Branches     : 30.29% ( 73/241 )
Functions    : 45.08% ( 270/599 )
Lines        : 65.85% ( 1184/1798 )
================================================================================
```

**Comment by sendilkumarn** [comment]
@pascalgrimaud is this in ng-jhipster ?

**Comment by pascalgrimaud** [comment]
Oh you're talking about this branch and not the current master, sorry!

**Comment by deepu105** [comment]
Yes talking of angular4 tests in this branch. Ng-jhipster is already on
angular 4.1.3 and tests pass there


Thanks & Regards,
Deepu

**Comment by sendilkumarn** [comment]
actually there is a missing breaking change in angular 2. I found a fix. I will create a new MR.

or @jdubois can I change it here and give you a MR

**Comment by jdubois** [comment]
Yes Sendil do a PR, I can merge it on my phone.

**Comment by jdubois** [comment]
Sorry, I messed up: do another PR, it's simpler, and we'll close this one

**Comment by deepu105** [comment]
WTF breaking change? I checked there changelog from 4.0 to 4.1 and didnt find any. @sendilkumarn what was it. I wasted hours on this

**Comment by jdubois** [comment]
And so did I!!!

**Comment by deepu105** [comment]
They could have atleast mentioned it in changelog or something as breaking or note or whatever
Anyway closing this in favour of PR from Sendil

**Pull request closed without merging**
