### PR TITLE
Upgrade gatling to v2.3

### PR DESCRIPTION
**Pull request by cbornet**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Gatling has updated the scala version, does that effect the build with kafka?

**Comment by jdubois** [comment]
Oh yes you need to check if Gatling and Kafka works each time one of them is touched... That's totally crazy.

**Comment by cbornet** [comment]
Yes, there's a conflict between Kafka and Gatling over the scala version. I wanted to see if something can be done. If not, let's close it for now.

**Comment by atomfrede** [comment]
Gatling also works with the older version so if that helps we can try this

**Comment by cbornet** [comment]
I'm closing this for now.
At least we're aware of the scala version issue...

**Pull request closed without merging**
