### PR TITLE
allow to don't generate user registration and password reset

### PR DESCRIPTION
**Pull request by mshima**
Related to https://github.com/jhipster/generator-jhipster/issues/23803

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
What's the reason for this? Did someone request it?

**Comment by mshima** [comment]
> What's the reason for this? Did someone request it?

Not every blueprint supports password reset.

**Comment by mshima** [comment]
I don't remember which blueprint now 😕.

**Comment by mshima** [comment]
Nodejs: https://github.com/jhipster/generator-jhipster-nodejs/blob/b8befe28a9025ad26d888eaaa1f6306708b29819/generators/cypress/generator.js#L21-L23

**Comment by mshima** [comment]
I am fine with this.

**Pull request closed without merging**
