### PR TITLE
add grafana with pre-configured dashboard view and few refactoring updates

### PR DESCRIPTION
**Pull request by srinivasa-vasu**
- Grafana added with pre-configured dashboard view
- Prometheus operator is included (as the app specific bits like service monitor and rbac objects are dependent on the operator crd)
- Aligned some of the prompts (jhipster console and prometheus) to be in sync with docker-compose
- Added a shell script pgm to deploy all of the k8s objects at one go
- Added init-container check to deployment object to wait for dependent services initialisation
- Output file structure is been refactored
- README and test spec updated accordingly

### CODE REVIEW

**Comment by deepu105** [comment]
@srinivasa-vasu @PierreBesson Since its a feature can we make it part of v5?

**Comment by PierreBesson** [comment]
Wow huge work @srinivasa-vasu ! Yes let's have this for v5.

**Comment by deepu105** [comment]
@PierreBesson can we merge this. The failing build is for React so should be ok. I restarted it anyway

**Comment by PierreBesson** [comment]
Yes it can be merged without issue.

**Pull request merged**
