### PR TITLE
chore: Migrate cassandra travis pipeline to github actions CI

### PR DESCRIPTION
**Pull request by vishal423**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
@pascalgrimaud, If you don't see an issue, I would like to merge this change. I have few more changes lined up to migrate more jobs from `travis ci`

**Comment by pascalgrimaud** [comment]
I'd like to go away from Travis, so here what I suggest:
- migrate all builds from Travis to Github Actions
- keep only npm test on Travis

What do you think ?

**Comment by vishal423** [comment]
I don't see harm in keeping `travis ci` to utilize it's available build infrastructure, however, would like to reduce current load to parallel jobs limit (I think 5) so that we can have faster builds. Since, our build scripts are quite independent (thanks to you), they can easily be moved across different CI. 

Github CI allows around 20 parallel jobs and I think we can do following:
- Add additional flows or move few jobs from daily builds.
- Add new jobs to test generated applications on windows OS.

**Comment by pascalgrimaud** [comment]
wow 20 jobs !
Is it per organization or per repository ?

**Comment by vishal423** [comment]
I think it's per repository

**Pull request merged**
