### PR TITLE
Reduce IDE warnings

### PR DESCRIPTION
**Pull request by erikkemperman**
I realize we're probably never going to get completely rid of IDE warnings for generated apps, but this will reduce the number considerably.

These changes are all quite minor -- but there are many of them...

Travis passes:
https://travis-ci.org/erikkemperman/generator-jhipster/builds/366090249

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x]  Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
I'm sorry I cancelled your build, everything is broken since I did the merge to the new jhipster libs, I'm trying to find what's wrong.

**Comment by erikkemperman** [comment]
@erikkemperman No problem, I understand that has more priority!

I don't want to make a PR for it because it will claim Travis again, but I had forgotten you reverted the SB 2.0.1 upgrade... So something like this will also be needed:

https://github.com/erikkemperman/generator-jhipster/commit/7b59bb764d5a8efdbe77570217d4877042d74500

**Comment by jdubois** [comment]
@erikkemperman can you make the change to Spring Boot 2.0.1 and push again? This will trigger the build again, and this time it should pass

**Comment by jdubois** [comment]
Awesome work!

**Comment by erikkemperman** [comment]
Thanks for merge! One thing I should mention;
https://github.com/jhipster/generator-jhipster/pull/7481/files#diff-54e2b26f2ffaaa71ba9f3cbae86c0ddbR46
This change is equivalent to before, but perhaps those `ZuulProperties` could be configured?
Or if we leave it as is, probably should remove the “TODO” I added...

**Comment by jdubois** [comment]
Yes I saw it but I was lazy and didn't write a comment :-)
Let me have a look

**Comment by erikkemperman** [comment]
Or maybe make it an ejs comment so it doesn’t show up in generated code?

**Pull request merged**
