### PR TITLE
fix missing export

### PR DESCRIPTION
**Pull request by sinedied**
---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

Latest 8.0.0-beta1 update removed the `./esm/priorities` import entirely, with no alternative replacement.
This PR adds it back as `./priorities` removing the `/esm/` prefix like other imports, so blueprints can be migrated to the new version.

### CODE REVIEW

**Comment by mshima** [comment]
The path doesn't exists anymore.
Priorities are exported as Class static fields at v8 because different generators can have different priorities.
A blueprint generated using v8 `jhipster generate-blueprint` has the new notation documentation needs update.

**Comment by mshima** [comment]
@DanielFran it's done https://github.com/jhipster/jhipster.github.io/pull/1287.

**Comment by jdubois** [comment]
Thanks @mshima ! As @sinedied is not working this week, I'll check with him on Monday.

**Comment by sinedied** [comment]
Thanks @mshima and @DanielFran, I'll update my blueprints with the new API

**Pull request closed without merging**
