### PR TITLE
[Code Standards] Remove space

### PR DESCRIPTION
**Pull request by Akuka**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
People who upgrade are going to hate this but 👍 for me.

**Comment by jdubois** [comment]
@PierreBesson not if they use "jhipster upgrade"!

**Comment by deepu105** [comment]
@pascalgrimaud the azure build says its successful in 1 minute, seems like an Azure bug WDYT?

**Comment by pascalgrimaud** [comment]
@deepu105 : no idea lol

**Pull request merged**
