### PR TITLE
Migrate from cloud sleuth to micrometer tracing

### PR DESCRIPTION
**Pull request by mshima**
Closes https://github.com/jhipster/generator-jhipster/issues/20004.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Micrometer tracing is still a milestone and probably will follow spring boot 3 cycle, rebased against spring 3 branch.
Seems to be some integration with spring-boot-actuator that should be available at 3.0.0-RC1.
Tried to use snapshot, but failed to compile.

**Comment by mshima** [comment]
It works almost of the box.
It's conflicting with prometheus right now https://github.com/spring-projects/spring-boot/pull/32817#issuecomment-1287456322.

**Comment by mshima** [comment]
It's working out of the box after https://github.com/jhipster/jhipster-bom/pull/986/commits/9bb15eb16aab831742835c89c66c16c22f4c6b30.

Documentation updated at https://github.com/jhipster/jhipster.github.io/pull/1238.

Tested using:
```
jhipster --application-type gateway --defaults --cache-provider no
docker compose -f src/main/docker/zipkin.yml up -d
./mvnw -Pdev,webapp,zipkin
```
Navigate to `localhost:8080` and go to `http://localhost:9411/` and click `RUN QUERY`.
Tracing should be shown.

**Comment by mshima** [comment]
If startup freezes, disable Prometheus at application.yml.

**Review by mraible — APPROVED** [review]
It looks like snapshots need to be updated.

**Pull request merged**
