### PR TITLE
fix gradle error/hanging in windows

### PR DESCRIPTION
**Pull request by kaidohallik**
reverts #4683 and replaces with better solution for gulp
resolves error/hanging on executing npmInstall and yarn_install
my comment in open gradle issue: https://github.com/gradle/gradle/issues/882#issuecomment-269996978

### CODE REVIEW

**Comment by kaidohallik** [comment]
I updated PR, now avoiding webpack error/hanging in Windows: changed `GulpTask` to `NodeTask` and use this in both cases: angular1 and angular2.

If gradle issue will be resolved then can remove this part from `build.gradle`

**Comment by deepu105** [comment]
this is really hacky and I feel we shouldnt be doing this as its not an issue with what we do or our code and to me its not a serious issue affecting everyone so I would rather have it as a tip for windows users and keep our builds clean from such stuff @jhipster/developers what do you think?

**Comment by pascalgrimaud** [comment]
I agree with you @deepu105
I didn't follow closely all these tickets, but it seems like a problem from gradle.

@kaidohallik : is there a problem with an older version of gradle ? If no, I think we should use an older version and wait for https://github.com/gradle/gradle/issues/882

**Comment by mehmet-aslan** [comment]
I normally work with larger screen buffer height (5000 - 9000) at Windows command prompt and clear output periodically. I didn't encounter this issue at this workflow but I could reproduce it with screen buffer height 300. `gradlew build` command is either gives error or just hangs at `npmInstall/yarn_install` and `webpack` tasks even if I clear output before.

This hack solves the issue but I prefer a tip about using larger screen buffer height and clearing unnecessary output before buffer exceeds.

**Comment by kaidohallik** [comment]
@pascalgrimaud There are inputs from gradle 2.x version about that problem and current version 3.2.1 is also affected.

It maybe can be fixed in gradle side but maybe this is some strange Windows problem what cannot be fixed in gradle.

Tip is ok for me. But gulp older fix is already taken into source. So I will make revert PR for #4730

**Comment by kaidohallik** [comment]
I made PR-s for tip and for revert gulp hack.
If tip will be accepted, will you @mehmet-aslan update tip with your suggestions to avoid error/hanging?

**Comment by mehmet-aslan** [comment]
@kaidohallik I checked your tip and it seems enough for me. You already wrote about increasing buffer height so I could only add clearing output when I have time.

**Comment by kaidohallik** [comment]
Tip is merged and old gulp hack is reverted so I'm closing this.

**Pull request closed without merging**
