### PR TITLE
npmw: revert to global node if local is not found.

### PR DESCRIPTION
**Pull request by mshima**
Local node is disabled for gradle and apple silicon, improves apple silicon support.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Not related to this PR, but I think there is an issue at line 8, with webapp profile, which doesn't exist for microservice

**Comment by mshima** [comment]
`npmw` isn’t used for microservice at the generation time.
https://github.com/jhipster/generator-jhipster/blob/687995104775c290ae4f0b2e506329e56a71149b/generators/server/index.js#L104-L106

If we write it, we can remove.

**Comment by pascalgrimaud** [comment]
It is used here: https://github.com/jhipster/jhipster-sample-app-microservice/blob/main/npmw#L8

And if I'm not wrong, I saw some error when I upgraded my microservice with last version of JHipster, when commiting. So maybe some use by the prettier auto commit with husky

**Comment by mshima** [comment]
I mean we should remove the `npmw` command and adjust husky.

**Pull request merged**
