### PR TITLE
Bump maven-jar-plugin to 3.2.2

### PR DESCRIPTION
**Pull request by AntonBarkan**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
Why should we make this change? What problem does this solve?

**Review by Akuka — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
@Akuka : as you approved, maybe can you explain this change ?

**Comment by AntonBarkan** [comment]
`spring-boot-maven-plugin` use output of  `maven-jar-plugin`, in spring starter used parent pom https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.2/spring-boot-dependencies-2.6.2.pom updated version of this plugin used, seems better to update this plugin too, for better compatibility

**Comment by mshima** [comment]
The description is wrong. 2022 not 2012.

**Comment by Akuka** [comment]
> The description is wrong. 2022 not 2012.

The current version used by JHipster is maven-jar-plugin 2.4, which was released in January 2012

**Comment by DanielFran** [comment]
Relaunching tests

**Comment by Tcharl** [comment]
Please sign the cla so that we'll merge it

**Comment by Tcharl** [comment]
Welcome!

**Pull request merged**
