### PR TITLE
Use randomAlphanumeric instead of random for password in tests codes 

### PR DESCRIPTION
**Pull request by pmverma**
Follow up of #18502
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pmverma** [comment]
It is strange that I am not able to reproduce the failing build locally.

@DanielFran , Can you please help follow the steps to reproduce?

1. Run `mkdir pr18530 && cd pr18530 && touch .yo-rc.json`
2. Copy [.yo-rc.json of failing build](https://github.com/jhipster/generator-jhipster/runs/6238321368?check_suite_focus=true#step:16:64)
3. Remove entities from `.yo-rc.json`
4. Run `jhipster`
5. Run `./mvnw clean verify`

[Failing error log](https://github.com/jhipster/generator-jhipster/runs/6238321368?check_suite_focus=true#step:21:1047)  is strange. 
I need to check for the string literal `"test"`, it is defined nowhere in the file.

**Comment by DanielFran** [comment]
@pmverma I did the test this morning and was not able to reproduce it locally also :(

Maybe something related with ci-cd cache?
@mshima any clue?

**Comment by mshima** [comment]
My guess would be that the cleanup failed.
I added a change to test.

**Comment by mshima** [comment]
It is a leftover from UserJWTControllerIT test.
Don't know why it started failing with this PR.

**Pull request merged**
