### PR TITLE
Added api docs into dto

### PR DESCRIPTION
**Pull request by javasparx**
Close https://github.com/jhipster/generator-jhipster/issues/8924

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
ya it makes sense @cbornet are you fine with this?

**Comment by DanielFran** [comment]
+1
And if you can remove from entities the swagger annotation when using DTO's would be owesome.

**Comment by cbornet** [comment]
+1 seems legit

**Comment by PierreBesson** [comment]
+1 it looks super useful

**Comment by javasparx** [comment]
Ok, I will try to remove swagger annotations from entities.

**Comment by javasparx** [comment]
Hi guys, I am not sure about this parts of code, leave or remove them from domain model?

image

**Comment by murdos** [comment]
@javasparx You should obviously keep the javadoc.
Just to make sure we understand each other: you should only remove swagger annotations from the domain model if the dto is generated. Otherwise swagger annotations should be present in domain model.

**Comment by javasparx** [comment]
Now it is ok.

image

**Comment by DanielFran** [comment]
@javasparx Can you please review last few comments from @murdos so we can merge it asap?
Thanks

**Comment by DanielFran** [comment]
@javasparx Can you please rebase and review last few comments from @murdos so we can merge it asap?
Thanks

**Comment by javasparx** [comment]
> @javasparx Can you please rebase and review last few comments from @murdos so we can merge it asap?
> Thanks

yes

**Comment by DanielFran** [comment]
@jdubois @deepu105 Can we merge it also?

**Comment by javasparx** [comment]
Did as @murdos said in review.

**Comment by javasparx** [comment]
Sorry guys, I forgot about the issue. Please, review last commit. @murdos , @DanielFran

**Comment by murdos** [comment]
Thanks @javasparx!

**Pull request merged**
