### PR TITLE
Set executable war to true by default

### PR DESCRIPTION
**Pull request by cbornet**
See #2225 

The issue with Cloud Foundry deployment should be fixed with cf CLI  v6.14.1
I don't have a CF account so I cannot test. Can somebody confim that it works ?

### CODE REVIEW

**Comment by jdubois** [comment]
I'm testing this right now!

**Comment by jdubois** [comment]
It's alive at http://jhipstercf.cfapps.io/ :-)

So I'm merging this!

**Comment by cbornet** [comment]
Great http://jhipstercf.cfapps.io/ ! Do you think you could add some entities with various fields (eg. the ones from travis) and maybe a cleanup task to limit the size of the DB. Then show this to the world as a live sample JHipster app ?

**Comment by jdubois** [comment]
Not really: CloudFoundry only gives me 2 Go of RAM for free, so I can test my app... I would need to ask for more, but it's always hard to get.

**Pull request merged**
