### PR TITLE
Upgrade to Keycloak 6.0.1

### PR DESCRIPTION
**Pull request by mraible**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
Can we also sync realm configurations?

**Comment by mraible** [comment]
@vishal423 I'm not sure what you mean. Sync between which sources?

**Comment by vishal423** [comment]
@mraible, I was referring to `jhipster-realm.json` templates that still uses keycloak `v4.3.0.Final` configurations. It's always good to sync those along.

**Comment by mraible** [comment]
@vishal423 Can you describe the steps to do that? Do you mean loading up the current ones, and then exporting them again?

**Comment by vishal423** [comment]
@mraible, Last time, I started from scratch as I wanted to encapsulate Jhipster specific mappers into their own implicit scope `jhipster` and reuse across different clients. If there are no new features, then, import/export configurations can be an easy approach.

**Pull request merged**
