### PR TITLE
Fix entity crea error

### LINKED ISSUE #5346: On error during entity update, save button is not enabled back
##### **Overview of the issue**

When editing an entity, on pressing save button, if error is received from the server save button is not enabled back.
I believe this happens only when enableTranslation is false, as I don't see this issue in Jhipster Sample application from git.

##### **JHipster Version(s)**

Jhipster Version 4.0.7

##### **JHipster configuration**

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

Browser: Chrome & Firefox
OS: Mac OS

- [x] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #5347: Entity should be refreshed when edited from entity detail page
##### **Overview of the issue**

When I click Edit button from Entity Detail page, edit entity modal is opened. On pressing save button, modal is closed but entity on the detail page is not updated. We have to refresh the entity detail page to reflect the changes on page.

If entity is edited from Entity List page, on pressing save button, modal is closed and entities are updated fine.

##### **Motivation for or Use Case**

Its nice to see entity edited from entity detail page 

##### **Suggest a Fix**

Like we are subscribing to entityListModification event on entity list page, and reset the entities there, we can subscribe to entityListModification event on entity detail page.

##### **JHipster Version(s)**

4.0.7

##### **JHipster configuration**

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "eachfit",
    "packageName": "com.eachfit",
    "packageFolder": "com/eachfit",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

- [x] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #5372: Not logged user can access to /entityName pages
##### **Overview of the issue**

Even if a user is not logged in, he can access to an entity page. The data is not loaded of course but the user should be redirected to login modal.

##### **Motivation for or Use Case**

We should have a correct redirection.

##### **Reproduce the error**

Create an app
Create an entity
Access to the entity page via /entityname

##### **Related issues**
None.

##### **Suggest a Fix**

It's in the main.component.ts file. Sometimes it's correct to do this:
`let destinationEvent = event.state.root.firstChild.children[0];`

But sometimes we shouldn't get firstChild but 'root'. I can commit this "dirty" fix tonight if you want.
I don't know if there is a better fix for this...

Maybe we can check this : https://angular.io/docs/ts/latest/guide/router.html "Guard the admin feature"

##### **JHipster Version(s)**

master

##### **JHipster configuration**

All defaults options

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Any entity will do

##### **Browsers and Operating System**

Mac OS

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by sendilkumarn**
Fix #5372
Fix #5347
Fix #5346

### CODE REVIEW

**Comment by sendilkumarn** [comment]
duplicate of #5385

**Comment by jdubois** [comment]
- Which PR is the good one?
- Your build is failing

Can I help you here? I'm not the best one on this part, but I have some time this morning

**Comment by jdubois** [comment]
@sendilkumarn I'm sorry but your build has still got test errors (and they are not due to Travis)

**Comment by sendilkumarn** [comment]
@jdubois funny windows didn't show any error (surprisingly), am checking that again.

**Comment by sendilkumarn** [comment]
@jdubois this fixes it.

**Comment by jdubois** [comment]
OK can you merge it? I'm on my phone I can't merge builds that didn't succeed

**Comment by sendilkumarn** [comment]
Ha ha... the phone view only prevents you from merging. When you change to desktop view, you can merge,  just like I did now.

**Comment by jdubois** [comment]
Oh yes of course

**Pull request merged**
