### PR TITLE
React: Performance improvement and lazy loading

### LINKED ISSUE #7864: React slow to load in production
##### **Overview of the issue**

I created an example app, blog post, and screencast about how to develop a Photo Gallery PWA with React and JHipster.

Blog: https://developer.okta.com/blog/2018/06/25/react-spring-boot-photo-gallery-pwa
Screencast: https://youtu.be/GlJWUqy1SJM
Source: https://github.com/oktadeveloper/okta-react-photo-gallery-example
Heroku: https://gallery-pwa.herokuapp.com/

You can see from the screencast and Heroku that i18n translations are slow to load and performance is poor. If I run Lighthouse on Heroku (after it wakes from sleeping), it scores a 39 for performance.

screen shot 2018-06-26 at 6 28 50 am

##### **Motivation for or Use Case**

I think we can do better.

##### **Reproduce the error**

Create a React app with JHipster 5, deploy it to Heroku, test it with Lighthouse.

##### **JHipster Version(s)**

```
gallery@0.0.0 /Users/mraible/dev/okta/okta-react-photo-gallery-example
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "monolith",
    "baseName": "gallery",
    "packageName": "com.okta.developer",
    "packageFolder": "com/okta/developer",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "herokuDeployType": "git",
    "herokuAppName": "gallery-pwa"
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album (album) {
  title String required,
  description TextBlob,
  created Instant
}
entity Photo (photo) {
  title String required,
  description TextBlob,
  image ImageBlob required,
  height Integer,
  width Integer,
  taken Instant,
  uploaded Instant
}
entity Tag (tag) {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User,
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.1

node: v9.8.0

npm: 6.1.0

yeoman: 2.0.2

yarn: 1.7.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 5a3f1a3

**Related:** `jhipster info` seems to work for getting the version on Linux, but not on Mac. Notice that it says (empty) for the JHipster version.

### LINKED ISSUE #7880: React: Fix lazy loading
The lazy loading doesnt see to work correctly due to the use of `commonjs` instead of `esnext` in tsconfig. Also some optimizations needs to be done in webpack config.

### PR DESCRIPTION
**Pull request by deepu105**
Fix #7864 
Fix #7880 

This improves the overall performance of React apps and also fixes lazy loading

image

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
@mraible can you check this. I didn't test PWA though

@atomfrede @vishal423 I guess this can be optimized even further, especially momentJs and other huge libs like lodash.

**Comment by mraible** [comment]
@deepu105 I tried checking out your branch, creating a new app, and deploying it to Heroku. It doesn't score very well (27) for performance.

https://gallery-pwa-screencast.herokuapp.com/

screen shot 2018-07-02 at 11 15 53 am

**Comment by deepu105** [comment]
@mraible thats strange.
I'm getting a pretty descent score, this is with RxJS, let me try without it

image

**Comment by deepu105** [comment]
@mraible I get a better score on your app as well, are you sure your plugin is up to date? i'm using the inbuilt chrome audit btw

image

**Comment by deepu105** [comment]
And without RxJS I get a descent 70

image

**Comment by atomfrede** [comment]
I have seen the same. Build in scores quite well 60 to 70. With the Plugin
ist just 20. Not sure why

Deepu K Sasidharan <notifications@github.com> schrieb am Mo., 2. Juli 2018,
19:30:

**Comment by mraible** [comment]
If I use Chrome DevTools and the Audit option, it's a bit better.

screen shot 2018-07-02 at 11 33 19 am

**Comment by raharrison** [comment]
The Lighthouse reports seems very dependent on what hardware you are running:

image

**Comment by deepu105** [comment]
@mraible I guess I have done all I could think of. Let me know if anything else can be improved.

For RxJs in websocket support, @ruddell was it you who optimized imports in the Angular build for RxJS?

**Comment by mraible** [comment]
I tried it on a different MacBook Pro and I got better numbers too. 

screen shot 2018-07-02 at 2 19 40 pm

FWIW, I can create a JHipster app in around 2 minutes on this Mac too!

**Comment by atomfrede** [comment]
I will check with the bundle analyzer how the bundle size looks like. Will also try to remove moment and replace it day.js to get rid of another large dependency.

**Comment by atomfrede** [comment]
Regarding lodash. I added `lodash-es` for testing it worked quite well (was very hard to find the single module in the bundle analyzer view) but something else imported normal lodash :( I have seen there is a lodash webpack plugin, did anyone tried that already?

**Comment by deepu105** [comment]
@atomfrede I already took care of lodash. I didnt use lodash-es as it needed use of a babel plugin, so I used the direct path imports. I also removed lodash dependency from the react-jhipster lib.
If you are planning to remove momentJs, you need to remove it in the react-jhipster lib as well.

Let merge this one and do further improvement in another PR since this might give merge conflicts since I touched many files

**Comment by deepu105** [comment]
@mraible may be there is some issue with your MacBook :wink:

**Pull request merged**
