### PR TITLE
Upgrading to MapStruct 1.1.0.Final

### PR DESCRIPTION
**Pull request by gunnarmorling**
Updated the versions of MapStruct I found. I hope I didn't miss anything?

### CODE REVIEW

**Comment by deepu105** [comment]
@gunnarmorling thanks. You could also consider to help us to get mapstruct support out of beta :stuck_out_tongue_winking_eye:

**Comment by gunnarmorling** [comment]
I'll try to do the best I can :) I'm not sure though what would be needed
to make it happen. Anything you miss from MapStruct in order to call your
support final?

**Comment by deepu105** [comment]
I guess for now its mostly quirks in IDE and some issues with handling complex relationships @jdubois might know better

**Comment by jdubois** [comment]
Yes we have 2 kinds of issues:

IDE configuration: I've spent a lot of time on this, I have no idea how to do it correctly. You can have a look at https://jhipster.github.io/configuring-ide/ (look for the "IDE profile" at the bottom), and you can contribute changes [here](https://github.com/jhipster/jhipster.github.io).

And we also have mapping issues, like [here](https://github.com/jhipster/generator-jhipster/issues/4356), but this isn't really a MapStruct issue, it's mostly us having trouble to use it correctly, with some corner cases.

**Pull request merged**
