### PR TITLE
Remove the use of the Web layer in the service layer

### LINKED ISSUE #4867: Remove the use of the Web layer in the service layer
As discussed in #4865

We have some Web/REST objects being called from the service layer, which is an architecture error, and causes package tangling (this should be seen by Sonar, I need to check).

Typically, the `ManagedUserVM` shouldn't be used in the service layer, that's why we have a `UserDTO`-> the `VM` is for "View Model", that's used for displaying in the Angular/HTML views, and the `DTO` is for "Data Transfer Object", that's used for transferring the object from one layer to another (if the entity isn't enough). Of course a DTO can be used as a VM, but the opposite isn't true.

### PR DESCRIPTION
**Pull request by jdubois**
Fix #4867

### CODE REVIEW

**Comment by gzsombor** [comment]
Makes sense !

If I were you, I would introduce "imageUrlSupported" flag, and "pkType" variable in the server generator, instead of the lot's of repetitive if-s :)

**Comment by jdubois** [comment]
So happy you like it :-)
Yes my code is repetitive but I find it clearer that way, for newbies. Anyway, at some point I hope that we will support this in Cassandra, so they should be totally deleted in the end.

**Comment by deepu105** [comment]
I think we already have the `pkType` flag in server generator

**Comment by gzsombor** [comment]
Just in the entity generator

**Comment by deepu105** [comment]
Oh ya sorry

Thanks & regards,
Deepu

**Pull request merged**
