### PR TITLE
Do not wait 4 seconds and then display error if ui is loaded before.

### PR DESCRIPTION
**Pull request by lionnel**
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@lionnel Can you sign the CLA please?

**Comment by mshima** [comment]
This PR fixes any bug?
In my opinion we should clear the timeout at page destroy instead.

**Review by mshima — CHANGES_REQUESTED** [review]
`jhipster-error` exists at creation and may be removed from DOM after the application is loaded.
If that happens `checkStillError` will be executed forever.

If we need to resolve `setTimeout` before the timeout for some reason, we should should use `clearTimeout`.

IMO we should close this PR.

**Comment by mshima** [comment]
Closing.
This PR doesn’t seems improve current implementation.

**Pull request closed without merging**
