### PR TITLE
Fixes to JDL annotation parsing

### LINKED ISSUE #12949: [jdl] Change jdl annotations.
##### **Overview of the feature request**

- Change jdl annotations to set lowerFirst option:
```
entity A {
  @Id Long customId
}
```
Should set `id` option to true instead of `Id`.

- Change relationship annotation to don't create options in the other side.
```
application {entities *} entity A{} entity B{} relationship OneToOne { @id A to B }
```
Currently generates:
```
{
  "name": "A",
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "b",
      "otherEntityRelationshipName": "a",
      "relationshipName": "b",
      "otherEntityField": "id",
      "ownerSide": true,
      "options": {
        "id": true
      }
    }
  ],
...
}
{
  "name": "B",
  "relationships": [
    {
      "relationshipType": "one-to-one",
      "otherEntityName": "a",
      "otherEntityRelationshipName": "b",
      "relationshipName": "a",
      "otherEntityField": "id",
      "ownerSide": false,
      "options": {
        "id": true
      }
    }
  ],
...
}
```
Makes harder to detect if A is id of B or if B is id of A.

A solution is to allow annotations on other side:
`relationship OneToOne { A to @id B }`

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by MathieuAA**
Fixes #12949

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@MathieuAA this PR fixes item 1 from https://github.com/jhipster/generator-jhipster/issues/12949.
Can we merge this?
Any update for item 2?

**Comment by MathieuAA** [comment]
Number 2 takes a bit of time to do and test. I'm almost done, but it's tricky as it's a syntax change.

**Comment by mshima** [comment]
@MathieuAA great thanks.
See https://github.com/jhipster/generator-jhipster/issues/12949#issuecomment-733670222.

**Review by mshima — APPROVED** [review]
LGTM.

I have just a observation:
`jpaDerivedIdentifier` should be deprecated soon.
`A{b} to B{a} with jpaDerivedIdentifier`
should be equivalent to:
`A{b} to @Id B{a}`

So I don't know how useful global options is.

**Comment by MathieuAA** [comment]
Okay, when the option is removed, we can change the code later on then.

**Comment by mshima** [comment]
@MathieuAA thanks.
Great work.

**Pull request merged**
