### PR TITLE
Update spring-boot version to 2.5.x

### PR DESCRIPTION
**Pull request by DanielFran**
Fix https://github.com/jhipster/generator-jhipster/issues/15387

Depends on https://github.com/jhipster/jhipster-bom/pull/353

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@jhipster/developers spring-data-elasticsearch [search](https://github.com/spring-projects/spring-data-elasticsearch/blob/4.1.x/src/main/java/org/springframework/data/elasticsearch/repository/ElasticsearchRepository.java#L63) method has been removed in spring-boot 2.5 version.

This is affecting:
- https://github.com/jhipster/generator-jhipster/blob/main/generators/entity-server/templates/src/main/java/package/common/search_stream_template.ejs#L26
- https://github.com/jhipster/generator-jhipster/blob/main/generators/entity-server/templates/src/main/java/package/common/search_template.ejs#L46
- https://github.com/jhipster/generator-jhipster/blob/main/generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs#L260
- https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/web/rest/PublicUserResource.java.ejs#L175

Any suggestion on what would be the best approach?

**Comment by mraible** [comment]
@DanielFran Anything I can do to help?

**Comment by DanielFran** [comment]
@mraible I am just short of time, but will try to finish it this week.
Basically just missing elasticsearch

**Comment by DanielFran** [comment]
Superseded by #15633

**Pull request closed without merging**
