### PR TITLE
Update pom.xml.ejs to fix issue #10180

### LINKED ISSUE #10180: openapi - generated pom.xml bug
##### **Overview of the issue**

with open-api option selected,
in the generated pom.xml,
at openapi-generator-maven-plugin section,
execution.configuration
there is an element named "validateSpec",
which is not defined.
(promoted by intellij then manually check by me)

##### **Motivation for or Use Case**

programming error.

##### **Reproduce the error**

just generate a project.

##### **Suggest a Fix**

I think it should be
```xml
<skipValidateSpec>false</skipValidateSpec>
```
##### **JHipster Version(s)**
6.2.0

##### **JHipster configuration**
```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ai.techfin",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "6.2.0",
    "applicationType": "monolith",
    "baseName": "tradeSystem",
    "packageName": "ai.techfin",
    "packageFolder": "ai/techfin",
    "serverPort": "8080",
    "authenticationType": "session",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "rememberMeKey": "6784f92a8fac4fa29d9b9b32e41d9c8afd4c7f2267cb03b28eaf7c111b30c677537df84a06b10df98c4362ee546c2c5b8d3f",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ],
    "blueprints": [],
    "skipClient": true
  }
}
```

### PR DESCRIPTION
**Pull request by GitAntinus**
Fixes #10180
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by GitAntinus** [comment]
A second submit failed to pass ci test because of network problem. I do not want to make a third submit identical to the second one and I did not find a way to make Travis try again

**Comment by atomfrede** [comment]
Thanks @GitAntinus and congratulations to your first contribution!

**Comment by GitAntinus** [comment]
> Thanks @GitAntinus and congratulations to your first contribution!

happy to do it :)

**Comment by pascalgrimaud** [comment]
@GitAntinus : congrats !

For your information, you can close / reopen the pull request to restart the CI if needed.

**Pull request merged**
