### PR TITLE
localize token date on sessions page

### PR DESCRIPTION
**Pull request by sergii-ostroverkhov**

### CODE REVIEW

**Comment by deepu105** [comment]
This is not major and has ui changes hence can be merged after angular2 changes

**Comment by jdubois** [comment]
I like this as it removes quite a lot of useless code!

**Comment by deepu105** [comment]
On second thought we can merge this now. @sendilkumarn @wmarques can any of you add the date pipe to the sessions page in our ng2 branch?

**Comment by wmarques** [comment]
@deepu105 Sure, I can do this once I'll migrate the sessions page if it's ok for you

**Comment by deepu105** [comment]
yes please


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@wmarques plz merge this once you have migrated the sessions page

**Pull request merged**
