### PR TITLE
Updated bower dependencies

### PR DESCRIPTION
**Pull request by mrzepinski**

### CODE REVIEW

**Comment by jdubois** [comment]
Did you test everything, for example does the "prod" profile works?

**Comment by mrzepinski** [comment]
@jdubois Jep :) It works fine. I can check it by yourself.

**Comment by jdubois** [comment]
Oops... I merged and now everything is broken... I'm rolling back your commit, we will have to check this again!

**Comment by mrzepinski** [comment]
@jdubois What is going on? What is wrong? :) Give me some tips or stacktrace.

**Comment by jdubois** [comment]
I'm testing, give me 10 minutes :-)

**Comment by jdubois** [comment]
Sorry, the error seems to be on my side!! I'm testing again, but now I keep your commit :-)

**Comment by mrzepinski** [comment]
@jdubois It could be also nice to bump JHipster version to 2.1.0. I have some small improvements. For example `gulp-usemin` is on black list: https://github.com/gulpjs/plugins/blob/master/src/blackList.json I use `gulp-useref` for that and it works on streams.

**Comment by jdubois** [comment]
Yes version 2.1.0 should be released anytime soon. If you want to upgrade Gulp, please talk with @amr (=open up a ticket) as he is our official Gulp.js maintainer and expert!

**Comment by mrzepinski** [comment]
@jdubois Ok. Thanks. First I have to get `2.1.0` to merge my changes with commits from here :)

**Comment by amr** [comment]
Hi @mrzepinski! You are right, some plugins are ought to be upgraded/replaced. Feel free to submit PRs

**Pull request merged**
