### PR TITLE
Upgrade Angular to 5.1.0 / TypeScript to 2.5.3

### PR DESCRIPTION
**Pull request by kevcodez**
Angular 5.1.0 officially supports TypeScript 2.5.x

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by gmarziou** [comment]
Thanks, angular cli 1.6.0 has also [some dependencies on newer version of webpack](https://github.com/angular/angular-cli/blob/1.6.x/package.json), I wonder whether we should upgrade it too.

**Comment by kevcodez** [comment]
@gmarziou Good point, webpack-dev-server and webpack-merge-tools seem to be fine. However, I upgraded webpack to 3.10.0 to align it with Angular 5 .1.0.

**Comment by gmarziou** [comment]
OK, I see also that uglifyjs-webpack-plugin has also evolved and is no longer in beta. There may be other ones to check. Tomorrow I'll run some tests with your changes.

**Comment by kevcodez** [comment]
@gmarziou  Aswell as rxjs, file-loader, postcss-loader, copy-webpack-plugin and extract-text-webpack-plugin.

I aligned the dependencies.

**Comment by sendilkumarn** [comment]
@kevcodez I have updated the ng-bootstrap library too. The error in travis is because of some library issues I guess. Lets check this out.

**Comment by gmarziou** [comment]
I have tested it on Windows but it failed in workbox-webpack-plugin only for a prod build: `mvnw -Pprod clean package` though I don't think it is related to this PR.

~~~
[ERROR]  95% emittingError: workbox-sw is needed by the service worker and could not be copied over to your new site. Error: EPERM: operation not permitted, open 'e:\projets\paratt_simpler\target\www\workbox-sw.prod.v2.1.2.js'                                                                                                                                                              
[ERROR]     at Promise.all.then.catch (e:\projets\paratt_simpler\node_modules\workbox-build\build\lib\utils\copy-workbox-sw.js:17:13)                                                           
[ERROR]     at <anonymous> 
~~~

**Comment by sendilkumarn** [comment]
yeah I think it is because of my PR. I will have a look.

**Pull request merged**
