### PR TITLE
chore(app): add addNpmDependency and addNpmDevDependency functions

### PR DESCRIPTION
**Pull request by vogloblinsky**
The function addBowerDependency is available, and it would be nice to have the same for npm.

So i propose this PR.

### CODE REVIEW

**Comment by vogloblinsky** [comment]
@deepu105 The checks seems to break on a side not impacted by my PR...

https://travis-ci.org/jhipster/generator-jhipster/jobs/188206153#L4515

**Comment by pascalgrimaud** [comment]
I'm restarting the Travis job

**Comment by vogloblinsky** [comment]
@pascalgrimaud ok nice, seems to be ok now ;)

**Comment by vogloblinsky** [comment]
thanks @deepu105

**Comment by deepu105** [comment]
​You are welcome​


Thanks & Regards,
Deepu

**Pull request merged**
