### PR TITLE
Added language to user settings page

### PR DESCRIPTION
**Pull request by tporadowski**
User can now change his default language at any time in Account/Settings. It was a bit misleading for me that language was changed after logging in and seemed to be not persisted (yet, it was persisted, but I could not change it, especially for existing admin/user accounts).

### CODE REVIEW

**Comment by jdubois** [comment]
I don't understand: currently, you just change the language by selecting it in the menu. Once you are logged in, it is persisted.
Can you explain your issue?

**Comment by tporadowski** [comment]
The latter from your description is not correct - once you are logged in language persisted during __registration__ is used (as described in [lines 13-14 of _auth.service.js](https://github.com/jhipster/generator-jhipster/blob/c7e7ecfad9f5ee05ecade758a618ecde96aca1b9/app/templates/src/main/webapp/scripts/components/auth/_auth.service.js)) and switching to a different language is not persisted. For instance:
- you open JHipster app with English culture
- you switch to Polish
- you log in as `user` - UI switches to English (as "en" is `user`'s default language)
- you want to switch back to Polish - ok, but it is not persisted at all, so next time you log in as `user` - you're back to English.

And that's why I added a language drop-down in Account/Settings, so default language for the user can be changed and persisted.

**Comment by tporadowski** [comment]
As an addition - switching language in drop-down in main navbar could be persisted, too (in case there is some user logged in), but it's not implemented at the moment.

**Comment by gzsombor** [comment]
:+1:

**Comment by jdubois** [comment]
Oh sorry @tporadowski -> I thought it was already working that way!
I need to check this: I didn't code it myself, and now I see I don't understand how it's working :-(

**Comment by andidev** [comment]
Isn't it better to persist the language on language change rather then introducing a language field in the settings page?

**Comment by cselti** [comment]
It's little different, because when you choose different language than English or French as default at the app generation phase - both the app and entity generator will generate the language.json files for this language too.
 I'm not only think to save the user's default language - I would like to define the application's default language (and the entity generator will generate translation files for this language too).

**Comment by tporadowski** [comment]
@andidev yes, that's a second thing that is not working - last selected language is stored in a cookie, but after logging in it's overridden by language stored in DB. So either each change in language is saved in DB or at least cookie setting should take precedence if found.

**Comment by tornabene** [comment]
Added new language. Italian language. git@github.com:Ntipa/generator-jhipster.git.
Peaks can I helped in the evolution of jhipster

**Comment by tornabene** [comment]
merge please git@github.com:Ntipa/generator-jhipster.git.

**Comment by jdubois** [comment]
@tomsoete if you added another langage, that's great, but can you do a separate ticket and submit a PR for this?

**Pull request merged**
