### PR TITLE
Add a prompt for the Azure location

### LINKED ISSUE #14863: azure-app-service missing location argument for app-insights
##### **Overview of the issue**

Azure Application Insights instance does not exist, creating it...
Error: Command failed: az monitor app-insights component create --app blog-insights --resource-group jhipster
ERROR: the following arguments are required: --location/-l

TRY THIS:
az monitor app-insights component create --app demoApp --location westus2 --kind web -g demoRg --application-type web --retention-time 120
Create a component with kind web and location.

https://aka.ms/cli_ref
Read more about the command in reference docs

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'az monitor app-insights component create --app blog-insights --resource-group jhipster'
}
/home/HOME/workspace/jhipster7-demo/node_modules/generator-jhipster/generators/generator-base.js:1787
    throw new Error(`${msg}`);
    ^

Error: Could not create the Azure Application Insights instance
    at module.exports.error (/home/HOME/workspace/jhipster7-demo/node_modules/generator-jhipster/generators/generator-base.js:1787:11)
    at /home/HOME/workspace/jhipster7-demo/node_modules/generator-jhipster/generators/azure-app-service/index.js:429:26
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

##### **Suggest a Fix**

Add a location prompt to configuration

##### **JHipster Version(s)**

7.0.1

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by jdubois**
Fix #14863

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
[This issue](https://github.com/jhipster/generator-jhipster/pull/14946) makes me wonder, do we need JDL support for this?

**Comment by MathieuAA** [comment]
There's currently no Azure deployment in the JDL, but yes: I think we want JDL support for this.

**Comment by jdubois** [comment]
Indeed, we could have deployment inside the JDL.

Now, just to explain you how it works with https://nubesgen.com/ -> if you select the "GitOps" option, the whole deployment is set up for you using GitHub Actions.
I believe this is the best solution for JHipster. The cloud provider is responsible for:
- Testing his Terraform config
- Deploying the final app to this config

This goes much farther to what we currently do with JHipster, but most importantly the testing (which costs $$ and is only interesting for the cloud provider) is done and paid by the could provider.

**Comment by MathieuAA** [comment]
Interesting :) I'm currently reviewing and updating the deployment part in the JDL. If I can do something to make the addition/update of options easier, I'll do it.

**Pull request merged**
