### PR TITLE
Avoid git commit if regenerating existing project

### LINKED ISSUE #10158: Auto commit in manual upgrade should be avoided
##### **Overview of the issue**

Since #8645 JHipster auto commits changes if manually upgrading project.

Auto commit can be avoided if using flag `--skip-git`, but I always forget this flag and then must do `git reset` to commit before upgrade, which is annoying.

In some comments of #8880 other people also don't like this auto commit behaviour on manual upgrade.

##### **Reproduce the error**

Generate project with JHipster (run command `jhipster`). Initial code is committed to Git with message "**Initial application generated by JHipster-6.1.2**".  
Make some changes and commit these to git with message "**My changes**".  
Regenerate project (run command `jhipster` again). Regenerated code is automatically committed to Git as new commit with message "**Initial application generated by JHipster-6.1.2**".

Now Git contains 3 commits with messages:
* Initial application generated by JHipster-6.1.2
* My changes
* Initial application generated by JHipster-6.1.2

and all changes made in commit with message "My changes" are lost.

##### **Suggest a Fix**

Possible fix is to change line https://github.com/jhipster/generator-jhipster/blob/master/generators/app/index.js#L517 from
```
                        if (code === 0 && this.gitInitialized) {
```
to
```
                        if (code === 0 && this.gitInitialized && !this.existingProject) {
```

##### **JHipster Version(s)**

```
jhipster@0.0.0 C:\projects\teest\jhipster-git
`-- generator-jhipster@6.1.2  -> C:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": [
      "et"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

git version 2.21.0.windows.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01
##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by kaidohallik**
fix #10158
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by kaidohallik** [comment]
@pascalgrimaud after you closed-reopened this PR I noticed that Travis builds are failing. I think this is related to my change. I started working to improve this PR now.

**Comment by kaidohallik** [comment]
Travis tests failed because these used predefined `.yo-rc.json` files and currently JHipster app generator variable `existingProject` is initialized based on `.yo-rc.json`

I improved this PR with following:
* existing project check in Git related logic: instead of checking `.yo-rc.json` availability, check if there is at least 1 commit in Git, because generating new application from existing `.yo-rc.json` is a legal action
* because of multiple application generation from JDL the following changes:
    * use `git add .` instead of `git add -A` and `git commit -m "message" -- .` instead of `git commit -am "message"` - this way in mono repo approach every application is committed with separated commit
    * add application base name to Git commit message - this way it's easy to see in Git history which commit is for which application (for mono repo approach)
    * in console logs include application paths to inform which applications are committed to Git and which applications have pending changes

I tested following cases:
* generate multiple applications from JDL with `jhipster import-jdl`
* generate application with `jhipster` if `.yo-rc.json` **is present**
* generate application with `jhipster` if `.yo-rc.json` **is missing**

I tested each above case with 2 sub cases:
* Git repo was initialized before generation
* Git repo was not initialized before generation

Let's see if Travis tests will pass.

**Comment by pascalgrimaud** [comment]
Thanks for the PR @kaidohallik

I agree with your changes, as I prefer this behavior, but did you test the upgrade sub generator ? I think the auto commit was done for that...

**Comment by kaidohallik** [comment]
Auto commit was introduced in #8645. I didn't find linked issue with information why this change. But if thinking what this #8654 changes then logical explanation is: mono repo is used and requirement is to commit all initial application generations into this Git mono repo.

Upgrade sub generator has automatic tests and all these tests passed.  
Is there some documentation how to test upgrade sub generator locally?

**Comment by pascalgrimaud** [comment]
upgrade sub generator is a pain to test and reproduce issue. The npm test is not enough I think. The best way would be to use Docker with old container. But I'm not a user of this sub generator :-) 

Unless someone has comments, I'll merge this soon, before the next release

**Pull request merged**
