### PR TITLE
Method with 6-7 String parameters is not the best pattern to follow

### PR DESCRIPTION
**Pull request by gzsombor**
It's better to pass the values as an object, so it's simpler to understand

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
Is it OK to have a dependency from service layer to REST layer ?
I think a method `User registerUser(UserDTO userDTO, String password)` would be cleaner.

**Comment by jdubois** [comment]
Good catch @cbornet -> there should not be a service -> REST dependency. I cleaned them up some time ago, that was really bad.

**Comment by cbornet** [comment]
OK. I'll do the change after #6411

**Comment by gzsombor** [comment]
Please, do not re-use the UserDTO, again. We can have a new class, for registration. Classes are cheap ;-)
 We can have a RegistrationDTO or UserRegistrationDTO, and an UserUpdateDTO, and an UserSelfViewDTO and PublicUserDTO. 
 Currently it's very confusing, who can see what, and which field is mandatory in different places.

**Comment by cbornet** [comment]
That would mean moving ManagedUserVM to the service layer (and become ManagedUserDTO). No problem for me.

**Pull request merged**
