### PR TITLE
Kubernetes improvements

### PR DESCRIPTION
**Pull request by pascalgrimaud**
- use Docker tag instead of imagePullPolicy -> fix https://github.com/jhipster/generator-jhipster/issues/5172
- add port and targetPort -> related to https://github.com/jhipster/generator-jhipster/issues/5174, I don't close this as @PierreBesson will probably work on adding ingress

### CODE REVIEW

**Comment by PierreBesson** [comment]
@pascalgrimaud I don't think it makes much sense to ask the tag in a question like you do. Are you sure about this ? What would you do if different microservices have different version numbers ?

What we could do is configure the maven/gradle docker build to set the version from the artifact version or git commit. Then when generating the k8s configuration we ask for the tag for each microservices.

**Comment by pascalgrimaud** [comment]
@PierreBesson : good point about microservices with different version numbers. I'm not sure about adding a question about the tag, it was simply the easiest and fastest solution.

I didn't use the artifact version because of the comment from Saturnism:
> Tag the image w/ a version (potentially githash, or a build number, but not the artifact version), and deploy the tagged images instead.

The idea was to generate some Kubernetes files and people would custom with what they want/need.
If you have another idea, don't hesitate @PierreBesson !

**Comment by PierreBesson** [comment]
I think it would be OK if the tag question was asked for every microservice. Can you do this for now ?

**Comment by pascalgrimaud** [comment]
right now -> I can't, because of day work :)
I try to do it tonight or tomorrow morning

**Comment by pascalgrimaud** [comment]
After 1 day thinking about this, here my opinion:
- in real production, the user will probably use `latest` as tag version, and the developer will update their image to the registry. So the K8s cluster will always pull the latest image. I can't imagine an architecture with 20 microservices and the DevOps updating every yaml file, to adapt to every version, every new release. This full configuration should stay stable with `latest`

- on demo, specially with Minikube, we should use tag (`demo` or `test`), to avoid pulling the image from a registry. So we can build, push, tag directly to minikube (using `eval $(minikube docker-env)`). I don't think we will put a specific version to every microservices

So for me, this PR is simple: ask tag version and use the same for all.
It will be overkill to ask a question tag for every microservices.
@PierreBesson : what do you think?

**Comment by PierreBesson** [comment]
@pascal As someone who is part of team actually managing a production kubernetes cluster with over 20 microservices I'm the right person to answer you !

Using the "latest" tag in prod is certainly a bad idea. What you usually do is that you have a separate kubernetes clusters for staging (or at least a specific namespace) where you test different combinations between versions. You run your integration tests and once it's passing you can promote those tags to production.
In the ideal world this happens automatically.

When you say "updating every yaml file" this is basically what you need to do. Yes this is tedious but this is very important so you that you can upgrade or rollback to specific versions.

Of course you can use templating of yaml files or something like helm/kpm to manage versions in manifest files but really "latest" should not be used.

So for me either we ask the tag question for every microservice or we put the maven artifact version as the defaut tag and extract the tag from properties.

**Comment by pascalgrimaud** [comment]
Ok, I understood and agree your point of view about not using latest

> When you say "updating every yaml file" this is basically what you need to do. Yes this is tedious but this 
is very important so you that you can upgrade or rollback to specific versions.

I wonder if it will be usefull to code and maintain our k8s sub generator to ask a tag for every microservice ?
- Will the DevOps team use our sub generator to update / changing their version -> I'm not sure
- Or will they simply use their own tools to edit the generated yaml files ? -> I think for this options, as the initial yaml files we provide will probably be customized

@PierreBesson : your turn :smile:

**Comment by pascalgrimaud** [comment]
@PierreBesson : so, after spending 2 hours on looping for prompting a question for every microservices, it's harder than expected... as I'm not a NodeJS developer :(
Should we spend more time, for something the user can simply edit ?

@jdubois / @deepu105 : do you have an opinion about this?

**Comment by PierreBesson** [comment]
@pascalgrimmaud,

Don't worry asking a question for each microservice. I'm having an idea now. That we can put thz version as a default docker tag and extract it from the build.properties file in the target/build directory. Just give me some time to experiment with it.

**Comment by mraible** [comment]
I'd love to demo how this works in a screencast. I was able to do a successful deploy to Google Cloud today and would love to document/record a screencast. Running on port 80 seems like an essential feature.

**Comment by pascalgrimaud** [comment]
rebase done to keep this PR up-to-date, after the refactor by Deepu

**Comment by pascalgrimaud** [comment]
@PierreBesson : this PR has been opened for a long time. What should we do ? 
- close this and you take the lead on the opened ticket ? 
- or merge this, as for me, it's better than what we currently have

**Comment by PierreBesson** [comment]
@pascal If we ask the docker tag question we should ask it for every service, then that would be ok. Would you agree to do this change ?

**Comment by pascalgrimaud** [comment]
As already said, I tried to code this but it's not as easy, and I really think it's not worth doing this, because it can be done manually very fast: it's our policy 2.

So I'm closing this, let stay like this for now -> with latest tag

**Pull request closed without merging**
