### PR TITLE
Generate Javadoc and static reporting site

### PR DESCRIPTION
**Pull request by Tcharl**
Works when https://github.com/jhipster/jhipster-dependencies/pull/10 will be merged.

Adds erikkepperman work, and some steroids maven (site generation, gpg key gen, apache enforcing, licence header gen).

- Please make sure the below checklist is followed for Pull Requests.

- [X ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [X ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
please put a better title

**Comment by jdubois** [comment]
This adds more than 600 lines of code in the build files - this is definitely not good for people upgrading, so I'm not a big fan of this.
As this does several different things, could you split this into separate PRs? At least that would be easier to understand and review

**Comment by Tcharl** [comment]
It will be far less important when https://github.com/jhipster/generator-jhipster/pull/6509 will be merge.

The only modifications which will stay will add:
* Automated release with maven-release-plugin (only two plugins declaration, gpg & release-mvn)
* Site Generation (the reporting configuration is kind of large, but if it is not complete, it's useless)
* License header generation (only one plugin declaration)

Do you want that I cut this PR in 3? But the site gen will however be 570 lines...

**Comment by erikkemperman** [comment]
@Tcharl FYI https://github.com/jhipster/generator-jhipster/pull/6509 is merged.

**Comment by Tcharl** [comment]
Is it normal that  JHIPSTER=app-mysql PROFILE=prod fails?

**Comment by deepu105** [comment]
No its not normal at all

**Comment by Tcharl** [comment]
It works now. Can a committer try an 'mvnw clean site' on a sample project and look at the Target/site/index.html resulting site to see what is this pr about? More free lunch for end users ;-).
I'll then make an issue to share the potential associated features that could be done around the subject.

**Comment by Tcharl** [comment]
Note that the wow effect is better when you fill the <développer>, organisation, mailinglist and all Maven informational content on the pom (or the parent one, which is here for this purpose)

**Comment by erikkemperman** [comment]
@Tcharl It looks like you cherry-picked some of the commits from my jhipster-dependencies PR. That's fine, of course, but those are now already in master... To avoid duplication, it might be a good idea to make a diff of your work against current master and submit a single clean commit here? Just a suggestion :-)

**Comment by jdubois** [comment]
Just to be 100% sure I understand: you extract a parent pom.xml, so you can have reporting and site in external pom.xml files, and skim down the project's pom.xml, is that correct?

**Comment by Tcharl** [comment]
Yes, I have split the original pom in 4 parts, otherwise, it would have been very complicated and hard to maintained:

- I have create a 'parent' pom (the one in the parent folder) (which can inherit from a company pom if any)
-> This pom is here to store general informations on the project (scms, organization, developpers, mailing list...), it's the 'company pom for the project'.
-> This pom also contains all release stuff, because all the poms chain shall be pushed on the ARM in order to make the project usable by everyone, so it also has the gpg signing plugin, scm wagons, nexus-pro integration, ...

- I created a parent pom child called reporting
-> Here is stored everything concerning the reporting of the project: javadoc, coverage report, dependency scanning, etc... Using 'mvn site' on a child project will then generate a static website reporting all these reporting plugin results.

- I created another reporting child called 'plugins'
-> This pom stores every pluginmanagement stuff (plugins versions) for the project, in order to 'skim down' its child poms, and potentially having a plugin governance throughout children modules/microservices and generic configurations (for example, the one of the eclipse-lifecycle plugin).

- And finally, we have the 'original' project pom (inheriting from the plugin one)
-> It contains project dependencies (managed by the jhipster-dependency bom) as well as project plugins configurations and project profiles.

Note that this PR offers perspective in term of pipeline: leading to CD (using maven release pg within travis, circle, etc.), and enterprise asset management (with site description deployment automation, automated OSS compliance checking and license header generation, ...) but there are some more tasks to achieve ;-)

**Comment by Tcharl** [comment]
@erikkemperman Sure! Also, can you review this one, as you're following it from the beginning? I'll be glad to have your insights on it.

**Comment by erikkemperman** [comment]
Not sure when I have time, I’ll try asap!

**Comment by Tcharl** [comment]
Can close this one: Erik asked me to clean it, so I did ;-). It was easier to start from a new branch. #6739

**Pull request closed without merging**
