### PR TITLE
Remove Prettier java option in favor of having it baseline

### PR DESCRIPTION
**Pull request by avdev4j**
fix https://github.com/jhipster/generator-jhipster/issues/12109

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by avdev4j** [comment]
I did not notice that @mshima already did the job. However I found a bug in search templates that can be fix with my last commit. 

I know we did not take the same way but I have no problem to close my PR in favour or yours @mshima  (and open a specific open for the bug).

Also what do you think about print the error object instead of error.message in prettierTransform ? In my case the error was undefined and I struggled a bit to find the reason.

**Comment by mshima** [comment]
> I did not notice that @mshima already did the job. However I found a bug in search templates that can be fix with my last commit.

No problem.

> I know we did not take the same way but I have no problem to close my PR in favor or yours @mshima (and open a specific open for the bug).
> 
> Also what do you think about print the error object instead of error.message in prettierTransform ? In my case the error was undefined and I struggled a bit to find the reason.

Sure.

@avdev4j the problem is that I think prettier options is not been honoured.
We don't have useful tests for prettier java, the only prettier java test does not do the job anymore.
Can you add a blueprint test that overrides `.prettierrc` with custom java options and add a not prettified java file to make sure it working?

I had to disable prettier java for some needles because the prettified code does not match the expected needles.
I prefer to merge my branch before removing prettierJava switch completely, I don't want to deal with that test.

**Comment by avdev4j** [comment]
hi @mshima 
I've just added a new tests which override App, Common and Server generators through a blueprint and test if .prettierrc is present and if it's applied as expected. WDYT ?

This is what we can do:
- You finish you work on your branch
- I open a new PR with the bug fix and the tests
- Close this one and postpone removing --prettier-java totally

I suppose I don't need to wait for your branch to be merge to open and merge mine since I add prettier-java option in my test (and you would remove it after)

**Comment by mshima** [comment]
> hi @mshima
> I've just added a new tests which override App, Common and Server generators through a blueprint and test if .prettierrc is present and if it's applied as expected. WDYT ?

I found the bug I was trying to find with the test I asked. It's not easily fixed =\\.
```
echo > .prettierrc
jhipster --defaults --prettier-java
```
The source will be generated and there will be diff (git pre-hook commit applied prettier correctly).

At the normal test I did a different approach, I created a side-by-side blueprint that overrides `.prettierrc` with `tabWidth: 10` and tested the generated source with that width.

> This is what we can do:
> 
> * You finish you work on your branch
> * I open a new PR with the bug fix and the tests
> * Close this one and postpone removing --prettier-java totally

Looks good, the test can be dropped.

> I suppose I don't need to wait for your branch to be merge to open and merge mine since I add prettier-java option in my test (and you would remove it after).
> 
> Indeed, we should mark `--prettier-java` option as dreprecated as soon as possible and remove it 7+ releases (when we will be trustful).

I think we can drop prettier java flag.

> Also what do you think about print the error object instead of error.message in prettierTransform ? In my case the error was undefined and I struggled a bit to find the reason.

Just remembered that the correct approach is to call the callback with the error instead of throwing.
Since it's running at a queued function, the process will die otherwise.

**Comment by avdev4j** [comment]
So, we should merge https://github.com/jhipster/generator-jhipster/pull/12114 and I'll do a rebase and remove the blueprint test.

**Comment by avdev4j** [comment]
Since you PR has been merged @mshima I trust you to review mine if all go green :D

**Pull request merged**
