### PR TITLE
Fixed syntax error when parsing ingressType option

### LINKED ISSUE #15578: string literal is expected
##### **Overview of the issue**

Related to JDL - deployment, when I specify ingressType as nginx, it shows this 'Error: Error during import-jdl: A string literal is expected, but found: "nginx"
	at line: 9, column: 16'

##### **Motivation for or Use Case**

I cannot generate script for deployment of kubernetes

##### **Reproduce the error**

deployment {
  deploymentType kubernetes
  directoryPath "../../"
  appsFolders [notification]
  dockerRepositoryName "registry.cn-shanghai.aliyuncs.com/jhipster"
  serviceDiscoveryType no
  istio true
  kubernetesServiceType Ingress
  ingressType  nginx
  kubernetesNamespace jhipster
  ingressDomain "app-api.jhipster.com"
}

just import this jdl

##### **Related issues**

N/A

##### **Suggest a Fix**

N/A

##### **JHipster Version(s)**
7.1.0

##### **Browsers and Operating System**

MacOS

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by MathieuAA**
Fixes #15578

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [X] Tests are added where necessary
- [X] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [X] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@MathieuAA according to documentation https://www.jhipster.tech/jdl/deployments, ingressType should be initialized by default with nginx for kubernetes deployment.
So it is missing initialization here: https://github.com/jhipster/generator-jhipster/blob/main/jdl/jhipster/deployment-options.js#L109

**Comment by MathieuAA** [comment]
The docs should be updated then: the `ingressType` is used when the `kubernetesServiceType` is set to `Ingress`.
The default for `kubernetesServiceType` is `LoadBalancer`, not `Ingress`. That's why it has no defaults.

**Comment by MathieuAA** [comment]
@DanielFran thanks for the review, I've just created a PR to change the doc. WDYT?

**Comment by DanielFran** [comment]
@MathieuAA looks good!

**Comment by MathieuAA** [comment]
thanks @DanielFran!

**Pull request merged**
