### PR TITLE
Containerize microservice and gateway applications

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/2988
All changes:
- all docker-compose files use v2 version, so you need docker 1.9+ and compose 1.6+
- gateway and microservice can now be easily containerized:
    - `mvn package docker:build -Pprod -DskipTests=true`
    - `./gradlew -Pprod bootRepackage -x test buildDocker`
- gateway and microservice apps generate 4 new files. As always, these files are here for samples, but can be used directly:
    - src/main/docker/app.dev.yml : start microservice/gateway app with registry in dev profile
    - src/main/docker/app.noregistry.prod.yml : start microservice/gateway app with registry in prod profile
    - src/main/docker/app.dev.yml : start microservice/gateway app without registry in dev profile
    - src/main/docker/app.noregistry.prod.yml : start microservice/gateway app without registry in prod profile

### CODE REVIEW

**Comment by PierreBesson** [comment]
:+1: This is exactly what we need to provide a docker workflow. The maven/gradle plugin are good but the only problem I see is that we don't yet provide a docker registry to store those images but it is not clear if it is really our job to provide it...

About, the noregistry options. From a previous discussion with @gmarziou, I was hoping that we could create either a standalone profile or activate registry discovery only if the config server is found. If we can do this, it will simplify the dependency on the registry. I will do some tests today to see if it's feasible.

**Comment by pascalgrimaud** [comment]
The `app.noregistry.dev.yml` and `app.noregistry.prod.yml` files are used to start the microservice app, without starting registry. because we suppose a registry is already started. Inside these files, external_link to registry is used.

I do it for playing with stop / start every microservices, without stopping registry. I don't know if I'm clear enough ?

But you're right, there are still some work to do with registry (volumes for config)

What I managed to do :
- create **gateway app**, package and start container : `app.dev.yml` (registry + gateway)
- create **microservice mysql app**, package and start container : `app.noregistry.prod.yml` (mysql + microservice)
- create **microservice no database app**, package and start container : `app.noregistry.prod.yml` (microservice alone)
- create **microservice mongo app**, package and start container : `app.noregistry.prod.yml` (mongo + microservice)
- create **microservice psql gradle app**, package and start container : `app.noregistry.prod.yml` (psql + microservice)

Everything work fine, with 9 containers running!

**Comment by PierreBesson** [comment]
I see ! So it will start the registry only if it is not already started, otherwise it will use the existing registry docker instance. Is this statement correct ?

About the config volume for the registry, I think it would be kind of bad to put it in the app itself as it is supposed to be shared between multiple app. The solution would be to use a git repository as the config server source as this is the correct way of using the config server. BTW, I already have a git server running in docker, I will push it to my demo repository, so you can see if it is a good solution. But in my opinion it is not as simple to use as using github.

Anyway, great work, I will integrate it in my demo as soon as it is merged.

**Comment by jdubois** [comment]
Looks good to me, let's merge this and start to have fun with Docker Compose v2 :-)

Another thing that we must test (no idea if that works!) is that we can scale microservices and that they use the same services.
For example, if `app1` uses database `mysql1`, doing a `docker-compose scale app1=2` makes 2 instances of `app1` which are both linked to the same `mysql1` database.

**Comment by PierreBesson** [comment]
@pascalgrimaud You have really done some amazing work :+1: ! 
The only thing that bother me is that the mvn build phase is a pre-requisite and you don't make use the 'build' feature in docker-compose. I guess for advanced docker users it is good as it is more flexible (the images are available locally and you can compose them from their image name). However I kind of liked the idea of building from a `docker-compose up` and then disposing of the images with a `docker-compose down`.

Starting tomorrow I will start integrating with what you have done to my demo. I especially like what you did with the registry, it really is the most elegant solution.

**Comment by pascalgrimaud** [comment]
@jdubois : I have to remove the `container_name` and the `docker-compose scale` works fine!!

docker-compose-scale

**Comment by pascalgrimaud** [comment]
I agree with you @PierreBesson ; it's a different approach. I personally prefer to have all images ready before launching docker-compose:
- mvn package and docker:build
- start docker-compose files
- stop, write another, start with same image without rebuild

I think a docker-compose file with build is only for dev

We can, of course, have different docker-compose files => one with build, one without build
But, too much files will confuse our users, unless it's very well documented

**Comment by PierreBesson** [comment]
@pascalgrimaud, You have convinced me, I guess I will need to adapt my workflow so that build is only done with maven and docker-compose only used to "compose" the available images.

**Comment by PierreBesson** [comment]
@pascalgrimaud 
After some testing I realized that the "noregistry" separation is kind of useless as the same result can be achieved by composing the registry.yml and app.noregistry.yml together.
The following commands are doing the same thing:
* `docker-compose -f app.dev.yml up`
* `docker-compose -f registry.yml -f app.noregistry.dev.yml up`
Am I missing something here ? But if not can we consider reducing the number of compose files.

**Comment by pascalgrimaud** [comment]
Mhhh let's discuss, I did it very fast this last weekend, so maybe I was wrong.

Try this :
1) console1 gateway : `docker-compose -f app.dev.yml up`
2) console2 microservice : `docker-compose -f app.dev.yml up`
3) check all is OK
4) console2 : ctrl+c to stop microservice => it stopped the registry too, so gateway doesn't work anymore

Why I did this:
1) console1 gateway : `docker-compose -f app.dev.yml up`
2) console2 microservice : `docker-compose -f app.noregistry.dev.yml up`
3) check all is OK
4) console2 : ctrl+c to stop microservice => the registry is not stopped

But I'm ok, there is too much docker-compose files. Maybe remove app.dev.yml
Start with registry : `docker-compose -f registry.yml -f app.noregistry.dev.yml up` (didn't test it)
Start without registry : `docker-compose -f app.noregistry.dev.yml up`
If it works, we can safely remove `app.dev.yml` and rename `app.noregistry.dev.yml` to `app.dev.yml`

**Comment by deepu105** [comment]
Yes guys too many configs will be confusing actually. can we have a single
default config that covers most common case?

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
@pascalgrimaud, I tried it, it works as we want ! It seems we won't need these noregistry docker-compose after all. I will let you test it yourself when you have time.

@deepu105, to sum it up we have:
- **registry.yml**: to start the registry, don't really need to be here but it's convenient to have it not to far away.
Maybe we can put it only on the gateway.
- **dev/prod.yml**: to start the database and or other dependent services, this is itself extended by app.dev.yml, meaning that launching app.dev.yml will automatically take care of setting up the database.
- **app.dev/prod.yml**: this describes how to launch our app in the docker container and link it with the registry. Maybe these files could be located somewhere else so as not to confuse users.

Another possibility would be to change the name so that it is more explicit of what it does (something like prod.yml -> prod-dependencies.yml).

**Pull request merged**
