### PR TITLE
Add createDatabaseIfNotExist=true to the MySQL connection String

### PR DESCRIPTION
**Pull request by qmonmert**
Fix issue #10831 

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by qmonmert** [comment]
@pascalgrimaud you merged ? tests are KO ?

**Comment by pascalgrimaud** [comment]
no, it's ok :)

**Comment by jdubois** [comment]
Thanks a lot @qmonmert !! Just after your impressive performance at the 10k this week-end?

**Comment by qmonmert** [comment]
@jdubois thanks, yes just after the race :)

**Pull request merged**
