### PR TITLE
Fix NPE when map users without Authorities - Improve UserMapper

### LINKED ISSUE #8899: Throws NPE when mapping using UserMapper
##### **Overview of the issue**

When calling `UserMapper::userDTOToUser` with a `UserDTO` with `authorities` set to `null` and throws a `NullPointerException`.

##### **Motivation for or Use Case**

`NullPointerException` - enough said...

##### **Reproduce the error**

Call `UserMapper::userDTOToUser` with a `UserDTO` with `authorities` set to `null`.

##### **Suggest a Fix**

`UserMapper::authoritiesFromStrings` doesn't consider a `null` input - either ensure no `null` comes this way or handle it here.
 
##### **JHipster Version(s)**

`generator-jhipster@5.7.0`

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "my.app.myapp"
    },
    "jhipsterVersion": "5.7.0",
    "applicationType": "monolith",
    "baseName": "core",
    "packageName": "my.app.myapp",
    "packageFolder": "my/app/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "otherModules": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.2 (Apple Git-113)

node: v8.12.0

npm: 6.4.1

Docker version 18.09.0, build 4d60db4

docker-compose version 1.23.1, build b02f1306

##### **Browsers and Operating System**

Irrelevant.

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by avdev4j**
Fix the user mapping by adding  : 
- Unit Tests in separate classes
- Improve code coverage
- Improve code to be more clean code
- Add "null" cleaning for cassandra and couchbase
- Move userFromId() test from UserResourceTest to new UserMapperTest

fix #8899 

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
@avdev4j can you put an understandable title to this PR ?

**Comment by avdev4j** [comment]
My bad !

**Comment by jdubois** [comment]
Merging this as there are unit tests in the code, so that should be OK

**Comment by jdubois** [comment]
Thanks @avdev4j !

**Pull request merged**
