### PR TITLE
Switch Main(S)CSS to Global(S)CSS

### PR DESCRIPTION
**Pull request by avdev4j**
The JHipster API provide functions to add style to css and scss files. 
But the files targeted are named main.css and main.scss.

As I can see 'main.css' and 'main.scss' is no longer existing and are replaces by 'global.css' and 'global.scss'.

I suggest to switch all 'main' references to 'global'. (needle, files references and needles).

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
Please check if there is a difference in name for React and Angular

Thanks & Regards,
Deepu

**Comment by avdev4j** [comment]
Update:
I fixed the SCSS file path `${CLIENT_MAIN_SRC_DIR}scss/main.scss` to `${CLIENT_MAIN_SRC_DIR}content/css/global.css`.

@deepu105 
These functions can't be used with React option. Related to the jsdoc:

> /**
     * Add new css style to the angular application in "global.css".
     * /

For React files are app.scss/app.css and needles are `jhipster-needle-css-add-main` in both cases.

There is no functions for adding style in react css.

**Comment by deepu105** [comment]
ok

Thanks & Regards,
Deepu

**Comment by avdev4j** [comment]
I'm not a react expert but I think we can have same names and needles for both react and angular.
Otherwise maybe should we adding functions for react? (not fan of this).

**Comment by avdev4j** [comment]
Finally I added 2 new functions to add styles to react app.
react css files already have needle. 2 possibilities: delete them or add method to use them. What do you think about ?

I wonder if we should made the API easier to use for example avoid duplicate code and put some code out from generator-base to a specific module.

develop blueprint could be more easier.

**Comment by deepu105** [comment]
I wanted to sync the names but lack of time. If you are willing to PR will
be happy to accept it. Its nice to have same names and structure

Thanks & Regards,
Deepu

**Comment by avdev4j** [comment]
I could do it, or waiting for this #9082 PR ?

**Comment by avdev4j** [comment]
Thanks to @DanielFran and @pascalgrimaud for validated the  #9082 PR.
Now I can do this one.

**Comment by avdev4j** [comment]
The #9151 replace this one.

I close this PR.

**Pull request closed without merging**
