### PR TITLE
Travis: java misconfigured

### PR DESCRIPTION
**Pull request by pascalgrimaud**
It should fix https://github.com/jhipster/generator-jhipster/issues/4602

### CODE REVIEW

**Comment by jdubois** [comment]
Great, looks like it's working!!!
I'm merging this, and re-launch the failed builds, so everything should be OK when I arrive at work!

**Comment by pascalgrimaud** [comment]
@jdubois : relaunch the failed builds won't work -> all PR need to fetch + rebase master

**Comment by jdubois** [comment]
Oh yes, my bad...

**Comment by pascalgrimaud** [comment]
FYI, all builds are OK except the OAuth2:
- all builds: https://travis-ci.org/pascalgrimaud/generator-jhipster/builds/181260138
- OAuth2: https://travis-ci.org/pascalgrimaud/generator-jhipster/jobs/181260153

It is clearly not our fault, as the OAuth2 configuration works well.

A quick solution would be to use the old version of Travis, with `group: deprecated` but I think we can wait and test the next release tomorrow morning US/Eastern: https://docs.travis-ci.com/user/build-environment-updates/2016-12-06/

**Comment by jdubois** [comment]
Well, for OAuth2, I don't know. I spent a couple of hours today to try to find out what's happening, and that's really strange.

- I can't reproduce the issue on my laptop
- But if you look at the log it's a Spring misconfiguration (there's a bean that is not configured), so that looks like our fault, and we should be able to reproduce this
- The Maven tests work on Travis, so the Spring bean is configured there - it just makes no sense: the tests pass, but you can't start the app...

**Comment by pascalgrimaud** [comment]
I'm pretty sure it comes from Travis, as I can't reproduce on my machine too.

When using `group: deprecated` which is the old Travis image, the OAuth2 build is OK:
https://travis-ci.org/pascalgrimaud/generator-jhipste

When using the current, OAuth2 build failed.

I wonder if I should PR immediatly this change or wait the new Travis release tomorrow?

**Comment by jdubois** [comment]
In that case Travis is badly broken!!! I can't understand why it would trigger a misconfigured Spring bean in just one specific part of one specific build, when that works everywhere else!
Yes can you PR the change? We have too many broke builds at the moment, and I'm not confident at all with Travis... Then we'll see tomorrow if we can upgrade.

**Pull request merged**
