### PR TITLE
Embedded entities don't need manual fetch.

### PR DESCRIPTION
**Pull request by mshima**
Fixes https://github.com/jhipster/generator-jhipster/issues/18017

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@tchlyah Can you confirm it fixes your issue please?

**Comment by tchlyah** [comment]
> @tchlyah Can you confirm it fixes your issue please?

Sorry for my late response. Yes I confirm that it is working perfectly.

Can you please quickly do a maintenance release with this fix and https://github.com/jhipster/generator-jhipster/pull/18007 ? I would much appreciate it!

**Comment by DanielFran** [comment]
@pascalgrimaud ?

**Comment by pascalgrimaud** [comment]
I won't have time until this friday, unless @deepu105 wants to take care of it :)

**Comment by deepu105** [comment]
I can try 😜

**Pull request merged**
