### PR TITLE
Merge shared common module with shared module in Angular

### PR DESCRIPTION
**Pull request by kaidohallik**
Currently there are 3 shared modules in hierarchy under `shared` folder. It makes it too complex. This PR simplifies shared modules hierarchy, removes one level. If some component, directive or pipe seems common enough then this can be moved to `ng-jhipster` library.

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by kaidohallik** [comment]
@deepu105 Do you think this simplification (reducing shared modules hierarchy to 2 levels) is good or is it better to proceed with 3 level hierarchy of shared modules for some reason?

**Comment by deepu105** [comment]
@kaidohallik originally this separation was due to some issues like cyclic dependencies and tree shaking, but if this doesn't cause any issues anymore, I think its fine

**Comment by kaidohallik** [comment]
@deepu105 thanks for the feedback. While testing this PR I didn't encounter any problems and CI passed. So I believe that this PR is ready for merge.

**Comment by vishal423** [comment]
thanks @kaidohallik

**Pull request merged**
