### PR TITLE
Update to latest gradle version

### LINKED ISSUE #1445: upgrade: Gradle 2.4 upgrade
Gradle 2.4 is released, when is the update planned?

### PR DESCRIPTION
**Pull request by atomfrede**
Fix #1445

### CODE REVIEW

**Comment by thiagogcm** [comment]
It's not compiling anymore. Is that just with me ?

**Comment by deepu105** [comment]
awesome, I read that Gradle 2.4 is 30% faster on their blog

**Comment by atomfrede** [comment]
@thiagogcm Just generated a fresh application and both ``./gradlew build`` and ``./gradlew bootRun`` works fine. My config:

```
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "rememberMeKey": "fe72d158483d25a389eb616a3145b389d58a39a0"
  }
}
```

**Comment by deepu105** [comment]
The same above failed for me as well on windows

here is the debug trace
```

19:43:52.956 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
19:43:53.016 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':c
ompileJava'
19:43:53.023 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :compileJava FAILED
19:43:53.033 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :compileJava (Thread[main,5,main]) complet
ed. Took 43.369 secs.
19:43:53.050 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finishe
d, busy: 43.369 secs, idle: 0.024 secs
19:43:53.075 [ERROR] [org.gradle.BuildExceptionReporter]
19:43:53.082 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
19:43:53.088 [ERROR] [org.gradle.BuildExceptionReporter]
19:43:53.093 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
19:43:53.099 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':compileJava'.
19:43:53.106 [ERROR] [org.gradle.BuildExceptionReporter] > invalid source release: 1.8
19:43:53.113 [ERROR] [org.gradle.BuildExceptionReporter]
19:43:53.118 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
19:43:53.122 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
19:43:53.127 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:43:53.132 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
19:43:53.136 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:43:53.141 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 56.204 secs
19:43:53.146 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).

```

stack trace

```
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> invalid source release: 1.8

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.
java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46
)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskEx
ecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExec
uter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.j
ava:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.j
ava:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecut
or.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecut
or.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:
51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter
.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExe
cuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExe
cuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:23
7)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:21
0)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.IllegalArgumentException: invalid source release: 1.8
        at com.sun.tools.javac.main.RecognizedOptions$GrumpyHelper.error(RecognizedOptions.java:88)
        at com.sun.tools.javac.main.RecognizedOptions$9.process(RecognizedOptions.java:348)
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:242)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:199)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:68)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.createCompileTask(JdkJavaCompiler.java:59)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:44)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler
.java:101)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34
)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25
)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:137)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:91)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(A
nnotationProcessingTaskFactory.java:243)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(Annota
tionProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(Ann
otationProcessingTaskFactory.java:230)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(Annota
tionProcessingTaskFactory.java:208)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.j
ava:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.
java:61)
        ... 49 more


BUILD FAILED

Total time: 25.43 secs
```

**Comment by atomfrede** [comment]
Looks like an invalid ``JAVA_HOME``. Will need to check it on windows (I'm using linux...)

**Comment by deepu105** [comment]
@atomfrede Yes I have jdk 7 in Java_home but it was working with Gradle 2.3 with Java8 source, is that possible?

**Comment by atomfrede** [comment]
Sounds strange to mee. Do you have jdk 8 installed elsewhere?

**Comment by deepu105** [comment]
yes I have jre 8 in x86 and jdk 7 in x64

**Comment by atomfrede** [comment]
you have *jre* 8 or *jdk* 8? If you only have a runtime environment its strange you could compile with gradle 2.3

**Comment by deepu105** [comment]
ya its strange, i had only jre 8, i didnt notice earlier, not sure if all along classes were from compiled cache(i was doing mostly front end stuff and hardly any backend change). anyway ill try changing java_home to jdk 8 and try

**Comment by thiagogcm** [comment]
@atomfrede  my build get stuck. This is part of what i got with ./gradlew build --debug

12:58:11.691 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: HEAD /snapshot/org/eclipse/jetty/jetty-webapp/9.2.9.v20150224/jetty-webapp-9.2.9.v20150224.pom HTTP/1.1

12:58:11.895 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 404 Not Found

12:58:11.896 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection 0.0.0.0:53888<->54.210.243.107:80 closed

12:58:11.896 [DEBUG] [org.apache.http.impl.conn.PoolingClientConnectionManager] Connection released: [id: 127][route: {}->http://repo.spring.io][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 10]

12:58:11.896 [INFO] [org.gradle.internal.resource.transport.http.HttpClientHelper] Resource missing. [HTTP HEAD: http://repo.spring.io/snapshot/org/eclipse/jetty/jetty-webapp/9.2.9.v20150224/jetty-webapp-9.2.9.v20150224.pom]

**Comment by thiagogcm** [comment]
nevemind.. after a HUGE amount of time it's running ok

**Comment by jdubois** [comment]
Yes, I had a the same issue: Gradle takes a very long time to set up. It's much slower than Maven, but I guess it's how the tool works.

**Comment by deepu105** [comment]
mine was JAVA_HOME issue. Damn never noticed that i had jdk 7 on path. Still baffled how my java 8 apps were buit by Gradle 2.3 

@jdubois . Yes Gradle is very slow in some machines for me also,The initial setup takes ages to finish checking all dependency and it takes nearly 5 minutes to compile classes alone if there is a single java file change. hope it improves with 2.4

**Comment by deepu105** [comment]
Not much of an improvement I guess :(

here is a profile snapshot with Gradle 2.4
image

image

**Comment by atomfrede** [comment]
Yes, strange initial setup, after a fresh created project takes very long (during dependency resolution for me I think). Afterwards normal builds, after changing some classes, are quite fast here:
screenshot from 2015-05-09 08-32-50

**Pull request merged**
