### PR TITLE
Remove finals that are now implicit

### PR DESCRIPTION
**Pull request by henri-tremblay**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by murdos** [comment]
Hi. Could you just explain why these finals are now implicit?
I don't get it.

**Comment by Blackdread** [comment]
No reason to remove.
I did not check all the code but it is not used in a lambdas so it is not implicit, anyone could eventually change the value later without the final

**Comment by henri-tremblay** [comment]
I misread then. My real reason to remove it is that adding final to a local variable is not really useful and adds unnecessary noise to the code. Currently, JHipster seems to adopt a coding style without these unnecessary finals. They are present only in these two places. I recommend to remove them.

I will change the commit comment though.

**Comment by jdubois** [comment]
Yes, our usual code style is that we remove that kind of "noise".

**Pull request merged**
