### PR TITLE
Add equals/hashCode to criterias

### PR DESCRIPTION
**Pull request by Blackdread**
My first contribution for the generator, I am not familiar with ejs.
I try to fix issue: [#8049](https://github.com/jhipster/generator-jhipster/issues/8049), could someone check the code I put and correct me if this is wrong?
I do not know how to launch tests (except yarn test but fails on my pc) and how to generate with the ejs.
Thanks

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

@deepu105 @lmbai @PierreBesson

### CODE REVIEW

**Comment by Blackdread** [comment]
@DanielFran All tests are green on travis, only one is red but the error shown should be unrelated to my changes.

**Comment by DanielFran** [comment]
@Blackdread Restarted the failing test, let see...

Yesterday I see lot of errors with criteria classes telling that it was missing a ';'.
Strange...

**Comment by DanielFran** [comment]
Seems OK now!

**Comment by pascalgrimaud** [comment]
Don't know what happens here with Travis builds, but there are still lot of errors, in last release v5.3.3

**Comment by jdubois** [comment]
There was some error with the M2 cache, I'm having a look

**Pull request merged**
