### PR TITLE
Fix Time

### PR DESCRIPTION
**Pull request by bondareko**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
- closing the pull request
- stopping Travis build
- reported to GitHub

**Comment by jdubois** [comment]
what's going on here???

**Comment by pascalgrimaud** [comment]
@jdubois : I don't know, it is a strange PR, but after looking his profile, he did a similar pull request `Fix time` to 15 other repositories, so I think he tried to do something...
So that's why I reported him to GitHub

**Comment by jdubois** [comment]
@bondareko this is definitely not cool, we have better things to do!!!!! I filled an abuse report to GitHub.

**Pull request closed without merging**
