### PR TITLE
Fixed #16244 load data issue for date columns

### LINKED ISSUE #16244: Webflux:  issue with liquibase + PostgreSQL
##### **Overview of the issue**
cannot authenticate after jhipster generation of Webflux postgreSQL project

```
org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [SELECT * FROM jhi_user u LEFT JOIN jhi_user_authority ua ON u.id=ua.user_id WHERE u.login = :login]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42P01] relation "jhi_user" does not exist
```

##### **Motivation for or Use Case**

I'd expect the /authenticate endpoint to work out of the box

##### **Reproduce the error**

Initialise Monolith WebFlux PostgreSQL

##### **Suggest a Fix**
com.mycompany.myapp.web.rest.UserJWTController.lambda$authorize$2(UserJWTController.java:40)

##### **JHipster Version(s)**

7.1.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "pgreactive",
    "jhipsterVersion": "7.1.0",
    "skipClient": true,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1631269877243,
    "serviceDiscoveryType": false,
    "reactive": true,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "no",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true,
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1631270352000,
    "entities": ["BarProperty"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BarProperty {
  legId String
  priority Integer
  receivedAt ZonedDateTime
  field String
  value String
  issuedAt ZonedDateTime
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

git version 2.33.0

node: v16.8.0

npm: 7.21.0

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entities

##### **Browsers and Operating System**

Mac OS Big Sur 11.5 - not browser related

### PR DESCRIPTION
**Pull request by yuvarajsanjeevi**
Fix #16244

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by yuvarajsanjeevi** [comment]
Recently enabled usePreparedStatements="true". So Liquebase tries to set the data type for each column and supported load data types are 
https://github.com/liquibase/liquibase/blob/v4.4.3/liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java#L876.

since there is no DateTime load data type in liquibase tries to set it as a string. hence the issue happens
for the date, the supported load column type is 'date' for all types of dates and times.

So changed the load data column type to return 'date'.

**Review by DanielFran — APPROVED** [review]

**Comment by mshima** [comment]
Why our CI didn’t catch the problem?
https://github.com/jhipster/generator-jhipster/blob/8642ee8f79ecc3a0b5308c8a4c1daf508561bdf0/test-integration/samples/.jhipster/FieldTestEntity.json#L144-L170

**Comment by yuvarajsanjeevi** [comment]
@mshima This issue happens only on liquibase load the fake data from CSV and during the insertion of date type columns for postgress. Please find below the JDL file used for reproducing this issue 

application {
  config {
    applicationType monolith
    authenticationType jwt
    baseName pgreactive
    blueprints []
    buildTool maven
    cacheProvider no
    clientPackageManager npm
    clientTheme none
    databaseType sql
    devDatabaseType postgresql
    dtoSuffix DTO
    enableHibernateCache false
    enableSwaggerCodegen false
    enableTranslation false
    jwtSecretKey "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons"
    languages [en, fr]
    messageBroker false
    nativeLanguage en
    otherModules []
    packageName com.mycompany.myapp
    prodDatabaseType postgresql
    reactive true
    searchEngine false
    serverPort 8080
    serviceDiscoveryType false
    skipClient true
    skipServer false
    skipUserManagement false
    testFrameworks []
    websocket false
    withAdminUi true
  }
  entities BarProperty
}

entity BarProperty {
  legId String
  priority Integer
  receivedAt ZonedDateTime
  field String
  value String
  issuedAt ZonedDateTime
}

**Comment by yuvarajsanjeevi** [comment]
@mshima I would like to mention one more point that is we are running liquibase in the asynchronous model even liquebase failure or success. the application has started successfully

**Comment by mshima** [comment]
> I would like to mention one more point that is we are running liquibase in the asynchronous model even liquibase failure or success. the application has started successfully

That's what I was thinking https://github.com/jhipster/generator-jhipster/issues/11949.
But should have appeared in our log: https://github.com/jhipster/generator-jhipster/runs/3576891944.
That build has no pending tests in E2E test, so liquibase was successfully loaded.
Does this problem is dependent on postgres? It happens with h2?

**Comment by yuvarajsanjeevi** [comment]
I have tested MySQL, Postgres,h2, and the problem happen only in Postgres. 
**h2 working fine**

**Comment by mshima** [comment]
Great thanks @yuvarajsanjeevi.
Probably we don't have a Postgresql test with dev profile.
I don't think it's worth to add it.

**Comment by yuvarajsanjeevi** [comment]
Thanks all,

I claim the bounty at https://opencollective.com/generator-jhipster/expenses/50024

**Comment by pascalgrimaud** [comment]
@yuvarajsanjeevi : approved. Thanks for  your work !

**Pull request merged**
