### PR TITLE
[vue] Readd path to webpack.dev.js

### PR DESCRIPTION
**Pull request by mshima**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@mshima : is there a bug in v7.0.1 with Vue app ?

**Comment by mshima** [comment]
@pascalgrimaud no, the variable was removed between the PR creation and merge.

**Comment by mshima** [comment]
This PR I’m referring to https://github.com/jhipster/generator-jhipster/pull/14561.

**Comment by pascalgrimaud** [comment]
Thanks for the info !

**Pull request merged**
