### PR TITLE
Fix JWT-Token is not given to Swagger-UI (#7444)

### PR DESCRIPTION
**Pull request by eruixma**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
OMG we still have one of those... Not the first time we have this error, thanks for spotting it!

**Comment by jdubois** [comment]
Oh and congrats for your first contribution!

**Comment by eruixma** [comment]
thanks:wink:

**Comment by PierreBesson** [comment]
I don't understand what was the bug, and what is the fix. @eruixma Can you explain what you did ?

**Comment by pascalgrimaud** [comment]
@PierreBesson : in the `index.html` file for Swagger
- for Angular, you need to use `<%=jhiPrefixDashed %>-authenticationtoken` -> must be lowercase
- but for React, it's `<%=jhiPrefixDashed %>-authenticationToken`

This PR fix the issue for Swagger+React, but broke the Swagger+Angular
@agaspardcilia fixed the problem after investigating the `ngx-webstorage`repo.
Here the code: https://github.com/PillowPillow/ng2-webstorage/blob/master/lib/helpers/keyStorage.ts#L28-L31
Here the fix https://github.com/jhipster/generator-jhipster/pull/7631

**Comment by PierreBesson** [comment]
OK now I understand. If this is working like that then no problem. Well done @agaspardcilia.

**Pull request merged**
