### PR TITLE
Updated the JDL export subgen

### PR DESCRIPTION
**Pull request by MathieuAA**
Now takes into account the output file

Fixes https://github.com/jhipster/jhipster-core/issues/391

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Strange... what happened with the CI @MathieuAA ?

**Comment by MathieuAA** [comment]
@pascalgrimaud Bought a ticket for Devoxx and will come back next week I think... I don't know. This is annoying as this PR is quite simple and doesn't do much :(

**Comment by pascalgrimaud** [comment]
Yes agree, the failures are not related to your changes
Have a good week at Devoxx :)

**Comment by MathieuAA** [comment]
@pascalgrimaud I'm trying something, don't worry if you see strange things. But if you merge the PR, don't forget to select the "squash" option instead of the default one.

**Pull request merged**
