### PR TITLE
Fixed password menu icon from 'clock' to 'lock' and completed 'uz-cyr' language support

### PR DESCRIPTION
**Pull request by javasparx**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by javasparx** [comment]
It was always LOCK icon in password menu item. Reject if I am wrong.

**Comment by pascalgrimaud** [comment]
you're totally right !
so funny, we didn't see it all this time !

Could you do the same for React too plz ?
And if possible, for Vue.js too -> if not, I'll do it at https://github.com/jhipster/jhipster-vuejs

**Comment by javasparx** [comment]
I think I did the fix for React too, but please check it, because we do not use React at all.

**Comment by clement26695** [comment]
I think you have to replace faClock by faLock in this file too :  generators/client/templates/react/src/main/webapp/app/config/icon-loader.ts.ejs

**Comment by javasparx** [comment]
@clement26695 , I did as you suggested.

**Comment by pascalgrimaud** [comment]
thanks @javasparx !

**Pull request merged**
