### PR TITLE
use hand cursor on sortable header

### PR DESCRIPTION
**Pull request by ctamisier**
(like in angular js)

### CODE REVIEW

**Comment by deepu105** [comment]
thanks

**Comment by deepu105** [comment]
please add [ci skip] to you commit for such trivial changes that doesnt affect builds

**Comment by tientq** [comment]
You should add [ci skip] to contribute guidelines, don't you?

**Comment by deepu105** [comment]
@tientq nope as its easy for people not to read it properly and end updating ci skip for stuff that might break build.

**Comment by tientq** [comment]
Ok, you are right.

**Pull request merged**
