### PR TITLE
Remove whitespace and set static on ProfileInfoVM

### PR DESCRIPTION
**Pull request by FireWolf2007**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Travis failed but it's not your fault (it got a timeout), so I'm merging this - thanks a lot @FireWolf2007 !

**Comment by PierreBesson** [comment]
I don't understand, why is the ProfileInfoResource in out current master even though I went to great lenght to remove it and put the data in /info ?

**Comment by jdubois** [comment]
@PierreBesson I have no idea!!

**Comment by ruddell** [comment]
@PierreBesson You didn't remove the file ProfileInfoResource.java in your PR #7050, it isn't copied into projects anymore though

**Comment by PierreBesson** [comment]
You are right @ruddell it seeems like it was a bad rebase on my part.

**Comment by jdubois** [comment]
Then if it's not used at all, shouldn't we remove it? @PierreBesson do you have time to take a look? Or I'll it, no problem

**Comment by PierreBesson** [comment]
I have submitted the PR.

**Comment by jdubois** [comment]
OK good! Thanks everyone

**Pull request merged**
