### PR TITLE
Azure DevOps

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix https://github.com/jhipster/generator-jhipster/issues/8337

I duplicate a lot of files in `travis` to `test-integrations` folder.
Once this PR is merged, I will rework Travis to use these same scripts and delete `travis` folder.

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Awesome work! I guess I understand what you mean, so I'm merging this

**Comment by pascalgrimaud** [comment]
yes @deepu105 : the goal is more configs
For now, I just used the same config as Travis to be sure everything works fine.

@jdubois : I thing we did something wrong in the github config as the build is triggered twice, once you merged into master:
- CI build for Github
- CI build for Julien Dubois

We'll have a look this wednesday

**Comment by pascalgrimaud** [comment]
A quick check would be to see at https://github.com/jhipster/generator-jhipster/settings/hooks

We should have 2 webhooks:
- https://dev.azure.com/jhipster/_apis/public/hooks/externalEvents  (push)
- https://dev.azure.com/jhipster/_apis/public/hooks/externalEvents  (pull_request)

Is it the case?

**Comment by jdubois** [comment]
Thanks @pascalgrimaud - I only have "push", so I'm going to add "pull request" right now.

**Comment by jdubois** [comment]
Here it is now:
screenshot 2018-10-08 10 43 01

**Comment by pascalgrimaud** [comment]
Thanks @jdubois
Can you check in your fork https://github.com/jdubois/generator-jhipster/settings/hooks too ? 
You shouldn't have webhooks in your fork.

**Comment by jdubois** [comment]
Thanks @pascalgrimaud - no there is no hook on my personal fork

**Pull request merged**
