### PR TITLE
WIP - Convert upgrade sub-generator to a CLI command

### PR DESCRIPTION
**Pull request by pvliss**
As discussed in #9908 this PR converts the upgrade sub-generator to a CLI command.

The functionality has remained intact and we can discuss how to add pre-upgrade steps, e.g to modify `.yo-rc.json` and maintain backwards compatibility without upgrade errors,etc.

The main changes are:
- Converted to use mainly synchronous calls when using `shelljs` to avoid callback hell, but I would like the team's input if that is desirable. Personally I find it easier to read. Only async methods are when checking for new versions where it also makes sense to perform asynchronously. 
- Refactored `gitExec` and `isGitInstalled` methods from base gen classes:
  - Moved them to `utils.js` so they can be re-used by the upgrade command
  - Removed callback from `isGitInstalled` which now executes synchronously and returns a boolean and further simplified generator code that uses them.

**TODO:**

- [ ] Discuss how to handle pre-upgrade steps. e.g are we going to use a separate `pre-upgrade.js` file similar to `cleanup.js` or embed the code within `upgrade.js`
- [ ] ~~Should we move the execution of cleanup within the upgrade flow as well?~~ _(Removed as it is needed for manual upgrades)_
- [ ] Remove upgrade sub-generator once complete
- [ ] Upgrade [docs](https://github.com/jhipster/jhipster.github.io/blob/master/pages/upgrading_an_app.md) if necessary 

Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pvliss** [comment]
Forgot to create as draft. Changing to WIP...

**Comment by pvliss** [comment]
Fixed some issues, removed the upgrade sub-gen and added code(69b5a02) that fixes the languages issue(#9908) to show how pre-upgrade steps can work. I believe that for the moment we can leave that there and if that gets more complex move it to a separate file/class. @jhipster/developers WDYT?

In regards to @murdos's [comment](https://github.com/jhipster/generator-jhipster/issues/9908#issuecomment-502371322) and the clean up mechanism, it seems that it is currently not useful as the cleanup scripts are indeed called after the `.yo-rc.json` file has already been changed. It seems that [cleanup](https://github.com/jhipster/generator-jhipster/blob/2e86c7d575668996b5b261f470d7cddd798fc65e/generators/app/index.js#L465) should be moved before [saveConfig](https://github.com/jhipster/generator-jhipster/blob/2e86c7d575668996b5b261f470d7cddd798fc65e/generators/app/index.js#L419) but have not tested

**Comment by deepu105** [comment]
@pvliss any progress on this, do you need help?

**Comment by pvliss** [comment]
@deepu105 I had done some work but now will need to find some time to resolve the conflicts as well. Will ping you when ready. Thanks

**Comment by deepu105** [comment]
Sure

Thanks & Regards,
Deepu

**Comment by mshima** [comment]
@pvliss what about this PR?
I really don't see much benefits on converting upgrade to a cmd.
I would love to have a sync version of the isGitInstalled and gitExec.
Can you create a separated PR for them?
We should keep callback compatibility for now.

I have plans to reduce callbacks in the generators.

**Comment by pascalgrimaud** [comment]
it has been opened for a while, maybe should we close this one ? 
Then, what do you think @pvliss ?

**Comment by pvliss** [comment]
Hello guys,

Please excuse my late reply and for leaving the PR in that state for that long but I really did not have the time.
@mshima Yes, I will try to extract these a changes in a separate PR this weekend.
@pascalgrimaud If you believe that there's no interest then sure lets close it. Otherwise, I can revise it and mauybe create a new one as a lot has changed since then and I neeed to catch up :)

**Comment by pvliss** [comment]
@mshima Added PR #11319 

Closing this one as I also do not believe is necessary.

**Pull request closed without merging**
