### PR TITLE
Fix number questions

### PR DESCRIPTION
**Pull request by pascalgrimaud**
The number with question should be displayed correctly now.

### CODE REVIEW

**Comment by deepu105** [comment]
Dont merge yet. Let me take look. It should ideally work fine without this hack. There might be some other issue. Let me check

**Comment by deepu105** [comment]
@pascalgrimaud could you tell me with what combination you are seeing wrong numbers?

**Comment by pascalgrimaud** [comment]
Yes it's a hack lol!
The wrong number is displayed when we use:
- no database
- nosql
- microservice
So I remember an old version of generator and tried to do something similary

**Comment by deepu105** [comment]
No probs, ill fix take a look and fix this. I guess the problem lies some
where else

**Comment by deepu105** [comment]
@pascalgrimaud I couldnt find any numbering issue in current master. Could you plz check again, and if you see an issue could you give me the exact question combinations. There might have been an issue in numbering before but I fixed that few days back so it might be possible that you had a version before my fix

```
PS D:\Projects\test\testApp> yo jhipster                                                                                                                                    
                                                                                                                                                                            
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████                                                                                              
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██                                                                                             
        ██  ████████     ██     ███████    █████      ██     ██████    ███████                                                                                              
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██                                                                                              
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██                                                                                             
                                                                                                                                                                            
                            http://jhipster.github.io                                                                                                                       
                                                                                                                                                                            
Welcome to the JHipster Generator testv3.3.0                                                                                                                                
Application files will be generated in folder: D:\Projects\test\testApp                                                                                                     
? (1/16) Which *type* of application would you like to create? Microservice application                                                                                     
? (2/16) What is the base name of your application? testApp                                                                                                                 
? (3/16) As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8081                  
? (4/16) What is your default Java package name? com.mycompany.myapp                                                                                                        
? (5/16) Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)                                                                 
? (6/16) Which *type* of database would you like to use? No database                                                                                                        
? (7/16) Would you like to use Maven or Gradle for building the backend? Maven                                                                                              
? (8/16) Would you like to enable internationalization support? Yes                                                                                                         
? Please choose the native language of the application? English                                                                                                             
? Please choose additional languages to install (Press <space> to select)                                                                                                   
? (9/16) Which testing frameworks would you like to use? (Press <space> to select)                                                                                          
>(*) Gatling                                                                                                                                                                
 ( ) Cucumber                                                                                                                                                               
                                                                                                                                                                            
PS D:\Projects\test\testApp> yo jhipster                                                                                                                                    
                                                                                                                                                                            
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████                                                                                              
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██                                                                                             
        ██  ████████     ██     ███████    █████      ██     ██████    ███████                                                                                              
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██                                                                                              
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██                                                                                             
                                                                                                                                                                            
                            http://jhipster.github.io                                                                                                                       
                                                                                                                                                                            
Welcome to the JHipster Generator testv3.3.0                                                                                                                                
Application files will be generated in folder: D:\Projects\test\testApp                                                                                                     
? (1/16) Which *type* of application would you like to create? Monolithic application (recommended for simple projects)                                                     
? (2/16) What is the base name of your application? testApp                                                                                                                 
? (3/16) What is your default Java package name? com.mycompany.myapp                                                                                                        
? (4/16) Which *type* of authentication would you like to use? HTTP Session Authentication (stateful, default Spring Security mechanism)                                    
? (5/16) Do you want to use social login (Google, Facebook, Twitter)? Warning, this doesn't work with Cassandra! No                                                         
? (6/16) Which *type* of database would you like to use? MongoDB                                                                                                            
? (7/16) Do you want to use clustered HTTP sessions? No                                                                                                                     
? (8/16) Do you want to use WebSockets? No                                                                                                                                  
? (9/16) Would you like to use Maven or Gradle for building the backend? Maven                                                                                              
? (10/16) Would you like to use the LibSass stylesheet preprocessor for your CSS? No                                                                                        
? (11/16) Would you like to enable internationalization support? Yes                                                                                                        
? Please choose the native language of the application? English                                                                                                             
? Please choose additional languages to install (Press <space> to select)                                                                                                   
? (12/16) Which testing frameworks would you like to use? (Press <space> to select)                                                                                         
>(*) Gatling                                                                                                                                                                
 ( ) Cucumber                                                                                                                                                               
 ( ) Protractor                                                                                                                                                             
                                                                                                                                                                            
PS D:\Projects\test\testApp>                                                                                                                                                
```

**Comment by pascalgrimaud** [comment]
Oh sorry @deepu105 I wasn't clear enought.
What I was trying to do is to display clearly the last question, like old versions before 3.0.0. Here, it should be 16/16, instead of 9/16
```
? (9/16) Which testing frameworks would you like to use? (Press <space> to select)                                                                                          
>(*) Gatling                                                                                                                                                                
 ( ) Cucumber
```

So to do it, I had to increment the 1st number when some questions are not related to the configuration. For example:
```
? (6/16) Which *type* of database would you like to use? No database                                                                                                        
? (7/16) Would you like to use Maven or Gradle for building the backend? Maven
```

We'll have:
```
? (6/16) Which *type* of database would you like to use? No database                                                                                                        
? (13/16) Would you like to use Maven or Gradle for building the backend? Maven
```

But as I said, it's very minor and just for **esthetic** :nail_care:
It didn't take me too much time to do it, so let's not lost too much of your time to test / analyze.
Feel free to close if you think it will bring too much maintenance when we'll add more questions in future, I won't be angry :bird:

**Comment by deepu105** [comment]
Oh you meant that way. Actually if the numbering is not in sequence it will confuse the user more than having extra total numbers. Earlier there was an issue raised for this as well and that's why I changed from static numbering to dynamic numbering, so that numbering is always continuous no matter what combination you choose, only downside being you might see a higher total number for some options. IMO its better to keep the numbering sequential without having jumps when some option is skipped and current dynamic numbering is easier, else we have to change a lot if we want to add/remove a question. The best option to avoid the confusion with total number of question would be to just stop showing the total numbers and show just current question number. So IMO this PR would only complicate things further so we should either keep as it is today or remove the total number of question from display.

**Comment by pascalgrimaud** [comment]
As you said, don't complicate things.
Let's keep as it is today

**Comment by deepu105** [comment]
Thank you

Thanks & Regards,
Deepu

**Pull request closed without merging**
