### PR TITLE
Fix missing Elasticsearch reindex after updating User

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix https://github.com/jhipster/generator-jhipster/issues/5867

___

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
We should add a test for that

**Comment by pascalgrimaud** [comment]
Indeed, I forget to check the coverage for that.
But I'm pretty sure this new line will be covered, as the UserService is at 95.9% (thanks to your hard work!!)

**Comment by cbornet** [comment]
Yes the coverage will be the same. But adding an assertion will strengthen the test (code coverage is a lure if you don't verify anything)

**Comment by pascalgrimaud** [comment]
Again I totally agree with you @cbornet, but I think it should be in another ticket, because today, when choosing ElasticSearch, we don't have tests on api/_search in UserResourceIntTest, either Entities.

**Comment by tezcane** [comment]
I have reported this a few times, e.g. in #5541 #5542 and one other related bug which I can't find right now.  I wonder why it was ignored when I tried to fix it @jdubois

**Comment by jdubois** [comment]
Sorry @tezcane but I don't understand... Don't take it bad, we're doing this mostly on our free time (on my phone while commuting, at the moment), so we can miss stuff.

**Comment by tezcane** [comment]
@jdubois I don't take it bad, no worries.  I was always questioning myself why this fix was not needed and how it was meant by design like I was told... I brought it up so we can spark some thoughts on not losing out on bug fixes in the future.  When the bug was rejected I tried adding a comment to the fact that it was left out by design (as I was told), but that was also rejected.

@pascalgrimaud Sorry, I put in wrong bug links.  I fixed it now.

**Comment by pascalgrimaud** [comment]
@tezcane : ok, your initial ticket contained a lot of item and we simply miss it sorry. That's why we always ask to open 1 ticket for 1 bug, with all description to reproduce. Better, you can to directly a PR if you are sure about the fix.

So reading this ticket https://github.com/jhipster/generator-jhipster/issues/5441 : is everything fixed ?

**Comment by tezcane** [comment]
Agreed, my first commits were a train wreck... I misread generator contributor documentation and thought PR's were preferred over opening issues first.  

#5441 everything is fixed, yes.

It is not just mentioned in #5441 though, this issue was highlighted in a few places (other bugs, PR comments, etc.). I should have followed up more maybe, but was too trusting and felt like I may be pestering my heros (yes you all are many developers heros :) ) by asking too many questions on a dead/concluded topic.

**Comment by jdubois** [comment]
@tezcane you expect too much from us :-)
we're just normal guys, doing mistakes and not totally reading their emails while commuting...

**Pull request merged**
