### PR TITLE
Setup Karma & Angular 2

### LINKED ISSUE #4302: Angular 2 Protractor & Karma migration
The protractor and Karma test cases needs to be migrated in order to be compatible with Angular2. The migration needs to be done in the client-2 subgen
Related to #3664 
@mraible hoping you would be able to help?

TODO:

- [ ] migrate karma tests for core
- [x] migrate karma tests for entity
- [x] migrate protractor tests for core
- [x] migrate protractor tests for entity

### PR DESCRIPTION
**Pull request by mohamed2a**
- I configure Karma for Angular 2
- I rewrite health spec file in TypeScript and it runs successfully
It's can help to fix #4302.

### CODE REVIEW

**Comment by deepu105** [comment]
@mraible has done a similar PR https://github.com/jhipster/generator-jhipster/pull/4760 @mohamed2a @mraible  which one should we go with

**Comment by mraible** [comment]
@deepu105 There are advantages to both. @mohamed2a's has an actual test in it. Mine integrates Karma and webpack and doesn't require listing of files in `karma.conf.js`. It also uses Istanbul for coverage, but I don't the junit reporter is working.

**Comment by deepu105** [comment]
In that case can we merge both work together @mohamed2a can you try to merge @mraible s branch into yours?

**Comment by jdubois** [comment]
Yes that would be awesome!!

**Comment by deepu105** [comment]
Btw guys I have upgraded all the npm libraries in master including webpack and have merged that here as well

**Comment by mohamed2a** [comment]
yes @deepu105 I'm working on it

**Pull request closed without merging**
