### PR TITLE
Add resource limits for Kubernetes specs

### LINKED ISSUE #10769: Add resourse limits on all generated Kubernetes specs
We do not have any resource limits on some of the spec we generate for Kubernetes. For example the MySQL deployment spec below. We should add limits to avoid starving of resourses

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-mysql
  namespace: jhipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-mysql
  template:
    metadata:
      labels:
        app: invoice-mysql
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mysql
          image: mysql:8.0.17
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: MYSQL_DATABASE
              value: invoice
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
```

### PR DESCRIPTION
**Pull request by bradsheppard**
Fix #10769

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by bradsheppard** [comment]
@deepu105 Sure! We can discuss later and lower. For testing, I used the following test plan:

For each database type (Couchbase, Elastic Search, MariaDB, MongoDB, MSSQL, MySQL, Postgres):
- Generated a project using `jhipster` and selecting the appropriate database type.
- In a separate directory, generated an associated Kubernetes project using `jhipster kubernetes` and referencing the first project.
- Deployed the generated Specs to Minikube using `./kubectl-apply.sh`. 
- Verified pods were deployed correctly using `kubectl get pods`.
- Verified resource contraints on pods were set correctly using `kubectl describe pod <pod_name>`.

For Kafka:
- Generated an project using `jhipster` and enabling Kafka message queue.
- Carried out the steps above to verify Kubernetes resources.

For Console:
- Generated a project using `jhipster`.
- In a separate directory, generated an associated Kubernetes project using `jhipster kubernetes`, referencing the first project, and enabling monitoring via Console.
- Carried out the steps above to verify Kubernetes resources.

For Console + Zipkin:
- Generated a microservice project using `jhipster`.
- In a separate directory, generated an associated Kubernetes project using `jhipster kubernetes`, referencing the first project, and enabling monitoring via Console + Zipkin.
- Carried out the steps above to verify Kubernetes resources.

**Comment by deepu105** [comment]
Needs to be tested with a microservice architecture to see if it still
works with the current default cluster config or not

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
I feel that those are good enough, maybe they could be lowered a bit. Actually it is really tricky to configure limits properly. @bradsheppard thank you for doing this work. It is good that you tried out those limits on real apps however, we would need to run load tests to see if those limits are adequate for real life usage.

**Comment by bradsheppard** [comment]
@PierreBesson No problem!

**Pull request merged**
