### PR TITLE
add a length limit for logstash-encoder forwarded stacktraces fix #3364

### LINKED ISSUE #3364: Log statements with stack trace get truncated due to Logstash 8 KB limit
##### **Overview of the issue**

When app logs an exception stack trace and the JSON encoded log statement is larger than 8 KB, Logstash is confused and truncate the statement resulting in invalid JSON fragment.

This limit is the default one in Logstash: https://github.com/elastic/logstash/issues/1505

##### **Motivation for or Use Case** 

Logs with exceptions are very important and should contain all required info for investigation while possibly optimizing the volume of data transferred to Logstash.

##### **JHipster Version(s)** 

3.0 master

##### **Reproduce the error** 

Log an error with very long text and exception:

~~~java
log.error("Very log text .....", exception );
~~~

##### **Suggest a Fix** 

logstash-logback-encoder has [few options to limit stack trace depth](https://github.com/logstash/logstash-logback-encoder#customizing-stack-traces).

In particular, the rootFirst option which prints the root cause first could be combined with maxLength in bytes.

### PR DESCRIPTION
**Pull request by PierreBesson**
Fix #3364 issue for stacktraces over 8K sent through an UDP socket.

### CODE REVIEW

**Comment by deepu105** [comment]
@gmarziou can we merge this?

**Comment by gmarziou** [comment]
I would prefer to wait for Pierre to answer my comments in issue.

**Comment by gmarziou** [comment]
Or we could merge it and then refine it later if Pierre agrees.

**Comment by PierreBesson** [comment]
@deepu105, just doing a last test to see if I need to add one more line to the config or not.

**Comment by PierreBesson** [comment]
@deepu105, @gmarziou, Stacktraces are now written in reverse order when forwarded to logstash. This does not affect regular console logging. Thanks @gmarziou for insisting on this.

**Comment by gmarziou** [comment]
Great work and it's easy to be adjusted by user if needed.

**Pull request merged**
