### PR TITLE
Update gitignore

### PR DESCRIPTION
**Pull request by marcomafessolli**
Adding directory bower_components as it is downloaded by **bower install** / **bower update** and don't need to be versioned

### CODE REVIEW

**Comment by lluiscanals** [comment]
I think that it has been discussed many times, and @jdubois is not agree with that.

**Comment by marcomafessolli** [comment]
Sorry @lluiscanals, I didn't know that it you already have discussed about it. But, as it is manage by bower, what is the purpose of versioning it?

**Comment by gzsombor** [comment]
Bower and npm is so slow, and unreliable, that it's better to put the downloaded javascript under version control.

**Comment by atomfrede** [comment]
It is a decision :) Having it inside VCS makes it possible to start right away with developing, even when you don't have npm, bower installed. So it is particulary useful for "backend only developers".

**Comment by marcomafessolli** [comment]
@gzsombor @atomfrede Thank you for the explanation.

**Comment by atomfrede** [comment]
@marcomafessolli I'll close your PR if you're ok with our explanation.

**Pull request closed without merging**
