### PR TITLE
Add support for Heroku + Gradle + PostGreSQL

### PR DESCRIPTION
**Pull request by trevorackerman**
Currently I'm able to create a JHipster project from scratch, choose Heroku, PostGreSQL, and then run yo jhipster:heroku with a successfully deployed app to Heroku.

### CODE REVIEW

**Comment by atomfrede** [comment]
Cool. Are you able to run the app in production mode on heroku? Last time I tried there was a problem when heroku detected a java/gradle app and then tried to execute grunt to minimize web resources.

**Comment by trevorackerman** [comment]
Yes, it would be great if you could clone my fork and verify it works for you also.

After cloning you'll need to go to the root of the project and run 'npm install . -g'
Then make a new JHipster project, choose gradle and PostgreSQL, then run 'yo JHipster:heroku' and you should have what you are asking about.

Try it out and let me know if it worked for you.

Cheers,
Trevor

**Comment by jdubois** [comment]
Looks good, @atomfrede when you have tested it, I will merge it.
-> @trevorackerman  can you also update the documentation on https://github.com/jhipster/jhipster.github.io ?

**Comment by atomfrede** [comment]
@jdubois Will try to test ist today, definitely tomorrow

**Comment by trevorackerman** [comment]
@jdubois, @atomfrede I will update the documentation.

Cheers,
Trevor

**Comment by atomfrede** [comment]
Sorry, didn't had time yesterday :( Will test it today

**Comment by atomfrede** [comment]
@trevorackerman Great work! Succefully deployed a sample app.
@jdubois You can merge it!

For reference, the sample app: https://atomfrede-jhipster-sample.herokuapp.com/#/

**Comment by jdubois** [comment]
Great job! This will be in our next release (Friday, normally), and I will merge the documentation when I release.

**Pull request merged**
