### PR TITLE
Update Window Title when Locale Changes fixes #2161

### LINKED ISSUE #2161: Page title is not translated after changing locale
Page title (html > head > title) is set only when the page is (re)loaded. After changing the locale title is not translated.

**Motivation:** For single page web application it is required to translate title after changing the language without reloading the page.

**JHipster Version:** 2.21.1

**Reproduce the error**
1. Generate app with angular-translation support
2. Set different values for different languages to global.title
3. Run the application and change the language.
4. Page title is not translated.

### PR DESCRIPTION
**Pull request by trevershick**
Place a watcher on $translate.use().  Whenever
it changes, call a function to update the window title.
This logic is all conditional on the enableTranslation
flag in the templates.

fixes #2161

### CODE REVIEW

**Comment by gmarziou** [comment]
Yes it's usually something to avoid, in this case I think a broadcast event could be better especially it seems to me that you could use [$translateChangeEnd](https://angular-translate.github.io/docs/#/guide/18_events) even though it may use $rootScope underneath.

**Comment by trevershick** [comment]
.on('$translateChangeSuccess') seems to be the ticket.

**Comment by gmarziou** [comment]
Yes you're right.

**Comment by trevershick** [comment]
Updated

**Comment by gzsombor** [comment]
+1, I think it's good !

**Pull request merged**
