### PR TITLE
upgrade to ng-bootstrap 4.0.0, to be fully compatible with Angular 7

### PR DESCRIPTION
**Pull request by Sebi11**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
congrats for your 1st contribution to the project @Sebi11 !!

**Comment by Sebi11** [comment]
Thank you, even if it was an easy one!

**Comment by deepu105** [comment]
@sendilkumarn did you test this? if so can you plz merge

**Comment by pascalgrimaud** [comment]
Tested it, and it works fine !

**Comment by DanielFran** [comment]
Congratulation @Sebi11 .

**Pull request merged**
