### PR TITLE
Use mapstruct in patch request

### LINKED ISSUE #14033: optimize PATCH request in v7
##### **Overview of the feature request**
make patch request better
1. move partialUpdate function to mapstruct,just like this:
```java
public interface EntityMapper<D, E> {
    E toEntity(D dto);

    D toDto(E entity);

    List<E> toEntity(List<D> dtoList);

    List<D> toDto(List<E> entityList);
    
    @Named("partialUpdate")
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void partialUpdate(@MappingTarget E entity, D dto);
}
```
2.generaoter the missing code for client in *.service.ts

##### **Motivation for or Use Case**
For first one, I want to exclude some field in PATCH request sometimes.or it's not the same for different user.it's eary to make different config in mapstruct

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #14290: Current PATCH method doesn't follows HTTP specification.
##### **Overview of the feature request**

When executing PATCH `api/my-entity/<id>`, a subsequent GET `api/my-entity/<id>` will return the same object.

https://tools.ietf.org/html/rfc5789

##### **Motivation for or Use Case**

Now with PR #14139 PUT follows HTTP specification, it would be interesting to be able to also change the PATCH, to maintain consistency and standardization.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by PiperDing**
Fix #14033
Fix #14290

1. move partialUpdate function to mapstruct
2. generate the patch request code at client
3. add ID parameter to PATCH
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@PiperDing can you add `id` parameter to PATCH? See https://github.com/jhipster/generator-jhipster/issues/14290.

**Comment by PiperDing** [comment]
@mshima ok, I will do it

**Comment by mshima** [comment]
> @mshima ok, I will do it

Thanks

**Comment by PiperDing** [comment]
@mshima The optimization is complete

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
@PiperDing many thanks for the contribution!

**Review by mshima — COMMENTED** [review]
@PiperDing great work and congrats for the first contribution.

**Pull request merged**
