### PR TITLE
Fix issue with fake data

### PR DESCRIPTION
**Pull request by deepu105**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@deepu105 : can you resolve the merge conflict plz ?

**Comment by deepu105** [comment]
Sure will do today

**Comment by deepu105** [comment]
@pascalgrimaud the build for `react-maven-couchbase-caffeine` seems to be failing with some weird backend warning, do you know anything about this? It doesn't look related to my change

**Comment by pascalgrimaud** [comment]
Yes, it's a known issue with Couchbase:
- https://github.com/jhipster/generator-jhipster/issues/10594

it seems to not be resolved completely...

**Pull request merged**
