### PR TITLE
Typecheck

### PR DESCRIPTION
**Pull request by sendilkumarn**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
You might have to add the `skipLibCheck: true` to the tsconfig.aot file for the failure, if that doesnt solve it then we could remove tslint phase from prod build as lint will be done during test phase anyway

**Comment by sendilkumarn** [comment]
Interesting another pain in aot 👎

**Comment by deepu105** [comment]
@sendilkumarn this is making the dev build much slower, I think i'm gonna remove the typecheck on tslint loader

**Comment by deepu105** [comment]
anyway its should be ok as we removed tslint loader from prod

**Pull request merged**
