### PR TITLE
Skip App questions to reduce and customize general prompt

### PR DESCRIPTION
**Pull request by amanganiello90**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by amanganiello90** [comment]
PR for  #10482

**Comment by murdos** [comment]
FYI there's another solution proposed to fix the same issue: https://github.com/jhipster/generator-jhipster/pull/10586

**Comment by amanganiello90** [comment]
Thanks @murdos, this is a good solution in order to provide a full customization...but my solution is only to skip some question prompts without customize any subgenerator, and it not exclude that you have referenced.

**Comment by avdev4j** [comment]
hi,
If we can customize questions, that's mean we can skip which we don't want to display to the user. That's why I prefer to avoid adding many and many skip options for adding a full solution to customize prompts and get benefit for all other blueprints.

So I suggest to help @mshima to secure his PR and contribute to a more complete solution.

**Comment by amanganiello90** [comment]
ok @avdev4j , what does miss in that PR?

**Comment by avdev4j** [comment]
First we need to help for the review and try to how test and (if needed) improve the code.
I think we can converge for a more generic solution.

**Comment by murdos** [comment]
I agree, I prefer a more generic solution too.

**Comment by pascalgrimaud** [comment]
I think it can be closed as https://github.com/jhipster/generator-jhipster/pull/10752 should help to customize app question

**Pull request closed without merging**
