### PR TITLE
Fix: OneToMany id bug in react entity validation form

### LINKED ISSUE #13989: OneToMany id bug in react entity validation form
##### **Overview of the issue**

Default name in AvInput of OneToMany relationship causes wrong object serialization.
I think it happens only in OneToMany relationships with required in the Many side.
image
image

##### **Motivation for or Use Case**

Can't properly create or update entities from frontend.

##### **Reproduce the error**

In JDL Studio >
relationship OneToMany {
    Warehouse{inventory} to Inventory{warehouse required},
}

##### **Related issues**

Didn't find one.

##### **JHipster Version(s)**

Release 7.0.0-beta.1
I have not tried previous versions of JHipster.

##### **JHipster configuration**

`-- generator-jhipster@7.0.0-beta.1

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling", "cucumber"],
    "pages": [],
    "creationTimestamp": 1613098461847,
    "promptValues": {
      "nativeLanguage": "es"
    },
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": ["websocket:spring-websocket"],
    "websocket": "spring-websocket",
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "litera",
    "clientThemeVariant": "primary",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "clientPackageManager": "npm",
    "languages": ["es", "en"],
    "lastLiquibaseTimestamp": 1613099810000
  }
}
</pre>
</details>

openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.8.10.1 (build 11.0.8+10-LTS, mixed mode)

git version 2.24.1.windows.2

node: v14.15.3

npm: 6.14.9

yeoman: 3.1.1

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

##### **Browsers and Operating System**

Windows 10 and Google Chrome.

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #13989 

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
As I'm not a React expert, trusting you on this :)

**Comment by deepu105** [comment]
I'm wondering how this passed the CI as there was clearly a TS error and #14163 . I'm gonna do a PR to fix it, but we need to check why this didn't fail the CI

**Comment by qmonmert** [comment]
@deepu105 what "TS error" ?

**Comment by qmonmert** [comment]
@deepu105 there is a problem with this PR ? 🤔

**Comment by deepu105** [comment]
@qmonmert check this https://github.com/jhipster/generator-jhipster/pull/14181

**Comment by deepu105** [comment]
@pascalgrimaud I figured out why the TS error was not caught by CI, the error happens only when your entity name is already plural, like `CustomerDetails` for example. May be we should add an entity with same spelling for singular/plural

**Comment by qmonmert** [comment]
> #14181

ok it was a bug before this PR

**Comment by pascalgrimaud** [comment]
Oh nice catch @deepu105. Agree, we should improve our CI

**Pull request merged**
