### PR TITLE
Add support to mixed microservice/microfrontend.

### PR DESCRIPTION
**Pull request by mshima**
Before https://github.com/jhipster/generator-jhipster/pull/18254 entities were required to link a gateway to microfrontends. For this reason, entities with microserviceName needed to be skipped.

This PR reenable microservices entities generation at gateway side (frontend) when microfrontend support is enabled.

This is a breaking change to existing microfrontend gateway applications.
Microfrontend entities need to be deleted from gateway’s `.jhipster` folder, otherwise the entities will have its frontend generated at gateway side.

- Enable microservices entities frontend generation at gateways when microfrontend flag is enabled.
- Removes legacy per entity microfrontend support from angular.
- Don’t generate some cypress common tests at microfrontend side.
- Convert vue and react mf test to mixed.
- Add mixed angular test.

Related to https://github.com/jhipster/generator-jhipster/issues/17031

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
@mshima What is the current behavior and how does this PR fix it?

**Comment by mraible** [comment]
I tried installing this branch and generating apps with `jhipster jdl reactive-mf`. Everything starts up OK and I'm able to run `npm run e2e` successfully in the `gateway`, `blog`, and `store` directories. 

I'm still interested in having a way to run `npm run e2e` for all apps with one command.

**Comment by DanielFran** [comment]
@mshima You still have 2 TODOs in the integration test samples:
- https://github.com/jhipster/generator-jhipster/pull/18632/files#diff-c8c1bd4b386c0db80d2f7662bf47af4d4609caf328f8daf61e12cbedae995ce9R29
- https://github.com/jhipster/generator-jhipster/pull/18632/files#diff-c8c1bd4b386c0db80d2f7662bf47af4d4609caf328f8daf61e12cbedae995ce9R37

**Comment by mshima** [comment]
> @mshima What is the current behavior and how does this PR fix it?

Before https://github.com/jhipster/generator-jhipster/pull/18254, microservice entities and microfrontend entities were indistinguishable.
So they were both ignore when the gateway is microfrontend enabled.

With https://github.com/jhipster/generator-jhipster/pull/18254, microfrontend entities don't need to be copied to the gateway anymore.

So with this PR, microfrontend entities at the gateway `.jhipster` will be generated like a microservice entity.

**Comment by mshima** [comment]
> @mshima You still have 2 TODOs in the integration test samples:

@DanielFran they are bugs not related to this PR.
I need to open ISSUES to every sample TODO.

**Comment by mshima** [comment]
> I'm still interested in having a way to run `npm run e2e` for all apps with one command.

@mraible need workspaces.
```
jhipster jdl reactive-mf.jdl --workspaces
.
npm run e2e --workspaces
```

**Review by mraible — APPROVED** [review]

**Comment by mraible** [comment]
@mshima I'm trying to create a demo script for the microfrontends support that will eventually become a blog post. If I try the following:

```
jhipster jdl reactive-mf.jdl --workspaces
npm run e2e --workspaces
```

It fails:

```
➜  mfr npm run e2e --workspaces

> blog@0.0.1-SNAPSHOT e2e
> npm run e2e:cypress:headed --


> blog@0.0.1-SNAPSHOT e2e:cypress:headed
> npm run e2e:cypress -- --headed


> blog@0.0.1-SNAPSHOT e2e:cypress
> cypress run --browser chrome --record ${CYPRESS_ENABLE_RECORD:-false} "--headed"

sh: cypress: command not found
npm ERR! Lifecycle script `e2e:cypress` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: blog@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/blog
npm ERR! Lifecycle script `e2e:cypress:headed` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: blog@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/blog
npm ERR! Lifecycle script `e2e` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: blog@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/blog

> store@0.0.1-SNAPSHOT e2e
> npm run e2e:cypress:headed --

(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ : ERR!   at location: /Users/mraible/Downloads/mfr/blog
> store@0.0.1-SNAPSHOT e2e:cypress:headed
> npm run e2e:cypress -- --headed

(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ : ERR!   at location: /Users/mraible/Downloads/mfr/blog
> store@0.0.1-SNAPSHOT e2e:cypress
> cypress run --browser chrome --record ${CYPRESS_ENABLE_RECORD:-false} "--headed"

sh: cypress: command not found
npm ERR! Lifecycle script `e2e:cypress` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: store@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/store
npm ERR! Lifecycle script `e2e:cypress:headed` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: store@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/store
npm ERR! Lifecycle script `e2e` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: store@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/store

> gateway@0.0.1-SNAPSHOT e2e
> npm run e2e:cypress:headed --

(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠸ : ERR!   at location: /Users/mraible/Downloads/mfr/store
> gateway@0.0.1-SNAPSHOT e2e:cypress:headed
> npm run e2e:cypress -- --headed

(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠸ : ERR!   at location: /Users/mraible/Downloads/mfr/store
> gateway@0.0.1-SNAPSHOT e2e:cypress
> cypress run --browser chrome --record ${CYPRESS_ENABLE_RECORD:-false} "--headed"

sh: cypress: command not found
npm ERR! Lifecycle script `e2e:cypress` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: gateway@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/gateway
npm ERR! Lifecycle script `e2e:cypress:headed` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: gateway@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/gateway
npm ERR! Lifecycle script `e2e` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: gateway@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/gateway
```

I thought this might be because I never started the apps, so I started all the dependent Docker containers (with `npm run ci:e2e:prepare` in { gateway, blog, store } and then used `./gradlew` to start them. They all fail on `npmInstall`:

gateway:

```
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     undefined,
npm WARN cleanup     AssertionError [ERR_ASSERTION]: rimraf: missing path
npm WARN cleanup         at rimraf (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:54:3)
npm WARN cleanup         at node:internal/util:360:7
npm WARN cleanup         at new Promise (<anonymous>)
npm WARN cleanup         at rimraf (node:internal/util:346:12)
npm WARN cleanup         at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:532:20
npm WARN cleanup         at Array.map (<anonymous>)
npm WARN cleanup         at Arborist.[rollbackCreateSparseTree] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:532:8)
npm WARN cleanup         at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:1078:50
npm WARN cleanup         at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm WARN cleanup         at async Arborist.[reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:235:11) {
npm WARN cleanup       generatedMessage: false,
npm WARN cleanup       code: 'ERR_ASSERTION',
npm WARN cleanup       actual: undefined,
npm WARN cleanup       expected: true,
npm WARN cleanup       operator: '=='
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /Users/mraible/Downloads/mfr/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! ERROR: Failed to set up Chromium r869685! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! [Error: ENOENT: no such file or directory, open '/Users/mraible/Downloads/mfr/node_modules/puppeteer/.local-chromium/chrome-mac.zip'] {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'open',
npm ERR!   path: '/Users/mraible/Downloads/mfr/node_modules/puppeteer/.local-chromium/chrome-mac.zip'
npm ERR! }
```

blog:

```
[webpack-cli] Error: Cannot find module 'browserslist'
Require stack:
- /Users/mraible/Downloads/mfr/node_modules/webpack/lib/config/browserslistTargetHandler.js
- /Users/mraible/Downloads/mfr/node_modules/webpack/lib/config/target.js
- /Users/mraible/Downloads/mfr/node_modules/webpack/lib/config/defaults.js
- /Users/mraible/Downloads/mfr/node_modules/webpack/lib/webpack.js
- /Users/mraible/Downloads/mfr/node_modules/webpack/lib/index.js
- /Users/mraible/Downloads/mfr/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/mraible/Downloads/mfr/node_modules/webpack-cli/lib/bootstrap.js
- /Users/mraible/Downloads/mfr/node_modules/webpack-cli/bin/cli.js
- /Users/mraible/Downloads/mfr/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mraible/Downloads/mfr/node_modules/webpack/lib/config/browserslistTargetHandler.js:8:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mraible/Downloads/mfr/node_modules/webpack/lib/config/browserslistTargetHandler.js',
    '/Users/mraible/Downloads/mfr/node_modules/webpack/lib/config/target.js',
    '/Users/mraible/Downloads/mfr/node_modules/webpack/lib/config/defaults.js',
    '/Users/mraible/Downloads/mfr/node_modules/webpack/lib/webpack.js',
    '/Users/mraible/Downloads/mfr/node_modules/webpack/lib/index.js',
    '/Users/mraible/Downloads/mfr/node_modules/webpack-cli/lib/webpack-cli.js',
    '/Users/mraible/Downloads/mfr/node_modules/webpack-cli/lib/bootstrap.js',
    '/Users/mraible/Downloads/mfr/node_modules/webpack-cli/bin/cli.js',
    '/Users/mraible/Downloads/mfr/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! Lifecycle script `webapp:build:dev` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: blog@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/blog
npm ERR! Lifecycle script `webapp:build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: blog@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/blog
```

store:

```
> Task :npmInstall
npm WARN workspaces store in filter set, but no workspace folder present
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/mraible/Downloads/mfr/node_modules/aria-query
npm ERR! dest /Users/mraible/Downloads/mfr/node_modules/.aria-query-0L00QxYs
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/mraible/Downloads/mfr/node_modules/aria-query' -> '/Users/mraible/Downloads/mfr/node_modules/.aria-query-0L00QxYs'
```

Am I doing something wrong?

**Comment by mshima** [comment]
`npm run ci:e2e:package` to build docker images.

`npm run ci:e2e:package:arm64` For m1

```
npm run ci:e2e:package
npm run ci:e2e:prepare
npm run ci:e2e:run
```

**Comment by mraible** [comment]
Should I be able to run these at the top level with `--workspaces` or in each app's directory?

If I run `npm run ci:e2e:package` in the gateway directory, it results in:

```
npm ERR! code 126
npm ERR! path /Users/mraible/Downloads/mfr/gateway
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! sh: /Users/mraible/Downloads/mfr/node_modules/.bin/husky: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2022-06-08T16_51_25_442Z-debug-0.log

> Task :npm_install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':npm_install'.
> Process 'command 'npm'' finished with non-zero exit value 126

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
4 actionable tasks: 2 executed, 2 up-to-date
npm ERR! Lifecycle script `java:jar` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: gateway@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/gateway
npm ERR! Lifecycle script `java:jar:prod` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: gateway@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/gateway
npm ERR! Lifecycle script `ci:e2e:package` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: gateway@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/mfr/gateway
```

**Comment by mshima** [comment]
> Should I be able to run these at the top level with `--workspaces` or in each app's directory?

Top level without `--workspaces` (if generated with jhipster --workspaces).

**Comment by mshima** [comment]
> I tried again with the `main` branch. I'm on an M1, but when I run `npm run ci:e2e:package:arm64`, it fails with:

Indeed doesn't exists. Use `npm run java:docker:arm64` instead.

> I ran `chmod +x node_modules/.bin/husky` from the top-level directory and tried again. It still fails.

Have you created the top level repository manually?
Husky must be disabled on each project. It need to be installed at top level (we don't support this).
`jhipster jdl --workspaces --monorepository` this will create git repository at top level and disable husky.

**Comment by mraible** [comment]
`npm run java:docker:arm64` works, but it results in the same error.

I have not created the top-level repository manually. Here are the commands I'm using:

```
cd ~/Downloads
rm -rf mfr
take mfr
jhipster jdl reactive-mf --workspaces
npm run java:docker:arm64
```

```
$ node --version
v16.15.0
```

**Comment by mshima** [comment]
I've forgot.
npm moves dependencies to the top level, so husky is installed at top level.
It tries to commit to a missing git repository.

Please use `jhipster jdl reactive-mf --workspaces --skip-commit-hooks` or `jhipster jdl reactive-mf --workspaces --monorepository`

**Comment by mraible** [comment]
I tried them both. For the first one, I had to use `--skip-commit-hook` and the error message was good. 

For both commands, I see the following errors like the following when generating apps:

```
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     undefined,
npm WARN cleanup     AssertionError [ERR_ASSERTION]: rimraf: missing path
npm WARN cleanup         at rimraf (/Users/mraible/Downloads/mfr2/store/build/node/lib/node_modules/npm/node_modules/rimraf/rimraf.js:54:3)
npm WARN cleanup         at node:internal/util:360:7
npm WARN cleanup         at new Promise (<anonymous>)
npm WARN cleanup         at rimraf (node:internal/util:346:12)
npm WARN cleanup         at /Users/mraible/Downloads/mfr2/store/build/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:532:20
npm WARN cleanup         at Array.map (<anonymous>)
npm WARN cleanup         at Arborist.[rollbackCreateSparseTree] (/Users/mraible/Downloads/mfr2/store/build/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:532:8)
npm WARN cleanup         at /Users/mraible/Downloads/mfr2/store/build/node/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:1078:50
npm WARN cleanup         at runMicrotasks (<anonymous>)
npm WARN cleanup         at processTicksAndRejections (node:internal/process/task_queues:96:5) {
npm WARN cleanup       generatedMessage: false,
npm WARN cleanup       code: 'ERR_ASSERTION',
npm WARN cleanup       actual: undefined,
npm WARN cleanup       expected: true,
npm WARN cleanup       operator: '=='
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /Users/mraible/Downloads/mfr2/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! ERROR: Failed to set up Chromium r869685! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! [Error: EEXIST: file already exists, mkdir '/Users/mraible/Downloads/mfr2/node_modules/puppeteer/.local-chromium'] {
npm ERR!   errno: -17,
npm ERR!   code: 'EEXIST',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/mraible/Downloads/mfr2/node_modules/puppeteer/.local-chromium'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2022-06-08T19_16_02_160Z-debug-0.log
Error executing './npmw install', execute it yourself. (Command failed with exit code 1: ./npmw install)6ms
```

Same when building the Docker containers:

```
[java:docker:arm64:gateway] > Task :npm_install FAILED
[java:docker:arm64:store] npm ERR! code 1
[java:docker:arm64:store] npm ERR! path /Users/mraible/Downloads/mfr2/node_modules/puppeteer
[java:docker:arm64:store] npm ERR! command failed
[java:docker:arm64:store] npm ERR! command sh -c node install.js
[java:docker:arm64:store] npm ERR! ERROR: Failed to set up Chromium r869685! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[java:docker:arm64:store] npm ERR! [Error: ENOENT: no such file or directory, open '/Users/mraible/Downloads/mfr2/node_modules/puppeteer/.local-chromium/chrome-mac.zip'] {
[java:docker:arm64:store] npm ERR!   errno: -2,
[java:docker:arm64:store] npm ERR!   code: 'ENOENT',
[java:docker:arm64:store] npm ERR!   syscall: 'open',
[java:docker:arm64:store] npm ERR!   path: '/Users/mraible/Downloads/mfr2/node_modules/puppeteer/.local-chromium/chrome-mac.zip'
[java:docker:arm64:store] npm ERR! }
```

And when I try using the `--monorepository` version, I get errors like:

```
[java:docker:arm64:blog] npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, lstat '/Users/mraible/Downloads/mfr3/node_modules/generator-jhipster/generators/server/templates/src'
```

**Comment by mshima** [comment]
> Also, with steps 6 and 7, the browser loads with an error rather than showing the app.
> 
> Screen Shot 2022-06-08 at 18 56 58

Didn't know about the browser sync popup.
Will be fixed at bootstrap 5.2.0 we would need to pin autoprefixer to prevent the error.

**Pull request merged**
