### PR TITLE
chore: fix config and usage instructions for local sonar setup and code coverage

### LINKED ISSUE #20773: Sonar no longer works with `main` branch
##### **Overview of the issue**

If I clone the `main` branch and create an app with `jhipster jdl 21-points.jh`, it doesn't work with Sonar out-of-the-box. First, I had to build an M1-compatible Docker image and start it. Then there's an error when I try to run the Gradle command against it:

```
> Task :sonarqube FAILED
Task 'sonarqube' is deprecated. Use 'sonar' instead.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> You're not authorized to run analysis. Please contact the project administrator.
```

I tried using `sonar` instead, but this fails too:

```
./gradlew -Pprod clean check jacocoTestReport sonar -Dsonar.host.url=http://localhost:9001

> Task :sonar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonar'.
> You're not authorized to run analysis. Please contact the project administrator.
```

##### **Motivation for or Use Case**

It'd be cool to see code coverage on a newly created app with v8.

##### **Suggest a Fix**

Maybe Sonar's Docker image needs to have authentication turned off by default? 

##### **JHipster Version(s)**

`main` as of Jan 10, 2023

### PR DESCRIPTION
**Pull request by Rajpratik71**
Fix #20773

Fixed config and usage instructions for local sonar setup and code coverage

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Comment by DanielFran** [comment]
@Rajpratik71 Thanks for the contribution.

Can you fix the tests: https://github.com/jhipster/generator-jhipster/actions/runs/4016879736/jobs/6900503352#step:10:16176

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
@Rajpratik71 Can you fix the snapshots?

Instructions are available in [CONTRIBUTING](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md).
````
Update every test snapshot npm run update-snapshots
````

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
Thanks @Rajpratik71 for the contribution

**Comment by Rajpratik71** [comment]
Raised claimed at https://opencollective.com/generator-jhipster/expenses/146037

**Comment by DanielFran** [comment]
@Rajpratik71 approved

**Comment by DanielFran** [comment]
@Rajpratik71 approved

**Pull request merged**
