### PR TITLE
Add remote shell

### LINKED ISSUE #4167: Add Spring Boot remote shell
See http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-remote-shell.html

This gives some nice features for debugging
```shell
> help
Try one of these commands with the -h or --help switch:                                                                                                                                                                                     
                                                                                                                                                                                                                                            
NAME       DESCRIPTION                                                                                                                                                                                                                      
autoconfig Display auto configuration report from ApplicationContext                                                                                                                                                                        
beans      Display beans in ApplicationContext                                                                                                                                                                                              
cron       manages the cron plugin                                                                                                                                                                                                          
dashboard  a monitoring dashboard                                                                                                                                                                                                           
egrep      search file(s) for lines that match a pattern                                                                                                                                                                                    
endpoint   Invoke actuator endpoints                                                                                                                                                                                                        
env        display the term env                                                                                                                                                                                                             
filter     a filter for a stream of map                                                                                                                                                                                                     
java       various java language commands                                                                                                                                                                                                   
jmx        Java Management Extensions                                                                                                                                                                                                       
jul        java.util.logging commands                                                                                                                                                                                                       
jvm        JVM informations                                                                                                                                                                                                                 
less       opposite of more                                                                                                                                                                                                                 
mail       interact with emails                                                                                                                                                                                                             
man        format and display the on-line manual pages                                                                                                                                                                                      
metrics    Display metrics provided by Spring Boot                                                                                                                                                                                          
shell      shell related command                                                                                                                                                                                                            
sleep      sleep for some time                                                                                                                                                                                                              
sort       sort a map                                                                                                                                                                                                                       
system     vm system properties commands                                                                                                                                                                                                    
thread     JVM thread commands                                                                                                                                                                                                              
help       provides basic help                                                                                                                                                                                                              
repl       list the repl or change the current repl                                                                                                                                                                                         
```
and you can execute groovy code in a REPL way on your live app
```shell
> repl groovy
Using repl groovy
> com.mycompany.myapp.StandardApp.context.getBean("userRepository").findAll()
[User{login='system', firstName='System', lastName='System', email='system@localhost', activated='true', langKey='en', activationKey='null'}, User{login='anonymoususer', firstName='Anonymous', lastName='User', email='anonymous@localhost', activated='true', langKey='en', activationKey='null'}, User{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', activated='true', langKey='en', activationKey='null'}, User{login='user', firstName='User', lastName='User', email='user@localhost', activated='true', langKey='en', activationKey='null'}]
> 
```
To configure, it's just a dependency spring-boot-starter-remote-shell to add to the pom.

### PR DESCRIPTION
**Pull request by cbornet**
Using a profile not activated by default.
To use, activate the "shell" maven profile in the IDE. With maven use ```./mvnw -Pdev,shell ... ```

Fix #4167

### CODE REVIEW

**Comment by cbornet** [comment]
Also done for gradle ```./gradlew -Pshell```

**Comment by jdubois** [comment]
Looks easy to use... Will you be also able to add some documentation for the website?

**Comment by cbornet** [comment]
Yes, I'll add doc with some examples of REPL !
Where should it be added ? Under "Developpement" or "Test and QA" ?

**Comment by jdubois** [comment]
It's complicated... because you also need to add a section in the "profiles" page! Maybe a specific page in "Test & QA"?

**Comment by cbornet** [comment]
Yes I'll adapt the "Spring profiles switches" and link to a page dedicated to REPL and shell goodies.

**Comment by jdubois** [comment]
OK and I'm merging this

**Pull request merged**
