### PR TITLE
Travis: improvements for ng2

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/4985
- switch to ng2 for sonar analysis
- reduce logs
- add elasticsearch and prod profile for NG2

### CODE REVIEW

**Comment by jdubois** [comment]
+1 for the `--spring.jpa.show-sql=false`!!!

**Comment by pascalgrimaud** [comment]
I tested for MongoDB and Cassandra applications. It is simply ignored so no problem for adding this for these builds too

**Comment by jdubois** [comment]
Yes, I can't wait to see the new logs :-)

**Comment by pascalgrimaud** [comment]
I think we can reduce more by changing log.debug when running tests with Travis

**Comment by jdubois** [comment]
Yes indeed! Maybe a specific profile for that, users will have the same
issue

Le 28 janv. 2017 1:08 PM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Pull request merged**
