### PR TITLE
Update /services prefix for the Kubernetes generator

### PR DESCRIPTION
**Pull request by saturnism**
For #10343 - issue based on https://medium.com/@simionrazvan/microservices-using-jhipster-kubernetes-istio-bf75e992612a

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
What this is needed is completely beyond me. I don't know who added this prefix but it doesn't make any sense.

**Comment by ruddell** [comment]
The discussion about the `/services/` prefix [starts here](https://github.com/jhipster/generator-jhipster/pull/9098#issuecomment-455891616), the purpose is to prevent client/server path conflicts.

>The Zuul routes take precedence, so you are right that if you name a microservice and entity the same thing, then generate it in the gateway, there will be issues.  For example, I have a `store` microservice and generate an `store` entity, the paths will match causing issues (`/store/**` is mapped to the microservice, so refreshing in the client on the `/store` entity listing returns a 403).

This PR does the same as https://github.com/jhipster/generator-jhipster/pull/10138

**Comment by saturnism** [comment]
agreed it's kind of weird and also caught me by surprise when i use jhipster recently. /api/[service]/[entity] would've made more sense for me, but i think that was an option discussed that would've been much more complicated.

**Comment by saturnism** [comment]
@PierreBesson if ok w/ you, i'd like to merge this, and then fix a couple of other issues :)

**Comment by PierreBesson** [comment]
Yes of course it's the right solution. Thanks @ruddell for giving clarification. I'm still not convinced but we will have to tackle this issue later.

**Comment by saturnism** [comment]
> ... I'm still not convinced but we will have to tackle this issue later.

+1 😄 thanks!

**Pull request merged**
