### PR TITLE
Gradle 4 upgrade

### LINKED ISSUE #5936: Upgrade to Gradle 4
##### **Overview of the issue**

The new major release has some nice new features, like parallel download of dependencies

##### **Motivation for or Use Case**

Always stay up to date

##### **Reproduce the error**

Not applicable

##### **Related issues**

None

##### **Suggest a Fix**

I already updates the version and found that some plugins needed to be updated. Will try to test further during the weekend and create a PR when I'm done, but it looks like a very seamless update now

##### **JHipster Version(s)**

Current master

##### **JHipster configuration**

Using gradle as build system

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

Not relevant

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by atomfrede**
I fixed some problems with dependency resolution (see comment here: https://github.com/spring-projects/spring-boot/issues/9516) and tested with following settings:

* [x] SQL, Monolithic Application
* [x]  Gatling Tests
* [x] Gateway
* [x] Microservice
* [x] Mongo
* [x] Cassandra

 I will update the PR when more tests are done,

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

close #5936

### CODE REVIEW

**Comment by atomfrede** [comment]
@jhipster/developers I have tested all above and couldn't find any problems, so I suggest we can merge it.

**Comment by atomfrede** [comment]
Furthermore when using gradle you can execute a single simulation with `-Psimulation=YouSimulation`

**Comment by jdubois** [comment]
Congrats!! As there is a lot of advertisement in conferences and Twitter about the new Gradle performance enhancements, did you experience any speed up?

**Comment by atomfrede** [comment]
Right that's what wanted to try with empty m2 repository as that was most annoying because dependencies have not been downloaded in parallel. Will post some numbers.

**Comment by pascalgrimaud** [comment]
@atomfrede :
- can you rebase with master plz?
- then, test with gradle+cassandra
- I think there is an issue, but it's not related to your PR...

Maybe the problem comes from this commit https://github.com/jhipster/generator-jhipster/commit/635a757c1238dc26e423e222d162e7c1b60f6c06 and the springfox version 2.7.0

**Comment by atomfrede** [comment]
@pascalgrimaud You are right. It doesn't work. Get this error `java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback`

**Comment by pascalgrimaud** [comment]
yes, I saw it there : https://travis-ci.org/hipster-labs/jhipster-travis-build/branches
There is a branch with full builds for Gradle

Not perfected yet and a lot of random failures, specially with uaa, but there are more tests than our current Travis

**Comment by atomfrede** [comment]
Wow, cool. Will check it and try it locally.

**Comment by atomfrede** [comment]
I fixed the cassandra problem (missing guava dependency).
Some numbers regarding performance

* `mvn clean package -DskipTests` with empty `.m2`: `~2 Min`
* `./gradlew clean bootRepackage` with empty jar cache: `~1 Min`
* `mvn clean package -DskipTests` with full `.m2`: `~15 sec`
* `./gradlew clean bootRepackage` with full jar cache: `~10 sec` (with daemon), `~18 sec` (without daemon)

I have no numbers currently for gradle 3.5 but the initial build with empty caches was terrible slow because of non parallel download of dependencies, so for me these are very cool results.

**Comment by jdubois** [comment]
OK, so nothing extraordinary here, but we need to upgrade anyway -> are you confident with merging your PR? If yes, let's do it!

**Comment by atomfrede** [comment]
Let's Merge it to see if any less used combination doesn't work well. As it also fixes gradle and Cassandra we should Merge it.

**Comment by deepu105** [comment]
Wow so finally now Gradle is faster than maven. @atomfrede what say we make Gradle the default option? 
Most people these days use Gradle anyway

**Comment by deepu105** [comment]
@jdubois what say we make Gradle the default option?

**Comment by sendilkumarn** [comment]
I second it. 👍

**Comment by atomfrede** [comment]
@deepu105 Would like to have gradle as default, but I think maven is still the dominant build system. E.g. all our services are build with maven. We use gradle for custom things, like executing test with docker or setting up our local minikube environment or handling translations via crowdin. @jdubois How are the current stats maven vs gradle?

**Comment by pascalgrimaud** [comment]
I'm a maven user, so I'd prefer keeping maven as default :)
I'm curious to have some stats between maven and gradle too

**Comment by deepu105** [comment]
Stats will always swing towards what we set us default :)


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes stats are always misleading, but as you asked for them, for July 2017, we have:

- Maven 81,71 %
- Gradle 18,29 %

Now I don't want to change the build tools for the following reasons:

- Our current focus is Angular 4, and that's already too complex
- Gradle 4 just got merged this morning, we need time to see if everything works fine (Docker build? CI-CD?)
- All my customers (and me also!) use Maven
- I'm still totally confused when looking at the Gradle conf, after years trying to understand it, when I've never had any trouble with Maven

Then, I'm totally opened at migrating to Gradle in the future:

- When we have the guarantee everything works well with Gradle
- If the Grade build is much quicker (but when I mean quicker, I mean "without the Gradle daemon")
- If this allows us to create some advanced configuration, maybe with the Angular/Webpack builds for example, and that in the end we have something much easier/performant/dev-friendly

**Comment by atomfrede** [comment]
Totally agree with you, except I don't understand the maven config very well :) But ~20% for a non default option is quite good I think.

**Comment by PierreBesson** [comment]
Personnaly I'm against moving the default build to gradle for now. Even though I have more experience with maven, I feel that gradle has the potential to be a better and much more flexible build tool. It's just that I don't consider our current gradle build to be clean enough and I feel that we are already struggling to maintain it because few people in our team actually use it.

**Comment by atomfrede** [comment]
@PierreBesson We should also wait for Spring Boot 2 and their new gradle plugin. If we make gradle the default now I am pretty sure something will break when sb2 is released

**Comment by deepu105** [comment]
@PierreBesson FYI, I always use Gradle. I have never used Maven except for testing a JHipster app with maven build :) And actually, many of the people in the team use Gradle If I'm not wrong, at least 4 that I know of, again if I'm not wrong.

Anyways, let's not worry about this now and we will see about this may be in our next major release.

**Comment by oehme** [comment]
> If the Grade build is much quicker (but when I mean quicker, I mean "without the Gradle daemon")

Gradle is designed to trade off the first startup for fast subsequent builds. The daemon is the default for that reason. I really don't understand why one would want to run without it. That being said, the only time I've seen Maven being quicker on a "cold" machine was either

- very small projects where Maven can keep the initial head start (that seems to be the case here)
- misconfigured Gradle builds

Using `clean` builds for performance comparisons is missing an important point though - Gradle developers will pretty much never call `clean`. Gradle has properly working incremental builds.

> OK, so nothing extraordinary here

It's 50% faster than Maven for a clean build on a pretty simple project. That's pretty extraordinary, given that in such a small project, there is almost nothing to optimize ;)

I'm not going to advocate for or against changing the default, that should be decided based on your community's feedback. I just wanted to give some perspective on those numbers.

**Comment by deepu105** [comment]
Thanks for the clarification @oehme 
From your profile looks like you are in the core Gradle team am I right? We would love to have your feedback on the Gradle build we create

**Comment by oehme** [comment]
Sure, if you point me to an example of a typical project you create, I'm happy to give some feedback.

**Comment by atomfrede** [comment]
@oehme I think best way is to test drive https://jhipster.julien-dubois.com/. I have created a simple monolithic application here: https://github.com/atomfrede/jhipsterGradleSampleApplication

If you find things to do better (I am sure you will) that would be awesome!

**Comment by deepu105** [comment]
Yes and there is also the official Gradle sample here https://github.com/jhipster/jhipster-sample-app-gradle which should be the same as @atomfrede posted above s it is generated with same version of JHipster

**Comment by jdubois** [comment]
@oehme oh yes, your feedback is very highly welcome here!!!! I can't guarantee we'll switch the default to Gradle, but if performance is much better (and maybe features also?), we'll do our best to market it, and maybe change the stats!

**Comment by oehme** [comment]
Just FYI, I'm on vacation next week, so I'll only get around to this in August. I think setting up a hangout would be ideal to walk through some of the pieces.

**Comment by deepu105** [comment]
Yes we could do that I guess

**Comment by atomfrede** [comment]
I am also on vacation next week so august would be fine.

**Comment by sendilkumarn** [comment]
Thanks a lot for the clarification @oehme 
and ofcourse +1 for hangout.

**Comment by deepu105** [comment]
@oehme could you let us know a date in August when you would be available for the call you suggested so that I can send out an invitation based on that so that people dont forget :)

**Comment by oehme** [comment]
How about the 16th or 17th at 18:00 CEST/ 9:00 PST? From our side @eriwen and I would like to join in.

**Comment by atomfrede** [comment]
16th is not possible for me as we have jug meetup but no problem if everyone else prefers 16th.

**Comment by oehme** [comment]
@deepu105 Wednesday is now already taken for me, but the time slot on Thursday is still free. Can you send out an invite?

**Comment by deepu105** [comment]
@oehme yes I'll send an invite. Unfortunately, my 6PM Thursday is taken as well but if @atomfrede and @sendilkumarn are available that should be fine. Guys please confirm

**Comment by deepu105** [comment]
@jhipster/developers anyone else interested to join?

**Comment by jdubois** [comment]
I'd love to, but I'm still on holidays (with 3 small kids, so I wonder if that can be called holidays??)

**Comment by atomfrede** [comment]
I can make it.

**Comment by deepu105** [comment]
@atomfrede great. I'll send an invite

**Comment by deepu105** [comment]
I have send out a google calendar invite for 17th August 1800 CEST

**Comment by oehme** [comment]
@deepu105 There is no hangout attached to the calendar invite, can you please add one?

**Comment by atomfrede** [comment]
@deepu105  @oehme Should I create a new invite?

**Comment by deepu105** [comment]
@atomfrede @oehme @sendilkumarn sorry guys I didnt have access to laptop as I was traveling. Did you manage to make the Hangout? I guess I totally forgot to attach the link. damn me

**Comment by atomfrede** [comment]
I posted a summary to our mailing list :)

2017-08-17 21:20 GMT+02:00 Deepu K Sasidharan <notifications@github.com>:

**Comment by deepu105** [comment]
Pasting the thread link for anybody interested https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/P91z4qd_-XY/m6qQTN8jAAAJ

**Pull request merged**
