### PR TITLE
several relationship fixes for Angular forms

### LINKED ISSUE #9347: Protractor: failure for creating/deleting with different relationships
##### **Overview of the issue**

Protractor tests failed with different relationships / pagination.

##### **Motivation for or Use Case**

Detected by https://dev.azure.com/hipster-labs/jhipster-daily-builds/_dashboards/dashboard/838f7bd8-7cb5-4bad-a47d-362df39abb27

You can look the full logs for ngx-mysql: https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=1580

##### **Reproduce the error**

- Generate a project with the entities above
- Launch the application
- Launch protractor tests

```
  account
    ✓ should fail to login with bad password
    ✓ should login successfully with admin account (4956ms)
    ✓ should be able to update settings
    ✓ should fail to update password when using incorrect current password
    ✓ should be able to update password (2996ms)

  administration
    ✓ should load user management
    ✓ should load metrics
    ✓ should load health
    ✓ should load configuration
    ✓ should load audits
    ✓ should load logs

  SuperMegaLargeTestEntity e2e test
    ✓ should load SuperMegaLargeTestEntities (5793ms)
    ✓ should load create SuperMegaLargeTestEntity page

  TestCustomTableName e2e test
    ✓ should load TestCustomTableNames (5818ms)
    ✓ should load create TestCustomTableName page (5720ms)

  TestEntity e2e test
    ✓ should load TestEntities (5656ms)
    ✓ should load create TestEntity page

  TestInfiniteScroll e2e test
    ✓ should load TestInfiniteScrolls
    ✓ should load create TestInfiniteScroll page
    1) should create and save TestInfiniteScrolls
    2) should delete last TestInfiniteScroll

  TestManyRelPaginDTO e2e test
    ✓ should load TestManyRelPaginDTOS
    ✓ should load create TestManyRelPaginDTO page
    ✓ should create and save TestManyRelPaginDTOS (5748ms)
    ✓ should delete last TestManyRelPaginDTO (5525ms)

  TestManyToMany e2e test
    ✓ should load TestManyToManies
    ✓ should load create TestManyToMany page (5836ms)
    ✓ should create and save TestManyToManies (11137ms)
    ✓ should delete last TestManyToMany (5487ms)

  TestManyToOne e2e test
    ✓ should load TestManyToOnes
    ✓ should load create TestManyToOne page (5695ms)
    ✓ should create and save TestManyToOnes (11490ms)
    ✓ should delete last TestManyToOne (5487ms)

  TestMapstruct e2e test
    ✓ should load TestMapstructs
    ✓ should load create TestMapstruct page
    ✓ should create and save TestMapstructs (5827ms)
    ✓ should delete last TestMapstruct (5481ms)

  TestOneToOne e2e test
    ✓ should load TestOneToOnes
    ✓ should load create TestOneToOne page (5776ms)
    ✓ should create and save TestOneToOnes (11518ms)
    ✓ should delete last TestOneToOne (5482ms)

  TestPager e2e test
    ✓ should load TestPagers
    ✓ should load create TestPager page
    3) should create and save TestPagers
    4) should delete last TestPager

  TestPagination e2e test
    ✓ should load TestPaginations
    ✓ should load create TestPagination page
    5) should create and save TestPaginations
    6) should delete last TestPagination

  Division e2e test
    ✓ should load Divisions
    ✓ should load create Division page
    ✓ should create and save Divisions (6469ms)
    ✓ should delete last Division (5445ms)

  Place e2e test
    ✓ should load Places
    ✓ should load create Place page
    ✓ should create and save Places (6750ms)
    ✓ should delete last Place (5498ms)

  TestServiceClass e2e test
    ✓ should load TestServiceClasses
    ✓ should load create TestServiceClass page
    7) should create and save TestServiceClasses
    8) should delete last TestServiceClass

  TestServiceImpl e2e test
    ✓ should load TestServiceImpls
    ✓ should load create TestServiceImpl page
    9) should create and save TestServiceImpls
    10) should delete last TestServiceImpl

  TestTwoRelationshipsSameEntity e2e test
    ✓ should load TestTwoRelationshipsSameEntities
    ✓ should load create TestTwoRelationshipsSameEntity page (5599ms)


  57 passing (5m)
  10 failing
```

##### **Related issues**

no idea

##### **Suggest a Fix**

If it's too complex to fix it, we could simply add these part in comment, like we already did for other use cases.

##### **JHipster Version(s)**

```
toto@0.0.0 /home/pgrimaud/tmp/44-toto
└── generator-jhipster@5.8.1  -> /home/pgrimaud/projects/jhipster/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "monolith",
    "baseName": "toto",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity TestTwoRelationshipsSameEntity (test_multiple_rel)
entity TestPager
entity TestCustomTableName (test_custom_table_name_entity)
entity TestEntity
entity TestInfiniteScroll
entity TestServiceImpl
entity TestPagination
entity TestServiceClass
entity TestMapstruct
entity TestManyToMany
entity TestManyRelPaginDTO (test_many_many_pagination_dto)
entity TestManyToOne
entity TestOneToOne
entity Division {
  name String required unique,
  shortName String unique,
  numberOfPeople Long,
  divisionType DivisionType required,
  colorBackground String,
  colorText String
}
entity Place {
  name String required,
  numberOfSeats Long,
  shortName String,
  colorBackground String,
  colorText String,
  description TextBlob
}
entity SuperMegaLargeTestEntity

enum DivisionType {
  SCHOOL,
  CLASS,
  SUBGROUP
}

relationship OneToOne {
  TestTwoRelationshipsSameEntity{userOne} to User,
  TestTwoRelationshipsSameEntity{userTwo} to User,
  TestPager{userOneToOne(login)} to User,
  TestCustomTableName{userOneToOne(login)} to User,
  TestEntity{userOneToOne(login)} to User,
  TestInfiniteScroll{userOneToOne(login)} to User,
  TestServiceImpl{userOneToOne(login)} to User,
  TestPagination{userOneToOne(login)} to User,
  TestServiceClass{userOneToOne(login)} to User,
  TestMapstruct{userOneToOne(login)} to User,
  TestOneToOne{testEntity} to TestEntity{testOneToOne},
  TestOneToOne{testMapstruct} to TestMapstruct{testOneToOne},
  TestOneToOne{testServiceClass} to TestServiceClass{testOneToOne},
  TestOneToOne{testServiceImpl} to TestServiceImpl{testOneToOne},
  TestOneToOne{testInfiniteScroll} to TestInfiniteScroll{testOneToOne},
  TestOneToOne{testPager} to TestPager{testOneToOne},
  TestOneToOne{testPagination} to TestPagination{testOneToOne},
  TestOneToOne{testCustomTableName} to TestCustomTableName{testOneToOne},
  TestOneToOne{superMegaLargeTestEntity} to SuperMegaLargeTestEntity{superMegaLargeTestOneToOne},
  SuperMegaLargeTestEntity{superMegaLargeUserOneToOne(login)} to User
}
relationship OneToMany {
  TestEntity{testCustomTableName} to TestCustomTableName{testEntity required},
  SuperMegaLargeTestEntity{superMegaLargeTestCustomTableName} to TestCustomTableName{superMegaLargeTestEntity required},
  TestEntity{testManyToOne} to TestManyToOne{testEntity},
  TestMapstruct{testManyToOne} to TestManyToOne{testMapstruct},
  TestServiceClass{testManyToOne} to TestManyToOne{testServiceClass},
  TestServiceImpl{testManyToOne} to TestManyToOne{testServiceImpl},
  TestInfiniteScroll{testManyToOne} to TestManyToOne{testInfiniteScroll},
  TestPager{testManyToOne} to TestManyToOne{testPager},
  TestPagination{testManyToOne} to TestManyToOne{testPagination},
  TestCustomTableName{testManyToOne} to TestManyToOne{testCustomTableName},
  SuperMegaLargeTestEntity{superMegaLargeTestManyToOne} to TestManyToOne{superMegaLargeTestEntity},
  Division{divisionsPlace} to Place{owner(name)}
}
relationship ManyToOne {
  TestTwoRelationshipsSameEntity{firstRelationship} to TestEntity,
  TestTwoRelationshipsSameEntity{secondRelationship} to TestEntity,
  TestTwoRelationshipsSameEntity{firstUniqueRequiredRelation required} to Division,
  TestTwoRelationshipsSameEntity{secondUniqueRequiredRelation required} to Division,
  TestPager{userOneToMany(login)} to User,
  TestCustomTableName{userOneToMany(login)} to User,
  TestEntity{userOneToMany(login) required} to User,
  TestInfiniteScroll{userOneToMany(login)} to User,
  TestServiceImpl{userOneToMany(login)} to User,
  TestPagination{userOneToMany(login)} to User,
  TestServiceClass{userOneToMany(login)} to User,
  TestMapstruct{userOneToMany(login)} to User,
  SuperMegaLargeTestEntity{superMegaLargeUserOneToMany(login) required} to User
}
relationship ManyToMany {
  TestPager{userManyToMany(login)} to User,
  TestCustomTableName{userManyToMany(login)} to User,
  TestEntity{userManyToMany(login)} to User,
  TestInfiniteScroll{userManyToMany(login)} to User,
  TestServiceImpl{userManyToMany(login)} to User,
  TestPagination{userManyToMany(login)} to User,
  TestServiceClass{userManyToMany(login)} to User,
  TestMapstruct{userManyToMany(login)} to User,
  TestManyToMany{testEntity} to TestEntity{testManyToMany},
  TestManyToMany{testMapstruct} to TestMapstruct{testManyToMany},
  TestManyToMany{testServiceClass} to TestServiceClass{testManyToMany},
  TestManyToMany{testServiceImpl} to TestServiceImpl{testManyToMany},
  TestManyToMany{testInfiniteScroll} to TestInfiniteScroll{testManyToMany},
  TestManyToMany{testPager} to TestPager{testManyToMany},
  TestManyToMany{testPagination} to TestPagination{testManyToMany},
  TestManyToMany{testCustomTableName} to TestCustomTableName{testManyToMany},
  TestManyToMany{superMegaLargeTestEntity} to SuperMegaLargeTestEntity{superMegaLargeTestManyToMany},
  TestManyRelPaginDTO{testMapstruct} to TestMapstruct{testManyRelPaginDTO},
  Place{preferredDivision(name)} to Division{preferredPlace},
  SuperMegaLargeTestEntity{superMegaLargeUserManyToMany(login)} to User
}

angularSuffix TestTwoRelationshipsSameEntity, TestManyToMany, TestManyRelPaginDTO, TestManyToOne, TestOneToOne with mySuffix
angularSuffix TestEntity, SuperMegaLargeTestEntity with mySuffixAlt
paginate TestPager with pager
paginate TestInfiniteScroll with infinite-scroll
paginate TestPagination, TestManyRelPaginDTO with pagination
filter TestEntity, TestServiceImpl, TestServiceClass, SuperMegaLargeTestEntity
service TestServiceImpl, TestManyRelPaginDTO with serviceImpl
service TestServiceClass with serviceClass
dto TestMapstruct, TestManyRelPaginDTO with mapstruct
clientRootFolder Division, Place with test-root

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.20.1

node: v10.15.0

npm: 6.7.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.21.2, build a133471

INFO! Congratulations, JHipster execution is complete!

### PR DESCRIPTION
**Pull request by ruddell**
- entity form should use relationshipFieldNamePlural for many-to-many relationships to match the entity fields to the form fields
- mapping form data to entity can't use model constructor as some fields should not be sent in request but are in the constructor (such as `many-to-one` relations) 
- faker data can only have a max userId of 2 (oauth doesn't have > 2)

Fix #9347

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by wmarques** [comment]
@ruddell would it be possible to use object spread to overwrite object properties instead of doing `entity.id = form.get` ? I  prefer this notation than object mutation... WDYT ?

**Comment by ruddell** [comment]
The following code works since all the field names match the form fields:
 
    return { ...this.editForm.value };

Is that what you mean? Otherwise can you give me an example of how to do that with an entity model/interface?

**Comment by wmarques** [comment]
For instance I can see that you are doing the following:
```
const entity = new <%= entityAngularName %>()
        entity.id = this.editForm.get(['id']).value
```

instead of doing this I would prefer:
```
const entity = {
...new EntityAngularName(),
id: this.editForm.get('id').value
```

And same goes one for other overrided properties. But if it's too complicated to manage for generation, let's keep it that way :)

**Comment by DanielFran** [comment]
Closing/Reopening to launch tests

**Comment by DanielFran** [comment]
Test failing are not related with Angular, so merging it.

**Pull request merged**
