### PR TITLE
Fix Swagger UI for Microservices

### LINKED ISSUE #8328: Swagger UI doesnt work on Gateways and Registry for microservices
Issue separated from https://github.com/jhipster/generator-jhipster/issues/8301 see #8301 for details

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix https://github.com/jhipster/generator-jhipster/issues/8196
Fix #8328 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
Well done @pascalgrimaud !

**Comment by pascalgrimaud** [comment]
@PierreBesson : look like, you prefer this solution :)

@ndywicki : if you can test this fix, it would be cool!

**Comment by pascalgrimaud** [comment]
ping @TonyLuo : if you can have a look and test too :)

**Comment by TonyLuo** [comment]
@pascalgrimaud I tested it locally, it works... I will try to test it in cloud server later

**Comment by pascalgrimaud** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/5115

**Comment by ndywicki** [comment]
@pascalgrimaud re-gzip the response body also working for me. thanks !

**Comment by pascalgrimaud** [comment]
thanks for your feedback @ndywicki !

**Pull request merged**
