### PR TITLE
Neo4j relation rework Spring boot 2.4

### PR DESCRIPTION
**Pull request by Evertude**
Spring boot 2.4 version of https://github.com/jhipster/generator-jhipster/pull/13106

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by atomfrede** [comment]
Thanks @Evertude, sorry for taking so long to give you a proper review, will try to do it over the weekend but both PRs look fine at first look. Will try to test both.

**Comment by mraible** [comment]
Please rebase to fix conflicts.

**Comment by mraible** [comment]
@Evertude Can you please fix the conflicts in this PR?

**Comment by DanielFran** [comment]
@Evertude Can you please fix the conflicts now that the migration to spring-boot 2.4.x is stable? Thanks

**Comment by mraible** [comment]
Are these changes necessary for Spring Boot 2.4, or just a refactoring optimization?

**Comment by atomfrede** [comment]
As the neo4j boot integration has moved from neo to spring it is "required". I can take this and rebase @Evertude 's branch

**Comment by DanielFran** [comment]
Superseded by #https://github.com/jhipster/generator-jhipster/pull/13763

**Pull request closed without merging**
