### PR TITLE
Support for reactive applications in entity subgenerator

### LINKED ISSUE #11404: Update entity generator to support reactive applications
##### **Overview of the feature request**

One of the last remaining items to move our Reactive/WebFlux support (https://github.com/jhipster/generator-jhipster/issues/7608) to beta is to update the entity generator and its tests.

- [ ] Entities with service
- [ ] Entities without service
- [ ] Entities tests with `WebTestClient`

##### **Motivation for or Use Case**

I'm opening these tasks as a new issue so we can assign a bug bounty to it and hopefully accelerate its development. Selfishly, I'd like to demo our WebFlux support with microservices in March.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by murdos**
Status:
- [x] Entities without Service, Pagination and DTO
- [x] Entities with DTO
- [x] Entities with Pagination
- [x] Entities with Pagination and DTO
- [x] Entities with ServiceClass
- [x] Entities with ServiceClass and DTO
- [x] Entities with ServiceClass and Pagination
- [x] Entities with ServiceClass and Pagination and DTO
- [x] Entities with ServiceImpl
- [x] Entities with ServiceImpl and DTO
- [x] Entities with ServiceImpl and Pagination
- [x] Entities with ServiceImpl and Pagination and DTO
- [x] Entities integration tests with `WebTestClient`

Fixes #11404

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by murdos** [comment]
PR is ready for review! ;-)

**Comment by mraible** [comment]
@murdos I merged your branch with my `reactive-gateway` branch and tested this.

I started by creating one of my favorite microservice demos. I created a JDL that uses NoSQL databases.

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    databaseType couchbase,
    devDatabaseType couchbase,
    prodDatabaseType couchbase,
    serviceDiscoveryType eureka,
    testFrameworks [protractor],
    reactive true
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    serverPort 8081,
    serviceDiscoveryType eureka
    reactive true
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    searchEngine elasticsearch,
    serverPort 8082,
    serviceDiscoveryType eureka,
    reactive true
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}

// will be created under 'kubernetes' folder
deployment {
  deploymentType kubernetes
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}
```

I created a directory called `reactive-stack`, added this file as `apps.jdl` and ran `jhipster import-jdl apps.jdl`. 

After that, I ran `./mvnw verify` in `store` and discovered I had to clone [JHipster BOM](https://github.com/jhipster/jhipster) and install it locally.

Then I ran `./mvn verify` on the `blog`, `store`, and `gateway`.

The `blog` project fails to compile with one error:

```

**Comment by mraible** [comment]
@murdos That's excellent to hear! I'll try and test it before I go to bed tonight.

**Comment by mraible** [comment]
Same steps as before (where I merged it with my `reactive-gateway` branch)...

I created a directory called `reactive-stack`, created a similar JDL file and imported. Results:

```
store - mvn verify - fail
```

Cause:

```
[ERROR] Failures:
[ERROR]   ProductResourceIT.createProduct:136
Wanted but not invoked:
productSearchRepository bean.save(
    Product{id=5e61e02c66d9291ddc818ffd, title='AAAAAAAAAA', price=0, image='[B@154cceec', imageContentType='image/jpg'}
);
-> at com.okta.developer.store.web.rest.ProductResourceIT.createProduct(ProductResourceIT.java:136)
Actually, there were zero interactions with this mock.

[ERROR]   ProductResourceIT.deleteProduct:329
Wanted but not invoked:
productSearchRepository bean.deleteById(
    "5e61e02c66d9291ddc818ffa"
);
-> at com.okta.developer.store.web.rest.ProductResourceIT.deleteProduct(ProductResourceIT.java:329)
Actually, there were zero interactions with this mock.

[ERROR]   ProductResourceIT.updateProduct:285
Wanted but not invoked:
productSearchRepository bean.save(
    Product{id=5e61e02b66d9291ddc818ff8, title='BBBBBBBBBB', price=1, image='[B@771d1db1', imageContentType='image/png'}
);
-> at com.okta.developer.store.web.rest.ProductResourceIT.updateProduct(ProductResourceIT.java:285)
Actually, there were zero interactions with this mock.

[ERROR] Errors:
[ERROR]   UserServiceIT.testUserDetailsWithUsername » IllegalState Failed to load Applic...
[INFO]
[ERROR] Tests run: 40, Failures: 3, Errors: 1, Skipped: 0
```

This seems to be because of Elasticsearch, which is now a default. I removed `searchEngine` from the `store` application definition and tried again.

```
store - mvn verify - pass
blog - mvn verify - pass
gateway - mvn verify - pass
gateway - yarn e2e - fail
```

Here's the console output from the last one. Please fix, I'll merge, and we can celebrate! 🎉

```
  Blog e2e test
    ✓ should load Blogs
    ✓ should load create Blog page
    1) should create and save Blogs
    2) should delete last Blog

  Post e2e test
    ✓ should load Posts
    ✓ should load create Post page
    3) should create and save Posts
    4) should delete last Post

  Tag e2e test
    5) "before all" hook: ret for "should load Tags"
    6) "after all" hook: ret for "should delete last Tag"

  Product e2e test
    7) "before all" hook: ret for "should load Products"
    8) "after all" hook: ret for "should delete last Product"


  12 passing (21s)
  8 failing
```

**Comment by murdos** [comment]
Yes, elasticsearch is not yet supported globally in reactive context (see https://github.com/jhipster/generator-jhipster/issues/7608). I plan to work on it, once I've finished with entities.

I'll try to reproduce your errors with your JDL and fix it ASAP.

**Comment by murdos** [comment]
@mraible : I reproduced the issue, but I don't really how to fix it because it doesn't seem to be strictly related to the entity code (it works fine for a monolith). 
I've the feelings that it's related to the gateway because gateway's log shows a lot of re-authentication (`o.z.problem.spring.common.AdviceTraits   : Unauthorized: Not Authenticated`)

**Comment by mraible** [comment]
@murdos If it works for a monolith, but not microservices, I can take a look.

**Comment by mraible** [comment]
I generated a monolith with the following JDL:

```
application {
  config {
    baseName mono,
    packageName com.okta.developer.mono,
    applicationType monolith,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    searchEngine elasticsearch,
    serviceDiscoveryType eureka,
    testFrameworks [protractor],
    reactive true
  }
  entities Product
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

paginate Product with pagination
```

Then I ran `./mvnw test -Dtest=ProductResourceIT -P'!webpack,dev'` and was able to reproduce the test failures.

```
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ProductResourceIT.createProduct:137
Wanted but not invoked:
productSearchRepository bean.save(
    Product{id=5e671f040e3a704e70d0fae0, title='AAAAAAAAAA', price=0, image='[B@7727a81c', imageContentType='image/jpg'}
);
-> at com.okta.developer.mono.web.rest.ProductResourceIT.createProduct(ProductResourceIT.java:137)
Actually, there were zero interactions with this mock.

[ERROR]   ProductResourceIT.deleteProduct:330
Wanted but not invoked:
productSearchRepository bean.deleteById(
    "5e671f040e3a704e70d0fadd"
);
-> at com.okta.developer.mono.web.rest.ProductResourceIT.deleteProduct(ProductResourceIT.java:330)
Actually, there were zero interactions with this mock.

[ERROR]   ProductResourceIT.updateProduct:286
Wanted but not invoked:
productSearchRepository bean.save(
    Product{id=5e671f040e3a704e70d0fadb, title='BBBBBBBBBB', price=1, image='[B@106a5725', imageContentType='image/png'}
);
-> at com.okta.developer.mono.web.rest.ProductResourceIT.updateProduct(ProductResourceIT.java:286)
Actually, there were zero interactions with this mock.

[ERROR] Errors:
[ERROR]   ProductResourceIT.checkTitleIsRequired » IllegalState Failed to load Applicati...
[INFO]
[ERROR] Tests run: 11, Failures: 3, Errors: 1, Skipped: 0
```

The `IllegalState` failure prints out `availableProcessors is already set to [12], rejecting [12]`. This seems like it might be caused by test containers https://github.com/testcontainers/testcontainers-java/issues/1009.

I tried fixing it by the workaround suggested in that issue:

```
@BeforeEach
public void initTest() {
    System.setProperty("es.set.netty.runtime.available.processors", "false");
    productRepository.deleteAll().block();
    product = createEntity();
}
```

This doesn't help. So I looked in `ProductResource.java` and there doesn't seem to be any code for interacting with Elasticsearch. If I look in your `save_reactive_template.ejs`, there doesn't seem to be any logic to include Elasticsearch like there is in `save_template.ejs` (on line 57).

If I modify `ProductResourceIT` to have some calls to ES, there's fewer test failures.

```
[ERROR] Failures:
[ERROR]   ProductResourceIT.deleteProduct:330
Wanted but not invoked:
productSearchRepository bean.deleteById(
    "5e671e64920f21632ea2a47c"
);
-> at com.okta.developer.mono.web.rest.ProductResourceIT.deleteProduct(ProductResourceIT.java:330)
Actually, there were zero interactions with this mock.

[ERROR] Errors:
[ERROR]   ProductResourceIT.checkTitleIsRequired » IllegalState Failed to load Applicati...
[INFO]
[ERROR] Tests run: 11, Failures: 1, Errors: 1, Skipped: 0
```

Here's the diff of the test after my changes.

```diff
diff --git a/src/main/java/com/okta/developer/mono/web/rest/ProductResource.java b/src/main/java/com/okta/developer/mono/web/rest/ProductResource.java
index 671634b..938fcd5 100644
--- a/src/main/java/com/okta/developer/mono/web/rest/ProductResource.java
+++ b/src/main/java/com/okta/developer/mono/web/rest/ProductResource.java
@@ -73,7 +73,8 @@ public class ProductResource {
         if (product.getId() != null) {
             throw new BadRequestAlertException("A new product cannot already have an ID", ENTITY_NAME, "idexists");
         }
-    return productRepository.save(product)
+        this.productSearchRepository.save(product);
+        return productRepository.save(product)
             .map(result -> {
                 try {
                     return ResponseEntity.created(new URI("/api/products/" + result.getId()))
@@ -100,7 +101,8 @@ public class ProductResource {
         if (product.getId() == null) {
             throw new BadRequestAlertException("Invalid id", ENTITY_NAME, "idnull");
         }
-    return productRepository.save(product)
+        this.productSearchRepository.save(product);
+        return productRepository.save(product)
             .switchIfEmpty(Mono.error(new ResponseStatusException(HttpStatus.NOT_FOUND)))
             .map(result -> ResponseEntity.ok()
```

**Comment by murdos** [comment]
@mraible : why are you still testing will elasticsearch enabled? I already told you it was not supported (https://github.com/jhipster/generator-jhipster/pull/11416#issuecomment-595688862) and that I was going to handle this in another PR because this one is already quite big.

**Comment by murdos** [comment]
I've added a check in the entity subgenerator for elasticsearch, there's now an explicit message saying that this is not supported yet.

**Comment by mraible** [comment]
Sorry about that. I'll try again without Elasticsearch.

**Comment by cbornet** [comment]
R2DBC support is almost ready. Do we add entity support for it in this issue or do we create another one ? Knowing that hardest part will be supporting relationships esp. if they are required. And probably some field types will need special conversions.

**Comment by murdos** [comment]
> 
> 
> R2DBC support is almost ready. Do we add entity support for it in this issue or do we create another one ? Knowing that hardest part will be supporting relationships esp. if they are required. And probably some field types will need special conversions.

I've no opinion on using the same issue or another one (I was planning to give a try on R2BC entity, but it can indeed be quite big and complex), however I really would like to have different PRs to avoid maintaining an huge branch and having to resolve conflicts on it.

**Comment by mraible** [comment]
@cbornet I'd do it in another PR after this one is merged.

I tried testing things again this morning. I started with a monolith JDL:

```
application {
  config {
    baseName blog,
    applicationType monolith,
    packageName com.jhipster.demo.blog,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    buildTool maven,
    clientFramework react,
    useSass true,
    testFrameworks [protractor]
  }
  entities *
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll
```

Results:

- ✅ `./mvnw verify` OK
- ✅ `yarn e2e` OK

Then I tested a microservice JDL:

```
application {
  config {
    baseName gateway,
    packageName com.okta.developer.gateway,
    applicationType gateway,
    authenticationType oauth2,
    databaseType couchbase,
    devDatabaseType couchbase,
    prodDatabaseType couchbase,
    serviceDiscoveryType eureka,
    testFrameworks [protractor],
    reactive true
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog,
    packageName com.okta.developer.blog,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    serverPort 8081,
    serviceDiscoveryType eureka
    reactive true
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store,
    packageName com.okta.developer.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka,
    reactive true
  }
  entities Product
}

entity Blog {
  name String required minlength(3),
  handle String required minlength(2)
}

entity Post {
  title String required,
  content TextBlob required,
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required,
  price BigDecimal required min(0),
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User,
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
  monitoring elk
  consoleOptions [zipkin]
}
```

Results:

- ✅ `./mvnw verify` OK
- ✅ `yarn e2e` KO

```
  Blog e2e test
    ✓ should load Blogs
    ✓ should load create Blog page
    1) should create and save Blogs
    2) should delete last Blog

  Post e2e test
    ✓ should load Posts
    ✓ should load create Post page
    3) should create and save Posts
    4) should delete last Post
```

If I try to add a blog manually, it works, but redirects me back to the homepage. If I try to edit it, it gets an access denied, logs in again, then redirects back to the page. Investigating now...

**Comment by mraible** [comment]
I tried changing the gateway's database to mongodb. 

- ✅ `./mvnw verify` OK
- ✅ `yarn e2e` KO

If I look at the request that fails, the request headers are:

```
GET /services/blog/api/blogs/5e67a9d80d194b5b62617411 HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Accept: application/json, text/plain, */*
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:8080/blog
Accept-Encoding: gzip, deflate, br
Accept-Language: en,en-US;q=0.9
Cookie: JSESSIONID_REGISTRY=tNbrj9XBVuNsu7HktuMtD27QwuFd6pEkfyJum300; XSRF-TOKEN=55a08cc4-7c61-4a62-b9ff-4ce0f7618083
```

And the response:

```
HTTP/1.1 401 Unauthorized
Content-Type: application/problem+json
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
X-XSS-Protection: 1 ; mode=block
Feature-Policy: geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'self'; payment 'none'
Content-Security-Policy: default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:
Referrer-Policy: strict-origin-when-cross-origin
content-length: 247
```

If I look at the one that succeeds, they are:

```
GET /services/blog/api/blogs HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Accept: application/json, text/plain, */*
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:8080/blog
Accept-Encoding: gzip, deflate, br
Accept-Language: en,en-US;q=0.9
Cookie: JSESSIONID_REGISTRY=tNbrj9XBVuNsu7HktuMtD27QwuFd6pEkfyJum300; XSRF-TOKEN=55a08cc4-7c61-4a62-b9ff-4ce0f7618083; SESSION=c1e5ecf2-2a67-46f4-ace4-977d624cd818
```

And its response headers:

```
HTTP/1.1 200 OK
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json
Content-Length: 99
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
X-XSS-Protection: 1 ; mode=block
Feature-Policy: geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'self'; payment 'none'
Content-Security-Policy: default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:
Referrer-Policy: strict-origin-when-cross-origin
Set-Cookie: SESSION=; Path=/; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; SameSite=Lax
```

I'm still not sure what's causing this problem.

**Comment by mraible** [comment]
I tried creating the "blog" app as a non-reactive app and e2e tests pass. I then compared the `SecurityConfiguration` classes and found that MVC sets things to stateless, while WebFlux does not. I added the following to WebFlux and it solves the problem!

```
http
	.requestCache()
		.requestCache(NoOpServerRequestCache.getInstance());
```

Thanks to @rwinch for this tip! https://github.com/spring-projects/spring-security/issues/6552#issuecomment-515571416

**Comment by murdos** [comment]
Thanks @mraible for the stateless fix and the merge! 
I'll try to handle reactive elasticsearch (I hope it will be quick), and then will come back to entities with R2BC.

**Pull request merged**
