### PR TITLE
removed zuul proxy dependent files for gateways without service discovery

### LINKED ISSUE #9877: OAuth2 without service discovery: gateway compilation errors
##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/alexandrastefanova/developer/projects/urban/gateway
└── generator-jhipster@6.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.urban.gateway"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.urban.gateway",
    "packageFolder": "com/urban/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "clientTheme": "journal",
    "clientThemeVariant": "primary",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Profile
relationship OneToOne {
  Profile{user(login)} to User
}

dto Profile with mapstruct
paginate Profile with infinite-scroll
service Profile with serviceClass
filter Profile

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.13.1

node: v10.15.1

npm: 6.9.0

yeoman: 2.0.5

yarn: 1.13.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Overview of the issue**

gateway process fails to compile class AuthorizationHeaderFilter with com.netflix.zuul not found error

##### **Motivation for or Use Case**

I want to deploy to a GCP kubernetes cluster with ingress/istio for load balancing.  So i choose to generate a jhipster gateway  without a jhipster registry 

##### **Reproduce the error**

generate a microservices gateway without a registry and with oauth2 authentication and compile it

##### **JHipster Version(s)**

6

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.urban.gateway"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.urban.gateway",
    "packageFolder": "com/urban/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "clientTheme": "journal",
    "clientThemeVariant": "primary",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

profile.json

{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [
        {
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "one-to-one",
            "otherEntityField": "login",
            "ownerSide": true,
            "useJPADerivedIdentifier": true,
            "otherEntityRelationshipName": "profile"
        }
    ],
    "fields": [],
    "changelogDate": "20190609151112",
    "dto": "mapstruct",
    "searchEngine": false,
    "service": "serviceClass",
    "entityTableName": "profile",
    "databaseType": "sql",
    "jpaMetamodelFiltering": true,
    "pagination": "infinite-scroll"
}

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by Hawkurane**
Fixes compilation error for gateways without service discovery

Fixes #9877 

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
@Hawkurane I think you should instead add a check that throws an error for the combination no discovery + gateway.

**Comment by ruddell** [comment]
I think the reason "gateways without service discovery" is possible is for Istio, related issue https://github.com/jhipster/generator-jhipster/issues/7337 and PR https://github.com/jhipster/generator-jhipster/pull/7695

**Comment by Hawkurane** [comment]
Indeed in that case it would be better to just removed zuul related files to fix the compilation errors. PR has been updated

**Comment by pascalgrimaud** [comment]
@Hawkurane : there are some conflict in this PR, I can't fix it for you as  it seems you deleted your fork, is it right ?

**Comment by pascalgrimaud** [comment]
I took your code and did a new PR: https://github.com/jhipster/generator-jhipster/pull/10207
So I'm closing this. But don't forget to claim the bounty as soon as it's merged

**Comment by Hawkurane** [comment]
Hello @pascalgrimaud , I've claimed the bounty:
https://opencollective.com/generator-jhipster/expenses/9525

Thanks :)

**Comment by pascalgrimaud** [comment]
@Hawkurane : just approuved. Thanks for your work !

**Pull request closed without merging**
