### PR TITLE
Move needle api to generators

### PR DESCRIPTION
**Pull request by avdev4j**
After a discussion with @deepu105 and @murdos we decide to test to move needle api into each generators they belong.

I'm starting with server generator. If this modification is ok for us I will adding the client part.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by avdev4j** [comment]
ah ah ah
I was sure you will note the "internal" folder. And of course you totally right. To make the change easier I kept the original path.

I added this folder because I planned to add "api" folders like "JsonWriteFiles".

We have to consider this possibility.

If we decide to not finally keep it, the final PR will looks like:

> needle-api.js
> needle-base.js
> - server
>     - needle-api
>        needle-server-maven.js
>        ...

**Comment by murdos** [comment]
:-)

> I added this folder because I planned to add "api" folders like "JsonWriteFiles".
> 

I'm not sure to understand what you mean... what is "JsonWriteFiles"?

> If we decide to not finally keep it, the final PR will looks like:
> 
> > needle-api.js
> > needle-base.js
> > 
> > * server
> >   
> >   * needle-api
> >     needle-server-maven.js
> >     ...

That's what I had in mind, and it looks fine to me.

**Comment by murdos** [comment]
BTW do you know if yesterday meetup has been recorded, and if it'll be published?
I'm curious to see your talk about blueprints ^^

**Comment by deepu105** [comment]
Lets wait as we are planning to revert the other PR that broke last patch
version

**Comment by avdev4j** [comment]
If I understand we have to  : 
- merge the #9151
- close the #9159
- rebase, resolve conflicts and merge this one.

In the same time I'm working for adding unit tests.

**Pull request merged**
