### PR TITLE
Attempt to fix Failing React Builds #11805

### PR DESCRIPTION
**Pull request by skmaingi**
Related to #11805.

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
@skmaingi Hello there, to bring you up to speed: the e2e tests are flaky. They sometimes pass, and sometimes they fail. Having everything "green" here doesn't mean it's fixed. That's why I've forked the project and duplicated react builds (we're talking 60 react  builds) just to try and see errors. Right now, only the memcached-related builds fail because they have data. As the tests aren't that well designed, they no separation is done between the "no entry" case and the "the table is filled" case.

**Comment by skmaingi** [comment]
@MathieuAA I have made a few changes. All the checks have passed but you can verify this

**Comment by MathieuAA** [comment]
I'll try to do so today, it's gonna be a very busy day for me :(

**Comment by skmaingi** [comment]
@mshima I request your help to verify if this bug is fixed.

**Comment by mshima** [comment]
@skmaingi I've triggered 2 additional builds 2 days ago and they passed.
Triggered one more and 1 test failed, looks like it improved, but it's not completely fixed yet.

See the failure https://github.com/jhipster/generator-jhipster/pull/11916/checks?check_run_id=765664707.

**Comment by skmaingi** [comment]
Thank you @mshima

**Comment by skmaingi** [comment]
A backend test has failed.

```
[ERROR] Tests run: 17, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.689 s <<< FAILURE! - in io.github.jhipster.sample.web.rest.UserResourceIT
[ERROR] io.github.jhipster.sample.web.rest.UserResourceIT.updateUser  Time elapsed: 0.048 s  <<< ERROR!
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
	at io.github.jhipster.sample.web.rest.UserResourceIT.updateUser(UserResourceIT.java:296)
Caused by: org.hibernate.exception.DataException: could not execute statement
	at io.github.jhipster.sample.web.rest.UserResourceIT.updateUser(UserResourceIT.java:296)
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
	at io.github.jhipster.sample.web.rest.UserResourceIT.updateUser(UserResourceIT.java:296)

[INFO] Running io.github.jhipster.sample.web.rest.errors.ExceptionTranslatorIT
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.088 s - in io.github.jhipster.sample.web.rest.errors.ExceptionTranslatorIT
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   UserResourceIT.updateUser:296 » DataIntegrityViolation could not execute state...
[INFO] 
[ERROR] Tests run: 864, Failures: 0, Errors: 1, Skipped: 0
```
#11805

**Comment by mshima** [comment]
@skmaingi just triggered a rebuild. The failure was due to server startup.

**Comment by skmaingi** [comment]
@mshima Thank you for assistance

**Comment by skmaingi** [comment]
@mshima Could this error `#[error]src/test/javascript/e2e/entities/entity-with-dto/entity-with-dto.spec.ts(174,5): error TS2304: Cannot find name 'entityWithDTODeleteDialog' ` be a server issue

**Comment by skmaingi** [comment]
> @mshima Could this error `#[error]src/test/javascript/e2e/entities/entity-with-dto/entity-with-dto.spec.ts(174,5): error TS2304: Cannot find name 'entityWithDTODeleteDialog' ` be a server issue

@mshima It's related to merge changes.

**Comment by SudharakaP** [comment]
@MathieuAA @mshima  : I didn't follow this thread from the beginning so I am not sure exactly what should be done or if this is in complement to the other PRs on the same topic, but I noticed this PR is getting larger and larger day by day. Maybe we should break it or something. :thinking:

**Comment by mshima** [comment]
@SudharakaP I think it's @skmaingi call to split or not.
Most of the changes are test related, the other changes are related to issues @skmaingi discovered while trying to fix flaky react e2e.

Once react e2e is stable, then we should decide to revert the change that made this branch conflicts (since it didn't fixed flaky react e2e), or master should be merged to this branch.

**Comment by mshima** [comment]
Closing/reopening to trigger CI.

**Comment by skmaingi** [comment]
> Most of the changes are test related, the other changes are related to issues @skmaingi discovered while trying to fix flaky react e2e.

@SudharakaP As @mshima said, the PR was an attempt to fix flaky react e2e #11805  but noticed others issues where one was closed #11909 and another is still open #11931. Didn't know the PR would get this big but hoping to have a stable commit to have this PR closed.

**Comment by skmaingi** [comment]
@SudharakaP @MathieuAA @mshima 
The react tests have passed. There is a failing Angular test. 
I made changes to Account, Administration e2e tests
I did also add additional e2e tests for viewing and updating an entity.

Going forward, I feel the test entities need to be updated to conform to the structure of JHipster frameworks.
One challenge I experienced was naming of entity which affected e2e tests for toast displayed on Create, Update and Delete actions.
This issue affects all test entities in test-root directory
```
  1) BankAccount e2e test
       should create and save BankAccounts:
     AssertionError: expected 'A new testRootBankAccount is created with identifier 2251' to include 'A new bankAccount is created with identifier'
      at /home/runner/app/src/test/javascript/e2e/entities/test-root/bank-account-my-suffix/bank-account-my-suffix.spec.ts:99:42
  2) BankAccount e2e test
       should update last BankAccount:
     AssertionError: expected 'A testRootBankAccount is updated with identifier 2251' to include 'A bankAccount is updated with identifier'
  3) BankAccount e2e test
       should delete last BankAccount:
     AssertionError: expected 'A testRootBankAccount is deleted with identifier 2251' to include 'A bankAccount is deleted with identifier'
...
  12) Place e2e test
       should delete last Place:
     AssertionError: expected 'A testRootPlace is deleted with identifier 2401' to include 'A place is deleted with identifier'
```

**Comment by skmaingi** [comment]
The failed Backend Angular test error:
```
Task :integrationTest
WARNING: Please consider reporting this to the maintainers of com.hazelcast.internal.networking.nio.SelectorOptimizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

SuperMegaLargeTestEntityResourceIT > updateSuperMegaLargeTestEntity() FAILED
    javax.persistence.PersistenceException at SuperMegaLargeTestEntityResourceIT.java:77
        Caused by: org.hibernate.exception.DataException at SuperMegaLargeTestEntityResourceIT.java:77
            Caused by: org.postgresql.util.PSQLException at SuperMegaLargeTestEntityResourceIT.java:77
...
FAILURE: Build failed with an exception.
> Task :integrationTest FAILED

* What went wrong:
Execution failed for task ':integrationTest'.

> There were failing tests. See the results at: file:///home/runner/app/build/test-results/integrationTest/
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
```

**Comment by mshima** [comment]
Closing/reopen to duplicate builds.

**Comment by skmaingi** [comment]
> Closing/reopen to duplicate builds.

There is a problem with "Test ms-ngx-gateway-eureka-uaa failed" JHipster installation
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project jhipster-framework: Execution attach-javadocs of goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar failed: Plugin org.apache.maven.plugins:maven-javadoc-plugin:3.2.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-javadoc-plugin:jar:3.2.0 -> org.apache.maven:maven-core:jar:3.0 -> org.apache.maven:maven-settings-builder:jar:3.0 -> org.codehaus.plexus:plexus-component-annotations:jar:2.0.0: Failed to read artifact descriptor for org.codehaus.plexus:plexus-component-annotations:jar:2.0.0: Could not transfer artifact org.codehaus.plexus:plexus-component-annotations:pom:2.0.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-component-annotations/2.0.0/plexus-component-annotations-2.0.0.pom: Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jhipster-framework
```

**Comment by mshima** [comment]
@skmaingi you can focus at just react e2e failures, most of the failures are related to error downloading maven/npm dependencies, starting docker services, and some random failures.

@skmaingi last time I checked #11923 didn't fixed the flaky react e2e, but seems @sendilkumarn improved it and it's kind of fixed now.

Since #11923 last commit, there were 6 CI builds at master branch, none of the 3 failures are related to react e2e. There is 8 PRs requests with only 1 failure and it's related to react e2e (https://github.com/jhipster/generator-jhipster/pull/11973/checks?check_run_id=794165738).

So looks like you will have to rebase or merge your PR against master.

**Comment by mshima** [comment]
Another issue point is that your PR makes react e2e take ~50% more time to finish comparing with current master.

**Comment by skmaingi** [comment]
> Another issue point is that your PR makes react e2e take ~50% more time to finish comparing with current master.

@mshima Likely because of the new e2e tests that I added; viewing and updating an entity.

**Comment by skmaingi** [comment]
> @skmaingi you can focus at just react e2e failures, most of the failures are related to error downloading maven/npm dependencies, starting docker services, and some random failures.
> 
> @skmaingi last time I checked #11923 didn't fixed the flaky react e2e, but seems @sendilkumarn improved it and it's kind of fixed now.
> 
> Since #11923 last commit, there were 6 CI builds at master branch, none of the 3 failures are related to react e2e. There is 8 PRs requests with only 1 failure and it's related to react e2e (https://github.com/jhipster/generator-jhipster/pull/11973/checks?check_run_id=794165738).
> 
> So looks like you will have to rebase or merge your PR against master.

 @mshima My last commit has no errors related to react. The only error is related to "Test ms-ngx-gateway-eureka-uaa failed". Glad @sendilkumarn managed to fix flaky react e2e. I believe there would be no need to continue working on the issue. 
@pascalgrimaud  I will remove the expense claim I made on pull request #11909 for #11805

**Pull request closed without merging**
