### PR TITLE
cache is fail in brower, in prod profile

### PR DESCRIPTION
**Pull request by gemron**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
Ok that indeed is a good plan. Just let me know if you need me to do
anything


Thanks & Regards,
Deepu

**Comment by ruddell** [comment]
@jdubois That's true for AngularJS.  In production with Angular (2+), all fonts, images, and js files are located on the base path

**Comment by jdubois** [comment]
@ruddell yes I know, this is the main reason why Angular 4 is still in beta, the prod build is not yet finished. I don't think we have hashes everywhere, so they shouldn't be cached, or people won't have their JS updated when a new version is released.

**Comment by ruddell** [comment]
All JS bundles, images, and fonts are hashed during the prod build, with the exception of `vendor.dll.js`

**Comment by gemron** [comment]
thanks! I hope jhipster  can fix it . 
another issure is:    jhipster 's client in prod is so big ,brower init vendor and main js is so slowly.I hope it  jhipster 's client  support lazy load.

**Pull request closed without merging**
