### PR TITLE
Add ability to create multiple user roles from a separate generator

### PR DESCRIPTION
**Pull request by gzsombor**
This is a solution for #780 but in a separate generator, so no additional question is asked during the initialization.

### CODE REVIEW

**Comment by fontanellif** [comment]
I don't know if it's the right place for this type of question but i would like to use this functionality. how can I do?

**Comment by deepu105** [comment]
@gzsombor I guess this would have been more useful if this could have been done from within application rather than the generator. but i guess its more complex im trying to find a simpler way to do that as i require ability to create dynamic roles and map access to modules

**Comment by gzsombor** [comment]
From the application? This needs to modify the source code of your application, at least in the frontend - you have to mark pages as accessible only by users with a specific roles. So I can't see, what could be the advantages to create new roles inside the running application. Maybe, if there were 'groups of roles' entity, which can be assigned to users, that could be nice to configured runtime. But that would be totally different

**Comment by deepu105** [comment]
@gzombor in a realworld application you would create roles and assign that role with access to different modules or pages and the give a user a role. No users will want to do a code change to achieve that, tole management has to be done at runtime, and i really dont like the way roles are applied to each routes now its too manual and tough to maintain 
i have seen 100s of enterprise applications and role management has always been this way by requirement
the current way of role management would work only for small applications and applications like blogs and stuff it will not work for complex application with different types of users

**Pull request closed without merging**
