### PR TITLE
Default application name suggestion changed to current directory name

### PR DESCRIPTION
**Pull request by tapas4java**
Instead of suggesting `jhipster` as the default application name, better to suggest current directory name as app name

### CODE REVIEW

**Comment by mraible** [comment]
+1. I like this change because it would also help to alert the user when they're not creating the project in the directory they expect to be in.

**Comment by tapas4java** [comment]
As user already created the directory for his application, It makes more sense to suggest the same name as it will avoid typing same name again.

**Comment by andidev** [comment]
+1

**Comment by pascalgrimaud** [comment]
Current directory name can have special caracters -> `Your application name cannot contain special characters or a blank space, using the default name instead`

**Comment by tapas4java** [comment]
@pascalgrimaud ..Good point, So what is your suggestion?? 
Should we show `jhipster` if directory name contains special char or space(though this scenario will be less)?

**Comment by jdubois** [comment]
First of all: kudos for a very, very good idea.

Then I have some comments:

- This is the first time I see this, so this should behave differently than the other Yeoman generators. I know the issue with the current directory, but that's how Yeoman generators work, and we copy their usual way of working. This is of course very minor, that's just the default name -> so this isn't a true issue for me
- Yes @pascalgrimaud is correct: if the current directory as some wrong characters, we could something like _.slugify(name); but we need to check if the resulting name is always OK (otherwise let's use "jhispter" and get down with it!!)

**Comment by tapas4java** [comment]
Thanks @jdubois , Updating PR with below rule:

1. If dir name contains `[a-zA-Z0-9_-]` then show dir name else `jhipster`

**Comment by jdubois** [comment]
Looking good!

**Pull request merged**
