### PR TITLE
Update spring-boot version to 2.5.7

### PR DESCRIPTION
**Pull request by DanielFran**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud As soon as this is merged, should be OK for next release.

**Comment by pascalgrimaud** [comment]
Waiting this since this morning. Our CI takes too much time :-(

**Comment by mshima** [comment]
We should avoid merging dependabot dependencies on release day, no need to have every module updated.

**Comment by mshima** [comment]
@pascalgrimaud there is something blocking our CI today, I will cancel some pending tests.

**Comment by pascalgrimaud** [comment]
I'm doing the same. Killing all useless CI

**Pull request merged**
