### PR TITLE
Fix dependency injection in Angular if i18n is enabled

### LINKED ISSUE #10476: Cannot inject JhiLanguageService into any core component
##### **Overview of the issue**

Regarding the Angular template: Cannot inject `JhiLanguageService` into any core component. As far as I see, as soon as `JhiLanguageService` is injected into any eagerly bootstrapped component, the app does not work anymore.

More precisely, within `AccountService.fetch()` `this.languageService` is undefined which causes any authentication to fail.

##### **Motivation for or Use Case**

What we try to achieve is, while loading the application, to set the language to the current browser language. Out attempt was to add the following to `JhiMainComponent`:

```
export class JhiMainComponent implements OnInit {
  constructor(
      ...
      private translateService: TranslateService,
      private languageService: JhiLanguageService) {}

  ngOnInit() {
    ...
    const languageKey = this.translateService.getBrowserLang();
    this.languageService.changeLanguage(languageKey);
  }
}
```

##### **Reproduce the error**

Create a new JHipster 6.3.1 application with the `angular` template. Then add the above lines to `JhiMainComponent`.

##### **Suggest a Fix**

As far as I see, the problem is that the constructor of `JhiLanguageService` calls `this.translateService.setDefaultLang(this.currentLang)` which in turn tries to load the language from the backend via HTTP. However due to the registered 

```
{
  provide: HTTP_INTERCEPTORS,
  useClass: AuthExpiredInterceptor,
  multi: true
}
```

that in turn demands 

```
constructor(private loginService: LoginService)
```

where `LoginService` demands

```
constructor(private accountService: AccountService, private authServerProvider: AuthServerProvider) {}
```

and `AccountService` in turn demands 

```
constructor(private languageService: JhiLanguageService, private sessionStorage: SessionStorageService, private http: HttpClient) {}
```

This causes a cyclic dependency

```
JhiLanguageService -> TranslateService -> AuthExpiredInterceptor -> LoginService -> AccountService -> JhiLanguageService
```

Thus the requested `JhiLanguageService` in the constructor of `AccountService` will be undefined and the whole authentication process breaks.

I don't know if our approach is wrong here (where to add our default behavior about languages), however the behavior and type of error seems something unwanted.

The only solutions I can think of is either

* switch the language later / lazily (where would be the best place to do this?)
* bypass the interceptors to load languages for internationalization (it does not seem useful to pass through an `AuthExpiredInterceptor` when loading languages that you need before the login has ever passed)

##### **JHipster Version(s)**

6.3.1

##### **JHipster configuration**

 jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
app@0.0.1-SNAPSHOT /home/user/workspace/app
└── generator-jhipster@6.3.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.3.0",
    "applicationType": "monolith",
    "baseName": "app",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "...",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "de"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

git version 2.17.1

node: v10.15.0

npm: 6.11.3

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.16.1, build 6d1ac21

##### **Browsers and Operating System**

```
Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
Ubuntu 18.04.3 LTS 
```

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by kaidohallik**
Fixes #10476

Depends on related `ng-jhipster` change jhipster/ng-jhipster#110, actions needed are:
* merge jhipster/ng-jhipster#110
* release new version of the `ng-jhipster`
* update this PR with the new version of the `ng-jhipster`
* merge this PR

I marked this PR as draft. Draft check can be removed after updating this PR with the new `ng-jhipster` version.

I moved also HTTP interceptor to core module which makes code better readable.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by kaidohallik** [comment]
Two notes.

1. e2e tests are failing because `generator-jhipster` is still using the old version of the `ng-jhipster` (the same problem as described in the #10476, the `languageService` is undefined in the `AccountService`). In my machine, if using `ng-jhipster` with modification jhipster/ng-jhipster#110 then e2e is successful.

2. Alternative solution exists, `languageService.init()` can be moved from generated app `CoreModule` constructor to `ng-jhipster` into `NgJhipsterModule` constructor. If this is preferred solution then I can modify PR-s.

It's just important to move `translateService.init()` out from `JhiLanguageService` constructor to avoid Angular DI instability.  
The reason of this instability is probably caused by cycle in DI: `HttpClient` --> `AuthExpiredInterceptor` --> `LoginService` --> `AccountService` --> `JhiLanguageService` --> currently in the constructor going back to `HttpClient`.

**Comment by kaidohallik** [comment]
Full path to cycle is:  
@angular/common/http.HttpClient -->  
app.AuthExpiredInterceptor -->  
app.LoginService -->  
app.AccountService -->  
ng-jhipster.JhiLanguageService -->  
@ngx-translate/core.TranslateService -->  
ng-jhipster.translatePartialLoader -->  
@angular/common/http.HttpClient

**Comment by wmarques** [comment]
@kaidohallik you can use ng-jhipster v0.11.2

**Comment by kaidohallik** [comment]
@wmarques thanks, I updated `package.json`, if CI passes then I remove draft status.

**Comment by kaidohallik** [comment]
CI passed and this PR is now ready for merge.

**Pull request merged**
