### PR TITLE
exceptions handled if no internationalization support

### PR DESCRIPTION
**Pull request by flaviencathala**

### CODE REVIEW

**Comment by jdubois** [comment]
Oh OK, sorry @deepu105

**Comment by jdubois** [comment]
@deepu105 I haven't revert it yet, could you have a look at the changes? This is just adding conditions for i18n: this is not doing anything with the regex, and without this the i18n option fails

**Comment by deepu105** [comment]
Ok ill revert it later. I know it fails but i wanted to do this similar to
what we do for ng1 so that we have less conditions to add and maintain.

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
No problem. I am travelling currently thats why couldn't close these. I
would have time this weekend to close the pending ng2 items.

Thanks & regards,
Deepu

**Pull request merged**
