### PR TITLE
Improve JSon serialization on bidirectional relationships

### LINKED ISSUE #6793: Improve JSon serialization on bidirectional relationships
##### **Overview of the issue**

When you have a bi-directional relationship between entities, you get the good old Jackson infinite recursion. JHipster uses `@JSonIgnore` to avoid this. But this can be improved with `@JsonIdentityInfo`

##### **Motivation for or Use Case**

Let's say you have a bidirectional OneToMany relationship between `SponsorAgreement` and `SponsorAgreementState`. JHipster generates the following code:

```
@Entity
public class SponsorAgreement implements Serializable {

    @OneToMany(mappedBy = "sponsorAgreement")
    @JsonIgnore
    private Set<SponsorAgreementState> states = new HashSet<>();
```

The problem with this `@JsonIgnore`, is that if you explicitelly create a query that returns all the states for a sponsor agreement with a join (`@Query("select sponsor_agreement from SponsorAgreement sponsor_agreement left join fetch sponsor_agreement.states")`) it will always be ignored. 

Getting rid of `@JsonIgnore` is doable (but not trivial). If you [read this blog](http://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion), there are several solutions:

* `@JsonBackReference` and `@JsonManagedReference` but this implies too much changes in JHipster
* `@JsonIdentityInfo` works pretty well... but slight changes need to be done in the client UI (the components listing all the entities).

##### **Suggest a Fix**

The best way is to use `@JsonIdentityInfo`, but it needs some fixes. If you change the entities by adding `@JsonIdentityInfo` we get the following (notice that `@JSonIgnore` is gone):

```
@Entity
@JsonIdentityInfo(
    generator = ObjectIdGenerators.PropertyGenerator.class,
    property = "id")
public class SponsorAgreement implements Serializable {

    @OneToMany(mappedBy = "sponsorAgreement")
    private Set<SponsorAgreementState> states = new HashSet<>();

@Entity
@JsonIdentityInfo(
    generator = ObjectIdGenerators.PropertyGenerator.class,
    property = "id")
public class SponsorAgreementState implements Serializable {
```

With this code, all the CRUD operations keep on working, which is nice. The only problem, is when displaying the list of `SponsorAgreementState` (in component `sponsor-agreement-state.component.html`). When you do a GET to get all the states, the produced JSon will look like this:

```
[ {
  "id" : 1001,
  "status" : "CREATED",
  "statusDate" : "2017-12-01T09:00:00Z",
  "sponsorAgreement" : {
    "id" : 951,
    "vatRate" : 20.0,
    "subtotal" : 20.0,
    "total" : 20.0,
    "states" : null
  }
}, {
  "id" : 1002,
  "status" : "SENT",
  "statusDate" : "2017-12-22T11:02:00Z",
  "sponsorAgreement" : 951
}, {
  "id" : 1003,
  "status" : "ABANDONED",
  "statusDate" : "2017-12-16T14:15:00Z",
  "sponsorAgreement" : 951
} ]
```

As you can see, the first state is still linked to the sponsor agreement, but not the other two who only get an id to the sponsor agreement:

* 1001: sponsorAgreement is filled, so the sponsorAgreementState.sponsorAgreement?.id is displayed
* 1002 and 1003: Jackson broke the recursion, and just displays the id (`"sponsorAgreement" : 951`)

So there is a bit of work to be done in list components (`sponsor-agreement-state.component.html`), because you could either display `sponsorAgreementState.sponsorAgreement?.id` or just `sponsorAgreementState.sponsorAgreement`. But that's all.

WDYT of such improvement of adding `@JsonIdentityInfo` on all entities (or DTOs) but also changing the behaviour of the the list compoents ? 

##### **Related issues**

* https://github.com/jhipster/generator-jhipster/issues/1569
* https://github.com/jhipster/generator-jhipster/issues/5855
* https://stackoverflow.com/questions/28111493/jhipster-one-to-many-relationship-cant-see-the-collection-on-client-side

##### **JHipster Version(s)**

```
bidirectjson@0.0.0 /Users/agoncal/Documents/Code/Temp/jhipster/bidirectjson
└── generator-jhipster@4.11.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.agoncal.bidirectjson"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "bidirectjson",
    "packageName": "org.agoncal.bidirectjson",
    "packageFolder": "org/agoncal/bidirectjson",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity SponsorAgreement (sponsor_agreement) {
  vatRate Float required,
  subtotal Float required,
  total Float required
}
entity SponsorAgreementState (sponsor_agreement_state) {
  status SponsorAgreementStatus required,
  statusDate Instant required
}

enum SponsorAgreementStatus {
  CREATED,
  SENT,
  ABANDONED,
  SIGNED
}

relationship OneToMany {
  SponsorAgreement{states} to SponsorAgreementState{sponsorAgreement required}
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.0

node: v8.9.0

npm: 5.5.1

bower: 1.8.0

gulp:
[12:40:09] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

- [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by Dufgui**
Improve JSon serialization on bidirectional relationships

read other relationship field name and provide it in @JsonIgnoreProperties

Fix #6793

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by BitFlipp3r** [comment]
Just to let you know. I've exchanged @JsonIgnore with @JsonIgnoreProperties in the current jhipster version to make bidirectional editing of relationships available and unfortunately this totally messes up your entity audit module @deepu105

**Comment by deepu105** [comment]
@BitFlipp3r do you know why? if so can you make a PR to fix it for the module as well

**Comment by Dufgui** [comment]
I will take a look tonight

**Comment by deepu105** [comment]
@Dufgui were you able to rebase?

**Comment by Dufgui** [comment]
Sorry i forgot.

**Comment by deepu105** [comment]
@jhipster/developers guys can someone tests and merge this, I have too much on my plate

**Comment by jdubois** [comment]
Great work!

**Pull request merged**
