### PR TITLE
Execute tests based on changed files.

### PR DESCRIPTION
**Pull request by mshima**
- Only execute backend or client tests if there are changes that will affect them.
- Skip the workflow entirely if changes that needs be tested are not detected.
- Reduced entities generated for devserver tests.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by atomfrede — APPROVED** [review]

**Comment by DanielFran** [comment]
@mshima @pascalgrimaud Since this has been merged, it fails in main

**Comment by pascalgrimaud** [comment]
I was trusting on @atomfrede's review :)
Let's wait @mshima

**Comment by atomfrede** [comment]
It looked fine 🥺

**Comment by mshima** [comment]
In my tests it was working, I was wrong 😕.
Testing those ci scripts is a pain.

**Comment by mshima** [comment]
At least PR list is quite empty now.

**Comment by pascalgrimaud** [comment]
no worry :-D we trusted in the CI, but we were wrong ahah

**Pull request merged**
