### PR TITLE
Fix npm install command on Windows

### LINKED ISSUE #21810: Access is denied on windows 11
Error executing './npmw install', execute it yourself. (Command failed with exit code 1: ./npmw install)

### PR DESCRIPTION
**Pull request by mraible**
Fixes #21810. 

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
@mshima Even after this fix, `npmw install` still fails on Windows when I run `jhipster jdl default`. 

I believe this is because `generator-jhipster@7.10.0` is not available in npmjs.com.

Screenshot 2023-04-20 at 9 13 23 AM

**Comment by mshima** [comment]
> @mshima Even after this fix, `npmw install` still fails on Windows when I run `jhipster jdl default`.
> 
> I believe this is because `generator-jhipster@7.10.0` is not available in npmjs.com.

Indeed, we should force --skip-jhipster-dependencies if latest version is less than package.json version.
Maybe we should force if jhipster executable has `.git` folder too.

**Comment by mraible** [comment]
If I use `jhipster jdl default --skip-jhipster-dependencies`, everything works.

Screenshot 2023-04-20 at 12 43 04 PM

I'm curious: why does the main branch use version 7.10.0? This is not released on npmjs.com and we've always used the same version as the last published version. 

Was the change necessary? It seems like it'll make it harder for folks to contribute.

**Comment by mshima** [comment]
`jhipster jdl bug-tracker.jh` was broken due to jdl changes.
Changed the version to use a new jhipster-samples branch.
See https://github.com/jhipster/generator-jhipster/pull/21792

**Review by mshima — APPROVED** [review]
I didn't test on a windows machine. But daily builds which uses bash succeed https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/4756657462.

LGMT.

**Pull request merged**
