### PR TITLE
Move tests next to the files they are testing in Angular

### PR DESCRIPTION
**Pull request by kaidohallik**
As per https://github.com/jhipster/generator-jhipster/issues/13125#issuecomment-735793814 this PR moves tests next to the files they are testing.

This PR has 2 commits:
* first moves tests next to the files they are testing
* second polishes imports in tests, using `./` for files which are next to test

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@kaidohallik Trusting you on this. Feel free to merge if you are confident
Just restarted 1 flaky test...

**Review by DanielFran — APPROVED** [review]
LGTM

**Comment by mshima** [comment]
The only problem I see it that we are removing the entire spec folder.
So if there is custom files there they will be removed.
Not sure how to proceed here, but I think it's important to keep this in mind.
- Remove file by file.
- Make `jhipster upgrade` the only supported upgrade path for this use case.

**Comment by kaidohallik** [comment]
I thought that they can revert their own files deletions. But you are right @mshima it's better to do clean up file by file. So I'm doing additional PR for cleaning test files file by file.

**Pull request merged**
