### PR TITLE
Fix microservice: auth token now passing from gateway to microservice

### PR DESCRIPTION
**Pull request by aneri90**
This PR fixes the following scenario: Microservice architecture, Oauth2 Authentication, No Service Discovery.
In this scenario the gateway fails to relay authentication token to downstream microservice, resulting in status code 401 when querying microservice's api.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
I didn't realize JHipster supported microservices without service discovery. How do the apps know how to talk to each other?

**Comment by aneri90** [comment]
In our case we are using kubernetes native service discovery

**Review by PierreBesson — APPROVED** [review]

**Comment by PierreBesson** [comment]
I totally approve of this change and yes JHipster supports microservices without service discovery although it's not a first-class citizen yet... We know that more and more people want to do this. However; a lot of our microservice templates were written with the assumption of using either eureka or consul and we lack resources to refactor all this code while not breaking anything. @aneri90 if this is something that interests you, please take a deeper look :pray:.

**Comment by pascalgrimaud** [comment]
merging this, as approved by @PierreBesson

**Pull request merged**
