### PR TITLE
[SpringBoot 2.3] Replace MongoBee with Mongock

### PR DESCRIPTION
**Pull request by murdos**
MongoBee is not maintained and doesn't support MongoDB driver v4 that comes with last Spring Data MongoDB release.

FYI #8678 was a previous feature request to switch to Mongock that was declined because the project had not enough github stars and there was a risk that the tool would be short-lived. Things have changed since, the project has 119 stars, is active.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by dieppa** [comment]
just let you know, there is a new release: 4.0.2.alpha. Basically added new feature to be able to use repositories in changeSets.

We have also added a BOM file and the spring module has been renamed to mongock-spring-v5.

So you would need to  add this in your dependencies management:

```
<dependency>
  <groupId>com.github.cloudyrock.mongock</groupId>
  <artifactId>mongock-bom</artifactId>
  <version>4.0.3.alpha-SNAPSHOT</version>
  <type>pom</type>
   <scope>import</scope>
</dependency>
```

and replace your mongock dependencies with this:

```
<dependency>
  <groupId>com.github.cloudyrock.mongock</groupId>
  <artifactId>mongock-spring-v5</artifactId>
</dependency>
<dependency>
  <groupId>com.github.cloudyrock.mongock</groupId>
  <artifactId>mongodb-springdata-v3-driver</artifactId>
</dependency>
```

Anyway, we'll be releasing a new version with some new features at the end of next week.

**Comment by DanielFran** [comment]
Thanks @dieppa for the details

**Comment by camcramz** [comment]
I've attempted to make the migration from mongobee to mongock on an existing project generated with mongobee.  I've followed the commits and have made the changes to the pom and the database configs as well as the init setup.  My application runs and seems to be working but when i run my tests i am getting an error.

Caused by: java.lang.NoClassDefFoundError: org/springframework/data/mongodb/MongoDatabaseFactory
	at com.github.cloudyrock.mongock.driver.mongodb.springdata.v3.SpringDataMongo3Driver.specificInitialization(SpringDataMongo3Driver.java:68)
	at io.changock.driver.core.driver.ConnectionDriverBase.initialize(ConnectionDriverBase.java:44)
	at io.changock.runner.core.MigrationExecutor.initializationAndValidation(MigrationExecutor.java:205)
	at io.changock.runner.spring.v5.core.SpringMigrationExecutor.initializationAndValidation(SpringMigrationExecutor.java:32)

Any idea on why i see this running mvn clean install?  

        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongock-spring-v5</artifactId>
            <version>4.1.17</version>
        </dependency>
        <dependency>
            <groupId>com.github.cloudyrock.mongock</groupId>
            <artifactId>mongodb-springdata-v3-driver</artifactId>
            <version>4.1.17</version>
        </dependency>

**Comment by SudharakaP** [comment]
@pascalgrimaud : I think this is only merged to master; probably not the v6.x.x branch right? Maybe the milestone needs to be changed? 🤔

**Comment by pascalgrimaud** [comment]
sure, I was wrong. Don't hesitate to change it :-p

**Pull request merged**
