### PR TITLE
Adding i18n Portuguese Language support

### PR DESCRIPTION
**Pull request by bfreire**

### CODE REVIEW

**Comment by andidev** [comment]
Could you also translate the entity and enum files in
https://github.com/jhipster/generator-jhipster/tree/master/entity/templates/src/main/webapp/i18n

**Comment by bfreire** [comment]
It's done!

**Comment by deepu105** [comment]
look good :+1:

**Comment by jdubois** [comment]
I just tested: looks good, excepted that the entities menu has got the labels instead of the values. I need to check why.

**Pull request merged**
