### PR TITLE
Sonar: Add a 'onKeyPress|onKeyDown|onKeyUp' attribute to this <span> tag

### LINKED ISSUE #26106: Sonar: 49 reliability issues
https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&resolved=false&id=jhipster-sample-application

image

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #26106 

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by mraible — DISMISSED** [review]

**Comment by mshima** [comment]
Won’t `(keypress)` conflict with tabs? Shouldn’t we use `(keypress.Space)`?

**Comment by qmonmert** [comment]
@mshima to try I added `tabindex="0"` on the `span` antd it works with `(keydown)` but I don't add `tabindex` because Sonar complains `"tabIndex" should only be declared on interactive elements.sonarlint(Web:S6845)
`

**Comment by mshima** [comment]
Are the remaining 7 bugs false positives?
Maybe change span to button if not false positives?

**Comment by qmonmert** [comment]
@mshima not false positives for me, I updated with `button`

**Review by Tcharl — APPROVED** [review]

**Review by mshima — APPROVED** [review]

**Comment by qmonmert** [comment]
7 issues fixed
image

**Pull request merged**
