### PR TITLE
Add tolerance for Twitter usernames with uppercase characters

### PR DESCRIPTION
**Pull request by amaillere**
... by lowercasing them
IMO it should be also implemented in UserService when creating users, as I had a similar issue with X509 certificate auto-create users on another project

### CODE REVIEW

**Comment by moifort** [comment]
In relation with #2632

**Comment by pascalgrimaud** [comment]
Travis build failed

**Comment by amaillere** [comment]
test case is assertEquals("@LOGIN"), which obviously fails
any thought about this?
1) should I change the test case to assertEqualsIgnoreCase
2) should I rework the global system to make it fully case sensitive? (and break ee2540c26d42b8ffaae0dd1cf0dcc4b09310d922 )

**Comment by deepu105** [comment]
I guess login names should not be case sensitive, that is what I have seen
everywhere else

Thanks & Regards,
Deepu

**Comment by amaillere** [comment]
I'm still not fully satisfied with this... even if the tests pass, I think the whole username/login system should be made case unsensitive on a Repository (or at least Service) level
But this is a big responsability to take  for me ;)

**Comment by deepu105** [comment]
seems ok to me. @jdubois are you ok with this??

**Comment by jdubois** [comment]
Yes LGTM
I'm merging this

**Pull request merged**
