### PR TITLE
Fix session auth with skipUserManagement

### PR DESCRIPTION
**Pull request by cbornet**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

The fix done in #9655 should also be done for skipUserManagement apps with DB.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@cbornet : do you think I should add new configs + builds at daily-builds project, to test config with skipUserManagement ?

**Comment by cbornet** [comment]
@pascalgrimaud that would be great ! At least some "no database builds"

**Comment by DanielFran** [comment]
@cbornet The "no database" changes require changes in jhipster-core?

**Comment by cbornet** [comment]
It should probably a added to the available options. Note however that it doesn't make sense for the entity generation.

**Comment by pascalgrimaud** [comment]
@cbornet : do e2e work with no database option ? I don't think so, as I can still see some account / user management items when choosing no database.
I can try to fix them if you confirm, but what is the difference between no database and skipUserManagement ?

**Comment by cbornet** [comment]
I'm working on this. We generate the front end account module for skipUserManagement although there's no account endpoint.
"No database" implies skipUserManagement but not the inverse.

**Comment by cbornet** [comment]
And yes, e2e probably don't work atm.

**Comment by pascalgrimaud** [comment]
Thanks for clarification :)
I will focus on adding the builds so

**Pull request merged**
