### PR TITLE
Travis: protractor tests retry

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix https://github.com/jhipster/generator-jhipster/issues/4884

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Perfect! The build number 3 (mysql in prod + protractor) failed 2 times:
https://travis-ci.org/jhipster/generator-jhipster/jobs/193681707

So we can see the retry.

**Comment by deepu105** [comment]
Damn is it failing even after 3 retries?

**Comment by jdubois** [comment]
There is definitely a problem on this build.....

**Comment by pascalgrimaud** [comment]
In fact, the commit message was wrong, there is only 1 retry, so 2 launchs of protractor.
We can increase the number of retries if you want

**Comment by deepu105** [comment]
but if it requires more than 2 retry then we are doing something wrong I
guess


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
At least it passes, so definitely a Travis issue...

**Pull request merged**
