### PR TITLE
adding bootswatch theme support

### LINKED ISSUE #1526: Feature Request: Bootswatch themes
Will any one be interested in having a default theme switcher on the generated app using bootswatch.

If so I can submit a PR, I have done a small directive to mimic the below function, I can integrate the same into the footer section of the generated app, so that there is a select element to choose from the list of available bootswatch themes, with the original bootstrap theme as fall back

Might not be much value once you get started fixing a theme, but will be nice to play for those who wanna try out some themes before fixing one right out of box in the generated app

http://jsbin.com/rabij/1/edit?html,js,output

### PR DESCRIPTION
**Pull request by deepu105**
Added support to switch themes using bootswatch API from the generated app
Added a service and directive to support the function

Fix #1526

### CODE REVIEW

**Comment by deepu105** [comment]
screenshots here https://github.com/jhipster/generator-jhipster/issues/1526

**Comment by jdubois** [comment]
It doesn't work with the token based authentication, I get a 
```
Request header field x-auth-token is not allowed by Access-Control-Allow-Headers
```

Otherwise this looks really cool, then I'm a bit annoyed that this adds a new menu for everyone. I guess most people will find it cool at the beginning, and then they will want to remove it.

**Comment by deepu105** [comment]
hmmm, so what do you suggest? can we have it as a dev only menu? I guess its not worth being an option all together during generation.

But most people would remove is fine rite? coz the purpose is to try out different styles during dev and once you go into prod you would fix something and just comment out the menu

For the token auth, ill take a look and update

**Comment by jdubois** [comment]
I don't suggest anything, I have no idea in fact :-(
But yes this should be mostly for dev, then maybe some applications will want this feature

For token auth (as well as OAuth2 probably) I'm not sure there is an easy solution

**Comment by deepu105** [comment]
else we can do something like this and ask users to select the theme they want during generation
https://github.com/dbtek/bootswatch-dist

**Comment by jdubois** [comment]
yes that's a completely different approach but that would solve both issues.
but maybe this should be a "tip"? Doesn't look that complicated to set up.

**Comment by deepu105** [comment]
nope not very complicated

On Thu, May 28, 2015 at 12:18 AM, Julien Dubois <notifications@github.com>
wrote:

> yes that's a completely different approach but that would solve both
> issues.
> but maybe this should be a "tip"? Doesn't look that complicated to set up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/pull/1529#issuecomment-105982870>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by jdubois** [comment]
OK, then can you just test it and add a "tip" on the website?

**Comment by deepu105** [comment]
you want tip for the bower repo one or the commit i made?

**Comment by jdubois** [comment]
the Bower repo, as it solves both issues, including the security one (and I'm not sure you can solve it otherwise)

**Comment by deepu105** [comment]
bower repo is straight forward remove bootstrap from bower config and just install the bower bootswatch theme
Ill add a tip sometime this week.

But anyway ill give a shot at security and see :smile:

**Comment by deepu105** [comment]
@jdubois  fixed the oauth and x-auth issue. also have put the theme switcher at the footer with `ng-show="{{ENV === 'dev'}}"`

image

**Comment by jdubois** [comment]
I find it even worse in the footer, I'd expect to have everything in the menu.

**Comment by deepu105** [comment]
Shall i put it back in the menu then?  With the same dev only switch?

**Comment by jdubois** [comment]
@deepu105 I'd rather have this as a "tip" on the website: otherwise it adds code in the main application, but that's only for the "dev" profile, so I don't think it's very good.
Besides, it would be good to explain how to change a theme, as this would be useful for more people: the idea is that you could bring your theme (or buy one) very easily

**Comment by deepu105** [comment]
ok

**Comment by deepu105** [comment]
will write as tip later

**Pull request closed without merging**
