### PR TITLE
Refactor hibernate id generator

### PR DESCRIPTION
**Pull request by jdubois**

### CODE REVIEW

**Comment by jdubois** [comment]
Fix #4725

**Comment by MathieuLorber** [comment]
I have a problem on current master (a409b6), on an empty project, the app stops to launch as soon as I had a (simple) entity.
It logs "Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed". Suggested solutions to the problem don't work.
When I revert this patch, it's ok again => an empty project + 1 entity launchs (I still have a ng2 state problem, I can't find the entity, but it's another problem).

**Comment by pascalgrimaud** [comment]
@MathieuLorber : can you open a new issue with the same description here + full details plz? (your .yo-rc.json, your configuration, etc.)
And if possible, the exact use case (with JDL or with sub generator entity)
So it will be easier for us to try to reproduce the issue

**Comment by jdubois** [comment]
Did you do a 'link' on generator-jhipster to use the master branch when generating your entities ?

**Comment by MathieuLorber** [comment]
=> https://github.com/jhipster/generator-jhipster/issues/4759

@jdubois yep

**Pull request merged**
