### PR TITLE
[Angular] French JHipster generation failed

### LINKED ISSUE #22989: French jHipster generation

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #22989 

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by qmonmert** [comment]
@mshima not sure that it's the best solution...

**Comment by mshima** [comment]
Does it fix the erro? Prettier will revert the change.
If the error is related to translating process, we will probably need to adjust the regular expressions and replacements.

**Comment by qmonmert** [comment]
yes with this PR it works, I added infos in ticket

**Comment by mshima** [comment]
👍
We can pass a escape function here:
https://github.com/jhipster/generator-jhipster/blob/f2856e4c5397346a8cef708f1dd45cb27903d198/generators/angular/support/translate-angular.mjs#L65

```

return replaceTranslationKeysWithText(getWebappTranslation, content, `${jsKey}\\s?:\\s?['|"]([a-zA-Z0-9.\\-_]+)['|"]`, {
  escape: (translation, target) => translation.replaceAll(target.slice(-1), `\\${target.slice(-1)}`),
});
```

**Comment by qmonmert** [comment]
@mshima ok, I tried your code but it doesn't work :/

**Comment by mshima** [comment]
Indeed we need the group 0 from the match:
```diff
diff --git a/generators/angular/support/translate-angular.mjs b/generators/angular/support/translate-angular.mjs
index 996470cb87..278e8ffe12 100644
--- a/generators/angular/support/translate-angular.mjs
+++ b/generators/angular/support/translate-angular.mjs
@@ -40,14 +40,17 @@ function getTranslationValue(getWebappTranslation, key, data) {
  * @param {number} [options.replacementIndex]
  * @returns {string}
  */
-function replaceTranslationKeysWithText(getWebappTranslation, content, regexSource, { keyIndex = 1, replacementIndex = 1 } = {}) {
+function replaceTranslationKeysWithText(getWebappTranslation, content, regexSource, { keyIndex = 1, replacementIndex = 1, escape } = {}) {
   const regex = new RegExp(regexSource, 'g');
   let match = regex.exec(content);
   while (match !== null) {
     // match is now the next match, in array form and our key is at index 1, index 1 is replace target.
     const key = match[keyIndex];
     const target = match[replacementIndex];
-    const translation = getTranslationValue(getWebappTranslation, key);
+    let translation = getTranslationValue(getWebappTranslation, key);
+    if (escape) {
+      translation = escape(translation, match);
+    }
     content = content.replace(target, translation);
     match = regex.exec(content);
   }
@@ -62,7 +65,9 @@ function replaceTranslationKeysWithText(getWebappTranslation, content, regexSour
  * @returns string with pageTitle replaced
  */
 function replaceJSTranslation(getWebappTranslation, content, jsKey) {
-  return replaceTranslationKeysWithText(getWebappTranslation, content, `${jsKey}\\s?:\\s?['|"]([a-zA-Z0-9.\\-_]+)['|"]`);
+  return replaceTranslationKeysWithText(getWebappTranslation, content, `${jsKey}\\s?:\\s?['|"]([a-zA-Z0-9.\\-_]+)['|"]`, {
+    escape: (translation, match) => translation.replaceAll(match[0].slice(-1), `\\${match[0].slice(-1)}`),
+  });
 }
 
 /**
```

**Comment by mshima** [comment]
Since the French sample is not catching the problem, can you add a test to avoid regression?

**Review by mshima — APPROVED** [review]

**Pull request merged**
