### PR TITLE
Use baseUrl in tsconfig.json for shorter imports

### PR DESCRIPTION
**Pull request by gmarziou**
Same as #4786 which was for entity-ng2 branch.

~~~ts
import {JhiHealthCheckComponent} from '../../../../../../main/webapp/app/admin/health/health.component'
import {JhiHealthService} from '../../../../../../main/webapp/app/admin/health/health.service';
~~~

can be replaced by

~~~ts
import {JhiHealthCheckComponent} from 'admin/health/health.component'
import {JhiHealthService} from 'admin/health/health.service';
~~~

### CODE REVIEW

**Comment by gmarziou** [comment]
Damn failing on a constant.

**Comment by deepu105** [comment]
May be we can do similar import in app source as well instaed of doing relative import. what do you think?

**Comment by gmarziou** [comment]
I'll try and let you know

**Comment by gmarziou** [comment]
Yes it works but it raises some questions too which in fact are very comparable to java packaging.
I'll put more comments on dev ML.

**Comment by gmarziou** [comment]
I'll submit a new PR using 'app' as import prefix.

**Pull request closed without merging**
