### PR TITLE
Update spring-boot version to 2.4.7 and other dependencies

### PR DESCRIPTION
**Pull request by DanielFran**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@atomfrede Any idea why using gradle we have error "Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/env/Environment" ?

**Comment by DanielFran** [comment]
Thanks @mshima, the fix in the script fixed the previous issues.
Nao just wondering why tests are failing...

**Comment by mshima** [comment]
The failure seems a behavior change.

**Comment by atomfrede** [comment]
> @atomfrede Any idea why using gradle we have error "Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/env/Environment" ?

Need to check. I have other non jhipster projects working without any issues.

**Comment by DanielFran** [comment]
@atomfrede Sorry this was due to a bug in ci script fixed in the branch by mshima

**Pull request merged**
