### PR TITLE
expose dropwizard metrics via prometheus

### LINKED ISSUE #8423: Enable Prometheus & add documentation for Prometheus
~~It seems like we have no documentation for Prometheus & Grafana, or at least I couldn't find them~~

~~Also it seems like there is no prometheus profile for Gradle and the maven profile isn't  documented as well~~

Enable prometheus back since its still ofeered during docker/kubernets config generation

### PR DESCRIPTION
**Pull request by atomfrede**
* Needs to merge https://github.com/jhipster/jhipster/pull/101 before to have the needed properties
* Currently the endpoint is not enabled
* I would like to add basic auth to the prometheus endpoint via an additional configuration which is only enabled when prometheus is enabled (I reused the config from @cbornet basic auth module)
* Should we add prometheus/grafana docker compose configs? (we had them before)

```java
@Configuration
@Order(1)
@ConditionalOnProperty(prefix = "jhipster", name = "metrics.prometheus.enabled")
public class BasicAuthConfiguration extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .antMatcher("/prometheusMetrics/**")
            .authorizeRequests()
            .anyRequest().hasAuthority(AuthoritiesConstants.ADMIN)
            .and()
            .httpBasic().realmName("jhipster") // <-- will be the appname
            .and()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
            .and().csrf().disable();
    }
}
```
closes #8423 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
As we will be migrating to Micormeter.io soon, is that useful to do this now? cc @PierreBesson

**Comment by atomfrede** [comment]
Depends how long it takes. We could add the export easily with this mr and it is disabled by default. We can document how to enable it and how to protect it. Furthermore I would provide prom and grafana compose files which we can also use when we made the switch to micrometer.

**Comment by jdubois** [comment]
Let's wait until next week, we'll do a session with @PierreBesson on this - but micrometer.io migration is going faster than I had expected

**Comment by atomfrede** [comment]
Ok let's put this on hold.

**Comment by anthonydahanne** [comment]
as a FYI, @henri-tremblay  and I are currently upgrading our sample ehcache application (https://github.com/ehcache/ehcache3-samples/pull/42) to the latest Jhipster (5.4.2), and prometheus metrics servlet disappeared.
Following the commits in this PR, I could successfully get them back.
In my opinion, if you drop Dropwizard Metrics for good, please make sure to replace it with micrometer + the previously existing integrations (prometheus for example)

**Comment by atomfrede** [comment]
@jdubois @PierreBesson Any news on micrometer and how to proceed with this MR here?

**Comment by jdubois** [comment]
Micrometer support is being done by a new trainee at Ippon but he's just working here 2-4 days per month, so it will take some time but I'm very confident here.

**Comment by PierreBesson** [comment]
As @atomfrede already did the work. I think we can merge in order to have this temporarily working.

**Comment by atomfrede** [comment]
@PierreBesson I will add prometheus and grafana docker compose files and put the part about basic auth in the documentation.

**Comment by atomfrede** [comment]
Updated the documentation and updated the grafana/prometheus container to the latest version. So can be merged from my point of view.

**Comment by jdubois** [comment]
Ok let's merge it!

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/5326

**Pull request merged**
