### PR TITLE
Update to webpack 3

### LINKED ISSUE #5955: Upgrade to Webpack 3
Webpack 3 was just released:
https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

This is only for Angular 4, not AngularJS 1.

### PR DESCRIPTION
**Pull request by deepu105**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

fix #5955

Please note that I didnt update to Typescript 2.4.1 as it has stricter type checks and is breaking some libs like RxJS https://github.com/ReactiveX/rxjs/issues/2539

### CODE REVIEW

**Comment by deepu105** [comment]
@jhipster/developers I had some weird port conflicts while testing `yarn start`, I have lots of docker containers running for my other projects so can't shut them down so can anyone test `yarn start` with this branch, please?

**Comment by jdubois** [comment]
Yes I'm currently testing it (upcoming tweet!!)

**Comment by deepu105** [comment]
great :smile:

**Comment by jdubois** [comment]
Sorry @deepu105 when doing `yarn start` I still get:

```
node_modules/webpack/lib/optimize/CommonsChunkPlugin.js:289
			for(const module of chunk.modulesIterable) {
                            ^
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

**Comment by deepu105** [comment]
Ah damn I thought it was fixed with the latest webpack-dev-server version. cc @TheLarkInn

**Comment by deepu105** [comment]
@jdubois for me yarn start doesnt throw any error. Are you sure you deleted your node_modules before regenerating? or did you try in a fresh project?

**Comment by jdubois** [comment]
Yes.... I'll try again this afternoon

**Comment by deepu105** [comment]
@jdubois So I killed all my docker stuff and tried to do yarn start on a fresh project and it works. Please try gain and let me know

**Comment by jdubois** [comment]
Sorry - no problem at all in fact! And performance is much better!!!!!!

**Pull request merged**
