### PR TITLE
Upgrade Couchbase support for Spring Boot 2.4

### LINKED ISSUE #13544: Couchbase tests are failing
##### **Overview of the issue**

Failure seems to be caused by [EJS issues](https://github.com/hipster-labs/jhipster-daily-builds/runs/1706508705?check_suite_focus=true).

```
WARNING! Copying template /home/runner/generator-jhipster/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs failed. [TypeError: /home/runner/generator-jhipster/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs:680
    678|         this.set<%= relationshipNameCapitalized %>(<%= otherEntityName %>);
    679| <%_ if ((databaseType === 'couchbase' && !otherEntityIsEmbedded) || reactiveRelationshipWithId) { _%>
 >> 680|         this.<%= relationshipFieldName %>Id = <%= otherEntityName %> != null ? <%= otherEntityName %>.get<%= primaryKey.nameCapitalized %>() : null;
    681| <%_ } _%>
    682|         return this;
    683|     }

Cannot read property 'nameCapitalized' of undefined]
ERROR! /home/runner/generator-jhipster/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs:680
    678|         this.set<%= relationshipNameCapitalized %>(<%= otherEntityName %>);
    679| <%_ if ((databaseType === 'couchbase' && !otherEntityIsEmbedded) || reactiveRelationshipWithId) { _%>
 >> 680|         this.<%= relationshipFieldName %>Id = <%= otherEntityName %> != null ? <%= otherEntityName %>.get<%= primaryKey.nameCapitalized %>() : null;
    681| <%_ } _%>
    682|         return this;
    683|     }

Cannot read property 'nameCapitalized' of undefined
TypeError: /home/runner/generator-jhipster/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs:680
    678|         this.set<%= relationshipNameCapitalized %>(<%= otherEntityName %>);
    679| <%_ if ((databaseType === 'couchbase' && !otherEntityIsEmbedded) || reactiveRelationshipWithId) { _%>
 >> 680|         this.<%= relationshipFieldName %>Id = <%= otherEntityName %> != null ? <%= otherEntityName %>.get<%= primaryKey.nameCapitalized %>() : null;
    681| <%_ } _%>
    682|         return this;
    683|     }

Cannot read property 'nameCapitalized' of undefined
    at module.exports.eval (/home/runner/generator-jhipster/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs:1460:37)
    at Entity.java (/home/runner/generator-jhipster/node_modules/ejs/lib/ejs.js:691:17)
    at tryHandleCache (/home/runner/generator-jhipster/node_modules/ejs/lib/ejs.js:272:36)
    at Object.exports.renderFile (/home/runner/generator-jhipster/node_modules/ejs/lib/ejs.js:489:10)
    at Object.renderContent (/home/runner/generator-jhipster/generators/utils.js:250:9)
    at module.exports.template (/home/runner/generator-jhipster/generators/generator-base-private.js:755:23)
    at /home/runner/generator-jhipster/generators/generator-base.js:2233:42
    at Array.forEach (<anonymous>)
    at /home/runner/generator-jhipster/generators/generator-base.js:2149:45
    at Array.forEach (<anonymous>) {
  path: '/home/runner/generator-jhipster/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs'
}
Error: Process completed with exit code 1.
```

##### **Motivation for or Use Case**

All our nightly builds on https://github.com/hipster-labs/jhipster-daily-builds should pass.

### PR DESCRIPTION
**Pull request by mraible**
Fixes #13544.

Replaces https://github.com/jhipster/generator-jhipster/pull/13770.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
I tested this PR in [JHipster Daily Builds](https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/625499517) and it fails to compile.

```
Error:  /home/runner/app/src/main/java/io/github/jhipster/app/config/couchbase/CustomCouchbaseRepositoryQuery.java:[16,9] constructor CouchbaseRepositoryQuery in class org.springframework.data.couchbase.repository.query.CouchbaseRepositoryQuery cannot be applied to given types;
  required: org.springframework.data.couchbase.core.CouchbaseOperations,org.springframework.data.couchbase.repository.query.CouchbaseQueryMethod,org.springframework.data.repository.core.NamedQueries,org.springframework.data.repository.query.QueryMethodEvaluationContextProvider
  found: org.springframework.data.couchbase.core.CouchbaseOperations,org.springframework.data.couchbase.repository.query.CouchbaseQueryMethod,org.springframework.data.repository.core.NamedQueries
  reason: actual and formal argument lists differ in length
Error:  /home/runner/app/src/main/java/io/github/jhipster/app/config/couchbase/CustomN1qlRepositoryQueryExecutor.java:[48,17] constructor StringN1qlQueryCreator in class org.springframework.data.couchbase.repository.query.StringN1qlQueryCreator cannot be applied to given types;
  required: org.springframework.data.repository.query.ParameterAccessor,org.springframework.data.couchbase.repository.query.CouchbaseQueryMethod,org.springframework.data.couchbase.core.convert.CouchbaseConverter,java.lang.String,org.springframework.expression.spel.standard.SpelExpressionParser,org.springframework.data.repository.query.QueryMethodEvaluationContextProvider,org.springframework.data.repository.core.NamedQueries
  found: org.springframework.data.repository.query.ParameterAccessor,org.springframework.data.couchbase.repository.query.CouchbaseQueryMethod,org.springframework.data.couchbase.core.convert.CouchbaseConverter,java.lang.String,org.springframework.data.repository.query.QueryMethodEvaluationContextProvider,org.springframework.data.repository.core.NamedQueries
```

I'm able to reproduce it locally. It seems that `CouchbaseRepositoryQuery` is deprecated, but I'm not sure what replaces it.

Any ideas @mmonti?

**Comment by mraible** [comment]
It looks like [Spring Data 2020.0.5](https://github.com/spring-projects/spring-boot/issues/25002) has [breaking changes in Couchbase](https://github.com/spring-projects/spring-data-couchbase/commit/883c931cf419f91f12ba93786e1f293f77bc7467) that might be causing this.

**Comment by pascalgrimaud** [comment]
Cc @tchlyah who is the one who proposed Couchbase option in JHipster

**Comment by mmonti** [comment]
Ey!.. @mraible, a couple weeks ago @mikereiche merged my [PR](https://github.com/spring-projects/spring-data-couchbase/issues/1072) right before the spring-data release so the changes I added to jhipster to make it work are no longer needed. 
I can work on JHipster this weekend and try to fix it to make it work with Spring Data 2020.0.5
I also took a look at the reactive implementation, and I don't think that will work for now (It was unstable when I tried to work on it a couple weeks ago), not sure how it is in the latest release.

**Comment by mikereiche** [comment]
I'm looking into this.

**Comment by mikereiche** [comment]
@mmonti @mraible - I've opened this issue. I will roll-back the changes to  CouchbaseRepositoryQuery and ReactiveCouchbaseRepositoryQuery for that issue.

**Comment by mikereiche** [comment]
@mmonti @mraible I've merged the fix. https://github.com/spring-projects/spring-data-couchbase/pull/1093
My apologies.

**Comment by mraible** [comment]
Just to keep everyone in the loop, we've removed Couchbase as an option for JHipster 7. Using it with JDL should still work. We can add it back in if/when everything is working again.

**Comment by mraible** [comment]
Added some juice to the mix. 🤑

**Comment by mraible** [comment]
Closing in favor of https://github.com/jhipster/generator-jhipster/pull/15645.

**Pull request closed without merging**
