### PR TITLE
WIP - Do not merge - Sonar: try to analyze pull request

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to discussion at https://github.com/jhipster/generator-jhipster/pull/8736

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
Does this give PR comments from Sonar ?

**Comment by pascalgrimaud** [comment]
I hope ! That's why I'm trying to do.
And we should migrate the analyze to official JHipster organization

**Comment by pascalgrimaud** [comment]
Reading Travis docs: https://docs.travis-ci.com/user/sonarcloud/#analysis-of-internal-pull-requests

> SonarCloud can inspect internal pull requests of your repository and write comments on each line where issues are found.

> For security reasons, this advanced feature works only for INTERNAL pull requests. In other words, pull requests built from forks won’t be inspected.

So now, I'm not sure if it can be achieved

**Comment by pascalgrimaud** [comment]
For security reasons, it's not doable like this.
Another solution I read:
https://stackoverflow.com/questions/45612758/how-do-i-get-sonarcloud-to-run-on-pull-requests-from-forks-with-travis-maven

We could use an external repo, using webhooks to trigger the build. But it would be more work than a simple pull request. And it could be achieved only during JHipster days, because I need Julien to config some webhooks.

So if we really want this, I can start to test things in hipster-labs or personnal repos.

For now, I'm closing this PR.

**Comment by deepu105** [comment]
@pascalgrimaud we dont want commenting and stuff, what about just running analyze?

**Comment by cbornet** [comment]
It would be nice not failing but getting notified of the bugs/vulnerabilities of all our configs.

**Comment by deepu105** [comment]
@pascalgrimaud that is exactly what I expected, a local sonar build is more than enough, the idea is to catch PRs that might break our rating

**Comment by deepu105** [comment]
@pascalgrimaud that's exactly what we need. It's sufficient to do the builds using local sonar. The aim is to catch PRs that could fail our rating. To start with let's try on one of the builds and see how it goes.

**Comment by deepu105** [comment]
@pascalgrimaud I didn't know you were a time traveller :wink: 
image

**Comment by pascalgrimaud** [comment]
Strange lol ! I commented it 1 hour ago :p

**Comment by pascalgrimaud** [comment]
@deepu105 : what it could be done:
- if master -> analyze on SonarCloud
- if branch or pull request:
    - local Sonar Analyze, using our sonar.yml docker-compose
    - display result in Travis console logs
    - can use exit 1 (failed build) if some values are under others
        - bugs = 0
        - vulnerabilities = 0
        - code smells <= TBD
        - coverage >= 80% or 81,6% (current) ?
        - duplication <= 3% or 2,1% (current) ?

It can be activated for all projects, but a lot of builds will fail (as I know we have some bugs/vulnerabilities for other configs like MongoDB, Cassandra, etc.)
What do you think?

**Comment by pascalgrimaud** [comment]
Here a sample builds: https://travis-ci.org/pascalgrimaud/generator-jhipster/jobs/450507072
And at the end of logs:

```yaml
{
  "component": {
    "id": "AWbfZ29NutLttol5XmTH"
    "key": "io.github.jhipster.sample:jhipster-sample-application"
    "name": "Jhipster Sample Application"
    "qualifier": "TRK"
    "measures": [
      {
        "metric": "coverage"
        "value": "81.6"
      }
      {
        "metric": "code_smells"
        "value": "58"
      }
      {
        "metric": "bugs"
        "value": "0"
      }
      {
        "metric": "duplicated_lines_density"
        "value": "2.2"
      }
      {
        "metric": "vulnerabilities"
        "value": "0"
      }
    ]
  }
}
```

**Comment by deepu105** [comment]
Thats great. We can set a baseline and fail based on that

**Pull request closed without merging**
