### PR TITLE
add entity update feature

### LINKED ISSUE #2668: [Enhancement Request] Add more fields to existing entity
**Overview of the issue**
I would like a way to add more fields to an entity. Currently Once have generated an entity there is no way to add additional fields (columns) unless done manually which is error prone.

**Motivation for or Use Case**
 In any ongoing project it is common in my humble opinion that fields will be missed or may need a change.  hence an option that allows us to continue adding more fields to the entity will be very beneficial to all.

An example will be lets say we have a customer entity that already has 5 fields added earlier. Invoking the generator in 'add' mode should allow continuing the add field loop by loading existing file and adjusting internal structure to next index.

```
yo jhipster:entity customer --add
```
or
```
yo jhipster:entity customer -a
```
Asks (# 6 for representation only):
```
Do you want to add more fields to this entity (# 6) (Y/n)?
```

### PR DESCRIPTION
**Pull request by deepu105**
This is somewhat inline with what @jdubois suggested in #2668 

When running `yo jhipster:entity` on an existing entity the below options are given

- If the user did a `yo jhipster:entity Foo --force` entity is regenerated directly (like we already do)
- Otherwise a new question is asked `Do you want to update the entity? This will replace the existing files for this entity, all your custom code will be overwriiten` this will have options 
    * Yes, re generate the entity
    * [BETA] Yes, add more fields and relationships
    * [BETA] Yes, remove fields and relationships
    * No, exit
- If Add is selected, use the current options for creating an attribute/relation
- If Remove is selected, give choice to select attributes/relations and remove the selected attribute/relation, this will reset the `fieldId` and `relationshipId` of existing items

Additionally have moved helper methods outside prompt methods for better readability and reuse
have also renamed the naming style for all constants used in entity and main generators

fix #2668

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
impressive @deepu105 ! :clap:

**Comment by andidev** [comment]
This is really nice!

**Comment by deepu105** [comment]
@pascalgrimaud Travis builds are taking a lot of time lately, any idea why?

**Comment by pascalgrimaud** [comment]
@deepu105 
you guys, work so much today, there are a big queue in Travis Build ! :construction_worker:  
PR builds : https://travis-ci.org/jhipster/generator-jhipster/pull_requests

And there are some timeout => you have to manually restart it (don't know if you can)

**Comment by deepu105** [comment]
Oh ok, ya i guess all of us can restart

**Comment by jdubois** [comment]
@deepu105 I don't see where the new question is, can you check this out? Did you forget to commit it?

**Comment by deepu105** [comment]
@jdubois its here https://github.com/deepu105/generator-jhipster/blob/entity-add/entity/index.js#L947

Git doesnt show the diff as its more than 300 lines, let me do one thing ill break this into 2 PRs

**Comment by deepu105** [comment]
@pascalgrimaud seems like two builds are triggered for a PR sometimes
image

**Comment by pascalgrimaud** [comment]
I ll have a look

**Comment by pascalgrimaud** [comment]
@deepu105 did you make a PR, then commit/push to the same PR before the 1st build finished?
In this case, maybe it would explain the 2 builds

**Comment by deepu105** [comment]
no even when i start a new PR i can see two builds

Thanks & Regards,
Deepu

**Pull request closed without merging**
