### PR TITLE
Fix #6386: Build with production profile on Jenkins always hang at 92%

### LINKED ISSUE #6386: Build with production profile on Jenkins always hang at 92%
##### **Overview of the issue**

After upgrade to JHipster 4.7.0, webpack production build on jenkins always hang at 92%: 

*****************************************************************************************************
modules 1144/1146 modules 2 active ...\main\webapp\content\scss\vendor.scss 69% building modules 1145/1146 modules 1 active ...\main\webapp\content\scss\vendor.scss                                          70% building modules 1146/1146 modules 0 active                         9657ms building modules
[ERROR]  79% module and chunk tree optimization 0ms module and chunk tree optimization
[ERROR]  80% chunk modules optimization 0ms chunk modules optimization
[ERROR]  81% advanced chunk modules optimization 0ms advanced chunk modules optimization
[ERROR]  82% module reviving32ms module reviving
[ERROR]  83% module order optimization31ms module order optimization
[ERROR]  84% module id optimization47ms module id optimization
[ERROR]  85% chunk reviving 0ms chunk reviving
[ERROR]  86% chunk order optimization 0ms chunk order optimization
[ERROR]  87% chunk id optimization187ms chunk id optimization
[ERROR]  88% hashing234ms hashing
[ERROR]  89% module assets processing15ms module assets processing
[ERROR]  90% chunk assets processing578ms chunk assets processing
[ERROR]  91% additional chunk assets processing795ms additional chunk assets processing
[ERROR]  92% recording 0ms recording
*****************************************************************************************************
##### **Motivation for or Use Case**
Can not complete production build on Jenkins

##### **Reproduce the error**

1. Generate project use JHipster 4.7.0
2. Configure Jenkins to execute maven target 'mvn -Pprod package'

##### **Suggest a Fix**
Set "parallel" to "false" in webpack.prod.js 

        new UglifyJSPlugin({ 
            ....... 
            parallel: false 
            } 
        }), 

##### **JHipster Version(s)**
4.7.0

##### **JHipster configuration**
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.monolith.generated",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "IconnectSampleAppMonolith",
    "packageName": "com.mycompany.monolith.generated",
    "packageFolder": "com/mycompany/monolith/generated",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "131b7d0a45cc951ad28e9f8293f65f433f575185",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "ic",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "iconnectShowCase": true,
    "languages": [
      "en",
      "zh-cn"
    ]
  }
}

##### **Browsers and Operating System**

- Jenkins 2.5 running as service on Windows Server 2012

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by liaoyunhe**
- Please make sure the below checklist is followed for Pull Requests.
Fix #6386
- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
@deepu105 are you OK to merge this? You know this better than I do,

**Comment by deepu105** [comment]
This speeded up the prod webpack build significantly but if it causes issues in Jenkins the i'm ok to change it. But I still dont understand how this is causing issues, probabaly its specific to the environment. I have this running in Jenkins(linux) without any issues

**Comment by jdubois** [comment]
Indeed, I've never seen anyone else having this issue, and I personally don't have it - so I'm now reluctant to merge this, as this is going to slow down builds for everyone, and I have no idea if this is an environment issue or not :-(

**Comment by jdubois** [comment]
Oh, and I see the issue is on `Windows Server 2012` - and using Jenkins on Windows is a really weird idea. So I'm now even more reluctant to change this.

**Comment by liaoyunhe** [comment]
Thanks for confirming this is os issue, as only me face the problem I will close this pull request

**Comment by jdubois** [comment]
OK, I think this is the best choice for the moment, but thanks a lot @liaoyunhe because this could be a big issue, and at least we know some people face it, and how to solve it.

**Comment by kaidohallik** [comment]
There is open ticket in uglifyjs-webpack-plugin about Windows `parallel=true` problem: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/118

FYI below is described my experience after switching to uglifyjs-webpack-plugin (https://github.com/jhipster/generator-jhipster/commit/0a5d09fbab6a2fb1484c7740cb81bd4b2c18d03d).

I am facing unstable behaviour in **Jenkins** in **Centos**. It started after using uglifyjs-webpack-plugin in `webpack.prod.js`. I tried to set `parallel=false`, but that didn't help, same unstability in Jenkins.

Sometimes build runs normally, sometimes takes very long time (hours and even days), sometimes crashes. If I look at logs then all this time is waited at this 92% webpack build step.

If I reverted webpack.prod.js part from https://github.com/jhipster/generator-jhipster/commit/0a5d09fbab6a2fb1484c7740cb81bd4b2c18d03d then builds are with predictable duration in Jenkins again and no big delay at 92% of the webpack build.

If I am building with my local Windows machine with prod profile, then I have never encounetered this problem with uglifyjs-webpack-plugin, all is done very quickly.

I used Jenkins version 2.66. Now I installed latest 2.81 and tried this version with uglifyjs-webpack-plugin and still hanging at 92% of webpack build.

I made some tests in my local Windows machine and results of `gradlew -Pprod bootRepackage` are (average of 2 runs):
* 1m 13s - uglifyjs-webpack-plugin, parallel = true
* 1m 40s - uglifyjs-webpack-plugin, parallel = false
* 1m 33s - webpack.optimize.UglifyJsPlugin
So uglifyjs-webpack-plugin, parallel = true is fastest in my Windows machine, but in my Centos Jenkins doesn't work well.

**Pull request closed without merging**
