### PR TITLE
Invalidate user session if token expired.

### PR DESCRIPTION
**Pull request by vkoop**
#1662

### CODE REVIEW

**Comment by jdubois** [comment]
Is it only with token authentication? Did you try with session or OAuth2?

BTW, you can write "fix" before the ticket id to close it automatically, it's better :-)

**Comment by vkoop** [comment]
I only tried it with token authentication. But all 3 AuthServerProviders provide a method called "hasValidToken" that isn't called afterwards. Will give Session and OAuth2 a try.

**Comment by vkoop** [comment]
OAuth2 doesn't seem to have the bug.

**Comment by jdubois** [comment]
As @gzsombor mentioned it caused an issue for him, I am going to revert this commit

**Comment by vkoop** [comment]
What was the issue? Couldn't find an other ticket concerning this commit.

**Comment by jdubois** [comment]
@vkoop sorry, it's in the code comments here: https://github.com/jhipster/generator-jhipster/commit/f9bcfd1f753f5dafe0300e70f271f6dd58bdafe5#commitcomment-11985467

**Comment by gzsombor** [comment]
Yes, I've just generated a simple http session based app, but every time, after I entered the username /password the system redirected to the main screen, and offered to log me in. I had to comment out that code, than I could log in.

**Pull request merged**
