### PR TITLE
Migrate RandomUtil to JHipster Framework

### LINKED ISSUE #10966: Migrate "RandomUtil" to the JHipster framework
"RandomUtil" shouldn't be generated:

- it doesn't provide any specific value to modify it
- last time we had a security issue on it, it would have been better for everyone if it had been in the framework (it would have been just a version update)

So I want to migrate it to the JHipster Framework.

### PR DESCRIPTION
**Pull request by SudharakaP**
Fixes #10966

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks @SudharakaP you are faster than me!

**Comment by SudharakaP** [comment]
@jdubois : Ha ha. Thanks. :smile: I've removed the file in `cleanup.js` as well.

**Comment by SudharakaP** [comment]
@DanielFran : Conflicts resolved. 😄

**Comment by SudharakaP** [comment]
@pascalgrimaud : Sorry about that. I might have missed something. 😢 Will check and correct it in the evening.

**Comment by pascalgrimaud** [comment]
No worry, the CI is here for this kind of thing :)

**Comment by SudharakaP** [comment]
In our original `RandomUtil.java` class in the `generator-jhipster` side we had; 

```
<%_ if (authenticationType === 'session' && !reactive) { _%>

    /**
     * Generate a unique series to validate a persistent token, used in the
     * authentication remember-me mechanism.
     *
     * @return the generated series data.
     */
    public static String generateSeriesData() {
        return generateRandomAlphanumericString();
    }

    /**
     * Generate a persistent token, used in the authentication remember-me mechanism.
     *
     * @return the generated token data.
     */
    public static String generateTokenData() {
        return generateRandomAlphanumericString();
    }
    <%_ } _%>
```
which was removed during the migration to the jhipster framework side. These methods are redundant anyways since they just return the value of  [`generateRandomAlphanumericString` method](https://github.com/jhipster/jhipster/blob/b22186e2bc6554be11181c714fa411acf3689634/jhipster-framework/src/main/java/io/github/jhipster/security/RandomUtil.java#L43).

**Comment by SudharakaP** [comment]
@jdubois @pascalgrimaud : I've made the `generateRandomAlphanumericString` method public at https://github.com/jhipster/jhipster/pull/510 in order to simplify things. Or we could define some methods such as `generateTokenData` etc to refer at different places. I don't see a value in this other than the method name more closely representing what the random value is being used for. Let me know if you guys have any other ideas. 😄 

After merging https://github.com/jhipster/jhipster/pull/510 the CI here should pass. 😄

**Comment by SudharakaP** [comment]
Close/Open for tests, now that https://github.com/jhipster/jhipster/pull/510 is merged.

**Comment by pascalgrimaud** [comment]
I don't understand why the CI still cloned an old version of JHipster...

**Comment by SudharakaP** [comment]
@pascalgrimaud : What do you mean? The CI is all successful now. The two failed ones is from the previous run. Apparently GitHub CI doesn't remove the failed builds when we close and reopen. :smile:

**Comment by pascalgrimaud** [comment]
oh you're right ! the old builds shouldn't appear here lol
Then, thanks @SudharakaP, let's merge it :)

**Comment by SudharakaP** [comment]
@pascalgrimaud : Yes, unfortunately they do. :cry: I wonder if there's a way to remove them; let me see.... :thinking:

**Pull request merged**
