### PR TITLE
Make gulp production-ready

### PR DESCRIPTION
**Pull request by ngasull**
The goal of this PR is to make gulp build system working as well as Grunt is currently. What should have been achieved here is:
* Fixed `gulp build` in order that production builds with gulp succeed
* Fixed links to `url()` resources in CSS files in prod builds
* Add a test to check that yo generates the `gulpfile.js` when asked
* Refactor test's expected file names to variables so that they're reusable and that the actual tests are easier to read

### CODE REVIEW

**Comment by deepu105** [comment]
Awesome man. Hey since you are on this can you enable source maps for js, css and sass so that we can debug things properly in prod. Ill add it for grunt later, there is an issue #2282 pending on that

**Comment by ngasull** [comment]
Hey, I'll sure have a look on how to integrate source maps nicely with usemin. However we need a way to secure the sources from being publicly explorable (`.map`s should not be downloadable in prod!) don't you think? Would be good to have a non-public target folder to store the maps.

**Comment by deepu105** [comment]
Without public maps it cannot be used for debugging so thats against the
purpose, and anyways i dont see an issue with having public maps as you can
beautify the uglified script easily if you want to read code its javascript
anyways.
In gulp enabling sourceMaps : true does this , need to check grunt

**Comment by ngasull** [comment]
Well beautifying uglyfied code is way less understandable than original source notably because of variable names, separate file names and comments. I think most businesses (including my company) don't want to share their full original source to the public. Doing so (by default at least) could create a very bad reputation to jhipster, don't you think?

I think leaving this configurable but disabled by default would be the best move!

**Comment by gmarziou** [comment]
I don't think a source map without the original source file would be helpful to malicious user.

**Comment by jdubois** [comment]
Can we move the sourcemaps subject to #2282 which is the related issue? And yes that would be great to have, several people have already asked me about it.

**Pull request merged**
