### PR TITLE
Fix tests for Clustered HTTP Session with Hazelcast

### PR DESCRIPTION
**Pull request by pascalgrimaud**
On Master, the tests failed when choosing Clustered HTTP Session with Hazelcast:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.0",
    "baseName": "jhipster",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "clusteredHttpSession": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "b8f09707d3a857f364927a4fa87aeb3f3ff66726",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

There is a missing tests in our Travis build.
I added it back in this commit: https://github.com/jhipster/generator-jhipster/pull/6878#discussion_r158390560

_____

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Doing a `MockHazelcastInstance` should not be needed, let me have a look

**Comment by jdubois** [comment]
Oh, this is stupid.... The test checks that the Hazelcast instance is here, so it is correctly configured, but in fact that's not needed at all - it is just injected here to force it to be initialized before the rest of the app, but it's not used at all...
I'm merging it because I don't really care about clustered sessions, those should be removed in our next major release.

**Comment by jdubois** [comment]
I just merged and it still fails... WTF??

**Comment by jdubois** [comment]
Sorry my fault, it's all good, thanks @pascalgrimaud !!

**Comment by pascalgrimaud** [comment]
Cool!
Do not scare me like @PierreBesson did it, this morning at work :p

**Pull request merged**
