### PR TITLE
Remove AWS Containers Subgenerator

### PR DESCRIPTION
**Pull request by SudharakaP**
This removes the aws containers subgenerator

Resolve https://github.com/jhipster/generator-jhipster/issues/14264

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by Tcharl** [comment]
Can it be extracted in a module? It may be taken by someone who want to maintain it later

**Comment by SudharakaP** [comment]
> Can it be extracted in a module? It may be taken by someone who want to maintain it later

@Tcharl : I think we can do that but the person who maintains the module will have the same problem we encountered. There's very little we can do to test the module and maintain it because it required AWS credits and I wonder if anyone will be willing to pay out of the pocket to do the maintenance. 🤔 But I am open to it for sure. 😄

**Comment by mraible** [comment]
Can't we use Open Collective funds to purchase AWS credits? As a sponsor, I think that's a reasonable use of funds.

**Comment by CGarces** [comment]
> Can't we use Open Collective funds to purchase AWS credits? As a sponsor, I think that's a reasonable use of funds.

In the past I think that someone tried to get some credits #10579

Maybe it's time to try again

https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/

**Pull request merged**
