### PR TITLE
possible fix of hanging gradlew in Windows

### PR DESCRIPTION
**Pull request by kaidohallik**
console output doesn't contain broken texts any more

fix jhipster/generator-jhipster#4675

### CODE REVIEW

**Comment by deepu105** [comment]
I dont want to merge this unless there is a clear reproduced issue which it solves. @atomfrede @jdubois what do you think?

**Comment by atomfrede** [comment]
Looks like @cbornet PR https://github.com/jhipster/generator-jhipster/pull/4677 has the same changes, so I would say lets wait for that to be merged. I still don't have a windows VM running, so I can only try to reproduce it on linux.

**Comment by atomfrede** [comment]
@kaidohallik Can you check the current master branch as we have updated the gradle node plugin there?

**Comment by kaidohallik** [comment]
I still can't reproduce this error. Console output with current master is:
```
:gulpConstantDev
[09:11:16] Using gulpfile C:\projects\jhipster-test\gulpfile.js
[09:11:16] Starting 'ngconstant:dev'...
[09:11:16] Finished 'ngconstant:dev' after 18 ms

urceslding 50% > :processResources
```
I synced my PR with current master, with these changes console output is:
```
:gulpConstantDev
Output from C:\projects\jhipster-test/gulpfile.js
[09:04:23] Using gulpfile C:\projects\jhipster-test\gulpfile.js
[09:04:23] Starting 'ngconstant:dev'...
[09:04:23] Finished 'ngconstant:dev' after 18 ms

:processResources
```
If someone can reproduce this error (maybe with renewed gradle gulp plugin in current master this error is gone forever) and test whether this change in build.gradle solves the issue maybe then this can be merged.
Until then, maybe close the PR?

**Comment by jdubois** [comment]
I don't have Windows so I can't test, but from what I read this looks solved... Let's close it, and we'll reopen it later if this bug arises again

**Comment by kaidohallik** [comment]
Today I was facing similar problem. But instead of hanging I got error message on executing gulp plugin:
```
:bower
:gulpConstantDev
[18:25:36] Using gulpfile C:\projects\contro-gitlab\gulpfile.js
[18:25:36] Starting 'ngconstant:dev'...
[18:25:36] Finished 'ngconstant:dev' after 26 ms

FAILURE: Build failed with an exception.

* What went wrong:
Unable to process incoming event 'ProgressComplete ' (ProgressCompleteEvent)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
Running with --stacktrace gave identical output.
So I added change from this PR to build.gradle:
```
gulp {
    bufferOutput = true
}
```
and after that was build successful:
```
:bower
:gulpConstantDev
Output from C:\projects\contro-gitlab/gulpfile.js
[18:27:27] Using gulpfile C:\projects\contro-gitlab\gulpfile.js
[18:27:27] Starting 'ngconstant:dev'...
[18:27:27] Finished 'ngconstant:dev' after 23 ms

:processResources
:compileJava UP-TO-DATE
```
Now I had error message and I was googling and found that others have similar random issue with gradle from [this gradle forum topic](https://discuss.gradle.org/t/build-fails-with-unable-to-process-incoming-event-progresscomplete-progresscompleteevent/18434/32).
Some actions that solved problem for different users:
1. increase windows command line buffer height (for example to maximum possible value)
2. in outputing text use println instead of print
3. use --info or --debug flag then error goes away

My change in this PR sounds like solution 2., avoid outputs from print command.
Now I have one case where this PR solved problem in my machine.

**Comment by kaidohallik** [comment]
Now I faced hanging `gradlew` on executing gulp plugin:
```
:bower
:gulpConstantDev
[20:20:06] Using gulpfile C:\projects\contro-gitlab\gulpfile.js
[20:20:06] Starting 'ngconstant:dev'...
[20:20:06] Finished 'ngconstant:dev' after 19 ms
```
 and after adding
```
gulp {
    bufferOutput = true
}
```
to `build.gradle` it worked: didn't hang any more:
```
:bower
:gulpConstantDev
Output from C:\projects\contro-gitlab/gulpfile.js
[20:24:52] Using gulpfile C:\projects\contro-gitlab\gulpfile.js
[20:24:52] Starting 'ngconstant:dev'...
[20:24:52] Finished 'ngconstant:dev' after 19 ms

:processResources
:compileJava UP-TO-DATE
```

**Comment by kaidohallik** [comment]
More information from problematic windows command line window:
* `gradlew --console plain` works well
* `gradlew --console auto` and `gradlew --console rich` are hanging

**Comment by kaidohallik** [comment]
FYI there is open gradle issue about that, [link to issue](https://github.com/gradle/gradle/issues/882)

**Comment by svict4** [comment]
I was having this issue on a newly generated project on Windows 10. It appears to have been [fixed recently](https://github.com/gradle/gradle/pull/1155). I was able to run `gradlew` without a `ProgressComplete` error :smile: 

[`gradle wrapper --gradle-version 3.4-20170166000026+0000`](https://github.com/gradle/gradle/pull/1155#issuecomment-272836950)

**Pull request closed without merging**
