### PR TITLE
Use cy.session to avoid login/logout for each test

### LINKED ISSUE #16545: Oauth2 cypress tests too slow because of login logout
##### **Overview of the feature request**

Cypress are tests too slow because of login logout specially when using OAuth2 because of all the redirects...
Cypress introduced a feature callled Cypress.session https://www.cypress.io/blog/2021/08/04/authenticate-faster-in-tests-cy-session-command/

##### **Motivation for or Use Case**

Faster tests

- [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by yelhouti**
use cy.session to avoid login/logout for each test. fixes #16545

---

Please make sure the below checklist is followed for Pull Requests.

- [X] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [X] Tests are added where necessary
- [X] The JDL part is updated if necessary
- [X] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [X] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Wait for https://github.com/jhipster/generator-jhipster/pull/16504 to be merged at start of 7.4.0 cycle.

**Comment by yelhouti** [comment]
sure no worries, please le me know when I can rebase (there are clearly conflicts)

**Comment by DanielFran** [comment]
@yelhouti I think you can rebase now that #16504 has been merged

**Comment by yelhouti** [comment]
@DanielFran here you go, sorry for the delay. Thanks for the review

**Comment by yelhouti** [comment]
@mshima for the tests that used `before` instead of `beforeEach` this can be expected but is very bad practice, for entity tests, specially when using OIdC when direct grant is disabled and we need to redirect to the form enter credentials... the gain in time is much bigger.
I will also gladly remove the cy.clearCookies ... if we decide to go forward with the changes

**Comment by yelhouti** [comment]
@mshima thank for fixing the issue, I see that when you rewrote the code you could see the speed improvements, any idea why you couldn't see them in mine ?

**Comment by mshima** [comment]
@yelhouti it's in the review:

> The increased time looks related to not required page visits. Eg:

The cypress session cleanups the browser state and set cookies/storage to the session snapshot and redirects to a blank page.
Every cleanup can be removed and is not recommended to visit a page at login (https://docs.cypress.io/api/commands/session#Where-to-call-cy-visit)

Your PR needed more work cleaning up non required commands.

**Comment by yelhouti** [comment]
@mshima I fixed all the changes as you suggested and as i have explained the visit was necessary because the feature was experimental.
Anyway thanks

**Pull request closed without merging**
