### PR TITLE
Added croatian language

### PR DESCRIPTION
**Pull request by SpiralUp**
Added Croatian language.

### CODE REVIEW

**Comment by DanielFran** [comment]
@SpiralUp you need to sign the cla.

**Comment by SpiralUp** [comment]
Hi Pascal,
I have added hr language to several .yo-rc.json files, so I hope that now
is ok ... :)

Best regards
Ivan



sub, 22. kol 2020. u 11:26 Pascal Grimaud <notifications@github.com>
napisao je:

**Comment by pascalgrimaud** [comment]
congrats for your 1st contribution @SpiralUp

**Comment by SpiralUp** [comment]
Jeee :D

pet, 28. kol 2020. u 00:30 Pascal Grimaud <notifications@github.com>
napisao je:

**Pull request merged**
