### PR TITLE
upgrading consul to 1.0.2

### PR DESCRIPTION
**Pull request by sendilkumarn**
- Please make sure the below checklist is followed for Pull Requests.

Part of #6755

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
I think you need to migrate to Edgware for services to work with consul v1.

**Comment by sendilkumarn** [comment]
@PierreBesson  Ofcourse it needs edgware to be there. This is part of #6755 and we have to merge jhipster-dependencies PR-26 first to make this works here.

**Comment by jdubois** [comment]
Not sure if/when we should merge that for JHipster 4 -> I'm testing the new Spring Cloud release for JHipster 5, and that should be out in about 1 month

**Comment by PierreBesson** [comment]
@jdubois OK for migrating to the new spring cloud with JHipster 5.

**Comment by sendilkumarn** [comment]
can be merged with spring boot 2 branch I guess. Since everything is updated there. I will check this over there

**Comment by jdubois** [comment]
Yes I agree @sendilkumarn

**Comment by sendilkumarn** [comment]
Why is this thing getting failed ?

**Comment by jdubois** [comment]
Now #7089 is closed, could you test again? I'm pretty sure this should work

**Comment by pascalgrimaud** [comment]
@sendilkumarn : do you think we can upgrade to 1.0.6 ? https://hub.docker.com/r/library/consul/tags/

**Comment by sendilkumarn** [comment]
I havent tested that yet. But yeah I will check this thing.

Cheers

On 13 Feb 2018 08:06, "Pascal Grimaud" <notifications@github.com> wrote:

@sendilkumarn <https://github.com/sendilkumarn> : do you think we can
upgrade to 1.0.6 ? https://hub.docker.com/r/library/consul/tags/

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/pull/6970#issuecomment-365170289>,
or mute the thread

**Pull request merged**
