### PR TITLE
Fix getEntityJson in generator-base to read entity json files in the correct directory when using microservices

### LINKED ISSUE #7216: Cannot read property 'clientRootFolder' of undefined
##### **Overview of the issue**

I tried to create my [latest blog post](https://developer.okta.com/blog/2018/03/01/develop-microservices-jhipster-oauth) with the code from the `master` branch today.

Unfortunately, it fails when I try to generate a UI for tags in the gateway. 

`$ jhipster entity tag`
Using JHipster version installed globally
Executing jhipster:entity tag
Options:

The entity tag is being created.

? Do you want to generate this entity from an existing microservice? `Yes`
? Enter the path to the microservice root directory: `../blog`

Found the .jhipster/Tag.json configuration file, entity can be automatically generated!

? Do you want to update the entity? This will replace the existing files for this entity, all your
 custom code will be overwritten `Yes, re-generate the entity`

events.js:137
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'clientRootFolder' of undefined
    at context.relationships.forEach (/Users/mraible/dev/generator-jhipster/generators/entity/index.js:669:131)
    at Array.forEach (<anonymous>)
    at module.exports.loadInMemoryData (/Users/mraible/dev/generator-jhipster/generators/entity/index.js:568:39)
    at Object.<anonymous> (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/lib/index.js:399:25)
    at /Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/mraible/dev/generator-jhipster/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)

##### **Reproduce the error**

Create a gateway app and a blog microservice app. Run import-jdl to import [blog.jh](https://github.com/jhipster/jdl-samples/blob/master/blog.jh) in the blog microservice app. Run `jhipster entity tag` in the gateway app.

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/mraible/apps-v5/gateway
└── generator-jhipster@4.14.0  -> /Users/mraible/dev/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.okta.developer.gateway",
      "nativeLanguage": "en",
      "microservicePath": "../blog"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "gateway",
    "packageName": "com.okta.developer.gateway",
    "packageFolder": "com/okta/developer/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-tw"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

git version 2.14.1

node: v9.5.0

npm: 5.6.0

bower: 1.8.2

yeoman: 2.0.1

yarn: 1.3.2

Docker version 17.12.0-ce, build c97c6d6

docker-compose version 1.18.0, build 8dd22a9

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by clement26695**
Fix #7216
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by ruddell** [comment]
Could you please change the title to something descriptive and link the issue you are fixing?

**Comment by clement26695** [comment]
Yes, I'm sorry. Is it better ? 

Since I'm new to the JHipster generator and the contributing community, I tried to follow the rules but please let me know if I have done something wrong, or if I have to add some tests, etc.

**Comment by gmarziou** [comment]
@clement26695 Travis builds are failing due to some style checkings (at least first one I checked).

Please run `yarn lint` in your clone to see them and fix:

```
/home/travis/build/jhipster/generator-jhipster/generators/generator-base.js
  1777:14  error  Trailing spaces not allowed  no-trailing-spaces
✖ 1 problem (1 error, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.
```

**Comment by gmarziou** [comment]
There are 2 build failures related to protractor that I don't understand  

```
$ protractor src/test/javascript/protractor.conf.js
(node:9866) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[03:11:18] I/launcher - Running 1 instances of WebDriver
[03:11:18] I/direct - Using ChromeDriver directly...
[03:11:18] E/direct - Error code: 135
[03:11:18] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[03:11:18] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
```

**Comment by clement26695** [comment]
Indeed, I forgot to run yarn lint... It seems that it was the reason why all the three test failed.

**Comment by ruddell** [comment]
Congrats on your first contribution!  Thanks!

**Pull request merged**
