### PR TITLE
Fix a typo in gradle spring cloud dependency name

### PR DESCRIPTION
**Pull request by PierreBesson**
The gradle build is broken for microservices. I think we should add a Travis build for a microservice app and microservice gateway with gradle and maven. @jdubois Can I can do it by myself ?

### CODE REVIEW

**Comment by jdubois** [comment]
Oh yes, I suck at Gradle! Have a talk also with @atomfrede he's our Gradle expert

**Comment by atomfrede** [comment]
@PierreBesson Zour change looks good. I must admit a didn"t had time to test the new microservice architecture (will try do it next week).

**Comment by pascalgrimaud** [comment]
@PierreBesson : yes we should add travis build for microservice app and gateway => it is on my todo list but you have more time than me to do this ! :-)

app-gulp => you can replace this because we already test this configuration in app-default

**Comment by PierreBesson** [comment]
@pascalgrimaud OK, I will do it.

**Pull request merged**
