### PR TITLE
Blueprint base api : parent class for generator extendable through a blueprint

### PR DESCRIPTION
**Pull request by murdos**
This parent class holds the public API that can be used for developers of blueprint.
See [this discussion](https://github.com/jhipster/generator-jhipster/pull/8623#discussion_r226876596) for the rationale.

This PR replaces #8677 : I've given up the factorization for now since it introduced regressions, but I've added more unit tests and fixed entity-i18n subgenerator and related entity-blueprint test.

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by murdos** [comment]
> 
> 
> @murdos awesome. I'll review and merge as soon as I find the time. What was the issue with entity sub gen btw?

Yeah, I spent a lot of time one this one, with my ups and down since 2 days :-) 

The entity subgen is quite complex, since it's compose itself with other subgen, that can be extended/overridden themselves by blueprints. 
BTW I wonder how the related test was passing previously. It also had side effects: the test was passing, but was making following tests break, I guess because of the [async call in checkBlueprint()](https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base-private.js#L770).

So I had to mock all subgen, and then had to debug things (because log is mocked in yeoman-test 👎) until I found that entity-i18n was silently failing because it was not fetching templates from installed JHipster, which generates issue when working with blueprint.

**Comment by murdos** [comment]
@deepu105 do you think that you'll be able to look at this soon? I've another valuable PR ready that depends on this one.
FYI I don't think there's any risk with the current PR:
- it just introduces a base class with all _ methods
- common subgen has been cleaned up since base API has been moved to parent class
- the fix of the entity-i18n subgenerator has been confirmed by @brunnels on gitter
- unit tests have been expanded and fixed

**Comment by deepu105** [comment]
I'll merge it this weekend. The CI was failing btw

**Comment by deepu105** [comment]
@murdos can you check the failing build locally?

**Comment by murdos** [comment]
@deepu105 I was not too worried since travis tests are ok.
I wanted to restart azure pipelines integration tests to be sure there's an actual issue, but without success.
@pascalgrimaud : can we do this?

**Comment by pascalgrimaud** [comment]
@murdos : just restart the build

**Comment by pascalgrimaud** [comment]
@murdos : I forgot to answer to you. For restarting, you need to be in the JHipster organization in Azure.
For now, only Julien, Deepu and me can restart the Azure builds

**Comment by murdos** [comment]
@pascalgrimaud thanks!
@deepu105 CI is ok now with the restart of azure build

**Pull request merged**
