### PR TITLE
Remove jhipster from the URL under the management part

### PR DESCRIPTION
**Pull request by gzsombor**
and fix pagination urls to correctly point back. 
This 'jhipster' separator doesn't add any functionality to the application, just confuses the thing.

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois added the seperator I guess. Not sure what was the reason so lets wait for his review.

**Comment by pascalgrimaud** [comment]
It was done for security -> I find the ticket https://github.com/jhipster/generator-jhipster/issues/3550

**Comment by gzsombor** [comment]
The admin functionality is still under /management/ only the jhipster prefix / or suffix is removed from the audit and the log listing

**Comment by jdubois** [comment]
Thanks everyone, first some background on this:

- All admin features are behind "management" for security
- Then, I used "management/jhipster" for all JHipster endpoints, so you don't fix them with the Spring Boot actuator admin endpoints

So, concerning this specific change:

- Only downside is that we mix the JHipster specific endpoints with the Spring Boot "official" endpoints. I'm not sure it can cause any issue, only risk is that Spring Boot does a new endpoint which is the same as us - this is unlikely, but possible
- And of course I agree with @gzsombor that this is less confusing, and easier.

So +1 from me

**Pull request merged**
