### PR TITLE
Add anonymousUser as an exception un User's login regexp

### PR DESCRIPTION
**Pull request by wmarques**
Related to #3338 
We will be able to view, edit or delete the anonymousUser created by default.

### CODE REVIEW

**Comment by jd-carroll** [comment]
Doesn't this change also prevent users from creating logins with `_'.-` ?  

Shouldn't the regex be: `^[_'.@a-z0-9-]*$|anonymousUser`

**Comment by notflorian** [comment]
Isn't the anonymousUser mandatory for Spring Security? Is it a good idea to allow to delete it?

**Comment by wmarques** [comment]
@jd-carroll when we try to register a user, it tells 

> Your username can only contain lower-case letters and digits.

So I changed the regex according to this

@notflorian Oh yes, maybe we shouldn't change the regex for the delete method

**Comment by deepu105** [comment]
@wmarques I thinks its better we lowercase the login and save it and also lowercase both sides in query when matching. I would prefer lowercasing when saving as thats how normally its done everywhere. Also I prefer username to contain `_` and `.` as well so it should be `^[_'.@A-Za-z0-9-]*$` so that people can create user without worrying about case. Can you check if `anonymousUser` works if its lowercased as `anonymoususer`?

**Comment by deepu105** [comment]
as @notflorian said we shouldnt let people delete the `anonymousUser` in the first place, so may be we shouldnt show it in the user listing at all, its just an internal user for spring security

**Comment by wmarques** [comment]
@deepu105 seems to work with lowercased `anonymoususer`

**Comment by wmarques** [comment]
Should work now

**Comment by wmarques** [comment]
I removed the anonymous from the result received in user management controller, it's working

**Comment by notflorian** [comment]
As anonymoususer is now fully in lowercase, do you still need to add it in the regex?

**Comment by wmarques** [comment]
I think I can remove it yes, thanks.
So I should put Locale.ENGLISH ?

**Comment by notflorian** [comment]
Yes Locale.ENGLISH should be good because thanks to the regex, the username cannot have special characters with accents.

**Comment by deepu105** [comment]
@wmarques A test for social login is still failing. Also since we use the regexp in many places in java files, shouldn't we keep it in any of the constants file and use it as static import?

**Comment by wmarques** [comment]
@deepu105 like a variable in the generator ?

**Comment by deepu105** [comment]
Nope as Java constant String

Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
Seems that Travis is failing randomly :disappointed: The test passed [here](https://travis-ci.org/wmarques/generator-jhipster/builds/124691907)

**Comment by deepu105** [comment]
@wmarques you can restart just the failed build alone within travis :) open the failed build and look for the restart icon on top right

**Comment by wmarques** [comment]
@deepu105 Yes i know but I committed right after so let's wait for this one ! :)

**Pull request merged**
