### PR TITLE
drop bucket4j dependency

### PR DESCRIPTION
**Pull request by mshima**
Seems to not be used.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by atomfrede** [comment]
It was used for rate limiting in gateways I think. Did we remove something?

**Comment by mshima** [comment]
According to https://github.com/spring-cloud/spring-cloud-gateway/issues/88, there is no auto configure bucket4j.
And it states resilience4j is a better fit:
https://github.com/jhipster/generator-jhipster/blob/0b91c057be6ac497bf778ce83170fb674462576c/generators/server/templates/pom.xml.ejs#L734

Probably it was used at old imperative implementation.

**Review by DanielFran — APPROVED** [review]

**Comment by atomfrede** [comment]
We need to update the documentation too.

**Comment by mshima** [comment]
@atomfrede can you update?

**Comment by atomfrede** [comment]
@mshima Will do. As we don't have a real replacement I guess we just need to remove it

**Pull request merged**
