### PR TITLE
[angular] Use tabWidth=2 and trailingComma and polish templates

### PR DESCRIPTION
**Pull request by kaidohallik**
Polished Angular templates under `src/main/webapp/app`:
* changed `tabWidth` from 4 to 2 because generated code uses `tabWidth=2` and if doing changes and copy-paste code then it's very annoying always to wrap from 2 to 4 and some newer templates are already using `tabWidth=2`
* added trailing commas to templates
* added missing license headers
* polished other noticed things

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@kaidohallik please don't do this now.

**Comment by mshima** [comment]
A bit too early.
There is no change on entity-client, so this should be safe.

**Comment by kaidohallik** [comment]
OK, I want to do the same also in Angular tests part (only `client` subgenerator), is this also safe?  
`entity-client` part can be done sometime later after you have finished your work.

**Comment by mshima** [comment]
> OK, I want to do the same also in Angular tests part (only `client` subgenerator), is this also safe?
> `entity-client` part can be done sometime later after you have finished your work.

Yes, thanks.

**Review by DanielFran — APPROVED** [review]

**Pull request merged**
