### PR TITLE
Enable and Fix keycloak User Registration Config along with defaulting to 'User' group for newly registered users

### PR DESCRIPTION
**Pull request by RawSanj**
Enable and Fix Keycloak User Registration Config along with defaulting to the 'User' group for newly registered users: 

1. This fixes the error in the Jhipster Realm config which throws an error when enabling the User Registration in Keycloak.
2. The User Registration is now by default enabled and newly registered accounts by default are assigned to the `User` group to get the `USER Role`.

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by RawSanj** [comment]
This PR belongs to the label `theme: keycloak`. Not sure if I can edit the labels.

**Review by atomfrede — APPROVED** [review]
LGTM. Should we document this as a breaking change, such that existing applications can disable user registration as they might rely on the old default configuration?

**Comment by RawSanj** [comment]
> LGTM. Should we document this as a breaking change, such that existing applications can disable user registration as they might rely on the old default configuration?

Would it go under - https://github.com/jhipster/jhipster.github.io/blob/main/pages/security.md#keycloak or in the release notes?

Or I can disable the user registration to false by default. But we might still require a note to inform users that User Registration is now fixed and can be enabled.

**Comment by atomfrede** [comment]
I would say lets keep it enabled as one can register without keycloak too by default.

**Comment by RawSanj** [comment]
@atomfrede Is there anything else I should work upon to get this merged?
If not, can you please merge this PR?

**Comment by idNoRD** [comment]
There are two "users" configuration keys in the json.
Can you please refactor to have only one "users" key to avoid json validation warning "Object contains duplicate keys 'users'"? Thanks

**Comment by mraible** [comment]
@idNoRD I don't see two `users` keys being added in this PR, so I believe your request is unrelated. Please open a new issue/PR for this.

**Comment by mraible** [comment]
@RawSanj I QA'd this PR today and I can confirm it enables registration by default and puts users in the proper group. 

However, if I create a brand new app with JHipster 8.3.0 (using `jhipster jdl blog-oauth2`), I can enable user registration successfully and register just fine. Because of this, it seems this PR only enables user registration. 

Can you please provide the steps needed to reproduce the issue where Keycloak throws an error when enabling user registration?

**Comment by RawSanj** [comment]
@mraible Looks like the registration issue is fixed in another [PR-25679](https://github.com/jhipster/generator-jhipster/pull/25679/files) merged (30 March) after this PR was raised (6 Jan). 

This PR now only enables the User Registrations by default and Puts newly registered users into User Group/Role. 
Let me know if we should skip this PR or sync up the changes and merge this PR?

**Comment by mraible** [comment]
@RawSanj If I create a new app with `jhipster jdl blog-oauth2` with JHipster 8.4.0, enable registration in Keycloak, and create a new user, it has access to the Entities menu. 

Screenshot 2024-04-30 at 9 43 38 AM

I thought this implies the new user is added to the correct group, but the new user has no groups. 

Screenshot 2024-04-30 at 9 45 58 AM

Please sync this PR with `main` and we'll get it merged.

**Review by mraible — APPROVED** [review]

**Pull request merged**
