### PR TITLE
Documentation typo issue 12469

### PR DESCRIPTION
**Pull request by Virginiw**
Fixed : #12469 

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks @Virginiw and congrats for your 1st contribution !

**Comment by qmonmert** [comment]
the file `jdl/bundling/dist/jdl-core.min.js ` should not be commited :)

**Comment by pascalgrimaud** [comment]
We can commit it, because the last commits in master were not included this file

**Comment by pascalgrimaud** [comment]
I convert to draft, so @Virginiw can amend the commits

**Pull request merged**
