### PR TITLE
Fix for Couchbase Testcontainers Failure

### LINKED ISSUE #10594: ngx-couchbase intermittent Test Failures
##### **Overview of the issue**

This issue was created from the discussion at https://github.com/jhipster/generator-jhipster/issues/10589. It seems that ngx-couchbase tests on our CI seems to hang and fail sometimes. Here are some examples;

https://github.com/jhipster/generator-jhipster/pull/10498/checks?check_run_id=254018117

https://dev.azure.com/jhipster/jhipster/_build/results?buildId=6316 

##### **Motivation for or Use Case**

Getting the CI tests in working condition without problems.

##### **Reproduce the error**

Submitting a PR or making a commit so that the CI is triggered might recreate the issue.

##### **Related issues**

#10589

##### **Suggest a Fix**

Currently not known.

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by SudharakaP**
This is a probable fix for #10594. Since GitHub actions doesn't seem to have a method to restart successful CI runs; I am going to close and open this PR several times to test this out.  

Fixes #10594

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
@SudharakaP, fyi, yesterday, I spent some time on the couchbase failures. I am still not sure on the root cause, and trying out few combinations. I will raise PR if able to get few consecutive successful runs.

**Comment by SudharakaP** [comment]
@vishal423 : Sure. Try it out; and let me know if you find the root cause. I initially thought I found the cause but I was wrong. The interesting thing is the same CI runs correctly [without errors on my fork](https://github.com/SudharakaP/generator-jhipster/actions) whereas it fails here. I am also trying out different things. :thinking:

**Comment by pascalgrimaud** [comment]
Here some additional info:

On GitHub Actions, we use:

```
openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)
```

With Azure Pipelines, see https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=6278&view=logs&j=1325b5b4-61f4-5784-74f4-9f398d404aa2

```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-116.04.1)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-116.04.1, mixed mode, sharing)
```

Maybe not related, but I wanted to inform you.

**Comment by pascalgrimaud** [comment]
Thanks @SudharakaP 
Does it mean the problem with Couchbase + OpenJDK8 on Daily builds is another problem ?

**Comment by SudharakaP** [comment]
@pascalgrimaud : I am not certain about that yet. I believe there's some subtlety that I am missing. I will do some more investigation on that today. :thinking:

**Pull request merged**
