### PR TITLE
Vue client - add interceptor for status >= 500

### PR DESCRIPTION
**Pull request by shershen08**
Added interceptor, that can be hooked to some UI finctionality

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

Fixes: #15722

### CODE REVIEW

**Comment by shershen08** [comment]
sample usage can be as follows:
```
// create event bus in  '@/shared/config/event-bus';
import Vue from 'vue';
const eventBus = new Vue();
export default eventBus;

//add call in config.ts
import eventBus from '@/shared/config/event-bus';

...
  setupAxiosInterceptors(
    () => console.log('Unauthorized!'),
    () => {
      eventBus.$emit('error');
    }
  );


//consume in root or any other component
import eventBus from '@/shared/config/event-bus';
...
  mounted(){
    eventBus.$on('error', () => {
      //this.onError();
      console.error('Global onError');
    })
  },
```

**Review by mshima — COMMENTED** [review]
Can you add a test case, please?

**Comment by shershen08** [comment]
All good now,

**Comment by mshima** [comment]
It looks good, but I don't know vue enough, maybe @atomfrede or @qmonmert can review this one.

**Comment by atomfrede** [comment]
Will have a look. I think I implemented something similar before.

**Comment by qmonmert** [comment]
it looks good for me :)

**Review by qmonmert — APPROVED** [review]

**Review by atomfrede — APPROVED** [review]

**Pull request merged**
