### PR TITLE
updating angular and bootstrap to the latest version

### PR DESCRIPTION
**Pull request by sendilkumarn**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by sendilkumarn** [comment]
[😏  -> check this out ](https://getbootstrap.com/docs/4.0/migration/#stable-changes)

screens look good. But I don't understand why the tests fail  😢

**Comment by deepu105** [comment]
@sendilkumarn rebase to current master, then your tests will pass I guess, might be related to the test that was breaking master

**Comment by vishal423** [comment]
I believe failures are due to [breaking changes](https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/) introduced as part of typescript v2.6 ( I noted that you have upgraded typescript version from 2.5.x to 2.6.x). These are mostly related to unused variables or imports and require code cleanup.

Do you need help to fix these? I have fix ready for 2 files that I noted in issue.

**Comment by deepu105** [comment]
thanks @vishal423
@sendilkumarn indeed I didnt see you updated TS, even TS minor versions are a pain as they often crry breaking changes

**Comment by sendilkumarn** [comment]
No they run locally for me :) There is no breaking change in 2.6 This is weird.

**Comment by sendilkumarn** [comment]
Adding on-hold here Let me verify

**Comment by deepu105** [comment]
@sendilkumarn there is a breaking change regarding unused variables and it fails as we have some which were not previously found by TS

**Comment by vishal423** [comment]
@sendilkumarn, for your reference, I noted below errors in travis build and also on local gateway app generated with your codebase. After cleaning unused variables, I was able to compile tests on local.

ERROR: /home/travis/app/src/test/javascript/spec/app/admin/audits/audits.component.spec.ts[38, 13]: 'service' is declared but its value is never read.
ERROR: /home/travis/app/src/test/javascript/spec/app/admin/user-management/user-management.component.spec.ts[16, 13]: 'mockPrincipal' is declared but its value is never read.

Since, we generate code conditionally (based on user selections), there are high chances that this issue would be reproducible with different selection option combinations (not sure if travis builds capture all possible scenario to generate code). This is good from cleanup perspective and would eventually improve code quality.

**Pull request merged**
