### PR TITLE
Upgrade keycloak and realm configurations to v9.0

### LINKED ISSUE #11245: Update jboss/keycloak version to 9.0
##### **Overview of the feature request**

See:
- https://www.keycloak.org/docs/latest/release_notes/index.html

https://www.keycloak.org/2020/02/keycloak-900-released.html

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vishal423**
Closes #11245 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
There seems to be some issue with the re-run of GitHub workflows. They seem to fail with a message like https://github.com/jhipster/generator-jhipster/runs/463106241#step:2:512

closing/re-opening to trigger build

**Comment by vishal423** [comment]
`react` e2e tests are failing intermittently between different restart attempts and there are already code issues identified in another ticket. IMO, this ticket is ready for review, test, & merge.

**Comment by pascalgrimaud** [comment]
React is too flaky these last weeks... I was thinking about removing all e2e for React in our build

**Comment by vishal423** [comment]
I think the main issue is with entity code and commenting out the e2e run will only suppress the main issues. It would be good if we can somehow accelerate the fixture of those issues, maybe with some bug bounties and/or ask for help on twitter?

**Comment by SudharakaP** [comment]
@pascalgrimaud @vishal423 : Let me see if I can find the cause of these React E2E issues. :thinking:  :thinking:

**Comment by pascalgrimaud** [comment]
if you're motivated enough... just open a new ticket so we can track it

**Comment by vishal423** [comment]
@SudharakaP, I think the current e2e test failures are due to open issues identified under #11321 If you can help closure on that ticket, it would be great.

**Comment by SudharakaP** [comment]
@vishal423 : Thanks for pointing to that ticket. Let me take a look. :smile:

**Pull request merged**
