### PR TITLE
[WIP] Use html5 input instead of NgbDatePicker

### LINKED ISSUE #5006: LocalDate and ZonedDateTime do not work properly
This comes from our JHipster 4 tests at https://github.com/jhipster/generator-jhipster/issues/4301#issuecomment-275901699

- LocalDate and ZoneDateTime cannot be edited - when you edit the entity, there is an error and the page reloads
- ZoneDateTime doesn't show the time (it's the same as LocalDate), so it can't be used properly

### PR DESCRIPTION
**Pull request by VictorADS**
Fix #5006

### CODE REVIEW

**Comment by deepu105** [comment]
@VictorADS I didnt notice the WIP in header, was there anything more to be done here?

**Comment by VictorADS** [comment]
Yes it is working

**Comment by deepu105** [comment]
ok open a new PR if there is anything more to add

**Comment by jdubois** [comment]
Just did a quick test, and it's not working for me... Do we need to release a new "ng-jhipster" for this? Not sure if I'm missing something or not.
If you want to check, that's easy: I'm going to commit very soon https://github.com/jhipster/jhipster-sample-app-ng2 (our new NG2 sample app), and if you go to "operations", there is a date/time field.

**Comment by VictorADS** [comment]
@jdubois  Yes I got a PR on hold for ng-jhipster [see this]( https://github.com/jhipster/ng-jhipster/pull/25).
Once it is merged, we can upgrade and it should be working.

**Comment by jdubois** [comment]
OK, don't forget to do it and upgrade the version number for tomorrow's release :-)

**Comment by gmarziou** [comment]
Also remember that not all browsers support inoput date.

http://caniuse.com/#feat=input-datetime

**Comment by deepu105** [comment]
yes in those we can still enter plain text. I have released and update
ng-jhipster version btw


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
I made some testing this morning and the date picker didn't work for me, but I'm not really sure, I need to check if I update all projects
Can someone else do a quick test to confirm ?

datepicker

**Comment by jdubois** [comment]
good catch @pascalgrimaud , this is being corrected by @VictorADS

**Pull request merged**
