### PR TITLE
Compress png and svg files to speed up page loading

### PR DESCRIPTION
**Pull request by sDaniel**
using tinypng.com and imageoptim.com
I'm using lossless + lossy compression to get ~54% file size reduction (1.285.389 Byte > 593.343 Byte) where I can't spot the difference.

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Thanks @sDaniel that are huge saving! Congrats to your first contribution.

**Comment by sDaniel** [comment]
Thanks for the quick merge. Makes me happy :)

**Comment by PierreBesson** [comment]
Thanks a lot @sDaniel ! Could you document your process in a text file to PR to https://github.com/jhipster/jhipster-artwork

**Comment by atomfrede** [comment]
@sDaniel Can you check `jhipster_family_member_1.svg` again? it is still quite large compared to the others.

**Pull request merged**
