### PR TITLE
Use content as folder name instead of static

### PR DESCRIPTION
**Pull request by avdev4j**
#9880

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@chrisdns @deepu105 Can you take a look please?

**Comment by hdurix** [comment]
Don't forget the bug bounty @avdev4j ;)

**Comment by avdev4j** [comment]
close #9880

**Comment by avdev4j** [comment]
fix #9880

**Comment by avdev4j** [comment]
Bounty claimed ;)

Thanks @hdurix 

https://opencollective.com/generator-jhipster/expenses/8956

**Pull request merged**
