### PR TITLE
application field not sent to prometheus

### LINKED ISSUE #27047: Metrics "application" field not sent to prometheus
##### **Overview of the issue**

The field "application" is not send to prometheus 

##### **Motivation for or Use Case**

the field is not send to prometheus so grafana queries are empty wich implies incorrect grafan dashbord

##### **Reproduce the error**

1. checkout jhipster sample app
2. run the docker compose monitoring
3. run the app 
4. Check that mettrics with "appllication" field is not present in prometheus 

##### **Suggest a Fix**

I just need to add the following properties
management.metrics.tags.application: ${spring.application.name} in application.yml
Maybe is there a better way? using metric registry?

See below picture of prometheus before and after fix. We can that "application" is sent after the fix (first row in the capture)

prometheus

##### **JHipster Version(s)**

8.6.0

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jhipsterSampleApplication",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angular",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "clusteredHttpSession": false,
    "creationTimestamp": 1577000812973,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "embeddableLaunchScript": false,
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [
      "BankAccount",
      "Label",
      "Operation"
    ],
    "entitySuffix": "",
    "hibernateCache": "ehcache",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "8.6.0",
    "languages": [
      "en"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "otherModules": [],
    "packageFolder": "io/github/jhipster/sample",
    "packageName": "io.github.jhipster.sample",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipServer": false,
    "skipUserManagement": false,
    "testFrameworks": [
      "gatling",
      "cypress"
    ],
    "useCompass": false,
    "useSass": true,
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-58)
OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)

git version 2.34.1

node: v20.15.0
npm: 10.7.0

Docker version 27.1.2, build d01f264

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
@ChangelogDate("20150805124838")
entity BankAccount {
  name String required
  balance BigDecimal required
}
@ChangelogDate("20150805124936")
entity Label {
  label String required minlength(3)
}
@ChangelogDate("20150805125054")
entity Operation {
  date Instant required
  description String
  amount BigDecimal required
}

relationship OneToMany {
  BankAccount{operation} to Operation
}
relationship ManyToOne {
  Operation{bankAccount(name)} to BankAccount{operation}
}
relationship ManyToMany {
  Operation{label(label)} to Label{operation}
}

search BankAccount, Label, Operation with no
paginate Operation with infinite-scroll

</pre>
</details>

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vmartowicz**
add the yml property management.metrics.tags.application with value ${spring.application.name} Fix #27047

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by vmartowicz** [comment]
I do not understand the errors

- You have duplicate properties in entity BankAccount: operations
- closing-issues

And I don't know where to add tests about the fix
Do I need something to do?

**Comment by mshima** [comment]
The error is related to :
```
relationship OneToMany {
  BankAccount{operation} to Operation
}
relationship ManyToOne {
  Operation{bankAccount(name)} to BankAccount{operation}
}
```
may be a jdl export bug.

**Comment by vmartowicz** [comment]
Hi @mshima 

Thanks for your response.
So What do I need to do for validating the fix? Wait for the fix about jdl export?
The fix does not concern the error

And what about the second error?

**Review by mshima — APPROVED** [review]

**Comment by mshima** [comment]
@vmartowicz can you share BankAccount and Operation json files from .jhipster folder?

**Comment by vmartowicz** [comment]
@mshima 

Sure, file are from /test-integration/samples/.jhipster path

[BankAccount.json](https://github.com/user-attachments/files/16749641/BankAccount.json)
[Operation.json](https://github.com/user-attachments/files/16749642/Operation.json)

**Pull request merged**
