### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by DanielFran**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@filiphr Trying to update mapstruct from 1.4.0.Final to 1.5.0.Final without change, it fails with 

> NullPointerException: Cannot invoke "javax.lang.model.element.Element.getSimpleName()" 
because the return value of "org.mapstruct.ap.internal.util.TypeUtils.asElement(javax.lang.model.type.TypeMirror)" is null

This seems happening only with maven.

````java
package com.okta.developer.blog.service.mapper;

import com.okta.developer.blog.domain.Blog;
import com.okta.developer.blog.domain.Post;
import com.okta.developer.blog.domain.Tag;
import com.okta.developer.blog.service.dto.BlogDTO;
import com.okta.developer.blog.service.dto.PostDTO;
import com.okta.developer.blog.service.dto.TagDTO;
import java.util.Set;
import java.util.stream.Collectors;
import org.mapstruct.*;

/**
 * Mapper for the entity {@link Post} and its DTO {@link PostDTO}.
 */
@Mapper(componentModel = "spring")
public interface PostMapper extends EntityMapper<PostDTO, Post> {
    @Mapping(target = "blog", source = "blog", qualifiedByName = "blogName")
    @Mapping(target = "tags", source = "tags", qualifiedByName = "tagNameSet")
    PostDTO toDto(Post s);

    @Mapping(target = "removeTag", ignore = true)
    Post toEntity(PostDTO postDTO);

    @Named("blogName")
    @BeanMapping(ignoreByDefault = true)
    @Mapping(target = "id", source = "id")
    @Mapping(target = "name", source = "name")
    BlogDTO toDtoBlogName(Blog blog);

    @Named("tagName")
    @BeanMapping(ignoreByDefault = true)
    @Mapping(target = "id", source = "id")
    @Mapping(target = "name", source = "name")
    TagDTO toDtoTagName(Tag tag);

    @Named("tagNameSet")
    default Set<TagDTO> toDtoTagNameSet(Set<Tag> tag) {
        return tag.stream().map(this::toDtoTagName).collect(Collectors.toSet());
    }
}
````

````java
package com.okta.developer.blog.service.mapper;

import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.Named;
import org.mapstruct.NullValuePropertyMappingStrategy;

/**
 * Contract for a generic dto to entity mapper.
 *
 * @param <D> - DTO type parameter.
 * @param <E> - Entity type parameter.
 */

public interface EntityMapper<D, E> {
    E toEntity(D dto);

    D toDto(E entity);

    List<E> toEntity(List<D> dtoList);

    List<D> toDto(List<E> entityList);

    @Named("partialUpdate")
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void partialUpdate(@MappingTarget E entity, D dto);
}
````

````log
[ERROR] /C:/Users/DanielFRANCO/IdeaProjects/jhipster/test/blog/src/main/java/com/okta/developer/blog/service/mapper/PostMapper.java:[17,8] 
Internal error in the mapping processor: java.lang.NullPointerException: Cannot invoke "javax.lang.model.element.Element.getSimpleName()" 
because the return value of "org.mapstruct.ap.internal.util.TypeUtils.asElement(javax.lang.model.type.TypeMirror)" is null  	
at org.mapstruct.ap.internal.processor.MapperAnnotatedFormattingMessenger.constructMethod(MapperAnnotatedFormattingMessenger.java:100)  	
at org.mapstruct.ap.internal.processor.MapperAnnotatedFormattingMessenger.determineDelegationArguments(MapperAnnotatedFormattingMessenger.java:89)  	
at org.mapstruct.ap.internal.processor.MapperAnnotatedFormattingMessenger.printMessage(MapperAnnotatedFormattingMessenger.java:50)  	
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.reportErrorForUnmappedTargetPropertiesIfRequired(BeanMappingMethod.java:1592)  	
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:308)  	
at org.mapstruct.ap.internal.model.AbstractBaseBuilder.createForgedAssignment(AbstractBaseBuilder.java:98)  	
at org.mapstruct.ap.internal.model.AbstractMappingMethodBuilder.forgeMapping(AbstractMappingMethodBuilder.java:95)  	
at org.mapstruct.ap.internal.model.AbstractMappingMethodBuilder.forgeMapping(AbstractMappingMethodBuilder.java:57)  	
at org.mapstruct.ap.internal.model.ContainerMappingMethodBuilder.forge(ContainerMappingMethodBuilder.java:169)  	
at org.mapstruct.ap.internal.model.ContainerMappingMethodBuilder.lambda$build$0(ContainerMappingMethodBuilder.java:100)  	
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:322)  	
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:169)  	
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:145)  	
at org.mapstruct.ap.internal.model.ContainerMappingMethodBuilder.build(ContainerMappingMethodBuilder.java:93)  	
at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeWithElementMapping(PropertyMapping.java:748)  	
at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeIterableMapping(PropertyMapping.java:733)  	
at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forge(PropertyMapping.java:305)  	
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:322)  	
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:169)  	
at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:145)  	
at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:256)  	
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1404)  	
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1368)  	
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:294)  	
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:418)  	
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:181)  	
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:135)  	
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:82)  	
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:350)  	
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:330)  	
at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:279)  	
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:174)  	
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)  	
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)  	
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)  	
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)  	
at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)  	
at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)  	
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)  	
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)  	
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)  	
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)  	
at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:136)  	
at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:182)  	
at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1209)  	
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:198)  	
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)  	
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)  	
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)  	
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)  	
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)  	
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)  	
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)  	
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)  	
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)  	
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)  	
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)  	
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)  	
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)  	
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)  	
at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)  	
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)  	
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	
at java.base/java.lang.reflect.Method.invoke(Method.java:568)  	
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)  	
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)  	
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)  	
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)  	
at org.codehaus.classworlds.Launcher.main(Launcher.java:47)  
````

**Comment by filiphr** [comment]
Really strange error @DanielFran. Thanks for pinging me. We are going to investigate this asap.

**Comment by filiphr** [comment]
And the problem has been located. There is a fix incoming https://github.com/mapstruct/mapstruct/pull/2868. We will try to do a release once the fix is merged.

For reference, the NPE is happening because there is a warning on the partial update for unmapped target properties. That warning always existed. However, the NPE is due to a new enhancement we've done to report warnings form parent interfaces on the main mapper interface. In this case the `PostMapper`.

-------

From a more conceptual side for JHipster (because I do not know how your are generating the mappers).
I saw that the `toEntity` method is overridden and does:

```
  @Mapping(target = "removeTag", ignore = true)
    Post toEntity(PostDTO postDTO);
```

The unmapped target property is `removeTag` in the `partialUpdate` as well.

This means that doing:

```
    @Named("partialUpdate")
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void partialUpdate(@MappingTarget Post entity, PostDTO dto);
```

i.e. overriding the method in the `PostMapper`.

**Comment by filiphr** [comment]
We just released 1.5.1.Final with the fix for this problem. You should be able to get it soon.

**Comment by mshima** [comment]
> From a more conceptual side for JHipster (because I do not know how your are generating the mappers). I saw that the `toEntity` method is overridden and does:
> 
> ```
>   @Mapping(target = "removeTag", ignore = true)
>     Post toEntity(PostDTO postDTO);
> ```
> 
> The unmapped target property is `removeTag` in the `partialUpdate` as well.
> 
> This means that doing:
> 
> ```
>     @Named("partialUpdate")
>     @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
>     void partialUpdate(@MappingTarget Post entity, PostDTO dto);
> ```
> 
> i.e. overriding the method in the `PostMapper`.

@filiphr I didn’t understand what we have to change.

**Comment by filiphr** [comment]
Sorry that post got a bit of mixed up. The `partialUpdate` snippet was meant to show how the problem can be fixed temporarily.

However, the conceptual problem, which I guess is up to you. Is regarding the `@Mapping(target = "removeTag", ignore = true)`. I guess you are adding that on the `toEntity` in order for the user not to have the warning for an unmapped target property. However, the `partialUpdate` does not have that and has a warning for the unmapped target property `removeTag`.

**Comment by mshima** [comment]
@filiphr ok thanks.

**Review by mshima — APPROVED** [review]

**Comment by DanielFran** [comment]
Thanks @filiphr for the fixed release

**Pull request merged**
