### PR TITLE
add uaa back to tokenRelay filter

### PR DESCRIPTION
**Pull request by xetys**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Oops you broke the build, @xetys can you check?

**Comment by xetys** [comment]
it looks more like a travis issue. I cannot imagine I broke the built by adding an if statement

**Comment by xetys** [comment]
k wait...maybe not...i'll check

**Comment by jdubois** [comment]
No I fixed it yesterday evening :-)

**Pull request merged**
