### PR TITLE
JDL-related code cleaning

### PR DESCRIPTION
**Pull request by MathieuAA**
Does a few things:
  - remove deprecated functions
  - refactor the app / entity exporters (noticed thanks to a PR from Marcelo)

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by MathieuAA** [comment]
Error:
```

The dependencies of some of the beans in the application context form a cycle:

   cassTestServiceClassEntityService defined in URL [jar:file:/home/runner/app/app.jar!/BOOT-INF/classes!/io/github/jhipster/sample/service/CassTestServiceClassEntityService.class]
      ↓
   cassTestServiceClassEntityRepository
      ↓
   org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration
┌─────┐
|  cassandraCluster defined in class path resource [org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.class]
↑     ↓
|  cassandraConfiguration (field private com.datastax.driver.core.Cluster io.github.jhipster.sample.config.cassandra.CassandraConfiguration.cluster)
└─────┘
```

**Comment by mshima** [comment]
Another cleanup is to don't create creationTimestamp if it's not there, the generator should handle a missing creationTimestamp.
There is a lot of duplicate code due to creationTimestamp.

**Comment by MathieuAA** [comment]
Ah :) great! I'll ask for directions to you then when I'll be tackling that

**Comment by DanielFran** [comment]
Relaunched tests

**Pull request merged**
