### PR TITLE
fix for console error on user management create dialog

### LINKED ISSUE #6593: Console error in User management Angular 4
##### **Overview of the issue**

Hello, a console error is thrown when user create dialog is opened in gateway. Doesn’t seem to cause any issue.

##### **Reproduce the error**
Create an app with jwt, run ./mvnw and open localhost:8080 and go to user management entity. Open user create dialog and look at console.

`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'userManagement.home.createOrEditLabel` ...

I can't display the full log error and configuration to security restriction.

##### **Related issues**

#5985 

##### **JHipster Version(s)**

4.10

##### **Browsers and Operating System**

Windows 10, centos 7
Firefox and chrome

### PR DESCRIPTION
**Pull request by ruddell**
aligns code in user-modal.service.ts with entity-popup.service.ts

Fix #6593

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by ruddell** [comment]
I added a test for the user-management-detail.component.ts file but I couldn't get a test for the user-management.component.ts working (I dont normally use Angular). This adds about 2% coverage.

**Comment by deepu105** [comment]
Ill take a look

**Comment by cbornet** [comment]
The CI was green for the PR but when merged to master, it's now [failing](https://travis-ci.org/jhipster/generator-jhipster/jobs/297688560)...

**Comment by pascalgrimaud** [comment]
yes, I noticed that. It seems to concern prod build only. It was green 7 days ago, so it's indirectly related to code from master too

**Comment by pascalgrimaud** [comment]
It should be back to green. Random failures...

**Pull request merged**
