### PR TITLE
Fix the SortDirective by using jhiSort from ng-jhipster

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix https://github.com/jhipster/generator-jhipster/issues/5019

### CODE REVIEW

**Comment by ruddell** [comment]
user-management.component.html has `<%=jhiPrefix%>SortBy` as well

**Comment by pascalgrimaud** [comment]
@ruddell : mhhhh I don't see it lol !
https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/admin/user-management/_user-management.component.html

**Comment by ruddell** [comment]
You're right haha, my master is a few hours old

**Comment by deepu105** [comment]
Oh ok I checked again and see that I indeed fixed it but I commited only user management part and the entity part is still on my local thats why it works locally for me. damn i'm tired :) thanks @pascalgrimaud

**Pull request merged**
