### PR TITLE
fix: From Yarn 1.0 scripts don't require "--" for options to be forwarded.

### PR DESCRIPTION
**Pull request by aneri90**
Resolve YARN warn:
`From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.`

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by wmarques** [comment]
@aneri90 Thanks for your PR. I think we still use the `--` because we need to be still compliant with NPM even we encourage our users to use yarn... If I'm not wrong NPM still requires those ugly `--` 😞

**Comment by aneri90** [comment]
Oh snap! You are right.. npm still needs it. 
Thanks for the reply! Closing PR

**Comment by pascalgrimaud** [comment]
I think we can use something like that:
- use a variable at the beginning of the file:
    - for NPM: `-- --`
    - for Yarn: `--`
- then, use this variable instead of all these `-- --`, so it will work for both: NPM and Yarn

**Comment by sendilkumarn** [comment]
@aneri90 go for it, it is kinda ugly to have that warning when running the application with `yarn`

**Comment by aneri90** [comment]
I have changed and rebased my PR to avoid dirty commits. I cannot reopen this PR.. should I open another one?

**Comment by jdubois** [comment]
I don't know why, but yes open up a new PR

**Pull request closed without merging**
