### PR TITLE
Fix jdl with micro service daily builds.

### PR DESCRIPTION
**Pull request by mshima**
Fix jdl with micro service daily builds.
- jdl should not add an empty `clientRootFolder` for `microservice` and `gateway` applications, it should be the microservice name by default.
- always calculate `clientRootFolder` for gateway applications.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Merging to test daily builds.

**Comment by mshima** [comment]
Looks like I don't have permission to trigger a rebuild for failed builds.

**Comment by pascalgrimaud** [comment]
Just invited you, to join the organization @mshima

**Comment by mshima** [comment]
Thanks @pascalgrimaud

**Pull request merged**
