### PR TITLE
Reduce code duplication on entity save response handling

### PR DESCRIPTION
**Pull request by gzsombor**
The same code is repeated twice for updating and inserting entity - this can be refactored to a separate function

### CODE REVIEW

**Comment by gzsombor** [comment]
Not clear, why the travis builds are failing

**Comment by pascalgrimaud** [comment]
@gzsombor : the failures come from protractor. Travis doesnt like when there are too much login/logout... nothing related to your PR
I will try to improve that the next days

**Comment by deepu105** [comment]
@pascalgrimaud may instead of login/logout per entity we can do it once for all entities together

**Comment by pascalgrimaud** [comment]
@deepu105 : so 1 file for protractor, with entities, and we could add a needle in it:
- login
- test entity 1
- test entity 2
- (...)
- logout

Sounds good!

**Comment by deepu105** [comment]
Im not talking about 1 file. I would still like 1 file per entity otherwise
its difficult to maintain for real use case but somehow if we can do the
login logout outsude of each file it will be faster and better. Ideally if
we could login/logout once per run that would be great

**Comment by pascalgrimaud** [comment]
Sure @deepu105 there are different solutions and we can improve the protractor tests!

**Comment by gzsombor** [comment]
Anyway, so there is no opposition agains merging this patch ? 😄

**Pull request merged**
