### PR TITLE
Add microfrontend support to vue.

### PR DESCRIPTION
**Pull request by mshima**
Vue modularization for microservice:
- Implement entities component. Declare every entity service here instead of at main.
- Implement entities menu component. So gateway will not need to add menus when adding entities.
- Move global variables to declarations.d.ts

Webpack:
- Don’t set custom names. Defaults are optimized for features like cachings.
- Remove additional entry points. They are not required and conflicts with module federation.
- Remove custom chunks definitions.
- Don’t add HotModulePlugin. Added automatically by webpack when hot is true.
- Don’t add NoEmitOnErrorPlugin. A missing page seems worse than a broken page.
- Remove fallback config. Not required anymore. Node features are not exported by webpack anymore.
- Migrate from deprecated url-loader to assets module.
- Move devServer config to common, so it's possible to `webpack serve --mode production`

Microfrontend details:
- Microfrontends needs to be started and functional, remote is loaded eagerly.
I've tried different approaches to lazy load without success.
- Gateway doesn't need to be regenerated when adding new entities.
- Entity page is using `microservice/entity` instead of just `entity`. Example `http://localhost:8080/blog/post`.

Closes https://github.com/jhipster/generator-jhipster/issues/16276.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Just missing entities-menu test.

**Comment by mraible** [comment]
I'll look into this as soon as I can. It might take until Monday.

**Comment by pascalgrimaud** [comment]
@mshima @mraible : it looks like a really complex PR. Keep in mind, we should not introduce breaking change in existing v7. If it's the case, it should be done on v8 branch

**Comment by mshima** [comment]
@pascalgrimaud I think this is not a breaking change.
IMO it's much less disruptive than a minor spring release or bootstrap 5 or dropping java 1.8 support.
The PR is big but most of the changes are new implementations or prettier.
Some adjusts to the build stack like removing deprecated webpack plugins and cleanup.

Anyway, if you want I can try to make more changes optional to microfrontend.

IMO breaking changes to JHipster should be jdl, the generators and some generated source features, not the source itself.
It's quite easy to keep old code with .yo-resove:
```
src/main/webapp skip
src/test/javascript skip
```

**Comment by mraible** [comment]
@mshima This PR needs a rebase. I'm testing it now.

**Comment by mraible** [comment]
I tried with `jhipster jdl reactive-ms --microfrontend` and it appears to use Vue for the gateway, but not for the blog or store. It used to be that you only need to specify `clientFramework vue` for the gateway. Is this required for the microservices as well when using micro frontends?

**Comment by mraible** [comment]
I tried specifying `clientFramework vue` for the blog and store microservices, yet it still generates Angular clients for those. Here's the JDL I'm using:

```
application {
  config {
    baseName gateway
    reactive true
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    buildTool gradle
    clientFramework vue
    prodDatabaseType postgresql
    serviceDiscoveryType eureka
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog
    reactive true
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    clientFramework vue
    databaseType neo4j
    devDatabaseType neo4j
    prodDatabaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType eureka
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    reactive true
    packageName com.okta.developer.store
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    clientFramework vue
    databaseType mongodb
    devDatabaseType mongodb
    prodDatabaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType eureka
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}
```

Copy this to an `app.jdl` file and run `jhipster jdl app.jdl --microfrontend` and you'll see that the blog and store apps are using Angular.

Ideally, this wouldn't matter and you could mix and match web frameworks. I'm not sure this is a good idea, but I was thinking it might work. However, when I load up http://localhost:8080, I get an error page and a 404 in the logs.

```
2021-11-01 21:52:44.180  WARN 76502 --- [     parallel-6] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUNDotRun
2021-11-01 21:52:44.181  WARN 76502 --- [     parallel-5] o.z.problem.spring.common.AdviceTraits   : Not Found: 404 NOT_FOUND
```

**Comment by mshima** [comment]
@mraible I've always used reused https://github.com/mshima/generator-jhipster/blob/main/test-integration/jdl-samples/blog-store/blog-store.jdl and used `--client-framework vue`.
I didn't realized the jdl is removing clientFramework and setting the default afterwards. So it needs change: https://github.com/jhipster/generator-jhipster/blob/dffe240bddc8d13eb692b97dcb9b7981e7e3e290/jdl/jhipster/default-application-options.js#L172-L176

**Comment by mshima** [comment]
@mraible jdl should be fixed now.

**Comment by mraible** [comment]
I tried it again a few minutes ago. If I just start the gateway and store, the gateway UI fails because it can't find blog. Is that expected? I think it'd be nice if you could just start the gateway + the microservice you want to work on.

Screen Shot 2021-11-11 at 12 48 17 PM

If I start the blog app, everything works fine. However, the blog's i18n translations don't seem to come through. They work fine on the product entity.

Screen Shot 2021-11-11 at 12 52 31 PM

**Comment by mshima** [comment]
> I tried it again a few minutes ago. If I just start the gateway and store, the gateway UI fails because it can't find blog. Is that expected? I think it'd be nice if you could just start the gateway + the microservice you want to work on.

You can start the gateway and use the microservice frontend standalone.
I couldn't find a way to make vue gateway happy with the missing remote. Probably we would need vue3 suspense component https://v3.vuejs.org/guide/migration/suspense.html.
I have tried various approaches.

> If I start the blog app, everything works fine. However, the blog's i18n translations don't seem to come through. They work fine on the product entity.

That's weird, if store app (product) works, blog app should work too.

**Comment by mshima** [comment]
> I tried it again a few minutes ago. If I just start the gateway and store, the gateway UI fails because it can't find blog. Is that expected? I think it'd be nice if you could just start the gateway + the microservice you want to work on.

Did another try, and I've managed to workaround the missing remote.

> If I start the blog app, everything works fine. However, the blog's i18n translations don't seem to come through. They work fine on the product entity.

Indeed, microservice translations of one app was been loaded before the gateway and been overridden.

**Comment by mraible** [comment]
I'm testing this again with the latest changes.

**Review by mraible — APPROVED** [review]
I tested this again today and things seem to work well. I did notice a couple of minor issues:

1. The UI seems to need a bit more padding. The buttons and alerts stretch to the edge of the screen.

Screen Shot 2021-11-15 at 2 20 42 PM
 
2. The view screen shows everything jumbled together instead of stacked neatly.

Screen Shot 2021-11-15 at 2 23 28 PM

**Comment by mraible** [comment]
I couldn't find where the index.html message is set, but I think we should change it from:

> Microfrontends packages don't provide a stand-alone front-end. Packaged microfrontend should be accessed through a JHipster gateway. 

To:

> JHipster's microfrontends implementation doesn't provide a stand-alone UI. Packaged microfrontends should be accessed through a JHipster gateway.

**Comment by mshima** [comment]
Ought I've removed `global.scss` in some rebase.

**Comment by pascalgrimaud** [comment]
@mraible @mshima : plz, don't forget to add some documentation. See https://github.com/jhipster/generator-jhipster/issues/17016

We have a lot of new features the last months, but no documentation at all :-(

**Pull request merged**
