### PR TITLE
Cassandra : add field type blob to entity generator

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Following #1703

Here the doc: https://docs.datastax.com/en/latest-java-driver/java-driver/reference/javaClass2Cql3Datatypes.html

There are some improvments, which can be done later (min/max size for example)

Ping @cbornet and @raphaelbrugier if you can review my PR :)

### CODE REVIEW

**Comment by raphaelbrugier** [comment]
Hi @pascalgrimaud,

I've tested blobs and cassandra with a few cases and it worked great!
LGTM

Unrelated, but there is a glitch in the ui with image and bin blobs, already existing in the master.
In the dialogbox, an extra comma is displayed by the help-block.
I'll open a bug for it.

**Comment by pascalgrimaud** [comment]
Thanks for testing it @raphaelbrugier

Yes I saw the extra comma too, lol.

**Comment by pascalgrimaud** [comment]
Just woke up, I was going to resolve conflict.
You're so fast @deepu105 ! Thanks you

**Comment by deepu105** [comment]
I was bored :)

Thanks & Regards,
Deepu

**Pull request merged**
