### PR TITLE
Server common scripts

### LINKED ISSUE #12697: Provide extensibility to use other frontend module bundler
##### **Overview of the feature request**

Currently, in all frontend framework implementations (`react`, `vue`, `angular`), `webpack` is used as a module bundler and the bundler name (webpack) is hard-coded in all scripts (including server side, CI). It leaves little option as blueprint authors to try other module bundlers like `rollup` and `parcel`.

I suggest to externalize the module bundler name as an option (like used for `yarn` before) and keep `webpack` as default option value (like used for `npm` before). 

##### **Motivation for or Use Case**

As a blueprint author, I would like to use `rollup` or `parcel` instead of `webpack` without overriding server-side code and scripts.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vishal423**
Closes #12697 
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
LGTM
Any chance for updating jhipster bom and the daily builds too plz @vishal423 ?

**Comment by vishal423** [comment]
> 
> 
> LGTM
> Any chance for updating jhipster bom and the daily builds too plz @vishal423 ?

Will try in next few days. bit down with cold 🤒

**Comment by pascalgrimaud** [comment]
I'm putting label on-hold, as we can't merge it without updating jhipster-bom and daily builds. Otherwise, it will fail there.

**Comment by vishal423** [comment]
@pascalgrimaud, I believe we are good now. I don't see any occurrence of `webpack` in the daily builds repository.

**Comment by pascalgrimaud** [comment]
Thanks @vishal423 : maybe we need to update our documentation too ?

**Pull request merged**
