### PR TITLE
Fix Protractor tests

### PR DESCRIPTION
**Pull request by mraible**
Fix location of selenium-server JAR
Disable directConnect since it doesn’t work with latest Firefox (45.0.1)

### CODE REVIEW

**Comment by mraible** [comment]
Is it possible to see the workspace for the applications generated? I'd like to see what version of the Selenium JAR is downloaded.

**Comment by pascalgrimaud** [comment]
You can't access to travis build.There are logs but maybe not enough for what you're looking for
You have to change the travis scripts and add `ls -al` for example, to folders you want

**Comment by pascalgrimaud** [comment]
I restarted the build but I don't understand why travis failed with gradle only...
On my local, it's ok

**Comment by mraible** [comment]
I'm not sure why the following needed to be removed:

```js
browser.driver.wait(protractor.until.elementIsVisible(element(by.css('h1'))));
```

With it in `beforeAll`, the following error happens:

```
Failures:
1) account should fail to login with bad password
  Message:
    Failed: WebElementCondition did not resolve to a WebElement: [object Object]
  Stack:
    TypeError: WebElementCondition did not resolve to a WebElement: [object Object]
        at TypeError (native)
        at /Users/mraible/blog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:698:17
        at Promise.invokeCallback_ (/Users/mraible/blog/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/Users/mraible/blog/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/mraible/blog/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /Users/mraible/blog/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /Users/mraible/blog/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:368:9)
    From: Task: Run beforeAll in control flow
        at Object.<anonymous> (/Users/mraible/blog/node_modules/protractor/node_modules/jasminewd2/index.js:81:14)
    From asynchronous test:
    Error
        at Suite.<anonymous> (/Users/mraible/blog/src/test/javascript/e2e/account/account.js:11:5)
        at Object.<anonymous> (/Users/mraible/blog/src/test/javascript/e2e/account/account.js:3:1)
        at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
```

However, if it's not needed - great! I think the tests are cleaner without it.

**Comment by pascalgrimaud** [comment]
maybe can we delete the branch protractor-fix ?

**Comment by mraible** [comment]
Done!

**Pull request merged**
