### PR TITLE
Fix i18n zh

### PR DESCRIPTION
**Pull request by liseri**
In #4316 , I discover encoding problem of file `zh-cn/gateway.json`.
In this pull, I do:
- fix encoding problem:  ASCII => UTF-8 of file `zh-cn/gateway.json`
- fix some i18n value not so accurate about gateway

### CODE REVIEW

**Comment by sendilkumarn** [comment]
Can you please rebase ?

**Comment by liseri** [comment]
@sendilkumarn  Oh, sure. Thanks for remind. Let me try.

**Comment by liseri** [comment]
Ah, #4316 had merged and closed. I cannot find the way to rebase it. It feasible?

**Comment by deepu105** [comment]
I squashed it so its ok

**Pull request merged**
