### PR TITLE
add the hand on the sortable header

### PR DESCRIPTION
**Pull request by ctamisier**
Add the hand on the sortable header

### CODE REVIEW

**Comment by gmarziou** [comment]
While this works, it should be better to define a CSS class for all these elements that should have this behavior rather than doing it in code because this way it can be overwritten by anyone  without coding.

**Comment by deepu105** [comment]
We already have a `hand` class so you just need to add it where needed

**Comment by ctamisier** [comment]
actually it might be better to let only the sort icon running the sort instead of the whole header...

**Comment by deepu105** [comment]
@ctamisier I would prefer the header to act as sort click are as it was before. From a usability perspective having it only on the icon makes it harder to click and hence not so user friendly. So unless you have a strong reason to make the change please revert back your last commit

**Comment by ctamisier** [comment]
sure!

**Comment by ctamisier** [comment]
I added `jh-table` class in the user management table (to be the same that the entity management table). This adds a style on the sorting icon when we pass the mouse over.

**Pull request merged**
