### PR TITLE
AWS Elastic-beanstalk instance profile creation missing from new iam class

### PR DESCRIPTION
**Pull request by ggotti**
As part of #7443 I failed to correctly define the instance profile as part of the role creation process. When the instance profile is not available, the application will not deploy correctly in Elastic Beanstalk. 

@jdubois would you mind having a look at this PR before it's merged. You'll want to remove the following roles via the web-interface to verify the creation process:

- aws-elasticbeanstalk-ec2-role
- aws-elasticbeanstalk-service-role

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Merging as this already broken anyway :-)
I'll test soon

**Comment by jdubois** [comment]
@ggotti it's working much better as I can now deploy to Beanstalk!! That's a huge improvement.

However, when I try to log in the application, I get a 404 error - that's very strange as if we have the login page, it means the application was deployed (the login page is inside the application!). I can't get the logs, as I didn't find how to configure CloudWatch :-(
Can you try deploying and see if you can log in?

**Comment by ggotti** [comment]
@jdubois I've found the issue, but haven't fixed it. I've raise this issue to track the discussion: https://github.com/jhipster/generator-jhipster/issues/7520

**Comment by jdubois** [comment]
Thanks !!

**Comment by mistvan** [comment]
Hi guys, was this issue already released please? I tested using jhipster 5.0.2. Creating bucket and uploading war works fine. But experiencing issue with creating database - some resource is not in dbavailable status - same as somebody mentioned in referenced issues. Many thanks

**Comment by jdubois** [comment]
It's merged and closed so this is released - you probably have something else, or this PR wasn't solving everything, you can open a new ticket if needed

**Pull request merged**
