### PR TITLE
fix react admin menu using module federation.

### PR DESCRIPTION
**Pull request by mshima**
Fixes https://github.com/jhipster/generator-jhipster/issues/21990

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
I tried re-creating everything using this branch, and the error still happens. 

Screenshot 2023-05-23 at 2 28 30 PM

**Comment by mshima** [comment]
Indeed, I fixed locally with others modifications that cannot be applied.
This only fixes a warning.

**Comment by mshima** [comment]
Using dynamic module federation load is the only way I found to fix the problem.
It makes the experience better.
But `@angular-architects/module-federation-runtime` has a unused dependency on angular.
I've created https://github.com/angular-architects/module-federation-plugin/pull/324.
But we will probably need to fork the lib.

**Comment by mshima** [comment]
I've switched to `@module-federation/utilities`.
Should work now.

**Review by mraible — APPROVED** [review]
I tested this branch with the JDL from the issue it fixes. Everything works as expected!

**Pull request merged**
