### PR TITLE
use promise to parallelise protractor input

### PR DESCRIPTION
**Pull request by Tcharl**
Wip: Use promise.all to parallelize protractor inputs.
This as reduced the time of our build by two on a big project!

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by wmarques** [comment]
@Tcharl I have to try this out :o

**Comment by pascalgrimaud** [comment]
Some error in Travis: https://travis-ci.org/jhipster/generator-jhipster/builds/436354159
Can you have a look plz ?

**Comment by Tcharl** [comment]
Sure, I'll take a look asap sorry for the inconvenience

**Comment by pascalgrimaud** [comment]
don't be sorry for contributing plz :)

**Pull request merged**
