### PR TITLE
Loggers should be 'private static final'

### PR DESCRIPTION
**Pull request by qmonmert**
Same as #26531 without renaming

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by mraible — APPROVED** [review]

**Comment by mshima** [comment]
Does this PR fixes the issue?

**Comment by qmonmert** [comment]
@mshima which issue?

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/pull/26531#issuecomment-2187312268

**Review by mshima — APPROVED** [review]
Not merging since I am considering we are in code freeze due to the release.

**Comment by qmonmert** [comment]
@mshima this PR is a simplified PR of #26531 because we must decide if we rename `log` into `LOGGER`

**Comment by mshima** [comment]
> @mshima this PR is a simplified PR of #26531 because we must decide if we rename `log` into `LOGGER`

So the issue still exists with lower case `log`. Am I correct?

`LOG` should be accepted too.

**Pull request merged**
