### PR TITLE
fix main generator tests

### LINKED ISSUE #2639: npm test broken
`npm test` seems to be OK, but in fact, it doesn't work anymore.
I think it is related to https://github.com/jhipster/generator-jhipster/pull/2565/ : @geraldhumphries if you have time, can you have a look plz ?

Steps to reproduce :

1) launch `npm test` => it's OK

```shell
$ ~/workspace/generator-jhipster $ npm test

> generator-jhipster@2.26.2 test /home/pgrimaud/workspace/generator-jhipster
> mocha --reporter spec



  JHipster generator
    ✓ creates files for default configuration
    ✓ creates files with a specific package name
    ✓ creates files with a specific application name
    ✓ creates expected files with authenticationType "oauth2"
    ✓ creates expected files with hibernateCache "hazelcast"
    ✓ does not create i18n files if i18n is disabled
    ✓ creates expected files with social login enabled
    ✓ creates files for default configuration with skip client option enabled

  JHipster generator
    ✓ can be imported without blowing up (481ms)


  9 passing (615ms)
```

2) made a change in test/test-creation.js for example, by changing a name file

```diff
diff --git a/test/test-creation.js b/test/test-creation.js
index 9fbad3a..b823db9 100644
--- a/test/test-creation.js
+++ b/test/test-creation.js
@@ -30,7 +30,7 @@ describe('JHipster generator', function () {
             })
             .on('end', function () {
                 assert.file([
-                    'bower.json',
+                    'helloBower.json',
                     'package.json',
                     'README.md',
                     '.bowerrc',

```

3) launch test

```shell
$ npm test

> generator-jhipster@2.26.2 test /home/pgrimaud/workspace/generator-jhipster
> mocha --reporter spec



  JHipster generator
    ✓ creates files for default configuration
    ✓ creates files with a specific package name
    ✓ creates files with a specific application name
    ✓ creates expected files with authenticationType "oauth2"
    ✓ creates expected files with hibernateCache "hazelcast"
    ✓ does not create i18n files if i18n is disabled
    ✓ creates expected files with social login enabled
    ✓ creates files for default configuration with skip client option enabled

  JHipster generator
    ✓ can be imported without blowing up (492ms)


  9 passing (630ms)
```

### PR DESCRIPTION
**Pull request by geraldhumphries**
fix main generator tests broken by #2565 and reorganized them according to
guidelines from http://yeoman.io/authoring/testing.html

fix #2639

### CODE REVIEW

**Comment by geraldhumphries** [comment]
Tests have been individually verified for failing/passing properly. 

Good news, no tests are failing so nothing was broken while the tests weren't working, and it's now easier to write multiple tests for the same feature. For example, the `skip client` test can be split into a 'created files' test and 'didn't create files' test.

**Comment by deepu105** [comment]
@geraldhumphries one question when the tests are running I dont see any file creation being shown or any console log from generator why is it so?

**Comment by deepu105** [comment]
Also there is a random timeout error in windows, hope its ok in Linux

**Comment by geraldhumphries** [comment]
I have always had to run mocha with `-t 20s` on windows to avoid timeouts. Testing it now, I still get random timeouts on the commit before #2565 (3becfa8).

The console output displays in commit 3becfa8, but when I am on master and revert only `test-creation.js` the console output disappears. That makes me think it is not related to my changes. Maybe a dependency update?

**Pull request merged**
