### PR TITLE
Replace jshint by eslint with angular plugin.

### PR DESCRIPTION
**Pull request by gmarziou**
This is a first step with many errors reported as our code base is rather heterogeneous regarding style and also @wmarques  is currently modifying our code to follow John Papa's guidelines, so I did not want to create merge conflicts with his work.

There are still few jshint comments to be removed or replaced by eslint equivalents.

Ref #2972

### CODE REVIEW

**Comment by deepu105** [comment]
There is no more notification on error :(

**Comment by gmarziou** [comment]
- If you mean what jsHintErrorReporter.js did then you're correct as I did not understand its purpose.
- if you mean build does not fail in case of error then it's because I disabled it until we fix the code.

AFAIK it could be done like below:

~~~javascript
        // To have the process exit with an error code (1) on
        // lint error, return the stream and pipe to failAfterError last.
        .pipe(eslint.failAfterError());
~~~

**Comment by deepu105** [comment]
jsHintErrorReporter.js was for Jshint to do custom error reporting.

my query was removal of this `.pipe(plumber({errorHandler: handleErrors}))`

this will show a notification for error

**Comment by gmarziou** [comment]
My mistake, I added the line and tested it.

For now, eslint task is not part of any other task, it could be part of watch but it could be annoying or maybe it could be part of test.

**Comment by deepu105** [comment]
lets merge and improve later. All the john papa style stuff are done so now this should give less errors

**Comment by deepu105** [comment]
@gmarziou btw do we still need the `.jshintrc` file?

**Comment by deepu105** [comment]
now there are couple of errors Im gonna try and fix them

**Comment by deepu105** [comment]
its done here https://github.com/jhipster/generator-jhipster/commit/b77a2d49435e819d0ca7fc6ae59b7c075895dd90

now there are no eslint errors @gmarziou can you plz test. do we have to add any more rules?

**Comment by deepu105** [comment]
I think the notification doesnt work we may have tow rite a custom reporter like the one we had for jshint

**Comment by gmarziou** [comment]
Normally, we have already [recommended rules from eslint (the ones with checkbox)](http://eslint.org/docs/rules/) and the ones from the angumar plugin. 
We can add some stylistic rules like 'use strict' or we can turn some warning into errors.

Regarding notifications, what is the symptom? When I re-enabled them, it seemed to me they were working on Ubuntu even though I did not really understand how to close them but I must admit that last months I have worked more on backend rather than frontend, so I did not know what to expect here.

**Comment by deepu105** [comment]
Ok im on windows for me earlier if i make a mistake in js or something Ill get an instant windows notification popup for it from gulp serve by jshint, but im not getting that from eslint like below

https://cloud.githubusercontent.com/assets/1773153/12733289/4c300890-c93a-11e5-8322-75755ae80bd5.png

**Comment by gmarziou** [comment]
OK, I got similar notification except that it showed only error text and not the source file which is what the jsHintErrorReporter was doing I guess.

**Pull request merged**
