### PR TITLE
Post entity creation Module hook

### PR DESCRIPTION
**Pull request by deepu105**
add post entity hook for modules

restructure entity sub generator to follow yeoman naming convention and run context priority

update to yo 1.5.1

move util methods to script base

@jhipster/developers I guess github is not showing diff of entity/index.js as it would look like a complete file change due to format change, I havent changed any logic, just changed the structure and added the post entity hook method at the end of the file

### CODE REVIEW

**Comment by cbornet** [comment]
+1
Next, we should have methods to do actions on all existing entities (like replaceContent for instance)

**Comment by deepu105** [comment]
@cbornet I already did this in the module, added replaceContent and rewriteFile methods, but we can add more yes

**Comment by deepu105** [comment]
@jdubois did you get a chance to review this? are you ok with it?

**Comment by jdubois** [comment]
Yes let's do this

**Comment by deepu105** [comment]
Awesome

**Pull request merged**
