### PR TITLE
Move clientwebpack needle from base

### PR DESCRIPTION
**Pull request by Tcharl**
Move some methods from base to client generator
---
Contributes to #20295

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
If we add a needles to client and cypress, we will need to add same needle to angular, react and vue.
The idea is to use the `source` object which is shared between every generator, inject the needle and use it in any generator.
In this case the webpack needle should have a common api and angular, react and vue will inject its own needle.

You can see a needle injection here:
https://github.com/jhipster/generator-jhipster/blob/8d55f965b4a51cc8e89f18318aaa2d11b11f76ba/generators/docker/generator.mjs#L48-L59
And bellow it's using the needle:
https://github.com/jhipster/generator-jhipster/blob/8d55f965b4a51cc8e89f18318aaa2d11b11f76ba/generators/docker/generator.mjs#L110-L117

**Comment by mshima** [comment]
I don't agree to add the same needle to 2 different generators even if temporary.

**Comment by Tcharl** [comment]
Thanks for the explaination, it was indeed blurry to me to have something injected which wasn't explicitely called (is there a way to explicitely call it during one of the generator phase so that statement will be clear?

The only remaining blurry stuff is the fact that 'angular', 'vue' and 'react' generator needs it (of the reverse, why client generator needs it).

Either we should use 'client' subgen to be in charge of everything which is in common to all clients generators (cypress included), or either we let the leafs generators to be in charge of injecting needles and stuff. I would be mitigated on the fact that both handles should do.

I'm personally in favor of the second option, e.g. to get only angular, react, vue and cypress generator extending `AbstractJHipsterClientGenerator`.

Your thought?

**Comment by mshima** [comment]
> Thanks for the explaination, it was indeed blurry to me to have something injected which wasn't explicitely called (is there a way to explicitely call it during one of the generator phase so that statement will be clear?

Needles should always be used at postWriting. The source parameter is only available at `preparing` for injection and `postWriting` for use.
https://github.com/jhipster/generator-jhipster/blob/ab599e070a346952290c87672b3428712a06e0fa/generators/base/generator.mts#L245-L248

> The only remaining blurry stuff is the fact that 'angular', 'vue' and 'react' generator needs it (of the reverse, why client generator needs it).

It's not about why client generator needs it, but which customization a blueprint can apply.
At jhipster v7 the needles api is available to every generators and a single generator can customize everything like it is stated in the docs:
https://www.jhipster.tech/modules/creating-a-blueprint/#local-blueprints.
`so a single sub-generator, the main one, is probably enough to customize your application (client and server).`

> Either we should use 'client' subgen to be in charge of everything which is in common to all clients generators (cypress included), or either we let the leafs generators to be in charge of injecting needles and stuff. I would be mitigated on the fact that both handles should do.

There is almost no common to all clients generators. We can abstract the api, but it will be always have diferences.
The technology generator should inject its own needle.

> I'm personally in favor of the second option, e.g. to get only angular, react, vue and cypress generator extending `AbstractJHipsterClientGenerator`.
> 
> Your thought?

At your current approach using `abstract-client-generator.mjs`,  a generator will require:
- to extend the client generator to have the needles api.
- if we migrate vue and/or react to vite, the `addWebpackConfig` will still be there.

This `source` approach is the simplest approach I can think of.

**Comment by DanielFran** [comment]
> This `source` approach is the simplest approach I can think of.

@Tcharl Should we then keep the current approach and close both PRs?

**Comment by Tcharl** [comment]
@DanielFran Working on it (I unfortunately have a jhipster project to migrate in parrallel, which is why I do not achieve that much progress). I'll close it when I'll totally understand what I should do ;-)

**Pull request closed without merging**
