### PR TITLE
Add a parent class for generator extendable through a blueprint

### PR DESCRIPTION
**Pull request by murdos**
This parent class holds the public API that can be used for developers of blueprint.
See [this discussion](https://github.com/jhipster/generator-jhipster/pull/8623#discussion_r226876596) for the rationale.

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
@murdos thanks, I was thinking of something like this but never got around to refactor. I'll test and merge this

**Comment by murdos** [comment]
I believe I've just found some side-effects locally that I need to investigate, so please don't merge this PR.

**Comment by pascalgrimaud** [comment]
ok @murdos : I added `on-hold` label

**Comment by deepu105** [comment]
Also check the effect of moving the useBlueprint variable from global scope
to class scope. I did that way to avoid blueprints thinking they have to
call themselves

**Comment by murdos** [comment]
Superseded by #8729

**Pull request closed without merging**
