### PR TITLE
Prevent wrong http code on empty body response

### PR DESCRIPTION
**Pull request by sahbi-ktifa**
This is mentionned here https://github.com/jhipster/jhipster-vuejs/issues/180.
To be more consistent with good practices, we should return correct HTTP codes when using DELETE Request and thus use 204 instead of 200.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by sahbi-ktifa** [comment]
Please @cbornet, could you review the reactive part ? I was forced to use ```@ResponseStatus```here to make it work. I may have missed something because I do not understand why the ResponseEntity.noContent() isn't enough...

**Comment by DanielFran** [comment]
@sahbi-ktifa Can you fix the conflits please?

**Comment by sahbi-ktifa** [comment]
Fixed conflicts

**Comment by jdubois** [comment]
You're totally right @sahbi-ktifa - and this is my fault, I think I'm the one who originally coded this

**Pull request merged**
