### PR TITLE
generate gradle enterprise configuration

### PR DESCRIPTION
**Pull request by atomfrede**
This integrates gradle enterprise prompts into the generator and the jdl. 
One open issue I was not able to solve (first time touching the JDL part):

I would like to have a configuration like this:

```
application {
  config {
    buildTool gradle
    enableGradleEnterprise true
    gradleEnterpriseHost "https://ge.jhipster.tech"
  }
}
```

Buit the property for the host can't be parsed/imported  with following error:

```
Syntax error message:
	unexpected character: ->"<- at offset: 222, skipped 1 characters.
Error during import-jdl: Error: unexpected character: ->"<- at offset: 222, skipped 1 characters.
Error: unexpected character: ->"<- at offset: 222, skipped 1 characters.
    at getCst (/home/fred/git/github/jhipster/generator-jhipster/jdl/parsing/api.js:49:11)
    at Object.parse (/home/fred/git/github/jhipster/generator-jhipster/jdl/parsing/api.js:40:15)
    at callApiMethod (/home/fred/git/github/jhipster/generator-jhipster/jdl/readers/jdl-reader.js:98:30)
    at parse (/home/fred/git/github/jhipster/generator-jhipster/jdl/readers/jdl-reader.js:84:25)
    at Object.parseFromFiles (/home/fred/git/github/jhipster/generator-jhipster/jdl/readers/jdl-reader.js:43:10)
    at parseFiles (/home/fred/git/github/jhipster/generator-jhipster/jdl/jdl-importer.js:132:20)
    at createImporterFromFiles (/home/fred/git/github/jhipster/generator-jhipster/jdl/jdl-importer.js:64:19)
    at JDLProcessor.importJDL (/home/fred/git/github/jhipster/generator-jhipster/cli/import-jdl.js:361:18)
    at module.exports (/home/fred/git/github/jhipster/generator-jhipster/cli/import-jdl.js:479:17)
    at /home/fred/git/github/jhipster/generator-jhipster/cli/jdl.js:61:49
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
ERROR! Error during import-jdl: unexpected character: ->"<- at offset: 222, skipped 1 characters.
Error: Error during import-jdl: unexpected character: ->"<- at offset: 222, skipped 1 characters.
    at module.exports (/home/fred/git/github/jhipster/generator-jhipster/cli/import-jdl.js:494:27)
    at /home/fred/git/github/jhipster/generator-jhipster/cli/jdl.js:61:49
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
```

As far as I can tell everything looks fine (basically the same config as for `jwtSecretKey`), but I must have missed something.

Will need to add the experimental usage such that the prompts only show when starting the generator with experimental.

updates #14226

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by atomfrede** [comment]
EDIT: Found a working solution, but not sure its the best one. Now you need to use

```
application {
  config {
    buildTool gradle
    enableGradleEnterprise true
    gradleEnterpriseHost "ge.jhipster.tech"
  }
}
```

**Comment by atomfrede** [comment]
Next step would be to extend the integration test configurations with our gradle enterprise configuration see how to integrate them with github actions (needs a secret, not sure how to handle that with PRs)

**Comment by atomfrede** [comment]
Will try to rebase this, so we can have this in our ci and sample apps eventually.

**Comment by atomfrede** [comment]
@jhipster/developers I think this one is ready to be merged. The gradle enterprise options are "experimental" and the prompt is only shown with `--experimental`. As a first follow up step it would be nice to have gradle enterprise & build scans for our sample apps. @pascalgrimaud How are they generated? Is there a jdl somewhere?

**Comment by pascalgrimaud** [comment]
@atomfrede : which samples are you talking about?

**Comment by atomfrede** [comment]
The sample apps we have for each release (?) where we also have the sonar cloud checks.

**Comment by pascalgrimaud** [comment]
There is no JDL. It uses the existing yo-rc.json file.
You can have a look at this repo: https://github.com/jhipster/jhipster-automated-samples

I launch the script to regenerate each projects

**Comment by atomfrede** [comment]
The failing test seems unrelated, keycloak can't be started. I would like to merge this and afterwards update the gradle sample apps to use our gradle enterprise instance and eventually use it in our ci build configuration if everyone agrees.

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/49922

**Pull request merged**
