### PR TITLE
Consul support for Kubernetes and improvements

### PR DESCRIPTION
**Pull request by PierreBesson**
It took me quite some time to get everything to work 😄 but now it's glorious !
I also did some changes for the jhipster-registry and now we can set the central config easily from a kubernernetes configmap (`application-config.yml` works the same way for the registry and consul)

Now we are almost at parity with docker-compose, it's only missing monitoring and cassandra (very nice example here : https://github.com/kubernetes/kubernetes/tree/master/examples/storage/cassandra).

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@PierreBesson : you need to fix the npm test, there is 1 failing

**Comment by pascalgrimaud** [comment]
I like that -> `🐳` so funny!
I can review this PR, but I need time.

**Comment by pascalgrimaud** [comment]
@PierreBesson : some comments:

- I generated a gateway and microservice
- I created the docker images inside minikube


- I run the registry (consul)
- after forwarding the 8500 port, when I go into http://localhost:8500/ui/#/dc1/kv/, there is no key / value. Is it normal ?

- then, I launch gateway and microservice
- the logs of gateway:
```
2017-01-06T23:15:29.939120516Z ----------------------------------------------------------
2017-01-06T23:15:29.939125124Z 	Application 'jhgate' is running! Access URLs:
2017-01-06T23:15:29.939128643Z 	Local: 		http://localhost:8080
2017-01-06T23:15:29.939132055Z 	External: 	http://172.17.0.12:8080
2017-01-06T23:15:29.939135513Z 	Profile(s): 	[prod, swagger]
2017-01-06T23:15:29.939138862Z ----------------------------------------------------------
2017-01-06T23:15:29.939659208Z 2017-01-06 23:15:29.939  INFO 7 --- [           main] io.github.pascalgrimaud.JhgateApp        : 
2017-01-06T23:15:29.939685011Z ----------------------------------------------------------
2017-01-06T23:15:29.939689796Z 	Config Server: 	Not found or not setup for this application
2017-01-06T23:15:29.939704437Z ----------------------------------------------------------
```

- the gateway runs fine, but as the JWT secret is not shared, it can't communicate with the microservice

**Comment by PierreBesson** [comment]
@pascalgrimmaud, there should be a key-value as it should take the value from the configmap mounted as a volume but maybe the configmap was created after the configloader pod. Try to delete the configloader pod to see if it fixes it.

**Comment by pascalgrimaud** [comment]
you're right @PierreBesson !
Everything works fine for me now.

Thanks for your work, I learn a lot of things when reviewing this PR, really great job !!

minikube

jhgate

**Comment by pascalgrimaud** [comment]
About the documentation here: https://jhipster.github.io/kubernetes/
Do you think we need to document the consul loader pod restart ?

Anyway, the documentation need to be updated for JHipster 4, as Consul is now supported!

**Comment by PierreBesson** [comment]
Yes I have a lot of docs to write ! Also this PR actually took a lot of time to do, as I needed a lot of experimenting and I learned a lot doing this. I'm really exited about kubernetes now and have a lot of ideas...

However, I think I might be able to do something to not need a pod restart. Maybe putting the configmap in the same yaml file as the configloader or do a check for consul in the configloader itself...

**Pull request merged**
