### PR TITLE
Error handling - server and client side and a notification service

### PR DESCRIPTION
**Pull request by gzsombor**
( code merged from https://github.com/deepu105/generator-jhipster/commit/98c0b809ef209751b2c10a65d19902cf28b9a2a3 )

This should cover most of  #1750

### CODE REVIEW

**Comment by Qinwroks** [comment]
:+1:

**Comment by deepu105** [comment]
@gzsombor I guess there are some duplicated logic in the alert service and your errorDisplay directive, i'll simplify it so that alert service is used globally for the toast style notifications, since its a generic service even users can use it for any kind of custom notifications on angular side, we should document that as well

**Comment by jdubois** [comment]
@deepu105 as I've just merged it, could you do another PR with your refactoring?

**Comment by deepu105** [comment]
yes ill add another PR for the directive and service merge


On Mon, Jul 27, 2015 at 6:07 PM, Julien Dubois <notifications@github.com>
wrote:

> @deepu105 <https://github.com/deepu105> as I've just merged it, could you
> do another PR with your refactoring?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/pull/1770#issuecomment-125154233>
> .
>



-- 
thank you,
Deepu.k.s

**Pull request merged**
