### PR TITLE
replica config - mongo and couch db

### PR DESCRIPTION
**Pull request by srinivasa-vasu**
- mongo and couch dbs' deployment object to statefulset
- replica config for mongo and couch dbs'

### CODE REVIEW

**Comment by deepu105** [comment]
@srinivasa-vasu @PierreBesson @pascalgrimaud can we merge this?

**Comment by pascalgrimaud** [comment]
There are some merge conflicts.
So need to rebase.

I'll try to find time to test this, or I will ask to Pierre monday, after his holidays. 
I think I should try to test kubernetes with Travis, it's doable but I just need time...

**Comment by deepu105** [comment]
@pascalgrimaud can we merge this

**Comment by pascalgrimaud** [comment]
Sorry, I'm so busy these last days/weeks.
Let's merge this. I'm trusting @srinivasa-vasu :)

In all cases, we will test manually everything before the v5.

**Pull request merged**
