### PR TITLE
[React] Hooks (logout, activate, settings and metrics components)

### PR DESCRIPTION
**Pull request by qmonmert**
WIP on #9891

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by qmonmert** [comment]
@jdubois & @deepu105 is it possible to relaunch protractor tests if you have time ? thks

**Comment by DanielFran** [comment]
Relaunched failing tests

**Comment by qmonmert** [comment]
@DanielFran thks

**Comment by qmonmert** [comment]
@DanielFran E2E tests seem to be random :/ cc @deepu105 & @chrisdns

**Pull request closed without merging**
