### PR TITLE
Upgrade libraries for ng4 support

### PR DESCRIPTION
**Pull request by sendilkumarn**

### CODE REVIEW

**Comment by deepu105** [comment]
Surprising didnt it break anything?

**Comment by sendilkumarn** [comment]
Nope, except for that test case. I think that was our mistake.

**Comment by jdubois** [comment]
Can you also try upgrading Angular CLI? I created the angular cli configuration on the root of the project, it was kinda working fine

**Comment by sendilkumarn** [comment]
Upgraded Angular cli to use 1.0.0 version already.

**Comment by jdubois** [comment]
Oh, and no issue at all? What's happening ?

**Comment by sendilkumarn** [comment]
Yeah I know that will be surprising. But yeah.

**Comment by jdubois** [comment]
Then I'm merging this -> it will be for our 4.2.0 release, hopefully for Devoxx France !

**Comment by sendilkumarn** [comment]
For my voxxeddays <3

**Comment by jdubois** [comment]
And now we need that ***** AOT to work ! I hope it will be easier !

**Comment by deepu105** [comment]
Hope you didnt encounter this https://github.com/jhipster/generator-jhipster/issues/5400

**Comment by jdubois** [comment]
Yes, and I remember there was an issue with Websockets, can you try the option ?

**Comment by deepu105** [comment]
It seems to work fine with websockets :)

**Pull request merged**
