### PR TITLE
ng-jhipster migration to generator-jhipster

### LINKED ISSUE #12868: Navigating back-forward in paginated entity sort icon doesn't change in Angular
##### **Overview of the issue**

If clicking sorting icons in paginated entity list component or in user list component and then navigating back or forward then sorting icons doesn't reflect correctly sorting status.

##### **Motivation for or Use Case**

Sorting icons in table header should correctly reflect what is current sorting status.

##### **Reproduce the error**

* Navigate to Administration -> User management
* Click on e-mail column header
* Click on ID column header
* Use browser back button

Sorting icons should reflect that table is sorted by e-mail ascending but in fact UI shows like table is sorted by ID field.

This scenario applies also to paginated entities.

##### **Related issues**

This bug is side effect from #11518

##### **Suggest a Fix**

This problem is caused by fact that `jhiSortBy` directive in `ng-jhipster` library is designed to change icon only on click events.

Solution is to redesign `jhiSortBy` directive in `ng-jhipster` library to change icon if sorting variable has changed.

##### **JHipster Version(s)**

```
jhipster-7@0.0.1-SNAPSHOT c:\projects\teest\jhipster7
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster7",
    "jhipsterVersion": "6.10.4",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": ["protractor"],
    "pages": [],
    "creationTimestamp": 1603213069799,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "gradle",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "et",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": ["et", "en", "ru"],
    "lastLiquibaseTimestamp": 1603730945000,
    "entities": [
      "BankAccount",
      "TheLabel",
      "Operation",
      "Department",
      "JobHistory",
      "Job",
      "Employee",
      "Location",
      "Task",
      "GoldenBadge",
      "SilverBadge",
      "Identifier",
      "Country",
      "Region",
      "MyDuration"
    ],
    "embeddableLaunchScript": false
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount {
  name String required
  bankNumber Integer
  agencyNumber Long
  lastOperationDuration Float
  meanOperationDuration Double
  balance BigDecimal required
  openingDay LocalDate
  lastOperationDate Instant
  active Boolean
  accountType BankAccountType
  attachment AnyBlob
  description TextBlob
}
entity TheLabel {
  labelName String required minlength(3)
}
entity Operation {
  date Instant required
  description String
  amount BigDecimal required
}
entity Department {
  name String required
  description TextBlob
  advertisement AnyBlob
  logo ImageBlob
}
/**
 * JobHistory comment.
 */
entity JobHistory {
  startDate ZonedDateTime
  endDate ZonedDateTime
  language Language
}
entity Job {
  title String minlength(5) maxlength(25)
  type JobType
  minSalary Long
  maxSalary Long
}
/**
 * The Employee entity.\nSecond line in javadoc.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String
  lastName String
  email String
  phoneNumber String
  hireDate ZonedDateTime
  salary Long
  commissionPct Long
}
entity Location {
  streetAddress String
  postalCode String
  city String
  stateProvince String
}
entity Task {
  title String
  description String
}
entity GoldenBadge {
  name String
}
entity SilverBadge {
  name String
}
entity Identifier {
  name String required unique
}
entity Country {
  name String
}
entity Region {
  name String
}
entity MyDuration {
  durationField Duration
  myBlobField AnyBlob
  myImageBlob ImageBlob
  myTextBlob TextBlob
}
enum BankAccountType {
  CHECKING,
  SAVINGS,
  LOAN
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}
enum JobType {
  BOSS,
  SLAVE
}

relationship OneToOne {
  Department{location} to Location
  Employee{user(login)} to User with jpaDerivedIdentifier
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
  Employee{job} to Job{emp(lastName)}
  /**
   * A relationship
   */
  Department{employee} to
  /**
   * Another side of the same relationship,
   */
  Employee{department}
  Location{country} to Country{location}
  Country{area} to Region{country}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
  Employee{manager(lastName)} to Employee
  Employee{sibag(name) required} to SilverBadge
  Employee{gobag(name) required} to GoldenBadge
  GoldenBadge{iden(name) required} to Identifier
  SilverBadge{iden(name) required} to Identifier
}
relationship ManyToMany {
  Operation{theLabel(labelName)} to TheLabel{operation}
  JobHistory{department} to Department{history}
  JobHistory{job} to Job{history}
  JobHistory{emp(firstName)} to Employee{history}
  Job{chore(title)} to Task{linkedJob(title)}
}

dto BankAccount, Department, Employee, Location, GoldenBadge, SilverBadge, Identifier, Country, Region with mapstruct
service BankAccount, Location, Country with serviceImpl
service TheLabel, Department, Employee, GoldenBadge, SilverBadge, Identifier, Region with serviceClass
angularSuffix BankAccount with mySuffix
filter BankAccount, Employee
clientRootFolder BankAccount, TheLabel, Operation with test-root
paginate TheLabel, Job with pagination
paginate Operation, JobHistory, Employee with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

git version 2.29.1.windows.1

node: v12.18.4

npm: 6.11.3

yeoman: 3.1.1

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #12909: ng-jhipster
This is follow up to https://groups.google.com/g/jhipster-dev/c/zrigrN1Ji_o where I proposed to move away from ng-jhipster.

I looked at `ng-jhipster` to see what code is used or unused in `generator-jhipster`.

### Unused ###

* **directives**: max.directive, maxbytes.directive, min.directive, minbytes.directive, number-of-bytes
* **pipes**: capitalize.pipe, truncate-characters.pipe, truncate-words.pipe
* **services**: base64.service, date-util.service, pagination-util.service, resolve-paging-params.service

### Used ###

All is used under **components**:
* metrics - metrics.component
* jhi-boolean.component - user-management-detail.component
* jhi-item-count.component - user-management.component, entity-management.component

Used in **directives**:
* sort-by.directive, sort.directive - configuration.component, logs.component, user-management.component, entity-management.component

All is used under **language**:
* JhiMissingTranslationHandler, jhiTranslate, JhiLanguageService - everywhere

Used **pipes**:
* ~~filter.pipe, pure-filter.pipe, order-by.pipe - logs.component~~ - unused after #12924
* ~~keys.pipe - configuration.component, gateway.component, health.component, health-modal.component~~ - unused after #12913

Used **services**:
* alert.service (JhiAlertService) - notification.interceptor, alert-error.component, alert.component
* data-util.service (JhiDataUtils) - entity-management.component, entity-management-update.component, entity-management-detail.component
* event-manager.service (JhiEventManager), event-with-content.model - many places
* parse-links.service (JhiParseLinks) - entity-management.component (if using infinite scroll)

All root files are used: JhiConfigService, JhiModuleConfig, NgJhipsterModule

### Dependencies in ng-jhipster ###

* @angular - everywhere
* @ngx-translate - language, alert.service, metrics (jhiTranslate), jhi-item-count.component (jhiTranslate)
* @fortawesome - sort-by.directive, sort.directive
* @ng-bootstrap - metrics
* rxjs - jhiTranslate, JhiDataUtils, JhiEventManager

---

Changing functionality in ng-jhipster is three step action:
* make changes in ng-jhipster
* someone from team leads should release a new version
* new version should be used in generator-jhipster

And basically 2 time testing: while making changes in ng-jhipster and after using new version in generator-jhipster.

The same change in generator-jhipster is one step:
* just change it and test once

---

Starting from Angular 9, Quick Development guide in https://github.com/jhipster/ng-jhipster#quick-development is no more working. So if we stay on ng-jhipster then this guide and/or ng-jhipster configuration needs to be changed.  
And if we stay on ng-jhipster then I would like to remove code that is no more used by generator-jhipster.

If we will move away from ng-jhipster then we can do this step by step, for example if some issue is related to ng-jhipster then as part of fixing, code is moved to generator-jhipster and removed from ng-jhipster.  
Currently 2 ng-jhipster related issues opened: #12868 and #12778

WDYT about that?

### PR DESCRIPTION
**Pull request by kaidohallik**
This PR removes `ng-jhipster` dependency from `generator-jhipster`.

Closes #12909

This PR contains commits from https://github.com/jhipster/ng-jhipster extracted by method described in https://github.com/jhipster/generator-jhipster/issues/12909#issuecomment-723351651

Probably not all `ng-jhipster` committers from period 2016-2020 are signed CLA, so probably needs to be merged without passing CLA check.

As we have strict TypeScript option and TypeScript ESLint "`plugin:@typescript-eslint/recommended-requiring-type-checking`" then I was forced to do quite a lot changes to get migrated functionality to work in `generator-jhipster`.

Some comments about changes by commits.

#### sort ####
In the process of migration fixed #12868

#### metrics ####
* split code to `.ts` and `.html` as Angular style guide suggests
* declared also model, so fixed one "`@typescript-eslint/no-explicit-any`" as referenced also in https://github.com/jhipster/generator-jhipster/pull/10873#discussion_r356840172
* used `ChangeDetectionStrategy.OnPush` where functions was used in html - performance improved a bit
* improved filter section in threads modal window - instead of showing filter in text input, badges are now directly reflecting current filtering state
* temporarily added `-new` to component selectors to avoid conflicts with `ng-jhipster`, those are removed by the `ng-jhipster` removal commit

#### event-manager ####
In jhipster/ng-jhipster#115 I made preparation to simplify output to event manager consumers - return only `event.content` because event name is redundant, subscription is by name. But now we have #12778 - multiple subscriptions, it's a good idea and in this case returning full info, including event name, is must have. So I deleted this simplification preparation and we should go #12778 way.

#### jhi-boolean ####
As this is used only in one place, user management detail view (and if skipping user management, for example oauth2, then there is 0 usages), and if this component is not widely used and it's API learned then code without this component is better understandable, so I didn't migrate this component but instead using simple html in user management detail view (lines used in `.ejs` template reduced from 10 to 2).

#### jhi-item-count ####
Temporarily added `-new` to component selector to avoid conflicts with `ng-jhipster`, this is removed by the `ng-jhipster` removal commit.

As in current implementation:
* HTML was hacked and very ugly to put somehow i18n disabled and enabled to work together in one component
* perfomance was bad, every event in page caused recalculation of `jhi-item-count` (for example every click resulted with 6 time recalculation)
* calculation was implemented twice, one for i18n enabled and other for i18n disabled
* if i18n disabled then calculation was not unit tested

Then rewrote component, now:
* HTML is now very minimalistic 1-liner (achieved by using `enableTranslation` variable available in generator)
* `item-count` component is recalculated only if input changes (different page is selected)
* common calculation for both i18n disabled and enabled
* as there is common solution for i18n disabled and enabled then both are now also unit tested

#### data-util ####
* removed unused functionality and tests for unused functionality (a lot was removed)
* `openFile` function has 2 forks, comment was that the first one is for IE and Edge, but for Edge that was not true, so changed comment from "`To support IE and Edge`" to "`To support IE`"

#### parse-links ####
Polished and made shorter

#### alert.service ####
Now when we have full control over this component (we can use powerful `if (enableTranslation) { ... }`) we should refactor this service to offer better API to avoid hacky workarounds as described in closing #12796. But this enhancement is out of scope of this PR.

#### translate ####
* in this commit removed also `ng-jhipster` dependency
* now we don't need to force `@ngx-translate` dependency for i18n disabled any more
* after removing `ng-jhipster` dependency, `core.module` is quite small and after merging this PR I want to move code from `core.module` to `app.module` and delete `core.module` to reduce code hierarchy level

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
really good job @kaidohallik !
I'm trusting you here, and unless someone wants to review it, I'll probably merge it really soon

**Comment by mshima** [comment]
I have tested yesterday, and everything looks fine, I forgot to test sorting.
I thing I've noticed it that the UI does not change to the account language once logged in, but I don't know if it's a regression.

Bundle at our ngx-default changed from:
```
chunk {2} main.2c37efdf00f81a130127.css, main.9268b221dd8c8f2aad31.js (main) 853 kB [initial] [rendered]
64
```
to
```
chunk {2} main.2c37efdf00f81a130127.css, main.83dd4bcfd4386bf44784.js (main) 801 kB [initial] [rendered]
63
```

IMO let's merge, and finish testing it in main branch.

**Comment by kaidohallik** [comment]
> One thing I've noticed it that the UI does not change to the account language once logged in, but I don't know if it's a regression.

I tested this and this was working for me. You probably changed language before logging in? Logic in application is: if user has changed language then in this session don't change language on login any more.

**Review by mshima — APPROVED** [review]

**Comment by kaidohallik** [comment]
Thanks @mshima for merging!

**Comment by kaidohallik** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/28314

**Comment by pascalgrimaud** [comment]
@kaidohallik : approved

**Pull request merged**
