### PR TITLE
Travis: reduce the size of entity name

### PR DESCRIPTION
**Pull request by pascalgrimaud**
See https://travis-ci.org/hipster-labs/jhipster-travis-build/jobs/366440181
It should fix this error:
```
Reason: liquibase.exception.DatabaseException: Identifier name 'test_many_rel_with_pagination_a_test_many_rel_with_pagination__id' is too long [Failed SQL: ALTER TABLE travisNg2.test_many_rel_with_pagination_anddto_test_mapstruct ADD CONSTRAINT test_many_rel_with_pagination_a_test_many_rel_with_pagination__id FOREIGN KEY (test_many_rel_with_pagination_anddtos_id) REFERENCES travisNg2.test_many_many_pagination_dto (id)]
```

I didn't follow closely the recent commits, so I don't know what happened

_____

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green -> https://travis-ci.org/pascalgrimaud/generator-jhipster/builds/366600878
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
I don't understand why: there was a check on table/identifier names length only for Oracle, and we added an option to remove it (as with recent Oracle versions you can have long table/identifier names). So that shouldn't have any impact.

**Comment by deepu105** [comment]
We need to find the root cause as this was working, maybe there is a bug introduced

**Comment by pascalgrimaud** [comment]
Yes, I tried to look at the commits, the last 5 days, I didn't find anything

**Comment by gmarziou** [comment]
Did we upgrade Liquibase? 3.6.1 is from Apr 11, 2018.

**Comment by pascalgrimaud** [comment]
@gmarziou : the problem comes from https://github.com/jhipster/generator-jhipster/pull/7323#discussion_r181574183
No computer until tonight, so I can't fix it right now

**Comment by pascalgrimaud** [comment]
Some analyze.

At first, I thought it comes from this change https://github.com/jhipster/generator-jhipster/pull/7323#discussion_r181574183

In fact, it comes from the tests added by @ruddell in this commit https://github.com/jhipster/generator-jhipster/commit/fe61d180686fea88b960ce8455cc481bc74e7ca8
The `TestManyRelWithPaginationAndDTO` is too long: 31 -> https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/prompts.js#L271

So this fix reduced the size of this entity.
Nothing to do more, and no regression in the other PR I think

**Pull request merged**
