### PR TITLE
Add datastax opscenter to dockerized cassandra

### PR DESCRIPTION
**Pull request by cbornet**
* Datastax Opscenter (community edition) is spawned by docker-compose and accessible at ```http://localhost:8888```
* The datastax-agent is installed and started on each node. The agent automatically connects to the opscenter container to send its metrics.

### CODE REVIEW

**Comment by cbornet** [comment]
Well, docker doesn't allow upper letter image name...
So it seems we can't use the baseName here. We can't use the "container-name" property either because we would lose the "scale" capability.
Any idea someone ? @jdubois @pascalgrimaud ?

**Comment by cbornet** [comment]
OK : <%=baseName.toLowerCase()%>. Will update the PR soon.

**Comment by pascalgrimaud** [comment]
Adding Datastax Opscenter is a good idea.
I'll try to have a look this weekend (if I have time)

**Comment by cbornet** [comment]
Green at last :smile:

**Comment by pascalgrimaud** [comment]
nice :+1:

**Pull request merged**
