### PR TITLE
ng2: (admin) migrate tracker

### PR DESCRIPTION
**Pull request by deepu105**
@wmarques @sendilkumarn I'm unable to get this working. there is no error on console and I spend far too much time trying to find whats wrong. may be it needs a fresh pair of eyes. SO if you have time try it out see if you are able to get it working

@christopherthielen I didnt know what to do with the onEnter and onExit of the state, should it be in transitions as well?

### CODE REVIEW

**Comment by sendilkumarn** [comment]
@deepu105 the problem is due to `private $json: JSON`

**Comment by deepu105** [comment]
Oh is it. Damn

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Btw how did you trace it? There wasnt any error rite?

Thanks & regards,
Deepu

**Comment by sendilkumarn** [comment]
There wasn't any error of course. I was backtracking.

**Comment by deepu105** [comment]
migration is done, but there seems to be some issue in connecting to socket. Im gonna merge this anyway and work on it in a new PR

**Pull request merged**
