### PR TITLE
Update prettier to version 2.0.5 and reformat code

### PR DESCRIPTION
**Pull request by murdos**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mshima** [comment]
I don’t think we should merge this.
This probably will break every single PR due to the array trailing coma.

**Comment by murdos** [comment]
@jhipster/developers : what should we do in your opinion?

A: update to prettier 2.0 but set `trailingComma` to `none` (the default value before prettier 2.0) and maybe switch back `trailingComma` to default prettier value for v7

B: wait for v7 to switch to prettier 2.0

**Comment by vishal423** [comment]
I prefer trailing comma as that provides cleaner diffs and readability.

**Comment by pascalgrimaud** [comment]
Thanks a lot for this PR @murdos 
Just my opinion, I'm in favor of merging this.

The more we try to improve our code, the more we are stuck because of possible breaking change.
It's pretty easy to update the existing code.

Concerning me, I already did my own personal fork of generator-jhipster for my customer with some items which will be in v7 and everything works well. I'll include this PR in my fork, so again, thanks for your work @murdos !

**Comment by deepu105** [comment]
I think we can merge this. I was also doing the exact same in my React branch along with some other upgrades. I'll do a separate PR with other upgrades then

**Pull request merged**
