### PR TITLE
Add Support for [skip ci] and [ci skip] for GitHub Actions

### LINKED ISSUE #10923: Add [skip ci] and [ci skip] for GitHub CI
##### **Overview of the issue**

An idea I got after reading the following conversation by @pascalgrimaud and @deepu105; https://github.com/jhipster/generator-jhipster/pull/10920#issuecomment-565118390

Currently it seems that when a commit is made, keywords such as [skip ci] and [ci skip] is not honored by the Github CI builds. Now the Azure builds [do follow them](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits). 

So we need to add a custom command for GitHub builds to skip when encountering [skip ci] and [ci skip]

##### **Motivation for or Use Case**

Stop unnecessary builds being triggered. 

##### **Reproduce the error**

Create a test branch in your fork and do a commit with [skip ci] or [ci skip].

##### **Related issues**

https://github.com/jhipster/generator-jhipster/pull/10920

##### **Suggest a Fix**

Please see associated PR. 

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by SudharakaP**
Fixes #10923

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
very nice @SudharakaP ! 
can you add the same to the generated github ci file plz ? the one inside cicd subgen

**Comment by SudharakaP** [comment]
@pascalgrimaud : Done :smile:

**Comment by pascalgrimaud** [comment]
thanks a lot

**Comment by SudharakaP** [comment]
@pascalgrimaud : You are welcome. I was wondering, shall we add this to our README file as well to let people know that when then do a documentation change for example they could skip the ci? :thinking:

**Comment by pascalgrimaud** [comment]
Oh yes, you're right. There was something similar in the contributing part, but I deleted it as I didn't find the same for GitHub Actions. We need to add it back

**Comment by pascalgrimaud** [comment]
just answered to a ghost comment lol...

**Comment by SudharakaP** [comment]
@pascalgrimaud : Sorry about that; it was my mistake. I just deleted that comment as soon as I made it and added it on the issue instead as it seemed appropriate to do the discussion there. :smile: Anyways, I'll go ahead and add it to the docs.

**Comment by SudharakaP** [comment]
@pascalgrimaud : I've added it to the documentation, at the place you mentioned (in the PULL_REQUEST_TEMPLATE.md file) as well as in the CONTRIBUTING.md file (under the Commit Message Format section).

**Pull request merged**
