### PR TITLE
Use unique operation names per resource

### PR DESCRIPTION
**Pull request by cbornet**
Since Swagger imposes that the operationId is unique in the spec, springfox will enumerate the methods that have the same names. For instance if you have Foo, Bar and Baz entities, you will have "createUsingPOST", "createUsingPOST_1", "createUsingPOST_2" operation names for the POST operation which is not very nice especially when you generate client code with swagger-codegen.
This PR changes the methods names to createFoo, createBar and createBaz.

### CODE REVIEW

**Comment by jdubois** [comment]
Looks like a good idea to me! Anybody has a feedback on this change?

**Comment by gmarziou** [comment]
Great idea, maybe it could be achieved through annotations but I think method name is even better

**Comment by cbornet** [comment]
@gmarziou WIth swagger annotations, we could have "createFoo" operationId instead of "createFooUsingPOST" which is even better I think. We could also add descriptions such as "Create a foo". I could do another PR for this.

**Comment by jdubois** [comment]
Yes but I'd rather not have too many annotations.... This PR is good enough for me!!

**Comment by cbornet** [comment]
@jdubois OK. I understand and share your point of view

**Pull request merged**
