### PR TITLE
Add possibility to also authenticate by Basic auth on JWT monoliths

### PR DESCRIPTION
**Pull request by cbornet**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
@PierreBesson We could now protect the prometheus endpoint at least for monoliths with JWT :smiley:

**Comment by PierreBesson** [comment]
Let me try it out... The problem is that it creates a "basic auth backdoor" to your app.

**Comment by cbornet** [comment]
Not really a backdoor, just a little less secure than JWT since you transmit the no-expiry password on each request. You just have to know what you're doing when using it...

**Comment by pascalgrimaud** [comment]
@PierreBesson : are you ok with this change ? Can we merge this ?

**Comment by PierreBesson** [comment]
No, Currently the password should be admin/admin with no explicit property file to change. I think the property must be `spring.security.user.name/password` but we need to test. Also initially, I wanted to have this only on /management/** endpoints... This needs a lot of docs as it is a pretty big change ! Also it potentially has a performance impact has it will add an additional servlet filter for all requests.

**Comment by cbornet** [comment]
This has no link with the property file. The login/pwd are those of the user DB.

**Comment by PierreBesson** [comment]
Interesting ! What about my remark on the additional servlet filter this might introduce ?

**Comment by cbornet** [comment]
That should be tested I guess. The worse would be an extra query to the DB...

**Comment by cbornet** [comment]
So if you don't use basic auth the filter will only do:
```java
String header = request.getHeader("Authorization");

		if (header == null || !header.toLowerCase().startsWith("basic ")) {
			chain.doFilter(request, response);
			return;
		}
```
I guess the impact should be minimal.

**Comment by cbornet** [comment]
Ok to merge ?

**Comment by pascalgrimaud** [comment]
@cbornet : ok for me, let's merge this.

**Pull request merged**
