### PR TITLE
update to eureka client register and service url env variables

### PR DESCRIPTION
**Pull request by srinivasa-vasu**
update to eureka client register and service url env variables to reflect the right env variables

change serviceurl to service_url (EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE)
change EUREKA_REGISTER_WITH_EUREKA to EUREKA_CLIENT_REGISTER_WITH_EUREKA

### CODE REVIEW

**Comment by PierreBesson** [comment]
@xetys, this might be the fix for the registry issue you noticed.

**Comment by deepu105** [comment]
@srinivasa-vasu thanks. Interested in adding openshift support? we had it a while ago but the removed it when RH changed the API and we didn't have anyone to maintain it. Btw the heroku and Kubernetes support are official so if you do the openshift part it can be considered official as well I guess :smiley_cat:

**Comment by deepu105** [comment]
Here is the old version which had the support https://github.com/jhipster/generator-jhipster/tree/v1.x_maintenance/openshift

**Comment by deepu105** [comment]
@jdubois @PierreBesson for some context about above message, Srini is a good friend of mine and works for Red Hat

**Pull request merged**
