### PR TITLE
Upgrade Consul version to 1.4.0

### PR DESCRIPTION
**Pull request by DanielFran**
See also https://github.com/jhipster/consul-config-loader/pull/15

https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#140-november-14-2018

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@PierreBesson we might need a new version of https://github.com/jhipster/consul-config-loader?
We might have missed the creation of a new one when migrated to consult v.1.3.0 ...

**Comment by DanielFran** [comment]
Just waiting for this PR https://github.com/docker-library/official-images/pull/5071 to be submited so the docker image will be available

**Comment by PierreBesson** [comment]
@danielfran don't worry the consul-loader is just a simple script and will work fine even if not on the latest consul version. And actually the consul API is very stable not changing between version so I'm not worried at all. I will give you admin right to the consul-loader repo so you can do releases yourself (very easy to do just create a new git tag with the Github ui).

**Comment by jdubois** [comment]
Thanks @DanielFran !

**Pull request merged**
