### PR TITLE
Bootswatch update theme

### PR DESCRIPTION
**Pull request by pascalgrimaud**
It will allow to use the new themes :-D
- https://bootswatch.com/quartz/
- https://bootswatch.com/vapor/
- etc

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
Thanks for adding the area+theme, @atomfrede !

**Comment by mshima** [comment]
I am wondering if bootswatch 5 is compatible with bootstrap 4.

**Comment by pascalgrimaud** [comment]
Indeed @mshima 
As I saw we already have it: https://github.com/jhipster/generator-jhipster/blob/main/generators/client/templates/vue/package.json#L9

And manually tests work fine

**Comment by DanielFran** [comment]
Closing/reopening since CI failed...

**Comment by istibekesi** [comment]
@pascalgrimaud @DanielFran 
It seems `"bootswatch": "5.1.3"` is present in react/vue templates, but missing in angular. 
So in case of angular, it fails to build with Quartz theme, since that new theme is not included in bootswatch 4.6.1 at all.

**Pull request merged**
