### PR TITLE
Snyk support

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/12441

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
GitLab CI result:

snyk-gitlab-ci

**Comment by pascalgrimaud** [comment]
Azure Pipelines result:

snyk-azure-pipelines

**Comment by pascalgrimaud** [comment]
GitHub Actions result:

snyk-github-actions

**Comment by pascalgrimaud** [comment]
CircleCI result:

snyk-circle-ci

**Comment by pascalgrimaud** [comment]
Travis CI result:

snyk-travis-ci

**Comment by pascalgrimaud** [comment]
Don't blame me if I didn't test Jenkins, as I don't use Jenkins any more and too lazy for installing, configuring and testing it
But the support with Jenkins is in this PR ! I'm feeling confident as I was helped by the post blog

**Review by DanielFran — APPROVED** [review]
@pascalgrimaud Trusting you on this 😀

**Comment by pascalgrimaud** [comment]
Thanks @DanielFran : that's why I added screenshots to show my tests, as it's very long to test all CI
But by doing this, I was able to test all @mshima's work with e2e tests in our CI-CD sub gen, and everything works well !

**Comment by mshima** [comment]
Great work @pascalgrimaud

**Comment by pascalgrimaud** [comment]
same to you, @mshima !

**Pull request merged**
