### PR TITLE
add finnish language support

### PR DESCRIPTION
**Pull request by JukkaPeltoaho**
Finnish language support added.

-   [X] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by JukkaPeltoaho** [comment]
I would like to propose a PR for adding Finnish i18n. Some admin related terms are left in english just for usability reasons.

**Comment by JukkaPeltoaho** [comment]
-   [X] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

**Comment by PierreBesson** [comment]
Thank you @JukkaPeltoaho and congratulations on your first contribution !

**Comment by JukkaPeltoaho** [comment]
Thanks @PierreBesson , jhipster is just awesome!

**Pull request merged**
