### PR TITLE
Correct gitlab CI jest report path

### PR DESCRIPTION
**Pull request by vwiencek**
-   Please make sure the below checklist is followed for Pull Requests.

-   [X] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Will check over the weekend most likely. Gitlab requires a valid junit report file as far as I remember. Is the jest file not in the correct format anymore? (we use the `-sonar` file for sonar analyses).

**Comment by vwiencek** [comment]
The file generated is not at the expected location .... don’t really know if it should be there or not ...

**Comment by atomfrede** [comment]
I will generate a sample project on gitlab.com so we can check our configuration better.

**Comment by atomfrede** [comment]
@vwiencek Sorry for coming back so late. But I think it is now correct again. Latest master generates `TESTS-results-jest` in `build/test-results` again, I guess due to https://github.com/jhipster/generator-jhipster/pull/10473/files so I would say this PR is not necessary anymore.

**Pull request closed without merging**
