### PR TITLE
Detect generated source changes.

### PR DESCRIPTION
**Pull request by mshima**
- Compare generated source.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@pascalgrimaud I have been using the diff approach to make sure the refactoring didn't break anything.
It could be applied to reduce overall CI time without loosing test quality.
What do you think?

**Comment by mshima** [comment]
@pascalgrimaud what do you think about this one?

**Comment by pascalgrimaud** [comment]
@mshima : thanks, I'll have a look. Need time to understand exactly what you're doing here :D

**Comment by mshima** [comment]
@pascalgrimaud I've reworked the workflow, it's cleaner now.
I removed the condition to ignore the tests, we can enable later.

**Comment by pascalgrimaud** [comment]
I'm sorry but I tried but I don't understand exactly what you tried to do here @mshima
Can you explain to me plz ?

**Comment by mshima** [comment]
> I'm sorry but I tried but I don't understand exactly what you tried to do here @mshima
> Can you explain to me plz ?

It generates 2 versions of the same application:
- Base commit (normally current master)
- Merge commit (PR merge commit)

Then it compares both and prints a diff.
This is really useful for reviewing the PR.
I removed the condition that skips the test, we can add it afterward, when our parallel builds reduces from 60 to 20 again 😆 .

**Comment by mshima** [comment]
I bumped a dependency to exemplify.

Vue generated app didn't changed, so tests from base commit (master) still applies and can be skipped:
Captura de Tela 2020-08-27 às 19 35 38

Angular generated app changed, so tests from base commit (master) does not applies and tests must run:
Captura de Tela 2020-08-27 às 19 36 40

**Comment by mshima** [comment]
@pascalgrimaud can this PR be merged?

**Comment by pascalgrimaud** [comment]
I'm a little bit to buzy these last weeks, so I'm totally trust you.
So yes, you can go !

**Comment by DanielFran** [comment]
@mshima the changes on the scripts can impact also jhipster/jhipster pipeline. Can you please validate if this project needs changes?

**Comment by mshima** [comment]
> @mshima the changes on the scripts can impact also jhipster/jhipster pipeline. Can you please validate if this project needs changes?

The changes to the scripts are minor. It won't impact.

**Pull request merged**
