### PR TITLE
Correct jhiHasAuthority Directive and make use of it

### PR DESCRIPTION
**Pull request by pvlastaridis**

### CODE REVIEW

**Comment by jdubois** [comment]
Really happy to see such contribution on our unreleased Angular 2 code!

**Comment by pvlastaridis** [comment]
I am not sure the cousin of this directive jhiHasAnyAuthority and if it is of any of use.

**Comment by deepu105** [comment]
@pvlastaridis could you do the same for `jhiHasAnyAuthority`?

**Comment by pvlastaridis** [comment]
@deepu105 `jhiHasAnyAuthority` is working fine but it's just not being used anywhere.

I believe we should leave it as it is, since it's a useful directive.

**Pull request merged**
