### PR TITLE
feat(app): add addNpmScript function

### LINKED ISSUE #4801: [FEATURE] Add addNpmScript function
Like for this feature (https://github.com/jhipster/generator-jhipster/issues/4798), i know need a addNpmScript for adding a npm script for the Angular 2 jhipster project.

I propose this PR : [#4802](https://github.com/jhipster/generator-jhipster/pull/4802)

### PR DESCRIPTION
**Pull request by vogloblinsky**
Add addNpmScript for adding a custom npm scripts task for angular 2+ application

fix #4801

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks for your contributions, @vogloblinsky 
Can you add in your comment this text: `fix #4801`

So, once the PR is accepted and merged, the issue is closed automatically.

**Comment by vogloblinsky** [comment]
@pascalgrimaud added in my first comment, is that you want ?

**Comment by pascalgrimaud** [comment]
In commit or comment, both should be ok

**Comment by vogloblinsky** [comment]
@pascalgrimaud one test need a restart ;)

**Comment by pascalgrimaud** [comment]
@xetys : FYI, as you are a core team member, you should have rights on Travis build for restarting the job which failed, instead of relaunching all jobs by closing/reopening the PR.

See: https://travis-ci.org/jhipster/generator-jhipster/jobs/188302477
Do you have the **Restart job** button ?

**Comment by xetys** [comment]
aaah, thanks @pascalgrimaud. I will notice that for the next time

**Pull request merged**
