### PR TITLE
 Fix #9608 JHipster family member png image widths

### LINKED ISSUE #9608: Resource size is not correct - typo in the Manifest
##### **Overview of the issue**
The Console shows the following error when using chrome inspect:

> Error while trying to use the following icon from the Manifest: http://localhost:9000/content/images/jhipster_family_member_3_head-192.png (Resource size is not correct - typo in the Manifest?)

##### **Motivation for or Use Case**
This was previously reported and fixed in #7790 by @mraible , but this was prior to the introduction of the new images for the JHipster family members.

##### **Reproduce the error**

1. Generate a monolith
2. Run the app
3. Open the webpage with chrome
4. Right click, inspect the page
5. look at the console logs

##### **Related issues**

#7790
Also [228](https://github.com/jhipster/jhipster-vuejs/issues/228) logged under jhipster-vuejs by @pascalgrimaud 

##### **Suggest a Fix**

Change the images width to have square sizes which match the dimensions declared in 
src/main/webapp/manifest.webapp.ejs

The heights are correct for the images.

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

jhipster@0.0.0 E:\projects\jhipster\a1-basic-mono
`-- generator-jhipster@5.8.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.mycompany.myapp",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.2",
        "applicationType": "monolith",
        "baseName": "jhipster",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en", "fr"]
    }
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

git version 2.6.3.windows.1

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.0

yarn: 1.7.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- Windows 10 Pro, 64 bit
- Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- Edge does not report the error

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by crowne**
Please note that this PR contains png binary image file changes only.
A lot of this is quite new to me so I haven't manged to strictly follow "all" of the contributing guidelines.
Any feedback would be much appreciated.

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
thanks and congrats for your 1st contribution @crowne

@jdubois : should we update this project too ? https://github.com/jhipster/jhipster-artwork

**Comment by PierreBesson** [comment]
This is what I call being a perfectionist ! Every pixel counts. Great work @crowne !

Screenshot 2019-04-26 at 11 22 04

**Comment by PierreBesson** [comment]
I noticed the images exist twice in the code base for react and angular. Maybe we could open an issue to refactor this.

**Comment by jdubois** [comment]
Wow, I had no idea we had the width wrong, that's an awesome work @crowne !!!!!

And @pascalgrimaud is right, they come from https://github.com/jhipster/jhipster-artwork so the changes should be made there too

**Comment by jdubois** [comment]
Oh @PierreBesson you are correct -> I'm copying/pasting those files now to be consistent, but indeed this should be refactored

**Pull request merged**
