### PR TITLE
configure principal claim name for oauth2

### PR DESCRIPTION
**Pull request by mshima**
related to https://github.com/jhipster/generator-jhipster/issues/24374

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@mraible I will let you test with you existing application.

**Comment by mraible** [comment]
@mshima I tested this, and it does not fix the issue.

**Comment by mraible** [comment]
I can confirm that this now works with Spring MVC. I did not test it with Spring WebFlux.

**Review by mraible — APPROVED** [review]
I created a new project with WebFlux and searched for `authentication.name`. Since there are no instances, I think we should merge this.

**Pull request merged**
