### PR TITLE
Remove deprecated Spring Cloud Connectors

### LINKED ISSUE #11685: Replace or remove Spring Cloud Connectors
##### **Overview of the issue**

Spring Cloud Connectors is in maintenance mode: https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services

And the Spring Cloud Connectors starter has been removed from Spring Boot since [version 2.3.0 M1](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3.0-M1-Release-Notes)

##### **Motivation for or Use Case**

Don't rely on outdated libraries.

### PR DESCRIPTION
**Pull request by murdos**
Fixes #11685

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@murdos : if you feel confident, plz merge it, so it can be in JH v7 beta. All daily builds will check more configurations this night

**Comment by pascalgrimaud** [comment]
Thanks @murdos !

**Comment by murdos** [comment]
For the record, I manually tested a deployment to heroku of our ngx-default sample, with these changes, and it was working fine.

**Comment by pascalgrimaud** [comment]
good news so. Don't forget your bounty with the comment plz :p

**Comment by murdos** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/98301

**Comment by pascalgrimaud** [comment]
@murdos : approved

**Pull request merged**
