### PR TITLE
Fix Gateway ports syntax for compose

### LINKED ISSUE #14910: Docker Compose sub-generator generates YAML that doesn't work with `docker compose`
##### **Overview of the issue**

The YAML generated by JHipster's Docker Compose sub-generator doesn't work with Docker CLI's new `compose` support.

* https://twitter.com/mraible/status/1390671872992464900
* https://github.com/oktadev/java-microservices-examples/pull/23

##### **Motivation for or Use Case**

It'd be cool if `docker compose` worked with JHipster.

##### **JHipster Version(s)**

7.0.1

### PR DESCRIPTION
**Pull request by swarajsaaj**
Fix port string generation in docker-compose.yml file, supporting
app.yml that may contain hostname as well in port-mapping

Fix #14910

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
Thanks for your contribution, @swarajsaaj! I believe the [version number](https://github.com/jhipster/generator-jhipster/blob/main/generators/docker-compose/templates/docker-compose.yml.ejs#L19) needs to be removed too. That's what @ndeloof did when he fixed my project in https://github.com/oktadev/java-microservices-examples/pull/23. 

If you want to _really_ test things, we should change all instances of `docker-compose` to `docker compose` in `test-integration/scripts`.

**Comment by swarajsaaj** [comment]
> 
> 
> Thanks for your contribution, @swarajsaaj! I believe the [version number](https://github.com/jhipster/generator-jhipster/blob/main/generators/docker-compose/templates/docker-compose.yml.ejs#L19) needs to be removed too. That's what @ndeloof did when he fixed my project in [oktadev/java-microservices-examples#23](https://github.com/oktadev/java-microservices-examples/pull/23).
> 
> If you want to _really_ test things, we should change all instances of `docker-compose` to `docker compose` in `test-integration/scripts`.

Thanks @mraible , 
1. Though the version number is optional now, but we can remove it to be more compliant to latest spec.
2. Yes, it would be great to _really_ test this using integration tests. Will make the change.

**Comment by swarajsaaj** [comment]
The pipelines are failing on adding "docker compose" command in `test-integration/scripts`. The command seems working fine on my machine. Is it possible the new "Compose CLI" support is not installed on azure devops instance?

**Comment by ndeloof** [comment]
Compose CLI is indeed a separate component, that is still beta and won't be installed by default.
Probably simpler to use the classic `docker-compose` until new compose is distributed within the docker CLI system packages

**Comment by swarajsaaj** [comment]
Yes @ndeloof , its still in "Tech Preview" and the pipelines worked only after adding a step to install the component first.
@mraible Shall we defer it from our test scripts and add it later once this feature is stable (and bundled by default) ?

**Comment by mraible** [comment]
@swarajsaaj Probably. I was motivated to add support for it since `docker-compose` tells you to try it.

**Comment by swarajsaaj** [comment]
@mraible Okay then let's keep the stable 'docker-compose' support for now, and migrate tests to new command once it is stable 😄  (BTW the tests showed that `docker compose` too is compatible with generated compose files now). 
Reverted test command change in f6c9238

**Comment by swarajsaaj** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/40709

**Comment by pascalgrimaud** [comment]
@swarajsaaj : approved

**Pull request merged**
