### PR TITLE
Add ids to menu containers on angular

### PR DESCRIPTION
**Pull request by mshima**
This will make easy to customize menus.
Ex: change order.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Would it make sense to have that for react part too to be consistent?

**Comment by mshima** [comment]
> Would it make sense to have that for react part too to be consistent?

I really don't know.

**Comment by MathieuAA** [comment]
What issue does this PR solve? My point is: if we didn't go with IDs at first, there may have been a _good_ reason, no?

**Comment by mshima** [comment]
> What issue does this PR solve? My point is: if we didn't go with IDs at first, there may have been a _good_ reason, no?

It's a feature.

This allows to create a menu at 
https://github.com/jhipster/generator-jhipster/blob/d40cf08ab79c0c4d005550551380ea446a1e4c6e/generators/client/templates/angular/src/main/webapp/app/layouts/navbar/navbar.component.html.ejs#L37

And then customize the order by
```
this.addVendorSCSSStyle(
                    `
#home-menu-container {@extend .order-0;}
#entity-menu-container {@extend .order-1;}
#some-other-menu-container {@extend .order-3;}
#admin-menu-container {@extend .order-10;}
#languages-menu-container {@extend .order-11;}
#account-menu-container {@extend .order-12;}
`,
                    'Apply order to menu'
                );
```

**Comment by MathieuAA** [comment]
@mshima thanks for the clarification :) I'm no expert on this part, @wmarques what's your take on this?

**Comment by wmarques** [comment]
I'm not a big fan of it, for me it's up to the develop once the app is generated to add his proper styles... 
If we start putting IDs for each customisable element it's going to become quite messy IMO.

I would prefer keeping simple bootstrap classes in our HTML.

**Pull request closed without merging**
