### PR TITLE
fix tsconfig-aot.json

### PR DESCRIPTION
**Pull request by deepu105**
Related to #5533

@sendilkumarn can you test this

### CODE REVIEW

**Comment by jdubois** [comment]
So, are you both OK to merge this? I'm going to do full tests this morning, so it's really the right time for me if you want this in our 4.2.0 release

**Comment by sendilkumarn** [comment]
@jdubois can we park this for a while ?

**Comment by sendilkumarn** [comment]
@deepu105 It is not strictly asking you to check that per say.

**Comment by jdubois** [comment]
Yes, no problem, it's just if you want it included in the next release

**Comment by deepu105** [comment]
@sendilkumarn if things are working fine with commonjs lets go with that. we dont need tree shaking at the moment so when we do if it causes issues we can reconsider

**Comment by jdubois** [comment]
Done :-)

**Pull request merged**
