### PR TITLE
Update Spring-boot version to 2.1.0 

### PR DESCRIPTION
**Pull request by VinodAnandan**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
We might have to wait until spring-cloud Greenwich release aimed at mid-december...

**Comment by DanielFran** [comment]
@VinodAnandan there is lot of impacts to migrate to spring-boot 2.1!
I will push today the changes in a specific branch... since there is lot of changes.

**Comment by VinodAnandan** [comment]
@DanielFran Thank you for your help. I didn't know about the changes, I am new to JHipster.

**Comment by DanielFran** [comment]
@VinodAnandan No problem, I am still learning too... ;)

I created the issue https://github.com/jhipster/generator-jhipster/issues/8683 with some information about the impacts.

If it is ok for you I will close both your PRs, and as soon as I push all changes in the specific branches you might strat contribute if you want...
It is ok for you?

**Comment by VinodAnandan** [comment]
Thanks @DanielFran, that's fine

**Comment by DanielFran** [comment]
Closed in favor of https://github.com/jhipster/generator-jhipster/issues/8683

**Pull request closed without merging**
