### PR TITLE
add missing health translations

### LINKED ISSUE #7938: No translations for health checks
Good day. 
Few missing translations on health checks page.

yo-rc.json:

```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.binakot.app",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.2",
    "applicationType": "monolith",
    "baseName": "app",
    "packageName": "io.binakot.app",
    "packageFolder": "io/binakot/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "d9dc10c6a8f82f93d38f69c22c5734d61a6f5927",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ]
  }
}
```

health.json:

```json
{
    "health": {
        "title": "Health Checks",
        "refresh.button": "Refresh",
        "stacktrace": "Stacktrace",
        "details": {
            "details": "Details",
            "properties": "Properties",
            "name": "Name",
            "value": "Value",
            "error": "Error"
        },
        "indicator": {
            "diskSpace": "Disk space",
            "mail": "Email",
            "db": "Database"
        },
        "table": {
            "service": "Service name",
            "status": "Status"
        },
        "status": {
            "UP": "UP",
            "DOWN": "DOWN"
        }
    }
}
```

Screenshot:

### PR DESCRIPTION
**Pull request by ruddell**
Fix #7938

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
@ruddell seems like the e2e tests are failing consistently for a build, maybe this change is causing that. can you take a look, the build was restarted atleast twice

**Comment by ruddell** [comment]
>  1) Administration
       should load metrics:
     NoSuchElementError: No element found using locator: By(css selector, .metrics-page-heading)

It's a flaky protractor test (fails about 50% of the time), I can get it to pass every time by adding `browser.wait(` around [the admin menu click](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/react/src/test/javascript/e2e/modules/administration/administration.spec.ts.ejs#L51).  Should I do that everywhere?

**Comment by deepu105** [comment]
@ruddell ideally the current isDisplayed methods are supposed to wait until the element is there, maybe let's just add the wait for the flaky test alone

**Comment by ruddell** [comment]
There's no call to isDisplayed in that test, adding `waitUntilDisplayed(element(by.className('metrics-page-heading')));` after the navbar click also works

**Comment by deepu105** [comment]
Then lets do that

Thanks & Regards,
Deepu

**Pull request merged**
