### PR TITLE
add properties to use gradle daemon mode

### PR DESCRIPTION
**Pull request by deepu105**
gradle daemon mode can produce better performance in some situation and
hence is an useful addition

Discussion [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jhipster-dev/3edKYmgt-TU)

### CODE REVIEW

**Comment by deepu105** [comment]
@atomfrede @gmarziou plz review and merge

**Comment by atomfrede** [comment]
I'm not happy with activating the daemon by default. This means you can't use it with any ci server by default. What about the parallel mode to get at least partly parallel download? I think that might have more impact on initial build time then the daemon.

**Comment by PeterEltgroth** [comment]
I ran into issues when using daemon when I had started it and then started a jhipster update on my project which included an node upgrade. The daemon seemed to have held onto the previous version of node even though at the command line I had changed it (using nvm on MacOS), which caused the front end portion of the build to fail. 

That said, when running a build during normal development (when the front end tooling isn't being updated) the daemon would speed up the build.  So, I would express some caution with this change, as it cost me several hours to get beyond it and have a hypothesis of the cause.

**Comment by jdubois** [comment]
Looks like the daemon mode causes quite a lot of issues, and isn't very complicated to set up if you want to use it -> I wouldn't put it by default.

If this is a useful option (and I think it is), it could be left commented out

**Comment by deepu105** [comment]
I guess it can be commented out by default :+1:  ill make the change

**Comment by deepu105** [comment]
its commented by default, nothing will be affected by this hence merging

**Pull request merged**
