### PR TITLE
Angular 1.5 migration

### LINKED ISSUE #2808: Upgrade to AngularJS 1.5
See http://angularjs.blogspot.fr/2016/02/angular-150-ennoblement-facilitation.html?m=1

- this should be as part of our 3.0 redesign
- here's some good work for my trainees cc @PierreBesson

### PR DESCRIPTION
**Pull request by wmarques**
Fix #2808 
Changed bower and npm dependencies to update into Angular 1.5. I had to update phantomJS into the latest version to support Angular 1.5 tests.
I also changed two element directives into components, other directives are attribute-restricted or manipulate DOM using link function so I couldn't transform them into components.

### CODE REVIEW

**Comment by mraible** [comment]
I tried to test your branch locally, but ran into issues. I cloned your project, checked out this branch and then ran `npm link`. After doing this, running `yo jhipster` in an empty directory gives me the following:

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'yeoman-generator'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mraible/dev/generator-jhipster-angular-1.5/generators/app/index.js:3:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

The reason I was hoping to try this out was because I recently ran into an issue where I discovered phantomjs is deprecated and phantomjs-prebuilt is its replacement.

https://www.npmjs.com/package/phantomjs

**Comment by wmarques** [comment]
As you suggested I updated the name of the package phantomjs into phantomjs-prebuilt. It caused an unmet dependency with the karma-phantomjs-launcher package so I also updated it into the last version.
I checked logs while running npm install and bower install and now it seems to works fine, I also had no error when creating an app and running "gulp test".
I don't know if it can be source of the errors you got, but I'm running on nodeJS v5.6.0 with npm v3.6.0.

**Comment by gmarziou** [comment]
@wmarques I would recommend you stay with LTS version of Node, the "stable" versions are usually a source of problems.

**Comment by deepu105** [comment]
Whats the progress of this?

**Comment by jdubois** [comment]
Oh, I totally forgot to introduce @wmarques on the dev mailing list, I'll do this now

**Comment by deepu105** [comment]
I checked this branch out and tested on windows.

My environment is as below and this seems to work fine

```
$ node -v && npm -v && yo --version
v5.5.0
3.7.1
1.6.0
```
trace 
```
$ yo doctor

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version

Everything looks all right!

Deepu@DESKTOP-3NUQHBI  /d/Projects/test/testNew
$ gulp test
[08:58:34] Using gulpfile D:\Projects\test\testNew\gulpfile.js
[08:58:34] Starting 'wiredep:test'...
[08:58:34] Starting 'ngconstant:dev'...
[08:58:34] Finished 'ngconstant:dev' after 114 ms
[08:58:34] Finished 'wiredep:test' after 129 ms
[08:58:34] Starting 'test'...
23 02 2016 08:58:36.707:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
23 02 2016 08:58:36.713:INFO [launcher]: Starting browser PhantomJS
23 02 2016 08:58:38.874:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#Wept5VPHYvZtJ2EUAAAA with id 28615290
23 02 2016 08:58:45.134:WARN [web-server]: 404: /bower_components/angular-i18n/angular-locale_en.js
 PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 9 of 44 SUCCESS (0 secs / 0.438 secs)
.
DUMP: 'background-color: rgb(153, 255, 0);'
 PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 13 of 44 SUCCESS (0 secs / 0.546 secs)
23 02 2016 08:58:45.560:WARN [web-server]: 404: /bower_components/angular-i18n/angular-locale_en.js
 PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 26 of 44 SUCCESS (0 secs / 0.928 secs)
 PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 44 of 44 SUCCESS (0 secs / 1.436 secs)
.
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 44 of 44 SUCCESS (3.928 secs / 1.436 secs)
[08:58:52] Finished 'test' after 19 s
```

**Comment by deepu105** [comment]
@wmarques try to rebase against latest master and if it resolves the build failures

**Comment by deepu105** [comment]
OK I know why the few builds are failing. The ones failed are the ones with RUN_APP set to true

The failure is during the final prod build run using the buitt jar. for the prod build there is an npm install task invoked and due to our travis using old node and npm versions the npm install is exiting with a failed state which is causing the total maven/gradle build to fail

few things we can try out as solution:

1. update node to latest LTS -> 4.3.1
2. update npm to latest -> 3.7.3 and set progress bars to false (this will also fix our yo always telling npm is outdated)
3. force the maven/gradle build even if npm install fails (coz sometimes there could be errors here which doesnt actually affect the actual build)

cc @pascalgrimaud @jdubois @wmarques @gmarziou

**Comment by deepu105** [comment]
the build passed when i re triggered it but gulp test failed actually but travis reported the build as pass
```
gulp test
[10:25:08] Warning: gulp version mismatch:
[10:25:08] Global gulp is 3.9.1
[10:25:08] Local gulp is 3.9.0
[10:25:10] Using gulpfile ~/app-default-from-scratch/gulpfile.js
[10:25:10] Starting 'wiredep:test'...
[10:25:10] Starting 'ngconstant:dev'...
[10:25:11] Finished 'ngconstant:dev' after 126 ms
[10:25:11] Finished 'wiredep:test' after 181 ms
[10:25:11] Starting 'test'...
18 02 2016 10:25:11.331:WARN [plugin]: Error during loading "/home/travis/app-default-from-scratch/node_modules/karma-phantomjs-launcher" plugin:
  Cannot find module 'phantomjs-prebuilt'
18 02 2016 10:25:14.461:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
18 02 2016 10:25:14.462:WARN [launcher]: Can not load "PhantomJS", it is not registered!
  Perhaps you are missing some plugin?
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated

```

**Comment by deepu105** [comment]
for the prod builds still failing the reason is as per my comment above

**Comment by pascalgrimaud** [comment]
@wmarques : can you rebase your branch plz ? I fixed some issue with Travis, so it will trigger new builds

@deepu105 :
1) 4.3.1 LTS -> agree
2) about npm 3.7.3 -> I have to check first if jhipster-travis-build repo (used for cache) will work with this new version
3) the `npm install` (launched after yo jhipster) is already in the "script" part of `.travis.yml` -> https://github.com/jhipster/generator-jhipster/blob/master/.travis.yml#L44
That means if it failed, the build should go on.

**Comment by deepu105** [comment]
reg point 3 for production build maven/gradle triggers a npm install udinh
the node plugin and if there is an error during that the build fails, I was
mentioning this

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
Oh I got it, and you're right!

**Comment by wmarques** [comment]
I rebased, tests are now loading

**Comment by pascalgrimaud** [comment]
@wmarques : try to add after these 2 lines https://github.com/jhipster/generator-jhipster/blob/master/travis/scripts/01-generate-project.sh#L9-L10
```
rm -Rf "$HOME"/"$JHIPSTER"/node_modules/*phantom*
```

So you won't use cache from https://github.com/jhipster/jhipster-travis-build

**Comment by pascalgrimaud** [comment]
Another issue is protractor tests :
https://travis-ci.org/jhipster/generator-jhipster/jobs/111182256

Yeah I know, Travis should return a "failed" build for protractor tests, but I didn't manage yet to do it.

**Comment by wmarques** [comment]
It's now passing, thanks @pascalgrimaud !

**Comment by pascalgrimaud** [comment]
protractor tests still failed (but it's green).
You have to look the log here : https://travis-ci.org/jhipster/generator-jhipster/jobs/111202334

**Comment by deepu105** [comment]
@pascalgrimaud can you add `--no-notification` flag on all the travis gulp tasks else there will be an error when it tries to do a notification as well

**Comment by wmarques** [comment]
I changed the protactor config file to load `phantomjs-prebuilt` module. 
It worked fine when i ran `gulp itest` so it should work now.

**Pull request merged**
