### PR TITLE
[webflux] fix compilation errors on tests

### PR DESCRIPTION
**Pull request by atomfrede**
This PR tries to fix the reactive microservice example provided by @mraible  in #12640 

Fixed:

- [x] Fix compilation in tests
- [x] Fix compilation `ProductResource`
- [x] Check why the ITs for patch are failing with 404 (should be fixed, wrong urls)
- [x] Check why gateway hands and does not start up (can't reproduce)

updates #12640

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Close/reopen to trigger webflux tests.

**Comment by atomfrede** [comment]
Trying fix the failing test tonight.

**Comment by atomfrede** [comment]
Regarding the failing webflux tests I found have fixed the compile errors, but now I get SQL query errors for e.g. the `Operation` entity. Maybe @gzsombor has an idea? For example in `OperationRepositoryInternalImpl` 

```java
    static List<Expression> getColumns(Table table, String columnPrefix) {
        List<Expression> columns = new ArrayList<>();
        columns.add(Column.aliased("id", table, columnPrefix + "_id"));
        columns.add(Column.aliased("date", table, columnPrefix + "_date"));
        columns.add(Column.aliased("description", table, columnPrefix + "_description"));
        columns.add(Column.aliased("amount", table, columnPrefix + "_amount"));

        columns.add(Column.aliased("label_id", table, columnPrefix + "_label_id"));
        return columns;
    }
```

The `Operation` table has not `_label_id` column as far as I can tell. Furthermore the query also uses `label_id` which does not exists on `Label` table or `Operation` table. Maybe we need to use the join table here? 

```java
        List<Expression> columns = OperationSqlHelper.getColumns(entityTable, EntityManager.ENTITY_ALIAS);
        columns.addAll(LabelSqlHelper.getColumns(labelTable, "label"));
        SelectFromAndJoinCondition selectFrom = Select
            .builder()
            .select(columns)
            .from(entityTable)
            .leftOuterJoin(labelTable)
            .on(Column.create("label_id", entityTable))
            .equals(Column.create("id", labelTable));
```

This is the sql exception:

```
Column "E.LABEL_ID" not found; SQL statement:
SELECT e.id AS e_id, e.date AS e_date, e.description AS e_description, e.amount AS e_amount, e_label.id AS label_id, e_label.label_name AS label_label_name FROM operation e LEFT OUTER JOIN label AS e_label ON e.label_id = e_label.id ORDER BY e_id DESC LIMIT 20 OFFSET 0 [42122-200]
```

**Comment by gzsombor** [comment]
I have a look on it!

**Comment by gzsombor** [comment]
Sorry, your mapper changes are incorrect. The problem introduced in [this](https://github.com/jhipster/generator-jhipster/commit/3a9562ae78c22c614b5da8bfeb891d26594c6c57#diff-e606891a5f420e4c77cf7e4ba7b787c4) recent commit, where the _eagerRelations_ variable got a whole new meaning and definition. Previously, it was a list of relations which 
```
rel.relationshipType === 'many-to-one' || (rel.relationshipType === 'one-to-one' && rel.ownerSide === true
```
Now, it's defined as 
```
!relationship.embedded && (this.context.eagerLoad || (relationship.relationshipType === 'many-to-many' && relationship.ownerSide === true))
```
which is very different from the previous one.
 So for example, in the OperationRowMapper, previously there was a call to:
```
    entity.setBankAccountId(converter.fromRow(row, prefix + "_bank_account_id", Long.class));
```

Now we have:
```
    entity.setLabelId(converter.fromRow(row, prefix + "_label_id", Long.class));
```

**Comment by atomfrede** [comment]
Already thought of something with one-to-one and one-to-many as it looked correct for one-to- one relations. I will have detailed look later today

**Comment by gzsombor** [comment]
> 
> @gzsombor so `eagerRelations` should be called `ownedRelations` instead? And `regularEagerRelations` called `relationOwnedRelations`?

Yes, that could be a better name. I think, this eager naming comes the JPA/Hibernate nomenclature, where these fields are eagerly loaded by default.

**Comment by mshima** [comment]
> Yes, that could be a better name. I think, this eager naming comes the JPA/Hibernate nomenclature, where these fields are eagerly loaded by default.

It's ok then.

This is the eager load logic used for non reactive java.
```
!relationship.embedded && (this.context.eagerLoad || (relationship.relationshipType === 'many-to-many' && relationship.ownerSide === true))
```

So we should create `reactiveEagerRelations`, or think in a logic that can be used for both.

**Comment by mraible** [comment]
Any updates on this issue? Anything I can do to help fix it?

**Comment by atomfrede** [comment]
Your sample should work now but there are more issues for other relations.

**Comment by mraible** [comment]
@atomfrede I can confirm that the changes in this branch solve my issue.

```
➜  gateway git:(master) npm run e2e

> gateway@0.0.1-SNAPSHOT e2e /Users/mraible/apps/gateway
> npm run e2e:protractor


> gateway@0.0.1-SNAPSHOT e2e:protractor /Users/mraible/apps/gateway
> protractor src/test/javascript/protractor.conf.js

[12:47:20] I/launcher - Running 1 instances of WebDriver
[12:47:20] I/direct - Using ChromeDriver directly...


  account
    ✓ should fail to login with bad password
    ✓ should login successfully with admin account
    ✓ should navigate to 404 not found error page on non existing route and show user own navbar if valid authentication exists

  administration
    ✓ should load metrics
    ✓ should load health
    ✓ should load configuration
    ✓ should load logs

  Blog e2e test
    ✓ should load Blogs
    ✓ should load create Blog page
    ✓ should create and save Blogs
    ✓ should delete last Blog

  Post e2e test
    ✓ should load Posts
    ✓ should load create Post page
    ✓ should create and save Posts
    ✓ should delete last Post

  Tag e2e test
    ✓ should load Tags
    ✓ should load create Tag page
    ✓ should create and save Tags
    ✓ should delete last Tag

  Product e2e test
    ✓ should load Products
    ✓ should load create Product page
    ✓ should create and save Products
    ✓ should delete last Product


  23 passing (24s)
```

An interesting paradigm that might surprise users: everything starts up OK, but some Docker containers might not be running and you won't know it until you hit them. 

This is the nature of reactive but can come as a surprise. 

For example, when I first ran `npm run e2e`, the `blog` app's tests failed because Neo4J wasn't running. Then the `store` app's tests failed because Elasticsearch wasn't running. I don't know if we can do anything to solve this, but I figured I'd mention it just in case we can.

**Comment by mraible** [comment]
@atomfrede I'd suggest merging this PR, closing the issue I created. Then create a new issue for the relationships problems.

**Comment by atomfrede** [comment]
Fun fact I had the same problems when trying your sample. Will try to find a solution for the remaining problems we still have.

**Comment by atomfrede** [comment]
> @atomfrede I'd suggest merging this PR, closing the issue I created. Then create a new issue for the relationships problems.

Sure we can. Let me revert the incorrect change in the rowmapper.

**Comment by atomfrede** [comment]
I have create this issues to follow the bug(s) found https://github.com/jhipster/generator-jhipster/issues/12730

**Comment by mshima** [comment]
This PR fixes 3 tests. Merging it.

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/26305

**Pull request merged**
