### PR TITLE
'add language dutch'

### PR DESCRIPTION
**Pull request by seghers**
I translated the necessary files but was unable to get it working.

after adding the dutch language: 'yo jhipster:languages'
and running the project. I'm able to see the dutch/nederlands box. But clicking on it won't change the language. the language cookie changes to 'nl'

### CODE REVIEW

**Comment by jdubois** [comment]
@seghers you're missing a `entity/templates/src/main/webapp/i18n/_entity_nl.json` file, can you have a look?

**Comment by seghers** [comment]
bug is still there. I'm missing something but I don't know what...

chrome developer tools:
error

**Comment by gzsombor** [comment]
Some generated json file must be corrupt.

**Comment by seghers** [comment]
@gzsombor thank you.

for me this pr is ready, @jdubois .

**Pull request merged**
