### PR TITLE
Heroku: set ${JHIPSTER_REGISTRY_URL} only for eureka apps

### PR DESCRIPTION
**Pull request by fleboulch**
Non eureka apps don't require ${JHIPSTER_REGISTRY_URL}

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by fleboulch** [comment]
@jkutner do we need to keep `fail-fast: true` property for non-eureka apps?

**Comment by jdubois** [comment]
For Spring Cloud Config I'm not sure: maybe we still need the conf for Consul - @PierreBesson WDYT ?

**Comment by PierreBesson** [comment]
No we should only need this for Eureka. Let's wait for @jkutner for confirmation.

**Comment by jkutner** [comment]
Correct, i believe it is fine to only have `fail-fast: true` for Eureka apps. Thanks for the PR!

**Pull request merged**
