### PR TITLE
Rename package io.github.jhipster -> tech.jhipster

### LINKED ISSUE #12854: Rename package io.github.jhipster -> tech.jhipster
As part of V7 Roadmap, It has been required to rename package io.github.jhispter -> tech.jhipster

To do so, it has been decided to create a new project [jhipster-bom](https://github.com/jhipster/jhipster-bom) to start with a new maven dependency starting on version 1.0.0.

Old project [jhipster](https://github.com/jhipster/jhipster) will be then discontinued

### PR DESCRIPTION
**Pull request by DanielFran**
Fix #12854
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@DanielFran : a lot of failure in builds, I'll review it once it's green

**Comment by DanielFran** [comment]
> @DanielFran : a lot of failure in builds, I'll review it once it's green

Yes, do not know what is missing...
Will try to test it again locally

**Comment by pascalgrimaud** [comment]
@DanielFran : if it works locally, but fails in CI, let me know, I can try to reproduce on my side. Just tell me if you need help

**Comment by pascalgrimaud** [comment]
Just gave a quick try, and I can reproduce locally the exact problem in the CI :

```
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfiguration' defined in file [/home/runner/work/generator-jhipster/generator-jhipster/app/target/classes/tech/jhipster/sample/config/SecurityConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.zalando.problem.spring.web.advice.security.SecurityProblemSupport': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'metricsWebMvcConfigurer' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/web/servlet/WebMvcMetricsAutoConfiguration.class]: Unsatisfied dependency expressed through method 'metricsWebMvcConfigurer' parameter 0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'io.micrometer.core.instrument.MeterRegistry' available: expected single matching bean but found 2: prometheusMeterRegistry,consoleLoggingRegistry
```

**Comment by pascalgrimaud** [comment]
I understand the error but I don't understand why it happens only now, when changing package name ?

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method metricsWebMvcConfigurer in org.springframework.boot.actuate.autoconfigure.metrics.web.servlet.WebMvcMetricsAutoConfiguration required a single bean, but 2 were found:
	- simpleMeterRegistry: defined by method 'simpleMeterRegistry' in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/export/simple/SimpleMetricsExportAutoConfiguration.class]
	- consoleLoggingRegistry: defined by method 'consoleLoggingRegistry' in class path resource [tech/jhipster/config/metric/JHipsterLoggingMetricsExportConfiguration.class]

```

**Comment by DanielFran** [comment]
@pascalgrimaud I was able too to reproduce the issue, but the code has not been changed.
Do not understand what is happening.

Looking at the [roadmap](https://github.com/jhipster/generator-jhipster/issues/10958), there is a request to stop exporting metrics through logback/logstash (https://github.com/jhipster/generator-jhipster/issues/10958#issuecomment-596448093) and so dropwizard dependency.

Maybe we can then remove JHipsterLoggingMetricsExportConfiguration?

**Comment by DanielFran** [comment]
Superseded by #12881

**Pull request closed without merging**
