### PR TITLE
add pacman loader and message

### PR DESCRIPTION
**Pull request by sabrinapayet**
@pascalgrimaud told me that JHipster needed a message when the front is not compiled, so I did my best to add a cute loader and a message that appears after 4 seconds.
What do you think ?

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Ping @jdubois @wmarques
As you discussed about it, at the last JHipster day

**Comment by pascalgrimaud** [comment]
@deepu105 : it is automatically removed if the front is compiled !

**Comment by deepu105** [comment]
@sabrinapayet @pascalgrimaud now I'm curious :thinking: , how does the removal happen?

**Comment by deepu105** [comment]
@sabrinapayet btw the animation super cool :) I love it. Great job

**Comment by deepu105** [comment]
@pascalgrimaud its not removed during compile, it just gets removed when angular/react renders on top of the div. But I like the animation so its ok to have it, i'm gonna make some improvements and merge it. Thanks a lot @sabrinapayet

**Comment by pascalgrimaud** [comment]
oh understood @deepu105
We read https://medium.com/@tomastrajan/how-to-style-angular-application-loading-with-angular-cli-like-a-boss-cdd4f5358554

> Angular removes content inside of <app-root></app-root> after successful Angular bootstrap so we don’t have to take care of hiding of the loading layout manually

**Comment by jdubois** [comment]
Hey, I didn't have the time to look at it, I wanted to create a ticket with a $100 bug bounty because that's a very important feature: could you do the ticket for me?

Besides I want the same idea if the front end is loaded but not the back end -> in dev mode, I want the same kind of error message if the back end is not available, and that would be another ticket.

I'm so sorry I don't have enough time at the moment

**Comment by pascalgrimaud** [comment]
Done @jdubois 
I created the 2 tickets, but I didn't put any bounty. Following our rules, only Deepu and you can do it and decide if it deserves.

**Comment by sabrinapayet** [comment]
Thank you  @deepu105  and @jdubois :smile:

**Comment by sabrinapayet** [comment]
bounty claimed 
https://opencollective.com/generator-jhipster/expenses/5325

**Comment by jdubois** [comment]
And already paid, congrats :-)

**Pull request merged**
