### PR TITLE
Move Reactive with WebFlux to Beta 🎉

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
`webflux-couchbase-es-oauth2` is failing. I tried it locally and got the following error from `UserResourceIT#getAllUsers()`:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error 
creating bean with name 'userService' defined in file [/Users/mraible/Desktop/webflux-couchbase-es-
oauth2/build/classes/java/main/io/github/jhipster/sample/service/UserService.class]: 
Unsatisfied dependency expressed through constructor parameter 0; nested exception is 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'userRepository': Invocation of init method failed; nested exception is 
org.springframework.data.mapping.PropertyReferenceException: No property removeAll found 
for type User!
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
```

**Comment by mraible** [comment]
Maybe this is caused by `UserSearchRepository`?

```
public interface UserSearchRepository extends ElasticsearchRepository<User, String> {
}
```

I tried changing it to extend `ReactiveElasticsearchRepository`:

```
package io.github.jhipster.sample.repository.search;

import io.github.jhipster.sample.domain.User;
import org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository;

/**
 * Spring Data Elasticsearch repository for the User entity.
 */
public interface UserSearchRepository extends ReactiveElasticsearchRepository<User, String> {
}
```

However, this results in:

```
/Users/mraible/.../io/github/jhipster/sample/web/rest/UserResource.java:125: error: cannot find symbol
            .stream(userSearchRepository.search(queryStringQuery(query)).spliterator(), false)
                                        ^
  symbol:   method search(QueryStringQueryBuilder)
  location: variable userSearchRepository of type UserSearchRepository
```

**Comment by murdos** [comment]
@mraible : I just tried your branch on the `webflux-couchbase-es-oauth2` sample and I have a different error (the same that is visible in the CI):
```
/home/runner/app/src/main/java/io/github/jhipster/sample/service/UserService.java:167: error: incompatible types: inference variable T has incompatible bounds
> Task :compileJava
        user.setAuthorities(authToken.getAuthorities().stream()
            ^
    equality constraints: String
    lower bounds: Authority
  where T is a type-variable:
    T extends Object declared in method <T>toSet()
```

This is caused by the change you made to `UserService.java.ejs`: https://github.com/jhipster/generator-jhipster/pull/11571/files#diff-eb8ab57e6c1b5729372ec3081226b95dR970 
this block of code was not generated for couchbase before, it's now and doesn't compile.

Also I've not confirmed the other issue you raised, here `UserSearchRepository` already extends `ReactiveElasticsearchRepository`.

**Comment by mraible** [comment]
The `webflux-couchbase-es-oauth2` is still failing. When I run it locally, the error is the same.

```
Error creating bean with name 'userRepository': Invocation of init method failed; 
nested exception is org.springframework.data.mapping.PropertyReferenceException: 
No property removeAll found for type User!
```

**Comment by murdos** [comment]
@mraible I've created #11576. It looks like Couchbase and Elasticsearch has never work together.

**Comment by mraible** [comment]
I tried running the integration tests for `webflux-mongodb-oauth2` locally and they just hang. To see the stack traces, I added the following at the bottom of `build.gradle`:

```
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

tasks.withType(Test) {
    testLogging {
        // set options for log level LIFECYCLE
        events TestLogEvent.FAILED,
               TestLogEvent.PASSED,
               TestLogEvent.SKIPPED,
               TestLogEvent.STANDARD_OUT
        exceptionFormat TestExceptionFormat.FULL
        showExceptions true
        showCauses true
        showStackTraces true

        // set options for log level DEBUG and INFO
        debug {
            events TestLogEvent.STARTED,
                   TestLogEvent.FAILED,
                   TestLogEvent.PASSED,
                   TestLogEvent.SKIPPED,
                   TestLogEvent.STANDARD_ERROR,
                   TestLogEvent.STANDARD_OUT
            exceptionFormat TestExceptionFormat.FULL
        }
        info.events = debug.events
        info.exceptionFormat = debug.exceptionFormat

        afterSuite { desc, result ->
            if (!desc.parent) { // will match the outermost suite
                def output = "Results: ${result.resultType} (${result.testCount} tests, ${result.successfulTestCount} passed, ${result.failedTestCount} failed, ${result.skippedTestCount} skipped)"
                def startItem = '|  ', endItem = '  |'
                def repeatLength = startItem.length() + output.length() + endItem.length()
                println('\n' + ('-' * repeatLength) + '\n' + startItem + output + endItem + '\n' + ('-' * repeatLength))
            }
        }
    }
}
```

And here's the output before it starts hanging:

```
UserServiceIT > testUserDetailsWithUSLocaleUnderscore() PASSED
2020-04-12 11:21:39.171 ERROR 32814 --- [ntLoopGroup-2-6] i.n.u.c.D.rejectedExecution              : Failed to submit a listener notification task. Event loop shut down?

reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
        at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
        at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
        at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
        at java.base/java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:409)
        at java.base/java.util.AbstractQueue.add(AbstractQueue.java:95)
        at io.netty.util.concurrent.GlobalEventExecutor.addTask(GlobalEventExecutor.java:141)
        at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:206)
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

2020-04-12 11:21:39.171 ERROR 32814 --- [tLoopGroup-2-21] i.n.u.c.D.rejectedExecution              : Failed to submit a listener notification task. Event loop shut down?

reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
        at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
        at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
        at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
        at java.base/java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:409)
        at java.base/java.util.AbstractQueue.add(AbstractQueue.java:95)
        at io.netty.util.concurrent.GlobalEventExecutor.addTask(GlobalEventExecutor.java:141)
        at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:206)
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

2020-04-12 11:21:39.171 ERROR 32814 --- [ntLoopGroup-2-5] i.n.u.c.D.rejectedExecution              : Failed to submit a listener notification task. Event loop shut down?

reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
        at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
        at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
        at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
        at java.base/java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:409)
        at java.base/java.util.AbstractQueue.add(AbstractQueue.java:95)
        at io.netty.util.concurrent.GlobalEventExecutor.addTask(GlobalEventExecutor.java:141)
        at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:206)
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

2020-04-12 11:21:39.177 ERROR 32814 --- [ntLoopGroup-2-3] i.n.u.c.D.rejectedExecution              : Failed to submit a listener notification task. Event loop shut down?

reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
        at java.base/jdk.internal.misc.Unsafe.park(Unsafe.java)
        at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
        at java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
        at java.base/java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:409)
        at java.base/java.util.AbstractQueue.add(AbstractQueue.java:95)
        at io.netty.util.concurrent.GlobalEventExecutor.addTask(GlobalEventExecutor.java:141)
        at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:206)
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

2020-04-12 11:21:39.179 DEBUG 32814 --- [extShutdownHook] d.f.embed.mongo.AbstractMongoProcess     : try to stop mongod
2020-04-12 11:21:39.598 DEBUG 32814 --- [extShutdownHook] d.f.embed.process.io.file.Files          : could delete /var/folders/f7/5x4rvsr5599ffnfckn487nzm0000gn/T/embedmongo-db-eb6af85b-dbb9-4fd8-b8ef-08717a456c33
2020-04-12 11:21:39.598 DEBUG 32814 --- [extShutdownHook] d.f.embed.process.io.file.Files          : could delete /var/folders/f7/5x4rvsr5599ffnfckn487nzm0000gn/T/extract-5864f7ae-a028-448d-9ca6-d514f395752cextractmongod.pid
2020-04-12 11:21:39.602 DEBUG 32814 --- [extShutdownHook] d.f.embed.process.io.file.Files          : could delete /var/folders/f7/5x4rvsr5599ffnfckn487nzm0000gn/T/extract-5864f7ae-a028-448d-9ca6-d514f395752cextractmongod
<============-> 92% EXECUTING [3m 19s]
> :integrationTest > 33 tests completed
```

If I run `UserResourceIT` from IntelliJ, all tests pass, but the shutdown process still hangs.

**Comment by mraible** [comment]
If I remove `blockhound-junit-platform` as a dependency, running `./gradlew integrationTest` passes. Any ideas @bsideup?

Steps to reproduce:

```
git clone git@github.com:jhipster/generator-jhipster.git
cd generator-jhipster
npm link
```

Create a new directory called `webflux-mongodb-oauth2` and put the JSON below in `webflux-mongodb-oauth2/.yo-rc.json`. 

```json
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "reactive": true,
    "baseName": "sampleWebfluxMongodbOauth2",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "buildTool": "gradle",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "testFrameworks": ["gatling", "protractor"],
    "serverPort": "8080",
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "jhipsterVersion": "6.8.0",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientTheme": "none",
    "creationTimestamp": 1580314672693,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  }
}
```

Then cd into the directory and run the following:

```
jhipster
./gradlew integrationTest
```

**Comment by bsideup** [comment]
Hi @mraible,

Sorry, I missed the notification :)

From the exception, it seems that the blocking call comes from `GlobalEventExecutor.addTask` -> `LinkedBlockingQueue.offer` chain.
`LinkedBlockingQueue` here looks suspicious, I would recommend reporting it to the Netty folks 👍 

Meanwhile, you can temporary whitelist it via a custom integration:
https://github.com/reactor/BlockHound/blob/master/docs/custom_integrations.md

**Comment by cbornet** [comment]
There has already been fixes in [Netty's GlobalEventExecutor](https://github.com/netty/netty/pull/10020). That's why we force [Netty 4.1.16](https://github.com/cbornet/generator-jhipster/blob/ba77eb14b3e00f6bf5c4e18795eed0b95460ef5b/generators/server/templates/pom.xml.ejs#L696).
Seems that there are still issues...

**Comment by cbornet** [comment]
The blocking call in Netty's GlobalEventExecutor.addTask has been fixed on Netty's master : https://github.com/netty/netty/pull/10262
Now waiting for a release

**Comment by cbornet** [comment]
Oh it's already been released ! Let's try to reactivate BlockHound !

**Pull request merged**
