### PR TITLE
Add no database option for Oauth2/OIDC apps

### PR DESCRIPTION
**Pull request by cbornet**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

To merge after #9644

### CODE REVIEW

**Comment by jdubois** [comment]
@cbornet you have eslint errors, this is why the build fails

**Comment by jdubois** [comment]
@cbornet thanks for the fixes - I think this can wait for the next release, in fact it might even be better as I need to add support for this in JHipster Online too

**Comment by jdubois** [comment]
@cbornet that's 2 big PRs in a row -> I added a $100 bug bounty to this PR (next time please do a ticket first, as bug bounties should be on tickets), don't hesitate to claim it once this is merged!

**Comment by cbornet** [comment]
OK. I'll create an issue first next time. I just wanted to keep the issue tracker at low count :smiley:

**Comment by avdev4j** [comment]
This sound great, it starts in 6s.
I would test more with a company oauth2 but I struggle with the new spring security config and my environnement. 

I'll do more tests with a keycloack later 👍

**Comment by pascalgrimaud** [comment]
Just tested and it works fine. Great job as usual !!
LGTM, is it ready to be merged @cbornet ?

**Comment by cbornet** [comment]
Yes it is :smiley:

**Comment by jsm174** [comment]
So if I understand this correctly, we can now create oauth2 gateways with no database.  Will this be supported in JDL? 

I can create it this way via `jhipster`, but when I try `jhipster import-jdl`, I get:

```
Error: Having no database type is only allowed for microservices without oauth2 authentication type and gateways with UAA authentication type.
ERROR! Error while parsing applications and entities from the JDL Error: Having no database type is only allowed for microservices without oauth2 authentication type and gateways with UAA authentication type.
```

It's getting hung up at:

https://github.com/jhipster/jhipster-core/blob/master/lib/exceptions/application_validator.js#L211

**Comment by ruddell** [comment]
That check needs to be updated now that the option is available for more app types.  Can you please open an issue in the `jhipster-core` repository for this change?

**Comment by cbornet** [comment]
bounty claimed

**Pull request merged**
