### PR TITLE
Make sure pom.xml doesn't have any reference to liquibase if no sql database is used

### PR DESCRIPTION
**Pull request by murdos**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@murdos Maybe we should also remove reference from logback file?
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/logback-spring.xml.ejs#L123

**Comment by murdos** [comment]
@DanielFran If you look at [L122](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/logback-spring.xml.ejs#L122), it's already conditioned by `(databaseType === 'sql')` ;-)

**Comment by DanielFran** [comment]
@murdos Did not see it.... Thanks

**Comment by jdubois** [comment]
Awesome work @murdos you even did tests :-)

**Pull request merged**
