### PR TITLE
Use updated dataUtils.setFileData() and handle returned promise

### PR DESCRIPTION
**Pull request by vivekmore**
Updating core generator to use the new dataUtils.setFileData() per [this discussion](https://github.com/jhipster/ng-jhipster/pull/88#issuecomment-457581776)

----

Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vivekmore** [comment]
@wmarques 
I couldn't find a place where I would add test for my change
Kindly suggest where/how I can add tests.

**Comment by vivekmore** [comment]
> check the test folder if we have some test for this case.

I checked the test folder, but couldn't find any test for this method.

> You also need to bump the ng-jhipster version

ng-jhipster is already up-to-date (d4ca3dc06dc22f5c9d7c875e8e09fa31bd60f46a)

**Comment by vivekmore** [comment]
It appears the [changes](https://github.com/jhipster/ng-jhipster/pull/88) did not result in the generation of the right `data-util.service.d.ts` which causes the builds against this PR to fail.

Can anybody point me to anything I missed in my [PR to ng-jhipster](https://github.com/jhipster/ng-jhipster/pull/88)

**Comment by wmarques** [comment]
@vivekmore I'm not sure your commit has been merged before the latest ng-jhipster release, that would explain why it's not working

**Comment by vivekmore** [comment]
> @vivekmore I'm not sure your commit has been merged before the latest ng-jhipster release, that would explain why it's not working

@wmarques - I had the same suspicion - I verified that my changes are in `ng-jhipster:0.9.1` and thus in `generator-jhipster:5.8.1`

**Comment by vivekmore** [comment]
@wmarques - I think the changes are released, however the type definition file that gets generated in the dist folder (which is not a part of the repo) does not appear to be inline with the modified signature of the setFileData() which in-turn causes typescript compilation error(s) in the generated jhipster app

**Comment by wmarques** [comment]
@vivekmore I built ng-jhipster on my laptop, the dist directory contains the correct type definitions, so for me is more of a release issue, as it works on my machine with a local `ng-jhipster` build

**Comment by deepu105** [comment]
May the ng-packer doesnt include it? or is skipped in npm pack, can you do
`npm pack` and see if its there

Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
@deepu105 I've done `npm pack` but in the `dist` folder, and it worked, maybe I'm missing something...

**Comment by deepu105** [comment]
np release does same as npm pack

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Maybe it was a glitch, I can make a new release if you want

Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
@deepu105 Maybe I can create a "test" npm repository to check the release scripts, it's better than doing a new "official" release 😄 wdyt ?

**Comment by wmarques** [comment]
@deepu105 just created a sample lib to test: https://www.npmjs.com/package/ng-jhiwma
Published it using `npm run build && npm run publish dist/` and it worked after changing the imports in the generated application of course.

So looks like we had a glitch during release, can you do another one please ?

**Comment by deepu105** [comment]
Ok I made another patch release, plz check

Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
@deepu105 Still not working.. I don't know what's missing in the release pipeline. Are you sure you are publishing the latest master version ?

**Comment by vivekmore** [comment]
> @deepu105 just created a sample lib to test: https://www.npmjs.com/package/ng-jhiwma
> Published it using `npm run build && npm run publish dist/` and it worked after changing the imports in the generated application of course.
> 
> So looks like we had a glitch during release, can you do another one please ?

I've updated the code to use the latest patch `0.9.2` of ng-jhipster, but the builds fail for the same reason.
This makes me wonder that the build's environment of building and packaging the generated app is different than your local or [ng-jhiwma](https://www.npmjs.com/package/ng-jhiwma) build environment.

Probably a node/npm version mismatch causing different outcomes of npm package.

**Comment by wmarques** [comment]
@vivekmore I reran `npm install` and I'm on node v10... @pascalgrimaud did a fresh install and has also the correct typings when running `npm run build`.

@deepu105 Do you want me to try to publish a patch version ? I can check with @jdubois to have the publishing rights.

**Comment by pascalgrimaud** [comment]
I confirm the strange behavior.
In a fresh generated project, using ng-jhipster 0.9.2, I look into `node_modules/ng-jhipster/service/data-util.service.d.ts` :

```typescript
import { ElementRef } from '@angular/core';
export declare class JhiDataUtils {
    constructor();
    abbreviate(text: string, append?: string): string;
    byteSize(base64String: string): string;
    openFile(contentType: string, data: string): void;
    toBase64(file: File, cb: Function): void;
    clearInputImage(entity: any, elementRef: ElementRef, field: string, fieldContentType: string, idInput: string): void;
    private endsWith(suffix, str);
    private paddingSize(value);
    private size(value);
    private formatAsBytes(size);
    setFileData(event: any, entity: any, field: string, isImage: boolean): void;
    downloadFile(contentType: string, data: string, fileName: string): void;
}
```

Locally, when I run `npm  run build`, I got this file:
```typescript
import { ElementRef } from '@angular/core';
/**
 * An utility service for data.
 */
export declare class JhiDataUtils {
    constructor();
    /**
     * Method to abbreviate the text given
     */
    abbreviate(text: string, append?: string): string;
    /**
     * Method to find the byte size of the string provides
     */
    byteSize(base64String: string): string;
    /**
     * Method to open file
     */
    openFile(contentType: string, data: string): void;
    /**
     * Method to convert the file to base64
     */
    toBase64(file: File, cb: Function): void;
    /**
     * Method to clear the input
     */
    clearInputImage(entity: any, elementRef: ElementRef, field: string, fieldContentType: string, idInput: string): void;
    /**
     * Sets the base 64 data & file type of the 1st file on the event (event.target.files[0]) in the passed entity object
     * and returns a promise.
     *
     * @param event the object containing the file (at event.target.files[0])
     * @param entity the object to set the file's 'base 64 data' and 'file type' on
     * @param field the field name to set the file's 'base 64 data' on
     * @param isImage boolean representing if the file represented by the event is an image
     * @returns a promise that resolves to the modified entity if operation is successful, otherwise rejects with an error message
     */
    setFileData(event: any, entity: any, field: string, isImage: boolean): Promise<any>;
    /**
     * Method to download file
     */
    downloadFile(contentType: string, data: string, fileName: string): void;
    private endsWith;
    private paddingSize;
    private size;
    private formatAsBytes;
}
```

**Comment by vivekmore** [comment]
thanks for confirming @pascalgrimaud ! I experienced the same

**Comment by deepu105** [comment]
If there is strange behaviour then its definitely after migration to ng packr, releases were fine before that

**Comment by deepu105** [comment]
And yes I was deploying latest master. You don't have to publish to verify. If you run npm pack the tarbal will be same as when you publish and then you can point to that file and do a lical npm install

**Comment by vishal423** [comment]
@deepu105, can you try clearing your dist directory followed by build and release, if not already done so?

**Comment by deepu105** [comment]
I think the problem is that there is no cleanup step and the d.ts files may not be being regenerated, let me look into it

**Comment by deepu105** [comment]
Seems like `"cleanup": "rimraf src/*.d.ts src/**/*.d.ts src/*.js src/**/*.js aot/* tests/**/*.d.ts tests/**/*.js tests/*.d.ts tests/*.js",` step have been removed, may be during ng-pakgr migration, actually I can see the problem when I build locally as well since I had the generated files pre migration there, I guess cleaning them will fix the issue. But after cleaning them I get build failure
```
BUILD ERROR
@angular/forms/src/validators.ts(39,22): Error during template compile of 'NG_VALIDATORS'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
: Invalid providers for "JhiMaxbytesValidatorDirective in /home/deepu/workspace/jhipster/ng-jhipster/src/directive/maxbytes.directive.ts" - only instances of Provider and Type are allowed, got: [?[object Object]?]
@angular/forms/src/validators.ts(39,22): Error during template compile of 'NG_VALIDATORS'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
: Invalid providers for "JhiMinbytesValidatorDirective in /home/deepu/workspace/jhipster/ng-jhipster/src/directive/minbytes.directive.ts" - only instances of Provider and Type are allowed, got: [?[object Object]?]
@angular/forms/src/validators.ts(39,22): Error during template compile of 'NG_VALIDATORS'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
: Invalid providers for "JhiMaxValidatorDirective in /home/deepu/workspace/jhipster/ng-jhipster/src/directive/max.directive.ts" - only instances of Provider and Type are allowed, got: [?[object Object]?]
@angular/forms/src/validators.ts(39,22): Error during template compile of 'NG_VALIDATORS'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
: Invalid providers for "JhiMinValidatorDirective in /home/deepu/workspace/jhipster/ng-jhipster/src/directive/min.directive.ts" - only instances of Provider and Type are allowed, got: [?[object Object]?]
Error during template compile of 'NgJhipsterModule'
  Function calls are not supported in decorators but 'TranslateModule' was called.
Error during template compile of 'NgJhipsterModule'
  Function calls are not supported in decorators but 'NgbModule' was called.
: Unexpected value 'CommonModule in /home/deepu/workspace/jhipster/ng-jhipster/node_modules/@angular/common/src/common_module.d.ts' imported by the module 'NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts'. Please add a @NgModule annotation.
: Unexpected value 'undefined' imported by the module 'NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts'
: Unexpected value 'FormsModule in /home/deepu/workspace/jhipster/ng-jhipster/node_modules/@angular/forms/src/form_providers.d.ts' imported by the module 'NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts'. Please add a @NgModule annotation.
: Can't export value TranslateModule in /home/deepu/workspace/jhipster/ng-jhipster/node_modules/@ngx-translate/core/public_api.d.ts from NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts as it was neither declared nor imported!
: Can't export value CommonModule in /home/deepu/workspace/jhipster/ng-jhipster/node_modules/@angular/common/src/common_module.d.ts from NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts as it was neither declared nor imported!
Error during template compile of 'NgJhipsterModule'
  Function calls are not supported in decorators but 'TranslateModule' was called.
Error during template compile of 'NgJhipsterModule'
  Function calls are not supported in decorators but 'NgbModule' was called.
: Can't bind to 'ngIf' since it isn't a known property of 'div'. ("
        <div [ERROR ->]*ngIf="i18nEnabled; else noI18n" class="info jhi-item-count" jhiTranslate="global.item-count" [transl")
: Can't bind to 'ngIfElse' since it isn't a known property of 'div'. ("
        <div [ERROR ->]*ngIf="i18nEnabled; else noI18n" class="info jhi-item-count" jhiTranslate="global.item-count" [transl")
: Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
        [ERROR ->]<div *ngIf="i18nEnabled; else noI18n" class="info jhi-item-count" jhiTranslate="global.item-count" [t")
: Property binding ngIfElse not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
        [ERROR ->]<div *ngIf="i18nEnabled; else noI18n" class="info jhi-item-count" jhiTranslate="global.item-count" [t")

Error: @angular/forms/src/validators.ts(39,22): Error during template compile of 'NG_VALIDATORS'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
: Invalid providers for "JhiMaxbytesValidatorDirective in /home/deepu/workspace/jhipster/ng-jhipster/src/directive/maxbytes.directive.ts" - only instances of Provider and Type are allowed, got: [?[object Object]?]
@angular/forms/src/validators.ts(39,22): Error during template compile of 'NG_VALIDATORS'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
: Invalid providers for "JhiMinbytesValidatorDirective in /home/deepu/workspace/jhipster/ng-jhipster/src/directive/minbytes.directive.ts" - only instances of Provider and Type are allowed, got: [?[object Object]?]
@angular/forms/src/validators.ts(39,22): Error during template compile of 'NG_VALIDATORS'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
: Invalid providers for "JhiMaxValidatorDirective in /home/deepu/workspace/jhipster/ng-jhipster/src/directive/max.directive.ts" - only instances of Provider and Type are allowed, got: [?[object Object]?]
@angular/forms/src/validators.ts(39,22): Error during template compile of 'NG_VALIDATORS'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
: Invalid providers for "JhiMinValidatorDirective in /home/deepu/workspace/jhipster/ng-jhipster/src/directive/min.directive.ts" - only instances of Provider and Type are allowed, got: [?[object Object]?]
Error during template compile of 'NgJhipsterModule'
  Function calls are not supported in decorators but 'TranslateModule' was called.
Error during template compile of 'NgJhipsterModule'
  Function calls are not supported in decorators but 'NgbModule' was called.
: Unexpected value 'CommonModule in /home/deepu/workspace/jhipster/ng-jhipster/node_modules/@angular/common/src/common_module.d.ts' imported by the module 'NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts'. Please add a @NgModule annotation.
: Unexpected value 'undefined' imported by the module 'NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts'
: Unexpected value 'FormsModule in /home/deepu/workspace/jhipster/ng-jhipster/node_modules/@angular/forms/src/form_providers.d.ts' imported by the module 'NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts'. Please add a @NgModule annotation.
: Can't export value TranslateModule in /home/deepu/workspace/jhipster/ng-jhipster/node_modules/@ngx-translate/core/public_api.d.ts from NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts as it was neither declared nor imported!
: Can't export value CommonModule in /home/deepu/workspace/jhipster/ng-jhipster/node_modules/@angular/common/src/common_module.d.ts from NgJhipsterModule in /home/deepu/workspace/jhipster/ng-jhipster/src/ng-jhipster.module.ts as it was neither declared nor imported!
Error during template compile of 'NgJhipsterModule'
  Function calls are not supported in decorators but 'TranslateModule' was called.
Error during template compile of 'NgJhipsterModule'
  Function calls are not supported in decorators but 'NgbModule' was called.
: Can't bind to 'ngIf' since it isn't a known property of 'div'. ("
        <div [ERROR ->]*ngIf="i18nEnabled; else noI18n" class="info jhi-item-count" jhiTranslate="global.item-count" [transl")
: Can't bind to 'ngIfElse' since it isn't a known property of 'div'. ("
        <div [ERROR ->]*ngIf="i18nEnabled; else noI18n" class="info jhi-item-count" jhiTranslate="global.item-count" [transl")
: Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
        [ERROR ->]<div *ngIf="i18nEnabled; else noI18n" class="info jhi-item-count" jhiTranslate="global.item-count" [t")
: Property binding ngIfElse not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
        [ERROR ->]<div *ngIf="i18nEnabled; else noI18n" class="info jhi-item-count" jhiTranslate="global.item-count" [t")

    at Object.<anonymous> (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ngc/compile-source-files.js:51:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ngc/compile-source-files.js:4:58)
```

@wmarques any idea? are you guys building on a clean workspace, else try running `rm **/*.d.ts src/*.js src/**/*.js aot/* tests/**/*.d.ts tests/**/*.js tests/*.d.ts tests/*.js` and run `npm run build` again

**Comment by deepu105** [comment]
I tried deleting and reinstalling npm modules and now I have a different error. Its weird
```
BUILD ERROR
error TS6053: File '/home/deepu/workspace/jhipster/ng-jhipster/node_modules/typescript/lib/lib.dom.d.ts' not found.
error TS6053: File '/home/deepu/workspace/jhipster/ng-jhipster/node_modules/typescript/lib/lib.es2018.d.ts' not found.

Error: error TS6053: File '/home/deepu/workspace/jhipster/ng-jhipster/node_modules/typescript/lib/lib.dom.d.ts' not found.
error TS6053: File '/home/deepu/workspace/jhipster/ng-jhipster/node_modules/typescript/lib/lib.es2018.d.ts' not found.

    at analyseEntryPoint (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:35:15)
    at MapSubscriber.exports.analyseSourcesTransform.rxjs_1.pipe.operators_1.map.graph [as project] (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:14:9)
    at MapSubscriber._next (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /home/deepu/workspace/jhipster/ng-jhipster/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
```

**Comment by wmarques** [comment]
@deepu105 ok i will check, it has for sure a link with the ng-packagr migration. On my laptop it overwrite the `dist` folder so that's why I removed the cleanup step.. I'll investigate, sorry

**Comment by pascalgrimaud** [comment]
@deepu105 : what is your node and npm version ?

**Comment by deepu105** [comment]
```
  ~/wo…ce/jh…er/ng-jhipster     master   5                                                                                                                 6%    10:14:15    ✔
 $ npm -v
6.4.1
  ~/wo…ce/jh…er/ng-jhipster     master   5                                                                                                                 6%    10:14:41    ✔
 $ node -v                
v10.13.0
```

**Comment by deepu105** [comment]
its weird since lib.* modules are not present in typescript folder, and each time I run `npm install` the package.lock changes a bit

**Comment by deepu105** [comment]
@wmarques I added the cleanup step back in master, can any of you try to run `npm run build` on master?

**Comment by pascalgrimaud** [comment]
Just cloned the repo, I have the same error like you, @deepu105 :

```
BUILD ERROR
error TS6053: File '/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/typescript/lib/lib.dom.d.ts' not found.
error TS6053: File '/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/typescript/lib/lib.es2018.d.ts' not found.

Error: error TS6053: File '/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/typescript/lib/lib.dom.d.ts' not found.
error TS6053: File '/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/typescript/lib/lib.es2018.d.ts' not found.

    at analyseEntryPoint (/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:35:15)
    at MapSubscriber.exports.analyseSourcesTransform.rxjs_1.pipe.operators_1.map.graph [as project] (/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:14:9)
    at MapSubscriber._next (/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /home/pgrimaud/projects/jhipster/ng-jhipster/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
```

I'm pretty sure it is related to a transitive dependencies. Why don't we use fixed version in package.json instead ?

**Comment by deepu105** [comment]
@pascalgrimaud for libraries it's better to use range so that there is a minimum conflict with end-user projects, so for peer dependencies it has to be range but may be for devDeps we can fix them

**Comment by deepu105** [comment]
ok lets fix the dev dependencies for anything that is not in peer dependencies

**Comment by deepu105** [comment]
i'm doing it

**Comment by deepu105** [comment]
even with exact versions for everything its still an issue, error message is bit different now
```
BUILD ERROR
error TS2688: Cannot find type definition file for 'estree'.
error TS2688: Cannot find type definition file for 'jest'.
error TS2688: Cannot find type definition file for 'node'.
error TS6053: File '/home/deepu/workspace/jhipster/ng-jhipster/node_modules/typescript/lib/lib.dom.d.ts' not found.
error TS6053: File '/home/deepu/workspace/jhipster/ng-jhipster/node_modules/typescript/lib/lib.es2018.d.ts' not found.

Error: error TS2688: Cannot find type definition file for 'estree'.
error TS2688: Cannot find type definition file for 'jest'.
error TS2688: Cannot find type definition file for 'node'.
error TS6053: File '/home/deepu/workspace/jhipster/ng-jhipster/node_modules/typescript/lib/lib.dom.d.ts' not found.
error TS6053: File '/home/deepu/workspace/jhipster/ng-jhipster/node_modules/typescript/lib/lib.es2018.d.ts' not found.

    at Object.<anonymous> (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at /home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at /home/deepu/workspace/jhipster/ng-jhipster/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

**Comment by deepu105** [comment]
I dont have time now to investigate further, if you guys have time plz take a look

**Comment by deepu105** [comment]
I have pushed the updates I made to master so master will be broken at the moment

**Comment by vishal423** [comment]
I had a quick look and figured below as an issue as it removes the type definitions from all including node_modules:
`"cleanup": "rimraf **/*.d.ts src/*.js src/**/*.js tests/**/*.js tests/*.js aot/* dist/*",`

Replace with below and everything should work:
`"cleanup": "rimraf dist/*",`

**Comment by wmarques** [comment]
@vishal423 oh yes I think you're right ! I'll check during my lunch pause 😄

**Comment by pascalgrimaud** [comment]
@vishal423 : tested your fix and it works

**Comment by deepu105** [comment]
Oh shit, stupid me :)

**Comment by deepu105** [comment]
I was trying to optimize by changing `src/*.d.ts src/**/*.d.ts tests/**/*.d.ts tests/*.d.ts` to `**/*.d.ts` and now I remember why I didn't do that originally :laughing:

**Comment by deepu105** [comment]
checkout the new patch release it should be good. I can see the updated type file

**Comment by wmarques** [comment]
Great ! Thanks guys 😄

**Comment by vishal423** [comment]
IMO, changes related to the fixed version should be reverted on lib as that adds maintenance overhead

**Comment by wmarques** [comment]
I'm so fed up by the NPM `package-lock` which changes even if no one touches the `package.json`... You never know if you are using the correct dependencies

**Comment by vishal423** [comment]
time to switch to `yarn` :smile:

**Comment by pascalgrimaud** [comment]
@vishal423 : we support Yarn, you can generate a project using `jhipster --yarn`, but by default, you'll have `npm`

**Comment by vishal423** [comment]
@pascalgrimaud, above reference was for `ng-jhipster`

**Comment by deepu105** [comment]
we were using Yarn and then switched to NPM, IMO no dependency management
system is perfect

Thanks & Regards,
Deepu

**Comment by vivekmore** [comment]
I could be wrong, but I feel the Azure build appears to be failing due to something unrelated to my changes.

Please let me know if I need to look into it further.

**Comment by DanielFran** [comment]
@vivekmore This is failing due to the PR https://github.com/jhipster/generator-jhipster/pull/9104 merged in master.

**Comment by vivekmore** [comment]
Thanks @DanielFran !

**Comment by wmarques** [comment]
@vivekmore thanks for contributing ! Let's merge this (finally 🎉) as the only failing build is about React

**Pull request merged**
