### PR TITLE
A pr to fix issue#10195

### PR DESCRIPTION
**Pull request by GitAntinus**
Hey guys, I cloned the io.github.jhipster package, and with pr#10194 , I recompiled the project so I get a full list of spring-configuration-metadata.json. Please add this to generator because it saves a lot of time for inetllij users.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by GitAntinus** [comment]
> I don't agree with this MR. You should add the annotation processor in this project instead : https://github.com/jhipster/jhipster/blob/master/jhipster-framework/pom.xml

the problem is that the processor wont be invoked dude. You really need to invoke it before the user of jhipsiter compile their code. Because when the compile their code, even with the processor in dependency, the source code of this project wont be processed so there would be no metadata. Do you see the problem here?

**Comment by GitAntinus** [comment]
> I don't agree with this MR. You should add the annotation processor in this project instead : https://github.com/jhipster/jhipster/blob/master/jhipster-framework/pom.xml

Besides, this metadata file is generated by spring-boot-c-processor with project jhipster-framework.

**Comment by PierreBesson** [comment]
No I think the the metadata will be present generated by maven when publishing the lib, but let's not take my word for it and do some testing.

**Comment by GitAntinus** [comment]
> No I think the the metadata will be present generated by maven when publishing the lib, but let's not take my word for it and do some testing.

there is no such file in any generated project.

**Comment by PierreBesson** [comment]
So I just added the annotation processor to the jhipster-framework pom and ran the build. It generated a new file : https://gist.github.com/PierreBesson/c90ee89336003f1fa835cafc044750cd
Then I think the IDE will have no problem importing this file from the dependency jar.

**Comment by PierreBesson** [comment]
Oh, do you have IDEA community or IDEA ultimate ?

**Comment by GitAntinus** [comment]
> Oh, do you have IDEA community or IDEA ultimate ?

The ultimate version

**Comment by GitAntinus** [comment]
> Oh, do you have IDEA community or IDEA ultimate ?

Anyway, I wish you are right because your workflow is better.

**Comment by PierreBesson** [comment]
I wish I'm right as well but I'm afraid we might have to go with your solution. I will have a look later.

**Comment by pascalgrimaud** [comment]
I didn't look in details but can't we do the same like Spring Boot ?

**Pull request closed without merging**
