### PR TITLE
add autoincrement id support for oracle

### LINKED ISSUE #2035: Enchancement: update Oracle support to use auto increment
From v 3.4.0 liquibase supports autoincrement of ID for Oracle 12c onwards, hence the current sequence based solution can be removed
https://github.com/liquibase/liquibase/pull/416

### PR DESCRIPTION
**Pull request by deepu105**
add auto increment support for primary key column
remove unique sequence for primary key

fix #2035

### CODE REVIEW

**Comment by AVE-cesar** [comment]
Why didn't you keep the old functionality for older Oracle version ?

I would have add the Oracle 11g and older choice when generating a new application with Jhipster.

**Comment by deepu105** [comment]
Oracle has officially end of lifed older versions and we will not support
such versions

**Comment by AVE-cesar** [comment]
that's crystal clear, thanks

**Comment by cbornet** [comment]
There is probably no point to keep the ```${autoIncrement}``` variable anymore in _added_entity.xml since all DBs set it to true.

**Comment by deepu105** [comment]
But its safer that way in case we decide to add more db support

**Pull request merged**
