### PR TITLE
Fix PublicUserResourceIT#getAllPublicUsers() for WebFlux + Neo4j

### PR DESCRIPTION
**Pull request by mraible**
See https://github.com/jhipster/generator-jhipster/pull/19791#issuecomment-1316049812. 

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] The `ms-mf-ng-consul-oauth2-neo4j` job is passing
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
I discovered that the gateway created in the `ms-mf-ng-consul-oauth2-neo4j` job has a `CacheConfiguration` class that's pretty much empty. When you run the integration tests, many of them fail with the following error:

```
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: 
No qualifying bean of type 'org.springframework.cache.CacheManager' available: 
expected single matching bean but found 2: cacheManager,concurrentMapCacheManager
```

If I remove this class, all tests pass. By all, I mean `npm run ci:backend:test`.

**Comment by mraible** [comment]
@mshima I get the following tests failures when I run `npm test` on this branch locally. Any idea why? 

```
  7331 passing (1m)
  283 pending
  2 failing

  1) Environment builder
       yeoman-test integration
         calls getEnvironment:
       const err = new Error(msg);
              ^

Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/cli/environment-builder.spec.cjs)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  2) jhipster cli with jdl fork
       generates an application with deployments
         should succeed:
       const err = new Error(msg);
              ^

Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/cli/jdl-fork.spec.cjs)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```

I just checked and it happens on the `spring-boot-3.0-m4` and `main` branches too.

**Comment by mshima** [comment]
@mraible maybe recreate the dist dir `rm -rf dist`, `npm run build`

**Comment by mraible** [comment]
@mshima Unfortunately, `rm -rf dist` followed by `npm run build` does not solve the problem.

**Comment by mshima** [comment]
> 7331 passing (1m)

@mraible how many cores are in you processor?
Using an M1 it takes 3m.
So maybe the problem parallelism and you should increase the timeout for those tests.

**Review by mshima — APPROVED** [review]

**Comment by mshima** [comment]
`ms-mf-ng-consul-oauth2-neo4j` test succeed, merging.

**Pull request merged**
