### PR TITLE
Use Spring security default auth form param names

### PR DESCRIPTION
**Pull request by cbornet**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Because:
* [Policy 1](https://www.jhipster.tech/policies/)
* The reactive version currently doesn't support custom param names

### CODE REVIEW

**Comment by cbornet** [comment]
fixed

**Comment by cbornet** [comment]
The VueJS blueprint should also be adapted I guess

**Comment by jdubois** [comment]
Ping @sahbi-ktifa in that case, as this is going in today's release!

**Comment by sahbi-ktifa** [comment]
Thanks for this notification ! I'll add an issue for it on the Vue.js blueprint immediately.

**Pull request merged**
