### PR TITLE
Migration from Swagger Spring MVC to Swagger Springfox 2.0.3

### PR DESCRIPTION
**Pull request by gmarziou**
- no more swagger-ui directory under webapp
- no more swagger dependency in bower.json
- version of the API in application.yml

It fully works with maven + grunt.

With gradle + gulp, it works with gradle (port 8080) however it does not work
with gulp (port 3000) I tried to configure the proxy for /swagger-ui.html nut it does not seem to work.
I'm not even sure it was working previously, I'll try.

Re #1508

### CODE REVIEW

**Comment by gmarziou** [comment]
Thanks I'll try when I'll fix Travis CI failed check.

**Comment by gmarziou** [comment]
gulp is now working.

I encountered issue #1639 which is not related to SpringFox.

**Comment by jdubois** [comment]
Looks good to me!!

**Comment by jdubois** [comment]
@gmarziou it fails with the token-based authentication, so I can't merge it at the moment.
I was expecting this -> btw OAuth2 works, and shouldn't be much different.

**Comment by gmarziou** [comment]
I have never used token-based authentication but let me know if I can help.

**Comment by jdubois** [comment]
@gmarziou can you try to generate with the token-based option?
I'll have a look on Sunday, probably.
I remember there was a trick with Swagger 1, and anyway it shouldn't be much different than OAuth2, so it's doable.

**Comment by gmarziou** [comment]
I generated with the token-based option, I authenticated as admin, when I go to API doc page I get these 401 errors:

~~~~
GET http://127.0.1.1:8080/configuration/security 401 (Unauthorized)
GET http://127.0.1.1:8080/configuration/ui 401 (Unauthorized)
GET http://127.0.1.1:8080/v2/api-docs 401 (Unauthorized)
~~~~

**Comment by jdubois** [comment]
@gmarziou this should be doable, as I'm doing it this in other parts of the apps (for the Gatling scripts, for example).
Anyway, I didn't code the first Swagger integration, and I've tested it and realized it wasn't working either!!!
So that's bad, but your PR didn't break anything that wasn't already broken :-)
-> this is why I am going to merge this

Of course, this should be documented, etc, and as it's a bit late today, I'll merge this tomorrow.
Thanks for the great work!

**Comment by cbornet** [comment]
@jdubois @gmarziou I think swagger ui currently only supports 3-legged Oauth and not the password flow which is used by jhipster.
Even if it were working, the springfox Docket would have to be configured (with securitySchemes and securityContexts)

**Comment by fontanellif** [comment]
@jdubois, If i have an old version of jhipster i have to manually remove the swagger-ui directory under webapp. Right?  

Another question: Using Oauth authentication i see that in the class OAuth2ServerConfiguration probably are missing the following configurations ( but i'm not sure):

``
.antMatchers("/v2/api-docs/**").hasAuthority(AuthoritiesConstants.SUPER_ADMIN)
.antMatchers("/configuration/security").hasAuthority(AuthoritiesConstants.SUPER_ADMIN)
.antMatchers("/configuration/ui").hasAuthority(AuthoritiesConstants.SUPER_ADMIN)
.antMatchers("/swagger-ui.html").hasAuthority(AuthoritiesConstants.SUPER_ADMIN)
``

**Comment by gmarziou** [comment]
Yes this is correct, I must admit that I did not test with oauth for this PR as I have no experience at all with it. To test this, make sure you look at the requests in your browser console.

**Pull request merged**
