### PR TITLE
Fix jhipster regeneration showing prompt without --with-entities and

### PR DESCRIPTION
**Pull request by mshima**
generate the native language the first time.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@pascalgrimaud merging this one, this will fix the errors you found.

**Comment by pascalgrimaud** [comment]
thanks @mshima : yes I needed this, as I'm working since several days on Vue integration.
I'll test tomorrow your fix. Time to sleep for me :-)

**Comment by pascalgrimaud** [comment]
@mshima : there is still an issue. Can you have a look plz ?

1) generate a JHipster project with all default options
2) after generation, relink: `npm link generator-jhipster`
3) relaunch `jhipster`
4) prompt for languages is displayed

```
Application successfully committed to Git from /home/pgrimaud/tmp/33-ngx.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Server application generated successfully.

Run your Spring Boot application:
./mvnw

Client application generated successfully.

Start your Webpack development server with:
 npm start


> jhipster@0.0.1-SNAPSHOT cleanup /home/pgrimaud/tmp/33-ngx
> rimraf target/classes/static/

INFO! Congratulations, JHipster execution is complete!

10:37:23 in ~/tmp/33-ngx on  master took 1m 34s 
➜ npm link generator-jhipster
/home/pgrimaud/tmp/33-ngx/node_modules/generator-jhipster -> /home/pgrimaud/.npm-global/lib/node_modules/generator-jhipster -> /home/pgrimaud/projects/jhipster/generator-jhipster

10:37:27 in ~/tmp/33-ngx on  master 
➜ jhipster        
INFO! Using JHipster version installed globally
INFO! Executing jhipster:app


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.10.0
Application files will be generated in folder: /home/pgrimaud/tmp/33-ngx
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

 ______________________________________________________________________________

  JHipster update available: 6.10.1 (current: 6.10.0)

  Run npm install -g generator-jhipster to update.

 ______________________________________________________________________________

This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...

? Please choose additional languages to install (Press <space> to select, <a> to toggle all, <i> to invert selection)
❯◯ Albanian
 ◯ Arabic (Libya)
 ◯ Armenian
 ◯ Belarusian
 ◯ Bengali
 ◯ Bulgarian
 ◯ Catalan
(Move up and down to reveal more choices)
```

Quick investigation, it's because `this.languagesToApply` is undefined:

```
function askForLanguages() {
    if (this.options.skipPrompts || this.languagesToApply || !this.jhipsterConfig.enableTranslation) {
        return undefined;
    }

    console.log('================>');
    console.log(this.options.skipPrompts);
    console.log(this.languagesToApply);
    console.log(!this.jhipsterConfig.enableTranslation);
```

**Comment by mshima** [comment]
@pascalgrimaud should be fixed in https://github.com/jhipster/generator-jhipster/pull/12061.
Let me know if it still persists.

**Pull request merged**
