### PR TITLE
Fix localized emails for complex locales

### LINKED ISSUE #9494: Email : localized messages not found for Locale with country specified (zh-cn)
##### **Overview of the issue**
When emails are generated for a Locale when the country is specified, the messages are not translated in this locale.
It seems to be due to the "uppercasing" of the country attribute in the locale initialization :

```java
// user.getLangKey = zh-cn
Locale locale = Locale.forLanguageTag(user.getLangKey());
// locale.getLocale() = zh
// locale.getCountry() = CN 
```
##### **Motivation for or Use Case**

99% of my users are Chinese and 2% of them speak English :)

##### **Reproduce the error**

* Generate an app with English as default language and simplified Chinese as additional language
* Change the language of the "user" user account to simplified Chinese
* Reset "user" password
==> The email is in English 

##### **Related issues**
None found

##### **Suggest a Fix**

I finally fixed this simply by renaming my messages_zh_cn.properties to messages_zh_CN.properties.
Maybe the .properties could be generated directly like this.

##### **JHipster Version(s)**

5.8.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": "com.demo.entity",
            "nativeLanguage": "en"
        },
        "jhipsterVersion": "5.8.2",
        "applicationType": "monolith",
        "baseName": "jhipTestIe11",
        "packageName": "com.demo.entity",
        "packageFolder": "com/demo/entity",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "cacheProvider": "no",
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Memory",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
        "clientFramework": "angularX",
        "useSass": false,
        "clientPackageManager": "npm",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "otherModules": [],
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": ["en", "zh-cn"],
        "enableHibernateCache": false,
        "entitySuffix": "",
        "dtoSuffix": "DTO"
    }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v10.15.3

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.12.3

Docker version 18.09.3, build 774a1f4

docker-compose version 1.22.0, build f46880fe

##### **Browsers and Operating System**

Ubuntu 18.04

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by PierreBesson**
With the great help from @olivierdepriester. It was really painful to develop, so I hope we can share the bug bounty 😄.

Fix #9494
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@PierreBesson : FYI, you still have an error. Here the logs:

```
[ERROR] Error: MomentLocalesPlugin: Moment.js doesn’t include a locale you specified: in. Check the plugin’s `localesToKeep` option.
[ERROR] You can see the full list of locales that Moment.js includes in node_modules/moment/locale/
```

This bug fix is really hard !

**Comment by PierreBesson** [comment]
@pascalgrimaud yes I have seen it. Hopefully I know the fix. You have to set the momentLocale to "id" instead of "in".

**Comment by pascalgrimaud** [comment]
@PierreBesson : are you able to do this ? Otherwise, I can try to finish this ticket for you

**Comment by pascalgrimaud** [comment]
@PierreBesson : just to let you know, I pushed 3 new commits to your branch. Hope it will help

**Comment by pascalgrimaud** [comment]
Congrats @PierreBesson and thanks @olivierdepriester for the help
I tested manually and it works well !

**Comment by jdubois** [comment]
@PierreBesson @olivierdepriester this indeed looks like a huge job, don't share the bug bounty, do one bug bounty each (so $200 in total, but we got the money at the moment, so let's spend it when there's some awesome work done)

**Pull request merged**
