### PR TITLE
polish (unused line, npm package-lock.json)

### PR DESCRIPTION
**Pull request by ruddell**
- Removes unused line (the value is set in the line under it)
- Update package-lock.json to reflect current version v5.0.1

Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Those 2 lines are definitely strange, I guess that was originally an error and the author wanted to do both

**Comment by jdubois** [comment]
Good catch by the way @ruddell !

**Comment by ruddell** [comment]
For reference, the extra line was added when we migrated the templates from `_template.js` to `template.js.ejs` https://github.com/jhipster/generator-jhipster/commit/643b42d60a2bfcdd238e20fb748206f92b85d3c4#diff-fddb513f7a2937b33eb1c1f6a71e64a7R2329

**Comment by deepu105** [comment]
@jdubois can you please revert this. May be I'll add a line there saying this is intentional

**Comment by jdubois** [comment]
This is reverted in https://github.com/jhipster/generator-jhipster/commit/6409cbcb1539d6a97a1c2c003dffeff92eda58fd -> @deepu105 can you check what the original idea is, because there's definitely a bug somewhere here

**Comment by deepu105** [comment]
yes I will check.

Thanks & Regards,
Deepu

**Pull request merged**
