### PR TITLE
Fix all known issues about swagger and authentication

### LINKED ISSUE #1697: Swagger UI & Token Based auth
The swagger UI is not working with token based auth. 
The token is not passed to the request.

### LINKED ISSUE #1731: JHipster 2.18 - Swagger Docs V2 - Unauthorized with Oauth2
I recently upgraded to Jhipster 2.18 and started an new effort.  

here is my yo file:

{
  "generator-jhipster": {
    "baseName": "myservices",
    "packageName": "com.myapp.my",
    "packageFolder": "com/myapp/my",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "blahblahblah"
  }
}

When I authenticate with admin/admin and then go to api / swagger docs, ... the resources show up as appropriate, but if I tryout the user resource : GET /api/users

I get Unauthorized.

Request URL
http://127.0.0.1:8080/api/users
Response Body
{
  "timestamp": 1436962673569,
  "status": 401,
  "error": "Unauthorized",
  "message": "Access Denied",
  "path": "/api/users"
}
Response Code
401
Response Headers
{
  "pragma": "no-cache",
  "date": "Wed, 15 Jul 2015 12:17:53 GMT",
  "x-content-type-options": "nosniff",
  "server": "Apache-Coyote/1.1",
  "transfer-encoding": "chunked",
  "content-type": "application/json;charset=UTF-8",
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "x-xss-protection": "1; mode=block",
  "expires": "0"
}

Even though I already logged in.

If I setup the app with session authentication the process works with no problems:

{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useCompass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": false,
    "rememberMeKey": "blahblahblah"
  }
}

So it appears that there might be a oauth security issue with Swagger docs.

Or, is there a security setting I need to change?

I am guessing it might be a yo template issues, ... I noticed the the SecurityConfiguration.java are different, ... the method "protected void configure(HttpSecurity http) throws Exception {" is missing from the Oauth app.

### LINKED ISSUE #1744: HTTP 401 error for api-docs with Token-based authentication
401 : {"timestamp":1437078467982,"status":401,"error":"Unauthorized","message":"Access Denied","path":"/v2/api-docs"}

I don't have this error when I use OAuth2 authentication configuration

### LINKED ISSUE #1772: Invalid CSRF Token
Hi,

I'm testing swagger and all the generated post failed with error 403 and message : 
> "Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'."

I'm using generator-jhipster v2.18.0
Here is my config : 

```
{
  "generator-jhipster": {
    "baseName": "ComicsManAdmin",
    "packageName": "net.ndt.comicsman.admin",
    "packageFolder": "net/ndt/comicsman/admin",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useCompass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "myKey"
  }
}
```

### PR DESCRIPTION
**Pull request by gmarziou**
The swagger spec file at /v2/api-docs is always public access but it's
available only in dev mode.

We have customized the index.html from swagger-ui so that we can pass
oauth2 and xauth token in request headers when using 'Try It Out!' buttons.
We no longer use springfox-ui.

Fixes #1697
Fixes #1731
Fixes #1744
Fixes #1772

### HTTP session auth (mvn + grunt)

- profile dev on port 8080: navbar OK, swagger OK, get and post OK
- profile prod on port 8080: no swagger
- grunt serve on port 3000: CORS error because the host in swagger
  spec is "localhost:8080", I don't think it worked before, I will
  open a new issue.

### HTTP oauth2 auth (gradle + gulp)

- profile dev: navbar OK, swagger OK, get and post OK
- gulp serve on port 9000: failed to login, I will
  open a new issue.

### HTTP xauth auth (mvn + grunt)

- profile dev: navbar OK, swagger OK, get and post OK

### CODE REVIEW

**Comment by atomfrede** [comment]
:+1:

**Comment by deepu105** [comment]
this means no more webjars rite? :+1:

**Comment by gmarziou** [comment]
Yes :)

**Comment by deepu105** [comment]
@gmarziou  does it need any work on gradle part?

**Comment by atomfrede** [comment]
Don't think so.

**Comment by gmarziou** [comment]
I took care of gradle dependencies in this PR

**Comment by atomfrede** [comment]
:+1: Let's merge it

**Pull request merged**
