### PR TITLE
Add modernizer-maven-plugin to detect legacy/deprecated API usage

### PR DESCRIPTION
**Pull request by gzsombor**
and fix one issue in the generated code

Modernizer Maven Plugin detects uses of legacy APIs which modern Java versions supersede - 
More about it here: https://github.com/gaul/modernizer-maven-plugin

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by atomfrede** [comment]
:+1:  Like it!

Can you add a gradle modernizer plugin too? I would suggest this one, but didn't try it myself. https://github.com/andygoossens/gradle-modernizer-plugin

**Comment by gzsombor** [comment]
Yes, I will try to do in a new PR

**Review by atomfrede — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
Should we add some documentation @gzsombor @atomfrede ?

**Comment by atomfrede** [comment]
Yes makes sense, otherwise we will have questions or tickets why something isn't compiling when modernizer complains.

**Pull request merged**
