### PR TITLE
Upgrade proxy-middleware to 0.13.1 for passing csrf cookie correctly.

### LINKED ISSUE #1454: Unable to login : CSRF Validation failed on OAuth2 authentification with gulp serve
**Overview**
When i try to login, on port 9000 (gulp serve), i've this response on token call : 
> {"timestamp":1431102471126,"status":403,"error":"Forbidden","message":"Expected CSRF token not found. Has your session expired?","path":"/oauth/token/"}

No problem on 8080

**JHipster version** : 2.10.1

### PR DESCRIPTION
**Pull request by gmarziou**
Upgrade proxy-middleware to 0.13.1 for passing csrf cookie correctly.

Fixes #1454

### CODE REVIEW

**Comment by atomfrede** [comment]
:+1:

**Comment by deepu105** [comment]
@gmarziou you may want to rebase and squash as current PR has some merge commits as well

**Comment by gmarziou** [comment]
yes I saw that but I'm not sure I can do it once I pushed to my github repo.

**Comment by deepu105** [comment]
I used to do it with a rebase and then by choosing to squash all commits into one, but anyway i guess this will merge without issues even this way

**Comment by gmarziou** [comment]
OK, I'll try to avoid this in next PR.

**Pull request merged**
