### PR TITLE
Modify Readme Page with Sponsor Logos Horizontally Aligned

### PR DESCRIPTION
**Pull request by SudharakaP**
The logos in our README.md file seems a bit space consuming with their vertical stacking. I re-formatted it to contain in a html table. 

To see how it looks --> https://github.com/SudharakaP/generator-jhipster/tree/modify-readme-page-with-sponsor-logo-alignment

I hope this looks better. :smile: 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
it looks better on computer but not on phone. Do you think it's possible to have both ?

**Comment by SudharakaP** [comment]
> 
> 
> it looks better on computer but not on phone. Do you think it's possible to have both ?

@pascalgrimaud : Good catch. Yes, I think it should be possible; I've put absolute width measurements (pixels). Instead I have to convert them into relative measurements I think. Will do that in the evening. 😄

**Comment by SudharakaP** [comment]
@pascalgrimaud : Okay, I've modified it; try it out now and let me know if it's better. I can't dynamically change the grid itself since I don't think the `README.md` file supports libraries like bootstrap. But I've fixed the grid to 5 columns which seems okay to me. :smile:

**Comment by pascalgrimaud** [comment]
thanks, it's better now :)

**Pull request merged**
