### PR TITLE
Allow entities to be organized by packages.

### PR DESCRIPTION
**Pull request by mshima**
This PR allows entities to be organized by packages.

```
@EntityPackage(custom)
entity CustomPackageChild
```

Will generate every CustomPackageChild file at packageName.custom package.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I'd like to rename domain to something else. As it will confuse people who uses real hexagonal architecture, and this approach doesn't respect the different rules.

Maybe `@EntityPackage(custom)` ?

**Comment by mshima** [comment]
> Maybe `@EntityPackage(custom)` ?

Looks good

**Comment by pascalgrimaud** [comment]
Adding a bounty on this, as it's a lot of work

**Comment by mraible** [comment]
I tried this today on a WebFlux project with the following JDL:

```
application {
  config {
    baseName blog,
    reactive true,
    applicationType monolith
    authenticationType oauth2
    packageName com.jhipster.demo.blog
    prodDatabaseType mysql
    cacheProvider ehcache
    buildTool maven
    clientFramework angular
    testFrameworks [cypress]
  }
  entities *
}

@EntityPackage(blog)
entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

@EntityPackage(post)
entity Post {
  title String required
  content TextBlob required
  date Instant required
}

@EntityPackage(tag)
entity Tag {
  name String required minlength(2)
}

relationship ManyToOne {
  Blog{user(login)} to User
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{entry}
}

paginate Post, Tag with infinite-scroll

```

It results in numerous compilation errors:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/repository/rowmapper/BlogRowMapper.java:[4,43] package com.jhipster.demo.blog.blog.service does not exist
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/repository/rowmapper/BlogRowMapper.java:[15,19] cannot find symbol
  symbol:   class ColumnConverter
  location: class com.jhipster.demo.blog.blog.repository.rowmapper.BlogRowMapper
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/repository/rowmapper/BlogRowMapper.java:[17,26] cannot find symbol
  symbol:   class ColumnConverter
  location: class com.jhipster.demo.blog.blog.repository.rowmapper.BlogRowMapper
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/domain/Blog.java:[33,13] cannot find symbol
  symbol:   class User
  location: class com.jhipster.demo.blog.blog.domain.Blog
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/domain/Blog.java:[79,12] cannot find symbol
  symbol:   class User
  location: class com.jhipster.demo.blog.blog.domain.Blog
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/domain/Blog.java:[83,25] cannot find symbol
  symbol:   class User
  location: class com.jhipster.demo.blog.blog.domain.Blog
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/domain/Blog.java:[88,22] cannot find symbol
  symbol:   class User
  location: class com.jhipster.demo.blog.blog.domain.Blog
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/domain/Tag.java:[32,17] cannot find symbol
  symbol:   class Post
  location: class com.jhipster.demo.blog.tag.domain.Tag
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/domain/Tag.java:[62,16] cannot find symbol
  symbol:   class Post
  location: class com.jhipster.demo.blog.tag.domain.Tag
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/domain/Tag.java:[66,32] cannot find symbol
  symbol:   class Post
  location: class com.jhipster.demo.blog.tag.domain.Tag
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/domain/Tag.java:[76,28] cannot find symbol
  symbol:   class Post
  location: class com.jhipster.demo.blog.tag.domain.Tag
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/domain/Tag.java:[81,25] cannot find symbol
  symbol:   class Post
  location: class com.jhipster.demo.blog.tag.domain.Tag
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/domain/Tag.java:[87,28] cannot find symbol
  symbol:   class Post
  location: class com.jhipster.demo.blog.tag.domain.Tag
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[39,13] cannot find symbol
  symbol:   class Blog
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[43,17] cannot find symbol
  symbol:   class Tag
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[102,12] cannot find symbol
  symbol:   class Blog
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[106,25] cannot find symbol
  symbol:   class Blog
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[111,22] cannot find symbol
  symbol:   class Blog
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[116,16] cannot find symbol
  symbol:   class Tag
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[120,29] cannot find symbol
  symbol:   class Tag
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[124,26] cannot find symbol
  symbol:   class Tag
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[129,24] cannot find symbol
  symbol:   class Tag
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/domain/Post.java:[135,27] cannot find symbol
  symbol:   class Tag
  location: class com.jhipster.demo.blog.post.domain.Post
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/PostRepositoryInternalImpl.java:[7,42] cannot find symbol
  symbol:   class Tag
  location: package com.jhipster.demo.blog.post.domain
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/PostRepositoryInternalImpl.java:[8,56] cannot find symbol
  symbol:   class BlogRowMapper
  location: package com.jhipster.demo.blog.post.repository.rowmapper
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/PostRepositoryInternalImpl.java:[10,43] package com.jhipster.demo.blog.post.service does not exist
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/PostRepositoryInternalImpl.java:[11,57] package com.jhipster.demo.blog.post.service.EntityManager does not exist
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/PostRepositoryInternalImpl.java:[42,19] cannot find symbol
  symbol:   class EntityManager
  location: class com.jhipster.demo.blog.post.repository.PostRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/PostRepositoryInternalImpl.java:[44,19] cannot find symbol
  symbol:   class BlogRowMapper
  location: class com.jhipster.demo.blog.post.repository.PostRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/rowmapper/PostRowMapper.java:[4,43] package com.jhipster.demo.blog.post.service does not exist
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/PostRepositoryInternalImpl.java:[50,39] package EntityManager does not exist
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/PostRepositoryInternalImpl.java:[54,9] cannot find symbol
  symbol:   class EntityManager
  location: class com.jhipster.demo.blog.post.repository.PostRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/PostRepositoryInternalImpl.java:[55,9] cannot find symbol
  symbol:   class BlogRowMapper
  location: class com.jhipster.demo.blog.post.repository.PostRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/rowmapper/PostRowMapper.java:[16,19] cannot find symbol
  symbol:   class ColumnConverter
  location: class com.jhipster.demo.blog.post.repository.rowmapper.PostRowMapper
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/post/repository/rowmapper/PostRowMapper.java:[18,26] cannot find symbol
  symbol:   class ColumnConverter
  location: class com.jhipster.demo.blog.post.repository.rowmapper.PostRowMapper
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/repository/BlogRepositoryInternalImpl.java:[8,56] cannot find symbol
  symbol:   class UserRowMapper
  location: package com.jhipster.demo.blog.blog.repository.rowmapper
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/repository/BlogRepositoryInternalImpl.java:[9,43] package com.jhipster.demo.blog.blog.service does not exist
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/repository/BlogRepositoryInternalImpl.java:[39,19] cannot find symbol
  symbol:   class EntityManager
  location: class com.jhipster.demo.blog.blog.repository.BlogRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/repository/BlogRepositoryInternalImpl.java:[41,19] cannot find symbol
  symbol:   class UserRowMapper
  location: class com.jhipster.demo.blog.blog.repository.BlogRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/repository/BlogRepositoryInternalImpl.java:[49,9] cannot find symbol
  symbol:   class EntityManager
  location: class com.jhipster.demo.blog.blog.repository.BlogRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/blog/repository/BlogRepositoryInternalImpl.java:[50,9] cannot find symbol
  symbol:   class UserRowMapper
  location: class com.jhipster.demo.blog.blog.repository.BlogRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/repository/TagRepositoryInternalImpl.java:[8,42] package com.jhipster.demo.blog.tag.service does not exist
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/repository/TagRepositoryInternalImpl.java:[38,19] cannot find symbol
  symbol:   class EntityManager
  location: class com.jhipster.demo.blog.tag.repository.TagRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/repository/rowmapper/TagRowMapper.java:[4,42] package com.jhipster.demo.blog.tag.service does not exist
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/repository/TagRepositoryInternalImpl.java:[44,68] cannot find symbol
  symbol:   class EntityManager
  location: class com.jhipster.demo.blog.tag.repository.TagRepositoryInternalImpl
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/repository/rowmapper/TagRowMapper.java:[15,19] cannot find symbol
  symbol:   class ColumnConverter
  location: class com.jhipster.demo.blog.tag.repository.rowmapper.TagRowMapper
[ERROR] /Users/mraible/webflux/src/main/java/com/jhipster/demo/blog/tag/repository/rowmapper/TagRowMapper.java:[17,25] cannot find symbol
  symbol:   class ColumnConverter
  location: class com.jhipster.demo.blog.tag.repository.rowmapper.TagRowMapper
[INFO] 47 errors
[INFO] -------------------------------------------------------------
```

**Comment by mshima** [comment]
@mraible relationships are pending, they need to be at the same package for now.
I wanted to get base support merged before going forward.

**Comment by JulioJu** [comment]
Hi, 

There is no documentation on this feature into https://www.jhipster.tech/jdl/ .

**Comment by zeal607** [comment]
Organizing by packages is Great.
However, it seems that only one-level package structure is supported at present.
com.mycompany.myapp.aop
com.mycompany.myapp.config
com.mycompany.myapp.domain
com.mycompany.myapp.domain
com.mycompany.myapp.repository
com.mycompany.myapp.web
com.mycompany.myapp.package1.domain
com.mycompany.myapp.package1.repository
com.mycompany.myapp.package1.service
com.mycompany.myapp.package1.web
____________________________________________

**Comment by zeal607** [comment]
Organizing by packages is Great.
However, it seems that only one-level package structure is supported at present.
com.mycompany.myapp.aop
com.mycompany.myapp.config
com.mycompany.myapp.domain
com.mycompany.myapp.domain
com.mycompany.myapp.repository
com.mycompany.myapp.web
com.mycompany.myapp.package1.domain
com.mycompany.myapp.package1.repository
com.mycompany.myapp.package1.service
com.mycompany.myapp.package1.web
____________________________________________
This causes package1 and aop/config/domain/repository  to be at the same level

**Comment by mshima** [comment]
Two level packages are supported.
See https://github.com/jhipster/generator-jhipster/blob/main/test-integration/samples/jdl-entities/custom-domain.jdl

**Pull request merged**
