### PR TITLE
Updated .gitignore with Elasticsearch data directory

### PR DESCRIPTION
**Pull request by bonhamcm**

### CODE REVIEW

**Comment by jdubois** [comment]
What is "Elasticache"? Is it "Elasticsearch" mispelt?

**Comment by bonhamcm** [comment]
Yes sorry I meant Elastisearch.

**Comment by jdubois** [comment]
OK, but in the application-dev.yml file we configure the data folder to be `target/elasticsearch/data`-> this is on purpose, so your .gitignore is not needed

**Comment by bonhamcm** [comment]
Sorry, apparently the root level data directory was left over from an older JHipster version.

**Comment by jdubois** [comment]
@bonhamcm yes, this has changed from the very first release, sorry

**Comment by andidev** [comment]
I can confirm that running `mvn clean install` after a fresh install creates the elastic search data dir.

@jdubois 
Maybe the tests are causing this? At least the test application.yml does not contain the elasticsearch data dir configuaration you mention.

**Comment by bonhamcm** [comment]
@andidev you are correct that the root-level ```data``` directory is created by the tests. I created https://github.com/jhipster/generator-jhipster/pull/1738 to add the Elasticsearch properties to the test ```_application.yml``` file.

**Comment by andidev** [comment]
Great!

**Pull request closed without merging**
