### PR TITLE
add RESERVED_WORDS_JHIPSTER to avoid entity name that can break the project

### PR DESCRIPTION
**Pull request by chamot1111**
##### **Overview of the issue**

When a user generate an entity "account", the jhipster project file AccountRessource.java is modified and the project is not working anymore.

##### Propose fix

I just add RESERVED_WORDS_JHIPSTER. For now, it's contains only 'ACCOUNT' but I suppose that the problem can happen with AuditRessource.java too.

### CODE REVIEW

**Comment by deepu105** [comment]
We did away with the reserved words by using the JHI suffix for stuff that JHipster generates so we could do that here as well

**Comment by chamot1111** [comment]
You mean that 'AccountRessource.java' should be 'JHIAccountRessource.java'?

**Comment by jdubois** [comment]
I agree with @chamot1111 - let's do a list of JHipster reserved keywords

**Comment by deepu105** [comment]
ok lets do it then

**Pull request merged**
