### PR TITLE
remove duplicated java source and target in pom

### LINKED ISSUE #10279: Choose between properties and plugin configuration for maven-compiler-plugin
##### **Overview of the feature request**
According to https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html we could configure maven-compiler-plugin by 2 ways:

* By setting properties:
 ```
<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
```

* By setting the configuration plugin itself:
```
     <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
```

In JHipster we have both solutions implemented. We could remove one of them.

IMHO I would remove the configuration in plugin declaration and only keep properties since they are easy to read and close to our `java.version` property.

/discuss
##### **Motivation for or Use Case**
Simplify the pom.xml.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by fdelbrayelle**
Fix #10279

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by avdev4j** [comment]
It's strange because the @DanielFran changes seems good, we are loading java version from compiler which load it from the compiler plugin which load it from our `maven.compiler.source` property (which has the `java.version` value).

Maybe the properties are not loaded properly when doing a javadoc:javadoc ?

**Comment by DanielFran** [comment]
I try do the the same in jhipster bom project and found also issues with Java 11. I believe there is a bug with javadoc plugin version that is fixed on Java >11.
Will try to found it again...
So for now it is KO.

**Comment by avdev4j** [comment]
Ok, it's sad :'(.

Nevermind I close the issue and the PR and we could try later when version  will be > 11.

Sry @fdelbrayelle

**Comment by DanielFran** [comment]
For reference:
- https://bugs.openjdk.java.net/browse/JDK-8212233
- https://issues.apache.org/jira/browse/MJAVADOC-562
- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8212233
- http://mail-archives.apache.org/mod_mbox/maven-issues/201907.mbox/%3CJIRA.13244266.1562836330000.857.1562837100113@Atlassian.JIRA%3E

**Comment by avdev4j** [comment]
As usual, Daniel 👍

**Pull request closed without merging**
