### PR TITLE
Use jhipster-dependencies BOM

### PR DESCRIPTION
**Pull request by erikkemperman**
See https://github.com/jhipster/generator-jhipster/issues/6061

So with this PR, almost all (*) dependencies are managed by the new `jhipster-dependencies` BOM, and unified across Maven and Gradle. There's one extra commit that can be discarded once 0.0.4 of the BOM is released with upgraded Cassandra driver artifacts.

(*) one exception are the inner deps within plugin configuration.

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
I would like to merge this after #6435 and doing JHipster v4.10.0 - otherwise the release would be too big

**Comment by erikkemperman** [comment]
Fair enough! Perhaps in the mean time we could discuss the merits of linking the releases of jhipster server library and the dependencies BOM, possibly putting them in a single repository so the maven-release-plugin can work as intended.

I think this might be a good idea because now there is an odd co-dependency: jhipster-dependencies manages the version of jhipster (for consumption by the generator and the registry) but the server lib itself also uses the BOM so all the versions will be automagically aligned.

Thoughts?

Oh and also I would very much appreciate if folks could try if this PR doesn't accidentally break their use cases (even though the tests all pass).

Thanks!

**Comment by atomfrede** [comment]
Great work. I will try to test it during the weekend somehow.

**Comment by erikkemperman** [comment]
@atomfrede thanks, that would be much appreciated!

**Comment by erikkemperman** [comment]
FYI Rebased to resolve merge conflicts, and bumped jhipster-dependencies to 0.0.5.

**Comment by erikkemperman** [comment]
Rebased to resolve conflicts with current master.

**Comment by jdubois** [comment]
OK let's do this, I'm reviewing this and merging ASAP

**Comment by erikkemperman** [comment]
@jdubois Great! FYI though, it needs to be rebased and due to recent merges to master branch it needs a new jhipster-dependencies in order to have no regression. See https://github.com/jhipster/jhipster-dependencies/pull/11. If you could look at that and do merge/release if you approve it, then I would be happy to resolve the merge conflicts on this PR!

**Comment by jdubois** [comment]
@erikkemperman this is going to be OK - however I must admit I'm a bit disappointed, we only gain 20 lines in the `pom.xml`, which isn't a lot, so this looks like a lot of work without a big win in the end.

**Comment by erikkemperman** [comment]
@jdubois Thanks for merging, but I was still resolving conflicts and bumping jhipster-dependencies to 0.0.7...

**Comment by erikkemperman** [comment]
Also, the big win here isn't line count, in my humble opinion, but:

- Separate version management so upgrades won't (easily) conflict with user's generated apps (it will be just the line with jhipster-dependencies.version that changes)
- Automatically uniform versions across Maven and Gradle (because the gradle plugin just reads the new POM)
- No more parent POM, leaving users free to attach their own corporate parent.

**Pull request merged**
