### PR TITLE
Bump angular to v15

### PR DESCRIPTION
**Pull request by mshima**
- Convert every component to standalone, except main.
- Use default export to simplify lazy loading.
- Build microfrontends using esm.
- Use a lib to lazy load microfrontends.

Fixes https://github.com/jhipster/generator-jhipster/issues/20385.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by qmonmert — APPROVED** [review]
LGTM

**Comment by Tcharl** [comment]
Too late, but may deserve a bounty @jdubois ? @deepu105 ?

**Comment by mshima** [comment]
@Tcharl there is a bounty at the issue.

**Comment by Tcharl** [comment]
Well deserved, congrats!

**Pull request merged**
