### PR TITLE
Ng2: Logs page refactoring

### PR DESCRIPTION
**Pull request by wmarques**
Here is an example of a total refactoring of a page with a component, a service, a template and a model. It's a simple one with some basic functionalities (search input, order by..).
I tried to follow as much as possible the style guide to do this.

### CODE REVIEW

**Comment by wmarques** [comment]
Just added a custom XSRF token cookie/header as we do in Angular 1 to fix security issues (403 errors) when doing request with the Ng2 HTTP provider

**Comment by deepu105** [comment]
@wmarques can you take a look at the merge conflict please?

**Comment by wmarques** [comment]
Yep I'm checking this

**Comment by wmarques** [comment]
Seems fine now

**Pull request merged**
