### PR TITLE
Fix package netflix.feign renamed to openfeign

### PR DESCRIPTION
**Pull request by pascalgrimaud**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Oh how did you find that? Looks like we don't test this part at all!!
I know you are correct, and that's not tested by Travis anyway, so I'm merging

**Comment by pascalgrimaud** [comment]
I'm testing my branch with jhipster-registry in Spring Boot 2 + OAuth2 configuration
In fact, I forgoet to add test with OAuth2 to hipster-labs builds !

**Comment by jdubois** [comment]
OK, I just had a look at migrating the JHipster Registry to Spring Boot 2, there's quite a lot of work -> are you doing it? Because there's no interest that both of us do it!
If you do it, you might need a specific release of jhipster-dependencies - just ask!

**Comment by pascalgrimaud** [comment]
@jdubois : you can expect a PR in few minutes for jhipster-registry. There are still some issues, but it's working!

**Comment by jdubois** [comment]
Awesome !! Then I'm going to bed :-)

**Comment by pascalgrimaud** [comment]
Done here: https://github.com/jhipster/jhipster-registry/pull/244
Good night :)

**Comment by jdubois** [comment]
Thanks!!

**Pull request merged**
