### PR TITLE
Fix missing parameter when skipping server

### LINKED ISSUE #8002: App generation with --skip-server fails with "TypeError: Cannot read property 'toLowerCase' of undefined"
##### **Overview of the issue**

i am trying to generate a jhipster app with "--skip-server" option (server was generated separately). but the generator fails with a TypeError as shown below:

```
D:\data\projects\xxxxxx\gw\client>jhipster app --skip-server --db xxxxxx --jhi-prefix zzz --npm --auth uaa
Using JHipster version installed globally
Executing jhipster:app
Options: skipServer: true, db: xxxxxx , jhiPrefix: zzz, npm: true, auth: uaa, skip-server: true, jhi-prefix: zzz

Welcome to JHipster v5.1.0

? What is the base name of your application? xxxxxx
? Which *Framework* would you like to use for the client? React
? Would you like to enable *SASS* support using the LibSass stylesheet preprocessor? No
? Would you like to enable internationalization support? No
? Besides JUnit and Jest, which testing frameworks would you like to use? Protractor
? Would you like to install other generators from the JHipster Marketplace? No
events.js:165
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at module.exports.getSharedConfigOptions (C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\generators\client\index.js:382:94)
    at Object.<anonymous> (C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\yyyyyy\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:406:18)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```
##### **Motivation for or Use Case**

i am unable to generate an app with --skip-server option

##### **Reproduce the error**

see above
##### **Related issues**

search did not reveal any similar issues

##### **JHipster Version(s)**

JHipster 5.1.0
##### **JHipster configuration**

.yo-rc.json was not generated due to above bug.

jhipster info
Using JHipster version installed globally
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
D:\data\projects\xxxxxxx\gw\client
`-- (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

git version 2.16.1.windows.1

node: v9.8.0
npm: 5.6.0

yeoman: 2.0.4

yarn: 1.7.0

Docker version 18.01.0-ce, build 03596f51b1

docker-compose version 1.18.0, build 8dd22a9

Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows 10. 
- [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by agaspardcilia**
fix #8002

`uaaBaseName` wasn't passed to the subgen when skipping the server.

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
I think react build failure is due to #8060

**Comment by deepu105** [comment]
@nagarajasr will you be able to test this?

**Comment by ruddell** [comment]
This fixes it for when you pass `--uaa-base-name` but we still need to display an error if you don't include that parameter. 

    jhipster app --skip-server --auth uaa --db mysql
    # generator crashes with unhelpful error message
    TypeError: Cannot read property 'toLowerCase' of undefined
        at module.exports.getSharedConfigOptions (/Users/ruddell/generator-jhipster/generators/client/index.js:382:94)


    jhipster app --skip-server --auth uaa --db mysql --uaa-base-name uaa
    # generates project correctly

**Comment by agaspardcilia** [comment]
You're right, I'll take care of this.

**Comment by nagarajasr** [comment]
i will test it and report back. thanks!

**Comment by nagarajasr** [comment]
tested and added my comments on the issue

**Comment by agaspardcilia** [comment]
I've moved the error to be displayed sooner and be more consistent with other error messages.

**Comment by deepu105** [comment]
@agaspardcilia you need to resubmit the bounty claim with a valid invoice as per OC guidelines

**Pull request merged**
