### PR TITLE
Travis: yarn

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/4317
Improvements:
- use yarn instead of npm to speedup the build
- use properly caches
- put install scripts directly into travis.yml to see precisely duration
- move entities before generating project using the flag --with-entities
- remove set -ev to reduce logs file

Please, don't merge it. Let me do this:
- I need to look the logs for every builds
- I need to clear cache on Travis before merging.
- I need to compare the time (before with npm / after with yarn)

Just say if it looks good to you

### CODE REVIEW

**Comment by jdubois** [comment]
Looks good to me! This will go even faster when me migrate to Angular 2 and remove Bower, as everything will go through Yarn.

**Comment by pascalgrimaud** [comment]
Yes, but don't expect too much improvements.
By using Travis cache with npm, our builds were already optimized...

**Comment by jdubois** [comment]
Congrats, the time was 36 minutes, much less than usual (always more than 40 minutes). And that's just the beginning, as Yarn wasn't cached, and as we still have Bower!
Anyway, the most important improvement is for us: this is so much faster for my own work!

**Comment by pascalgrimaud** [comment]
Same for me, on my computer, `jhyarn` rocks!!! :rocket:

**Comment by cbornet** [comment]
As for the travis time improvement, let's see in the long run. See https://travis-ci.org/jhipster/generator-jhipster/builds/177927467, it was already 36 mn...

**Comment by pascalgrimaud** [comment]
What I did:
- I cleaned all cache on Travis
- I realize that I commit yarn.lock although it's in .gitignore (I did it during my tests) -> I don't know what to do here:
    - keep in .gitignore and delete this file
    - or remove from .gitignore

**Comment by deepu105** [comment]
What does yarn recomend. IMO i guess we can put it in git


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
After day 1:
- Before, with npm:
    - elapsed time: 35min to 39min
    - total time: 2h16 to 2h24
- Now with yarn:
    - elapsed time: 29min to 32min
    - total time: 1h45 to 1h55

So for me, I'm convinced that Travis has been improved!

**Pull request merged**
