### PR TITLE
Add hystrix configuration commented for microservices

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/4810

### CODE REVIEW

**Comment by PierreBesson** [comment]
I don't understand how the zuul properties would be useful for microservices as I thought zuul was not embedded in microservices, only the gateway.

**Comment by pascalgrimaud** [comment]
Oh you're right @PierreBesson!
Only the part on Hystrix should be enough so

**Comment by gmarziou** [comment]
isn't ribbon being used also on a microservice calling another one?

**Comment by pascalgrimaud** [comment]
You make be doubt!
I need to check the config we use on my project :)

**Comment by pascalgrimaud** [comment]
The config with hystrix should be enough.

But remember the Policy 1: technologies used by JHipster have their default configuration used as much as possible, I should not put this additional config for microservices as it's very specific -> only when there are communication between microservices. There are already some tickets about that, so the information can easily be found.

Let's close this!

**Comment by PierreBesson** [comment]
@pascalgrimmaud, but maybe we should still leave a commented out hystrix property with a link to the docs for discovery purposes...

**Comment by xetys** [comment]
+1 to providing more docs on this

**Pull request merged**
