### PR TITLE
Upgrade to angular 1.3.15

### PR DESCRIPTION
**Pull request by gzsombor**

### CODE REVIEW

**Comment by andidev** [comment]
Is there a reason why angular was upgraded to 1.3.15 in the [resolutions part of bower.json](https://github.com/gzsombor/generator-jhipster/blob/9accdc6c4918302022fe7aa769fcc50c65d8dcd6/app/templates/_bower.json#L33-L34) and kept at 1.3.11 [amongst included dependencies](https://github.com/gzsombor/generator-jhipster/blob/9accdc6c4918302022fe7aa769fcc50c65d8dcd6/app/templates/_bower.json#L15)?

Also the angular-i18n version seems to be kept at 1.3.11. Is there a reason for this as well?

**Comment by jdubois** [comment]
I didn't see this, so for me there is no reason for this -> @andidev a PR is welcome

**Comment by andidev** [comment]
@jdubois  Done!

**Comment by gzsombor** [comment]
Sorry, my bad ! It was a result of failed cherry-pick.

**Pull request merged**
