### PR TITLE
add `relationshipSide`concept to jdl relationships

### PR DESCRIPTION
**Pull request by mshima**
- replace `ownerSide` with `relationshipSide` at jdl. `ownerSide` is dependent on databaseType.
- recreate `ownerSide` in entity preparation.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by wangxinxx** [comment]
I think this part of the content is getting more and more complicated. Concepts such as ownerSide/relationshipSide/from/to/source/destination all appear in related content, bringing more concepts to blueprint creators.

**Comment by mshima** [comment]
> I think this part of the content is getting more and more complicated. Concepts such as ownerSide/relationshipSide/from/to/source/destination all appear in related content, bringing more concepts to blueprint creators.

The purpose is to be more consistent.
- from/to is part of jdl model and not passed to generators.
- don't know what source/destination you are talking about.
- left/right will allow a file with jdl relationships to be recreated just like the original. Currently some relationships are inverted.
- ownerSide is been removed from jdl parser. Recreated at generators for backward compatibility with existing templates.

**Comment by wangxinxx** [comment]
OK.

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
@mshima we need to document those jdl changes

**Comment by mshima** [comment]
@DanielFran there is no change to the end user. I don’t think there is documentation to be changed.

**Pull request merged**
