### PR TITLE
Improve the TLS grade

### PR DESCRIPTION
**Pull request by Akuka**
Docs: https://github.com/jhipster/jhipster.github.io/pull/661

Reference: https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices#23-use-secure-cipher-suites

The ciphers suite enforce the security by deactivating some old and deprecated SSL cipher, this list was tested against SSL Labs (https://www.ssllabs.com/ssltest/) and got grade of A+

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
The reason I add those properties in my previous PR on the tls profile (#8138 ) was that this was actually not working in local development with the generated test keystore.
Can you check that it currently works at least in Chrome and Firefox ?

**Comment by PierreBesson** [comment]
Just needs some testing to make sure it works with the local dev keystore that we create after generation.

**Comment by PierreBesson** [comment]
Well I have tested it and it works for me.

**Comment by jdubois** [comment]
Awesome, thanks @Akuka @PierreBesson !

**Pull request merged**
