### PR TITLE
Health page - Support of composite health indicators

### LINKED ISSUE #1109: Health page - Support of composite health indicators
I am using a CompositeHealthIndicator to present health for sub systems. However, the health page does not currently show status for sub systems. 

I would also like add a new column left of the exception column to show any details provided in the health information. If the health contains any additional information, an information icon is show. If clicked upon, a popup (similar to exceptions) will show the additional information.

I would like to fix the the issues mentioned above. I am preparing to provide a pull request if all is ok with you.

### PR DESCRIPTION
**Pull request by hirro**
Health page now supports display of submodules.
Parent modules are only displayed if it contains additional attributes
or an error.
Health page now contains an extra column to display additional
attributes under the details column.
New unit tests added to health. All tests run. Test project generated and verified.

Fix #1109

### CODE REVIEW

**Comment by hirro** [comment]
- "This is too simple to write a unit test for".
Sorry for that, I will fix it during the evening and add the matching tests. No other comments?

**Comment by hirro** [comment]
I have now fixed the bug  pointed out by jmangas

**Comment by jdubois** [comment]
I just tested your PR and the images (the eyes) are not centered, the pop up are not readable... Have a look at the screenshot attached
capture d ecran 2015-02-11 16 48 51
So I can't merge this at the moment

**Comment by hirro** [comment]
Hi,

I will take a look at it in different browsers. I tested it using Chrome
(OSX).

Before I start with the fix, is there any particular reason
http://angular-ui.github.io/bootstrap/ is not used? Or would that be an
option apply the modal from that in the health page?



2015-02-11 16:51 GMT+01:00 Julien Dubois <notifications@github.com>:

**Comment by hirro** [comment]
Hi Julien,
I reproduced and found the issue, it is now tested in OSX Firefox, Chrome and Safari.

**Comment by jdubois** [comment]
It's getting better but it's not perfect yet!

- Instead of having a "details" and a "stacktrace" columns, which are mutually exclusive, I'd rather have everything in the same "details" column (if there's an error, the details is the stacktrace, that looks logical to me)
- Have a look at the following screenshot, I can click on 2 details, and they overlap: clicking on a new "detail" should close the existing one

capture d ecran 2015-02-12 10 29 03

**Comment by hirro** [comment]
Hi Julien,

I can fix that, either using existing CSS or with help from ui-bootstrap.

I would prefer to do it using ui-bootstrap but that required pulling in a
dependency. If you want to read more about it this link provides
information http://angular-ui.github.io/bootstrap/.



2015-02-12 10:32 GMT+01:00 Julien Dubois <notifications@github.com>:

**Comment by jdubois** [comment]
I don't want another dependency -> we should not include another dependency for everyone, just for a single admin screen

**Comment by hirro** [comment]
It now looks like this:
# Health page
image

## Information
image
## Errors
image

I have not done anything with the translations.

**Comment by jdubois** [comment]
Yes it looks better, but we now have a stacktrace when you open the developer tools (see screenshot), so you still have some errors to solve!
capture d ecran 2015-02-18 11 19 34 2

**Comment by hirro** [comment]
The error is fixed. Also fixes spelling error, currentHealth was misspelled.

**Comment by hirro** [comment]
Just checking in on the PR. Since this is my first PR I am a bit confused about the next expected action? Who is supposed to fix the merge conflicts?

**Comment by jdubois** [comment]
Hi, no problem: anybody can fix this, in fact

- if you do it, then you will update your PR and push your code again, and of course that would make my job easier
- I could do it, in that case I would merge your PR and then solve the conflicts

**Comment by hirro** [comment]
I have now merged the conflicts. The PR is now be ready for insertion. Let me know if you have any questions.

**Comment by jdubois** [comment]
Great work! I'm merging this now!

**Pull request merged**
