### PR TITLE
add a default logo

### PR DESCRIPTION
**Pull request by deepu105**
add a default logo in navbar, so that users can just replace it with their own logo.

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois please merge if you are ok with this

**Comment by jdubois** [comment]
It looks like the same code than in the JHipster Registry -> yes OK for the idea, but I just changed it in the Registry, as it wasn't displaying correctly, so I need to test before

**Comment by deepu105** [comment]
what happend in registry, it was working when I tested!

**Comment by deepu105** [comment]
Ok you moved the logo to the menu, but I dont think thats the proper place as it would be hidden in mobile, I would rather have the logo and App name in its old location and just remove the home menu instead.

**Comment by deepu105** [comment]
This is what I meant
image

This looks much better and prominent IMO
image

**Comment by deepu105** [comment]
and in desktop view 
image

**Comment by jdubois** [comment]
Agreed, but on my screen (with Chrome), it was displaying like this:
capture d ecran 2016-05-04 12 24 48

**Comment by deepu105** [comment]
Oh thats normal even without the logo image, since the menu items are more there is no space so bootstarp kicks it down. If you remove home, it would be ok in your screen, but in smaller screen it will look that way and IMO thats normal bootstrap

**Comment by deepu105** [comment]
may be we should try to group few menu items together. also we can remove the text for signout, the icon is kind of standard

**Comment by atomfrede** [comment]
Maybe just remove ``Jhipster``, if we have the logo in the navbar we could just have ``Registry v1.1.0`` there. I think the Java Hipster is already well known :)

**Comment by deepu105** [comment]
Yup agree it will be cooler :)
also remove home menu.
remove signout text, i guess icon would be sufficient

so together it will use less space and should look ok in your display. Ill
later add some responsive util classes to limit breakpoints

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
OK I'm trusting you on this -> and this needs to be copied to the Registry too (or start with the Registry, I find it easier)

**Comment by deepu105** [comment]
This PR is good to go :+1:

**Comment by deepu105** [comment]
@jdubois can i merge this?

**Comment by jdubois** [comment]
Yes

**Pull request merged**
