### PR TITLE
AWS Elastic-beanstalk role creation for new environments

### LINKED ISSUE #7086: Failed to deploy on AWS Elastic Beanstalk
##### **Failed to deploy on AWS Elastic Beanstalk**

When deploying on aws using command 

```
jhipster aws
```

An error occurs `ERROR! Resource is not in the state dBInstanceAvailable`. Here's a stack trace.

It seems like the issues is at [this line](https://github.com/jhipster/generator-jhipster/blob/4b8e64e95b2354577539a057c056734bfcdad984/generators/aws/index.js#L198) where the DB URL is created.

```
....

Create S3 bucket
Bucket myappwebapp already exists

Upload WAR to S3
War uploaded successful

Create database
Database myappwebapp already exists

Waiting for database (This may take several minutes)
/home/mohataher/dev/web_projects/myappwebapp/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: ERROR! Resource is not in the state dBInstanceAvailable
    at Environment.error (/home/mohataher/dev/web_projects/myappwebapp/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/mohataher/dev/web_projects/myappwebapp/node_modules/generator-jhipster/generators/generator-base.js:2064:18)
    at rds.createDatabaseUrl (/home/mohataher/dev/web_projects/myappwebapp/node_modules/generator-jhipster/generators/aws/index.js:200:30)
    at Response.rds.waitFor (/home/mohataher/dev/web_projects/myappwebapp/node_modules/generator-jhipster/generators/aws/lib/rds.js:55:13)
    at Request.<anonymous> (/home/mohataher/dev/web_projects/myappwebapp/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/home/mohataher/dev/web_projects/myappwebapp/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/mohataher/dev/web_projects/myappwebapp/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/mohataher/dev/web_projects/myappwebapp/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/mohataher/dev/web_projects/myappwebapp/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/mohataher/dev/web_projects/myappwebapp/node_
```

##### **Motivation for or Use Case**

This is done at the deployment of the app on Elastic Beanstalk

##### **Reproduce the error**

1. Create new project using MySQL at production environment.
1. run `jhipster upgrade` to use latest version.
1. Create an entity (optional)
1. Deploy using command `jhipster aws`. Following steps in [this guide](http://www.jhipster.tech/aws/).

##### **Operating System**

Using Ubuntu 16.

### PR DESCRIPTION
**Pull request by ggotti**
In AWS environments where an elastic-beanstalk application hasn't been deployed via the environment management console initially, then two dependent roles are missing from IAM: [aws-elasticbeanstalk-ec2-role](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/iam-instanceprofile.html#iam-instanceprofile-verify), and [aws-elasticbeanstalk-service-role](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/iam-servicerole.html). This fix will generate the appropriate default roles, based on the documentation, allowing the environment to start once deployed.

I'm hoping it fixes #7086

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
This is awesome @ggotti !!!!! Thanks so much. I'll test before we release v5.

**Comment by jdubois** [comment]
Argh it's still faililng... I found a couple of issues I'll try to correct, but I'm stuck when deploying, on the Elasticbeanstalk instance I get: `Environment must have instance profile associated with it.` and then the instance is terminated

**Comment by ggotti** [comment]
@jdubois I've made a mistake with the instance profile settings; just correcting it now.

**Comment by jdubois** [comment]
Great, thanks !

**Pull request merged**
