### PR TITLE
Add eslint for generator files

### LINKED ISSUE #3244: Use eslint in the generator itself
As per https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/-L8ZlfaLPJY/aBfKVqYlBwAJ

Eslint supports natively some coding styles, like Airbnb's one. Using this tool will prevent code unconsistency in our various JS files.

### PR DESCRIPTION
**Pull request by wmarques**
Fix #3244 
Added eslint linter to check our syntax. It throws many errors that I'm going to fix tomorrow (many of them will be fixed with --fix option).
Check the .eslintrc file and tell me if you disagree about some rules !

### CODE REVIEW

**Comment by jdubois** [comment]
Let's merge this once you have corrected the errors, maybe this will help to have better rules

**Comment by deepu105** [comment]
I thinks its good for a start, we can add more rules later.

Btw I think you should set `browser: false`

**Comment by wmarques** [comment]
Just one error left : "hasWarning undefined" in cloudfoundry subgen but I don't know how to resolve this..

**Comment by deepu105** [comment]
what does the error trace say?

**Comment by wmarques** [comment]
it says that the variable hasWarning (used in an if block) is not defined, and I couldn't find how to define it above the if block.

**Comment by deepu105** [comment]
its definitely a bug, the variable will be always undefined here (I guess
it was copied form the openshift generator, but ist not applicable here),
its not anywhere in the scope, You can remove that if block completeley

Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
Ok it's done thanks !

**Comment by deepu105** [comment]
@wmarques can you take care of the conflict.

Once we merge this we should make lint part of a travis build or as a prepublish task in npm to ensure rules are followed

**Comment by wmarques** [comment]
Forgot to say : run `npm run lint` to execute eslint.

**Pull request merged**
