### PR TITLE
Add needle api unit tests

### PR DESCRIPTION
**Pull request by avdev4j**
Adding tests for the needle API:

-   [x] base (done in #9151)
-   [X] client (done in #9233)
-   [x] client-angular (started at  #9151 and finished at #9321)
-   [X] client-i18n
-   [X] client-react (done in #9151)
-   [x] client-webpack
-   [x] server-cache
-   [x] server-gradle
-   [x] server-liquibase
-   [x] server-maven

------
-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by avdev4j** [comment]
I have finally split commits in PR they belong and I added in this one the missing tests.
The goal is to have green PR that bring fix and also unit tests with. I think it's better

**Comment by avdev4j** [comment]
@jdubois  As we discussed before, it will be a good idea to have a sonar analyse for the core tests, isn't it ?

**Comment by jdubois** [comment]
@avdev4j it's done here: https://sonarcloud.io/dashboard?id=jhipster-core

And congrats to @MathieuAA as this looks really nice :-)

**Comment by avdev4j** [comment]
`core tests` was a little bit misleading, I was thinking of generator-jhipster test not jhipster-core.

Of course having report for jhipster-core is really appreciate too, good job @MathieuAA

**Comment by DanielFran** [comment]
@MathieuAA congratulation for the code coverage!
Sonar seems detected a bug: https://sonarcloud.io/project/issues?id=jhipster-core&open=AWkL2DNsfuL_aNBIoMaH&resolved=false&types=BUG

**Comment by avdev4j** [comment]
I found 2 bugs during maven tests: 
- in needle-base we omit the path in `addBlockContentToFile` can sometime be use by some method in public API. I fixed it by using directly `rewriteFileModel` instead of map to another object.
- in `addMavenDependencyManagement` we historically used version in scope field. Thanks to unit tests for having found that.

**Pull request merged**
