### PR TITLE
Add jshint in watch task for Gulp (with notification errors)

### PR DESCRIPTION
**Pull request by cicoub13**
Add jshint task in watch task.
Each modification in a js file trigger jshint. If an error is found, notification pops.

Suggested here : https://github.com/jhipster/generator-jhipster/pull/2756
Please feel free to merge if you think it's an enhancement in development.

### CODE REVIEW

**Comment by PierreBesson** [comment]
+1
We were just discussing it here : #2506
Waiting for @jdubois' feedback.

**Comment by jdubois** [comment]
I find this is a very good addition, then maybe for big projects it could be annoying: could we have this as a specific gulp task? Or with a specific option to the wiredep task? I'm sure we are not the only ones to do this, do you know what other generators do?

**Comment by deepu105** [comment]
@cicoub13 will this fail the build or exit wiredep if there is error? or is it just a notification only

**Comment by deepu105** [comment]
@cicoub13 really sorry for making merge conflict

**Comment by cicoub13** [comment]
@jdubois Yes, i understand. I can do a separate task or an option.
@deepu105 No, it doesn't fail the build. No problem for conflict, i'll correct that.

**Comment by cicoub13** [comment]
And there is a problem, notifications (and console error) pop for warnings too. I need to write a customReporter to catch only errors from jshint.

**Comment by deepu105** [comment]
@cicoub13 if it doesnt fail build, watch then its fine also we need to notify only errors, warnings can be in console alone else will be annoying. can we configure to pass a flag to watch/build task to say `--no-alerts` or something like this http://stackoverflow.com/questions/23023650/is-it-possible-to-pass-a-flag-to-gulp-to-have-it-run-tasks-in-different-ways?answertab=votes#tab-top

**Comment by cicoub13** [comment]
I suggest :
* --notify option to enable all notifications (sass and jshint). Default gulp serve has no notifications.
* add customReporter to catch only jshint errors
* let jshint in watch (but no notifications if no --notify tag)
* no change in build and wiredep tasks

**Comment by deepu105** [comment]
I would have notify enabled by default coz most people would forget the
flag and if it feels annoying they can disable it

**Comment by jdubois** [comment]
Yes notifications is really cool, we can keep it enabled by default!
I'm always doing "yo jhipster --force | say "project finished", this is
going to be a cool improvement for everyone :-)
So the option would be --no-notification



On Thu, Feb 4, 2016 at 1:03 PM, Deepu K Sasidharan <notifications@github.com
> wrote:

> I would have notify enabled by default coz most people would forget the
> flag and if it feels annoying they can disable it
> On 4 Feb 2016 19:15, "Cyril Beslay" <notifications@github.com> wrote:
>
> > I suggest :
> >
> > - --notify option to enable all notifications (sass and jshint).
> > Default gulp serve has no notifications.
> > - add customReporter to catch only jshint errors
> > - let jshint in watch (but no notifications if no --notify tag)
> > - no change in build and wiredep tasks
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jhipster/generator-jhipster/pull/2777#issuecomment-179777601
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/pull/2777#issuecomment-179790837>
> .
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by cicoub13** [comment]
Done : 
* add **--no-notification** flag to disable all notifications (enabled by default). I tried to pass parameter to handleError without success. Sorry for redundant code but if you have an idea, i'll take it ...

To do :
* create a **customReporter** to notify only jshint errors (and not warnings)
* **fix** merge issues (you code quickly :-))

**Comment by cicoub13** [comment]
Done, feel free to test and review.

**Comment by deepu105** [comment]
build failed, I guess you forgot to add `yargs` to package.json

also your commit list shows too many from others thats strange can you check this it shouldnt have all those files listed. all the client templates are now in `generators/client/templates` plz check and correct

**Comment by deepu105** [comment]
since your changes are only in 2 files, may be just close this PR and open a  new PR on latest master with your changes alone

**Comment by cicoub13** [comment]
Close because bad merge. See new PR here : https://github.com/jhipster/generator-jhipster/pull/2796

**Pull request closed without merging**
