### PR TITLE
Fix whitespace issues reported by eslint

### PR DESCRIPTION
**Pull request by pvliss**
Fix whitespace issues reported by eslint

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
Wait we have prettier to take care of these, why do you have to do it manually?

**Comment by pvliss** [comment]
Hello @deepu105. No sure what exactly you mean by manually? I actually used `npm run lint-fix`. The problem is that `npm test` would not run unless these were fixed. Do you have a git commit hook that auto-formats code or something?

**Comment by deepu105** [comment]
@pvliss @avdev4j seems we dont have commit hooks on this repo as some core team members didnt like it. I have enabled it on test so should be good now, just rebase your branches to master and run `npm test` and create PR if there is any file updated

**Comment by pvliss** [comment]
Yes, problems are now resolved. Thanks @deepu105

**Pull request closed without merging**
