### PR TITLE
Upgrading to Hibernate Validator 5.3.3.Final

### PR DESCRIPTION
**Pull request by gunnarmorling**
This updates HV to the latest and greatest. I'm not 100% sure about the POM change, in that case you seem to get the HV version from the Spring Boot dependencies POM. I can rework or split it up as needed.

### CODE REVIEW

**Comment by jdubois** [comment]
Yes, we normally get it from Spring Boot, and don't upgrade unless it solves a specific issue.... Then I don't know why it's set up in Gradle, but not in Maven!

**Comment by gunnarmorling** [comment]
Right, that's what's unclear to me as well.

**Comment by jdubois** [comment]
Then it's good to have this fixed, and having a newer version is probably good as we also upgrade Hibernate in the next release

**Comment by gunnarmorling** [comment]
Sweet, thanks!

**Comment by gunnarmorling** [comment]
Hey, before my change you linked above, JHipster would use the HV as configured by Spring Boot with Maven but use a specific version with Gradle. So I changed it to use the same version with Maven, too. I think you need the variable reference for Gradle with the current kind of set-up.

**Comment by ctamisier** [comment]
ok indeed, so I added:
`compile "org.hibernate:hibernate-validator:${hibernate_validator_version}"` in the PR

**Pull request merged**
