### PR TITLE
Improve compose files with Docker 1.13

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/5128
- remove all container_name, links and external_links to use DNS alias instead
- add npm test

@PierreBesson : if you have time to review it

@jdubois / @mraible : I know you do a lot of demos, so I hope you can test this. I don't want to break something!

### CODE REVIEW

**Comment by PierreBesson** [comment]
@pascalgrimaud I have notice a new docker-compose feature that could replace our JHipster Sleep by using docker healthchecks and depends_on : https://docs.docker.com/compose/compose-file/#/dependson

Also big news, I have managed to deploy a docker-compose with a full microservice stack to a swarm, with scaling working correctly. So when I have the time I will finally be able to add the option to generate a docker-compose for "prod".

**Comment by romaindequidt** [comment]
May I propose you smething like this?
https://github.com/romaindequidt/generator-jhipster/commit/72038a4588cebbe3cca8a7a5ebeb6587398925e1

**Comment by pascalgrimaud** [comment]
@PierreBesson : interesting! so we need to upgrade the docker-compose file version to 2.1+. I think it can be done on another PR to be clearer

@romaindequidt : sure, it looks better than what I did:
- you can PR directly on my branch (so this PR will be updated)
- or you can wait this PR to be merged, then you make a PR, so you get credits for your work

**Comment by romaindequidt** [comment]
@pascalgrimaud I wanted to PR our PR but i do not if i can (i'm not jhipster member and I did find your branch :/)
Sorry to ask you that but, may you explain me the procedure?

**Comment by pascalgrimaud** [comment]
@romaindequidt : so if you want to PR on my branch, just go to this link https://github.com/pascalgrimaud/generator-jhipster/compare/docker-1.13...romaindequidt:docker-1.13

**Comment by jdubois** [comment]
LGTM so @pascalgrimaud I let you merge this when the PR on your PR is also merged :-)

**Comment by romaindequidt** [comment]
@jdubois @pascalgrimaud Are you sure to force everyone to upgrade their Docker client version?
For exemple, some AWS service are only available for 1.12 version:
[Amazon ECS Container Agent Versions](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html)
Should we add a subgenerator option/parameter to choose one of the versions?

**Comment by jdubois** [comment]
Thanks @romaindequidt I didn't notice that!!!
No we can't support multiple versions, that would be a lot of work for something quite temporary. Our options are:

- Stay on the newer version, and if people want to use it, they need to upgrade (or stay on an old JHipster release otherwise)
- Switch back to the older version, and in that case people won't benefit from the newer code

I would stay with 1.13, people need to upgrade, or use an up-to-date cloud. @pascalgrimaud what's your opinion?

**Comment by pascalgrimaud** [comment]
In fact, this PR removes `links` and `external_links`, to use DNS alias instead.
It's not concerned by Docker 1.13 -> the title was wrong, it should be: `Improve compose files by using DNS alias`
The version in Docker compose files is still v2, not v3 (Docker 1.13), so don't worry @romaindequidt it is still compatible :)

But I made this PR https://github.com/jhipster/jhipster.github.io/pull/386 to update the Docker client API to 1.13

**Comment by romaindequidt** [comment]
@pascalgrimaud Ok, if it's not this PR it will be the next one ;)
I 'd like to work on the "healthchecks" and "depends_on" parameters proposed by @PierreBesson , so in that case we go forward and we do not manage "backward compatibility"

**Comment by pascalgrimaud** [comment]
Yes plz @romaindequidt !

**Comment by PierreBesson** [comment]
@romaindequidt Yes a PR would be very much appreciated ! Do not worry about "background compatibility" as for us docker-compose is first and foremost a "dev" tool (no meaningful way to manage your "prod" with it before the last version).

**Pull request merged**
