### PR TITLE
Modified reload for .new .edit and .delete states

### PR DESCRIPTION
**Pull request by danielbrutti**
Added the `.new`, `.edit` and `.delete` states reload modifications based on this #3894 issue

Best,

Daniel

### CODE REVIEW

**Comment by deepu105** [comment]
@sendilkumarn did you test this?

**Comment by sendilkumarn** [comment]
Not yet. I will try to test over the weekend. Completely occupied 👍

**Comment by sendilkumarn** [comment]
this has better use case in `multiple nested` route and  `customised` version

`true` will reload the entire tree and using the `entity` name here will be more correct

**Comment by deepu105** [comment]
Ok then

**Pull request merged**
