### PR TITLE
[WIP] Add Traefik support

### PR DESCRIPTION
**Pull request by jdubois**
This work was done with @ptavares @Yannoo @latourna @Gregoriz @djahanshahi

This is a work in progress:
- When Traefik starts faster than Consul, it doesn't sync with it (and needs to be restarted to work)
- The gateway doesn't work well, as it's not on the "/" path anymore -> the easiest solution would be to map it to the "/" path, but we haven't found how

See #6397

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
yeah @ptavares ! finally, 1st contribution :)

**Comment by Gregoriz** [comment]
About gateway's URL problem, traefik provides configuration for URL rewrite:

http://docs.traefik.io/configuration/entrypoints/#rewriting-url

One solution could be to redirect the `/` endpoint to `/gateway`

**Comment by jdubois** [comment]
Thanks @Gregoriz ! I would love to have something like:
```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    regex = "^http://localhost/gateway/(.*)"
    replacement = "http://localhost/$1"
```
However I have 2 issues:
- I'm not sure of the format here, as I don't know what hostname to write
- I just can't test: Docker4Mac crashes so bad on my Mac, that I need to reinstall it completely several times per day... That's probably a trick from Docker, Inc to increase their number of pulls :-)

**Comment by Gregoriz** [comment]
The configuration you provided seems to take any URL starting with `http://localhost/gateway/` and remove the `gateway` part.

I was more thinhink about something like that:

```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    regex = "^http://localhost[/]?$"
    replacement = "http://localhost/gateway/"
```
This would redirect `http://localhost/`  or `http://localhost` to `http://localhost/gateway`.
However, as soon as a service is called, then no redirection would be applied.
Ex:  `http://localhost/micro1` would not be redirected to `http://localhost/gateway`

I don't have enough knowledge in JHipster to think about any side effects which could be caused by such a redirection rule.

**Comment by jdubois** [comment]
I just found a much simpler solution (I wonder why I didn't think of this!!!!):

- On the "JHipster gateway", use the new `SERVER_API_URL` (configured in Webpack), so it is just "" (currently it is "/", so it doesn't use relative URLs -> I'm the one who coded that, and I have no idea why!!!!!). With this change, URLs are relatives, so the whole `http://127.0.0.1/gateway/` application works!
- As the "JHipster gateway" uses its internal Zuul to route microservices URLs, you then need:
  - Either keep the current config, so it uses `http://127.0.0.1/gateway/microservice1/` -> it goes through Traefik and then trough Zuul. This could be interesting for rate limiting, for example.
  - Or configure the Angular service for each entity to use an absolute URL (just add `/` again), so it will use `http://127.0.0.1/microservice1/` -> this looks better to me

So in the end it's just a simple work on having a `/` or not, this shouldn't be hard to configure in a template!

**Comment by jdubois** [comment]
I've just added 2 new commits corresponding to my previous comment:

- The URL prefix for all apps is now "", so it's relative: it should work everywhere, and should also allow to deploy monoliths to a non-root context.
- For microservices, there is now an absolute API starting with "/", as this is how they are routed by Zuul or Traefik. For example, a "micro1" microservice is available through the "/micro1" route.

**Comment by jdubois** [comment]
I'm merging this as it has only very limited impact on the rest of the code (only the relative URLs are a big change, but I think it's better for everyone anyway).

TODOs:

- Documentation (I'll do it today probably)
- Maybe add this feature to Kubernetes (cc @saturnism ) and Rancher (cc @stevehouel )? Shouldn't be hard to

**Pull request merged**
