### PR TITLE
Update postgresql-version and align hazelcast-management-center-version

### PR DESCRIPTION
**Pull request by pmverma**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pmverma** [comment]
I am using jhipster with postgresql 10 and it is working fine.

**Comment by pmverma** [comment]
Getting error `Error: ERROR! webpack:build failed.`

Hi devs, can anyone please do retry the travis build?

**Comment by jdubois** [comment]
@pmverma I just restarted it, cross your fingers :-)

**Comment by jdubois** [comment]
Thanks a lot! I'm trusting you for Postgresql 10!

**Comment by pmverma** [comment]
Thanks too!

**Pull request merged**
