### PR TITLE
Fix cassandra audits

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by deepu105** [comment]
doesnt audits work in Cassandra?

**Comment by pascalgrimaud** [comment]
No backend, it has never been coded
That's why I removed the front

**Comment by deepu105** [comment]
Wow after all these years. Are there even people using cassandra at all

**Comment by jdubois** [comment]
Stats show less than 0,5% of projects, and that's probably me doing tests :-)
So yes very disappointing, that's also why I'm removing it from the gateway.
At some point we will need to remove Cassandra support, probably.

**Comment by sendilkumarn** [comment]
and me 😉 doing tests 😛

**Comment by deepu105** [comment]
Ya probably its not worth the maintenance effort :(

**Pull request merged**
