### PR TITLE
Add oracle database support

### PR DESCRIPTION
**Pull request by deepu105**
add option to choose oracle as SQL database for development and production

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois Please take look

Have tested with both maven and Gradle with Oracle, H2 and Mysql and it works as expected, tried few combinations in app generation and all worked

Noteworthy changes are:
+ renamed `password` to `PASSWORD` in liquibase initial schema and users.csv - this was to avoid conflicts when using Oracle in prod and H2 in dev, since liquibase creates this field as uppercase for all DB except Oracle this should work as today for mysql and Posgres
+ added sequence to all tables having auto increment key if oracle is selected
+ removed liquibaseNow variable and used interpolateRegex instead in templates
+ Added a warning to provide ojdbc jar if oracle is selected
+ changed `${javaVersion}` in gradle.build to `<%= javaVersion %>` since it was failing
+ renamed `JHI_PERSISTENT_AUDIT_EVENT_DATA` table to `JHI_PERSISTENT_AUDIT_EVT_DATA` to support oracle char limit
+ added local repo for maven and gradle buid to put ojdbc jar
+ not generating unique index for unique column if oracle is selected as oracle autogenerates this
+ shortened keywords which are more than 30 chars

**Comment by MatthieuLebigre** [comment]
I'm using Oracle too, and the changes you made looks good to me !!
I will be happy if this code will be merged !!

**Comment by deepu105** [comment]
Next version of liquibase adds autoincrement support for oracle and once we have that we can drop the sequence used for primary key

**Comment by deepu105** [comment]
rebased to fix merge conflicts

**Comment by jdubois** [comment]
I'm currently merging this -> there is no Oracle database for Mac OS X, so I can't install it or test it. I have no solution for this, but it's annoying that I can't test anything

**Comment by jdubois** [comment]
I will add a specific documentation page for Oracle

**Comment by deepu105** [comment]
ya even i realized later that they have dropped support for mac, My team is using the custom branch and its working fine so far on local DB as well as an instance on the clients test bed. If there is any bug reported on this you can assign it to me i can take up maintenance

**Pull request merged**
