### PR TITLE
add more config data

### LINKED ISSUE #2427: show more configuration data to admin configuration screen
There are more info available in the /env endpoint which can be shown in current config screen i think its very useful

image

### PR DESCRIPTION
**Pull request by deepu105**
add more details in the admin configuration screen
also tweak some scss

image

fix #2427

### CODE REVIEW

**Comment by deepu105** [comment]
@pascalgrimaud not sure why but some of the builds are failing randomly in travis, most times it seems like failure in `npm install` phase. Is it possible to do any try catch here and retry `npm install` when it fails?

**Comment by pascalgrimaud** [comment]
We use travis a lot, probably more than other projects, so sometimes, he's tired!

About try catch, I think it's not possible. If npm install failed, the build stop immediatly
But I have an idea to reduce these fails (will work on it ;-)

**Comment by deepu105** [comment]
I too actually feel bad that we use lot of travis resources :( that too
when they are giving it for free.


Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
Maybe we can split and use other CI (CircleCI, Drone) at the same time

**Comment by deepu105** [comment]
ya may be we should consider that

**Pull request merged**
