### PR TITLE
Add elasticsearch support for Spring Boot 2

### PR DESCRIPTION
**Pull request by michael-wirth**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks a lot! Lots of good things here, too bad the tests don't pass yet... I'll try to merge this anyway, as it's better than the current code

**Comment by sendilkumarn** [comment]
@michael-wirth Congrats on your first PR 🎉

**Comment by DanielFran** [comment]
Is this dependent of https://github.com/jhipster/jhipster-dependencies/pull/28 ?

**Comment by michael-wirth** [comment]
@DanielFran Yes, it is required to remove the dependency to elasticsearch 6.1. Currently spring-data-elasticsearch is working with max version 5.5.3

@jdubois I found some other issues running the tests. I'll fix them

**Comment by michael-wirth** [comment]
PR depends on https://github.com/jhipster/jhipster-dependencies/pull/28

**Comment by jdubois** [comment]
Thanks again @michael-wirth -> I'm trying to merge this in the next hour
(please note I'll probably be unavailable for the next few days, so don't be surprised if your PR looks stuck - this is very important and my main task at the moment, so don't worry I'll work on this)

**Pull request merged**
