### PR TITLE
Use new generatePaginationHttpHeaders

### PR DESCRIPTION
**Pull request by cbornet**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
Depends on https://github.com/jhipster/jhipster/pull/202

**Comment by pvliss** [comment]
Closing and re-opening to re-launch tests

**Comment by cbornet** [comment]
Now all the tests fail except Webflux haha :sweat_smile: ... I'm on it.

**Comment by pvliss** [comment]
Well if I am not mistaken it seems that on Travis that the latest commit of the jhipster lib/server have not been picked up properly. At Azure most builds pass as they use the version built from the master branch. I will give it another try so that we can see what's really failing

**Comment by pvliss** [comment]
Seems there are only 2 + cucumber failing now and most likely related to elastic search

**Comment by pvliss** [comment]
@cbornet the details link for Travis still points to an older build. The correct one is [15452](https://travis-ci.org/jhipster/generator-jhipster/builds/504847280)

**Comment by cbornet** [comment]
Good catch ! I just fixed the Elastic Search issue. Let's see how it goes !

**Comment by cbornet** [comment]
Didn't you fix the cucumber tests in https://github.com/jhipster/generator-jhipster/pull/9404 ?

**Comment by pvliss** [comment]
Yes, I merged it as noone offered a better solution. Hopefully with your latest changes everything should be back to green

**Comment by pvliss** [comment]
Everything is working again. Merging. Nice work @cbornet :+1:

**Pull request merged**
