### PR TITLE
Change cli logs from fatal to error.

### PR DESCRIPTION
**Pull request by mshima**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by avdev4j** [comment]
hi @mshima 
I would like to merge this PR but I have one question, why sometimes we have to throw the error with an uncaught exception e.g. `throw error;` and why sometimes we do not ?

**Comment by mshima** [comment]
> hi @mshima
> I would like to merge this PR but I have one question, why sometimes we have to throw the error with an uncaught exception e.g. `throw error;` and why sometimes we do not ?

If it is inside a loop, then throw to break the loop. Sometimes this isn’t needed, the process can terminate normally.

**Comment by mshima** [comment]
We could catch outside the loop. But the error description must be right.
I am out this week.

**Comment by avdev4j** [comment]
As I can see we do some unnecessary catch sometimes (not totally sure).
e.g. `jdlImporter.generateEntities(env, forkProcess);` is catch and the error is logged 
```
    try {
        const jdlImporter = new JDLProcessor(jdlFiles, options.inline, options);
        jdlImporter.getConfig();
        jdlImporter.importJDL();
        jdlImporter.sendInsight();
        jdlImporter.generateApplications(forkProcess);
        jdlImporter.generateEntities(env, forkProcess);
        jdlImporter.generateDeployments(forkProcess);
    } catch (e) {
        logger.error(`Error during import-jdl: ${e.message}`, e);
    }
```

but the method itself catch and log the error :
```
        } catch (error) {
            logger.error(`Error while generating entities from the parsed JDL\n${error}`, error);
            throw error;
        }
``` 

So the error is catch and log twice. Is it intended ?

**Comment by mshima** [comment]
We could get some improvements in this area.
This PR is related to https://github.com/jhipster/generator-jhipster/issues/10963

**Comment by avdev4j** [comment]
Ok, We should rework the way we manage the logging part, but not in this PR ;).

One thing I want to be sure before merging that:
- There is still a fatal logging in the  [import-jdl.js](https://github.com/jhipster/generator-jhipster/blob/aaea725f6cbc55e40c74d384a527ff2ca2bbaffe/cli/import-jdl.js#L452), is it intended ?

**Comment by mshima** [comment]
Yes, but it can be changed to error and then a test
```
if (process.exitCode !=0){
  return;
}
```
after: 
https://github.com/jhipster/generator-jhipster/blob/aaea725f6cbc55e40c74d384a527ff2ca2bbaffe/cli/import-jdl.js#L471

**Comment by avdev4j** [comment]
Ok, so as far as we should avoid `process.exit(1);` should we do remove this one ? 
I'm not expert of this part and how to manage node error code, that's why I'm asking you that. If you think it's ok, I'll merge it however let's remove the fatal logging and finally merge.

**Comment by mshima** [comment]
I think we can keep fatal there. It’s cleaner. And the use case is very simple.
Otherwise the developer will need to know log.error sets exitCode as 1 to understand the conditional.

**Comment by avdev4j** [comment]
Great, I see !

Thanks you very much @mshima

**Pull request merged**
