### PR TITLE
let node crypto generate the remember me key

### PR DESCRIPTION
**Pull request by andidev**
add new yeoman config property rememberMeKey which is generated by node crypto (not promoted but kept in .yo-rc.json)
inject yeoman config property rememberMeKey in application.yml in main and test resource

### CODE REVIEW

**Comment by andidev** [comment]
Note that this will introduce a new config in .yo-rc.json (non promted sinse it is generated)
This also means that re-generating an existing app with a .yo-rc (without this new rememberMeKey config value) will lead to that the user is promted enter the generator configs again.

**Comment by jdubois** [comment]
This is a really neat idea, I love it! For people upgrading, maybe you could add a test: if the value does not exist, then they have the former secret key (which is the app name): if that's fine with you, can you update your PR?

**Comment by andidev** [comment]
Sure thing! brb

**Comment by andidev** [comment]
Added 
```
+        // Generate key if key does not already exist in config
+        if (this.rememberMeKey == null) {
+            this.rememberMeKey = crypto.randomBytes(20).toString('hex');
+        }
```

which is checked when config file is detected

**Comment by andidev** [comment]
also tested it and it seems to add the config if its missing and keep it if itäs there already

**Comment by gmarziou** [comment]
I suppose that the goal is to keep this key secret, I'm wndering if storing it in .yo-rc.json is a good idea as this file is mandatory to continue to use jhipster generators after initial generation so it can't be in .gitignore which could be an issue for people planning to use a public git repository.
By putting it in another file, you could easily decide whether to ignore it or not.

**Comment by jdubois** [comment]
if you put it that way, it's also in the application.yml file -> both files are in the same Git repository, so they have the same security level

For me you have 2 options:

- you store the key in Git, by default: it's secured as long as you trust your dev team
- if you want better security, you override it in production, for example with an env variable (easy to do with Spring Boot)

Compared to what we currently have, this is still a lot more secured, as we don't give the same secret key to everyone.

**Comment by gmarziou** [comment]
I agree but it would be nice to put 2 lines about it in the doc.
As I see it JHipster is easy and so is attractive to developers who may lack some experience in this domain. This is what happened with Rails and so someone wrote a tool to audit security in Rails app and report vulnerabilities.

**Pull request merged**
