### PR TITLE
Fix call to track function on entity list component template

### PR DESCRIPTION
**Pull request by edilsonmendes**
Fix call to track function on entity list component template
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by kaidohallik** [comment]
Thanks for the fix!

Can you do 3 more things with this PR:
* remove redundant parameter `_index` from the tracking function in `_entityFile_.component.ts.ejs` (`_entityFile_.component.spec.ts.ejs` also needs change after that)
* similar error is also in `user-management.component.html.ejs` - can you fix this issue also there
* can you remove `_index` parameter also from the tracking function in `user-management.component.ts.ejs`

**Comment by kaidohallik** [comment]
fixes #27112

**Comment by edilsonmendes** [comment]
> Thanks for the fix!
> 
> Can you do 3 more things with this PR:
> 
> * remove redundant parameter `_index` from the tracking function in `_entityFile_.component.ts.ejs` (`_entityFile_.component.spec.ts.ejs` also needs change after that)
> * similar error is also in `user-management.component.html.ejs` - can you fix this issue also there
> * can you remove `_index` parameter also from the tracking function in `user-management.component.ts.ejs`

Sure. I'll adjust it.

**Review by kaidohallik — APPROVED** [review]

**Comment by kaidohallik** [comment]
@edilsonmendes thanks for your contribution!

**Pull request merged**
