### PR TITLE
Add Micro-Service Support to AWS-Containers Subgenerator

### LINKED ISSUE #8366: Issues with aws-containers subgenerator
I have been playing with the AWS containers sub generator a lot these days and I find some issues there.

- [ ] If the application contains a cameCase base name this doesn't work
- [ ] For monoliths, there is microservice like flow which is useless and annoying
- [ ] Error reporting needs improvements
- [ ] The config is saved in the `.yo-rc.json` which is different from other cloud sub gens and could be confusing
- [ ] Also out of the box the CF template doesn't work as it stalls towards the end. Maybe it's just for me (Seems like the issue is the app service is unable to pull the image from ECR, and only works if `AssignPublicIp` is enabled in the `*AppService`)
- [ ] the config says no password for DB, but the created DB has a password so app fails

The microservice flow is broken and I don't think it works anyway

### LINKED ISSUE #10472: aws sub-generated not working.
##### **Overview of the issue**

I have a newly created project using jhipster command. now I am trying to use aws sub-generated to deploy. I have created one folder in the root of the project and write command 
```

Dharmeshs-Mac-mini:aws-deploy dharmesh$ jhipster aws               
INFO! Using JHipster version installed globally
INFO! Executing jhipster:aws
INFO! Options: from-cli: true

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /Users/dharmesh/Workspace/Live/Crick2/Source/Crick2-Backend
Installing AWS dependencies
npm WARN @angular/core@8.2.4 requires a peer of zone.js@~0.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.

+ progress@2.0.3
+ uuid@3.3.3
+ aws-sdk@2.533.0
updated 3 packages and audited 908725 packages in 20.317s
found 3 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'aws-sdk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at AwsFactory.shelljs.exec.code (/usr/local/lib/node_modules/generator-jhipster/generators/aws/lib/aws.js:41:19)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:121:9
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)

```

##### **Reproduce the error**

Create fresh project using v6.3.0 or v6.3.1 and use aws sub-generator.

##### **JHipster Version(s)**

v6.3.0
v6.3.1

##### **JHipster Version(s)**

```
crick-2@0.0.1-SNAPSHOT /Users/dharmesh/Workspace/Live/Crick2/Source/Crick2-Backend
└── generator-jhipster@6.3.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.initfusion.crick2"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "Crick2",
    "packageName": "com.initfusion.crick2",
    "packageFolder": "com/initfusion/crick2",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "embeddableLaunchScript": false
  }
}

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

git version 2.21.0 (Apple Git-122)

node: v10.16.3

npm: 6.11.3

yeoman: 3.1.0

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

### PR DESCRIPTION
**Pull request by SudharakaP**
Adds basic Micro-service support to aws-containers sub-generator.  

Fixes #8366 and Fixes #10472

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Huge work @SudharakaP, thanks so much

cc @jhipster/developers @Falydoor

If someone wants to test it, plz, you're welcome ! Otherwise, I'm trusting @SudharakaP and will probably merge this the next week, as I can't test AWS and I'm sure it's better than what we currently have.

**Comment by SudharakaP** [comment]
@pascalgrimaud : Thanks. I've went ahead and [modified some info](https://github.com/jhipster/jhipster.github.io/pull/807) in our website to include these changes as well. 

To anyone who is testing; the EKS stack is not covered by free tier so it might incur some costs when deploying things there. I think you might be able to get away with around 20 dollars if you didn't keep it running for long.

**Comment by SudharakaP** [comment]
@pascalgrimaud : Bug bounty claim submitted at; https://opencollective.com/generator-jhipster/expenses/10734

**Comment by pascalgrimaud** [comment]
just approuved
thanks for helping the project !

**Comment by SudharakaP** [comment]
@pascalgrimaud : You are most welcome. :hugs:

**Pull request merged**
