### PR TITLE
JDL: improve parsed jdl content

### LINKED ISSUE #12494: JDL: Improve parsed JSON
When using `jhipster-core/lib/dsl/api` to parse a JDL to JSON, provide the resolved entities in the application structure instead of included/excluded

Current:
```
{
  "applications": [
    {
      "config": {
        "baseName": "myApp",
        "applicationType": "gateway",
        "packageName": "com.myapp",
        "packageFolder": "com/myapp",
        "authenticationType": "jwt",
        "prodDatabaseType": "mysql",
        "clientFramework": "react"
      },
      "entities": { "entityList": ["*"], "excluded": [] },
      "options": {}
    }
  ]
}
```

Expected 
```
{
  "applications": [
    {
      "config": {
        "baseName": "myApp",
        "applicationType": "gateway",
        "packageName": "com.myapp",
        "packageFolder": "com/myapp",
        "authenticationType": "jwt",
        "prodDatabaseType": "mysql",
        "clientFramework": "react"
      },
      "entities": { 
          "entityList": ["A", "B", "C"]
      },
      "options": {}
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by MathieuAA**
Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Fixes #12494

### CODE REVIEW

**Comment by DanielFran** [comment]
@MathieuAA Can you fix the conflicts?

**Comment by MathieuAA** [comment]
@DanielFran done. I'm gonna merge it once the CI passes. This PR has been stale for too long.

**Review by DanielFran — APPROVED** [review]

**Comment by mshima** [comment]
@MathieuAA you are still jdl lead, merge PRs at will.
We will ping you if you break something 😄 .

**Comment by MathieuAA** [comment]
My pleasure

**Comment by mshima** [comment]
@MathieuAA I took a look, but there is nothing I could contribute.
Not sure where it is used, maybe JDL Studio.

**Comment by MathieuAA** [comment]
Yes @mshima, it is.

**Pull request merged**
