### PR TITLE
initial OpenShift generator files

### PR DESCRIPTION
**Pull request by srinivasa-vasu**
initial ocp generator files

### CODE REVIEW

**Comment by jdubois** [comment]
This is so huge, I won't be able to test this so @srinivasa-vasu I have two questions for you:

- If we merge this, can add you to a specific group in the project, so Openshift issues are assigned to you? I will also create a specific label for the tickets
- I know you work for Red Hat, can we say that this is an official contribution from Red Hat? I'll be happy to put your company logo everywhere, and of course thank Red Hat for this.

**Comment by srinivasa-vasu** [comment]
@jdubois 
1. I am fine with point#1.
2. Not sure about point#2. This is an individual contribution, but to treat this as an official contribution, I probably have to check with few folks here.

By the way, I believe you should be able to test this out easily. Just install minishift and then apply the auto generated script (I have added few troubleshooting tips as part of documentation). I can also send across ansible playbook which takes care of installation of OpenShift (either community/0$ enterprise).

**Comment by jdubois** [comment]
@srinivasa-vasu the first point is the most important:

- I invited you to the organization
- I created the label: https://github.com/jhipster/generator-jhipster/labels/openshift (and I'm applying it to this very ticket!)

For Red Hat, it's really up to you and to your company:

- I'd be very happy to tweet about it and put the Red Hat logo on the website
- By the way, we use Undertow, Hibernate, MapStruct... I'm also discussing with @sebastienblanc for adding Keycloak support... If you count the total number of lines, we probably use more Red Hat code than Spring code, which is surprising for many people!

**Comment by srinivasa-vasu** [comment]
@jdubois Wow, that's really great to hear

**Comment by jdubois** [comment]
@srinivasa-vasu I'm not merging this right now as we are going to do a new release, with already a lot of new features: we'll feature Openshift support in the next release

**Comment by srinivasa-vasu** [comment]
Ok...

**Comment by deepu105** [comment]
The command alias needs to be added to the new CLI here https://github.com/jhipster/generator-jhipster/blob/master/cli/commands.js

**Comment by jdubois** [comment]
Let's merge this -> @srinivasa-vasu if you have any news from Red Hat, I'll be happy to put their logo and thank them publicly

**Comment by deepu105** [comment]
its added

**Comment by srinivasa-vasu** [comment]
@jdubois I have already written about it, yet to get an update. Will keep you posted. Is it ok if you can use the upstream OpenShift 'origin' logo in the mean time?

**Comment by deepu105** [comment]
@srinivasa-vasu I think it should be ok can you add the appropriate logo in the documentation PR please

**Comment by srinivasa-vasu** [comment]
@jdubois - You may pls mention this as official contribution from Red Hat, but pls not use the logo. I got the conformation to mention publicly that Red Hat made an official contribution. To use the logo, have to get explicit permission and also a formal process to be followed to get this done.

**Comment by cata86** [comment]
Hi @srinivasa-vasu can I ask you little questions about this implementation?
Why this implementation do the build on localhost and push the image on docker hub? 
I think it would be better to delegate the build to openshift:
https://docs.openshift.com/container-platform/3.3/dev_guide/builds.html#binary-source
and then push the image to local openshift registry.

**Comment by srinivasa-vasu** [comment]
@cata86 That will be the future. To align with 'one build multiple deploys' notion, build happens locally and then image gets pushed to docker runtime of OpenShift [through eval $(docker-machine env <machine_name>) ]. At this point of time, complete lifecycle will not be managed in OpenShift. In future, we shall have an option prompt to manage the lifecycle in OpenShift which would even help us easily implement CI/CD and CD/CI. Another reason why it is not done now is, every time when you need to build in OpenShift it is going to take a longer time without the local Nexus/Artifactory repo as the build pods are ephemeral and hence artefacts/libraries need to be pulled every time build happens or incremental build needs to be activated which would save some time. To begin with, easy option is to follow the existing practise and eventually we shall introduce more options in the future.

**Pull request merged**
