### PR TITLE
Angular: Remove angular2-moment

### PR DESCRIPTION
**Pull request by wmarques**
Angular2-moment makes the application bundle contains `moment` twice, which is quite huge... I think we should only use moment to do date manipulation.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
can you check ng-jhipster lib as well, I suggested to add the plugin to avoid writing our own pipes but if moment can directly do it than its fine. Just make sure the pipes are not used in HTML

**Comment by wmarques** [comment]
Yep, I'll check that ! I agree that this lib is useful as it provides built in pipes but the cost is too high.. Moment is quite a huge lib,  Generally I use date-fns when I need to do date manipulation.

**Comment by wmarques** [comment]
@deepu105  I didn't find `moment`in ng-jhipster and I didn't find pipes of the `angular2-moment`lib in our HTML templates

**Comment by deepu105** [comment]
then its good, lets merge this


Thanks & Regards,
Deepu

**Pull request merged**
