### PR TITLE
Revert @typescript-eslint/eslint-plugin and @typescript-eslint/parser to 5.13.0

### PR DESCRIPTION
**Pull request by DanielFran**
Reverts jhipster/generator-jhipster#18065 and jhipster/generator-jhipster#18066

### CODE REVIEW

**Comment by emilpaw** [comment]
The issues caused by the update seem to be pretty minor. Maybe rather than reverting to the older version we could fix the issues?

**Comment by DanielFran** [comment]
@emilpaw Yes of course, but this is just to unblock pipeline. Did this PR from my phone, cannot fix the issue right now.
Can you please create a fix?

**Comment by emilpaw** [comment]
> @emilpaw Yes of course, but this is just to unblock pipeline. Did this PR from my phone, cannot fix the issue right now. Can you please create a fix?

Yes, I will work on it now.

**Comment by emilpaw** [comment]
The PR is open:  #18074

**Comment by DanielFran** [comment]
Superseded by  #18074

**Pull request closed without merging**
