### PR TITLE
Remove Diskspace Health Check for GAE Deployments

### PR DESCRIPTION
**Pull request by SudharakaP**
Fixes https://github.com/jhipster/generator-jhipster/issues/11092

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by SudharakaP** [comment]
Close/Open for tests. The failures are interesting with some kinda chrome binary failure; seems unrelated to this PR. :thinking:

**Comment by pascalgrimaud** [comment]
> chrome binary
again...? :(

**Comment by SudharakaP** [comment]
This thread explains it perfectly; https://askubuntu.com/questions/1182803/what-causes-failed-to-fetch-file-has-unexpected-size-mirror-sync-progress

Maybe we should give it a little time until the mirrors get updated? :thinking:

**Comment by SudharakaP** [comment]
> > chrome binary
> 
> again...? :(

Have you seen this problem occuring before? :thinking:

**Comment by pascalgrimaud** [comment]
Oh not this one. I thought it was the problem with Chrome driver during e2e tests
This one is a different one

**Pull request merged**
