### PR TITLE
img-loader downgrade to fix warnings

### PR DESCRIPTION
**Pull request by flaviencathala**
Fix for warnings (see https://github.com/jhipster/generator-jhipster/issues/5196)

### CODE REVIEW

**Comment by deepu105** [comment]
@flaviencathala downgrading cannot be a permanent fix. as we have to keep libs upto date so I would prefer to have latest lib and fix the deprecation as per the libs suggestion. We can temporarily downgrade if there is some bug but not for deprecation. Hence please revert this

**Comment by deepu105** [comment]
here is what should be done to fix it https://github.com/tcoopman/image-webpack-loader/issues/68

**Comment by jdubois** [comment]
@deepu105 I agree for this specific issue, but what about the Windows issue? If downgrading solves the Windows issue, we don't have another solution for the moment

**Comment by deepu105** [comment]
@jdubois I'm not sure if its related but let me test this in windows later today

**Pull request merged**
