### PR TITLE
update gitignore

### LINKED ISSUE #1168: Use repository absolute paths in .gitignore
Having entries like `target` in the `.gitignore` file is a bad idea since it will ignore any file or folder with this name regardless of were they are in the repository. I've been bitten myself with this when I had a Java package named `target`. It took me a while to figure out why it didn't show up in `git status`! :-) Here's the `.gitignore` I use for my JHipster generated project:

```
/target
/node
/node_modules
.idea
*.iml
.classpath
.project
.settings
.tmp
.merge_file*
.sass-cache
.DS_Store
/src/main/webapp/dist
/src/main/webapp/bower_components
.gradle
/build
```

So basically just prepend the paths that should only be ignored if they are in the root of the repository with /.

### PR DESCRIPTION
**Pull request by rasheedamir**
added comments in gitignore to make it more readable

Fix #1168

### CODE REVIEW

**Comment by jdubois** [comment]
You mean "update gitignore"? :-)

**Comment by rasheedamir** [comment]
good catch @jdubois this happens when you have long working day!

Should I raise another PR?

**Comment by jdubois** [comment]
Yes, if we could have a correct commit message that would be better!

**Comment by rasheedamir** [comment]
Sure! no problem. I will provide it by tomorrow day end.

**Comment by rasheedamir** [comment]
@jdubois please reject this PR and accept the other one with fixed commit message.

**Pull request closed without merging**
