### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by mshima**
Related to https://github.com/jhipster/jhipster-dotnetcore/pull/1358 and  https://github.com/jhipster/generator-jhipster/issues/23449

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
@mshima Not sure if this is the pr that started to break Windows pipeline

**Comment by mshima** [comment]
@DanielFran daily builds is passing. What do you mean about pipeline?

**Comment by DanielFran** [comment]
https://github.com/hipster-labs/jhipster-daily-builds/actions/workflows/windows.yaml

**Comment by mshima** [comment]
Ok the summary at readme is not updated for me.

**Pull request merged**
