### PR TITLE
Update spring-boot to 2.1.6 and dependencies

### PR DESCRIPTION
**Pull request by DanielFran**
Depends on https://github.com/jhipster/jhipster/pull/293

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud @jdubois Can someone clean travis cache?

**Comment by pascalgrimaud** [comment]
I can, but is there a problem with Travis cache ??

**Comment by DanielFran** [comment]
I do not know, it still failing with error that dependencies did not exists but in Azure everything is OK...

**Comment by pascalgrimaud** [comment]
@DanielFran : ok, just deleted the cache and restart this build

**Comment by DanielFran** [comment]
@pascalgrimaud Seems OK now! Thanks

**Comment by pascalgrimaud** [comment]
@DanielFran : just to understand the strange issue. Did you PR upgrade spring-boot with 2.1.6 before the official release ?

**Comment by DanielFran** [comment]
Yes but in Draft.

**Pull request merged**
