### PR TITLE
WIP: import JDL generate liquibase incremental changelogs

### PR DESCRIPTION
**Pull request by gimoh**
WIP for #5954 

Some of this will probably need to be split so I'll push a new branch for final review.

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
Great ill take a look tomorrow

**Comment by jdubois** [comment]
This looks surprisingly simple! I can't believe this!

**Comment by deepu105** [comment]
I think its not complete yet, there still work to be done to compare the
entities and stuff when importing I guess


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Oh yes, and relationships are missing... Still, that's an awesome idea and work

**Comment by sendilkumarn** [comment]
Awesome idea 👏

**Comment by gimoh** [comment]
Thank you all, much appreciated :smile: 

Yes, this is very much a work in progress, just wanted to publish to make it visible.

I had some other urgent stuff to take a look at the last couple of days, but I'm getting back to this now, we'll see where it takes me :laughing:

**Comment by tan9** [comment]
This idea is really impressive! Once this feature is complete, we will have a **versioned** JDL.

If we can further incorporate magics already implemented in the `upgrade` sub-generator,  it will be super productive while evolving domain models!

For example, I always open an orphan branch to generate all codes using current JDL, merging into master, and then modify the JDL and re-generate everything again, and I will have a difference on model changes on code to apply back to master. Just like what `upgrade` sub-generator did, except the thing been upgraded is the model instead of JHipster itself.

**Comment by deepu105** [comment]
@gimoh did you make progress? do you need any help?

**Comment by gimoh** [comment]
@deepu105 had to switch tasks, needed to get the hipster-labs/generator-jhipster-entity-audit#70 addressed and also started looking into port to Angular 4; but I'll be back on this as soon as I can, I'll need to rebase on master as I've seen there's some interesting changes

**Comment by deepu105** [comment]
Sure no hurry


Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
@gimoh Hello, if you need any help, don't hesitate to delegate some tasks!

**Comment by deepu105** [comment]
@gimoh are you still working on this?

**Comment by gimoh** [comment]
It's still on my radar, yes, however I've been swamped by other work recently and haven't had the time to move this forward unfortunately.

But you're right, I'll spend some time this weekend and bring it up to date and split it into smaller tasks so it can be partially delegated / split between a team.

**Comment by jdubois** [comment]
@gimoh I had a quick look at your PR, and it looks good to me (except for the obvious merge conflicts, but that's not your fault).

- Are you still working on this?
- How can we help you?

**Comment by jdubois** [comment]
I'm closing this, unfortunately, as this is stalled.

I'd love to have this, and it looks like a great idea, so I'll study this again in a couple of months, when I will have 2 trainees to work on JHipster.

**Comment by Entrecampos** [comment]
If I do
```
 ./mvnw liquibase:diff
 ./mvnw liquibase:clearCheckSums

```
It solves the error but I still have to delete the DB and create again.

**Pull request closed without merging**
