### PR TITLE
Add Heroku Git deployment

### PR DESCRIPTION
**Pull request by jkutner**
This change adds support for Git deployment to Heroku. New applications will be prompted to choose between JAR and Git deployment:

```
? Which type of deployment do you want ? (Use arrow keys)
❯ JAR (compile locally)
  Git (compile on Heroku)
```

JAR deployment uses the CLI to deploy a precompiled JAR file (as in previous JHipster versions), while Git deployment commits changes to the Git repo and pushes to the remote Heroku repository. 

Existing apps will not be prompted, and will continue to use JAR deployment.

### Non-Heroku specific changes

This PR also adds a `addMavenProfile` function to the `generator-base.js`. This supports a new `heroku` profile that cleans `node_modules` and other artifacts during the Maven build on Heroku.

### CODE REVIEW

**Comment by jdubois** [comment]
This looks incredibly awesome!!!
Let me test this - and then we need this in https://start.jhipster.tech/ so you can do everything directly in the app, which is super-slick, and was my original idea when starting JHipster 4 years ago, and that makes me really happy.

**Comment by jdubois** [comment]
@jkutner argh it's failing with a basic app (from the master branch, with all default options), saying "Caused by: java.lang.IllegalArgumentException: URL must start with 'jdbc'"

**Comment by jdubois** [comment]
@jkutner maybe this is because I selected MySQL and not Postgresql (btw we should change that default settings in JHipster 5, Postgresql is just better).
But now another issue, I can't generate a second project, I got:

```
Installing Heroku CLI deployment plugin
✖ { Error: Command failed: heroku plugins:install heroku-cli-deploy
Installing plugin heroku-cli-deploy... !
 ▸    heroku-cli-deploy is already installed, run with --force to install anyway

**Comment by jkutner** [comment]
@jdubois you're seeing that error at runtime? Can you check if the db addon was created by running `heroku addons`?

**Comment by jkutner** [comment]
@jdubois i'm not seeing the same thing :( how do you set up to test? I'm using `yarn link`.

**Comment by jkutner** [comment]
@jdubois i agree that Postgres would be a better default, but this should still work with MySQL (in fact I did nearly all of my testing with MySQL).

**Comment by jkutner** [comment]
@jdubois are you getting the `URL must start with 'jdbc'` locally or on Heroku? If you've run the Heroku generator, the app will need a SPRING_DATASOURCE_URL in prod mode (and that error might happen if you don't have one locally?)

**Comment by jdubois** [comment]
I'm just doing "jhipster" and then "jhipster heroku"

**Comment by jkutner** [comment]
Two possibilities I can think of:

 1. I'm not seeing the error because I'm running `jhipster` with 4.13.3, then using `yarn link` to `yarn run jhipster heroku` with the new stuff. I'll try to figure out how to do it the same way as you.
1. Your Heroku CLI had to update the first time you ran `jhipster heroku` and that screwed up or timed out the generator (if that's what's happening, it should work the second time and I can add a guard for this).

Either of those sound possible?

**Comment by jkutner** [comment]
@jdubois how do I run JHipster 5. Is that in master branch?

**Comment by jkutner** [comment]
@jdubois i've tried a bunch of different things, and haven't been able to reproduce. But the errors you're seeing seem like they would happen even w/o the Git changes from this PR. I suspect there is some other problem (such as the Heroku CLI auto-updating and interrupting the generator). I'll keep investigating, but I'm curious to see if anyone else runs into those errors.

One last thing: what does `heroku --version` show for you?

**Comment by jdubois** [comment]
Sorry @jkutner my Heroku install was probably old & broken. I installed a new version using Homebrew and I can deploy OK - but I have still the problem `Caused by: java.lang.IllegalArgumentException: URL must start with 'jdbc'`.

I just created an app from the master branch, with all default options, and then did a "jhipster heroku". I'm testing again, but with Postgresql.

**Comment by mraible** [comment]
I just tried this and it doesn't seem to build the frontend. Maybe it needs to be built with the prod profile?

**Comment by jkutner** [comment]
@mraible is that for `jhipster heroku` with Git or with JAR deploy (or both)?

**Comment by mraible** [comment]
@jkutner For the Git deploy.

```
[mraible:~/backend] % yo jhipster:heroku
Heroku configuration is starting
? Name to deploy as: backend
? On which region do you want to deploy ? us
? Which type of deployment do you want ? Git (compile on Heroku)

Using existing Git repository

Heroku CLI deployment plugin already installed

Creating Heroku application and setting up node environment
heroku create backend

? The Heroku app "backend" already exists! Use it anyways? No, generate a random name
https://vast-refuge-36937.herokuapp.com/ | https://git.heroku.com/vast-refuge-36937.git

Provisioning addons
Created jawsdb:kitefin --as DATABASE

Creating Heroku deployment files
   create src/main/resources/config/bootstrap-heroku.yml
   create src/main/resources/config/application-heroku.yml
   create Procfile
 conflict pom.xml
? Overwrite pom.xml? overwrite this and all others
    force pom.xml

Skipping build

Updating Git repository
git add .
git commit -m "Deploy to Heroku" --allow-empty

Configuring Heroku

Deploying application
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Java app detected
remote: -----> Installing JDK 1.8... done
remote: -----> Executing: ./mvnw -DskipTests clean dependency:list install
remote:        [INFO] Scanning for projects...
remote:        [INFO]
remote:        [INFO] ------------------------------------------------------------------------
remote:        [INFO] Building Backend 0.0.1-SNAPSHOT
remote:        [INFO] ------------------------------------------------------------------------
remote:        [INFO]
remote:        [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ backend ---
remote:        [INFO]
remote:        [INFO] --- maven-dependency-plugin:2.8:list (default-cli) @ backend ---
remote:        [INFO]
remote:        [INFO] --- maven-resources-plugin:3.0.1:copy-resources (default-resources) @ backend ---
remote:        [INFO] Using 'UTF-8' encoding to copy filtered resources.
remote:        [INFO] Copying 5 resources
remote:        [INFO] Copying 14 resources
remote:        [INFO]
remote:        [INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ backend ---
remote:        [INFO] Using 'UTF-8' encoding to copy filtered resources.
remote:        [INFO] Copying 5 resources
remote:        [INFO] Copying 14 resources
remote:        [INFO]
remote:        [INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) @ backend ---
remote:        [INFO]
remote:        [INFO] --- maven-resources-plugin:3.0.1:copy-resources (docker-resources) @ backend ---
remote:        [INFO] Using 'UTF-8' encoding to copy filtered resources.
remote:        [INFO] Copying 2 resources
remote:        [INFO]
remote:        [INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (pre-unit-tests) @ backend ---
remote:        [INFO] argLine set to -javaagent:/app/tmp/cache/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/tmp/build_a42031ccda04e8ab02893e018fb1a3ff/target/test-results/coverage/jacoco/jacoco.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
remote:        [INFO]
remote:        [INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ backend ---
remote:        [INFO] Changes detected - recompiling the module!
remote:        [INFO] Compiling 75 source files to /tmp/build_a42031ccda04e8ab02893e018fb1a3ff/target/classes
remote:        [INFO]
remote:        [INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ backend ---
remote:        [INFO] Using 'UTF-8' encoding to copy filtered resources.
remote:        [INFO] Copying 4 resources
remote:        [INFO]
remote:        [INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ backend ---
remote:        [INFO] Changes detected - recompiling the module!
remote:        [INFO] Compiling 19 source files to /tmp/build_a42031ccda04e8ab02893e018fb1a3ff/target/test-classes
remote:        [INFO]
remote:        [INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ backend ---
remote:        [INFO] Tests are skipped.
remote:        [INFO]
remote:        [INFO] --- jacoco-maven-plugin:0.7.9:report (post-unit-test) @ backend ---
remote:        [INFO] Skipping JaCoCo execution due to missing execution data file.
remote:        [INFO]
remote:        [INFO] --- maven-war-plugin:2.6:war (default-war) @ backend ---
remote:        [INFO] Packaging webapp
remote:        [INFO] Assembling webapp [backend] in [/tmp/build_a42031ccda04e8ab02893e018fb1a3ff/target/backend-0.0.1-SNAPSHOT]
remote:        [INFO] Processing war project
remote:        [INFO] Copying webapp webResources [/tmp/build_a42031ccda04e8ab02893e018fb1a3ff/src/main/webapp] to [/tmp/build_a42031ccda04e8ab02893e018fb1a3ff/target/backend-0.0.1-SNAPSHOT]
remote:        [INFO] Webapp assembled in [262 msecs]
remote:        [INFO] Building war: /tmp/build_a42031ccda04e8ab02893e018fb1a3ff/target/backend-0.0.1-SNAPSHOT.war
remote:        [INFO]
remote:        [INFO] --- spring-boot-maven-plugin:1.5.9.RELEASE:repackage (default) @ backend ---
remote:        [INFO]
remote:        [INFO] --- maven-install-plugin:2.4:install (default-install) @ backend ---
remote:        [INFO] Installing /tmp/build_a42031ccda04e8ab02893e018fb1a3ff/target/backend-0.0.1-SNAPSHOT.war to /app/tmp/cache/.m2/repository/com/okta/developer/backend/0.0.1-SNAPSHOT/backend-0.0.1-SNAPSHOT.war
remote:        [INFO] Installing /tmp/build_a42031ccda04e8ab02893e018fb1a3ff/pom.xml to /app/tmp/cache/.m2/repository/com/okta/developer/backend/0.0.1-SNAPSHOT/backend-0.0.1-SNAPSHOT.pom
remote:        [INFO] ------------------------------------------------------------------------
remote:        [INFO] BUILD SUCCESS
remote:        [INFO] ------------------------------------------------------------------------
remote:        [INFO] Total time: 14.257 s
remote:        [INFO] Finished at: 2018-01-25T20:37:40Z
remote:        [INFO] Final Memory: 55M/418M
remote:        [INFO] ------------------------------------------------------------------------
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 180M
remote: -----> Launching...
remote:        Released v5
remote:        https://test-2243.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/test-2243.git
   1f0b846..6de8d62  HEAD -> master

Your app should now be live. To view it run
	heroku open
And you can view the logs with this command
	heroku logs --tail
After application modification, redeploy it with
	jhipster heroku
[mraible:~/backend] 1m57s
```

**Comment by jdubois** [comment]
@jkutner everything is fine for me:

- I had to reinstall my heroku client
- it only works with postgresql as I removed my credit card (so MySQL isn't available)

For me it works perfectly, and the performance looks really good! That's awesome.

**Comment by jkutner** [comment]
I think @mraible's problem is due to the two different app name (one is created in the "Use it anyways? No, generate a random name" step, and then a different one is pushed to in the "Deploying application". I'll submit a PR to make sure those resolve the same if they are different.

**Comment by mraible** [comment]
I just tried this on a different machine and got a new error:

```
Installing Heroku CLI deployment plugin
✖ { Error: Command failed: heroku plugins:install --force heroku-cli-deploy
 ▸    Unexpected argument heroku-cli-deploy

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'heroku plugins:install --force heroku-cli-deploy' }
 conflict pom.xml
```

Here's my `heroku --version` information:

```
heroku-cli/6.15.18-fdf2097 (darwin-x64) node-v9.3.0
```

**Comment by jdubois** [comment]
@mraible your last error is the same I used to have, I did `brew install heroku/brew/heroku` and then `brew link --overwrite heroku` to re-install

**Comment by mraible** [comment]
@jdubois Running these commands seems to have fixed my problem and I was able to deploy an app to Heroku and the UI renders just fine. Huzzah!

**Comment by cbornet** [comment]
I guess we need to add this deployment option in the ci-cd subgen !

**Comment by jkutner** [comment]
@cbornet indeed. i could even have it setup the [Heroku Pipeline](https://devcenter.heroku.com/articles/pipelines) for you. I'll take a look

**Comment by cbornet** [comment]
Oh yes that would be awesome!!

**Pull request merged**
