### PR TITLE
Add Hooks.onOperatorDebug() and BlockHound to reactive apps

### PR DESCRIPTION
**Pull request by cbornet**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

See #7608

### CODE REVIEW

**Comment by cbornet** [comment]
Blockhound detects that Spring's `LocalValidatorFactoryBean` makes a blocking call !
I raised issue https://github.com/spring-projects/spring-framework/issues/24247

**Comment by DanielFran** [comment]
@cbornet We already migrate to spring-framework 5.2.4 that include the fix you were waiting...

**Comment by cbornet** [comment]
Let's rebase !

**Comment by cbornet** [comment]
Blockhound is merciless ! Blocking calls everywhere in places you would never suspect :sob:

**Comment by cbornet** [comment]
CI is green !

**Comment by cbornet** [comment]
@murdos @DanielFran Would you review ?

**Comment by DanielFran** [comment]
@cbornet time to migrate to R2DBC Arabba-SR3?

Maybe add it to jhipster bom:
<dependencyManagement> <dependencies> <dependency> <groupId>io.r2dbc</groupId> <artifactId>r2dbc-bom</artifactId> <version>Arabba-SR3</version> <type>pom</type> <scope>import</scope> </dependency> </dependencies> </dependencyManagement>

**Comment by cbornet** [comment]
@DanielFran  Yes we could do that. Or wait for Spring Boot 2.3 which will have support for R2DBC.

**Comment by cbornet** [comment]
Can we merge this ?

**Comment by murdos** [comment]
Sure. I'm trusting you here, you're our expert on the reactive domain.

**Comment by murdos** [comment]
@cbornet : I think these changes make the webflux integration tests unstable. Should we disable `Hooks.onOperatorDebug();` ?

**Comment by cbornet** [comment]
Can you point to a failing test ? I'll have a look.

**Comment by murdos** [comment]
You can easily find some by checking recent PR with failing webflux tests.
E.g. https://github.com/jhipster/generator-jhipster/pull/11555/checks?check_run_id=562680222

**Comment by cbornet** [comment]
Interesting. It's Blockhound which fails the test because of a blocking call in the bounded elastic scheduler service. That's the first time I see this. I'll investigate.

**Comment by mraible** [comment]
@cbornet Do we need Blockhound integrated for a beta release of our reactive support? I feel like we're sooooo close and this could be something that's integrated for v7 (or whenever we want to call it stable).

**Comment by cbornet** [comment]
Well, Blockhound is a really useful tool. I would even say that if you don't use it in your reactive app, then you are most probably blocking. In places where you would have never imagined. This issue for instance detected 2 blocking issues in the Spring code itself (and a 3rd one apparently in the bounded elastic scheduler).
That said, we can of course remove it for now. But we should have at least a daily build where it's activated so we can detect new blocking calls.

**Comment by DanielFran** [comment]
@cbornet now that we switch to spring-boot 2.3, should we give another try?

**Comment by cbornet** [comment]
We can't because of https://github.com/reactor/reactor-core/issues/2137 .

**Comment by cbornet** [comment]
Or we could whitelist BoundedElasticScheduler.schedule

**Pull request merged**
