### PR TITLE
Remove LocaleConfiguration

### LINKED ISSUE #20106: Drop AngularCookieLocaleResolver or rename
##### **Overview of the feature request**

Leftover from angularjs (angular 1).
https://github.com/angular-translate/angular-translate/blob/d727abb0cae045c1f645bb7a92f06f8240875987/src/service/storage-key.js

##### **Motivation for or Use Case**

Cleanup

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by shrralis**
remove LocaleConfiguration due to being a leftover from angularjs

Fix #20106

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by shrralis** [comment]
Not sure why it's failing

**Comment by DanielFran** [comment]
@shrralis we are using snapshot to validate changes on file generation
You need to update snapshots and it should fix the issue 
Also you need to add the deleted files to the cleanup list, so with the upgrade the files will be deleted too.

**Comment by shrralis** [comment]
@DanielFran sorry, it is my first time doing such kind of stuff.
Do I understand correctly I need to run `npm run update-snapshots` and it would apply some changes to the source files I need to commit as well?

@mshima I don't get what's wrong with Spring i18n. I believe it's being used by sending E-Mails only? If so, then there should be no problem since we creating a `new Context(Locale.forLanguageTag(user.getLangKey()))` and it's not dependent on the `LocaleConfiguration` we're removing (and I've re-checked, Spring i18n works as expected in E-Mails)

**Comment by mshima** [comment]
Translated error messages in api responses.
Would be nice to check if it resolves Accept-Language headers at least.
@DanielFran what do you think?

**Comment by shrralis** [comment]
@mshima well, I could revert the change and remove only this part:
```java
@Bean
public LocaleResolver localeResolver() {
    return new AngularCookieLocaleResolver("NG_TRANSLATE_LANG_KEY");
}
```
But still, I see that there's a `LocaleChangeFilter` configured which seems to be completely redundant to me because I couldn't find any usage of the `language` request param in the front-end part, so the locale never gets changed from what I see.

**Comment by DanielFran** [comment]
> Translated error messages in api responses. Would be nice to check if it resolves Accept-Language headers at least. @DanielFran what do you think?

@mshima Not sure it is working today?

**Comment by shrralis** [comment]
@DanielFran I'm not sure what I should check there. From what I saw, API error messages aren't i18n-ized and all of the i18n is being performed by frontend frameworks (except EMail sending).

**Comment by mraible** [comment]
@shrralis Can you please resolve conflicts in this PR?

**Comment by shrralis** [comment]
@mraible sure, done

**Review by mraible — APPROVED** [review]

**Comment by mraible** [comment]
@shrralis Thanks for your contribution!

**Comment by shrralis** [comment]
Bug bounty claimed https://opencollective.com/generator-jhipster/expenses/200339

**Pull request merged**
