### PR TITLE
Support Elasticsearch in reactive applications

### LINKED ISSUE #11536: Update entity generator to support Elasticsearch in reactive applications
##### **Overview of the feature request**

The last remaining item to move our Reactive/WebFlux support (https://github.com/jhipster/generator-jhipster/issues/7608) to beta is to update the entity generator and its tests to support Elasticsearch. 

##### **Motivation for or Use Case**

I'm opening these tasks as a new issue so we can assign a bug bounty to it and hopefully accelerate its development. Selfishly, I'd like to write a blog post about our WebFlux support in the next week or two.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by murdos**
Fixes #11536

- Use reactive web client provided by spring-data-elasticsearch rather than Jest
- Handle reactive search for User entity
- Handle reactive search for generated entities
- Changed `webflux-mongodb-session` sample to `webflux-mongodb-es-session` in order to have a webflux sample with elasticsearch

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by murdos** [comment]
@cbornet : it seems that blockhound makes webflux backend integration tests unreliable...

**Comment by mraible** [comment]
@murdos Anything I can do to help with this one? 

In the [project I created this week](https://github.com/mraible/mobile-jhipster), I used Elasticsearch and had a lot of problems with it. It seems that in dev mode (when it writes to the filesystem), you can't restart the app and have it work again. The index gets corrupted or something. 

I mention this because the main Elasticsearch implementation might be flaky. In fact, we might want to make it so it writes to the filesystem when testing but expects a Docker container to be running in dev.

**Comment by murdos** [comment]
@mraible : From my point of view, the PR is ready, it's just blocked by unrelated unstable webflux tests: https://github.com/jhipster/generator-jhipster/pull/11009#issuecomment-611062854
However I've not used it in real situation. 

Unless I'm misunderstanding what you said, the issue you mentioned with elasticsearch is not specific to reactive apps? 
Switching to a Docker container in dev might be a good idea, as we do for databases. It would just require a few changes to the application-dev.yml. V7 seems to a good opportunity to switch.

**Comment by mraible** [comment]
> Unless I'm misunderstanding what you said, the issue you mentioned with elasticsearch is not specific to reactive apps? ... V7 seems to a good opportunity to switch.

Correct. I agree we should make this change in v7 if you can't restart and have it work in dev mode.

**Comment by mraible** [comment]
Couchbase is failing, which doesn't seem to be unique to reactive apps. I think we should merge this PR, move reactive to beta, and celebrate! 🎉

**Comment by mraible** [comment]
Couchbase is failing, which is a common occurrence. Merging. :)

**Comment by murdos** [comment]
> I used Elasticsearch and had a lot of problems with it. It seems that in dev mode (when it writes to the filesystem), you can't restart the app and have it work again. The index gets corrupted or something.

@mraible : it looks like embedded node server is not officially supported by Spring Boot [since version 2.0](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide). And it doesn't work anymore with Spring Boot 2.3 and ES 7: https://github.com/jhipster/generator-jhipster/pull/11683

So we should have already switched to a Docker container for dev since quite some time ;-)

**Comment by mraible** [comment]
You are right, that's why I integrated Spring Data Jest, which does support the filesystem. I think it could still be useful for testing so you don't need to run Docker for tests.

https://github.com/VanRoy/spring-data-jest

**Pull request merged**
