### PR TITLE
Restructure all

### PR DESCRIPTION
**Pull request by deepu105**
move all generators into `generators` folder

### CODE REVIEW

**Comment by deepu105** [comment]
ill merge once travis passes, keeping this long will cause conflicts for all

**Comment by deepu105** [comment]
@pascalgrimaud the gradle build failed coz there is no permission for ./gradlew any idea why?

**Comment by pascalgrimaud** [comment]
You just moved files, right ?
it should keep all file permission... gradlew should has as least +x to be launched

**Comment by pascalgrimaud** [comment]
I saw it !!
app/templates/gradlew → generators/app/templates/gradlew 100755 → 100644

**Comment by pascalgrimaud** [comment]
Oh you are with windows ,if I remember well, that's explain
Same issues with :
app/templates/mvnw → generators/app/templates/mvnw 100755 → 100644

**Comment by deepu105** [comment]
can you change permissions and commit plz

**Comment by pascalgrimaud** [comment]
I would like but can't right now
I'm at work... I will do it just after lunch, in 2h~

**Comment by deepu105** [comment]
sure

**Comment by PierreBesson** [comment]
I can do it. It is just chmod +x on gradlew and mvnw right ?

**Comment by pascalgrimaud** [comment]
yes plz, Pierre :-)

**Comment by pascalgrimaud** [comment]
Forgot to thank you @PierreBesson 

I think these changes have an impact on our modules
cc @deepu105 @moifort @atomfrede @cbornet @geraldhumphries

**Comment by deepu105** [comment]
Oops ya forgot to mention that. This should not affect modules but the
angular structure change would affect

Thanks & Regards,
Deepu

**Pull request merged**
