### PR TITLE
Check home directory

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/7896

@leighadellinger : what do you think ?

@PierreBesson :
- the code is really simple, and it should work for all OS
- as discussed during  the OnBoarding, I reduce the timeout for git connection from 15sec to 5sec

warning_home_directory

### CODE REVIEW

**Comment by jdubois** [comment]
Yes but maybe point to the documentation to explain the issue (here we see the issue but don't understand what happens)

**Comment by pascalgrimaud** [comment]
@jdubois :
Is this documentation about 'Destination context' OK for you ? http://yeoman.io/authoring/file-system.html
If yes, I can add this link, something like:
> You are in your HOME folder! See the documentation at http://yeoman.io/authoring/file-system.html

Otherwise, I don't see any reference in our docs. Maybe we should add it ?

**Comment by jdubois** [comment]
I'd rather have something in our own documentation - I guess most people don't even know we're based on Yeoman, so that page will confuse them.

We need a section in the "installation" page.

-> if you don't have the time I'll do it, it's pretty simple

**Comment by pascalgrimaud** [comment]
Ok, I will do it.
I'll try to find time tonight, after the 2nd match :-)

Le sam. 30 juin 2018 à 18:46, Julien Dubois <notifications@github.com> a
écrit :

**Comment by PierreBesson** [comment]
I think the error message should state "this can cause problems, you should always create a new directory and run the jhipster command from here."

**Comment by pascalgrimaud** [comment]
@PierreBesson : I will add this

**Comment by pascalgrimaud** [comment]
Last update:

warning_home_directory1

**Comment by vishal423** [comment]
can we be more explicit on problems that it can cause so that end user can take correct decision? 
Also, is it possible to print path of .yo.rc.json during code generation if that's not in current directory and steps to fix?

**Comment by PierreBesson** [comment]
I would write it like that :

Generation choices will be stored in a .yo-rc.json file which yeoman uses to remember those choices when regenerating an application. Be warned that when running `jhipster` yeoman will pick up any existing .yo-rc.json file present in a parent directory.
So it is strongly recommanded to not generate a JHipster project in your HOME directory as this will create a parent .yo-rc.

**Comment by vishal423** [comment]
@pascalgrimaud, Per my understanding, it would happen if .yo-rc.json is present in any parent directory of current and not tied to only HOME directory. Following is the yeoman documentation explaining this:

> While running a generator, Yeoman will try to figure some things out based on the context of the folder it’s running from.
> 
> Most importantly, Yeoman searches the directory tree for a .yo-rc.json file. If found, it considers the location of the file as the root of the project. Behind the scenes, Yeoman will change the current directory to the .yo-rc.json file location and run the requested generator there.
> 
> The Storage module creates the .yo-rc.json file. Calling this.config.save() from a generator for the first time will create the file.
> 
> So, if your generator is not running in your current working directory, make sure you don’t have a .yo-rc.json somewhere up the directory tree.

**Comment by pascalgrimaud** [comment]
@vishal423 : yes, agree with you! But it's completely related to Yeoman not directly to JHipster. We can of course added this to documentation (see https://github.com/jhipster/jhipster.github.io/pull/594 as it can be improved maybe), but not to the generator itself, as it already displays a lot of information

**Comment by jdubois** [comment]
Yes, this is 100% due to Yeoman, that's supposed to be a feature, in fact.
The idea is that you could run that command in any directory of your application, and that would still work.
Of course, if you created your app in your home directory, then Yeoman thinks that everything inside your home directory is your app.
It's not a stupid feature, but it's surprising for many people. Then, I wouldn't recommend running an application inside your home directory, without reading the documentation or the warnings.

**Comment by vishal423** [comment]
To be specific to HOME, can we abort installation if user tries to install in HOME directory with appropriate message?

**Comment by deepu105** [comment]
Guys, I guess we do enough hand-holding already. So I would say in this case it's up to the user to at least read whats displayed on the console. We are talking about technically capable people here aren't we :wink: 

So let's leave this at it. We have more pressing stuff to spend time on, don't you agree?

**Comment by jdubois** [comment]
Yes and if someone wants to generate this in his home directory, let him do what it wants... I even do it from time to time when I set up a test server quickly

**Pull request merged**
