### PR TITLE
Remove mysql root user setting

### PR DESCRIPTION
**Pull request by deepu105**
Setting `MYSQL_USER` to `root` seems to fail with latest mySQL version being used when deployed as container

There are two more places where this is set for openshift but to non-root values so I guess that should be fine

here is the error I got

```
kubectl logs product-mysql-55fbb8fdd8-6dbwc -n jhipster         
2021-03-27 13:52:40+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
2021-03-27 13:52:40+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-03-27 13:52:40+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
2021-03-27 13:52:40+00:00 [ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_USER and MYSQL_PASSWORD are for configuring a regular user and cannot be used for the root user
    Remove MYSQL_USER="root" and use one of the following to control the root user password:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_ALLOW_EMPTY_PASSWORD
    - MYSQL_RANDOM_ROOT_PASSWORD
``` 

@jhipster/developers I also did the same for MariaDB but not usre about that can someone take a second look as well
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
Related with this fix: https://github.com/jhipster/generator-jhipster/commit/22c630dbcaa9aac678d9334128e4892bc3b8a77e

**Comment by deepu105** [comment]
So does it apply for MariaDB as well? I haven't tried with it

**Comment by DanielFran** [comment]
@deepu105 did not found same changes for Mariadb

**Comment by deepu105** [comment]
Oh my PR had same change for MariaDB yaml files as well, so probably I
should revert that. I have never used or followed MariaDB so not sure how
diverged it is from MySQL

**Pull request merged**
