### PR TITLE
[React] Update react-jhipster version to 0.21.0

### PR DESCRIPTION
**Pull request by qmonmert**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by qmonmert** [comment]
Same bug as us https://stackoverflow.com/questions/73150968/chakra-ui-react-hook-form-error-wrong-types (ticket opened today)

**Comment by qmonmert** [comment]
@DanielFran possible solution for now, I think a new version of `react-hook-form` will be available soon

**Comment by DanielFran** [comment]
Thanks @qmonmert for the fix.
Let's merge it and wait for new version of react-hook-form

**Review by DanielFran — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
@qmonmert : I'm adding a bounty, as you spent lot of time to test and for helping to prepare the release

**Comment by qmonmert** [comment]
thanks @pascalgrimaud :) https://opencollective.com/generator-jhipster/expenses/88101

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Pull request merged**
