### PR TITLE
Upgrade Liquibase to 4.11.0

### LINKED ISSUE #18071: Bump liquibase-core from 4.6.1 to 4.12.0 (Security alert)
Improper Restriction of XML External Entity Reference in Liquibase

The XMLChangeLogSAXParser() function in Liquibase prior to version 4.8.0 contains an issue that may lead to to Improper Restriction of XML External Entity Reference.

Package: org.liquibase:liquibase-core
Affected versions: < 4.8.0
Patched version: 4.8.0

image

### PR DESCRIPTION
**Pull request by mraible**
Fixes #18071. 

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@mraible liquibase > 4.6.2 uses h2-2.x (actually 2.1.210) but spring-boot will only update it in v.2.7

I tried manually in a monolithic project with h2-disk and did not find issues, so it is OK.

**Comment by DanielFran** [comment]
Trying to fix react issues with https://github.com/jhipster/generator-jhipster/pull/18073

**Review by DanielFran — DISMISSED** [review]

**Comment by DanielFran** [comment]
@mraible react pipeline has been fixed.
Can you rebase?

**Comment by DanielFran** [comment]
Seems there is issues with MySQL/Mariadb

**Comment by mraible** [comment]
Speaking of MySQL, I tried to do a screencast today with JHIpster 7.7 and MySQL on my MacBook Pro M1 Max and it totally failed when I ran `docker compose up`. 

I eventually found out that you need to specify a `platform` parameter for Apple Silicon. https://stackoverflow.com/a/70668476/65681

To me, this seems to indicate that not many folks are using M1s to create JHipster apps or we'd have more issues.

**Comment by mraible** [comment]
I tried running the `vue-fulli18n-es` app with Liquibase 4.8.0 and all e2e tests pass. I'm not sure if the CI failures are related to this PR.

**Comment by mraible** [comment]
Failures might be related to https://github.com/liquibase/liquibase/issues/2634.

**Comment by DanielFran** [comment]
@mraible Should be fixed with https://github.com/liquibase/liquibase/pull/2752

Looking for next liquidate release

**Comment by DanielFran** [comment]
@mraible the update to 4.10.0 seems not to solve all issues

**Comment by mraible** [comment]
@DanielFran That's unfortunate. Maybe we should start putting bug bounties on Liquibase issues? ;)

**Comment by DanielFran** [comment]
@mraible liquibase 4.6.1+ needs spring-boot 2.7 so I will close this PR in favour of https://github.com/jhipster/generator-jhipster/pull/18511

**Comment by mraible** [comment]
@DanielFran I found that Liquibase 4.11.0 doesn't work with MariaDB and Spring Boot 2.7.0. 4.6.1 does seem to work just fine.

**Pull request closed without merging**
