### PR TITLE
Always define string enum for React

### LINKED ISSUE #11215: Enum Not Usable in ReactUI Conditions
##### **Overview of the issue**

I have some ENUM in my Monolith Project. I make some changes to the REACT frontendcode, but ENUM not working in production build.
In develop-mode I can compare the ENUM value from the Entity with a String, but not with the ENUM-Entity itself. But for the production build, the validation engine put out an error, that an comparison of ENUM and String isn't valid.

ENUM Definition from JDL File:
`enum MatchStatus {
  NONE, CREATED, SCHEDULED, READY, RUNNING, FINISHED, APPROVED
}`

1) Comparison that works in react:
`if (entity.matchStatus == 'RUNNING') {...}`

2) Comparison Works NOT in frontend:
`if (entity.matchStatus == MatchStatus.RUNNING) {...}`

Point 1 works in develop, but can't package it for production.
Point 2 can package for production, but not working.

commandline command that I use
`mvn -Pprod,swagger clean verify`

##### **Reproduce the error**

JDL:

```
application {
  config {
    applicationType monolith
    baseName example
    packageName com.example.my
    buildTool maven
    authenticationType jwt
    clientFramework react
    cacheProvider ehcache
    prodDatabaseType mariadb
    devDatabaseType h2Disk
    nativeLanguage en
    languages [en,de]
    useSass true
  }
  entities *
}

enum MatchStatus {
  NONE, CREATED, SCHEDULED, READY, RUNNING, FINISHED, APPROVED
}

entity Match {
    name String
    status MatchStatus
}
```

Then in the match list I change the code of the status column to show different colored icons for each status.

```
{ (() => {
                    switch (tournamentMatch.status) {
                      case 'READY':
                        return <span className="match-status-ready"/>;
                      case 'RUNNING':
                        return <span className="match-status-running"/>;
                      case 'FINISHED':
                        return <span className="match-status-finished"/>;
                      default:
                        return '-';
                    }
                  })() }
```
With string cases it works fine, but can't build for production

```
[INFO] Webpack: Starting ...
[INFO] Starting type checking service...
Webpack: Starting ...
[INFO] 
[INFO]    ✔ Compile modules
[INFO]    ✔ Build modules
[INFO]    ✔ Optimize modules
[INFO]    ✔ Emit files
[INFO] 
[INFO] Webpack: Finished after 49.419 seconds.
[INFO] 
[INFO]  ERROR  Failed to compile with 3 errors8:16:54 PM
[INFO] 
[INFO] ERROR in /..../matches.tsx
[INFO] TS2678: Type '"READY"' is not comparable to type 'MatchStatus'.
[INFO] 
[INFO] ERROR in /..../matches.tsx
[INFO] TS2678: Type '"RUNNING"' is not comparable to type 'MatchStatus'.
[INFO] 
[INFO] ERROR in /..../matches.tsx
[INFO] TS2678: Type '"FINISHED"' is not comparable to type 'MatchStatus'.
```

The entity enum is compared as a string, but the enum itself is compare as a number

##### **Environment and Tools**

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)

git version 2.25.0

node: v13.7.0

npm: 6.13.6

yeoman: 3.1.0

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.2, build 698e2846

##### **Browsers and Operating System**

Operating System ist latest macOS Catalina.

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by foxable**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
thanks and congrats for your 1st contribution @foxable

**Comment by tibistibi** [comment]
Interesting, if we initialize them for React why did we moved from initialization to NOT initialization for Angular?

**Comment by pascalgrimaud** [comment]
@tibistibi : good idea. feel free to propose a pull request for Angular too

**Comment by tibistibi** [comment]
@pascalgrimaud thanks but it seems that it was just removed. When I used version 6.2.0 and before it was always initialized. So I wondered why it was changed (and by who ;) )

**Comment by vicpermir** [comment]
@pascalgrimaud I've sent PR #11408 to fix this in angular, let me know if I did something wrong (checks are in progress).

Also, related to the following question in SO: [How should I do an Enum comparison in typescript](https://stackoverflow.com/questions/60415624/how-should-i-do-an-enum-comparison-in-typescript)

**Comment by tibistibi** [comment]
@vicpermir thats fast!!!

**Pull request merged**
