### PR TITLE
Move client app to classpath:/public

### LINKED ISSUE #9118: Move client app to classpath:/public
##### **Overview of the feature request**

By default Spring-boot serves anything that is into `classpath:/public`
So I propose to build the client into `target/classes/public` instead of `target/www`.
With this we can remove our custom addition of static assets for IDEs in WebConfigurer.
So far I've tested with IDEA, maven, and `java -jar`. Not yet by deploying in an app server, not yet with gradle.
We have a lot of ways to run the app and it can be tricky. Do you see use-cases I'm missing ?

##### **Motivation for or Use Case**

* Policy 1, less custom code
* Our current implementation can have a bad effect if someone runs the prod war from a dir that has a `target/www` directory. In that case our detection will serve what is in this folder instead of what is in the war.
* This would be compatible with Webflux (our current is not : you can't do `setDocumentRoot` in Webflux)
* After that, we may be able to use Spring's built-in cache control instead of our custom cache filter.

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by cbornet**
Fix #9118 

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
Note : with this, there is no index.html error page when you start the IDE without first building the front-end (the one with instructions on how to troubleshoot).
So should we put index.html in `src/main/resources/public` ? Maybe also other resources that are not processed by webpack like favicon, loading.css, ... ?

**Comment by deepu105** [comment]
@cbornet what about the issues with web servers that forced us to revert this last time? did you test that? cc @ruddell

**Comment by deepu105** [comment]
Also is the move from `src/webapp` to `src/www` necessary? I personally like the `webapp` folder name as its clearer even to novice devs and also I would like to avoid an unnecessary breaking change if possible

**Comment by cbornet** [comment]
The problem is that by default the maven-war-plugin copies everything that is in src/main/webapp to the root of the war

**Comment by cbornet** [comment]
@deepu105 if it's important to keep the code in src/main/webapp it should be possible to prevent the copy by configuring maven-war-plugin with packageExcludes.

**Comment by cbornet** [comment]
There is a discussion on this in #9118 . Let's discuss there !

**Comment by cbornet** [comment]
Eventually I've left the client source code in `src/main/webapp` for the moment. We can move it to another dir later.
I tested the following which seem to work:
* maven/gradle
* angular/react
* executable war
* war.original in Tomcat
* docker/jib
* launch from IDE
* no devtool reload on /static change

**Comment by deepu105** [comment]
So there is no encoding issue when running in Tomcat?

**Comment by cbornet** [comment]
No everything looks fine for me. Would you double check ?

**Comment by deepu105** [comment]
Unfortunately I'm on a tight schedule, may be @ruddel can help

**Comment by ruddell** [comment]
This PR still has the same issue that the other one had.

Steps to reproduce:
 - Generate an app. I recommend a UAA gateway with no database and no service discovery, otherwise you have to set up a database reachable by Tomcat.
```
{ "generator-jhipster": { "promptValues": { "packageName": "com.mycompany.myapp", "nativeLanguage": "en" }, "jhipsterVersion": "5.8.1", "applicationType": "gateway", "baseName": "jhipster", "packageName": "com.mycompany.myapp", "packageFolder": "com/mycompany/myapp", "serverPort": "8080", "authenticationType": "uaa", "uaaBaseName": "uaa", "cacheProvider": "no", "enableHibernateCache": false, "websocket": false, "databaseType": "no", "devDatabaseType": "no", "prodDatabaseType": "no", "searchEngine": false, "messageBroker": false, "serviceDiscoveryType": false, "buildTool": "maven", "enableSwaggerCodegen": false, "clientFramework": "angularX", "useSass": true, "clientPackageManager": "npm", "testFrameworks": [], "jhiPrefix": "jhi", "entitySuffix": "", "dtoSuffix": "DTO", "otherModules": [], "enableTranslation": true, "nativeLanguage": "en", "languages": [ "en" ] } }
```
 - Add `<h2>&nbsp; &euro; &times;</h2>` to `home.component.html`
 - Package into war
 - Start Tomcat, I used below docker-compose:
```
version: '2'
services:
    tomcat:
        image: tomcat:8-jre8-alpine
        ports: 
            - 8080:8080
```
 - Copy `.war.original` to the Tomcat container 
```
docker cp target/jhipster-0.0.1-SNAPSHOT.war.original tomcat-container-id:/usr/local/tomcat/webapps/issue.war   
```
 - Open app once launched through Tomcat at http://localhost:8080/issue/

The string added above looks like `Â  â‚¬ Ã—` but it should look like &nbsp; &euro; &times;

**Comment by cbornet** [comment]
Thanks @ruddell . I could reproduce. So now I can probably fix it :wink:

**Comment by cbornet** [comment]
I think I found the cause : Tomcat has a charset mapper which [defaults to ISO-8859-1 for en and fr](https://github.com/apache/tomcat/blob/c4b006e3dd46ca8604b2c9418a4714b6261aab7c/java/org/apache/catalina/util/CharsetMapperDefault.properties).
If you change your browser language to something else then the issue disappears.
When using the embedded Tomcat, Spring overrides the default mapping in `resetDefaultLocaleMapping()`.

So we could:
1 / add a `web.xml` with `<locale-encoding-mapping-list>` with locales that we want to map to UTF-8 encoding.
2/ Or add a `web.xml` with `<mime-mapping>` to map `html` to `text/html;charset=utf-8`

I think 2/ is better since it will force UTF-8 whatever the locale and is closer to what we do for the embedded Tomcat in `WebConfigurer::setMimeMappings()`

Note : I haven't found a way to do it in Java with the ApplicationWebXml initializer.

**Comment by cbornet** [comment]
Everything should be OK now. @ruddell @deepu105 can you test ?

**Comment by ruddell** [comment]
The Tomcat encoding issue is fixed with your latest changes 👍

**Comment by deepu105** [comment]
@cbornet @ruddell go ahead and merge if you guys have tested it

**Pull request merged**
