### PR TITLE
add Sort direction to get all Entities Test

### LINKED ISSUE #2361: Unit test getAllEntities() fail for a Entity with more than 19 rows.
When a entity is populated with more than 19 items, the test "getAllEntities()" fail, how a small contribution to this awesome project i suggest add a sort direction to the GET url using the id field:

        restSkosPropertyMockMvc.perform(get("/api/entities?sort=id,DESC"))

### PR DESCRIPTION
**Pull request by lsolisc**
Fix #2361

### CODE REVIEW

**Comment by geraldhumphries** [comment]
`DESC` is uppercase which is inconsistent with #2314. I think one of them should be changed - the sort direction should either be in uppercase everywhere or lowercase everywhere. @jdubois, what do you prefer?

**Comment by cbornet** [comment]
I'm not sure what this does if the entity doesn't support pagination. I guess its OK since the CI tests where OK. But still, shouldn't this be done only if entity has pagination activated ?

**Comment by geraldhumphries** [comment]
The API will ignore the params. I do agree that they shouldn't be in the tests if there is no pagination, however.

**Comment by deepu105** [comment]
I thinks its better to have lowercase

**Comment by jdubois** [comment]
@deepu105 agreed, I'll merge this with lowercase
I also find that's a good example of using Spring MVC REST with Spring Data

**Pull request merged**
