### PR TITLE
bump execa from 8.0.1 to 9.0.2

### PR DESCRIPTION
**Pull request by qmonmert**
Fix https://github.com/jhipster/generator-jhipster/pull/26101

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by qmonmert** [comment]
@DanielFran we must wait a new release of the lib https://github.com/sindresorhus/execa/issues/1036

**Comment by qmonmert** [comment]
@DanielFran try `9.0.1` but its not working for the moment https://github.com/sindresorhus/execa/issues/1040

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
Thanks @qmonmert for the fix!
Added a bug bounty

**Comment by qmonmert** [comment]
@DanielFran thanks a lot https://opencollective.com/generator-jhipster/expenses/202147

**Comment by DanielFran** [comment]
@qmonmert approved

**Pull request merged**
