### PR TITLE
[v6] - upgrade jhipster lib to 3.9.1

### PR DESCRIPTION
**Pull request by pascalgrimaud**
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]

**Review by gmarziou — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
@gmarziou : if needed, I can do a patch release for v6
But I remember an issue with Redis, we need to fix it before doing a release

**Comment by gmarziou** [comment]
An issue with Redis due to this Undertow update?

**Comment by pascalgrimaud** [comment]
@gmarziou : no, it's this one https://github.com/jhipster/generator-jhipster/issues/12817

**Comment by gmarziou** [comment]
I think that a vulnerability fix should be released as soon as possible, but I'm not the one who does the job 😃

**Comment by pascalgrimaud** [comment]
ok then, will try to do a release before the end of week

**Comment by gmarziou** [comment]
Great, thanks

**Pull request merged**
