### PR TITLE
[vue] Fix OneToOne fields binding in update entity select

### LINKED ISSUE #15130: vue does not display relations in edit view out of box
##### **Overview of the issue**

Selections for relationships seem to be broken in vue. The for loop uses a non existing property.

##### **Motivation for or Use Case**

It should work out of box.

##### **Reproduce the error**
 
Import following JDL:

```
application {
  config {
    baseName hike
    applicationType monolith
    authenticationType oauth2
    packageName com.github.atomfrede.example.hike
    prodDatabaseType postgresql
    testFrameworks [cypress]
    buildTool gradle
    clientFramework vue
  }
  entities *
}
entity HikingLocation {
    name String required
    description String required
}
entity Hike {
    name String required
    date LocalDate required
    description TextBlob required
    photo ImageBlob required
    type Difficulty required
    length Integer required
}
enum Difficulty {
  EASY,
  MEDIUM,
  HARD,
  ULTRA
}
relationship OneToOne { 
  Hike{startLocation(name)} to HikingLocation,
  Hike{destination(name)} to HikingLocation
}
paginate Hike with pagination
paginate HikingLocation with pagination
```

Try to edit a `Hike`. You will notice the location selectors are empty.

##### **Related issues**

None.

##### **Suggest a Fix**

```
  <option
                v-bind:value="
                  hike.startLocation && hikingLocationOption.id === hike.startLocation.id ? hike.startLocation : hikingLocationOption
                "
                v-for="hikingLocationOption in startLocations"
                :key="hikingLocationOption.id"
              >
                {{ hikingLocationOption.name }}
              </option>
```

`startLocations` does not exist. They correct property would be `hikingLocations`.

##### **JHipster Version(s)**

Latest main.

##### **JHipster Version(s)**

```
hike@0.0.0 /home/fred/jug-bonn-jdl-3
└── generator-jhipster@7.0.1 -> /home/fred/git/github/jhipster/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "clientFramework": "vue",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": true,
    "withAdminUi": true,
    "baseName": "hike",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["cypress"],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "com.github.atomfrede.example.hike",
    "packageFolder": "com/github/atomfrede/example/hike",
    "jhipsterVersion": "7.0.1",
    "skipServer": false,
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": ["HikingLocation", "Hike"],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "nativeLanguage": "en",
    "creationTimestamp": 1622047196898,
    "lastLiquibaseTimestamp": 1622047316000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity HikingLocation {
  name String required
  description String required
}
entity Hike {
  name String required
  date LocalDate required
  description TextBlob required
  photo ImageBlob required
  type Difficulty required
  length Integer required
}
enum Difficulty {
  EASY,
  MEDIUM,
  HARD,
  ULTRA
}

relationship OneToOne {
  Hike{startLocation(name)} to HikingLocation
  Hike{destination(name)} to HikingLocation
}

paginate HikingLocation, Hike with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

git version 2.31.1

node: v14.16.1

npm: 7.11.1

Docker version 20.10.6, build 370c28948e

docker-compose version 1.29.2, build unknown

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by swarajsaaj**
Fix #15130

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
At angular, `${relationshipFieldNamePlural}Collection` Is filtered for one-to-one available values while `${otherEntityName}Collection` isn't.
Don’t know about vue.

**Comment by swarajsaaj** [comment]
@mshima In Angular, somehow there are multiple `${relationshipFieldNamePlural}Collection` arrays created (`startLocationsCollection` and `destionationLocationsCollection`) even for the same relationship target entity (`HikingLocation`).

https://github.com/jhipster/generator-jhipster/blob/717d172efbbe35d0fb862cd11299f6c308bf034b/generators/entity-client/templates/angular/src/main/webapp/app/entities/update/entity-management-update.component.ts.ejs#L91-L93

But in Vue, only a single array for options is created in component i.e. `relationshipFieldNamePlural` (`hikingLocations`)

https://github.com/jhipster/generator-jhipster/blob/717d172efbbe35d0fb862cd11299f6c308bf034b/generators/entity-client/templates/vue/src/main/webapp/app/entities/entity-update.component.ts.ejs#L306

**Review by mshima — APPROVED** [review]
LGTM.

**Comment by swarajsaaj** [comment]
bounty claimed at https://opencollective.com/generator-jhipster/expenses/43269

**Comment by pascalgrimaud** [comment]
@swarajsaaj : approved and thanks for your work!

**Pull request merged**
