### PR TITLE
Fix translate for sr & vi languages

### PR DESCRIPTION
**Pull request by nkolosnjaji**
Am I missing something more for angular2 ?

### CODE REVIEW

**Comment by ruddell** [comment]
`_reset.json` is missing the changes for Angular 2 for those languages too

**Comment by kaidohallik** [comment]
In Estonian language migration to angular2 I made changes in PR #4637

**Comment by nkolosnjaji** [comment]
@kaidohallik "et" / estonian is fine :)
@ruddell you are right, I will make fix asap.

**Comment by kaidohallik** [comment]
@nkolosnjaji In #4637 you can see what changes were needed. This [commit](https://github.com/jhipster/generator-jhipster/pull/4637/commits/47823390cf010a59cd697015af0bc17918161cb4) was merged.
4 files changed, 2 you already changed, 1 was referenced by @ruddell and 1 left: _activate.json

**Comment by kaidohallik** [comment]
@ruddell Sorry, I misread, you already mentioned _activate.json

**Comment by nkolosnjaji** [comment]
@kaidohallik thanks. Language pipe was already merged in another pull https://github.com/jhipster/generator-jhipster/pull/4944

**Pull request merged**
