### PR TITLE
Implement domain support at entity-server.

### PR DESCRIPTION
**Pull request by mshima**
This PR implements domain support for entities.
```
@domainName(Bar)
entity Foo {}
```

`domainName` is been used instead if `domain` due to conflict with exiting `domain` property (probably EventEmitter class).
To use `domain` would require us to stop using the generator as template data.

Related to https://github.com/jhipster/generator-jhipster/issues/11122

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
thanks @mshima : I'll review it when possible. If I forget, plz remind me :)

**Comment by pascalgrimaud** [comment]
@mshima : I just give a try and there is some good progress. Thanks a lot for working so fast.
Anyway, there is an important thing we should take into consideration:
In `domainName/domain/`, each class should not import any framework. It should be only default java import

It means:
- `domain/model/Entity.java` should be moved to infrastructure/secondary/entity/Entity.java
- service should be in `domainName/application`
- etc

**Comment by mshima** [comment]
@pascalgrimaud thanks for trying it.

> In `domainName/domain/`, each class should not import any framework. It should be only default java import

I think it can have basic validations from `javax.validation.*`.

> * `domain/model/Entity.java` should be moved to infrastructure/secondary/entity/Entity.java

This is the step I was talking about, every adapter/port should have it's own DTO, or can have.
I am not sure if we should move current entity to secondary or create a new DTO there.

Anyway this is a domain kickstart, I would prefer to put in domain branch instead of my own, creating PRs and discussing there.

1 - If you agree I can create a PR without domain support. Only files, packages, etc configuration to be merged to master to prevent too many conflicts.
2 - And create domain branch.

or just create domain branch.

**Comment by pascalgrimaud** [comment]
I think when using this feature, DTO is mandatory. In fact, I tried using this config:
```
    "entitySuffix": "Entity",
    "dtoSuffix": "",
```

It seems dtoSuffix can't have "" value.

Yes about "domain" branch, you should have the permission to do it
No, don't split your work here, it's already very good start and I don't want you lost too much time on splitting.
Let's create this domain branch and let's work on this !

**Comment by mshima** [comment]
Closed in favor of domain branch.

**Pull request closed without merging**
