### PR TITLE
Login redirect doesn't work in OAuth2 and Vue

### LINKED ISSUE #13042: Login redirect doesn't work in OAuth2 and Vue
##### **Overview of the issue**

If you're using Vue + OAuth 2.0 and try to navigate directly to a URL (e.g., `http://localhost:8080/admin/health`), you get an error page rather than redirected to log in.

Screen Shot 2020-11-14 at 2 04 34 PM

Inspired by https://github.com/jhipster/generator-jhipster/issues/13010. 

NOTE: I tested Angular and it works as expected.

##### **Motivation for or Use Case**

The best user experience is you're prompted to log in, then returned to where you started.

##### **Reproduce the error**

Create an app with the following `.yo-rc.json`:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.andespetro.tms"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "tms",
    "packageName": "com.andespetro.tms",
    "packageFolder": "com/andespetro/tms",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1604848055606,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "reactive": false,
    "pages": [],
    "withAdminUi": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"]
  }
}
```

Start the app, then try to navigate directly to http://localhost:8080/admin/health. You'll get an error rather than being redirected to log in.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/13010

##### **JHipster Version(s)**

`main` branch on Nov 14, 2020.

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #13042 

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
This appears to work. There is a flash of a "forbidden" error and then it redirects to Keycloak to login.

Minor nit: Vue seems to bold all the top nav menu items, except for Home.

**Review by mraible — APPROVED** [review]

**Comment by qmonmert** [comment]
@mraible I fix CSS bug in nav menu

**Comment by mraible** [comment]
It looks like there's a failing test.

**Comment by qmonmert** [comment]
@mraible it was a false positive, I restarted builds and it's ✅  🙂

**Pull request merged**
