### PR TITLE
Update spring-boot to 2.0.5 and dependencies

### PR DESCRIPTION
**Pull request by DanielFran**
Dependent on https://github.com/jhipster/jhipster/pull/94 and https://github.com/jhipster/jhipster/pull/95

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@jdubois This is necessary to migrate to spring-boot 2.0.5 ;)

**Comment by DanielFran** [comment]
On hold till spring-data-jest support JEST 5.3.4: https://github.com/VanRoy/spring-data-jest/issues/84

**Comment by DanielFran** [comment]
@jdubois Ready also.

**Comment by DanielFran** [comment]
@jdubois jhispter/jhispter is now green ;)

**Comment by jdubois** [comment]
Thanks a lot, I'll merge and release today (unless something else broke the build, too many commits recently!)

**Pull request merged**
