### PR TITLE
Adding i18n Greek Language support

### PR DESCRIPTION
**Pull request by dimitrisli**
Adding i18n Greek Language support

### CODE REVIEW

**Comment by andidev** [comment]
Could you also translate the entity and enum files in
https://github.com/jhipster/generator-jhipster/tree/master/entity/templates/src/main/webapp/i18n

**Comment by dimitrisli** [comment]
Thanks, I've added the 2 new files

**Comment by jdubois** [comment]
I just tested it with an entity and I got this error in the Chrome console:

    Error: Plural Function not found for locale: gr
    at new MessageFormat (messageformat.js:26)
    at Object.$translateInterpolator.setLocale (angular-translate-interpolation-messageformat.js:82)

I'm not sure if this is related to your code of if this is a general error, I need to check further

**Comment by jdubois** [comment]
I confirm this is specific to your code.

**Comment by dimitrisli** [comment]
I think this is happening because of my **_enum_gr.json** file that had code prior to [this fix](https://github.com/bfreire/generator-jhipster/commit/1c639dcf12c880bd882444f3a092e24d2a458a88).

Will be adressing now..

**Comment by dimitrisli** [comment]
I'm getting following error inTravis: "JHipster generator  "before all" hook:     Error: timeout of 2000ms exceeded"

Any ideas please?

The file is straightforward and identical to all other enum files in same directory.

thanks,
Dimi

**Comment by dimitrisli** [comment]
Attempting to trigger Travis CI build again since failure seems not related to my checkin by closing and reopening the PR

**Comment by dimitrisli** [comment]
Ok that worked. Please review my new file checkin and let me know if any more issues.

**Comment by jdubois** [comment]
I just tested your PR and I got a 404 error:

    http://127.0.0.1:8080/bower_components/messageformat/locale/gr.js

This is why you can have this error in the entities:

    Error: Plural Function not found for locale: gr

This is something we are going to need even more in the future, if we work on the pluralization of our endpoints, so I can't merge it at the moment.

It looks like Greek isn't supported yet in messageformat.js

Please note I haven't work on this myself, so I didn't select messageformat.js -> there is still work to be done here.

I don't think you can solve this unless you correct messageformat.js yourself -> that would of course be great, and I encourage you to do so!!!! But in the meantime you can't solve that issue, and I'm very sorry about it but I can't merge your PR.
Don't hesitate to send a new PR if you correct messageformat.js!!!

**Comment by deepu105** [comment]
@jdubois I didnt have this issue, I guess i was checking with tamil added by my collegue, it was already in messageformat folder as ta.js hence it works as we add it to index automatically during generation

**Pull request closed without merging**
