### PR TITLE
Add dependabot.yml file for automatic version upgrades [ci skip]

### PR DESCRIPTION
**Pull request by SudharakaP**
This adds dependabot.yml file to leverage native support for dependabot through GitHub

Related to https://github.com/jhipster/generator-jhipster/issues/11914

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
let's give it a try in main generator-jhipster

**Comment by SudharakaP** [comment]
@pascalgrimaud : Thanks for merging. :smile:

**Comment by pascalgrimaud** [comment]
Following this merge, there are a lot of PR: https://github.com/jhipster/generator-jhipster/pulls
I don't think it is usefull to launch the full build, as the dependencies are related to the generated project
So I think launch `npm test` for these PR would be enough

What do you think @SudharakaP ?

**Comment by SudharakaP** [comment]
@pascalgrimaud : Done at https://github.com/jhipster/generator-jhipster/issues/11962.

**Pull request merged**
