### PR TITLE
Add relationship name, so multiple A->B relation could co-exists

### PR DESCRIPTION
**Pull request by gzsombor**
This is a breaking change, as the name of the join table will be different.

### CODE REVIEW

**Comment by jdubois** [comment]
This is a much-needed improvement, so I'm merging this, as I want this ASAP.

Some notes:

- Yes this is a breaking change. But it's not that big: can you write (as comments here, no worries) about how to upgrade? So I can write it in the release notes of the 2.2.0 version
- You didn't do the Hungarian translation, which is another of your PRs -> can you add it, as another PR?
- I don't really have the time to test at the moment, so this might delay the 2.2.0 version a bit, but for me it's more important to have this feature

**Comment by jdubois** [comment]
@gzsombor maybe I merged this a bit quickly... Here is what I would rather have:

- Ask the name of the other entity before the name of the relationship
- Then, when you ask the name of the relationship, you have by default the name of the other entity, like it was before

-> that way, it's as easy as it used to be for people who have just one relationship between 2 entities, which is the normal use case

@gzsombor Can you have a look at it? Otherwise I'll do it, no problem

**Comment by gzsombor** [comment]
Thanks, I can implement your suggestions, for tomorrow, if it's ok for you.

**Comment by jdubois** [comment]
Yes of course!
I'm testing the current implementation at the moment

**Comment by jdubois** [comment]
Oups, I'm having all kind of errors since I merged your PR :-(
I'm doing many-to-many relationships, and it looks like it causes the issues, did you try them?

**Comment by gzsombor** [comment]
I've tested mainly on my branch, probably I've broke something, when I backported to the official one

**Comment by jdubois** [comment]
@gzsombor I confirm, many-to-many relationships are not working

**Pull request merged**
