### PR TITLE
Run prettier on ts files using yeoman transform streams

### LINKED ISSUE #7172: Prettier runs too late and causes conflicts during re-generation
Currently, prettier runs after code generation.

Due to this, when re-generating an entity or an app, yeoman shows many conflicts (~25% of generated files) only due to reformatting that runs later.

I don't know enough yeoman to say whether it is easy to run prettier after template rendering and before yeoman compares file contents.

### PR DESCRIPTION
**Pull request by gmarziou**
Currently applies to app generator only.

Fix #7172

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by gmarziou** [comment]
Nice work @deepu105.
When I did it also on entity-client and run `jhipster --with-entities` on jhipster-sample-app I noticed that registerTransformStream() was called 4 times: one for the app and 3 for the 3 entities. I haven't run same test on your code but I was wondering whether this could be a problem.

**Comment by deepu105** [comment]
It shouldn't be from the tests I did, but ya lets keep an eye on it

**Comment by gmarziou** [comment]
Anyway looks good to me

**Comment by deepu105** [comment]
Need to figure out failing tests, seems like from transform streams

**Comment by deepu105** [comment]
merging manually

**Pull request merged**
