### PR TITLE
Fixing camel cased app names

### LINKED ISSUE #3117: Camel cased app names are not correctly handled
##### **Overview of the issue**

When generating an application with a camel cased name like `GatewayMobile`, the M capitalization is not used in several places resulting in names that do not follow their respective naming conventions

|  Object              | actual name     | expected name |
|  ------------------- |  ------------------- |   ------------------- | 
| maven artifact | gatewaymobile | gateway-mobile |
| spring boot main class | GatewaymobileApp.java  | GatewayMobileApp.java |
| angular app | gatewaymobileApp  | gatewayMobileApp |

### PR DESCRIPTION
**Pull request by wmarques**
Fix #3117.
GatewayMobile is gateway-mobile (artifact, npm package name, gradle root name), GatewayMobileApp (Class name) and gatewayMobileApp (AngularJS module name).

### CODE REVIEW

**Comment by wmarques** [comment]
If someone can cancel [this build](https://travis-ci.org/jhipster/generator-jhipster/builds/114795732), it will fail as I forgot to define a variable. Sorry !

**Comment by gmarziou** [comment]
This looks great William, I'll test it tonight.

**Comment by gmarziou** [comment]
I tested it successfully with maven and gradle.

**Comment by jdubois** [comment]
I don't know what's happening with the Travis build, but this is has nothing to do with this PR, so I'm merging it.

**Pull request merged**
