### PR TITLE
WIP -use spring reactive repository implementation as implementation parent

### PR DESCRIPTION
**Pull request by Tcharl**
Should fix https://github.com/jhipster/generator-jhipster/issues/17271 when it will be achieved
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
I used this branch to create a webflux app earlier today. It runs just fine on the JVM (`npm run e2e` passes), but when I convert it to a native app with Spring Native, it fails with the following error on startup:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 
'userService': Unsatisfied dependency expressed through constructor parameter 0; nested exception is 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Invocation of 
init method failed; nested exception is java.lang.IllegalStateException: No suitable constructor found on class 
org.springframework.data.r2dbc.repository.support.SimpleR2dbcRepository to match the given arguments: 
org.springframework.data.relational.repository.support.MappingRelationalEntityInformation, 
org.springframework.data.r2dbc.core.R2dbcEntityTemplate, 
org.springframework.data.r2dbc.convert.MappingR2dbcConverter. Make sure you implement a constructor taking these
```

I tried refactoring `UserRepository` to the following, but the error still happens. Any ideas?

```java
package com.mycompany.myapp.repository;

import com.mycompany.myapp.domain.Authority;
import com.mycompany.myapp.domain.User;
import com.mycompany.myapp.repository.rowmapper.UserRowMapper;
import com.mycompany.myapp.service.EntityManager;
import org.apache.commons.beanutils.BeanComparator;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.r2dbc.convert.R2dbcConverter;
import org.springframework.data.r2dbc.core.R2dbcEntityOperations;
import org.springframework.data.r2dbc.core.R2dbcEntityTemplate;
import org.springframework.data.r2dbc.repository.Query;
import org.springframework.data.r2dbc.repository.support.SimpleR2dbcRepository;
import org.springframework.data.relational.repository.support.MappingRelationalEntityInformation;
import org.springframework.data.repository.reactive.ReactiveCrudRepository;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.util.function.Tuple2;
import reactor.util.function.Tuples;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Repository
public interface UserRepository extends ReactiveCrudRepository<User, Long>, UserRepositoryInternal {
    Mono<User> findOneByLogin(String login);

    Flux<User> findAllByIdNotNull(Pageable pageable);

    Flux<User> findAllByIdNotNullAndActivatedIsTrue(Pageable pageable);

    Mono<Long> count();

    @Query("INSERT INTO jhi_user_authority VALUES(:userId, :authority)")
    Mono<Void> saveUserAuthority(String userId, String authority);

    @Query("DELETE FROM jhi_user_authority")
    Mono<Void> deleteAllUserAuthorities();

    @Query("DELETE FROM jhi_user_authority WHERE user_id = :userId")
    Mono<Void> deleteUserAuthorities(Long userId);
}

interface UserRepositoryInternal {
    Mono<User> findOneWithAuthoritiesByLogin(String login);

    Mono<User> create(User user);

    Flux<User> findAllWithAuthorities(Pageable pageable);
}

@Component
class UserRepositoryInternalImpl extends SimpleR2dbcRepository<User, Long> implements UserRepositoryInternal {
    private final DatabaseClient db;
    private final R2dbcEntityTemplate r2dbcEntityTemplate;
    private final EntityManager entityManager;
    private final UserRowMapper userMapper;
    private final R2dbcConverter r2dbcConverter;

    public UserRepositoryInternalImpl(
        R2dbcEntityTemplate template,
        EntityManager entityManager,
        UserRowMapper userMapper,
        R2dbcEntityOperations entityOperations,
        R2dbcConverter converter
    ) {
        super(
            new MappingRelationalEntityInformation(converter.getMappingContext().getRequiredPersistentEntity(User.class)),
            entityOperations,
            converter
        );
        this.db = template.getDatabaseClient();
        this.r2dbcEntityTemplate = template;
        this.entityManager = entityManager;
        this.userMapper = userMapper;
        this.r2dbcConverter = converter;
    }

    @Override
    public Mono<User> findOneWithAuthoritiesByLogin(String login) {
        return findOneWithAuthoritiesBy("login", login);
    }

    @Override
    public Flux<User> findAllWithAuthorities(Pageable pageable) {
        String property = pageable.getSort().stream().map(Sort.Order::getProperty).findFirst().orElse("id");
        String direction = String.valueOf(
            pageable.getSort().stream().map(Sort.Order::getDirection).findFirst().orElse(Sort.DEFAULT_DIRECTION)
        );
        long page = pageable.getPageNumber();
        long size = pageable.getPageSize();

        return db
            .sql("SELECT * FROM jhi_user u LEFT JOIN jhi_user_authority ua ON u.id=ua.user_id")
            .map((row, metadata) ->
                Tuples.of(r2dbcConverter.read(User.class, row, metadata), Optional.ofNullable(row.get("authority_name", String.class)))
            )
            .all()
            .groupBy(t -> t.getT1().getLogin())
            .flatMap(l -> l.collectList().map(t -> updateUserWithAuthorities(t.get(0).getT1(), t)))
            .sort(
                Sort.Direction.fromString(direction) == Sort.DEFAULT_DIRECTION
                    ? new BeanComparator<>(property)
                    : new BeanComparator<>(property).reversed()
            )
            .skip(page * size)
            .take(size);
    }

    @Override
    public Mono<User> create(User user) {
        return r2dbcEntityTemplate.insert(User.class).using(user).defaultIfEmpty(user);
    }

    private Mono<User> findOneWithAuthoritiesBy(String fieldName, Object fieldValue) {
        return db
            .sql("SELECT * FROM jhi_user u LEFT JOIN jhi_user_authority ua ON u.id=ua.user_id WHERE u." + fieldName + " = :" + fieldName)
            .bind(fieldName, fieldValue)
            .map((row, metadata) ->
                Tuples.of(r2dbcConverter.read(User.class, row, metadata), Optional.ofNullable(row.get("authority_name", String.class)))
            )
            .all()
            .collectList()
            .filter(l -> !l.isEmpty())
            .map(l -> updateUserWithAuthorities(l.get(0).getT1(), l));
    }

    private User updateUserWithAuthorities(User user, List<Tuple2<User, Optional<String>>> tuples) {
        user.setAuthorities(
            tuples
                .stream()
                .filter(t -> t.getT2().isPresent())
                .map(t -> {
                    Authority authority = new Authority();
                    authority.setName(t.getT2().get());
                    return authority;
                })
                .collect(Collectors.toSet())
        );

        return user;
    }
}
```

/cc @joshlong

**Comment by DanielFran** [comment]
@Tcharl As soon as you have finished the reactive part, you can merged it and continue directly in https://github.com/jhipster/generator-jhipster/pull/16787 for the native part

**Comment by mraible** [comment]
@Tcharl My repo is at https://github.com/mraible/spring-native-examples.

Steps to reproduce:

```
git clone -b spring-native-0.11 git@github.com:mraible/spring-native-examples.git
cd spring-native-examples/postgres-webflux
./mvnw package -Pnative,prod -DskipTests
```

When the process completes, start Keycloak and PostgreSQL:

```
docker-compose -f src/main/docker/keycloak.yml up -d
docker-compose -f src/main/docker/postgresql.yml up -d
./target/postgres-webflux
```

You'll see the error above on startup.

**Comment by mraible** [comment]
@Tcharl There's a couple CI failures on MongoDB projects that are probably unrelated to this PR. However, it seems that the failure from `webflux-mariadb-gradle` are related:

```
BankAccountResourceIT > getBankAccount() FAILED
    java.lang.AssertionError at BankAccountResourceIT.java:382

BankAccountResourceIT > getAllBankAccounts() FAILED
    java.lang.AssertionError at BankAccountResourceIT.java:332

BankAccountResourceIT > putNewBankAccount() FAILED
    org.springframework.data.mapping.MappingException at MappingR2dbcConverter.java:187
        Caused by: org.springframework.core.convert.ConverterNotFoundException at BankAccountResourceIT.java:437
```

**Comment by Tcharl** [comment]
Learning gradle now ^^

**Comment by Tcharl** [comment]
@mraible regarding your native example, wasn't it on h2? if it's the case, it's because the Clob to string converter was not implemented: I changed the database type to varchar (maxchar) but will fill a ticket to use Clob as java type.
Should work now...

**Comment by mraible** [comment]
No, my Spring Native example uses PostgreSQL. I briefly tried with H2, but gave up because I couldn't add a native hint for H2 because it's not in the classpath by default.

**Pull request merged**
