### PR TITLE
Fix negative option values

### LINKED ISSUE #8608: JDL application options
##### **Overview of the issue**

At [JDL application options](https://www.jhipster.tech/jdl/#application_options) documentation page:

JDL option name | Default value | Possible values | Comment
----------------------|------------------|---------------------|---------------
serviceDiscoveryType | false | eureka, consul, no | 

The *Default value* seems to be wrong as the only accepted values are *eureka, consul, no*.

##### **Motivation for or Use Case**

Fix doc (and possibly implementation).

##### **Reproduce the error**

Using JHipster JDL for vscode (v. 1.3.1) shows error if using value false.

```json
application {
  config {
    serviceDiscoveryType false
  }
}
```

##### **Suggest a Fix**

The easy fix should be changing the value from false to no in Doc

Note:  But...  there seems to be some inconsistency for "don't use" value as some options use "no" and other options use "false".  Default "don't use" values should be revised in order to be consistent.

##### **JHipster Version(s)**

5.5.0

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/media/data/rubensa/development/vscode/workspace/autotriaje/monolith
└── generator-jhipster@5.5.0

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v8.11.3

npm: 5.6.0

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.21.2, build a133471

##### **Browsers and Operating System**

Linux 4.15.0-36-generic Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by MathieuAA**
Fixes #8608

---

My approach is to:
  - start with the JDL-part of the code base,
  - add warnings about deprecated values,
  - move on to the generator-related changes

Disclaimer: it's gonna be a PITA, but will be worth it in the end.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
What about saving as `null` or false to `.yo-rc.json`?
This should prevent the need for false comparisons:
`if(!this.jhipsterConfig.databaseType)` instead of `if(this.jhipsterConfig.databaseType === ‘none’)`

**Comment by MathieuAA** [comment]
Beware of the falsies. I'll check your suggestion

**Comment by murdos** [comment]
👍 
Do you also plan to convert the other options listed here https://github.com/jhipster/generator-jhipster/issues/8608#issuecomment-431617230 ?

**Comment by MathieuAA** [comment]
@murdos that's the plan!

**Comment by mraible** [comment]
Any updates? This has been open for a few months.

**Comment by MathieuAA** [comment]
Due to my lack of time, I haven't worked on this :( I've only submitted the beginning of a PR, but didn't have the time to properly work on this. There are a lot of things to do here...

**Pull request closed without merging**
