### PR TITLE
Improve Pulsar tests

### PR DESCRIPTION
**Pull request by cbornet**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
@cbornet we have now randomly errors with the tests:
image

**Comment by cbornet** [comment]
Those are only warnings.
Would need to ad some java 17 `add-opens`

**Comment by cbornet** [comment]
It seems the integration test `mf-ng-eureka-jwt-psql-ehcache` is not run anymore ?
This is where pulsar is tested.

**Comment by mshima** [comment]
Tests are selective.
There are a few rules like backend/frontend changes, generated source changes, dependabot auto merge doesn’t trigger builds.
Pulsar builds are flaky https://github.com/jhipster/generator-jhipster/actions/runs/4637630825/attempts/1

**Comment by cbornet** [comment]
It seems the tests should have been run for this PR but were not.

**Comment by mshima** [comment]
Pulsar tests are failing 20-40% from my perception.

**Pull request merged**
