### PR TITLE
Implement output path customizer

### PR DESCRIPTION
**Pull request by mshima**
Fixes https://github.com/jhipster/generator-jhipster/issues/9960

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@danielpetisme : can you review / test this one plz ?

**Comment by mshima** [comment]
Easy way to test:

```
npm install mshima/generator-jhipster#git-output-dir
mkdir .jhipster
echo "module.exports = {
    outputPathCustomizer: paths => (paths ? paths.replace(/^src\/main\/webapp([$/])/, 'src/main/webapp2$1') : undefined)
}" > .jhipster/sharedOptions.js
jhipster
```

**Comment by mshima** [comment]
Works for filtering too
```
module.exports = {
    outputPathCustomizer: paths => /^src\/main\/webapp([$/])/.test(paths) ? undefined : paths
}
```

**Comment by danielpetisme** [comment]
That's awesome!! Unfortunately, I think I will not be able a proper review/test before this weekend :( I'll do my best to do a quick feedback

**Comment by danielpetisme** [comment]
LGTM

**Comment by mshima** [comment]
@pascalgrimaud what about this one?
We should ask for another review?
Wait for 6.8.0?

**Comment by pascalgrimaud** [comment]
Daniel already reviewed it I think.
So I think it can be merged.
Amazing work here !

**Comment by pascalgrimaud** [comment]
I'll have a last look tomorrow morning and will merge it.

**Pull request merged**
