### PR TITLE
Only allow H2 remoting in the development environment, otherwise it's…

### PR DESCRIPTION
**Pull request by gzsombor**
… a huge security issue.

### CODE REVIEW

**Comment by jdubois** [comment]
In dev that's normal, as it's the only way to get liquibase-hibernate running.
In prod H2 should never be available anyway -> it shouldn't be possible to do this

**Comment by gzsombor** [comment]
Yep, this is why, this H2 server bean should be enabled only on dev profile

**Comment by cbornet** [comment]
Spring-boot 1.3 starts an H2 web console when devtools is on and h2 is present on the classpath (http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-sql-h2-console). You can test that it is already there with dev profile :smile:  at http://localhost:8080/h2-console. As per Policy 1, shouldn't we use it instead of our custom one ? The only drawback I see is that it doesn't get its properties from src/main/resources.

As for the security, we could also set "webAllowOthers" to false in the settings.

Also, interesting to note: the console is not limited to H2 and can be used with any jdbc driver.

**Comment by gzsombor** [comment]
This change is not the web console - JHipster has it for ages - and which is enabled on development profile. It's about opening a separate port for remote JDBC access, even in production environment.

**Comment by cbornet** [comment]
You're right. I will open a separate issue.
The remark about "webAllowOthers" stays though

**Pull request merged**
