### PR TITLE
Add issue template based on contributing.md information

### LINKED ISSUE #2916: Add Github issue templates
See https://github.com/blog/2111-issue-and-pull-request-templates

### PR DESCRIPTION
**Pull request by PierreBesson**
Fix #2916

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
FYI, it's exactly `[ci skip]` in commit message (not in title) ;-)

**Comment by PierreBesson** [comment]
Yes sadly, I realized to late.

**Comment by cbornet** [comment]
And misses "Fix #2916" for auto-closing

**Comment by pascalgrimaud** [comment]
When merging, I added [ci skip] in merge message and it skips build.
So cool for our friend Travis :construction_worker:

**Comment by pascalgrimaud** [comment]
Oh no!! In fact there is a build although the [ci skip]...! Will try next time

**Pull request merged**
