### PR TITLE
remove unused and confusing import

### PR DESCRIPTION
**Pull request by yelhouti**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by wmarques** [comment]
@yelhouti Thanks for your contribution.
Why this import were unusued for you?

**Comment by pascalgrimaud** [comment]
@wmarques : we need to check and test this closely. It is probably here for a good reason.

**Comment by yelhouti** [comment]
@pascalgrimaud the module is already imported in shared.module that imports this.
Also I feel that other imports are also a mess, since all global (application level) module imports are re-imoprted in each module...

**Comment by wmarques** [comment]
@yelhouti Ok let me check this :) 
The purpose to have a SharedModule is to re-import it in each feature module to access to shared Components, Pipes or Directives so that's a normal thing.
But I need to check if we import other modules in each feature module.

**Comment by wmarques** [comment]
@yelhouti LGTM. Can you also remove the `forRoot` static methods from `SharedModule` and `SharedLibs` ? It should work without them.

**Comment by yelhouti** [comment]
@wmarques I removed only the very confusing import, I think the hwole import should reviewed, keeping only what's is strictly required in the module reimported for each entity.

**Comment by wmarques** [comment]
Ok let's merge this then and I'll try to clean that.
I agree with you that we have too much imports, we should only have one simple `SharedModule`.

**Pull request merged**
