### PR TITLE
fix access to login with stateful security

### PR DESCRIPTION
**Pull request by smaestri**
Related to https://github.com/jhipster/generator-jhipster/issues/22843

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by yelhouti** [comment]
@smaestri be careful with this code, It might be the case that not all auth methods use the `UsernamePasswordAuthenticationFilter` in that case the the correct filter should be use. Please try with OAuth2 ...

**Comment by mraible** [comment]
Does it work with the following command?

```
jhipster jdl blog-oauth2
```

**Comment by smaestri** [comment]
Hi, you're right @mraible @yelhouti it fails with oauth2.
One approach would be to keep `BasicAuthenticationFilter` for oauth and have `UsernamePasswordAuthenticationFilter` for session-based. I will test it and keep you posted. I will also dig into spring security documentation to be sure this is the right approach.
For your question @mraible I let @yelhouti share his vision, but I guess even with an SPA, we should be able to go to any frontend route manually. Also, if you go to _login_ with UI and refresh page, it fails.

**Comment by yelhouti** [comment]
@mraible as @smaestri stated, sometimes, a user just navigates to /login to not lose there unsaved changes in a new tab (using ctrl+click) or because they bookmarked the login page. An SPA should just not work differently depending on how you navigate. I stumbled upon it when using an app so it can happen to anybody.

**Comment by mshima** [comment]
I think the fix is to disable spring-boot's login endpoint. We probably don’t use it.

**Comment by smaestri** [comment]
Yes indeed would be cleaner Will investigate this option, thank you @mshima

**Comment by mraible** [comment]
@smaestri Please fix conflicts if you have time.

**Comment by mshima** [comment]
Superseded by https://github.com/jhipster/generator-jhipster/pull/23766.
Closing.

**Pull request closed without merging**
