### PR TITLE
change CacheConfiguration for Infinispan Provider

### PR DESCRIPTION
**Pull request by nbaiocco**
-   Please make sure the below checklist is followed for Pull Requests.

-   [X] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@nbaiocco Please take a look at missing changes: https://travis-ci.org/jhipster/generator-jhipster/jobs/578891611#L4701

**Comment by nbaiocco** [comment]
@DanielFran 
I've made some changes in needle-server-cache.spec.js  and in  needle-server-cache.js.
Now seems like something else is wrong for some azure-pipelines, can you help me about that?

**Comment by DanielFran** [comment]
Closed/Reopened to launch tests

**Comment by nbaiocco** [comment]
Hi @srinivasa-vasu,

in collaboration with @ecostanzi  we have made some changes to the original pull request.
In the original version all works well but Hibernate L2 Cache stats were not available by micrometer.
In this version we have configured the cache manager inside the Spring context and than we have used it for Hiberate cache region factory, in this way cache configurations are centralized and their stats are exposed correctly with micrometer.

Nicola

**Comment by srinivasa-vasu** [comment]
LGTM

**Comment by pascalgrimaud** [comment]
Thanks @srinivasa-vasu for the review

Thanks @nbaiocco for your patience. Can you update this PR and resolve the conflict plz ? So it can be merged soon

**Comment by nbaiocco** [comment]
@pascalgrimaud 
Rebase done.

**Comment by pascalgrimaud** [comment]
Thanks a lot @nbaiocco !

**Comment by pascalgrimaud** [comment]
Sorry @nbaiocco but this PR failed all daily builds related to Infinispan.
Can you help plz ?

See:
https://dev.azure.com/hipster-labs/jhipster-daily-builds

**Test ngx-mariadb-oauth2-sass-infinispan** - Backend tests failed with OpenJDK8 - see https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=5791&view=logs&j=8d81b87e-4d26-5175-d51a-680d334119d9

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.533 s
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:javadoc (default-cli) on project travis-oauth-2-sass-infinispan: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - /home/vsts/app/src/main/java/io/github/jhipster/travis/config/CacheConfiguration.java:163: error: self-closing element not allowed
[ERROR]     * Hibernate property customizer. <br/>
[ERROR]                                      ^
[ERROR] /home/vsts/app/src/main/java/io/github/jhipster/travis/config/CacheConfiguration.java:168: warning: no @param for cacheFactoryConfiguration
[ERROR]     public HibernatePropertiesCustomizer hibernatePropertiesCustomizer(CacheFactoryConfiguration cacheFactoryConfiguration) {
[ERROR]                                          ^
[ERROR] /home/vsts/app/src/main/java/io/github/jhipster/travis/config/CacheConfiguration.java:168: warning: no @return
[ERROR]     public HibernatePropertiesCustomizer hibernatePropertiesCustomizer(CacheFactoryConfiguration cacheFactoryConfiguration) {
[ERROR]                                          ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/zulu-8-azure-amd64/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/vsts/app/target/site/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
##[error]Bash exited with code '1'.
```

**ngx-infinispan** - Application can't start in prod profile - see https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=5792&view=logs&j=a9815e2e-e060-5314-30a2-abdfb12c3532

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NullPointerException: null
	at org.infinispan.stats.impl.StatsImpl.<init>(StatsImpl.java:54)
	at org.infinispan.cache.impl.CacheImpl.getStats(CacheImpl.java:1405)
	at org.infinispan.cache.impl.AbstractDelegatingAdvancedCache.getStats(AbstractDelegatingAdvancedCache.java:301)
	at org.infinispan.spring.starter.embedded.actuator.InfinispanCacheMeterBinder.size(InfinispanCacheMeterBinder.java:31)
	at io.micrometer.core.instrument.binder.cache.CacheMeterBinder.bindTo(CacheMeterBinder.java:49)
	at org.springframework.boot.actuate.metrics.cache.CacheMetricsRegistrar.bindCacheToRegistry(CacheMetricsRegistrar.java:65)
	at org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration.bindCacheToRegistry(CacheMetricsRegistrarConfiguration.java:78)
	at org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration.lambda$bindCacheManagerToRegistry$0(CacheMetricsRegistrarConfiguration.java:73)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration.bindCacheManagerToRegistry(CacheMetricsRegistrarConfiguration.java:73)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration.bindCachesToRegistry(CacheMetricsRegistrarConfiguration.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 24 common frames omitted
```

**Comment by nbaiocco** [comment]
@pascalgrimaud 
I'm fixing javadoc issue for **ngx-mariadb-oauth2-sass-infinispan**.
Can I have same hints to replicate **ngx-infinispan** configurations?

Thanks in advance, and sorry for the inconvinience.

**Comment by nbaiocco** [comment]
@pascalgrimaud 
The problem about **ngx-infinispan** is related to the default value of:

    hibernate.cache.infinispan.statistics: false

set in application-prod.yml.

if this property has value **true** all works as described in previous comments;
if this property has value **false** the subsequent problem appears: https://github.com/infinispan/infinispan-spring-boot/issues/123

Can we close this pull request by simply changing the default value of this property in file application-prod.yml?

After that we can open/manage another issue for the NullPointerException related to https://github.com/infinispan/infinispan-spring-boot/issues/123.

**Comment by pascalgrimaud** [comment]
@nbaiocco : yes, I'm fine to put this value to `true`, if it fixed the problem. Can you do a PR plz ? Otherwise, I'll try to find time to do it

**Comment by nbaiocco** [comment]
@pascalgrimaud no problem, I'm going to do it.

**Comment by nbaiocco** [comment]
@pascalgrimaud  https://github.com/jhipster/generator-jhipster/pull/10497

**Pull request merged**
