### PR TITLE
Upgrade to Gradle 5.2.1

### LINKED ISSUE #9081: gradle 5.x support
Gradle 5 is already a few month old. We should support gradle 5 out of box for jhipster 6. There should be no big changes required, but I am pretty sure we will have some deprecation warnings regarding gradle 6. Need to investigate a little further, but pretty sure these are from some of the plugins we use, so most likely we just need to wait for new plugins releases.

Edit. Should consider removing the apt plugins and use default gradle features https://github.com/gradle/gradle/issues/2300#issuecomment-460065789

### PR DESCRIPTION
**Pull request by pvliss**
The following PR upgrades to Gradle 5. 

List of changes:

- Upgrade gradle wrapper to 5.2.1
- Switch to use the new configuration names(e.g. `implementation` instead of `compile`, etc.)
- Upgrade plugins:
  - Upgrade of jib gradle plugin to 1.0.2
  - Upgrade io.spring.dependency-management gradle plugin to version 1.0.7.RELEASE
- Some minor formatting changes and dead code removal

Fixes #9081 

Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Just as a note, we should check if upgrading jib is possible for us right now, did we do that for maven already? CC @danielpetisme @DanielFran Will have a look at the other changes tonight. Thanks in advance for your work and stepping up to do that!

**Comment by DanielFran** [comment]
No, for maven it is not updated yet. I actually requested some times ago to @danielpetisme in #https://github.com/jhipster/generator-jhipster/pull/8891 if he can handle this upgrade but it was not done yet...

**Comment by pvliss** [comment]
@atomfrede + @DanielFran Just re-based to master and fixed conflicts as #9328 has been merged. Great job btw 👍 

Regarding jib, I did actually notice that Maven is also not upgraded but I was not sure if the 2 need to be updated at the same time. If you want I can remove this change and create a separate issue for jib for both Maven and Gradle. I did check the change log of the gradle plugin and did not find any breaking changes that affect JHipster and I also did try a few tasks in order to build some images but that is far from testing it thoroughly.

**Comment by DanielFran** [comment]
@pvliss It is better to remove here jib update.
Let's wait from @danielpetisme feedback before create a new PR....

**Comment by atomfrede** [comment]
At keast I remember a lot of issues when we tried to update to some version greater than the current one, so I would not do it in this PR. In general gradle and maven doesn't need to be updated in sync but in general we try that, such that we have a common baseline in case we have some issues with some feature.

**Comment by pvliss** [comment]
@atomfrede  + @DanielFran : Sorry guys I was not aware of that. Reverted jib upgrade

**Pull request merged**
