### PR TITLE
Add Couchbase reactive option

### PR DESCRIPTION
**Pull request by tchlyah**
https://github.com/jhipster/generator-jhipster/issues/7608

This needs spring-boot 2.1.0 as it fixes https://github.com/spring-projects/spring-data-couchbase/pull/171

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@tchlyah Did you test in spring-boot 2.1 branch? Can I merge it?

From my investigation th fix is present since Lovelace release (see https://github.com/spring-projects/spring-data-couchbase/pull/171)

**Comment by tchlyah** [comment]
Yes sure, it is working well with Spring Boot 2.1. This is why I'm merging with the 2.1 branch.

**Comment by DanielFran** [comment]
@tchlyah Since I merged this reactive mongodb is failing!
See 'webflux-mongodb': https://jhipster.visualstudio.com/generator-jhipster/_build/results?buildId=1491

Can you please take a look?
Thanks

**Comment by tchlyah** [comment]
@DanielFran, I dont see any issue, all tests are green!

**Comment by DanielFran** [comment]
@tchlyah see webflux-mongodb tests...

**Comment by tchlyah** [comment]
Yes I already saw them. But I executed the tests again on my computer both after the merge and also in latest commit on spring-boot 2.1 branch, and mangodb tests are green.

**Comment by DanielFran** [comment]
@tchlyah I make some changes in project and tests are still failing: https://jhipster.visualstudio.com/generator-jhipster/_build/results?buildId=1544

**Comment by tchlyah** [comment]
Sorry my bad, I have tested twice and everything was working, now I can reproduce the error! I should have an issue with yarn not linking my project right. I'll fix it ASAP

**Comment by DanielFran** [comment]
@tchlyah Do not worry, this has been fixed 5 minutes ago in https://github.com/jhipster/generator-jhipster/pull/9074

**Pull request merged**
