### PR TITLE
Make the prometheus endpoint public

### PR DESCRIPTION
**Pull request by PierreBesson**

### CODE REVIEW

**Comment by Allsimon** [comment]
This endpoint gives tons of data to a potential attacker.

**Comment by PierreBesson** [comment]
@allsimon if you have a good solution to this problem please discuss it on this issue : https://github.com/jhipster/generator-jhipster/issues/8946

**Comment by Allsimon** [comment]
No idea, I was faced with the same issue at work and just decided to go with the public but denied to outsider via a proxy

I think we should put a disclaimer in the generated README.md

**Comment by PierreBesson** [comment]
I'm merging this and doing a new PR for prometheus where I will disable prometheus by default on the prod profile.

**Pull request merged**
