### PR TITLE
improving tomcat startup time during tests on linux (if you're building on docker this is required)

### PR DESCRIPTION
**Pull request by Panthro**
as per: http://stackoverflow.com/a/2325109/656094

### CODE REVIEW

**Comment by deepu105** [comment]
need to be tested in windows as well

**Comment by pascalgrimaud** [comment]
I complete : http://wiki.apache.org/tomcat/HowTo/FasterStartUp#Entropy_Source

Does it work on Windows and OSX ?

**Comment by jdubois** [comment]
No that wouldn't work on Windows and Mac OS X.
I'm not sure if it could make any difference for us, we don't use sessions at all for tests (or maybe just one?). But that could be a big improvement for production (unless we do #2948 of course), and it's worth to test this.
And wasn't this solved with Java 8?

**Comment by atomfrede** [comment]
What about ``gradle``?

**Comment by Panthro** [comment]
I have tested on Windows and Mac, it's only used on Linux systems, on windows the property is ignored

**Comment by Panthro** [comment]
and nope, wasn't solved on Java 8 :(

**Comment by jdubois** [comment]
Oh, and the interesting news is that @pascalgrimaud did the same thing for our Docker build, see https://github.com/jhipster/jhipster-registry/blob/master/Dockerfile#L80

So that's a +1 for me, anybody against this?

**Comment by pascalgrimaud** [comment]
@jdubois : I did the same, following spring boot docker guide : https://spring.io/guides/gs/spring-boot-docker/
>  To reduce Tomcat startup time we added a system property pointing to "/dev/urandom" as a source of entropy.

**Comment by deepu105** [comment]
+1

**Pull request merged**
