### PR TITLE
Add tip about ARM64 when generating Docker Compose files

### PR DESCRIPTION
**Pull request by mraible**
Fixes an issue I've had in demos when I copy the command verbatim on my M1. 

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
I'm not sure why snapshots were deleted when I ran `npm run update-snapshots`.

**Comment by mraible** [comment]
If I restore the snapshots and run `npm test` with these changes, I get 73 test failures and it takes time: 13 min. 29 s. This duration seems excessive. I'm using Node.js v18.14.0.

**Comment by mraible** [comment]
I tried running `npm test` on the `main` branch and I get similar results: 74 failures in 13 min. 27 s.

**Review by mshima — APPROVED** [review]

**Comment by mshima** [comment]
Merged without finishing the build 😕 . I thought it wasn’t possible .

**Comment by mraible** [comment]
@mshima Do you know why `npm test` doesn't pass locally? I tried using Node 16.19.0 and it seems much faster, but still fails.

```
  7861 passing (1m)
  317 pending
  1 failing

  1) Uncaught error outside test suite:
     Uncaught Workerpool Worker terminated Unexpectedly
    exitCode: `1`
    signalCode: `null`
    workerpool.script: `/Users/mraible/dev/generator-jhipster/node_modules/mocha/lib/nodejs/worker.js`
    spawnArgs: `/Users/mraible/.nvm/versions/node/v16.19.0/bin/node,--loader=file:///Users/mraible/dev/generator-jhipster/node_modules/@node-loaders/auto/dist/index-strict.js,/Users/mraible/dev/generator-jhipster/node_modules/mocha/lib/nodejs/worker.js`
    spawnfile: `/Users/mraible/.nvm/versions/node/v16.19.0/bin/node`
    stdout: `null`
    stderr: `null`
```

**Comment by mshima** [comment]
> I tried running `npm test` on the `main` branch and I get similar results: 74 failures in 13 min. 27 s.

It should take less than 3min. I will try.

**Comment by mshima** [comment]
@mraible try to remove node_modules. And run npm ci.

**Comment by mraible** [comment]
Removing `node_modules` and running `npm ci` results in one error:

```
  7876 passing (1m)
  323 pending
  1 failing

  1) jdl - JDLImporter
       import
         when passing the skipFileGeneration option
           should not create the .jhipster folder:

      /Users/mraible/dev/generator-jhipster/test/jdl/jdl-importer.spec.ts:803
        expect(fse.existsSync('.jhipster')).to.be.false;
                                               ^

AssertionError: expected true to be false
      + expected - actual

      -true
      +false

      at Context.<anonymous> (test/jdl/jdl-importer.spec.ts:803:48)
      at processImmediate (node:internal/timers:466:21)
```

I ran `npm run build` to try and fix. I get the same `Uncaught Workerpool Worker terminated Unexpectedly` error.

**Comment by mshima** [comment]
Node 18 support looks broken at main

**Comment by mraible** [comment]
Yeah, with Node 18, the tests still take forever. I see a lot of "applying multi-step templates" messages.

Screenshot 2023-02-28 at 7 56 50 AM

**Comment by mraible** [comment]
I just tested [this issue](https://github.com/jhipster/generator-jhipster/issues/21226#issuecomment-1447564759) with Node 16 and it doesn't happen. It seems to be a Node 18 issue.

**Comment by mshima** [comment]
@mraible tried with 18.13.0 and it works.

**Comment by mraible** [comment]
@mshima Maybe it's a problem with v18.14.0? That's what I'm using and it stops before installing anything when I run `jhipster jdl reactive-mf`. 

Screenshot 2023-03-08 at 12 06 34 PM

Since 18.15.0 is the latest LTS (according to https://nodejs.org), I tried that too. I get the same result. 

I tried with Node.js 18.13.0 and it seems to work fine.

**Comment by mshima** [comment]
@mraible looks related to https://github.com/nodejs/node/issues/46595.
Backport 18.x is pending.
We probably should blacklist 18.14.x and 18.15.0

**Pull request merged**
