### PR TITLE
Refactoring of the edit/new dialogs

### PR DESCRIPTION
**Pull request by gzsombor**
Advantages: 
 - separate the entity listing functionality, from the editing/creating functionality. So no need to load every related entities on the listing page, only when the dialog needs it. 
 - the edit / create dialog have a proper URL, so it is easy to link from other parts of the application
 - less html magic in the controllers (currently only the delete dialog needs jquery, but it can be fixed in a separate commit)
 - emitting events when an entity is modified, which can be used in other parts of the application

### CODE REVIEW

**Comment by jdubois** [comment]
You work too much, I can't follow :-)
Let's merge #1343 first :-)

**Comment by gzsombor** [comment]
Sorry !  :laughing:

**Comment by geesen** [comment]
This is awesome!
I always do this by hand after creating new entities!

I hope it will be reviewed soon! 
Maybe for 2.11.0 ?! ;-)
I'm going to start a new project in the near future and starting with a new version that includes this feature would be great!

**Comment by jdubois** [comment]
Sorry, I still want to review this PR (and merge it!), but I had too many PRs and issues waiting. I should work on this very soon, but if @geesen you want to do a first review please do, I need help!

**Comment by geesen** [comment]
Yes, I will have a look at it and test it (as far as I can)

**Comment by gzsombor** [comment]
I'm eagerly waiting for the review & merge  :wink:

**Comment by geesen** [comment]
I had finally some time for testing the PR/1372 branch and everything is working. I only used default jhipster settings, since there are only changes for the view and most settings are dedicated to the server part...).

One thing I did not expect: why there are still dialogs? 
I expected that the edit- and create-views are totally separated from other views.
In my projects (where I also split list/new/edit/show into different views) I have different views and controllers. For example for the entity "contact":

routes:
* contact.route.js
controllers:
* contact.index.controller.js
* contact.edit.controller.js
* contact.new.controller.js
* contact.show.controller.js

views:
* contact.index.html
* contact.edit.html
* contact.new.html
* contact.show.html

shared views:
* contact.dialog.html
* contact.form.html

and a service class
* contact.js

The contact.form.html contains only the form for the entity without any form and submit tags. This allows me to reuse the form in other views, but I want to have dedicated controllers, especially for handling new and edit...
The edit-view for example contains more or less the following:
 
```
....
<div class="widget-body">
    <form name="contactForm" class="form-horizontal" ng-submit="updateContact()">
        <div ng-include="'modules/contact/contact.form.html'"></div>
         <div class="form-actions">
	    <div class="row">
	        <div class="col-md-12">                                        
                    <button class="btn btn-default" type="button" ui-sref="contacts">back</button>
                    <button class="btn btn-primary" type="submit">save</button>
                </div>
            </div>
        </div>
   </form>
</div>
....
```



But don't get me wrong: I like the solution that the dialog is opened using the "onEnter" when your directly call the edit/new route (e.g. http://localhost:8080/#/item/1/edit)!
I just want to share/discuss my solution/idea at this point...
So, please: merge :smile:

**Comment by jdubois** [comment]
There's 2 big merge conflicts, so merging will be difficult.

I like to have everything in the same page. Here we now have separate screens, so we can link to them, but it's also more code, so I'm sure if that's a good idea.

**Comment by gzsombor** [comment]
@geesen : yes, it can be further improved, with a more modularized approach. But I fear, that you can't really decouple the form html from the controller, as the current UI needs lots of entity services for all the drop-downs, which all needs pre-initialized lists. Ideally, for every entity, an 'entity-picker' or an 'entity-selector' component could be generated (which can use even auto-completes or some other filtering mechanism), and that can be re-used without the current tricky form-controllers.
 @jdubois : I don't think it's too hard to merge, I can update it any time - if you say that you are going to merge, I've just didn't want to waste my time rebasing it every week, if nobody cares.

**Comment by geesen** [comment]
you're right, lists are indeed a problem or they require at least a lot of code... 
So, as always in architectural things: it hardly depends on the real project if such a modularization decoupling is possible and reasonable or not.

And I also think that a merge is very easy possible.

**Comment by deepu105** [comment]
:+1:  and once we have angular bootstarpin we can slowly remove jquery bootstrap widgets and use angular bootstrap ones, like dropdowns, progressbars etc

**Comment by gzsombor** [comment]
Can you merge this?

**Comment by deepu105** [comment]
:+1:  I'm currently doing almost the same thing in a local branch using angular-bootstrap as well, but @gzsombor your code looks much cleaner :smile:

**Comment by gzsombor** [comment]
Thanks! 😊

**Comment by jdubois** [comment]
I had -finally- had the time to review this PR, and indeed it's an improvement. Anyway, I'm trusting you both @deepu105 and @gzsombor , so this can only be good :-)

There are some merge conflicts, so if you have time to help @gzsombor as you wrote, yes I will merge this.

**Comment by gzsombor** [comment]
I've rebased it, and tested a bit. Seems to be ok ...

**Comment by jdubois** [comment]
Hi @gzsombor indeed it's working.

I have some comments, thus:

- Enums are not working -> this is kind of normal, as they are new, and were implemented after you did the PR
- The URLs are good, that's better than before, but I wonder if it's correct to have something like "book/new" for a new book and "book/1" to get the first book. I'd like to do some research here, or if you have any good practice for this kind of REST API...
- I don't like the dialog when you edit (a bit like @geesen ) -> you go to the "view" page and put an edit dialog on top of it, in fact the previous UI looked better to me (but of course the URLs where not as good). Maybe we could remove the dialog here?

**Comment by gzsombor** [comment]
* I will have a look on the enums, it's new, and I haven't seen it working :-)
* Previously it was /book and /book, now it will be /books /book/1 and /book/new - if the id is a number, and not a string equal to 'new', it is easily distinguishable. I'm open to suggestions, but it seemed consistent and reasonable - but yes, my mother language is not 'REST-English' :wink: 
* The beauty of this refactoring, is that soo easy to put the edit dialog, where ever you like it. (It's is amazingly simple to create child entities inside a parent entity details screen). With only the stage definitions changes, we can have on the edit page, and on the list page too. Personally, I prefer to put the edit button inside the view/detail screen, because it's much simpler to decide, if one 'entity' is editable or not, you don't need to care about evaluating that logic, when you list a lot's of entities. And the lots of buttons, in a table, seems a bit ugly. But it's just my personal taste.

**Comment by gzsombor** [comment]
The enums are fixed.

**Comment by jdubois** [comment]
- great for the enums !
- OK for the URLs -> I checked what Github does, and the do a ```/book/new``` like you, so that's good
- my only concern is where the edit dialog is -> I would like it to be in a separate non-modal page (like the view page, we could have an edit page). But here it's a modal on the view page, I find it ugly. Could you refactor this? That would also mean making the "create" page non-modal, but that would be good also (here the modals are not doing anything good)

**Comment by gzsombor** [comment]
I'm not a great UI designer - as the detail screen already proved it :wink: - so I dont think I can create a nicer edit/create page than the current dialog. But what you proposing is basically to turn the current simple view page to a page, where the entity can also be edited, which could be fine, but it will be a radically different than how the current, dialog based editing works, which will be a big surprise to the current users. 
 When this patch is merged, the entity generator could be improved with a question  about if the user prefer to generate an edit page or an edit dialog.

**Comment by jdubois** [comment]
yes you are correct -> your URLs are better, but I liked the previous UI better, and if we change this a lot of people might not like it.
This is annoying, I need more time to think about this (sorry, at the moment I am full time working for a client, so not enough time for JHipster!!!)

**Comment by gzsombor** [comment]
previous UI? What previous UI? This change doesnt modify the UI, it still looks the same, as before, only the code is less monolithic, more re-usable and more modular.

**Comment by jdubois** [comment]
I meant, if we change the UI to remove the modal dialogs.
But in your PR you have something in-between, as the user goes to the view page and has the edit modal -> could you stay on the list page and have the modal on top of it? In that case, the UI wouldn't change at all, so that would solve the issue

**Comment by gzsombor** [comment]
I see, make sense now ! :)
 Yes, it's a simple change, I will do it in the evening.

**Comment by deepu105** [comment]
:+1: to keep current dialog based UI instead of separate view pages

**Comment by zmb632** [comment]
I've implemented your suggestions in the latest commit, so I think, it can be merged :wink:

**Comment by gzsombor** [comment]
Sorry, I accidentally switched to a different profile :)

**Comment by jdubois** [comment]
Merged, at least!! Thanks @gzsombor !
There are still a few things to improve in the UI, but the biggest job is done!

**Comment by gzsombor** [comment]
Awesome !

**Pull request merged**
