### PR TITLE
Add an option to skip jdl validations and fixes to skipUserManagement.

### PR DESCRIPTION
**Pull request by mshima**
Fixes https://github.com/jhipster/generator-jhipster/issues/12433.
Workaround to https://github.com/jhipster/generator-jhipster/issues/12366.
Superseed https://github.com/jhipster/generator-jhipster/pull/12434.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by MathieuAA** [comment]
I'm against disabling the validation, passing booleans in params and having lots of ifs.
I've tried something this afternoon to see what can be done.
There's no simple way without changing how the validation happens. The same may also be the case for the JDL to JSON converters.
I'll try to provide an example tomorrow of what I'm talking about

**Comment by mshima** [comment]
@MathieuAA actually I took your advice when you didn’t approved my PR that added blueprint support to jdl. See https://github.com/jhipster/jhipster-core/pull/449#issuecomment-611448490.
I agree with that, validation in jdl side has became too complicated IMO, and we support prompts and jdl, we should unify validations.
I will create another PR removing the 2 commits related to jdl.

**Comment by MathieuAA** [comment]
@mshima this is what I was talking about. Minus some refactorings, and the boring copyright header :)

```javascript
// boring imports

module.exports = {
    createBusinessErrorChecker,
};

// Here that will most likely be an injected then modified yoRc content.
/**
 * Constructor taking the jdl object to check against application settings.
 * @param {JDLObject} jdlObject -  the jdl object to check.
 * @param {Object} applicationSettings - the settings object.
 * @param {String} applicationSettings.baseName - the application's name.
 * @param {String} applicationSettings.applicationType - the application type.
 * @param {String} applicationSettings.databaseType - the DB type.
 * @param {Boolean} applicationSettings.skippedUserManagement - whether user management is skipped.
 */
function createBusinessErrorChecker(jdlObject, applicationSettings = {}) {
    if (!jdlObject) {
        throw new Error('A JDL object must be passed to check for business errors.');
    }
    let specificErrorChecker;
    if (jdlObject.getApplicationQuantity() === 0) {
        specificErrorChecker = createBusinessErrorCheckerWithoutApplications();
    } else {
        specificErrorChecker = createBusinessErrorCheckerWithApplications();
    }

    return {
        /**
         * Checks the jdlObject's correctness against application parameters.
         */
        checkForErrors: () => {
            specificErrorChecker.checkForErrors();
        },
    };
}

function createBusinessErrorCheckerWithoutApplications(jdlObject, applicationSettings) {
    return {
        checkForErrors: () => {
            checkForEntityErrors();
            checkForRelationshipErrors();
            checkForEnumErrors();
            checkDeploymentsErrors();
            checkForOptionErrors();
        },
    };

    function checkForEntityErrors() {
        if (jdlObject.getEntityQuantity() === 0) {
            return;
        }
        const validator = new EntityValidator();
        jdlObject.forEachEntity(jdlEntity => {
            validator.validate(jdlEntity);
            if (isReservedTableName(jdlEntity.tableName, applicationSettings.databaseType)) {
                logger.warn(
                    `The table name '${jdlEntity.tableName}' is a reserved keyword, so it will be prefixed with the value of 'jhiPrefix'.`
                );
            }
            checkForFieldErrors(jdlEntity.name, jdlEntity.fields);
        });
    }

    function checkForFieldErrors(entityName, jdlFields) {
        const validator = new FieldValidator();
        Object.keys(jdlFields).forEach(fieldName => {
            const jdlField = jdlFields[fieldName];
            validator.validate(jdlField);
            if (isReservedFieldName(jdlField.name)) {
                logger.warn(`The name '${jdlField.name}' is a reserved keyword, so it will be prefixed with the value of 'jhiPrefix'.`);
            }
            const typeCheckingFunction = getTypeCheckingFunction(entityName, applicationSettings);
            if (!jdlObject.hasEnum(jdlField.type) && !typeCheckingFunction(jdlField.type)) {
                throw new Error(`The type '${jdlField.type}' is an unknown field type for field '${fieldName}' of entity '${entityName}'.`);
            }
            const isAnEnum = jdlObject.hasEnum(jdlField.type);
            checkForValidationErrors(jdlField, isAnEnum);
        });
    }

    function checkForValidationErrors(jdlField, isAnEnum) {
        const validator = new ValidationValidator();
        jdlField.forEachValidation(jdlValidation => {
            validator.validate(jdlValidation);
            if (!FieldTypes.hasValidation(jdlField.type, jdlValidation.name, isAnEnum)) {
                throw new Error(`The validation '${jdlValidation.name}' isn't supported for the type '${jdlField.type}'.`);
            }
        });
    }

    function checkForRelationshipErrors() {
        if (jdlObject.getRelationshipQuantity() === 0) {
            return;
        }
        const skippedUserManagement =
            applicationSettings.skippedUserManagement || jdlObject.getOptionsForName(OptionNames.SKIP_USER_MANAGEMENT)[0];
        const validator = new RelationshipValidator();
        jdlObject.forEachRelationship(jdlRelationship => {
            validator.validate(jdlRelationship, skippedUserManagement);
            checkForAbsentEntities({
                jdlRelationship,
                doesEntityExist: entityName => !!jdlObject.getEntity(entityName),
                skippedUserManagementOption: skippedUserManagement,
            });
        });
    }

    function checkForEnumErrors() {
        if (jdlObject.getEnumQuantity() === 0) {
            return;
        }
        const validator = new EnumValidator();
        jdlObject.forEachEnum(jdlEnum => {
            validator.validate(jdlEnum);
        });
    }

    function checkDeploymentsErrors() {
        if (jdlObject.getDeploymentQuantity() === 0) {
            return;
        }
        const validator = new DeploymentValidator();
        jdlObject.forEachDeployment(deployment => {
            validator.validate(deployment);
        });
    }

    function checkForOptionErrors() {
        if (jdlObject.getOptionQuantity() === 0) {
            return;
        }
        const unaryOptionValidator = new UnaryOptionValidator();
        const binaryOptionValidator = new BinaryOptionValidator();
        jdlObject.getOptions().forEach(option => {
            if (option.getType() === 'UNARY') {
                unaryOptionValidator.validate(option);
            } else {
                binaryOptionValidator.validate(option);
            }
            checkForPaginationInAppWithCassandra(option, applicationSettings);
        });
    }

    function getTypeCheckingFunction(entityName, applicationSettings) {
        if (applicationSettings.applicationType === ApplicationTypes.GATEWAY) {
            return () => true;
        }
        return FieldTypes.getIsType(applicationSettings.databaseType);
    }
    function checkForAbsentEntities({ jdlRelationship, doesEntityExist, skippedUserManagementOption }) {
        const absentEntities = [];
        if (!doesEntityExist(jdlRelationship.from)) {
            absentEntities.push(jdlRelationship.from);
        }
        if (!doesEntityExist(jdlRelationship.to) && (!isUserManagementEntity(jdlRelationship.to) || skippedUserManagementOption)) {
            absentEntities.push(jdlRelationship.to);
        }
        if (absentEntities.length !== 0) {
            throw new Error(
                `In the relationship between ${jdlRelationship.from} and ${jdlRelationship.to}, ` +
                    `${absentEntities.join(' and ')} ${absentEntities.length === 1 ? 'is' : 'are'} not declared.`
            );
        }
    }
    function isUserManagementEntity(entityName) {
        return entityName.toLowerCase() === 'user' || entityName.toLowerCase() === 'authority';
    }
    function checkForPaginationInAppWithCassandra(jdlOption, applicationSettings) {
        if (applicationSettings.databaseType === DatabaseTypes.CASSANDRA && jdlOption.name === BinaryOptions.Options.PAGINATION) {
            throw new Error("Pagination isn't allowed when the application uses Cassandra.");
        }
    }
}

function createBusinessErrorCheckerWithApplications() {
    return {
        checkForErrors: () => {
            // TODO
        },
    };
}
```

Only the "with application/s" case is left, and (almost) all that will be left for me to do is use your changes to merge the two together.

**Comment by MathieuAA** [comment]
I'm actually refactoring this part of the code, so this PR may not be necessary

**Comment by pascalgrimaud** [comment]
As @MathieuAA is refactoring this part, I'm putting `on hold` label. Plz sync with @mshima

**Pull request closed without merging**
