### PR TITLE
[gradle] generate initial files for convention plugin usage

### PR DESCRIPTION
**Pull request by atomfrede**
This PR adds the needed "infrastructure" part to use gradle convention plugins.

updates #19615

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by atomfrede** [comment]
Strange behaviour with checkstyle/nohttp and dependency resolution, which I didn't had when trying it out. It worked yesterday, so maybe some issue with upstream things. Will have a look later.

**Comment by atomfrede** [comment]
The dependency resolution issue is tracked at checkstyle here: https://github.com/checkstyle/checkstyle/issues/14123 for now i have applied the [workaround described here](https://github.com/gradle/gradle/issues/27035#issuecomment-1814589243)

**Comment by mshima** [comment]
From your sample, gradle plugins uses the format `id 'plugin'`.
At current implementation you are adding a dependency instead of a plugin.
Is this the desired behavior?

**Comment by atomfrede** [comment]
@mshima This is just the "infrastructure" inside `buildSrc` folder. So adding a dependency is correct. These are needed dependencies for the convention plugins. One need to add third party plugins to the dependencies block inside `buildSrc/build.gradle` to use them within the convention plugins. See https://github.com/atomfrede/jhipster-gradle-improvements/blob/main/buildSrc/build.gradle

Applying and creating convention plugins will be separate PRs.

**Review by mshima — APPROVED** [review]

**Pull request merged**
