### PR TITLE
add database to admin menu

### LINKED ISSUE #975: Add the H2DB console to the Administration menu
It would be nice to have the possibility to go the the H2DB console through the administration menu. Also it would be nice that it then would be opened in a page with the navbar present. This is possible if the console is placed in an `<iframe>`-tag.

Is a this feature request accepted? If it is I can provide a PR.

### PR DESCRIPTION
**Pull request by andidev**
use grunt-ng-constant and gulp-ng-constant to generate an app.constants.js file containing the running environment (ENV = dev or prod)
generate app.constants.js at end of hipster generator along with the wiredep (see index.js)
refactor to use environment constant to tell if developer ribbons should be shown or not
add new menu item linked to h2db console in Administration menu and show it only if the environment constant is dev

fix #975

### CODE REVIEW

**Comment by andidev** [comment]
Tested configurations:
grunt
gulp

Tested:
grunt serve
mvn spring-boot:run
mvn spring-boot:run -Pprod

**Comment by andidev** [comment]
Worth mentioning is that I have introudeced an angular constant, `ENV`, for the running environment (dev or prod) available in all views. This will make it easier to add environment specific code in the views in the future.

**Comment by gmarziou** [comment]
is your `ENV`approach similar to the one described in [this article](http://mindthecode.com/how-to-use-environment-variables-in-your-angular-application)?

**Comment by andidev** [comment]
Yes, it is exactly where I got the idea.

**Comment by andidev** [comment]
Found two bugs actually so hold this PR until I comment again

**Comment by andidev** [comment]
One bug was fixed and the other one is not from this PR (see issue #1047)

So this seems to be ready for release.

**Pull request merged**
