### PR TITLE
Add new Bronze Sponsor: MiniTool [skip ci]

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Following https://github.com/jhipster/jhipster.github.io/pull/894

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
The `[skip ci]` seems broken...

**Comment by jdubois** [comment]
Thanks! I was just about to do it!!

**Comment by jdubois** [comment]
@pascalgrimaud let me do the Twitter thank you message, I see you don't usually use our account

**Comment by jdubois** [comment]
@pascalgrimaud ah you already did it, you're too fast!! Thanks!

**Comment by pascalgrimaud** [comment]
@jdubois : just did it myself, it was the first time :)

**Comment by SudharakaP** [comment]
> The `[skip ci]` seems broken...

@pascalgrimaud : Refer https://github.com/jhipster/generator-jhipster/pull/11304

**Pull request merged**
