### PR TITLE
Remove Datastax from Gold Sponsor

### PR DESCRIPTION
**Pull request by pascalgrimaud**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
I believe Okta's sponsorship might have expired as well.

**Comment by pascalgrimaud** [comment]
@mraible : yes, and what is the state of Okta's sponsorship ? simply stopped or planned to go from platinium to gold ?

**Comment by mraible** [comment]
I have been unable to get funds to continue our sponsorship. Hopefully, that will change in the future.

**Comment by cbornet** [comment]
😢

**Pull request merged**
