### PR TITLE
sb3: bump elasticseach container to v8.5.0

### PR DESCRIPTION
**Pull request by mshima**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by mraible — APPROVED** [review]

**Comment by mshima** [comment]
@mraible actually, this is due to diff logic applied to the workflows. If there is no change to the generated source, the test is skipped.
It doesn’t fix anything, every elasticsearch project broke, while others didn’t change.

**Comment by mraible** [comment]
So Elasticsearch v7.17.4 works fine with Spring Boot 3, but v8.5.0 does not? Maybe @xeraa can help.

**Comment by mshima** [comment]
@mraible no it's just the docker health check that is not working.
https://github.com/jhipster/generator-jhipster/blob/75898e4860ed9850d697a5c0ba34f47b77559e14/generators/docker/templates/src/main/docker/elasticsearch.yml.ejs#L35

**Comment by xeraa** [comment]
So, since 8.0 security is enabled by default. That means HTTPS only and a random password for the `elastic` user. Which is generally good, but would make your setup quite a bit more complex. And the health check is the first thing failing — not entirely surprising 😅

You could disable security for this scenario (**please, don't do this in general**)? I think this should get you sorted:

    environment:
      - xpack.security.enabled=false

**Review by mraible — APPROVED** [review]

**Pull request merged**
