### PR TITLE
Provide memcached and redis support for heroku

### LINKED ISSUE #11695: Support redis in heroku subgen
##### **Overview of the feature request**

Heroku as a redis service. If I am not mistaken we don't support that addon in the heroku subgen. I think we should

* https://elements.heroku.com/addons/heroku-redis

##### **Related issues or PR**

* https://github.com/jhipster/generator-jhipster/issues/11693

-   [x] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #11696: Support memcache with heroku subgen
##### **Overview of the feature request**

Heroku has multiple memcache addons, which both provide a free plan for evaluation. I think we should support one of them in the heroku subgen.

* https://elements.heroku.com/addons/memcachier
* https://elements.heroku.com/addons/memcachedcloud

##### **Related issues or PR**

* https://github.com/jhipster/generator-jhipster/issues/11693
* https://github.com/jhipster/generator-jhipster/issues/11695

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by atomfrede**
This PR is in draft mode to see if we all agree on the property naming for additional cache properties.

Before we can merge this at least two things must be done:

* Add additional common properties to jhipster(lib)
* Adapt cache configuration to respect these for redis and memcached

closes #11695
closes #11696

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
@jdubois Can you review the redis part maybe and check if the changes still work e.g. with azure?

**Comment by atomfrede** [comment]
As we only use the defaults as before I don't expect any issues, but it would be nice to have second pair of eyes here, so we can have it in the next release to have better heroku integration.

**Comment by pascalgrimaud** [comment]
@atomfrede : not sure someone will have the bandwidth to test this, but I'm trusting you. Feel free to merge this if you're confident :)

**Comment by atomfrede** [comment]
Thanks @pascalgrimaud! Will do some more testing with local docker compose. Heroku works fine.

**Comment by atomfrede** [comment]
Test with local docker compose and heroku, both work fine, so I assume it will also work with other cloud providers.

**Pull request merged**
