### PR TITLE
fix: missing dashes on Kafka configuration

### PR DESCRIPTION
**Pull request by fdelbrayelle**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
The problem is simply consistency.
Sometimes we used dashed, sometimes not.

The current Kafka configuration work well. Your problem is because you tried to add a property with dash in your module, instead of not using a dash.
Not sure if generator-jhipster should change, to be compatible with your module.
I think, your module should change this part, to be compatible with generator-jhipster and the current config for existing projects

**Comment by fdelbrayelle** [comment]
@pascalgrimaud Which part of the module are you making a reference of? I didn't modify any yml configuration recently :thinking:

**Comment by pascalgrimaud** [comment]
I'm referring to your error:

```
Error parsing file src/main/docker/app.yml: SyntaxError: A collection cannot be both a mapping and a sequence (33:7)
  31 |       - 127.0.0.1:9092:9092
  32 |     environment:
> 33 |       KAFKA_BROKER_ID: 1
     |       ^^^^^^^^^^^^^^^^^^
> 34 |       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 35 |       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 36 |       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 37 |       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 38 |       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 39 |       KAFKA_ADVERTISED_HOST_NAME: kafka
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 40 |   zookeeper:
     | ^
```

You should add the property without dash, I think:
https://github.com/fdelbrayelle/generator-jhipster-kafka/blame/475b46eda587774108b3cae99923433dd8d36ceb/generators/app/files.js#L376

**Comment by fdelbrayelle** [comment]
Thank you I didn't understand and notice that detail!

**Comment by vishal423** [comment]
@pascalgrimaud , I think the consistency issue is on `generator-jhipster` side as few component configurations use `dash` notation. like: https://github.com/jhipster/generator-jhipster/blob/e39889ff66c4cd652493fe6fba46579dd15291f2/generators/docker-compose/templates/docker-compose.yml.ejs#L54

I believe we should be consistent on our approach so that module owners can extend without worrying about the notation to use

**Comment by fdelbrayelle** [comment]
Yes @vishal423. Before it was like this in `app.yml` for Kafka : `- KEY=VALUE`. It became recently : `KEY: VALUE` and so the module builds fail as I update some of these keys/values.

**Comment by pascalgrimaud** [comment]
Yes agree @vishal423

**Pull request closed without merging**
