### PR TITLE
fix tslint semicolon config for Angular

### PR DESCRIPTION
**Pull request by ctamisier**
4d6bf48:
```
"semicolon": [
            "always"
]
```

should be

```
"semicolon": [
            true,
            "always"
]
```

5718bba:
fix tslint warning

### CODE REVIEW

**Comment by deepu105** [comment]
@ctamisier shount matter anymore as we will be using prettier soon. But thanks

**Comment by pascalgrimaud** [comment]
With this change, there are a lot of new errors: https://travis-ci.org/jhipster/generator-jhipster/jobs/331473118#L3998
There are still some works to do before merging this.

**Comment by ctamisier** [comment]
ouch indeed !
I am fixing it.
Can you confirm that this is something that we want a "always semicolon" ?
With prettier it will be automatically added, right ?
I think that prettier will be a value added for managing white-spaces.
For semicolon, as this is "textual", I think this is better to have it in the template as well.
(Might be confusing to see a semicolon in the generated code but note having it in the template ?!)

**Comment by deepu105** [comment]
Yes, always semicolon should be true.

**Pull request merged**
