### PR TITLE
Create centralized configuration management.

### PR DESCRIPTION
**Pull request by mshima**
Fix https://github.com/jhipster/generator-jhipster/pull/10247
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pvliss** [comment]
Wow. Some amazing work @mshima!!! Will try to review this within the next couple of days. As this is a big refactoring more @jhipster/developers need to agree and review so please be patient

NOTE: The description should link to #10247

**Comment by mshima** [comment]
> Wow. Some amazing work @mshima!!! Will try to review this within the next couple of days. As this is a big refactoring more @jhipster/developers need to agree and review so please be patient

Thanks for the follow up.
I will wait the review to continue the migration.
 
> NOTE: The description should link to #10247

Fixed

**Comment by pascalgrimaud** [comment]
I'd like to know if there is a breaking change for other existing blueprints ?

**Comment by mshima** [comment]
> I'd like to know if there is a breaking change for other existing blueprints ?

It shouldn't break existing blueprints.

It may break once the old configuration code is removed, but shouldn't break too.

**Comment by mshima** [comment]
One point that can cause unexpected problem is item 3 from motivation (https://github.com/jhipster/generator-jhipster/issues/10247).

Can be easy fixed by merging jhipster upstream configs into blueprint configs at
https://github.com/mshima/generator-jhipster/blob/4b1b7d0b8fa10b1a1881fb37ae37320926e9d846/generators/configuration.js#L359

**Comment by mshima** [comment]
Should fix https://github.com/jhipster/generator-jhipster/issues/9692

**Comment by mshima** [comment]
Closing in favor of https://github.com/jhipster/generator-jhipster/pull/10554

**Pull request closed without merging**
