### PR TITLE
Check the entity is saved and can be correctly serialized after creation

### LINKED ISSUE #8147: [Protractor] Test that the entity can be displayed after creation
##### **Overview of the feature request**

As explained in #8146, [no assert](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs#L143) is done for checking that the entity can be displayed after being created.

##### **Motivation for or Use Case**

This is important as we don't detect that an entity can not be displayed in client, an error could be at any of these parts:
- retrieve in the database
- JSON serialization
- Angular/React deserialization
- Angular/React display
- ...

An easy implementation is to check that the number of entities is incremented by 1 after creation (I proposed to do the same for delete: we check the entity list is decremented by 1 after delete).

Although checking the number of line could be not enough, because apparently, we don't switch to the next page after creating the 21st element in a page of 20 elements: a proper way could be to parse the pagination footer and assert that it has be incremented: (`Showing 1 - 20 of 20 items.` ==> `Showing 1 - 20 of 21 items.`)?

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by hdurix**
Fix #8147

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by hdurix** [comment]
Need to wait for https://github.com/jhipster/generator-jhipster/pull/8197 before merging it (not the same test framework).

**Comment by hdurix** [comment]
OK to be merged now.

**Comment by jdubois** [comment]
Thanks @hdurix !

**Comment by hdurix** [comment]
Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/4937

**Pull request merged**
