### PR TITLE
fix-oom

### PR DESCRIPTION
**Pull request by bertwin**
2 halve memory leaks !== 1 memory leak

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
the build is green ! let's try this

**Comment by bertwin** [comment]
@pascalgrimaud maybe it would be better to make the jest workers limited to 2 only when running in a CI environment?

What would be the best way to do that? In the travis script?

**Comment by jdubois** [comment]
@bertwin @pascalgrimaud yes, totally agree! We should only limit this for Travis

**Comment by pascalgrimaud** [comment]
It would be an improvment. Maybe adding `test:ci` in `package.json` ? But we need to be carefull when packaging in prod, as it will use `test`
Need time to think about that :)

**Pull request merged**
