### PR TITLE
angular module Principal.hasAuthority should always return a promise

### PR DESCRIPTION
**Pull request by andidev**

### CODE REVIEW

**Comment by andidev** [comment]
I get `TypeError: Principal.hasAuthority(...).then is not a function` when using `<div ng-cloak="" has-authority="ROLE_ADMIN">Admin Content</div>` since false instead of a promise which resolves to false is returned by `Principle.hasAuthority(...)`

**Comment by andidev** [comment]
@atomfrede can you confirm this is okay here? I have also fixed some indentations thats why the diff looks a bit messy. It's actually a simple oneliner diff.

**Comment by atomfrede** [comment]
I'm not at home right now. I'll have a look at it tomorrow.

**Comment by jdubois** [comment]
@atomfrede I'm not sure of the issue here, can you confirm it's good for you? If both of you are OK then it's fine for me!

**Comment by atomfrede** [comment]
I can think of a scenario where it might be an issue. But didn't have the time to check it yet.

**Comment by andidev** [comment]
To be more exact on how to reproduce the issue:
1) Add `<div ng-cloak="" has-authority="ROLE_ADMIN">Admin Content</div>` to the footer
2) Open the application in the browser
3) The console shows the error
```
TypeError: Principal.hasAuthority(...).then is not a function
    at link.defineVisibility (http://localhost:8080/scripts/components/auth/authority.directive.js:52:30)
    at link (http://localhost:8080/scripts/components/auth/authority.directive.js:63:21)
    at invokeLinkFn (http://localhost:8080/bower_components/angular/angular.js:8746:9)
    at nodeLinkFn (http://localhost:8080/bower_components/angular/angular.js:8246:11)
    at compositeLinkFn (http://localhost:8080/bower_components/angular/angular.js:7637:13)
    at compositeLinkFn (http://localhost:8080/bower_components/angular/angular.js:7641:13)
    at compositeLinkFn (http://localhost:8080/bower_components/angular/angular.js:7641:13)
    at compositeLinkFn (http://localhost:8080/bower_components/angular/angular.js:7641:13)
    at publicLinkFn (http://localhost:8080/bower_components/angular/angular.js:7512:30)
    at http://localhost:8080/bower_components/angular/angular.js:1660:27 <div has-authority="ROLE_ADMIN">
```
...and the "Admin Content" is displayed in the footer though it should not be.

**Comment by deepu105** [comment]
Yes this definetely has issues, i saw them too, the has any role directive
also used this i guess so doesnt work properly

**Comment by jdubois** [comment]
I'm not sure I understand correctly here... Who thinks this PR as an issue?

**Comment by deepu105** [comment]
PR seems good +1

**Comment by jdubois** [comment]
OK then let's merge this (even if I don't understand the issue, and that's the great thing about being a team!)

**Pull request merged**
