### PR TITLE
Fix bug getRecentForLiquibase always passing 1 day and move to utils

### PR DESCRIPTION
**Pull request by mshima**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
@mshima Thanks! One thing: should we create another utils file for liquibase-related stuff? I'd like to see the utils file split into content-related stuff

**Comment by mshima** [comment]
@MathieuAA utils-liquibase.js?

**Comment by MathieuAA** [comment]
@mshima yeah liquibase-utils sounds good!!

**Comment by mshima** [comment]
@MathieuAA keep inside generators folder or create utils folder at root?
Creating utils folder at root makes sense to me.

**Comment by MathieuAA** [comment]
@mshima Agreed, this makes more sense

**Comment by mshima** [comment]
@MathieuAA created utils/liquibase.js instead of utils/liquibase-utils.js.

**Comment by MathieuAA** [comment]
Good call. Can you do the same for tests? So as to be consistent with where the tests are kept

**Comment by MathieuAA** [comment]
Maybe you're right. You know what? Let's keep your version. I'm approving this

**Comment by mshima** [comment]
@MathieuAA thanks.

**Comment by MathieuAA** [comment]
I'm seeing one weird issue in the logs:
```
 AccountResourceIT > testRegisterDuplicateLogin() FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132
        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException at ConstructorResolver.java:798
            Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException at ConstructorResolver.java:798
                Caused by: org.springframework.beans.factory.BeanCreationException at ConstructorResolver.java:656
                    Caused by: org.springframework.beans.BeanInstantiationException at SimpleInstantiationStrategy.java:185
                        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException at ConstructorResolver.java:798
                            Caused by: org.springframework.beans.factory.BeanCreationException at ConstructorResolver.java:656
                                Caused by: org.springframework.beans.BeanInstantiationException at SimpleInstantiationStrategy.java:185
                                    Caused by: java.lang.IllegalArgumentException at RedisURI.java:42
```

**Pull request merged**
