### PR TITLE
fix ticket #5164 by patching correctly the URLs in the MANIFEST.MF when

### PR DESCRIPTION
**Pull request by cmoine**
fix ticket #5164 by patching correctly the URLs in the MANIFEST.MF when  …
they contains spaces

### CODE REVIEW

**Comment by jdubois** [comment]
I have no idea how this works, so thank you so much for contributing this :-)

**Comment by cmoine** [comment]
Trust me ;-)

It comes from how the URL should be presented in the MANIFEST.MF:
C:\Users\Christophe%20M
instead of
C:\Users\Christophe M

**Comment by jdubois** [comment]
I do, it's already merged :-)

**Comment by cmoine** [comment]
Yes I saw that, thank you !

----- Original Message -----

**Pull request merged**
