### PR TITLE
Add a message when `yo` is not installed.

### PR DESCRIPTION
**Pull request by antarus**
Add a message when `yo` is not installed.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by antarus** [comment]
Without yo, i can't test the blueprint vue.js

**Comment by jdubois** [comment]
Yes, `yo` is needed to run the blueprints, so we can't remove it, at least not for advanced users

**Comment by PierreBesson** [comment]
AFAIK, yo is only needed for modules not blueprints (as they should be run with `jhipster --blueprint blueprint`). I would rather we totally deprecate yo usage and find an alternative solution even if it means just wrapping yo in the jhipster cli (for example, implementing something like `jhipster --module ionic`).

**Comment by jdubois** [comment]
Oh sorry, @PierreBesson you are probably right, it's for modules, not blueprints.

**Comment by PierreBesson** [comment]
I have an alternate solution to this problem https://github.com/jhipster/generator-jhipster/pull/10004
Actually jhipster was depending on the globally installed yo command in order to check that the blueprint was correctly installed. In my PR I'm simply using yo from generator-jhipster's node_modules so this is hidden from the user.

**Comment by PierreBesson** [comment]
Anyway @antarus thanks for doing this PR, which revealed the issue !

**Comment by antarus** [comment]
ok, no problem ;)

**Pull request closed without merging**
