### PR TITLE
fix test comment generator _EntityResourceIntTest.java

### PR DESCRIPTION
**Pull request by sapiensmagno**
change 'Alice' to entityClass using EJS synthax.

the integration test generator was hardcoded to produce the following comment: 'Validate the Alice in the database'

### CODE REVIEW

**Comment by gmarziou** [comment]
Thanks and congratulations for your first contribution :)

**Comment by jdubois** [comment]
Thanks also, even if you removed my daughter's name :-)

FYI "Alice" is a good test name, as it is not pluralized by https://www.npmjs.com/package/pluralize and so this finds quite a lot of bugs in our unit tests :-)

**Comment by cbornet** [comment]
@jdubois is your son's name Bob 😄  ?

**Comment by jdubois** [comment]
@cbornet well, I will need to negotiate that if I get another boy :-)

**Pull request merged**
