### PR TITLE
Add Spring Boot build info to maven and to gradle

### PR DESCRIPTION
**Pull request by gmarziou**
/management/info shows build info like version, date, ...

Use same dependencies for both maven and gradle.
Add mariadb driver to gradle properties.

Ref #3574

### CODE REVIEW

**Comment by gmarziou** [comment]
Wait before merging.

I have some strange issues on my environment, it seems that `npm link` does not always work as expected, when I run `yo jhipster` it seems I get the globally installed generator rather than my linked clone. Due to this, I'm not sure what I'm testing.

Can someone test it?

**Comment by ruddell** [comment]
Generating a project puts `"generator-jhipster": "3.5.1",` into the package.json and installs it into the local node_modules folder.  After the initial generation, the project uses that version.  What I've been doing is removing it from package.json and node_modules/generator-jhipster in order to use the one installed with `npm link`, if there's a better way someone please let me know because it's kind of a pain.

I get an empty JSON array for any combination of options that I try - I tried maven/gradle for both session/JWT, also tested both monolith/gateway options.

**Comment by deepu105** [comment]
This is how `npm link` works

when you run `npm link` on the actual repository code it symlinks the global node_modules version to point to this folder, so when we run `yo jhipster` node always will use the repository pointed by symlink from the global module.
Now once you generate an app you are installing a local version of JHipster as well and any run on the generated app folder after would use the local version which doesnt know of the symlink.

Now to overcome this you need to run `npm link generator-jhipster` on the generated project folder as well so that the local version is symlinked to the global version which points to our local repo.

Hope thats clear so in short to ensure you are using local repo
1. run `npm link` on the local repo folder
2. run  `npm link generator-jhipster` on the generated app folder (you need to do this for each application you create)

**Comment by jdubois** [comment]
Thanks @deepu105 !! I totally agree this is annoying, or least not intuitive. And I was doing the symlink manually, so thanks for the tip.
I'm updating https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup with this info

**Comment by gmarziou** [comment]
Thanks @deepu105, I didn't know this trick either.
Thanks @ruddel for testing, I also get an empty json object while it was working when I first tried with a project that was generated with older JHipster version, I'll investigate further.

**Comment by gmarziou** [comment]
Maven: it does not work with `mvn spring-boot:run`, it works only when the jar or war is created so basically by running `mvn package` before or by running `mvn spring-boot:build-info`. maybe there could be some configuration to attach it to another phase but this is not [what is documented](http://docs.spring.io/spring-boot/docs/1.4.0.RELEASE/reference/htmlsingle/#howto-build-info) 

Gradle: it does not work though I followed the doc but I must admit I know nothing about gradle. So I need help.

**Comment by PierreBesson** [comment]
@gmarziou, on the need to run the build-info phase, I don't think there is something we can do about it. Similar to when you run the Application class in the IDE, there is no clean way that it could refresh the build info details. However the goal of the feature is mostly useful to track the build version of a bundled artifact like a jar or a docker image. For dev, people will have to understand how it work (maybe add some docs about it). I think we can leave it like that for now.

I will try to have a look at gradle.

**Comment by gmarziou** [comment]
Yes it sounds reasonable.

**Comment by PierreBesson** [comment]
@gmarziou, I just had a look and tried to add the buildInfo() to the gradle build but it didn''t work for me either. I must have missed something because it does work in the [spring-boot-sample-actuator](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-actuator). I didn't manage to have the `build/resource/META-INF/build-info.properties` generated with gradle.

**Comment by atomfrede** [comment]
Do we overwrite the ``processResources`` in gradle?

**Comment by gmarziou** [comment]
As far as I know resources are not involved here but I may be wrong.

The actuator example showed me on thing, is that you can have several `springBoot` blocks in build.gradle, in [my commit I added `buildInfo()` to the existing one](https://github.com/jhipster/generator-jhipster/pull/3970/files#diff-5595eed51dd01e38e024547a86042a81) we have maybe that's a mistake.

**Comment by gmarziou** [comment]
Gradle: I tried spring boot 1.4.1 snapshot, no success

I took a trace in debug mode `(./gradlew -d jar`) and now I think it is related to resources as you suggested @atomfrede 

```
00:29:14.538 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':bootBuildInfo' (up-to-date check took 0.044 secs) due to:
  Output file /home/gael/jhipster/infog/build/resources/main/META-INF/build-info.properties has changed.
  Output file /home/gael/jhipster/infog/build/resources/main/META-INF/build-info.properties has been removed.
```

I checked t(he file does not exist at the end of the build.

Here is the full log in case, some gradle expert has some suggestion:

[debug.txt](https://github.com/jhipster/generator-jhipster/files/421481/debug.txt)

**Comment by gmarziou** [comment]
Closing this PR as I can't make it work for gradle.

I have submitted a PR #4010 for maven only.

**Pull request closed without merging**
