### PR TITLE
Add Missing Method in SecurityConfiguration.java.ejs

### LINKED ISSUE #11551: Gateway Application with No Service Discoverty Failing to Start
##### **Overview of the issue**

It seems that we have a small bug when generating applications with no service discovery. For example generate an Gateway application with no service discovery and if you try to start the application you'll get the following error. 

 ```

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.mycompany.myapp.web.filter.RouteDetectorFilter required a bean of type 'org.springframework.web.client.RestTemplate' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Qualifier(value="vanillaRestTemplate")


Action:

Consider defining a bean of type 'org.springframework.web.client.RestTemplate' in your configuration.
```

##### **Motivation for or Use Case**

Getting the `No Service Discovery` option working by default. 

##### **Reproduce the error**

Generate an application with the below provided configuration and start it in dev mode. 

##### **Suggest a Fix**

I think the following lines should be added for each configuration not only for `uaa`

https://github.com/jhipster/generator-jhipster/blob/1353bc4ad39e4a616309f4669c441e761f40b5d7/generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs#L450-L454

##### **JHipster Version(s)**

I believe this is a regression after commit; 7dced34 or caused previously by the commits reverted by that commit.

##### **JHipster configuration**

<details>
<summary>Click here to expand!</summary>
<pre>&lt;details&gt;
&lt;summary&gt;.yo-rc.json file&lt;/summary&gt;
&lt;pre&gt;
{
  &quot;generator-jhipster&quot;: {
    &quot;promptValues&quot;: {
      &quot;packageName&quot;: &quot;com.mycompany.myapp&quot;
    },
    &quot;jhipsterVersion&quot;: &quot;6.8.0&quot;,
    &quot;applicationType&quot;: &quot;gateway&quot;,
    &quot;baseName&quot;: &quot;jhipster&quot;,
    &quot;packageName&quot;: &quot;com.mycompany.myapp&quot;,
    &quot;packageFolder&quot;: &quot;com/mycompany/myapp&quot;,
    &quot;serverPort&quot;: &quot;8080&quot;,
    &quot;authenticationType&quot;: &quot;jwt&quot;,
    &quot;cacheProvider&quot;: &quot;ehcache&quot;,
    &quot;enableHibernateCache&quot;: true,
    &quot;websocket&quot;: false,
    &quot;databaseType&quot;: &quot;sql&quot;,
    &quot;devDatabaseType&quot;: &quot;h2Disk&quot;,
    &quot;prodDatabaseType&quot;: &quot;mysql&quot;,
    &quot;searchEngine&quot;: false,
    &quot;messageBroker&quot;: false,
    &quot;serviceDiscoveryType&quot;: false,
    &quot;buildTool&quot;: &quot;maven&quot;,
    &quot;enableSwaggerCodegen&quot;: false,
    &quot;jwtSecretKey&quot;: &quot;YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons&quot;,
    &quot;embeddableLaunchScript&quot;: false,
    &quot;useSass&quot;: true,
    &quot;clientPackageManager&quot;: &quot;npm&quot;,
    &quot;clientFramework&quot;: &quot;angularX&quot;,
    &quot;clientTheme&quot;: &quot;none&quot;,
    &quot;clientThemeVariant&quot;: &quot;&quot;,
    &quot;creationTimestamp&quot;: 1586054458998,
    &quot;testFrameworks&quot;: [],
    &quot;jhiPrefix&quot;: &quot;jhi&quot;,
    &quot;entitySuffix&quot;: &quot;&quot;,
    &quot;dtoSuffix&quot;: &quot;DTO&quot;,
    &quot;otherModules&quot;: [],
    &quot;enableTranslation&quot;: false,
    &quot;blueprints&quot;: []
  }
}

&lt;/pre&gt;
&lt;/details&gt;

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

&lt;details&gt;
&lt;summary&gt;JDL entity definitions&lt;/summary&gt;

&lt;pre&gt;

&lt;/pre&gt;
&lt;/details&gt;

##### **Environment and Tools**

openjdk version &quot;11.0.6&quot; 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.17.1

node: v12.13.0

npm: 6.14.4

yarn: 1.21.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.24.1, build 4667896b
</pre>
</details>

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by SudharakaP**
When a gateway application with no service discovery is generated we have a RouteDetectorFilter.java file which refers this method.

Fixes #11551

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by SudharakaP** [comment]
Close/Open for tests.

**Comment by SudharakaP** [comment]
Don't think these build failures are related to this one.... :thinking: :thinking:

**Comment by PierreBesson** [comment]
Should it really be generated in the SecurityConfiguration class (maybe it should be in a RestTemplateConfiguration class ?), also why the name "vanillaRestTemplate" rather than the basic `restTemplate` ?

**Comment by SudharakaP** [comment]
@PierreBesson : Good point. I've refactored the code to a separate class. Take a look and let me know if anything else needs done. :smile:

**Comment by SudharakaP** [comment]
@PierreBesson : Thanks for the review. :smile:

**Pull request merged**
