### PR TITLE
add reserved words for postgresql

### PR DESCRIPTION
**Pull request by ErickSanVal**
Added some reserved keywords for PostgreSQL according to this list:
[PostgreSQL keywords](http://www.postgresql.org/docs/current/static/sql-keywords-appendix.html)

Only the words marked as 'reserved' where added. I made sure that this words are actually throwing a syntax error in PostgreSQL.

If someone would like to review this PR, making a comment about it, or add/remove some words, I'd appreciate it.

This PR is related to this issue [#2137](https://github.com/jhipster/generator-jhipster/issues/2137)

### CODE REVIEW

**Comment by Ariel-Isaacm** [comment]
I was having the same trouble as #2137 this would really help :)!

**Comment by DarthCharles** [comment]
yup, thumbs up for this. :+1:

**Comment by jdubois** [comment]
Great!! I'll review it tomorrow.

**Comment by deepu105** [comment]
@jdubois I thought yiu removed posgres reserved keywords on purpose earlier,  but i dont recall the reason

**Comment by ErickSanVal** [comment]
I think you mean this commit: https://github.com/jhipster/generator-jhipster/commit/96b3d20121f2da2015bb06b0e40de36d116978f8
As you see in that list they were non reserved keywords as well, I think that was the reason to remove them, but what I did was only select keywords that did were marked as reserved and cause a syntax error. Let's wait for @jdubois opinion on this, maybe there are other reasons. Thank you

**Comment by jdubois** [comment]
Yes, I removed the previous keywords as there were too many of them (and that was seriously annoying), and most of them could in fact be used (which is kind of stupid, really)

**Pull request merged**
