### PR TITLE
add camelToHuman filter

### LINKED ISSUE #2544: Entity names are not capitalized in the Entities dropdown menu
Tested with the 2.26.1 release.

### PR DESCRIPTION
**Pull request by deepu105**
add camelToHuman conversion in generator
add utility fiilter in angular js

fix #2544

### CODE REVIEW

**Comment by jdubois** [comment]
For #2544 I just wanted to generate the correct text directly, why this filter? And don't we already have this fonction in underscore.js?

**Comment by deepu105** [comment]
@jdubois i thought the filter could be a nice utility for people,  ill remove it if you dont like it. I dont know if underscore has it let me check

**Comment by deepu105** [comment]
@jdubois yes underscore has this, ill remove the method and use that instead, do you want me to remove the angular filter also?

**Comment by jdubois** [comment]
@deepu105 yes please remove the filter, I don't understand what it would be used for

**Comment by deepu105** [comment]
@jdubois have updated to use underscore and removed the angular filter, it was just a utility in case the user wants to do these kind of stuff in angular

**Pull request merged**
