### PR TITLE
EntityMapper should be invoked from EntityResource only even if EntityService is present #3175

### PR DESCRIPTION
**Pull request by lordlothar99**
Everything linked to DTO and mappers is now (back) in `EntityResource` objects
I tried to clean the code as much as I could, both generator and generated. Generated code is very close to what it was before

### CODE REVIEW

**Comment by deepu105** [comment]
Ill review test this over weekend

**Comment by deepu105** [comment]
plz follow this guideline next time https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-git-commit-guidelines

also add the fix #issuenumber keyword for auto close of issue

**Comment by deepu105** [comment]
all your commits have same message can you plz squash them

**Comment by lordlothar99** [comment]
ok I will

**Comment by deepu105** [comment]
lets do this after 3.0, so Im putting this on hold

**Comment by jdubois** [comment]
Closing this as #3175 has evolved a lot!!! I'm re-writing everything

**Pull request closed without merging**
