### PR TITLE
Implement generate-blueprint, entities priorities and improvements to esm support.

### PR DESCRIPTION
**Pull request by mshima**
Follow up to https://github.com/jhipster/generator-jhipster/pull/17549.
Related to https://github.com/jhipster/generator-jhipster/pull/17499, i18n not implemented.

Closes https://github.com/jhipster/generator-jhipster/pull/17549.
Fixes https://github.com/jhipster/generator-jhipster/issues/15869.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Anyone wants to review?

**Review by deepu105 — APPROVED** [review]

**Comment by mraible** [comment]
Since https://github.com/jhipster/generator-jhipster-ionic/pull/612 depends on this, I'm curious. What release will this be included in?

**Comment by mshima** [comment]
Angular should be broken at v7.6.0, so we should release v7.7.0 next week at most.
cc @pascalgrimaud

**Comment by pascalgrimaud** [comment]
Okey got it!

**Pull request merged**
