### PR TITLE
No need to use the JavaMailSenderImpl, enough to get the interface.

### PR DESCRIPTION
**Pull request by gzsombor**
Make the UserResource.getUser call similar to getAllUser - ManagedUserVM is received consistently

### CODE REVIEW

**Comment by jdubois** [comment]
Yes for the "MailSender", but here you also modify some other code, including using the ManagedUserVM on the service layer, which you shouldn't do (package tangling)

**Comment by gzsombor** [comment]
There are already methods in UserService which take or return ManagedUserVM : 
[createUser](https://github.com/gzsombor/generator-jhipster/blob/c92d46400f0715611f01b29ca4b5028bb9577d9f/generators/server/templates/src/main/java/package/service/_UserService.java#L165)
[updateUser](https://github.com/gzsombor/generator-jhipster/blob/c92d46400f0715611f01b29ca4b5028bb9577d9f/generators/server/templates/src/main/java/package/service/_UserService.java#L217)
[getAllManagedUsers](https://github.com/gzsombor/generator-jhipster/blob/c92d46400f0715611f01b29ca4b5028bb9577d9f/generators/server/templates/src/main/java/package/service/_UserService.java#L278)

I've noticed because I've added a field to ManagedUserVM which initialized from a lazy loaded field of user.
I don't know why the travis build is failed

**Comment by jdubois** [comment]
No package in the service layer should call the Web layer.
At some point we had a huge mess here, and I refactored it, maybe there are some this stuff still missing there.
They should be removed before JHipster 4.

**Comment by jdubois** [comment]
I'm creating a specific ticket for this

**Comment by gzsombor** [comment]
The build failed with some angular2 errors, which is surely unrelated to this change

**Pull request merged**
