### PR TITLE
Create delete method in protractor test

### LINKED ISSUE #7844: Add delete tests to Protractor tests
##### **Overview of the feature request**

The current Protractor tests verify that add works, but they don't delete the records. This means that when you run the tests, test data is left around.

##### **Motivation for or Use Case**

Because I like to run e2e tests, but not have the test data lying around after.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/7778

- [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by hdurix**
Test to delete last element of the entity list:
- click on last delete button
- check dialog title
- click on confirm button
- check an element has been removed

Fix #7844

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by hdurix** [comment]
The PR is in WIP until I add the same tests for react.

@mraible, to answer your [comment](https://github.com/jhipster/generator-jhipster/issues/7844#issuecomment-399669609) on the related issue, I'm not sure we should go further on deleting relationships between entities.

Indeed, we can't know in which order the entities should be deleted. I think that's why, the creation test is disabled when at least one relationship is required: see [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs#L34-L36) and [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-client/templates/angular/src/test/javascript/e2e/entities/entity.spec.ts.ejs#L89).

What do you think?

**Comment by mraible** [comment]
Can you try out these changes on my [blog.jh](https://github.com/jhipster/jdl-samples/blob/master/blog.jh) JDL? It has relationships in it and the current Protractor tests do create data with relationships.

**Comment by hdurix** [comment]
I created a [project](https://github.com/hdurix/jdl-blog) with your JDL file and protractor option (and my current generator branch).

Here what I understand from the protractor test. A test is done for testing the entity creation:
- for each relationship: if the relationship is many-to-many, [does nothing](https://github.com/hdurix/jdl-blog/blob/master/src/test/javascript/e2e/entities/entry/entry.spec.ts#L43): statement is commented
- for each relationship: if the relationship is NOT many-to-many, [selects the last option](https://github.com/hdurix/jdl-blog/blob/master/src/test/javascript/e2e/entities/entry/entry.spec.ts#L42) if any
- if at least one relationship is required (not the case on your sample JDL file), all the test is ignored: method is commented

All of the `delete` tests work properly with those cases, whether the target relationship contains entities (relationship with `User` or manually added with the app running) or not (test from scratch with no `Entry` for instance when testing `Blog` creation).

Now I need to understand why some Travis configurations are failing.

**Comment by hdurix** [comment]
For random failures (especially in travis), I reckon I have to wait for the entity list to be displayed (→ retrieved from back-end) before trying to delete one (I need to find a way to do that with protractor).

**Comment by hdurix** [comment]
Ok thanks! Next time I'll know...
It's a shame Travis does not let the committer to re run the build by himself.

**Comment by pascalgrimaud** [comment]
probably to avoid an user to restart a build, and blocking the other builds, because there are some priorities.

Another solution is to use your own Travis instance, so you will be the boss there

**Comment by hdurix** [comment]
It's okay for me!

**Comment by jdubois** [comment]
Awesome, let's merge this! And don't forget the bug bounty :-)

**Comment by pascalgrimaud** [comment]
impressive work @hdurix !!

**Comment by hdurix** [comment]
Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/4936

**Pull request merged**
