### PR TITLE
Do not prompt for feign clients when creating a monolith 

### LINKED ISSUE #24560: Jhipster v8.1.0 asks to generate Feign client during Monolithic app creation
##### **Overview of the issue**

While running `jhipster` to create a new project, a user can choose both a Monolithic application, and a Feign client.  After answering remaining questions, project generation fails with the following error:

ERROR! An error occured while running jhipster:server#feignMigration
ERROR! ERROR! Feign client is only supported by microservice applications.

##### **Motivation for or Use Case**

Completing the questions to generate a new app should not lead to a failure situation.

##### **Reproduce the error**

install JHipster v8.1.0.  Answer questions as follows:
What is the base name of your application? something
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? Do you want to generate a feign client? Yes
? Besides Junit, which testing frameworks would you like to use? Cucumber
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.test
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with in-memory persistence
? Which cache do you want to use? (Spring cache abstraction) No cache - Warning, when using an SQL database, this will disable the 
Hibernate 2nd level cache!
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? API first development using OpenAPI-generator

##### **Suggest a Fix**

Bypass feign client question if user selects Monolithic in previous question

##### **JHipster Version(s)**
v8.1.0

##### **JHipster configuration**

Welcome to JHipster v8.1.0
Welcome to the JHipster Information Sub-Generator
```
/home/me/code/test
└── (empty)
```
##### **Environment and Tools**

openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22)
OpenJDK 64-Bit Server VM GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22, mixed mode, sharing)

git version 2.39.2

node: v18.18.2
npm: 10.2.5

Docker version 24.0.7, build afdd53b
WARNING! Current location doesn't contain a valid JHipster application

---

no jdl yet

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
no entity file yet

##### **Browsers and Operating System**

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

Linux pluto 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by nil-malh**
Added a when to the feingClient command where it checks if the application type is not a Monolith

closes #24560

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by nil-malh** [comment]
Bounty claimed @ https://opencollective.com/generator-jhipster/expenses/177579

**Review by atomfrede — APPROVED** [review]
looks good to me. Thanks @nil-malh and congrats to your first contribution.

**Comment by DanielFran** [comment]
Thanks @nil-malh:  bug bounty approved.

**Comment by mraible** [comment]
It'd be awesome to have a new release with this fix in it! I'm going to start updating my JHipster Mini-Book, and a screenshot without this question would be nice.

**Pull request merged**
