### PR TITLE
changes to have angular translate as an option during generation

### LINKED ISSUE #1416: Feature Request: Can Angular Translate be an option while generating an app?
Instead of making Angular translate and everything related to translate default, can it be an option while generation? I know I can just remove the default french translation and work but still for just using English the entire translation services riding on top of everything is unnessery right? that too with the occasional fliker of foo.some.title

### PR DESCRIPTION
**Pull request by deepu105**
changes to have an option during app generation to disable translation

Fix #1416

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois Please take a look and let me know if anything needs improvement

**Comment by deepu105** [comment]
@gzsombor I didnt do this PR since I needed this feature, as I have already made the changes when I generated the app. I thought that this could be a an option which would benefit others too as not everyone would want translation and when i dont need it why all those watches on the body text which indeed is heavy. And so far used angular translate, once in say every 10 loads in average i would see foo.bar,title and its not quite impressive to the end user.

Of all the files commited many of the changed files are due to content mismatch in json files and html files, I have tried to make html content same as the en/*.json

why would you think it is a burden?

**Comment by jdubois** [comment]
@deepu105 @gzsombor this would be a good feature for many people, so I would like to have it. But indeed, I thought it would be much simpler, without all those checks.
@gzsombor can you put some comments in the code (like in the health controller, I agree this looks weird) where you specifically don't like what you see?
@deepu105 can you try to simplify your code? Are really all those checks necessary?

This touches so many parts of the code that we can't have this PR opened for too long.

I'll tweet about it, so maybe someone can have some clever idea to suppress some of those checks.

**Comment by deepu105** [comment]
yes more eyes please.

I guess we can have a regex stripper for JS files as well. But what about the places where only translation keys are used? like in page.title. I guess we can read the respective json and replace that but that will be complex i guess, atleast for me :P

**Comment by deepu105** [comment]
@jdubois Have tried to simplify and reduce the number of diffs further

Any one have a better way to reduce the diffs further.

remaining manual switches are in module.js page.title and placeholder values

**Comment by gzsombor** [comment]
I can understand, that if you want one-language, English only application, and you can accept that you never need to rename all your Save/Edit/Delete buttons to 'Apply'/'Modify'/'Remove' and you cant reuse any labels easily, then the translations are not needed. Otherwise you will need it. 
 My main objections is that I would never put any user visible strings in java code, neither into javascript. This is the code, which should focus on the business logic, the presentation should be in a different layer, so the user visible stuff should be in html(+css) or in the other templates. 

 Interesting that you have saw problems with translations, I've only had problems, when either the json was not correctly formatted or not every translation is loaded which is needed by that state. I guess, you could provide some more detail about your problems.
 The problem with this approach with the contributors is that this feature change a lots of things in lots of places, and it's getting harder and harder to test the different possible combinations, without bigger benefit. For example, currently to test a change in the 'entity-controller-js' you need at least 4 try at least, for every different pager implementation - with this exclude-translation settings, it will double the number of tries.

 I think, if you really want to remove this translation stuff, there would be a much simpler solution:
* Modify the html files to have a reasonable default labels, and provide a dummy 'translation' filter/directive and '$translate' and '$translationProvider' services, which don't do anything. In this way, you only modify small part of the JHipster, and you can be sure, that no javascript is used for any translations on the client side

**Comment by deepu105** [comment]
@gzsombor In my humble opinion, I guess most of the real world jhipster application would go through some level of UI revamp, of the applications i do I have completely replaced the UX so along with that most of my labels change. And yes it is convenient to have a json to manage labels, but the occasional flick, i dont how to reproduce it and when it happens i dont see any json not loaded error in console, is not acceptable. I guess some of us would have seen it occasionally. So if you talk about value of not having translation at all is the removal unwanted watches all over your code.

Your approach of having a dummy translate directive to load only english json looks good but isnt it same as having only en folder in translate?  Im no angular expert but i think again thats the same kind of bloat on top of your code where you really wanted plain old html text rite? 

But i guess i have removed switch for the directives and service using regex, the only thing i couldn't do is removing the page titles and translate directive in placeholders, so i guess if we can have a dummy directive to do this i can remove some more switch.

But i dont know how to go about it properly, can you help?

**Comment by deepu105** [comment]
@gzsombor btw your right about string in java, damn me, forgot about that. I guess we can leave the en.properties in java alone, ill make that changes

**Comment by deepu105** [comment]
Have made changes to have English property files on server side even when translation is disabled
[comparison] (https://github.com/jhipster/generator-jhipster/compare/master...deepu105:JH-CR)

**Comment by deepu105** [comment]
@jdubois  If you feel that this commit touches so many files and complex to review and accept shall I suggest a different approach
+  I'll close this PR and submit 2 new PR
+  First PR will have only corrections to sync text in HTML files to Json files, and some corrections to use the translate attribute directive instead of filter in some places, so this will be a simple PR which you can merge first as a cleanup release.
+ Once you merge this, the codebase should be cleaner, now I will submit the second PR which will actually have the changes to make translation optional. Now since this is on top of  clean code base it will have less files affected and fewer diffs

So overall you will have a less complex merge and I guess the first PR anyway would be good as it is a overall cleanup to sync json content with html content which doesnt affect anyone

What say

**Comment by jdubois** [comment]
@deepu105 if it makes it easier for me, yes you can split it into 2 PRs.

I want to have this merged, it's just that I need time to review all PRs.

**Comment by deepu105** [comment]
OK Ill do that over the weekend, then you can decide when you want to merge each PR

**Comment by deepu105** [comment]
closing so the change can be merged as 2 seperate PR

1. https://github.com/jhipster/generator-jhipster/pull/1537

**Pull request closed without merging**
