### PR TITLE
adds test profile to resource tests and excludes uaa tokenstore beans on that

### PR DESCRIPTION
**Pull request by xetys**
please review if it is ok to use `@ActiveProfile` in the tests...

tried to build some setup for my current PR and docs on that, noticed that #3982 is present in all services, and added this manually to them in order to make it working

### CODE REVIEW

**Comment by deepu105** [comment]
I dont like the idea of mixing test related profile and stuff into actual impl. Isnt there any other cleaner way?

**Comment by xetys** [comment]
The only thing I now have in mind is to still use the profile annotation, but with "cloud" instead of "! Test" and force microservice applications to run using cloud profile. 

I think all these load balance dependence features have to be explicitly enabled, since they make the application not really testable, if beans are depending per default

**Comment by xetys** [comment]
ok I decieded to add a profile "uaa" if we use authenticationType uaa. For all tests, if they are usual, they don't lead to the evil uaa beans get wired...this should fix this (and some more problems)

**Comment by cbornet** [comment]
Maybe you can provide some @Primary beans in test to overridethe ones created for normal operation ?

**Comment by xetys** [comment]
primary beans, in order to exclude actualy beans from main application? I would have to checkout how to manage that

**Comment by xetys** [comment]
ok, i tried a simple approach: add a new configuration class where those evil beans are nulled (one naive but working way of disabling beans) and referring them in `@SpringBootTest(classess = ... )`

if this is a way you think is better then the current approach, I will change that to this. In this case, each test must now refer to that additional config class, but no profile magic anymore in actual implementation

**Comment by xetys** [comment]
so this now works in a way as @cbornet asked

**Comment by deepu105** [comment]
This looks much better. But you seem to have a travis failure also you might want to squash some commits

**Comment by xetys** [comment]
i fixed the travis, so for me this is ready to be merged

**Pull request merged**
