### PR TITLE
use Zipkin instead of Jaeger for istio tracing

### PR DESCRIPTION
**Pull request by PierreBesson**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@PierreBesson Jaegers has been graduated by cncf: https://www.cncf.io/announcement/2019/10/31/cloud-native-computing-foundation-announces-jaeger-graduation/

Maybe we should reconsider to add the possibility to choose between both Jaeger and Zipkin?

**Comment by PierreBesson** [comment]
No Jaeger is just the freemium version of a certain APM vendor whereas Zipkin is a 100% community open source project like JHipster. I would rather support Zipkin. CNCF is mostly about big money at this point.

**Comment by deepu105** [comment]
The demo setup from Istio comes with Jaeger, maybe we should add docs to provide setup instruction for Zipkin

**Comment by deepu105** [comment]
Also, this means I have to reupdate my Book :cry:

**Comment by PierreBesson** [comment]
Yes we need some docs ! For me Zipkin is much better and also truly in the
spirit of the community.
BTW, Deepu, There is an istio install script in the demo I have used at my
last conference (https://github.com/PierreBesson/demo-vxdms-2019).
I want to add this to the generated code. However we need to make sure it
works in every cloud. Also we have to use Istio 1.4 now.
If you really want this for your book, please create an issue and assign it
to me. It would be better as part of the generated code as Istio changes so
quickly that docs and books 😜 get outdated all the time.

**Comment by deepu105** [comment]
@PierreBesson I didn't understand your comment abput Jaeger being freemium and APM, Isn't it from Uber, also its Apache 2 licensed like us

> Jaeger, inspired by Dapper and OpenZipkin, is a distributed tracing system released as open source by Uber Technologies. It can be used for monitoring microservices-based distributed systems:

**Comment by deepu105** [comment]
@PierreBesson your scripts are already outdated for Helm 3 :wink:

**Pull request merged**
