### PR TITLE
Initial Reactive support

### PR DESCRIPTION
**Pull request by cbornet**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

First basic implementation of reactive option.
The `experimental` flag must be set to see the option in the questions.

See #7608

### CODE REVIEW

**Comment by jdubois** [comment]
@cbornet you have Travis work with Reactive???

**Comment by cbornet** [comment]
Yes, I do 😄 !
I'll be AFK for 3 weeks (at least) so it would be great if this could be reviewed and merged meanwhile. Or at least don't do any big bang refactoring during this period so it's not a nightmare to rebase 😅 
Don't hesitate to fix directly on the branch if needed.

**Comment by pascalgrimaud** [comment]
as always, incredible work @cbornet ! :open_mouth:

**Comment by cbornet** [comment]
I force pushed one last time because I had done a mistake in the last commit. I won't do it again, I promise.

**Comment by joumenharzli** [comment]
The last time i used webflux i found that Springfox is not willing at this time to support it. So i cannot use it to document my apis.
https://github.com/springfox/springfox/issues/1773#issuecomment-408956294
What will you plan for Swagger ?

**Comment by cbornet** [comment]
I think Springfox's maintainer is working actively on supporting Webflux. It seems like a lot of work and I'm sure he would love to get help. Unfortunately I have so much to do right now that I can't help him myself.
I guess we'll have to wait for now. But don't worry there's already plenty of work around Webflux for Jhipster. 
As for the Api-first option, it shouldn't be hard to do in case you're also using it.

**Comment by DanielFran** [comment]
@cbornet @joumenharzli see https://github.com/springfox/springfox/pull/2608

**Comment by DanielFran** [comment]
@cbornet @joumenharzli see springfox/springfox#2608 has been merged! :)

**Comment by cbornet** [comment]
Is there any objection to merge once I resolve the conflicts ?

**Comment by jdubois** [comment]
@cbornet no, because I don't think this would have any impact with the rest of the code, so there's no risk

**Comment by deepu105** [comment]
@jdubois IMO this ticket needs more than a 100$ bounty, may be we should multiply bounty based on complexity of the ticket since not every ticket are the same

**Comment by jdubois** [comment]
Yes this is like the VueJS bug bounty. The "lead" of each project (so @cbornet here) should create a [project](https://github.com/jhipster/generator-jhipster/projects) and split the main issue into several issues. Then we'll add bounties to those tickets: like for VueJS, I think we should give at least $500 here, so that means 5 tickets will have each a $100 bounty.

That's also better because maybe several people will work on the project, so that's a way to split the money between contributors.

**Comment by deepu105** [comment]
Ya that sounds fine

Thanks & Regards,
Deepu

**Comment by Mahdihp** [comment]
added Reactive support webflux with jwt

**Comment by jdubois** [comment]
@Mahdihp that's the third comment you post in a row which doesn't make much sense, what's happening?

**Pull request merged**
