### PR TITLE
correct response types in account resource

### PR DESCRIPTION
**Pull request by atomfrede**
I've implemented the mentioned workaround and checked some other endpoints for missing plain text response type.

update #3127

### CODE REVIEW

**Comment by notflorian** [comment]
:+1:

**Comment by atomfrede** [comment]
Oh seems I missed a ``(`` will fix it today.

**Comment by deepu105** [comment]
@atomfrede can we close #3127 or does it need more work?

**Comment by atomfrede** [comment]
From my point of view it can be closed.

**Pull request merged**
