### PR TITLE
Updated JCore to v6.0.4 & fixed the JDL export error logging 

### PR DESCRIPTION
**Pull request by MathieuAA**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
The build still failed, because of this:
- the installation of JHipster in the CI is done without `npm link`, but with a real installation of the package
- once the application is generated, the `node_modules` contains the last release version (here 6.5.0), so it will use the JHipster Core 6.0.1, so it failed

That's why the CI didn't detect it until the release.
And that's why the CI will fail until a new release.
But as it concerns only the `jhipster info` commands, I think it's ok.

**Comment by murdos** [comment]
Thanks for the explanation! I was wondering why we hadn't detected the issue earlier.
Is it possible to fix the CI and use `npm link`?

**Comment by pascalgrimaud** [comment]
We can of course use `npm link`, but by doing this, we won't detect some potential other problems until the release. We already encounted these kind of things in the past.
- current installation -> similar as an npm install -g <package>
- npm link -> workflow for development

I think it's better to keep the current installation as it's the closest to the final release, and there is only 1 command which is done after the generation: `jhipster info`.

**Comment by pascalgrimaud** [comment]
I'm confident, let's merge this
Then, I'll do a patch release, probably tomorrow, after waiting all our daily builds

**Pull request merged**
