### PR TITLE
Disable allow unknown option.

### PR DESCRIPTION
**Pull request by mshima**
Closes https://github.com/jhipster/generator-jhipster/issues/11896

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by MathieuAA — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
@MathieuAA @mshima : all daily builds related to JDL failed
See https://github.com/hipster-labs/jhipster-daily-builds/runs/1104989345

Can one of you have a look plz ?

**Comment by MathieuAA** [comment]
Alright

**Comment by MathieuAA** [comment]
This is because there's an unknown option "no-force".

**Comment by pascalgrimaud** [comment]
@MathieuAA : so there is a bug from this PR, I think.

```
10:01:57 in ~/tmp/05-jdl 
➜ vim app.jdl

10:02:09 in ~/tmp/05-jdl took 9s 
➜ l
total 16K
drwxr-xr-x 2 pgrimaud pgrimaud 4,0K sept. 12 10:02 .
drwxrwxr-x 7 pgrimaud pgrimaud 4,0K sept. 12 09:59 ..
-rw-r--r-- 1 pgrimaud pgrimaud 4,3K sept. 12 10:02 app.jdl

10:02:10 in ~/tmp/05-jdl 
➜ jhipster import-jdl *.jdl             
INFO! Using JHipster version installed globally
INFO! Executing import-jdl app.jdl
INFO! The JDL is being parsed.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
INFO! Found entities: Customer, Product, ProductCategory, ProductOrder, OrderItem, Invoice, Shipment, Notification.
INFO! The JDL has been successfully parsed
INFO! Generating 4 applications.
error: unknown option '--no-force'
INFO! Generator app child process exited with code 1
error: unknown option '--no-force'
INFO! Generator app child process exited with code 1
error: unknown option '--no-force'
INFO! Generator app child process exited with code 1
error: unknown option '--no-force'
INFO! Generator app child process exited with code 1
ERROR! JHipster finished with code 1
```

**Comment by mshima** [comment]
@pascalgrimaud thanks for the noting.
Since jhipster code will be in 2 days I opted to revert.
The problem is https://github.com/tj/commander.js/issues/1343.

`jhipster jdl foo.jdl` creates executes a command with `force: false` option.
Our Import-jdl fork option, default when the jdl contains more than 1 application (disabled for 1 application to add liquibase support), calls jhipster command again with `jhipster —no-force`.
For all generator options the negate option was added, but not for options added mannually.

I will add a commander copy to our project (just 1 file) and fix https://github.com/tj/commander.js/issues/1343.
It’s better than keeping 2 options parser in our project, commander and meow.

**Comment by pascalgrimaud** [comment]
Thanks a lot @mshima 
Yes as during JHipster Code, we'll use master branch... so `import-jdl` must work, that's why I ask it here :-)

**Pull request merged**
