### PR TITLE
Add support to custom ids.

### PR DESCRIPTION
**Pull request by mshima**
This PR adds support to custom ids:
```
entity Foo {
  id UUID
}
```
and
```
entity Foo {
  @Id customId Long
}
```

Relationships are not complete yet.
Angular and CI changes split into https://github.com/jhipster/generator-jhipster/pull/13257 and https://github.com/jhipster/generator-jhipster/pull/13204

Related to https://github.com/jhipster/generator-jhipster/issues/7112

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Which type can we use ? UUID ? Long ?

**Comment by mshima** [comment]
> Which type can we use ? UUID ? Long ?

Both with auto generation.
Others with manual generation, but I didn't try.
```
entity Foo {
  @AutoGenerate(false) @Id String customId
}
```

**Comment by mraible** [comment]
It would be cool if we could generate UUIDs instead of Long for IDs. My 21-Points Health app has been in production for over 5 years and it has issues with Long. I created [this PR to fix it](https://github.com/mraible/21-points/pull/58), but I'm hesitant to merge it because it's not a standard JHipster feature and it'll be difficult to build the app again for JHipster 7.

**Comment by mshima** [comment]
Merging this later today if there is not objections.

**Review by DanielFran — APPROVED** [review]

**Pull request merged**
