### PR TITLE
Adapt to Neo4j-Migrations 1.x API.

### PR DESCRIPTION
**Pull request by michael-simons**
Fixes broken build mentioned in #17308.

### CODE REVIEW

**Comment by DanielFran** [comment]
@atomfrede Can you check it please?

**Comment by atomfrede** [comment]
@michael-simons :heart: You are just awesome

**Comment by mshima** [comment]
Triggered daily builds: https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/1583333634

**Review by atomfrede — APPROVED** [review]

**Comment by mshima** [comment]
It’s failing with gradle.
We will probably need to fix at jhipster-bom.
Like this:
https://github.com/jhipster/jhipster-bom/blob/d6a7cf130325ae5580b3419a6ac30ffdb0faa2cc/jhipster-dependencies/pom.xml#L641-L646

**Pull request merged**
