### PR TITLE
Replace Font Awesome icons on admin menu for issue #12457

### LINKED ISSUE #12457: Front: icon in menu
##### **Overview of the issue**

The icon in menu could be more appropriate, for Angular, React and Vue
I suggest:
- change the icon of administration to https://fontawesome.com/icons/users-cog?style=solid
- change the icon of administration>configuration to https://fontawesome.com/icons/cogs?style=solid
- change the icon of administration>user-management to https://fontawesome.com/icons/users?style=solid
- change the icon of administration>database to https://fontawesome.com/icons/database?style=solid

##### **Motivation for or Use Case**

Better UI 

##### **Reproduce the error**

- generate an application
- start the app
- log in
- navigate in menu

##### **Suggest a Fix**

- import new icons
- use these icons in page

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ascelineboullen**
Fixed #12457 

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@ascelineboullen Can you please sign the CLA?

**Comment by ascelineboullen** [comment]
> @ascelineboullen Can you please sign the CLA?

I've already signed the CLA, but it's not working

**Comment by pascalgrimaud** [comment]
wow, I didn't expect so much work !
Thanks and congrats for your 1st contribution @ascelineboullen

**Comment by pascalgrimaud** [comment]
Thanks and congrats for your 1st pull request @ascelineboullen

**Comment by ascelineboullen** [comment]
@pascalgrimaud, I did my bug bounties request on : https://opencollective.com/generator-jhipster/expenses/25239
Thanks ! :)

**Comment by pascalgrimaud** [comment]
@ascelineboullen : approved :)

**Pull request merged**
