### PR TITLE
replaced 31 with getClass().hashCode() for Entity hashCode

### PR DESCRIPTION
**Pull request by pblanchardie**
Use `getClass().hashCode()` instead of `31` as Entity hashCode, as mentioned in #10097 (initially #8656).

I noticed that @Shaolans copied this implementation to `EntityDTO.hashCode` (commit 6a66c401), so I also updated it even if I'm not sure why it absolutely needs to be aligned, as DTOs don't have the same constraints as JPA Entities regarding equals and hashCode.

---

Please make sure the below checklist is followed for Pull Requests.

-   [X] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [X] Tests are added where necessary
-   [X] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by mshima — APPROVED** [review]
LGTM

**Comment by pblanchardie** [comment]
Please let me add a comment in the code before merging.

**Comment by DanielFran** [comment]
@pblanchardie Can you please add the comment so we can merge it?

**Comment by DanielFran** [comment]
Thanks @pblanchardie for the contribution

**Review by DanielFran — APPROVED** [review]
LGTM

**Comment by pascalgrimaud** [comment]
Missing unit tests here

**Pull request merged**
