### PR TITLE
Jhipster ignore

### LINKED ISSUE #12080: .jhipsterignore file
##### **Overview of the feature request**
To prevent Jhipster from overriding files, we could add a `.jhipsterignore` file to the workspace. It would have .gitignore-like syntax and could be used to "freeze" files after generation.

##### **Motivation for or Use Case**

These are some of the examples that come to my mind after having used jhipster for a while:

- Services and Controllers are almost never changed by jhipster after the layers (Controller, DTO, Service/QueryService, Repository) have been defined. By .jhipsterignoring the service and the controller after they have been created allow to customize them without going side-by-side.
- in a "DDD" like scenario (pointed out here: https://github.com/jhipster/generator-jhipster/issues/11122#issuecomment-653464042), or simply when I write custom logic into the entities. it could be useful to freeze the entity and handle the upgrade manually. 
- sometimes I don't need to generate a controller for an entity, I just use the entity and the repository in my business layer. (though a `@skipCrud` in the jdl is probably more appropriate) 
- liquibase changeset should never change (see also: https://github.com/jhipster/generator-jhipster/issues/11398
- Other "fragile" files: `SecurityConfiguration`, `UserService`, email templates

There are other scenario where this feature can be useful, these are some of them. 

I drafted the change here: https://github.com/ecostanzi/generator-jhipster/commit/f58e95ac51adf5debc9ae6fa1375e3d9b69ea23d. If you like the idea I can move on. 

##### **Related issues or PR**

I took the idea after reading this issue: https://github.com/jhipster/generator-jhipster/issues/9171

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by Tcharl**
fix #12080

I've to add test to be confident but the idea is here :-).

Any remark?
---

Please make sure the below checklist is followed for Pull Requests.

-   [X ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@Tcharl https://github.com/jhipster/generator-jhipster/pull/12521

**Comment by mshima** [comment]
> @Tcharl #12521

Missing:
- define file name
- add tests
- move to upstream conflicter.

**Comment by Tcharl** [comment]
@mshima , so we close this one in favor of yours?

**Comment by mshima** [comment]
> @mshima , so we close this one in favor of yours?

@Tcharl I think so, unless you have some objection to this.
It's feature complete.
I've been using at my project and it's working great.

A major yeoman-generator/environment is pending, probably I will do it later next month.
I am not convinced with .yoattributes name, maybe .yo-resolver, .yoignore can be used too.

There is the possibility to merge and keep it here while I don't finish yeoman-*.

**Pull request closed without merging**
