### PR TITLE
add invalid tokens metrics + tests

### LINKED ISSUE #16269: Custom metrics and logging for invalid JWT tokens
https://github.com/jhipster/generator-jhipster/blob/b3a50e9fea46f3e5dcdc496010f4b3ff415d1af8/generators/server/templates/src/main/java/package/security/jwt/TokenProvider.java.ejs#L123

There's already a `TRACE` level log row (with error details) for the very same event, and I think this is the proper level for this kind of events. I think `INFO` is appropriate for general information about the application status (e.g. app bootstraping, during normal operation, recurring tasks progress).

So, I propose to get rid of the `INFO` log row, and to change the `TRACE` log row message to `"Invalid JWT token."` too.

### PR DESCRIPTION
**Pull request by nickshoe**
add a service to track token validation errors, use it into the existing TokenProvider class and add corresponding tests

Closes #16269

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by nickshoe** [comment]
@mshima ok, I'll run `npm ci`. I'm using WSL2 under Windows, so it's Linux actually (Ubuntu to be precise).

**Comment by DanielFran** [comment]
> @DanielFran what if I add some content to the [monitoring page](https://www.jhipster.tech/monitoring/) first? We've added some costum metrics for monitoring purpouses, after all.

@nickshoe good Idea

**Comment by nickshoe** [comment]
@DanielFran I've made the PR for the documentation: https://github.com/jhipster/jhipster.github.io/pull/1175.

**Comment by nickshoe** [comment]
@DanielFran added a line to "security" page too, referencing the new section in the "monitoring" page.

**Pull request merged**
