### PR TITLE
add support for 2 new languages

### PR DESCRIPTION
**Pull request by vivekmore**
add i18n support for

1. Marathi
2. Hindi

### CODE REVIEW

**Comment by vivekmore** [comment]
Some work is still pending for Hindi locale jsons 
committed initial draft of work which is 75% complete.

I'll comment here once the PR is good to be merged.

**Comment by deepu105** [comment]
@vivekmore in future if you are doing a PR plz submit only when its completed as we cant have WIP PRs in our queue for long

**Comment by vivekmore** [comment]
sure @deepu105

**Comment by deepu105** [comment]
Im closing this plz open a new PR when its ready

**Pull request closed without merging**
