### PR TITLE
switch to UI Bootstrap's pagination

### LINKED ISSUE #1374: Why entity generator don't use pagination directive?
(Google translate help)

1. Why entity generator don't use pagination directive?
2. Why pagination directive use the "angularAppName" in your name? Others directives don't use...

Thanks!

### PR DESCRIPTION
**Pull request by geraldhumphries**
switch user-management page and entity generator to using UI Bootstrap's
pagination and pager directives

fix #1374

### CODE REVIEW

**Comment by geraldhumphries** [comment]
UI Bootstrap's pagination is 1-indexed which is why the page variables were changed to 1.

I have tried out the entity generator and generated a full app (for user management) and ran Mocha tests but I have not tested out Cassandra! I have a feeling that the `X-Total-Count` header might be empty and could break something.

**Comment by geraldhumphries** [comment]
After #2389 is merged in, this will need to be modified (or vice-versa)

**Comment by geraldhumphries** [comment]
Translations have not been done, but can be added with filters:

`previous-text="{{ 'global.pager.previous' | translate }}" next-text="{{ 'global.pager.next' | translate }}"`

I have left them out for now and made the buttons `«` and `»` because adding new messages means updating ALL the languages.

**Comment by geraldhumphries** [comment]
Something seems to be wrong with Travis. The first build failed for something that didn't appear to be related to the code, so I closed and reopened the pull request to make it run again. It gave a different error. Any thoughts?

**Comment by jdubois** [comment]
@geraldhumphries Travis had a timeout, I just ran it again

**Comment by deepu105** [comment]
We should remove the unused directives and their html files

**Comment by deepu105** [comment]
@geraldhumphries #2389 is merged can you plz update this as well?

**Comment by geraldhumphries** [comment]
Updated with the new names, removed the unused directives and templates, and fixed conflict.

**Comment by deepu105** [comment]
+1

**Comment by deepu105** [comment]
have someone tested this with cassandra?

**Comment by jdubois** [comment]
@deepu105 I'm going to test this with Cassandra

**Comment by jdubois** [comment]
Works great! Also tested with MongoDB

**Pull request merged**
