### PR TITLE
Add missing enum i18n for gl and ro [ci skip]

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Following this initial PR https://github.com/jhipster/generator-jhipster/pull/5465

### CODE REVIEW

**Comment by kaidohallik** [comment]
I think (as you pointed out in https://github.com/jhipster/generator-jhipster/pull/5465#issuecomment-288488570) it's better to remove all `_enum_<lang>.json` files and add one general file `_enum.json`.
And replace [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L1781) `_enum_${language}.json` with `_enum.json`.

**Comment by pascalgrimaud** [comment]
This PR is just for a very (and easy) fix

Sure, there is something to do about it.
Do you want to take the lead for improving the enum part, @kaidohallik ?

**Comment by kaidohallik** [comment]
OK, I'll do PR where I leave only 1 general `_enum.json` file.

**Comment by deepu105** [comment]
Closing in favor of the other PR

**Pull request closed without merging**
