### PR TITLE
WIP - start migrating cli to mjs

### PR DESCRIPTION
**Pull request by Tcharl**
Contributes to https://github.com/jhipster/generator-jhipster/issues/19113

I think that I'm too dumb to continue this PR: help would be really appreciated.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
I don't think rewiremock will work for us. See the ESM section `powered by [@std/ESM](https://github.com/standard-things/esm/), not native modules`.
I won't work with native esm modules.

We will need something like https://github.com/iambumblehead/esmock but, it won't work too. Since it conflicts with existing loader for typescript.

The short story: I am writing loaders that won't conflict with each other.

**Comment by Tcharl** [comment]
Why is JS so difficult?

**Comment by Tcharl** [comment]
@mshima found testdouble, which works well: I reworked the entire jdl.spec and succeed, now tackling import-jdl.spec

**Review by mshima — CHANGES_REQUESTED** [review]
Please keep the PR focused.
Templates changes should be avoided, there are lots of templates changes at sb3 branch.
We should avoid conflicts.

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/pull/20549 integrates a new module mocking lib.
Should be compatible with esm/js, esm/typescript, commonjs/js but not commonjs/typescript.

**Comment by Tcharl** [comment]
@mshima can you please take a look? Just to see if I am in the good direction. 
Quick overview:
 - Tried to use standard loaders instead of the auto one to lower the contributors load (and ensure proper support)
 - Didn't touch any template
 - have some doubt on dynamic imports changes

**Pull request closed without merging**
