### PR TITLE
add email size min  = 5 param check and simplify equals() function

### PR DESCRIPTION
**Pull request by tezcane**
User.java: Add email @Size min = 5 boundary (exists everywhere else)
User.equals(): replace if else block with "return login.equals(user.login)"

new issues

### CODE REVIEW

**Comment by jdubois** [comment]
I'm sorry but this PR does far more than just simplifying an equals() method - can you have a look?

**Comment by deepu105** [comment]
can you rebase this as well

**Comment by tezcane** [comment]
OK, I will just send User.java in the PR (as originally intended).  Much appreciated that @deepu105 took in most of my PR's still.  Still scratching my head here.

**Comment by tezcane** [comment]
New PR for this: #5467  Closing it.

**Comment by tezcane** [comment]
New PR for this: #5467  Closing it.

**Comment by tezcane** [comment]
New PR for this: #5467  Closing it.

**Pull request closed without merging**
