### PR TITLE
Ask for Heroku JHipster Registry components

### PR DESCRIPTION
**Pull request by jkutner**
This solves a common mistake where users enter the JHipster Registry URL without including the username:password. The prompts look thusly:

```
? What is the name of your JHipster Registry Heroku app? sushi
? What is your JHipster Registry username? admin
? What is your JHipster Registry password? changeme
JHIPSTER_REGISTRY_URL: https://admin:changeme@sushi.herokuapp.com
```

### CODE REVIEW

**Comment by deepu105** [comment]
@jkutner I also noticed that the heroku sub gen creates bootstrap yml files for monolith without a registry is that expected?

**Comment by jkutner** [comment]
@deepu105 yes, that way it can be easily added in later without running the generator.

**Comment by jkutner** [comment]
@deepu105 let me know if you think that's misguided.

**Comment by deepu105** [comment]
@jkutner i'm not sure if the `bootstrap-heroku.yml` is needed when you do not enable registry for a monolith, @jdubois WDYT?

**Comment by jdubois** [comment]
Indeed @deepu105 if you don't use Spring Cloud Config (= JHipster Registry), you probably don't need a bootstrap-*.yml file

**Comment by jkutner** [comment]
@deepu105 @jdubois ok, i can conditionally add `bootstrap-heroku.yml`. But can I make that change in a separate PR and merge this one as is?

**Comment by jdubois** [comment]
@jkutner whatever is easier for you (and the build is currently broken, so it's happy hour for merging!)

**Pull request merged**
