### PR TITLE
Cancel outdated workflow runs.

### PR DESCRIPTION
**Pull request by mshima**
Related to https://github.com/jhipster/generator-jhipster/issues/15205 and https://github.com/jhipster/generator-jhipster/issues/14566.

Using group name as `worflowName-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}`.
PRs should resolve as `worflowName-refs/heads/branchName`
Push events to main should resolve as `worflowName-commitHash`, so will not cancel running workflows.
Push events to others branches should resolve as `worflowName-refs/heads/branchName`.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
I will try to enable for branches others than main later.
Is working great for PRs.

**Comment by deepu105** [comment]
@mshima I dont get your comment in PR description, on newer commits it should cancel older workflows right? even running ones as the new commit is what matters

**Comment by mshima** [comment]
If we merge 5 PRs at once like we always do, only the last will complete. If that one fails, we will have to manually run every other PR merged at the same time.
@deepu105 IMO a push to main must always complete the workflows, so we don't need to bisect after.

As it is now, this PR cancels every push/pr outdated workflows runs except a push to main branch.

**Comment by deepu105** [comment]
Yes agree for main but for PR builds I think the last commit would be enough and all others can cancel even if running

**Comment by mshima** [comment]
It will cancel every push/PRs except push to main.

**Review by deepu105 — APPROVED** [review]

**Pull request merged**
