### PR TITLE
Updated the JCore dep to v3.3.3

### PR DESCRIPTION
**Pull request by MathieuAA**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X] Tests are added where necessary
- [X] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
I'm finding it weird that NPM uses unfixed versions in the package-lock, did I do something wrong?

**Comment by jdubois** [comment]
@MathieuAA I have no idea what you did wrong, as I'm having the same issue!! But indeed, all those should be fixed, otherwise it's going to be a nightmare.

**Comment by jdubois** [comment]
Oh: https://github.com/npm/npm/issues/20434

**Comment by MathieuAA** [comment]
@jdubois I don't there's at least one good package manager for this ecosystem...

**Comment by jdubois** [comment]
It looks like it's only in the "requires" sections, so that should be fine, hopefully. I'm upgrading to the latest NPM 6 release, and will overwrite your `package-lock.json` with it.

**Pull request merged**
