### PR TITLE
Fix git commit with microservices

### PR DESCRIPTION
**Pull request by pascalgrimaud**
When generating a microservice, `git commit` is done before the `npm install`
This PR will fix it because I change the place where `npm install` should be done.
But it will reveal another problem with `jhipster import-jdl`

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
@pascalgrimaud let me take a look at this, this is quite tricky and last time I moved some things around to fix some issues. Give me this weekend to test this with all scenarios

**Comment by pascalgrimaud** [comment]
Ok, no worry @deepu105 
Just for your information, I'm working right now with @PierreBesson : we will probably update this PR to try to fix the issue with `jhipster import-jdl` + git

**Comment by pascalgrimaud** [comment]
I retested it, and there is no npm install anymore.
I did something wrong here

**Comment by pascalgrimaud** [comment]
Updated my PR, it should be good now

**Pull request merged**
