### PR TITLE
Remove watcher from $rootScope upon $scope destroy

### PR DESCRIPTION
**Pull request by trevershick**
Watchers on root scope should be cleaned up or it can lead to memory leaks.  Attach a listener to the scope, so that when it's destroyed ($scope.$on('$destroy'...) call the unsubcribe method returned from the $rootScope.$on(...) call

### CODE REVIEW

**Comment by deepu105** [comment]
Ok with your first commit, but your second commit adds something new, we never had karma test cases for entities, i know its good to have, but needs review from the board 

Guys for your attention plz @jdubois @andidev @gzombor @gmarziou @mraible @moifort @atomfrede

**Comment by atomfrede** [comment]
@trevershick Thanks, didn't notice listeners are not unregistered. I can have a look at the entity test, but it looks good to me.

**Comment by mraible** [comment]
I like the entity test, but I think users will want tests for the other controllers (list and dialog) as well.

**Comment by gzsombor** [comment]
It's a nice addition, we should merge it.
We can always add new tests for other code as well, if someone contribute one :)

**Comment by atomfrede** [comment]
@gzsombor Yes that would also be my point of view. We have a default test to check that nobody creates a memory leak (or doesn't change the default behaviour).

**Comment by trevershick** [comment]
Provided this PR ends up getting merged and we want to add tests, I plan on working on adding those unit tests for the controllers in subsequent PRs.

**Comment by deepu105** [comment]
Yes plz @jdubois if you are ok with this we can merge i guess

**Comment by jdubois** [comment]
Thanks guys! Not too much time today, but it looks good and you all agree, so merging this!

**Comment by deepu105** [comment]
@trevershick plz feel free to do PR to add/improve the entity karma tests

**Pull request merged**
