### PR TITLE
Switch to composite mode for defining the configserver sources

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to this ticket: https://github.com/jhipster/jhipster-registry/issues/281
Fixed by this PR: https://github.com/jhipster/jhipster-registry/pull/282
See official documentation: https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html#composite-environment-repositories

_____

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@PierreBesson : as soon as the new registry is released, I can update this PR to point to the new release. Just tell me

**Comment by pascalgrimaud** [comment]
Then, we need to update the documentation

**Comment by PierreBesson** [comment]
I just did the release : https://github.com/jhipster/jhipster-registry/releases/tag/v4.0.0

**Comment by pascalgrimaud** [comment]
Just updated my PR to use JHipster Registry v4.0.0

**Pull request merged**
