### PR TITLE
Add issue stats

### PR DESCRIPTION
**Pull request by deepu105**
@jdubois what do you think of this?

sample https://github.com/jhipster/generator-jhipster/blob/8eb8bfcbeaafd8856085841d3bd2100b5e257692/README.md

### CODE REVIEW

**Comment by deepu105** [comment]
badges from http://issuestats.com/github/jhipster/generator-jhipster

**Comment by jdubois** [comment]
More pressure for us! But yes it looks interesting, let's try it.

**Comment by atomfrede** [comment]
@deepu105 There is a missing ``/`: ``http://issuestats.com/github/jhipster/generator-jhipsterbadge/issue?style=flat`` Can you fix it? I don't have my laptop here right now.

**Comment by atomfrede** [comment]
@deepu105 There is a missing ``/``: ``http://issuestats.com/github/jhipster/generator-jhipsterbadge/issue?style=flat``. Can you fix it? I don't have my laptop here at the moment.

**Comment by deepu105** [comment]
Oops ok ill

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
I tried to solve it but it's still broken... Looks quite unstable, I get application errors from their backend, so maybe we shouldn't use this after all.

**Comment by jdubois** [comment]
yes their backend is currently down.... I don't like this as it's on our front page -> @deepu105 OK to revert this?

**Comment by deepu105** [comment]
Yes please, saw it on angular page so thought might be cool. Its not very
important so ya lets revert

Thanks & regards,
Deepu
On 2 Aug 2016 19:32, "Julien Dubois" <notifications@github.com> wrote:

yes their backend is currently down.... I don't like this as it's on our
front page -> @deepu105 <https://github.com/deepu105> OK to revert this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/pull/3911#issuecomment-236913550>,
or mute the thread

**Pull request merged**
