### PR TITLE
Fix git commit for import-jdl

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/8547

Now, when using `jhipster import-jdl file.jdl`, all applications are correctly committed with git.

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
No I wouldn't change the default behavior. Besides, monorepos have huge downsides for microservices, as the idea is that they are loosely coopled (and here you can only a tag/release for everything at the same time)

**Comment by deepu105** [comment]
@jdubois ok its settled then :)

**Comment by atomfrede** [comment]
This will also resolve https://github.com/jhipster/generator-jhipster/issues/8503

**Comment by jdubois** [comment]
Thanks @pascalgrimaud !!

**Pull request merged**
