### PR TITLE
Add option to suppress the transfer progress for maven download

### PR DESCRIPTION
**Pull request by pmverma**
Related to #7785.

Maven has now an option to suppress the transfer progress when downloading/uploading in interactive mode.
This is only for automated tests for main generator. Not for generated project.

See more at https://maven.apache.org/docs/3.6.1/release-notes.html

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pmverma** [comment]
I know this won't bring any value but it will reduce number of lines hence we don't have to see raw logs.
When cache is available then this has no effect.

**Comment by pascalgrimaud** [comment]
> I know this won't bring any value

you're wrong ! :-)
it helps a lot when reading logs in Azure !

**Comment by pmverma** [comment]
Thanks @pascalgrimaud. Same for travis, I mostly had to read logs in raw format and it is annoying.

**Comment by pascalgrimaud** [comment]
Yes, the same for me, specially with phone... it's a pain.
Thanks a lot for your help @pmverma !

**Pull request merged**
