### PR TITLE
Check installation java8

### PR DESCRIPTION
**Pull request by pascalgrimaud**
@gmarziou : I work often on the train and checking github connectivity stucks me. So in my opinion, I don't think it's usefull, because if we check github connectivity, we have to do the same for npm and bower. What do you think ?

@deepu105 : can you check if this new PR works on windows plz ?

### CODE REVIEW

**Comment by deepu105** [comment]
I dont think we need to check connectivity as I can generate an app and
work without connectivity as well

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@pascalgrimaud  I checked in windows there are 2 issues
1. in windows `javac -version` doesnt work `java -version` works (if the second commnad works in unix I suggest to use that)
2. `stderr` has below value, so getting java version number fails for current code, may be do a regex parse
```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)
```

**Comment by gmarziou** [comment]
Checking Github connectivity would be an extra help for newbies, and we already had such cases in the past, however this could be just a warning, or we don't do it if it takes some time to timeout when you're offline.

I don't think that checking connectivity with npm registry would help as user would probably not be able to install yo or jhipster.

I'm also wondering whether all checkings make sense in all cases: java when --skip-server, node tools when --skip-client

**Comment by pascalgrimaud** [comment]
@deepu105 :
`java -version` works in linux, so I will replace `javac -version` and use regex

@gmarziou :
Yes you're right. I will add checkGitConnectivity
And I will add --check-install flag, with true by default -> when user wants to avoid checking connectivity

**Comment by gmarziou** [comment]
--check-install flag is great idea for power users.

**Comment by deepu105** [comment]
Also move the client side and server side checks respectively  into client
sub generator and server sub generator from main generator. Keep common
checks if any in the main generator

**Comment by pascalgrimaud** [comment]
@deepu105 : I could put the respective checks into client/server sub generator in initializing session
But, if I do it for client sub generator, the check will be done only after the 12th question -> so I prefer keep it in main index.js and check with skipClient / skipServer

**Comment by deepu105** [comment]
No, regardless of where you put them yeoman will queue them together in the
run loop so if its in init section on client and server it will be shown
before all the questions, just try it out and see

**Comment by pascalgrimaud** [comment]
Few tests this morning, before day work:
- add `this.log('hello client');` before this line : https://github.com/jhipster/generator-jhipster/blob/master/generators/client/index.js#L113
- when launching `yo jhipster`, the message `hello client` is displayed after question 12/15
- when launching `yo jhipster:client`, the message is displayed before questions

I don't get it, where moving to client sub gen ? => I will dig tonight!

**Comment by deepu105** [comment]
Ok then you do it with skipServer flag for now, ill see how it can be moved,

Thanks & Regards,
Deepu

**Pull request merged**
