### PR TITLE
docker-compose file : registry

### PR DESCRIPTION
**Pull request by pascalgrimaud**
new docker-compose file : registry.yml
It uses the official [jhipster/jhipster-registry](https://hub.docker.com/r/jhipster/jhipster-registry) image

To start the registry :
```
docker-compose -f src/main/docker/registry.yml up -d
```

Travis build should not display stacktrace anymore (for gateway and microservice build)

### CODE REVIEW

**Comment by jdubois** [comment]
Cant' wait to test this!
Shouldn't we call the file "jhipster-registry.yml" instead of "registry.yml"?
Anyway that name should change, it's not just a registry anymore.

**Comment by pascalgrimaud** [comment]
yes, you can rename registry.yml to what you want, of course

But by changing the name, do you mean changing the name of repository jhipster-registry too ?

**Comment by jdubois** [comment]
Yes, I'm going to send an email to the dev mailing list about that

**Comment by pascalgrimaud** [comment]
Oh ok. I'm not sure we can rename a Docker Hub repository

So as soon as you rename the Github repository, I will :
1) delete https://hub.docker.com/r/jhipster/jhipster-registry
2) recreate a new Docker Hub repo and link to the new Github repo
3) configure branch/tag
4) => you :smile: configure the trigger

**Pull request merged**
