### PR TITLE
replace nativeLanguageShortName with nativeLanguage, fix #3554 fix #3444

### LINKED ISSUE #3444: Error when entity have a attribute enumeration (enum java).
When I use "entity" sub-generator to create a entity that have a attribute enumeration (enum java), I get an error when click on Menu of entity in Angular.
In fact, nothing happens. In the file "...src\main\webapp\app\entities\myentity\myentity.state.js" I have, in part, the code:

```        
        resolve: {
            translatePartialLoader: ['$translate', '$translatePartialLoader', function ($translate, $translatePartialLoader) {
                $translatePartialLoader.addPart('myEntity');
                $translatePartialLoader.addPart('');
                $translatePartialLoader.addPart('global');
                return $translate.refresh();
            }]
        }
```

When I remove this line: $translatePartialLoader.addPart(''); Everything works well. This would be expected behavior or is it a bug?
Ps. In entities that do not have enumeration (enum java type) this line is not generated.

.yo-rc.json File:

{
  "generator-jhipster": {
    "jhipsterVersion": "3.1.0",
    "baseName": "finame",
    "packageName": "br.com.finame",
    "packageFolder": "br/com/finame",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "7cd65d49249f429c58d1d04359454b1c7b2bfb0c",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br",
      "en"
    ]
  }
}

### LINKED ISSUE #3554: Application doesnt load i18n files for 5 letter language codes
Seems like i18n doesn't load any files and app fails when languages with `pt-*` pattern is selected as native language.

Seems like an issue with setting `nativeLanguageShortName` instead of `nativeLanguage`

If I change to `nativeLanguage` it works

@andidev I do not see why `nativeLanguageShortName` is required? shouldnt it be `nativeLanguage` every where?

### PR DESCRIPTION
**Pull request by andidev**

### CODE REVIEW

**Comment by andidev** [comment]
@deepu105 
I have replaced the nativeLanguageShortName variables with nativeLanguage. Though it is still important that the nativeLanguage variable is set to 'en' when enableTranslation is false, this was done when setting the nativeLanguageShortName variable, [here](https://github.com/jhipster/generator-jhipster/pull/3561/files#diff-0aacb43c4d7b6935003fe4580a092707L289) and [here](https://github.com/jhipster/generator-jhipster/pull/3561/files#diff-053e6cfb498ac0d242b20c194eb7e318L884).

Not sure where this should be done now. Any ideas?

**Comment by deepu105** [comment]
Let me see

**Comment by deepu105** [comment]
its taken care of here https://github.com/jhipster/generator-jhipster/commit/52f5cbaeaeb9d613f6c9115f227312a87a7a6513

**Comment by andidev** [comment]
Great thanks!

**Pull request merged**
