### PR TITLE
Cleanup the generated java code

### PR DESCRIPTION
**Pull request by tuxetuxe**
Add serialVersionUIDs to serializable classes;
Fix minor java generics warnings;
Remove unused imports;

### CODE REVIEW

**Comment by gzsombor** [comment]
:+1:

**Comment by jdubois** [comment]
I will need to pass my tests before merging, but it looks good.

My only issue is with the "serialVersionUID" -> this doesn't do anything useful excepted having the default Eclipse configuration be happy.
I don't want to have a useless line of code, so I don't want to merge this part of the code.

**Comment by gzsombor** [comment]
You've already merged a commit a couple of days ago, just for making an IDE warning disappear :wink:

**Comment by jdubois** [comment]
@gzsombor yes, but this was with a IDE I use :-)

The real issue is that it made a wrong "compilation error" in IDEA. Here it's just a warning, and you can (should?) turn it off. It's not as annoying as compilation error.

**Comment by gzsombor** [comment]
You could, as well, ignore that false warning in that case - or stop using that broken IDE. But in this case, it's a perfectly valid code quality improvement. It's not only Eclipse complains it but FindBugs ( http://findbugs.sourceforge.net/bugDescriptions.html#SE_NO_SERIALVERSIONID ) and Sonar also do the same.

**Comment by tuxetuxe** [comment]
@jdubois Yes it is just a warning in eclipse. 
This PR fixes some of the warnings in a hipster generated project. (In he serialVersionId case, anyone can select all the warnings a do a "quick fix" that adds exactly this PR's code!)
However I would disagree that the serialVersionId is useless. It is a best practice (whence the warning!), documented in the Serializable interface documentation

```
[...]
* deserialization will result in an {@link InvalidClassException}.  A
 * serializable class can declare its own serialVersionUID explicitly by
 * declaring a field named <code>"serialVersionUID"</code> that must be static,
 * final, and of type <code>long</code>:
 *
 * <PRE>
 * ANY-ACCESS-MODIFIER static final long serialVersionUID = 42L;
 * </PRE>
 *
 * If a serializable class does not explicitly declare a serialVersionUID, then
 * the serialization runtime will calculate a default serialVersionUID value
 * for that class based on various aspects of the class, as described in the
 * Java(TM) Object Serialization Specification.  However, it is <em>strongly
 * recommended</em> that all serializable classes explicitly declare
 * serialVersionUID values, since the default serialVersionUID computation is
 * highly sensitive to class details that may vary depending on compiler
 * implementations, and can thus result in unexpected
 * <code>InvalidClassException</code>s during deserialization.  Therefore, to
 * guarantee a consistent serialVersionUID value across different java compiler
 * implementations, a serializable class must declare an explicit
 * serialVersionUID value.  It is also strongly advised that explicit
 * serialVersionUID declarations use the <code>private</code> modifier where
 * possible, since such declarations apply only to the immediately declaring
[...]
```

**Comment by jdubois** [comment]
Yes, I know what this is for, of course.
Our entities are Serializable because it could be useful to some people:

- for people using the 2nd level cache -> if you use ehcache's diskstore for example (not our default configuration), or if you use Hazelcast
- for people who want to store their entity in the HTTP Session (this is for stateful applications, of course). 

It is not for sending them to a remote interface: I don't think anybody does that, and that would be the exactly opposite of what we try to do with our REST interfaces. So the serialVersionUID is useless for us.

**Pull request merged**
