### PR TITLE
Use spring-cloud BOM (dependency management only)

### LINKED ISSUE #3316: Wrong dependencies on spring cloud
##### **Overview of the issue**

The way we declare our dependencies on spring-cloud is wrong.

I found it by having this exception in a gateway:

~~~
java.lang.NoSuchMethodError: com.netflix.servo.monitor.Monitors.isObjectRegistered(Ljava/lang/String;Ljava/lang/Object;)Z
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.shutdown(RetryableEurekaHttpClient.java:91)
	at com.netflix.discovery.shared.transport.TransportUtils.shutdown(TransportUtils.java:40)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:70)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:823)
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1379)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
~~~

This was due to using com.netflix.servo:servo-core:jar:0.7.2 rather than 0.10.1

According this recent issue, the right way to depend on spring-boot is by importing their bom:

https://github.com/spring-cloud/spring-cloud-netflix/issues/938

##### **JHipster Version(s)** 

3.0 today's master

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

~~~json
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "buildTool": "maven",
    "jwtSecretKey": "8236c1377cd345f2a83c41efbd726577389066a1",
    "useSass": false,
    "enableTranslation": false,
    "applicationType": "gateway",
    "testFrameworks": [],
    "enableSocialSignIn": false,
    "serverPort": 8080,
    "jhiPrefix": "jhi"
  }
}
~~~

##### **Suggest a Fix** 

I will submit a PR for maven, I'll need some help for gradle.

Import the bom and do not use ${spring-cloud.version} in dependencies like this:

~~~xml
    <properties>
        <spring-cloud.version>Brixton.RC1</spring-cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zuul</artifactId>
        </dependency>
~~~

### PR DESCRIPTION
**Pull request by gmarziou**
Fix #3316 for maven and gradle

### CODE REVIEW

**Comment by deepu105** [comment]
seems to be some failure during javaCompile. I have re triggered it lets see

**Comment by deepu105** [comment]
@jdubois @gmarziou it has passed and ready now

**Comment by deepu105** [comment]
@gmarziou I think this needs rebase

**Comment by jdubois** [comment]
This should be merged -> I'm going to fix the conflicts

**Comment by gmarziou** [comment]
Sorry I was not available, thanks Julien

**Pull request merged**
