### PR TITLE
add logo in readme

### PR DESCRIPTION
**Pull request by deepu105**
coz it looks cool

@jhipster/developers can we have this in readme?

look here https://github.com/jhipster/generator-jhipster/blob/deepu105-patch-1/README.md

### CODE REVIEW

**Comment by deepu105** [comment]
stopping travis

**Comment by pascalgrimaud** [comment]
very minor issue : https://hub.docker.com/r/jhipster/jhipster/ -> the same readme.md is copied
Docker Hub can't read html... only markdown

Normally, npmjs.com should accept html format -> https://www.npmjs.com/package/generator-jhipster

**Comment by deepu105** [comment]
Npm will update only when next version is published. For docker does it
break anything?  If not i think its ok if they just ignore it.

**Comment by pascalgrimaud** [comment]
Yes minor, we can ignore it

**Comment by jdubois** [comment]
I'd rather not have the image, and have a clean Docker readme. The image
doesn't add much, and the current Docker image has more than 10K pulls, so
we'd better have a nice readme.

-> Deepu is it fine for you if I revert your change?

On Mon, Mar 21, 2016 at 6:07 AM, Pascal Grimaud <notifications@github.com>
wrote:

> Yes minor, we can ignore it
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/pull/3226#issuecomment-199128132>
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by deepu105** [comment]
I dont think this will cause any issue in docker, docker will just not show
the image thats all

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
No what I mean is that here https://hub.docker.com/r/jhipster/jhipster/ we
have some ugly HTML code, I'd like to have something clean instead, and the
image isn't really important

On Mon, Mar 21, 2016 at 10:35 AM, Deepu K Sasidharan <
notifications@github.com> wrote:

> I dont think this will cause any issue in docker, docker will just not show
> the image thats all
>
> Thanks & Regards,
> Deepu
>
> On Mon, Mar 21, 2016 at 5:15 PM, Julien Dubois <notifications@github.com>
> wrote:
>
> > I'd rather not have the image, and have a clean Docker readme. The image
> > doesn't add much, and the current Docker image has more than 10K pulls,
> so
> > we'd better have a nice readme.
> >
> > -> Deepu is it fine for you if I revert your change?
> >
> > On Mon, Mar 21, 2016 at 6:07 AM, Pascal Grimaud <
> notifications@github.com>
> > wrote:
> >
> > > Yes minor, we can ignore it
> > >
> > > —
> > > You are receiving this because you modified the open/close state.
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/jhipster/generator-jhipster/pull/3226#issuecomment-199128132
> > >
> > >
> >
> >
> >
> > --
> > Julien Dubois
> >
> > Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
> > Phone: +33 (0)6 25 02 34 18
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jhipster/generator-jhipster/pull/3226#issuecomment-199186694
> >
>
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/pull/3226#issuecomment-199192627>
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by deepu105** [comment]
Oh thats bad, no probs let me convert that to mark down :) gimme a minute

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I have corrected it, will docker update automatically?

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
yes it should be automatically updated, but docker hub is little bit slow.
let him time to finish the build

**Comment by pascalgrimaud** [comment]
perfect now, thanks @deepu105

**Pull request merged**
