### PR TITLE
Fix Elasticsearch default port in profile production

### PR DESCRIPTION
**Pull request by pascalgrimaud**
I'm testing elasticsearch and I got the same problem #1660

In development profile, no error because it's an embedded Elasticsearch

In production profile, I got this error when starting the app :
```
[INFO] com.mycompany.myapp.config.ThymeleafConfiguration - loading non-reloadable mail messages resources
[ERROR] org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository - failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
[INFO] com.mycompany.myapp.Application - Started Application in 24.697 seconds (JVM running for 25.311)
```

The elasticsearch logs :
```
[2015-10-03 19:29:33,589][WARN ][http.netty               ] [Spike] Caught exception while handling client http traffic, closing connection [id: 0x0f6c5855, /127.0.0.1:35353 => /127.0.0.1:9200]
java.lang.IllegalArgumentException: empty text
	at org.elasticsearch.common.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:89)
	at org.elasticsearch.common.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62)
	at org.elasticsearch.common.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75)
	at org.elasticsearch.common.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191)
```

In the `application-prod.yml` file, if I change : `cluster-nodes: localhost:9200` to `cluster-nodes: localhost:9300`, it seems to work.
App logs, no error :
```
[INFO] com.mycompany.myapp.config.ThymeleafConfiguration - loading non-reloadable mail messages resources
[INFO] com.mycompany.myapp.Application - Started Application in 18.54 seconds (JVM running for 19.119)
```

Elasticsearch logs :
```
[2015-10-03 19:45:08,013][INFO ][cluster.metadata         ] [Thunderclap] [user] creating index, cause [api], templates [], shards [5]/[1], mappings []
[2015-10-03 19:45:08,340][INFO ][cluster.metadata         ] [Thunderclap] [user] create_mapping [user]
```

Am I correct ?

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I made another little change : rename databaseName to name refer to https://github.com/jhipster/generator-jhipster/commit/0431d1cc7ad2cd0536d9ba01f7dcb502382b1659

**Comment by jdubois** [comment]
Not sure about this, I thought the default port was 9200?

**Comment by pascalgrimaud** [comment]
I thought too... About the port, it seems : 
* 9200 => http protocol, after launching elasticsearch : http://localhost:9200
* 9300 => transport protocol

I tested with elasticsearch and elasticsearch-docker. I had to modify 9200 to 9300 in application-prod.yml to launch my app without error in production profile.

Maybe I'm wrong and have to change default config in my elasticsearch ?

**Comment by jdubois** [comment]
Oh yes, 9200 is for doing the HTTP queries, 9300 is the transport protocol! You are correct, I'm merging this.

**Comment by maheshkaranjkar** [comment]
Hi Guys,

Even after changing port to 9300. I am getting same error.

<code>
data:
        elasticsearch:
            cluster-name:
            cluster-nodes: localhost:9300

</code>

<code>
org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository - failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository - failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
</code>

Do i need to change any other file.

Regards
Mahesh

**Comment by pascalgrimaud** [comment]
Can you show your elasticsearch logs ? (must wait some minutes after starting your app)

**Comment by maheshkaranjkar** [comment]
Sorry for Silly Question , Where Can I find elasticsearch Logs. Sorry for this But I am very new to this.

Are you asking about catalina.log

Regards
Mahesh

**Comment by pascalgrimaud** [comment]
Elasticsearch is a search engine, you have to launch it by itself (download the binary or with docker container). It's not included in JHipster.
If you don't know where finding elasticsearch logs, I suppose you didn't launch your search engine ? No search engine => no node => error at starting you app

**Comment by maheshkaranjkar** [comment]
Thanks a  Lot @pascalgrimaud  for your reply,
I will try to launch Search engine and let you know.

Regards
Mahesh

**Comment by maheshkaranjkar** [comment]
Thanks a lot @pascalgrimaud   your solution worked for me.

Regards
Mahesh

**Pull request merged**
