### PR TITLE
Replace node-sass with sass

### PR DESCRIPTION
**Pull request by bertwin**
React & Angular

see #8121 
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by bertwin** [comment]
The build failure seems unrelated

**Comment by jdubois** [comment]
@bertwin yes I messed up the master last night - can you rebase and test? And this moves to "dart-sass", right? That would be an awesome change, and it would be worth a specific release!

**Comment by bertwin** [comment]
yes, this is just replacing node-sass with dart-sass, leaving everything else as-is. 

If all goes well with dart-sass the pure css option could be removed

**Comment by jdubois** [comment]
@bertwin yes removing the pure CSS option is the next step, but there's no need to rush: this would probably annoy a lot of people, so we should first deprecate it, and give them time to migrate. It doesn't cost anything to keep it a few months.

**Comment by deepu105** [comment]
I agree the idea would be as below

1. Test this out on a release by making Sass the default option and adding
deprecation warning for CSS
2. Do the improvements to have a common base Jhipster sass file for angular
and react
3. Move to Sass only and remove CSS in a specific release after some months

**Comment by vishal423** [comment]
Today, while trying out [bootstrap material theme](https://github.com/FezVrasta/bootstrap-material-design), I faced sass compilation issues with dart-sass (also tried latest version). I haven't debugged much ,but, reverting to node-sass fixed those issues. Has anyone else also experienced similar issues?

**Comment by deepu105** [comment]
What exactly was the issue. We use the js version of dart sass, and its
much better than node sass from what I experienced.

May be that these uses something not supported by sass?

**Comment by vishal423** [comment]
I see following compilation errors:

> error  in ./src/main/webapp/content/scss/vendor.scss
> 
> Module build failed: 
>   .is-focused,
>  ^
>       Top-level selectors may not contain the parent selector "&".
>   node_modules/bootstrap-material-design/scss/mixins/_forms.scss 153:3            bmd-form-color()
>   node_modules/bootstrap-material-design/scss/_forms.scss 75:1                    @import
>   node_modules/bootstrap-material-design/scss/_core.scss 14:9                     @import
>   node_modules/bootstrap-material-design/scss/bootstrap-material-design.scss 3:9  @import
>   stdin 10:9                                                                      root stylesheet
>       in /home/vishal/node_modules/bootstrap-material-design/scss/mixins/_forms.scss (line 153, column 3)

coming out of following mixins in bootstrap-material-design (strip down styles here):

```
@mixin bmd-form-color($label-color, $label-color-focus, $border-color) {
  [class^='bmd-label'],
  [class*=' bmd-label'] {
    color: $label-color;
  }

  .is-focused,
  // may or may not be a form-group or bmd-form-group
  &.is-focused {
    // on focus set borders and labels to the validation color

    // Use the BS provided mixin for the bulk of the color
    @include form-validation-state("valid", $label-color);

  }
}
```

**Comment by deepu105** [comment]
I'm not sure if that is valid scss. Normally `&` is used when nesting but here its combined with another selector, can you check the sass spec, if its supported then its a dart-sass bug else a bootstrap-material-design bug

**Comment by deepu105** [comment]
I tried it on https://www.sassmeister.com/ and seems to work. can you check the @include usages of `bmd-form-color` may be its used in some invalid location
```

@mixin bmd-form-color($label-color, $label-color-focus, $border-color) {
  [class^='bmd-label'],
  [class*=' bmd-label'] {
    color: $label-color;
  }

  .is-focused,
  // may or may not be a form-group or bmd-form-group
  &.is-focused {
    // on focus set borders and labels to the validation color

    // Use the BS provided mixin for the bulk of the color
    // @include form-validation-state("valid", $label-color);

  }
}
.hello {
 @include bmd-form-color("red", "white", "black");
}
```

**Comment by bertwin** [comment]
It looks very similar to this: https://github.com/FezVrasta/bootstrap-material-design/issues/1300

**Comment by vishal423** [comment]
From discussions on linked issue, it seems to be an issue on bmd, however,
I wonder why that still works with latest version of node-sass?

**Comment by deepu105** [comment]
As per that issue it doesn't work with latest node sass but only works on
an older version which had a bug

**Comment by vishal423** [comment]
It works with latest node-sass v4.9.4, but, not with latest dart-sass v1.14.3. I have commented on above referenced issue as well to track it separately. Thanks everyone and I guess it's time to upgrade :smile:

**Pull request merged**
