### PR TITLE
Rename package io.github.jhipster -> tech.jhipster

### PR DESCRIPTION
**Pull request by DanielFran**
Fix https://github.com/jhipster/generator-jhipster/issues/12854

As part of V7 Roadmap, rename package io.github.jhispter -> tech.jhipster

Should we change BOM library version?
To:
 - 3.10.0 (actual version)
 - 1.0.0 (might need a new repo since 'group' as changed)
 - 7.0.0 (same as generator)?
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
I'm not sure the package name really matters does it? In reality, I'm still bitter that Facebook doesn't allow to you to post links to jhipster.tech. 🤬

**Comment by DanielFran** [comment]
It was @jdubois that request it I guess...

**Comment by pascalgrimaud** [comment]
I think it's not as simple, as Julien needs to ask access to publish to tech.jhipster at maven central.
As for now, we can publish only to io.github.jhipster

**Comment by DanielFran** [comment]
@pascalgrimaud Any suggestion about the version?

**Comment by pascalgrimaud** [comment]
just wait the confirmation from Julien first, and if it's deserved to ask some changes / new permissions to Maven Central
If it's possible and not too much work, then, we can discuss about the version :)

**Comment by jdubois** [comment]
It shouldn’t be an issue, but indeed let me ask the permissions for this package on Maven Central.

**Comment by pascalgrimaud** [comment]
Ok at the same time, is it possible to ask permissions for Deepu and me, @jdubois ?
As I'm still using your account when I want to publish to maven central...

**Comment by jdubois** [comment]
@deepu105 and @pascalgrimaud can you send me your login IDs on https://oss.sonatype.org/#welcome (please do it privately, this doesn't need to be public). Then I'll do a request on the Sonatype website.

**Comment by jdubois** [comment]
I created 2 tickets for this:

- https://issues.sonatype.org/browse/OSSRH-60960
- https://issues.sonatype.org/browse/OSSRH-60961

**Comment by jdubois** [comment]
Everything should be good on Maven Central, just be careful with https://issues.sonatype.org/browse/OSSRH-60961 as they say we *might* need to tell them to do a first sync up after our initial release

**Comment by pascalgrimaud** [comment]
@DanielFran : so if I understand well, we need to do new release of jhipster lib, right ?
What about the version we should use ? Should we keep the same sequence for version ? The latest is 3.9.0, so the next would be 3.9.1 or 4.0.0, as there will be major version

**Comment by DanielFran** [comment]
@pascalgrimaud there 3 possibilities:
- keep using current version, like 3.9 ou 4.0
- align we generator, like 7.0. This was discussed when we had security issues and it was targeting bom version because of bad description of the issue
- start with 1.0 but this would need a new repo to not conflict in the future

**Comment by pascalgrimaud** [comment]
So the last option is choosen:
- start with 1.0.x but this would need a new repo to not conflict in the future
- new repo: http://github.com/jhipster/jhipster-bom/

**Comment by DanielFran** [comment]
Superseded by #12866

**Comment by pascalgrimaud** [comment]
@jdubois : it could be interesting if @DanielFran can do release too. Is it possible ?

**Pull request closed without merging**
