### PR TITLE
Replace HerokuDatabaseConfig.java with yaml config

### PR DESCRIPTION
**Pull request by jkutner**
The `HerokuDatabaseConfig.java` is unnecessarily complicated. It also seems to have problems in some cases. The yaml config is much better.

Do I also need to do something to delete an existing `HerokuDatabaseConfig.java`? What does that look like?

### CODE REVIEW

**Comment by ruddell** [comment]
To delete an existing file in future versions, add it to [generators/cleanup.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/cleanup.js)

**Comment by cbornet** [comment]
You also need to remove heroku from the excluded profiles in the regular DatabaseConfiguration.java

**Comment by jdubois** [comment]
This is linked to #3952 -> I'll try to solve both at the same time

**Comment by jdubois** [comment]
And thanks @jkutner that's much better than the current code!

**Pull request merged**
