### PR TITLE
Add user management

### LINKED ISSUE #1525: User management
Hello the community,

I would like to know if it's will be interesting to implement in Jhipster the user management functionality. The idea is to provide for administrator user an interface to manage all the users.

We can start to implement some mains functions like:
- Display all user with summary informations
- Allow the admin user to modify setting for a specific user:
  - Change first name
  - Change last name
  - Change email
  - Activate/Disable an user
  - Change default language
  - Change authorities 

I already make a prototype for my application:

capture d ecran 2015-05-24 a 23 04 54

capture d ecran 2015-05-24 a 23 05 07
 
Thibaut.

### PR DESCRIPTION
**Pull request by moifort**
Provide the screen to manage users.

Compatibility with:
  - SQL 
  - MongoDB
  - Java 7/8

Not compatible with Cassandra (sorry Julien)

Thanks to @phouverneyuff and @atomfrede 

Fix #1525

### CODE REVIEW

**Comment by deepu105** [comment]
This would require a lot of testing i guess

**Comment by tapas4java** [comment]
Good job guys!

**Comment by matdere** [comment]
You guys rock !

-- 
Mathieu Chauvet

**Comment by matdere** [comment]
Guys, I'm gonna need a postal address to send you beers (seriously!)



-- 
Mathieu Chauvet

**Comment by jdubois** [comment]
@matdere as you @moifort and myself are all in Paris you could easily pay us a beer one evening :-)

**Comment by matdere** [comment]
@jdubois @moifort : with pleasure! I have a few free days coming but I won't forget it when I come back.

**Comment by jdubois** [comment]
@moifort some comments on your code:

- I'm a bit worried that you had to create a REST endpoint for getting the authorities. They are normally just constants. I know they are also in a database table, but this is to have foreign keys when using Spring Security. Maybe we should also "expose" those constants to the AngularJS side? But maybe your code is more generic.
- When editing a user, the language keys should be in a drop-down lists -> this is basically the same idea of exposing "constants" to the AngularJS part, in fact. We auto-generate the language menu for the user, maybe we could refactor this to have a list of language constants you could use.
- There is some formatting to be done -> do you have access to Intellij IDEA for this, this is [Policy 3](http://jhipster.github.io/policies.html).

None of those are blocker issues, anyway!!

Indeed we are going to need a lot of testing here. With such a great work (and in order to have the Intellij license), maybe you should [join the board](http://jhipster.github.io/team.html) ?

**Comment by moifort** [comment]
@matdere Thank you! But I think it's more Julien who deserve the beer. But I will be very happy to meet you!
@jdubois I will change the language keys in a drop-down-list. For the code formatting, I am sorry for that, I use Atom, I will format my code with IntelliJ. And yes I will be very happy to join the board!

**Comment by xjiaoyang** [comment]
GOOD!

**Comment by moifort** [comment]
@jdubois this is my corrections:
- Reformatting files, just check if I have a good formatting because in `index.js` I reformat lines that I didn't change
- Remove some useless generator code in `UserManagement` html and controller
- Add new translate file for NL
- Hide the field `language` when translate option is not enable
- Add a drop-down list for language keys

I didn't change the Authorities, because I am afraid to make some mistakes.

**Comment by jdubois** [comment]
OK, there is still something to talk about: the "userManagement" REST endpoint.

- It does not follow our usual namings for the AngularJS part at least
- I'm not sure we need another "resource" for that on the Java side: the UserResource should be enough

I'm going to try to refactor that.

**Comment by deepu105** [comment]
@jdubois do we also need a new userManagementDTO which is a replica of
userDTO?  Also cant we reuse user Resource,  service etc on java and
angular instead of new ones?
Im worried about code duplication
I also don't like the mapstruct DTO on this, what of all my entities are
non DTO and i want to remove mapStruct dependency?  All our core entities
arenon mapstruct and thats why i think its a better idea to reuse UserDTO
here

**Comment by jdubois** [comment]
Guys,

I have heavily refactored this, but I haven't finished yet -> as it's late and I don't want to keep it like this, I'm going to merge this PR, but then my code needs to be corrected and finished. I will do it this week if I have the time, otherwise I will appreciate your help of course!

What I have done:

- Removed the DTOs -> maybe we will need to use the current UserDTO to get the roles for the users, the problem is that I don't want to do an eager relationship on User.authorities (the good news is that if we do a fetch for every user it's not such a big issue as long as we have a 2nd level cache)
- Renamed the JS files from userManagement to user-management to follow our current coding guidelines

What still needs to be done:

- The update/delete methods do not work yet -> I want to copy what the current entity sub-generator does, so it's mostly generating an entity and copy/pasting it
- I haven't checked for Java 7, MongoDB and Cassandra
- I haven't checked that the @RolesAllowed annotations work, and I doubt they work -> this could be a big security issue
- The Authorities are not available -> we need to find a way to copy them from the backend, as they are just constants, doing a REST request to get them looks overkill
- Add some tests!

**Comment by leite08** [comment]
Hello guys!

First of all, **KUDOS** for this great project!

@moifort, thanks for this contribution!

Sorry for the newbie comment, but I've just finished merging this into my generated project and I'm getting an exception when I try to run the project on Eclipse.

I've created a question on StackOverflow: http://stackoverflow.com/questions/32609755/duplicated-mapstruct-generated-file-during-jhipster-maven-compilation

Hope this is the proper interaction flow with you guys... :)

Best regards to you all!

**Comment by leite08** [comment]
Just passing to inform the problem is fixed. Was a source folder problem with my project configuration in Eclipse. Sorry for the trouble.
Thanks!

**Comment by KazamT** [comment]
Hello guys  !
@leite08  I have the same problem .How you did to correct it ? thanks

**Comment by leite08** [comment]
Hey @KazamT! As mentioned on question in StackOverflow, I was missing the "target/generated-sources" folder on the project's source folder.
Added it with exclusion of subfolder "annotations" and added another entry to "annotations", to match the package name of the annotation classes.
Cheers!

**Comment by foxyuca** [comment]
Hello @moifort Thank you very much for your job. I have a question. I added new Roles into the DB. in the table jhi_authority, But those roles wasn't in the interface when I tried to modify an user(in the profiles section). but When I tried to relate the new role with an existing user (Modifying the values At DB level). it was showing in the main view (Table with the user view), Any Idea about this issue? Thank you

**Comment by moifort** [comment]
Hey, thanks, but I was not the only one to have worked on it :), there are @phouverneyuff, @atomfrede and @jdubois.

It's maybe due to the cache (by default it's activated). If I understand you directly add the roles into the DB, doing that you shortcut all the application cache, you need to wait 1 hour to see the data (The expiration time of the cache are define in `ehcache.xml`).

**Comment by foxyuca** [comment]
@moifort  Thank you for your answer I reviewed the cache but the problem was in other place. The file user-management-controller.js had the authorities as a static array in the java script code, I created a new rest service for the authorities in order to use it in the user-management-controller.js and load the new ROLES  from the DB and assign those roles to a user. Im going to add other new view to manage the roles via GUI. Thank you!

**Pull request merged**
