### PR TITLE
i18 support for Telugu-India language

### PR DESCRIPTION
**Pull request by harishreddy-m**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
I think you missed few files. Can you reference https://github.com/jhipster/generator-jhipster/pull/8317 to double check.

**Comment by harishreddy-m** [comment]
I left few files as it is for same reason. But all tests are passing in my
case.

Do you think it is still important to translate the files which are meant
for developer instead of end users.

**Comment by vishal423** [comment]
I think tests are passing because these bundles are not integrated with application. Have you generated application with this change and noticed new language option for Telugu available for selection? Also, post generation, check if this appears in language drop down and on selection, all translations are correctly working.

**Comment by harishreddy-m** [comment]
Thank you for responding.

I will test and update you.

**Comment by harishreddy-m** [comment]
screenshot from 2019-01-26 10 48 25

**Pull request merged**
