### PR TITLE
Add basic auth in parallel of form login

### LINKED ISSUE #2428: Combine basic auth with form login
Form login is adapted for web applications but not for mobile apps or other servers consuming the api. OAuth2 can of course be used but it is not implemented in all clients or already existing softwares.
So it would be great to combine session formlogin with stateless basic auth for /api/**.
[Here](https://github.com/spring-projects/spring-security-javaconfig/blob/master/samples-web.md#sample-multi-http-web-configuration) is a sample project that gives an idea on how to do it.

### PR DESCRIPTION
**Pull request by cbornet**
Fix #2428

### CODE REVIEW

**Comment by jdubois** [comment]
I don't want basic auth by default -> if you are not using HTTPS, then you send your credentials with each request, and that can be a security concern 
Besides, some people only put the login form in https, and then switch back to http - which of course is a bad idea, but that's a use case

**Comment by cbornet** [comment]
Well basic auth is of course not to be used without HTTPS. If you don't have HTTPS, just don't use basic auth !
If you use session auth then you stay with session auth so there is no harm in switching back to simple http (except that it is a bad idea as you said). Basic auth will not be used and you will not have your credentials exposed in the http headers.

**Comment by cbornet** [comment]
I don't know if this is clear but the angular app will continue to use form login and session as if basic auth never existed.

**Comment by jdubois** [comment]
OK, but still I don't think it's a good idea to have this by default (not big value & security issue)

But now I have an answer to everybody that I don't agree with: let's do your own JHipster module! Like they have exactly the same for Meteor: https://atmospherejs.com/jabbslad/basic-auth

As you are on the dev team -> I was going to fire up a discussion on this anyway, so let me start this in the dev mailing list (I just need to finish coding a little surprise before)

**Comment by cbornet** [comment]
Ok. As I told I have no problem closing this PR. And we can surely make this a module. Actually since this would normally be a very simple one, this would be a good training.

**Pull request closed without merging**
