### PR TITLE
Update to spring-boot 2.4.3 and other dependencies

### PR DESCRIPTION
**Pull request by DanielFran**
Dependent on https://github.com/jhipster/jhipster-bom/pull/188

Include migration of:
- infinispan version to 11.0.9.Final
- mongock version to 4.3.4
- Cassandra driver version to 4.9.0
- Caffeine version to 3.0.0
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@DanielFran : do you think we can have this for the next release plz ?

**Comment by mraible** [comment]
I tried upgrading to Mongock 4.3.5 to fix the MongoDB issues but ran into [this bug](https://github.com/cloudyrock/mongock/issues/302). The error with v4.3.4 is:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate
 [com.github.cloudyrock.mongock.driver.api.driver.ConnectionDriver]: Factory method 'connectionDriver' 
 threw exception; nested exception is com.mongodb.MongoCommandException: Command failed with error 2 (BadValue): 
 'cannot use 'j' option when a host does not have journaling enabled' on server localhost:54419. The full 
 response is {"ok": 0.0, "errmsg": "cannot use 'j' option when a host does not have journaling enabled", "code": 
 2, "codeName": "BadValue"}
```

**Comment by mraible** [comment]
Infinispan is failing with:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.infinispan.manager.DefaultCacheManager]: Factory method 'defaultCacheManager' threw exception; nested exception is org.infinispan.commons.CacheConfigurationException: ISPN000432: Missing configuration for default cache 'infinispan-samplesMicroserviceEurekaInfinispan-cluster-cache' declared on container
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 84 common frames omitted
Caused by: org.infinispan.commons.CacheConfigurationException: ISPN000432: Missing configuration for default cache 'infinispan-samplesMicroserviceEurekaInfinispan-cluster-cache' declared on container
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:269)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:230)
	at org.infinispan.spring.starter.embedded.InfinispanEmbeddedAutoConfiguration.defaultCacheManager(InfinispanEmbeddedAutoConfiguration.java:84)
	at org.infinispan.spring.starter.embedded.InfinispanEmbeddedAutoConfiguration$$EnhancerBySpringCGLIB$$d13828ed.CGLIB$defaultCacheManager$0(<generated>)
```

Downgrading to 11.0.8.Final in JHipster BOM does *not* fix the problem.

**Comment by mraible** [comment]
I'm not sure why `npm test` is failing since there are no changes to any frontend files.

```
  18 failing

  1) JHipster generator with required configuration
       "before all" hook for "writes additional default config to .yo-rc.json":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/app-required-config.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) jhipster:app with applicationWithEntities option
       with --with-entities
         and User
           "before all" hook for "should write .yo-rc.json":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/app/application-with-entities.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  3) jhipster:app with applicationWithEntities option
       with --with-entities
         and User
           "after all" hook for "should not compose with entities generator":
     TypeError: Cannot read property 'cleanup' of undefined
      at Context.<anonymous> (test/app/application-with-entities.js:113:29)
      at processImmediate (internal/timers.js:461:21)

  4) JHipster application generator with scoped blueprint
       generate monolith application with scoped blueprint
         "before all" hook for "creates expected default files for server and angularX":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/blueprint/scoped-blueprint.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  5) jhipster:app composing
       when mocking jhipster:common,jhipster:languages,jhipster:entities,jhipster:entity,jhipster:database-changelog
         with default options
           "before all" hook for "should compose with common generator once":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/app/composing.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  6) jhipster:app composing
       when mocking jhipster:common,jhipster:languages,jhipster:entities,jhipster:entity,jhipster:database-changelog
         with default options
           "after all" hook for "should not compose with database-changelog generator":
     TypeError: Cannot read property 'cleanup' of undefined
      at Context.<anonymous> (test/app/composing.js:299:29)
      at processImmediate (internal/timers.js:461:21)

  7) JHipster generator
       Default configuration with
         AngularX
           "before all" hook for "creates expected default files for angularX":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/app-client-custom-path.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  8) JHipster entity generator with multiple blueprints
       generate entity with multiple blueprints option 'generator-jhipster-my-client-blueprint,generator-jhipster-my-server-blueprint'
         "before all" hook for "creates expected files from jhipster app generator":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/blueprint/multiple-blueprints.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  9) JHipster entity generator with multiple blueprints
       generate entity with multiple blueprints option 'my-client-blueprint,my-server-blueprint'
         "before all" hook for "creates expected files from jhipster app generator":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/blueprint/multiple-blueprints.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  10) JHipster application generator with blueprint
       generate application with a version-compatible blueprint
         "before all" hook for "creates expected default files for server and angularX":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/blueprint/app-blueprint.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  11) JHipster application generator with blueprint
       generate application with a peer version-compatible blueprint
         "before all" hook for "creates expected default files for server and angularX":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/blueprint/app-blueprint.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  12) JHipster generator
       Default configuration with
         Custom prettier
           "before all" hook for "writes custom .prettierrc":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/generator-transform.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  13) needle API React: JHipster client generator with blueprint
       Assert entity is added to module:

      AssertionError [ERR_ASSERTION]: src/main/webapp/app/entities/index.tsx did not match 'import entityName from './entityFolderName';'. Contained:

import React from "react";
import { Switch } from "react-router-dom";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import ErrorBoundaryRoute from "app/shared/error/error-boundary-route";

import entityName from "./entityFolderName";
/* jhipster-needle-add-route-import - JHipster will add routes here */

const Routes = ({ match }) => (
  <div>
    <Switch>
      {/* prettier-ignore */}
      <ErrorBoundaryRoute path={`${match.url}entityFileName`} component={entityName} />
      {/* jhipster-needle-add-route-path - JHipster will add routes here */}
    </Switch>
  </div>
);

export default Routes;

      + expected - actual

      -false
      +true

      at /Users/mraible/dev/generator-jhipster/node_modules/yeoman-assert/index.js:115:5
      at Array.forEach (<anonymous>)
      at Function.assert.fileContent (node_modules/yeoman-assert/index.js:102:26)
      at Context.<anonymous> (test/needle-api/needle-client-react.spec.js:102:12)
      at processImmediate (internal/timers.js:461:21)

  14) needle API Vue: JHipster client generator with blueprint
       menu contains the item in router:

      AssertionError [ERR_ASSERTION]: src/main/webapp/app/router/entities.ts did not match '  {
    path: '/entityFileName',
    name: 'entityName',
    component: entityName,
    meta: { authorities: [Authority.USER] },
  },
  {
    path: '/entityFileName/new',
    name: 'entityNameCreate',
    component: entityNameUpdate,
    meta: { authorities: [Authority.USER] },
  },
  {
    path: '/entityFileName/:entityInstanceId/edit',
    name: 'entityNameEdit',
    component: entityNameUpdate,
    meta: { authorities: [Authority.USER] },
  },
  {
    path: '/entityFileName/:entityInstanceId/view',
    name: 'entityNameView',
    component: entityNameDetails,
    meta: { authorities: [Authority.USER] },
  },
'. Contained:

import { Authority } from "@/shared/security/authority";
/* tslint:disable */
// prettier-ignore

// prettier-ignore
const entityName = () => import('@/entities/entityFolderName/entityFileName.vue');
// prettier-ignore
const entityNameUpdate = () => import('@/entities/entityFolderName/entityFileName-update.vue');
// prettier-ignore
const entityNameDetails = () => import('@/entities/entityFolderName/entityFileName-details.vue');
// jhipster-needle-add-entity-to-router-import - JHipster will import entities to the router here

export default [
  {
    path: "/entityFileName",
    name: "entityName",
    component: entityName,
    meta: { authorities: [Authority.USER] },
  },
  {
    path: "/entityFileName/new",
    name: "entityNameCreate",
    component: entityNameUpdate,
    meta: { authorities: [Authority.USER] },
  },
  {
    path: "/entityFileName/:entityInstanceId/edit",
    name: "entityNameEdit",
    component: entityNameUpdate,
    meta: { authorities: [Authority.USER] },
  },
  {
    path: "/entityFileName/:entityInstanceId/view",
    name: "entityNameView",
    component: entityNameDetails,
    meta: { authorities: [Authority.USER] },
  },
  // jhipster-needle-add-entity-to-router - JHipster will add entities to the router here
];

      + expected - actual

      -false
      +true

      at /Users/mraible/dev/generator-jhipster/node_modules/yeoman-assert/index.js:115:5
      at Array.forEach (<anonymous>)
      at Function.assert.fileContent (node_modules/yeoman-assert/index.js:102:26)
      at Context.<anonymous> (test/needle-api/needle-client-vue.spec.js:116:12)
      at processImmediate (internal/timers.js:461:21)

  15) needle API Vue: JHipster client generator with blueprint
       menu contains the item in service import:

      AssertionError [ERR_ASSERTION]: src/main/webapp/app/main.ts did not match 'import entityNameService from '@/entities/entityFolderName/entityFileName.service';'. Contained:

// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.common with an alias.
import Vue from "vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import App from "./app.vue";
import Vue2Filters from "vue2-filters";
import { ToastPlugin } from "bootstrap-vue";
import router from "./router";
import * as config from "./shared/config/config";
import * as bootstrapVueConfig from "./shared/config/config-bootstrap-vue";
import JhiItemCountComponent from "./shared/jhi-item-count.vue";
import JhiSortIndicatorComponent from "./shared/sort/jhi-sort-indicator.vue";
import InfiniteLoading from "vue-infinite-loading";
import HealthService from "./admin/health/health.service";
import MetricsService from "./admin/metrics/metrics.service";
import LogsService from "./admin/logs/logs.service";
import ConfigurationService from "@/admin/configuration/configuration.service";
import ActivateService from "./account/activate/activate.service";
import RegisterService from "./account/register/register.service";
import UserManagementService from "@/admin/user-management/user-management.service";
import LoginService from "./account/login.service";
import AccountService from "./account/account.service";

import "../content/scss/vendor.scss";

import UserOAuth2Service from "@/entities/user/user.oauth2.service";
/* tslint:disable */

import entityNameService from "@/entities/entityFolderName/entityFileName.service";
// jhipster-needle-add-entity-service-to-main-import - JHipster will import entities services here

/* tslint:enable */
Vue.config.productionTip = false;
config.initVueApp(Vue);
config.initFortAwesome(Vue);
bootstrapVueConfig.initBootstrapVue(Vue);
Vue.use(Vue2Filters);
Vue.use(ToastPlugin);
Vue.component("font-awesome-icon", FontAwesomeIcon);
Vue.component("jhi-item-count", JhiItemCountComponent);
Vue.component("jhi-sort-indicator", JhiSortIndicatorComponent);
Vue.component("infinite-loading", InfiniteLoading);
const store = config.initVueXStore(Vue);

const loginService = new LoginService();
const accountService = new AccountService(store, router);

router.beforeEach((to, from, next) => {
  if (!to.matched.length) {
    next("/not-found");
  }

  if (to.meta && to.meta.authorities && to.meta.authorities.length > 0) {
    accountService
      .hasAnyAuthorityAndCheckAuth(to.meta.authorities)
      .then((value) => {
        if (!value) {
          sessionStorage.setItem("requested-url", to.fullPath);
          next("/forbidden");
        } else {
          next();
        }
      });
  } else {
    // no authorities, so just proceed
    next();
  }
});

/* tslint:disable */
new Vue({
  el: "#app",
  components: { App },
  template: "<App/>",
  router,
  provide: {
    loginService: () => loginService,
    activateService: () => new ActivateService(),
    registerService: () => new RegisterService(),
    userService: () => new UserManagementService(),
    healthService: () => new HealthService(),
    configurationService: () => new ConfigurationService(),
    logsService: () => new LogsService(),
    metricsService: () => new MetricsService(),

    userOAuth2Service: () => new UserOAuth2Service(),
    entityInstanceService: () => new entityNameService(),
    // jhipster-needle-add-entity-service-to-main - JHipster will import entities services here
    accountService: () => accountService,
  },
  store,
});

      + expected - actual

      -false
      +true

      at /Users/mraible/dev/generator-jhipster/node_modules/yeoman-assert/index.js:115:5
      at Array.forEach (<anonymous>)
      at Function.assert.fileContent (node_modules/yeoman-assert/index.js:102:26)
      at Context.<anonymous> (test/needle-api/needle-client-vue.spec.js:146:12)
      at processImmediate (internal/timers.js:461:21)

  16) jhipster program
       generates an application
         should succeed:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/cli/jdl-fork.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  17) jhipster program
       generates entities
         should succeed:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/cli/jdl-fork.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  18) Vue applications
       Default with Maven
         "before all" hook for "creates expected files from jhipster Vue generator":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mraible/dev/generator-jhipster/test/vue.spec.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)



npm ERR! Test failed.  See above for more details.
```

**Comment by dieppa** [comment]
@mraible hello. The error you're facing is not related to that bug. Basically Mongock is encouraging strong consistency by setting by default: writeconcern: majority, journal true, readconcern: majority and readPreferenceL primary.

Although we released without documenting it yet because if a client need(mistake), you can change the configuration with this(the following are the default values):

```yaml
mongock:
  mongo-db:
    write-concern:
      w: majority
      journal: true
    read-concern: majority
    read-preference: primary
```

**Comment by mraible** [comment]
@dieppa We upgraded Mongock from 4.2.8.BETA to 4.3.4 in [this PR](https://github.com/jhipster/jhipster-bom/pull/188/files#diff-404c8e6431f02abfa400f23d22e8719c41592d7e926100798a8aa7e95c482a02R60). 

Do we need this upgrade for Spring Boot 2.4.3? If not, maybe we should revert to 4.2.8.BETA.

**Comment by dieppa** [comment]
@mraible no, We couldn't reproduce that bug, not sure if it was something the user was doing wrong. Anyway, we adopted a more conservative and safer approach and that was resolve even for him. 

We are realising the version 4.3.6 with that and some other minor bug fixes, that should be fine.

**Comment by mraible** [comment]
I [reverted from Mongock 4.3.4 to 4.2.8.BETA](https://github.com/jhipster/jhipster-bom/pull/188/commits/cf76bd5bc98c3c6f1502b55e1cd27e1f849a2290) and tests pass locally. Closing and re-opening this PR to see if tests pass.

**Comment by mraible** [comment]
I tried upgrading `jhipster-bom` to use Infinispan v12, but the error is the same.

```diff
diff --git a/jhipster-dependencies/pom.xml b/jhipster-dependencies/pom.xml
index 97941a1..950606c 100644
--- a/jhipster-dependencies/pom.xml
+++ b/jhipster-dependencies/pom.xml
@@ -50,8 +50,7 @@
         <de.flapdoodle.embed.mongo.version>2.2.0</de.flapdoodle.embed.mongo.version>
         <hazelcast.version>4.1.1</hazelcast.version>
         <hazelcast-hibernate5.version>2.2.0</hazelcast-hibernate5.version>
-        <infinispan.version>11.0.9.Final</infinispan.version>
-        <infinispan-spring-boot-starter-embedded.version>2.3.6.Final</infinispan-spring-boot-starter-embedded.version>
+        <infinispan.version>12.0.1.Final</infinispan.version>
         <jjwt.version>0.11.2</jjwt.version>
         <liquibase-mssql.version>1.6.4</liquibase-mssql.version>
         <logstash-logback-encoder.version>6.6</logstash-logback-encoder.version>
@@ -160,7 +159,7 @@
             <dependency>
                 <groupId>org.infinispan</groupId>
                 <artifactId>infinispan-spring-boot-starter-embedded</artifactId>
-                <version>${infinispan-spring-boot-starter-embedded.version}</version>
+                <version>${infinispan.version}</version>
             </dependency>
             <dependency>
                 <groupId>io.jsonwebtoken</groupId>
@@ -729,6 +728,14 @@
                 <type>pom</type>
                 <scope>import</scope>
             </dependency>
+
+            <dependency>
+                <groupId>org.infinispan</groupId>
+                <artifactId>infinispan-bom</artifactId>
+                <version>${infinispan.version}</version>
+                <type>pom</type>
+                <scope>import</scope>
+            </dependency>
         </dependencies>
     </dependencyManagement>
```

Do we have an Infinispan expert among @jhipster/developers?

**Comment by pascalgrimaud** [comment]
Yes, I think it's @ecostanzi :)

**Comment by ecostanzi** [comment]
I'll take a look this evening

**Comment by ecostanzi** [comment]
I created 2 PRs, one for the generator and one to upgrade the infinispan version in the bom to version 12. Let's see if tests pass. Feel free to close https://github.com/jhipster/jhipster-bom/pull/201 if you prefer to go with https://github.com/jhipster/jhipster-bom/pull/188

**Comment by mraible** [comment]
Restarted to see if Infinispan builds pass.

**Comment by mraible** [comment]
This seems like it's good to go! I'll see if https://github.com/jhipster/jhipster-bom/pull/188#issuecomment-791183783 passes first.

**Comment by dieppa** [comment]
Hello, We are realising Mongock 4.3.7 today(within a couple of hours) with some bug fixes.

My suggestion is to wait for version 4.3.7 and add the following properties when running on in-memory databases, like flapdoodle

```yaml
mongock:
  mongo-db:
    write-concern:
      journal: false
```

**Comment by mraible** [comment]
I'm standing by, waiting for your release. 😉

**Comment by dieppa** [comment]
Mongock version 4.3.7 is released 👍 , please give a try

**Comment by mraible** [comment]
@dieppa In progress... Thanks!

**Comment by dieppa** [comment]
@mraible , I see the pipeline failing with the following error:
```java
Caused by: com.github.cloudyrock.mongock.exception.MongockException: com.mongodb.MongoQueryException: Query
failed with error code 148 and error message 'Majority read concern requested, but server was not started with 
-enableMajorityReadConcern.' on server localhost:44169
```

To fix this, you can enable the majority read concern in the MongoDB, as suggested with `--enableMajorityReadConcern`.
Or you can change the read concern level in Mongock property `mongock.mongo-db.read-concern`, 
The possible values are the ones provided by MongoDB ReadConcernLevel: `majority`, local`,`available`, `linearizable and `snapshot`

I believe the following should be fine for testing.
```yaml
mongock:
  mongo-db:
    read-concern: local
```

**Comment by pascalgrimaud** [comment]
@DanielFran : approved

If other people participated to this big upgrade, just ping me and I can add more bounty on this, so it can be shared
I think it's fair :-)

**Pull request merged**
