### PR TITLE
Add table/column description into liquibase remarks tag

### PR DESCRIPTION
**Pull request by DanielFran**
If description is defined for Entity and/or Field(s), it will be added to Table and/or Column(s) description in liquibase remarks tag in entity changelog.

- Please make sure the below checklist is followed for Pull Requests.

- [X] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X] Tests are added where necessary
- [X] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
What is the use of the description field?

**Comment by DanielFran** [comment]
Usefull to document database. Not all database have field name that describe correctly what data is (particularly existing database)

**Comment by gmarziou** [comment]
Have you tested special chars like accents and `<>` ? Because I saw you re-used a function that is used for javadocs and there could be differences with Liquibase due to XML changesets and due to database char encoding.

**Comment by DanielFran** [comment]
@gmarziou, no I did not tested with all special characters bit usually it works with accents in PostgreSQL.

**Comment by jdubois** [comment]
Sorry but it fails if you have a `"` character in the comment.
Please note the function is broken, that also makes the `@ApiModel` annotation fail in the generated Java entity (it's not compiling).

If you want to test, here is a JDL that breaks stuff:

```
/**
 * Class"   c(o'mmen<ts>.
 * dqds!dqdqs#dsq
 * @author The JHipster team.
 */
entity MyEntity { // another form of comment
  /** A required attribute */
  myField String required,
  mySecondField String // another form of comment
}
```

**Comment by DanielFran** [comment]
@jdubois The " should already be escaped!?!

Locking at the code I see:

    /**
     * Format As Api Description
     *
     * @param {string} text - text to format
     * @returns formatted api description
     */
    formatAsApiDescription(text) {
        if (!text) {
            return text;
        }
        const rows = text.split('\n');
        let description = rows[0];
        for (let i = 1; i < rows.length; i++) {
            // discard empty rows
            if (rows[i].trim() !== '') {
                // if simple text then put space between row strings
                if (!description.endsWith('>') && !rows[i].startsWith('<')) {
                    description += ' ';
                }
                description += this.formatLineForJavaStringUse(rows[i]);
            }
        }
        return description;
    }

    formatLineForJavaStringUse(text) {
        if (!text) {
            return text;
        }
        **return text.replace(/"/g, '\\"');**
    }

**Comment by DanielFran** [comment]
@jdubois I have fixed API description and also escaped 5 xml characters (&, ", ', <, >) for liquibase remarks!

Tested even with liquibase dbdoc that documentation include correctly the descriptions from database.

**Comment by DanielFran** [comment]
Just for information, I manage to create documentation based on changelog for database using liquibase maven plugin:
`            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>${liquibase.version}</version>
                <configuration>
                    ...
                </configuration>
                <dependencies>
                    ...
                </dependencies>
                <executions>
                    <execution>
                        <id>update</id>
                        <phase>process-test-resources</phase>
                        <configuration>
                            <propertyFile>src/test/resources/config/application.yml</propertyFile>
                            <logging>info</logging>
                        </configuration>
                        <goals>
                            <goal>update</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>dbDoc</id>
                        <phase>test</phase>
                        <configuration>
                            <propertyFile>src/test/resources/config/application.yml</propertyFile>
                            <outputDirectory>${project.basedir}/target/site/database/</outputDirectory>
                            <logging>info</logging>
                        </configuration>
                        <goals>
                            <goal>dbDoc</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>dropAll</id>
                        <phase>test</phase>
                        <configuration>
                            <propertyFile>src/test/resources/config/application.yml</propertyFile>
                            <logging>info</logging>
                        </configuration>
                        <goals>
                            <goal>dropAll</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
`
Do not know if it migth be usefull as a tip?

**Comment by gmarziou** [comment]
I did not know it existed, can you share something to see how this doc looks like?

**Comment by gmarziou** [comment]
The example was generated 11 years ago :) I was expecting a graph but it's better than nothing.

**Comment by DanielFran** [comment]
@gmarziou Looking forward for SchemaCrawler and his maven report plugin, but did found only this example: http://mvn-schemacrwlr.sourceforge.net/schemacrawler-maven-plugin/1.0/usage.html

Will investigate more next week....

It looks like it (quite good): https://www.schemacrawler.com/snapshot-examples/snapshot.svg.html

**Comment by gmarziou** [comment]
No suggestion to offer, this one is pretty impressive :sunglasses:

**Comment by DanielFran** [comment]
@jdubois Are you waiting anything else from me to pursuive with the merge or it is just that you did not have time to review it?
Waiting for your review.... Thanks.

**Comment by DanielFran** [comment]
@gmarziou after some investigation I did not found how to use the report plugin from @schemacrawler!
For now I believe that only using the shell script...

During my investigation I have found this project: https://github.com/vindell/spring-boot-starter-schemacrawler

Might be usefull, I do not know...

**Comment by jdubois** [comment]
Sorry I'm still on holidays - if @ruddell says it's good let's merge it

**Comment by DanielFran** [comment]
@ruddell @jdubois Thanks.

And sorry to interrompt your holidays.

**Comment by DanielFran** [comment]
@gmarziou Seems that we have now the schemascrawler plugin updated and report example here: https://github.com/schemacrawler/SchemaCrawler-Report-Maven-Plugin-Usage-Example

I will test it during the day...

**Pull request merged**
