### PR TITLE
Update spring-boot version to 2.6.5

### PR DESCRIPTION
**Pull request by DanielFran**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
Seems that gradle plugin is fixed.

**Comment by mraible** [comment]
@DanielFran Do you know why this upgrade fails?

**Comment by DanielFran** [comment]
I identified several issues so far:
- MongoDB is broken, the workaround done by @mshima in previous version do not work anymore
- Couchbase also did not work, maybe @tchlyah can help on this
- Issues with UserService with webflux, after the upgrade it did not return users

**Comment by mraible** [comment]
There seems to be a commonality among failing tests:

```
PublicUserResourceIT > getAllPublicUsers() FAILED
    java.lang.NullPointerException at PublicUserResourceIT.java:72
```

```
Error:    PublicUserResourceIT.getAllPublicUsers:65 NullPointer
```

**Comment by mraible** [comment]
Should we try to upgrade to [Spring Boot 2.6.5](https://spring.io/blog/2022/03/24/spring-boot-2-6-5-available-now) instead?

**Comment by DanielFran** [comment]
@mraible I will update it, just waiting that it is available in maven repo

**Comment by DanielFran** [comment]
@mraible @mshima Everything is green!?!

Will deploy BOM and update repos...

**Review by mraible — APPROVED** [review]

**Comment by DanielFran** [comment]
@mshima I propose to divide the bug bounty 50/50
Is it OK for you?

**Comment by mshima** [comment]
@DanielFran sorry the delay. You take 350, I take 150.
You did more here.

**Comment by pascalgrimaud** [comment]
No @mshima
Take each one 500 plz, you did so much for the project, it's deserved

**Comment by DanielFran** [comment]
@pascalgrimaud Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/69653

**Comment by pascalgrimaud** [comment]
@DanielFran : approved

**Comment by pascalgrimaud** [comment]
@mshima : approved :)

**Pull request merged**
