### PR TITLE
JHipster lib 3.0.3

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Just to check if the JHipster 3.0.3 is compatible with current master branch

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
If the CI passed, I think we can merge this, so a new release can be done !

**Comment by DanielFran** [comment]
@pascalgrimaud the new version should be 3.0.4, version 3.0.3 already exists in maven central

**Comment by DanielFran** [comment]
And what about Redis Cache, the PR is waiting confirmation in https://github.com/jhipster/generator-jhipster/pull/10057

**Comment by pascalgrimaud** [comment]
@DanielFran : yes thanks I know :-) as I didn't do a new release, I'm trying to check if the 3.0.3 is comptatible with current master

If yes: we can do a new release of the generator
If not, we need to wait or I need to find time to config my computer to do a release of JHipster lib

**Pull request merged**
