### PR TITLE
Add docker dependency and health checks

### PR DESCRIPTION
**Pull request by mshima**
Closes https://github.com/jhipster/generator-jhipster/issues/19811.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
This had become quite big PR.
- adds 2 more arguments for tasks: control and source.
  - control in available in every priority and should be used for common runtime options like `existingProject`, `skipChecks`.
  - source is available at `preparing` for injection and `postWriting` for use. Will be used for content insertion like needles. as example docker generator injects and use 2 insertion apis.
- modularize docker generator. Some blueprints like quarkus uses docker files from generator-jhipster, this will make easier for those blueprints to use our docker files.
probably makes sense to move non core docker files to others generators, like zipkin, sonar.
- replaces `docker compose up -d` with `docker compose up --wait`. `--wait` waits for healthy status at every container if available and implies `-d`.
- drop `wait-on` scripts now that we are using `--wait`. we still have `wait-on` at application scripts that don't uses docker.

**Comment by DanielFran** [comment]
@mshima Can you resolve the conflicts?

**Comment by mshima** [comment]
This PR never gets finished =\
@DanielFran all green but 4 attempts to make ms-cassandra to succeed is not good.
 I’ll need to try others changes.

**Comment by DanielFran** [comment]
@mshima Is this ready to review?

**Comment by mshima** [comment]
@DanielFran yes, I just want to squash.

**Review by DanielFran — CHANGES_REQUESTED** [review]

**Review by DanielFran — APPROVED** [review]

**Comment by mshima** [comment]
Microservice + cassandra still flacky at the gateway, which uses postgresql.
I suppose there is a bug at react, not at this PR.
So moving on.

**Comment by mshima** [comment]
I won’t manage to squash into 2 our 3 commits like I wanted. Squashing using GitHub.

**Pull request merged**
