### PR TITLE
remove duplicated java source and target in pom

### LINKED ISSUE #10279: Choose between properties and plugin configuration for maven-compiler-plugin
##### **Overview of the feature request**
According to https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html we could configure maven-compiler-plugin by 2 ways:

* By setting properties:
 ```
<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
```

* By setting the configuration plugin itself:
```
     <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
```

In JHipster we have both solutions implemented. We could remove one of them.

IMHO I would remove the configuration in plugin declaration and only keep properties since they are easy to read and close to our `java.version` property.

/discuss
##### **Motivation for or Use Case**
Simplify the pom.xml.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by fdelbrayelle**
Fix #10279

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
Closed/Reopened to see if https://github.com/jhipster/generator-jhipster/pull/10327/commits/31f592418343ad26ca560de6c2912fb3bcc78d8f fix the issue

**Comment by DanielFran** [comment]
Well seems that it is a bad idea to remove those configuration, javadoc fails with java 11

**Comment by fdelbrayelle** [comment]
Yes it seems the maven javadoc is setted with Java 8 in the generated pom.xml. According to the logs it seems to be linked.

**Comment by DanielFran** [comment]
Yes please.

**Pull request closed without merging**
