### PR TITLE
Ng2 protractor upgrade

### PR DESCRIPTION
**Pull request by mohamed2a**
Upgrade to Protractor 4 to make it compatible with Angular 2

### CODE REVIEW

**Comment by deepu105** [comment]
does protractor work or is this a work in progress?

**Comment by mraible** [comment]
@deepu105 I tested it locally, and it doesn't work for me. FWIW, I spent several hours trying to get Protractor to work on the `angular-2` branch and failed. My current guess is that it doesn't work because we have a hybrid app. I have several projects that work fine with Angular 1 and Angular 2, but none are hybrid.

**Comment by deepu105** [comment]
In that case we can upgrade protractor after ng1 dependencies are removed
untill that we can supress the option for ng2

Thanks & regards,
Deepu

**Comment by mohamed2a** [comment]
The work is still in progress, I need to rewrite Angular modules inside the `onPrepare` function in the config file.

**Comment by mraible** [comment]
FWIW, there's compile errors when generating with the default settings:

```
src/main/webapp/app/app.ng2module.ts(70,22): error TS2304: Cannot find name 'Http'.
src/main/webapp/app/app.ng2module.ts(72,26): error TS2304: Cannot find name 'XHRBackend'.
src/main/webapp/app/app.ng2module.ts(73,33): error TS2304: Cannot find name 'RequestOptions'.
src/main/webapp/app/app.ng2module.ts(79,86): error TS2304: Cannot find name 'stateStorageService'.
src/main/webapp/app/app.ng2module.ts(84,17): error TS2304: Cannot find name 'XHRBackend'.
src/main/webapp/app/app.ng2module.ts(85,17): error TS2304: Cannot find name 'RequestOptions'.
src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts(5,34): error TS2307: Cannot find module '../../shared/auth/auth-jwt.service'.
```

@mohamed2a Do you need to re-sync your branch with the `angular-2` branch?

**Comment by mohamed2a** [comment]
My branch is already synced @mraible 
capture

**Comment by mraible** [comment]
OK, I’ll look into fixing these on the main angular-2 branch.

**Comment by deepu105** [comment]
Matt I have fixed it in the ng2-webpack branch. May be ill cherrypick those
into angular2 branch today

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
please rebase to current angular2 branch, you can remove gulp related stuff and instead add a command to run it from npm

**Comment by deepu105** [comment]
@mohamed2a this PR commit history seems very polluted. can you checkout a new branch from latest angular2 and apply your changes there. It hard for me to review this

**Comment by mohamed2a** [comment]
I did it @deepu105
Best regards

**Comment by mohamed2a** [comment]
I fixed Protractor, now it works. @jdubois 

image

**Comment by mraible** [comment]
@mohamed2a There seems to be many changes in your branch that aren't in the angular-2 branch. Can you rebase with the origin branch? I tried to run your branch and it fails to compile.

```
[INFO] --- frontend-maven-plugin:1.0:webpack (webpack build) @ pro ---
[INFO] Running 'webpack.js --config webpack/webpack.dev.js' in /Users/mraible/pro
[INFO] Hash: 4f9a127f71e2524f8f75
[INFO] Version: webpack 2.1.0-beta.25
[INFO] Time: 578ms
[INFO]     + 3 hidden modules
[INFO]
[INFO] ERROR in ./src/main/webapp/app/polyfills.ts
[INFO] Module build failed: Error:
[INFO]             Could not find implementations for the following rules specified in the configuration:
[INFO]             max-classes-per-file
[INFO]             Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
[INFO]             If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
[INFO]
[INFO]     at Object.loadRules (/Users/mraible/pro/node_modules/tslint/lib/ruleLoader.js:29:15)
[INFO]     at Linter.lint (/Users/mraible/pro/node_modules/tslint/lib/tslint.js:59:44)
[INFO]     at Object.lint (/Users/mraible/pro/node_modules/tslint-loader/index.js:41:23)
[INFO]     at Object.module.exports (/Users/mraible/pro/node_modules/tslint-loader/index.js:103:8)
[INFO]
[INFO] ERROR in ./src/main/webapp/app/vendor.ts
[INFO] Module build failed: Error:
[INFO]             Could not find implementations for the following rules specified in the configuration:
[INFO]             max-classes-per-file
[INFO]             Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
[INFO]             If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
[INFO]
[INFO]     at Object.loadRules (/Users/mraible/pro/node_modules/tslint/lib/ruleLoader.js:29:15)
[INFO]     at Linter.lint (/Users/mraible/pro/node_modules/tslint/lib/tslint.js:59:44)
[INFO]     at Object.lint (/Users/mraible/pro/node_modules/tslint-loader/index.js:41:23)
[INFO]     at Object.module.exports (/Users/mraible/pro/node_modules/tslint-loader/index.js:103:8)
[INFO]
[INFO] ERROR in ./src/main/webapp/app/app.main.ts
[INFO] Module build failed: Error:
[INFO]             Could not find implementations for the following rules specified in the configuration:
[INFO]             max-classes-per-file
[INFO]             Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
[INFO]             If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
[INFO]
[INFO]     at Object.loadRules (/Users/mraible/pro/node_modules/tslint/lib/ruleLoader.js:29:15)
[INFO]     at Linter.lint (/Users/mraible/pro/node_modules/tslint/lib/tslint.js:59:44)
[INFO]     at Object.lint (/Users/mraible/pro/node_modules/tslint-loader/index.js:41:23)
[INFO]     at Object.module.exports (/Users/mraible/pro/node_modules/tslint-loader/index.js:103:8)
[INFO] Child html-webpack-plugin for "index.html":
[INFO]         + 21 hidden modules
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.663 s
[INFO] Finished at: 2016-12-07T08:58:33-05:00
[INFO] Final Memory: 47M/431M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:webpack (webpack build) on project pro: Failed to run task: 'webpack.js --config webpack/webpack.dev.js' failed. (error code 2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by deepu105** [comment]
@mohamed2a I cannot review or merge this as there are too many unwanted commits from base branch. can you please either rebase or cleanup so that it has only your commits?

**Comment by mohamed2a** [comment]
It's done. @deepu105 @mraible

**Comment by deepu105** [comment]
@mohamed2a what do you mean by its done? it still shows 122 commits and 196 file changes. Its impossible for me to review this. can you please close this PR and open a clean PR with only your commits related to this change?

few things you could try.

1. Try to do `git rebase -i master` fix conflicts if any and force push to this branch (check contributing.md file on root for more details)
2. If it doesnt work try to checkout a new branch from current angular-2 branch and then cherry pick your commits to that branch and create PR from that

**Pull request closed without merging**
