### PR TITLE
fix to #3581 invalid message for used emails

### PR DESCRIPTION
**Pull request by sendilkumarn**
#3581

### CODE REVIEW

**Comment by sendilkumarn** [comment]
is there any error with cassandra testing?

**Comment by jdubois** [comment]
@sendilkumarn this is probably some Travis issue, your commit shouldn't make the integration server fail

**Comment by sendilkumarn** [comment]
@jdubois 👍

**Comment by deepu105** [comment]
@sendilkumarn is the proper error message shown for both enableTranslation true and false?

**Comment by sendilkumarn** [comment]
screen shot 2016-05-17 at 5 07 25 pm

**Pull request merged**
