### PR TITLE
Update liquibase version to 4.15.0

### PR DESCRIPTION
**Pull request by DanielFran**
Fix https://github.com/jhipster/generator-jhipster/issues/17529
---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@mshima With liquibase 4.14.0, autoincrement have been fixed for mysql/mariadb/h2 (see [here](https://github.com/liquibase/liquibase/pull/3026))
Do not remember if we should make any changes here:
https://github.com/jhipster/generator-jhipster/blob/d048756de18718433196c78c7703c4f37cfdeafd/utils/field.js#L282-L298

**Comment by mshima** [comment]
> @mshima With liquibase 4.14.0, autoincrement have been fixed for mysql/mariadb/h2 (see [here](https://github.com/liquibase/liquibase/pull/3026)) Do not remember if we should make any changes here:
> 
> https://github.com/jhipster/generator-jhipster/blob/d048756de18718433196c78c7703c4f37cfdeafd/utils/field.js#L282-L298

Not needed.

**Comment by mshima** [comment]
Try updating h2-r2dbc

**Comment by mshima** [comment]
Maybe we should try to update h2 only at imperative

**Comment by mraible** [comment]
Can y'all please fix the conflicts in this PR?

**Comment by mshima** [comment]
@DanielFran tests succeeded.

**Pull request merged**
