### PR TITLE
enable neo4j+gateway at test sample.

### PR DESCRIPTION
**Pull request by mshima**
Fixes https://github.com/jhipster/generator-jhipster/issues/18744.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
Needs rebase.

**Comment by mraible** [comment]
@mshima Needs another rebase.

**Comment by mraible** [comment]
@mshima Since tests are still failing, does this mean that Spring Cloud Gateway and Neo4j don't work well together?

**Comment by mshima** [comment]
Maybe related to neo4j with reactive been broken for a while at daily builds https://github.com/hipster-labs/jhipster-daily-builds/actions/workflows/neo4j.yaml.
I think the error should be easy.

Or we should just close this PR.

**Comment by atomfrede** [comment]
Don't close it. I will have a look at the webflux part. It indeed looks like an error which should be easy to find I hope.

**Review by DanielFran — APPROVED** [review]

**Pull request merged**
