### PR TITLE
Fakerjs 8 deprecated method

### PR DESCRIPTION
**Pull request by qmonmert**
https://fakerjs.dev/api/random.html#random is deprecated
Replaced by https://fakerjs.dev/api/lorem.html#lorem 

https://v7.fakerjs.dev/api/name.html
Replaced by https://fakerjs.dev/api/person.html

### CODE REVIEW

**Comment by qmonmert** [comment]
@mshima do you think that `ng-gradle-fr` build failed is a false positive?

**Comment by mshima** [comment]
> @mshima do you think that `ng-gradle-fr` build failed is a false positive?

Faker seems to generate an incompatible character. Should check if input is correctly handling the sample, if it’s correct, should replace the offending char.

**Comment by mshima** [comment]
ng-default still have deprecations:
```
[@faker-js/faker]: faker.name is deprecated since v8.0 and will be removed in v10.0. Please use faker.person instead.
```

**Comment by qmonmert** [comment]
@mshima I updated `faker.person`, but how do you see `stringRequiredMika: "ah à l'insu de",` ?

**Comment by mshima** [comment]
At PR generated source diff:
IMG_0417

There is an strange value here:
IMG_0418

**Comment by qmonmert** [comment]
@mshima ah thanks, I've never seen that 🙂
the character `&#39;` is apostrophe and examples are valid in french language
when you say `Should check if input is correctly handling the sample, if it’s correct, should replace the offending char.` what do you mean?

**Comment by mshima** [comment]
> @mshima ah thanks, I've never seen that 🙂
> the character `&#39;` is apostrophe and examples are valid in french language
> when you say `Should check if input is correctly handling the sample, if it’s correct, should replace the offending char.` what do you mean?

Cypress or angular implementation is not accepting the generated sample.
Last commit should not convert apostrophe into html escaped char.
I think it will fix the problem.

**Comment by qmonmert** [comment]
@DanielFran https://opencollective.com/generator-jhipster/expenses/151629 🙂
@mshima thanks for the help 🙂

**Comment by DanielFran** [comment]
@qmonmert approved

**Pull request merged**
