### PR TITLE
Changing controllers

### PR DESCRIPTION
**Pull request by sendilkumarn**
@deepu105 @wmarques 

Can we change the name to components after we finish everything?

### CODE REVIEW

**Comment by deepu105** [comment]
yes we can

**Comment by sendilkumarn** [comment]
I will convert by today... 😃

**Comment by deepu105** [comment]
do you want me to merge this or do you want to add more commits?

**Comment by sendilkumarn** [comment]
You can merge if it is okay. 👍

**Comment by wmarques** [comment]
Seems fine to me, good job :+1:

**Comment by sendilkumarn** [comment]
@deepu105 i think you can merge this.

**Pull request merged**
