### PR TITLE
bump mysql from 8.2.0 to 8.3.0

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #24919 

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by qmonmert** [comment]
@DanielFran @mshima it seems that with `1.19.4` version of `org.testcontainers:mysql` it works, but I think that applying the version directly in files (like in this PR) is not the good way... WDYT?

**Comment by DanielFran** [comment]
@qmonmert we have already defined same version in BOM project, this is strange that it is needed to overwrite here too...

**Comment by qmonmert** [comment]
@DanielFran on JHLite it was related https://github.com/jhipster/jhipster-lite/commit/f0c16c3e68f6b7b97bda2a87920b837492e0af7d

**Comment by qmonmert** [comment]
@DanielFran without specify the version #25008  ❌

**Comment by mshima** [comment]
I think this is a bug at jhipster-bom, it's not overriding correctly the testcontainer-bom.
Maybe because jhipster-bom uses spring-boot-dependencies as parent.

**Comment by DanielFran** [comment]
> I think this is a bug at jhipster-bom, it's not overriding correctly the testcontainer-bom. Maybe because jhipster-bom uses spring-boot-dependencies as parent.

In the past, defining the spring-boot bom then any other after that allow to overwrite the any spring-boot dependency.
Starting on some specific maven version the behaviour change and we try to fix it with https://github.com/jhipster/jhipster-bom/pull/1457
Maybe it needs more investigation

**Comment by mraible** [comment]
It looks like all tests are passing now.

**Comment by DanielFran** [comment]
Superseded by https://github.com/jhipster/generator-jhipster/pull/24919

**Pull request closed without merging**
