### PR TITLE
Update infinispan

### LINKED ISSUE #10691: Update Infinispan to 10.1.0.Final
https://infinispan.org/docs/dev/index.html

https://infinispan.org/blog/2019/10/28/infinispan-10-final/

https://infinispan.org/blog/2019/12/23/infinispan-10/

https://infinispan.org/release-notes/

https://infinispan.org/docs/stable/titles/upgrading/upgrading.html#upgrading

### PR DESCRIPTION
**Pull request by ecostanzi**
Fixes #10691. Depends on https://github.com/jhipster/jhipster/pull/619.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by ecostanzi** [comment]
There's just one thing I'm not sure of. I'm expecting tests to fail because the generator still depends on jhipster-dependencies 3.6.0, while the related PR jhipster/jhipster#619 updates jhipster-dependencies 3.7.0-SNAPSHOT. How should I behave in this case?

**Comment by murdos** [comment]
@ecostanzi : you can change the jhipster-dependencies repository and/or branch used for integration tests: https://github.com/jhipster/generator-jhipster/blob/master/.github/workflows/angular.yml#L26
You need to make the change for react GitHub actions pipeline too, and for azure-pipelines.

**Comment by pascalgrimaud** [comment]
I merged the other PR and restart this one, let's see

**Comment by murdos** [comment]
> I merged the other PR and restart this one, let's see

Since master of generator-jhipster is configured to use the released version of jhipster-dependencies rather than master, it won't work ;)

**Comment by pascalgrimaud** [comment]
oh right ! then I can't modify it as I'm on phone right now

**Comment by ecostanzi** [comment]
I'm not sure I understood... should I update jhipster-dependencies in the master branch via PR or change the pipeline JHI_LIB_BRANCH configuration?

**Comment by ecostanzi** [comment]
Created #11479 to update master branch

**Comment by pascalgrimaud** [comment]
Since this PR, Infinispan daily builds failed:
- https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=31&_a=summary
- here an extract of logs with Gradle:

```
warning: unknown enum constant Scopes.GLOBAL
/home/vsts/app/store/src/main/java/com/jhipster/demo/store/config/CacheConfiguration.java:238: error: method setInitialHosts in class TCPPING cannot be applied to given types;
            tcpping.setInitialHosts(initialHosts);
                   ^
  required: Collection<InetSocketAddress>
  found: List<PhysicalAddress>
  reason: cannot infer type-variable(s) T
    (argument mismatch; List<PhysicalAddress> cannot be converted to Collection<InetSocketAddress>)
  where T is a type-variable:
    T extends TCPPING declared in method <T>setInitialHosts(Collection<InetSocketAddress>)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
10 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
```

Can you have a look plz @ecostanzi ?

**Comment by ecostanzi** [comment]
Sure I'll take a look asap

**Pull request merged**
