### PR TITLE
Generate separate service class with a couple of known limitations 

### PR DESCRIPTION
**Pull request by gzsombor**
(Issue #1823)

 - only works, when DTO generation is used
 - with cassandra is broken, because there is no 'repository.findAll(page)' method
 - the filtering for null one-to-one relations is not implemented
    (which should happen in the repository/db side, not in the java side)

### CODE REVIEW

**Comment by atomfrede** [comment]
Splitting into two templates is great.

**Comment by jdubois** [comment]
Can we wait a little bit before merging? There's already so much to test right now, I don't know when I will finish testing everything...
If it doesn't work with Cassandra, this isn't an issue -> just remove the feature when Cassandra is selected. Only very few people use Cassandra, so let's not get stuck or lose time for such a few user base.

**Comment by deepu105** [comment]
Hey guys, hold on I might have found a simpler way to do this without new templates and without  some of the limitations, let me try that out will post results if it works

**Comment by deepu105** [comment]
@gzsombor I have tried to merge my changes with your PR but there was lot of conflicts and most of the code was different hence i created a new PR, hope you dont mind. can you plz take a look?

**Comment by gzsombor** [comment]
Nice twist with that includes, I like it ! I didn't know that it is possible to include stuff

We can close this PR

**Comment by deepu105** [comment]
Yup ejs should document those better, its a killer feature but very less
documented

**Pull request closed without merging**
