### PR TITLE
5604 using getter in equals() and hashcode() methods

### PR DESCRIPTION
**Pull request by Tcharl**
#5604 - Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
@Tcharl something went wrong. You should create a branch before making a PR.

**Comment by Tcharl** [comment]
There's no merge conflict anymore, I rebased the master.

But there are some failing ci tests: the websocket one (timeout), the eureka and consul one (missing import, or unaffected property if I fix it): I don't think that these errors are from my part, is it normal?

 Regards,

**Comment by jdubois** [comment]
The cache issue is my fault, I did a quick fix, I hope it's OK -> if the main build is green, can you rebase your PR? I'm sorry about this, I don't have enough time to do this as good as I would like to

**Comment by Tcharl** [comment]
Thank you, I did not notice! Shitty Mac, and long live to continuous improvement!

**Comment by ruddell** [comment]
`_CacheConfiguration.java` should be untouched by this PR, I think you rebased the wrong section in?

**Comment by Tcharl** [comment]
Sorry, I fixed a missing import for some tests (Eureka and Consul ones), should I remove that modification?

**Comment by jdubois** [comment]
Yes @Tcharl those are my fault, I'm taking care of those

**Comment by Tcharl** [comment]
Damn, parallel git really isn't that easy.
Sorry for the upstream history mess :-S.
I swear I'll do better the next time.

**Comment by jdubois** [comment]
@Tcharl that's also my fault, I keep making mistake and breaking the build... It's hard to work over the week end with a baby!

**Comment by jdubois** [comment]
I'm merging this - there is just a random Travis failure and I restarted it, but that's not your fault.

That was hard :-)

**Comment by deepu105** [comment]
@Tcharl the toStrings generated for the DTO are missing new lines after each attribute can you please check. I dont have enough time now to fix that. cc @jdubois

**Comment by jdubois** [comment]
@deepu105 I'm checking this

**Comment by jdubois** [comment]
Done: https://github.com/jhipster/generator-jhipster/commit/979926e7ee972ba01ea39b3f8f3d90b917a48ac9

**Comment by Tcharl** [comment]
Sorry, I did not notice.
Regards,

**Pull request merged**
