### PR TITLE
Added CORs support for microservices prefixed with /services/

### PR DESCRIPTION
**Pull request by jsm174**
This fixes the CORS issue in https://github.com/jhipster/generator-jhipster/issues/9903 which is a result of https://github.com/jhipster/generator-jhipster/pull/9262

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jsm174** [comment]
Here is a sample project to recreate this issue:

https://github.com/jsm174/jh610-cors-issue-demo

**Comment by ruddell** [comment]
Before v6, the microservice endpoints were covered by the existing CORS filters below, so I think this change is good.  It might be needed for the `management` endpoint too, which is called cross-origin by the registry.

    source.registerCorsConfiguration("/*/api/**", config);
    source.registerCorsConfiguration("/*/management/**", config);

**Comment by mraible** [comment]
Don’t you think it’s strange that I don’t need this change when running an Ionic app against microservices in Chrome?

I’m not against the change, I’m just trying to understand why I don’t need it. 🤔

**Comment by jsm174** [comment]
That's why I spent the time to put together the sample repo. :)

**Comment by mraible** [comment]
@jsm174 Thanks for taking the time to put this together. Unfortunately, I'm unable to build the frontend:

```
npm WARN tar ENOENT: no such file or directory, open '/Users/mraible/jh610-cors-issue-demo/frontend/node_modules/.staging/postcss-color-mod-function-1e2274db/LICENSE.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/mraible/jh610-cors-issue-demo/frontend/node_modules/.staging/postcss-color-mod-function-1e2274db/README.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/mraible/jh610-cors-issue-demo/frontend/node_modules/.staging/expect-2ea054d2/build-es5/index.js.map'
npm WARN tar ENOENT: no such file or directory, open '/Users/mraible/jh610-cors-issue-demo/frontend/node_modules/.staging/react-dom-9c77a418/umd/react-dom-unstable-fire.production.min.js'
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.2.tgz
npm ERR! 404
npm ERR! 404  'websocket-driver@0.7.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'frontend'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2019-06-26T10_06_40_625Z-debug.log
Execution time: 8 s
```

**Comment by jsm174** [comment]
Thanks @mraible . I just re-downloaded and it worked. But I'm guessing it's related to this:

https://stackoverflow.com/questions/56718056/websocket-driver-was-not-found-on-deploy

(which was just posted three days ago)

I'll clear out my node modules and see if I can reproduce.

**Comment by jsm174** [comment]
@mraible - Just updated. 

`package-lock.json` became out of date due to `websocket-driver` update.

**Comment by jsm174** [comment]
@mraible - Thanks for merging this. Thought I was going to have to track you down at your NJ speaking event to plead my case! ha

**Pull request merged**
