### PR TITLE
Unique constraints / enum key value support 

### PR DESCRIPTION
**Pull request by bmoers**
- check constraint name for uniqueness, in case related objects have similar name (start with same character) 
- support for values in enums (according to update in modelio parser in [jhipster-uml](https://github.com/bmoers/jhipster-uml))

### CODE REVIEW

**Comment by deepu105** [comment]
can you do seperate PRs for each feature please. also this needs to be discussed first

**Comment by bmoers** [comment]
Sorry, new here.
This is addressing #3839

**Comment by deepu105** [comment]
@bmoers I understand that. But we cant have two unrelated items in the same PR. can you remove the enum related stuff from this PR and submit that as a new PR please.

**Comment by deepu105** [comment]
@bmoers will you be making the suggested change? else we will need to close the PR to clean up tracker

**Comment by bmoers** [comment]
Was busy with an other project. Yes, will do.

**Comment by bmoers** [comment]
@deepu105 Ok when I submit a new PR and you decline this one?

**Comment by deepu105** [comment]
@bmoers there have been some development in the issue #3839 we have added a solution there please take a look. comments there if you think that it can be improved.

As for the enum value support please open a feature request issue so that we can discuss and if the team agrees then you can do a PR for that. Im closing this as it has a lot of commits back and forth and will mess up the history

**Pull request closed without merging**
