### PR TITLE
Update _messages_pt_br.properties

### PR DESCRIPTION
**Pull request by tiagovt**
Translate pt-br message create account

### CODE REVIEW

**Comment by tiagovt** [comment]
translate messages pt-br

**Comment by deepu105** [comment]
you need to rebase and resolve conflicts

**Comment by wmarques** [comment]
ping @tiagovt

**Comment by tiagovt** [comment]
@deepu105 , how to do it?

**Comment by deepu105** [comment]
Check the contributing.md file on the project root for instructions to
rebase

**Pull request merged**
