### PR TITLE
Disable e2e at ms-react-gateway-consul-oauth2 test.

### PR DESCRIPTION
**Pull request by mshima**
It's broken.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Why is it broken ? since when ?

**Comment by pascalgrimaud** [comment]
Ok, maybe since we changed from Protractor to Cypress

**Comment by mshima** [comment]
Never worked with cypress.
This was the only missing test.
Maybe it’s related to oauth like daily builds.
But was working there some time ago.

**Comment by pascalgrimaud** [comment]
yes, looks like the same, so we already have the ticket, I'll put the link there

**Pull request merged**
