### PR TITLE
disable lazy bean init to make hot reload via dev tools working again

### PR DESCRIPTION
**Pull request by atomfrede**
See https://groups.google.com/forum/#!topic/jhipster-dev/aFZ4O2ebFuQ for details. Instead of removing the `LazyInitBeanFactoryPostProcessor` it is just disabled by default such that users can decide to enable it to gain startup performance for loosing hot reloading java code.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
FYI, error in logs:
> LazyInitBeanFactoryPostProcessor.java:[25,2] cannot find symbol
  symbol: class ConditionalOnExpression

**Comment by atomfrede** [comment]
Ah sorry forgot to add the import.

**Comment by murdos** [comment]
> 
> 
> Instead of removing the `LazyInitBeanFactoryPostProcessor` it is just disabled by default such that users can decide to enable it to gain startup performance for loosing hot reloading java code.

Then we should document it. Otherwise it will be unused and dead code.

**Comment by atomfrede** [comment]
Yes, definitly. Will provide a doc PR later today.

Am Di., 26. März 2019 um 08:54 Uhr schrieb Aurélien Mino <
notifications@github.com>:

**Comment by pascalgrimaud** [comment]
But is it really usefull to keep this file ?

**Comment by atomfrede** [comment]
We could just remove it and put it as a tip maybe.

Am Di., 26. März 2019 um 09:02 Uhr schrieb Pascal Grimaud <
notifications@github.com>:

**Comment by PierreBesson** [comment]
I think we need to remove it. As the feature will be available in Spring Boot 2.2 and can be enabled with just a property: https://spring.io/blog/2019/03/14/lazy-initialization-in-spring-boot-2-2

**Comment by jdubois** [comment]
Yes let's just remove it, it's not worth the effort as @PierreBesson says

**Comment by atomfrede** [comment]
Alright, will remove it.

Am Di., 26. März 2019 um 11:43 Uhr schrieb Julien Dubois <
notifications@github.com>:

**Comment by atomfrede** [comment]
@jhipster/developers I have removed the file. Please check if the cleanup of that file is correct.

**Comment by pascalgrimaud** [comment]
no need to clean up, there was no release since we introduced this file

**Pull request merged**
