### PR TITLE
Add Maven  --batch-mode option to improve CI readability in GitHub Actions

### PR DESCRIPTION
**Pull request by jdubois**
This should remove all the "downloading artefact" clutter in the console log, if this works this is going to be a lot better for reading the logs

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I don't understand what happened here in the CI with these failures. It looks not related to your PR, we need to investigate

**Comment by mshima** [comment]
> I don't understand what happened here in the CI with these failures. It looks not related to your PR, we need to investigate

Seems to be new chrome driver release.

**Comment by kaidohallik** [comment]
Seems that Chrome version 79 is declared as stable since 17.12.2019 and this is incompatible with webdriver-manager 12.1.7. I tried to use webdriver-manager version 13.0.0 but the same error.

https://chromereleases.googleblog.com/2019/12/stable-channel-update-for-desktop_17.html

**Comment by kaidohallik** [comment]
Hmm, error message is saying that chromedriver version is 79 - so this is latest, but Chrome version seems to be old in GitHub Actions.

In GitHub Actions page I can see that in https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts is information: **Google Chrome (Google Chrome 78.0.3904.108 )**

So one possible explanation is:
* webdriver-manager downloads chromedriver 79
* GitHub Actions uses fixed chrome version 78

And these are incompatible.

**Comment by vishal423** [comment]
Looks like we don't control the version of driver to use. To fix broken builds, we can install latest chrome binary as part of build step.

**Comment by kaidohallik** [comment]
I tried to add to GitHub Actions step:
```
sudo apt-get install google-chrome-stable
```

The I see in the CI logs: **google-chrome-stable is already the newest version (78.0.3904.108-1)** and nothing is installed additionally and error remains.

**Comment by vishal423** [comment]
You need to update the package list before trying the install command. Anyway, I have done this change and will raise PR in next few mins

**Comment by kaidohallik** [comment]
OK, thanks @vishal423 !

**Comment by pascalgrimaud** [comment]
closing / reopening to trigger the builds

**Comment by mshima** [comment]
@pascalgrimaud if think the patch needs to be rebased to fix the ci builds.

**Comment by pascalgrimaud** [comment]
This is something I always wonder... Does it test the merge or only the branch ?
I think you're right, I need sleep :D

**Pull request merged**
