### PR TITLE
Save clientPackageManager in yo-rc.json file

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/issues/4317#issuecomment-267764276

### CODE REVIEW

**Comment by deepu105** [comment]
Take a look at my comment on the ticket. You dont have to rename it everywhere. You could use an in memory variable to retain yarnInstall/npmInstall as it would look better on switches

**Comment by pascalgrimaud** [comment]
@deepu105 : yes I agree it would be better for switches, but I was not happy with the variable name `yarnInstall` which I choose (because for me, `yarnInstall` is like a test if yarn is installed or not). I'd prefer to have a test with:
- `clientPackageManager === 'yarn'` instead of `yarnInstall`
- `clientPackageManager === 'npm'` instead of `!yarnInstall`

And these tests are in pom.xml and gradle files, not everywhere. So if you're ok, I'd prefer keep this new version.

What I did in this PR:
- I rebase with master
- I add npm test for clientFramework

**Comment by deepu105** [comment]
ok


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
Yes I agree with @pascalgrimaud as it's easier to understand for people who want to contribute

**Pull request merged**
