### PR TITLE
Add JSR310 types to entity generator for Java 8 projects

### LINKED ISSUE #1158: Use Java 8 Date Time API instead of JodaTime
If Java 8 is selected as Java runtime, it it better to use Java 8 Date API(JSR310) instead of the joda.

There some some points needs to be aligned with Java 8 and JSR310.

1. Spring date conversion and formatting by conversion service and @DateFormat
2. Jackson JSON desearialization and serialization should be compatible with AngularJS date filter.
3. JPA  Date conversion which can be done by JPA 2.1 @Convertor

### PR DESCRIPTION
**Pull request by cbornet**
Since the PR #1640 is blocked because it is not compatible with Java 7, I restarted one with a smaller scope (only entity generator) that is compatible with Java 7 and not too far behind the master branch.
* Joda is still used by the non-entity files (can be migrated later)
* Joda is still used by entity files if Java 7 is used.
* Hibernate attribute converters are used so jadira annotations are not needed.
* Jackson custom ser/deser are configured globally so jackson annotations are not needed.

Fix #1158

### CODE REVIEW

**Comment by deepu105** [comment]
@cbornet in the cloudMongoDbConfiguration.java file why is the java 7 check
in an or with oauth2 check?

**Comment by cbornet** [comment]
Because if oauth2 or java8 are selected we need a CustomConversions bean but oauth2 converters are added only if oauth2 is selected and jsr310 converters are added only if java8 is selected. Do you see a non working case ?

**Comment by deepu105** [comment]
Nope haven't tested just was curious

**Comment by cbornet** [comment]
Huh, not sure I did the right operation to resolve the conflict... Can someone familiar with git/github have a look ?

**Comment by paivaric** [comment]
+1

**Comment by cbornet** [comment]
Y U not merged ? It eventually conflicted again...

**Comment by jdubois** [comment]
Sorry, but this is like the other PR from @deepu105 and @ygrenzinger

- It's a lot of work to review so many lines of code, and we've had many opened bugs recently (I was working on a full-time gig for a client, not enough time to do everything)
- As far as I understand this will be a lot easier when Java 7 is removed, and when we have moved to Spring Boot 1.3

I clearly did not have the time to work on this, it's just too much work.

But, things are changing:

- I have more time at the moment
- I've started removing lots of bugs (have a look at our pulse, lots of closed bugs last week)
- I'm beginning to work on Spring Boot 1.3, and then that will be the Java 7 removal

So yes, time is coming that I will work on this.

**Comment by jdubois** [comment]
I'm sorry but I merged the PR from @deepu105 and @ygrenzinger as it looked more complete, and as it was the first one to be proposed.
There is still much testing to be done!!

**Comment by cbornet** [comment]
Well, I had some improvements over the other PR:
* Hibernate attribute converters are used so jadira annotations are not needed.
* Jackson custom ser/deser are configured globally so jackson annotations are not needed.
So I will fork from the new master to add these changes.
Great decision to remove java7 btw ! :+1:

**Comment by jdubois** [comment]
Yes @cbornet if you can further improve the code, feel free to do! I just created #2140 to track the progress on this, you can add your comments there

**Pull request closed without merging**
