### PR TITLE
refactor: use a logger to debug SQL

### PR DESCRIPTION
**Pull request by ctamisier**
Use a logger to debug SQL requests.
`spring.jpa.show-sql` writes to standard output.

(https://thorben-janssen.com/hibernate-logging-guide)

### CODE REVIEW

**Comment by DanielFran** [comment]
@ctamisier Should we also add org.hibernate.type.descriptor.sql?
_If you also want to get this information, you have to set the log level of org.hibernate.type.descriptor.sql to DEBUG_
````yml
org.hibernate.type.descriptor.sql: TRACE
````

**Comment by ctamisier** [comment]
I would say what we have now is enough. the `org.hibernate.type.descriptor.sql: TRACE` logs the bound parameters and it's quite verbose as it's one line per parameters...
I check the current DEBUG logs to see the shape of the SQL requests and how many there are. I'm not much interested for the actual values.
But this is: IMHO :)

**Review by DanielFran — APPROVED** [review]
LGTM.

@ctamisier Maybe just remove the show-sql property since the default is false?

**Comment by ctamisier** [comment]
Yes, indeed, I removed it in all configuration files.

**Pull request merged**
