### PR TITLE
Providing Role Checking directive

### PR DESCRIPTION
**Pull request by jgribonvald**
Providing directives that permit to hidde some links/actions when the user isn't in the specified role
As example it's usefull when a user can watch an entity but can't edit/delete it.

### CODE REVIEW

**Comment by jdubois** [comment]
This looks to me like the "isInRole" function we have in the navbar (have a look at navbar.controller.js and navbar.html)

I agree a directive might be better, at least we should consider both approaches:

- Can you have a look at this "isInRole" function?
- Could you compare both solutions?
- Of course, if we use your directive, could you also refactor the navbar so that it uses your directive instead?

**Comment by jgribonvald** [comment]
Ok sorry I didn't see that !

Maybe the ng-show approach is better because you can have several conditions depending on the scope and not only based on a role unlike my directive approach as it use only Principal function isInRole, isInAnyRole

**Comment by jgribonvald** [comment]
I pushed a second commit for the refactoring of the navbar using my directive.

Else finaly i think the directive approach is cleaner, and we don't have to modify any controller. If a customized approach is needed everybody can do it like it was done in the navbar before.

**Comment by jmirc** [comment]
Thanks for the support. It is a cleaner approach.

**Comment by jdubois** [comment]
Yes, great job !

**Comment by deepu105** [comment]
@jgribonvald Just a question, wouldn't it be better to do the ng-if approach (remove the element instead of hiding it, so that one cannot view by toggling css). I mean you have to ensure unathorized content is not served from server side anyway but was going through ng-if docs and seemed like a better option.
In most practical cases a role change would require reload of data and hence showing the element again should be fine right.
Plz correct me if I missed something

**Comment by jgribonvald** [comment]
The two approach can be used, depending of your willing/goal on controlling actions.
This directive is only a lighter way of doing than defining a function for a scope. After you can modify the directive to remove the element instead of hiding it.

In my point of view :

Only hiding a content is suffisant as you should secure all sever side actions and the served content. If you have to hide a secured content in the rendered html, you forgot something or made something wrong in your development.

Also like the "toggling css" the ng-if can be removed from the js code, nothing avoid css/js modification in the browser, keep in mind that only the server side is entirely secured and control secured datas. Controls in the front side are only for "cosmetics" and to avoid to do action/show links where the user will obtain errors/unwanted behaviour.

After for most pratical cases when a role change the best is to wait that the user logout/login again to show new rights else you will have too much things to implements (session objects, cache, force reload of front-end, etc...) and the user won't understand why something change during his actions.

**Comment by dearnani** [comment]
Can we invalidate the current loggedIn user if the roles got updated and
not belongs.

On Tue, Apr 14, 2015 at 10:54 PM, Julien Gribonvald <
notifications@github.com> wrote:

> The two approach can be used, depending of your willing/goal on
> controlling actions.
> This directive is only a lighter way of doing than defining a function for
> a scope. After you can modify the directive to remove the element instead
> of hiding it.
>
> In my point of view :
>
> Only hiding a content is suffisant as you should secure all sever side
> actions and the served content. If you have to hide a secured content in
> the rendered html, you forgot something or made something wrong in your
> development.
>
> Also like the "toggling css" the ng-if can be removed from the js code,
> nothing avoid css/js modification in the browser, keep in mind that only
> the server side is entirely secured and control secured datas. Controls in
> the front side are only for "cosmetics" and to avoid to do action/show
> links where the user will obtain errors/unwanted behaviour.
>
> After for most pratical cases when a role change the best is to wait that
> the user logout/login again to show new rights else you will have too much
> things to implements (session objects, cache, force reload of front-end,
> etc...) and the user won't understand why something change during his
> actions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/pull/1272#issuecomment-92988489>
> .
>



-- 
-SN RAO

**Comment by jgribonvald** [comment]
you can by deleting session id of the concerned user, but you will have to have a map of associated sessionid/userid (spring-security should help).

**Pull request merged**
