### PR TITLE
fixed turkish character problem

### PR DESCRIPTION
**Pull request by geist100**
Fixed jpa metamodel generation character encoding problem. Details: https://stackoverflow.com/questions/57182568/hibernate-jpa-2-metamodel-generator-turkish-char-problem

### CODE REVIEW

**Comment by mshima** [comment]
@geist100 seems wrong to force user language.
You should try a less intrusive approach.
Adding <encoding>UTF-8</encoding> to compiler plugin like the second answer seems enough.

**Comment by geist100** [comment]
> @geist100 seems wrong to force user language.
> You should try a less intrusive approach.
> Adding `<encoding>UTF-8</encoding>` to compiler plugin like the second answer seems enough.

Unfortunately not enough add this line <encoding>UTF-8</encoding> i tried many options, only add fork and compiler args works

**Comment by mshima** [comment]
In my opinion this should not be merged as it is now.
This is a locale specific bug, by merging this, we can break many others locales and have unpredictable problems

I think this PR fixes https://github.com/jhipster/generator-jhipster/issues/10239, you should post your fix there.

**Comment by pascalgrimaud** [comment]
Thanks for your PR @geist100 but as mentioned by @mshima we can't merge it, because it can break many others locales and have unpredictable problems on existing projects

Anyway, your proposal can be added to the documentation at https://github.com/jhipster/jhipster.github.io project, if you think it can help. So you're welcome to propose a PR there.

**Pull request closed without merging**
