### PR TITLE
Fix React uaa auth

### PR DESCRIPTION
**Pull request by agaspardcilia**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Oh, does it mean that UAA works with Spring Boot 2 ?

**Comment by agaspardcilia** [comment]
We can only do basic stuffs with this fix like login but as far as I tested, yes it seems.

**Comment by ruddell** [comment]
@pascalgrimaud UAA Auth was fixed for Spring Boot 2 here: https://github.com/jhipster/generator-jhipster/pull/7310

**Comment by pascalgrimaud** [comment]
thanks @ruddell !!

**Pull request merged**
