### PR TITLE
feat (angular): Upgrade angular to v10.0

### LINKED ISSUE #11990: Upgrade to support angular v10.0
##### **Overview of the feature request**
Angular v10.0 has been released. Checkout the details at https://blog.angular.io/version-10-of-angular-now-available-78960babd41

##### **Motivation for or Use Case**

It would be good to support latest angular version before next JHipster release.
- [ ] Upgrade angular version and associated dependencies in `JHipster`
- [ ] Upgrade angular version and associated dependencies in `ng-jhipster`

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vishal423**
Closes #11990 
- [x] Upgrade angular and associated library dependencies
- [x] Upgrade ng-jhispter
- [x] Upgrade to solution style typescript configurations
---

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
@jhipster/developers,  The PR is ready for review.

**Comment by pascalgrimaud** [comment]
I'm merging this, as the CI is green!
Trusting you on this

**Comment by vishal423** [comment]
Bounty claimed @ https://opencollective.com/generator-jhipster/expenses/22578

**Comment by pascalgrimaud** [comment]
approved @vishal423

**Pull request merged**
