### PR TITLE
Update _gradle.properties

### PR DESCRIPTION
**Pull request by rifatdover**
Fix https://github.com/jhipster/generator-jhipster/issues/6270

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by rifatdover** [comment]
https://github.com/jhipster/generator-jhipster/pull/6297

**Comment by pascalgrimaud** [comment]
I don't understand:
- in your issue https://github.com/jhipster/generator-jhipster/issues/6270, you don't use infinispan, and here, you updated `infinispan_hibernate52_version` from `5.2.8.Final` to `5.2.9.Final`
- there is still this property: `hibernate_version=5.2.8.Final`
- the last version is `5.2.10.Final`
- if there is an upgrade here, we should be done for Maven too

**Comment by rifatdover** [comment]
@pascalgrimaud Sorry yes you are right I created a new pull request https://github.com/jhipster/generator-jhipster/pull/6300

**Comment by pascalgrimaud** [comment]
Don't be sorry, thanks for your contribution @rifatdover :smile:

**Pull request merged**
