### PR TITLE
Change spring-boot:repackage to append exec instead of renaming to .original

### PR DESCRIPTION
**Pull request by myspivey**
Ticket https://github.com/jhipster/generator-jhipster/issues/2720

### CODE REVIEW

**Comment by jdubois** [comment]
I'm sorry but can you open up a ticket first? Why do you want to do this?

**Comment by myspivey** [comment]
Sorry updated with ticket number, I have a maven script that uploads the build files and does not like .original. This saves the need for a user to have to rename .original to .war when that is the file they wish to use for deployment.

**Comment by deepu105** [comment]
Makes sense actually.

Btw build failed can you check

**Comment by myspivey** [comment]
I will check tomorrow. It passed local so not sure what happened. Maybe we
can talk about having it rename the nonexec one instead to not impact those
who use the built-in tomcat. All of the large scale installs I work with
have exciting tomcat servers on aws already. Leaving as is really is not
ideal but if this does not work for others i can just keep adjusting local.
Trying to share for others who have the same issue.

**Comment by pascalgrimaud** [comment]
Build failed because of these lines :
- maven war : https://github.com/jhipster/generator-jhipster/blob/master/travis/scripts/05-run.sh#L15
- gradle war : https://github.com/jhipster/generator-jhipster/blob/master/travis/scripts/05-run.sh#L19

**Comment by myspivey** [comment]
Thanks pascalgrimaud. Must have been beat when I ran it. Because we no longer have .original and .war, instead we have two .war files, the mv command fails on the broad search for *.war.

**Pull request closed without merging**
