### PR TITLE
Added Malayalam language support

### PR DESCRIPTION
**Pull request by vipinbalanpp**
---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@vipinbalanpp Please sign the CLA

**Comment by vipinbalanpp** [comment]
Thank you for considering my contribution and I have signed the CLA. It's
great pleasure to connect with you

**Comment by mshima** [comment]
ng-default have all languages, add ml:
https://github.com/jhipster/generator-jhipster/blob/da6362f428952644c462902905c37907b0cce0c2/test-integration/samples/ng-default/.yo-rc.json#L49

**Comment by vipinbalanpp** [comment]
Okey. Fixed

**Pull request closed without merging**
