### PR TITLE
Extract FormControl utility methods.

### LINKED ISSUE #10198: [Feature Request] - Frontend: Move FormGroup to service
##### **Overview of the feature request**
When having entities with many fields, having them in the `entity-update.component.ts` file could be tedious. Also, when coding side-by-side it will force me to duplicate my code for creating the form, updating the form and for creating the entity from form (those can be big methods).

##### **Motivation for or Use Case**
This change would allow anyone to work _side-by-side_ without repeating code, by just calling the service. For instance, I have moved the code to the service and I have a method like this:

``` 
createFromForm(editForm: FormGroup): IInvoice {
    return {
        ...new Invoice(),
        id: editForm.get(['id']).value,
        (...many other variables....)
        };
    }
``` 

and I would just call

`let invoice = this.invoiceService.createFromForm(this.editForm);`

I think this will improve readability, would make the code even cleaner, and again, it would stop repeated code in the front end.

##### **Related issues or PR**
None that I know of.

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by mshima**
Closes https://github.com/jhipster/generator-jhipster/issues/10198.
Closes https://github.com/jhipster/generator-jhipster/pull/14156.

- Move away from FormBuilder, it doesn't bring any benefit for us.
- Expose functions for handling FormGroup.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by Tcharl** [comment]
Reviewed, good for me

**Comment by pascalgrimaud** [comment]
@kaidohallik or @wmarques : can one of you have a look plz? 🙏

**Comment by wmarques** [comment]
I find strange to have the component + form utility functions in the same file. Maybe we can move the form functions in a entity-name-form.functions.ts ? WDYT @mshima 
Should we add some unit tests on those? I think today only the component is tested, maybe it could be nice to have unit tests for functions.

**Comment by mshima** [comment]
> I find strange to have the component + form utility functions in the same file. Maybe we can move the form functions in a entity-name-form.functions.ts ? WDYT @mshima

👍 , I've tried to find a good name for it, but just kept in the same file.
@wmarques what about entity-name-form.utils.ts?

> Should we add some unit tests on those? I think today only the component is tested, maybe it could be nice to have unit tests for functions.

Let me think how to implement those tests.

**Comment by wmarques** [comment]
Yep entity-name-form.utils lgtm 👍
Thanks !

**Pull request closed without merging**
