### PR TITLE
Add static swagger docs

### LINKED ISSUE #1715: Integration of springfox-staticdocs and Swagger2Markup
Hello,

do you think it makes sense to create a generator for [springfox-staticdocs](http://springfox.github.io/springfox/docs/current/#configuring-springfox-staticdocs) which uses [Swagger2Markup](https://github.com/Swagger2Markup/swagger2markup). The generator could generate the unit test and Gradle/Maven pipeline which generates the HTML and PDF documentation and includes the artifacts into the JAR-file so that the documentation can be statically served by the Spring Boot app. No runtime libraries (overhead) and no swagger-ui needed. 
Swagger2Markup allows to add hand-written Markup (AsciiDoc or Markdown) documentation to your generated Swagger Markup documentation. The documentation is served by the MicroService App itself. A further documentation server is not required anymore.

The HTML and PDF result looks as follows:

image

Kind regards,
Robert Winkler

### LINKED ISSUE #1750: Feature: Notification system
currently JH app generated doesnt have any notification system for below
1. Successfull events like entity creation, update, delete etc.
2. Error events like validation failure on server, unknown errors etc

these can be observed in console logs but to an end user there is no indication of success/failures

My solution: Angular Http interceptor to listen for response, requestError and responseError events and provide a visual notification to user using a toast style notification message(using angular bootstrap alert service). green toast with successful entity creation/update/delete message or red toast with error reason and message

I have implemented this for my app looks good and works well. So if this would be useful in the default app i would like to add it to JH what say @jdubois @atomfrede @gmarziou @gzsombor @andidev

### PR DESCRIPTION
**Pull request by atomfrede**
Generated static api docs are located in: `target/docs` for maven and `build/asciidoc` for gradle. Will provide another PR for the jhipster website.

Close #1715

### CODE REVIEW

**Comment by jdubois** [comment]
In that case, do we still need to have the "dynamic" version? Shouldn't we remove it at the same time?

**Comment by atomfrede** [comment]
You mean the swager-ui? It would keep them both for now and maybe start a vote if swagger-ui should be removed.

**Comment by jdubois** [comment]
Yes that was my idea... On second thoughts, I don't think you can test your REST endpoints with it, like Swagger UI, so it's not really doing the same thing in the end.

**Comment by atomfrede** [comment]
Yes. Thats the main point for swagger-ui in my oppinion.

**Comment by jdubois** [comment]
Then do we need to also generate this documentation? I know it's not exactly the same thing, but we can't generate all options for everything. For me we should have only one option, then people can still add a second one if they want to - our added value is only if this second option is complex to set up, but here it doesn't look very complex to do.

**Comment by atomfrede** [comment]
Static docs make sense for external access without being an admin in the generated app. But I agree, it could be a part of tips 'n tricks maybe.

**Comment by atomfrede** [comment]
I've written a tip for the documentation instead.

**Comment by gmarziou** [comment]
I think we should consider to generate the swagger spec file by build, this way we would not have to generate it at startup time and still we benefit for swagger-ui for online testing.

There are many code generators that takes the spec file in input but they are painful to use when the spec is online and requires authentication. For instance you could generate a mobile client from this file. 

Usages are very similar to WSDL file in SOAP world.

**Pull request closed without merging**
