### PR TITLE
add class and field comments to entity generator

### LINKED ISSUE #1949: Add support for Class and Field javadoc comments to entity generator
Jhipster UML request the possibility to generate javadoc comments on Classes and Fields, see jhipster/jhipster-uml#46.

This could be implemented as optional properties in the json files so it will have minimum footprint on the entity generator.

### PR DESCRIPTION
**Pull request by andidev**
relates to jhipster/jhipster-uml#46
fix #1949

### CODE REVIEW

**Comment by andidev** [comment]
```json
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "complexJavadocRelationship",
            "otherEntityName": "complexJavadocRelationship",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "complexJavadocEntity",
            "javadoc": "<p>This class represents the Magna ligula pellentesque. Lacus ut sed. Himenaeos\nlitora et posuere. Accumsan purus inceptos. Ultricies praesent metus. &#47;*\nFames odio quam. *&#47;</p><p>TODO:</p>\n\n<ul>\n<li>first &uuml;ber</li>\n<li>second</li>\n</ul>\n\nMake sure that json special characters like double quotes \" and backslashes \\ are escaped in json file and correctly displayd in javadoc"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "complexJavadocField",
            "fieldType": "String",
            "javadoc": "<p>This class represents the Magna ligula pellentesque. Lacus ut sed. Himenaeos\nlitora et posuere. Accumsan purus inceptos. Ultricies praesent metus. &#47;*\nFames odio quam. *&#47;</p><p>TODO:</p>\n\n<ul>\n<li>first &uuml;ber</li>\n<li>second</li>\n</ul>\n\nMake sure that json special characters like double quotes \" and backslashes \\ are escaped in json file and correctly displayd in javadoc"
        }
    ],
    "changelogDate": "20150829194644",
    "dto": "no",
    "pagination": "no",
    "javadoc": "<p>This class represents the Magna ligula pellentesque. Lacus ut sed. Himenaeos\nlitora et posuere. Accumsan purus inceptos. Ultricies praesent metus. &#47;*\nFames odio quam. *&#47;</p><p>TODO:</p>\n\n<ul>\n<li>first &uuml;ber</li>\n<li>second</li>\n</ul>\n\nMake sure that json special characters like double quotes \" and backslashes \\ are escaped in json file and correctly displayd in javadoc"
}
```

will generate
```java
/**
 * <p>This class represents the Magna ligula pellentesque. Lacus ut sed. Himenaeos
 * litora et posuere. Accumsan purus inceptos. Ultricies praesent metus. &#47;*
 * Fames odio quam. *&#47;</p><p>TODO:</p>
 * 
 * <ul>
 * <li>first &uuml;ber</li>
 * <li>second</li>
 * </ul>
 * 
 * Make sure that json special characters like double quotes " and backslashes \ are escaped in json file and correctly displayd in javadoc
 */
@Entity
@Table(name = "COMPLEXJAVADOCENTITY")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class ComplexJavadocEntity implements Serializable {

    ...

    /**
     * <p>This class represents the Magna ligula pellentesque. Lacus ut sed. Himenaeos
     * litora et posuere. Accumsan purus inceptos. Ultricies praesent metus. &#47;*
     * Fames odio quam. *&#47;</p><p>TODO:</p>
     * 
     * <ul>
     * <li>first &uuml;ber</li>
     * <li>second</li>
     * </ul>
     * 
     * Make sure that json special characters like double quotes " and backslashes \ are escaped in json file and correctly displayd in javadoc
     */    
    @Column(name = "complex_javadoc_field")
    private String complexJavadocField;

    /**
     * <p>This class represents the Magna ligula pellentesque. Lacus ut sed. Himenaeos
     * litora et posuere. Accumsan purus inceptos. Ultricies praesent metus. &#47;*
     * Fames odio quam. *&#47;</p><p>TODO:</p>
     * 
     * <ul>
     * <li>first &uuml;ber</li>
     * <li>second</li>
     * </ul>
     * 
     * Make sure that json special characters like double quotes " and backslashes \ are escaped in json file and correctly displayd in javadoc
     */
    @OneToMany(mappedBy = "complexJavadocEntity")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<ComplexJavadocRelationship> complexJavadocRelationships = new HashSet<>();
    
    ...
    
}
```

**Comment by deepu105** [comment]
Awesome and they are optional right?  May be we can add another quest in
entity generator to capture this from user as optional input as well what
say?

**Comment by andidev** [comment]
It's fine by me. What do you sat @jdubois? This will lead to a lot more questioning but that is maybe no issue.

**Comment by andidev** [comment]
Added wordwrap on javadoc comment. It wraps att 80 characters. Not sure what the standard wordwrap is used for jhipster. @jdubois you have any input on this?

**Comment by jdubois** [comment]
@andidev I don't want to have all those added questions, it's just going to be annoying most of the time. My opinion is that the class and field names should be clear enough, so that documenting them is useless (most of the time). I also believe clean coding names are the best documentation.
For the line length, the policy is to follow Intellij IDEA rules, but to be honnest I'm not sure what they are here!

**Comment by andidev** [comment]
Okey I have a look at intellijs default setting.

@jdubois 
Are you okey with adding this feature at least for the jhipster uml (without questions asked by the generator)? I actually agree with you but that comments should not be needed but in complex systems they sometime could help.

**Comment by jdubois** [comment]
@andidev yes this would only be for JHipster UML, as it makes sense in this case to have the comments coming from the UML tool (this is in fact something I've done in the past, when I was using ArgoUML, probably around 2000 or 2001...)

**Comment by cbornet** [comment]
It would also be great to have these comments fill the swagger doc.

**Comment by andidev** [comment]
@cbornet unfortunately I have no swagger skills :cry: 
Could you hint me where the comments should be added so that swagger shows them?

**Comment by cbornet** [comment]
@andidev You can use ```@ApiModel``` on the class and ```@ApiModelProperty``` on the attributes https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#apimodel
Not sure how swagger-ui will react to html text though...

**Comment by andidev** [comment]
Did not find a way to deal with swagger. 

Jhipster UML seems to be done with their work on  their side. We should either merge this or close this PR. Are there any doubts on merging this @jdubois?

**Comment by andidev** [comment]
Fixed merge conflict so it should be mergable now

**Pull request merged**
