### PR TITLE
Improve spring cache implementation

### LINKED ISSUE #6796: Improve spring cache implementation
Hello,
 I would like to improve the cache support. For that I would like to add 'spring-boot-starter-cache' to dependencies, and give the possibility to the user to choose a cache system.
But before starting I have some questions.
Which default implementation do you want to use?
Spring cache offers the following services:
    - Generic
    - JCache (JSR-107) (EhCache 3, Hazelcast, Infinispan, etc.)
    - EhCache 2.x
    - Hazelcast
    - Infinispan
    - Couchbase
    - Redis
    - Caffeine
    - Guava (deprecated)
    - Simple
I have to add questions to configure the different implementations. if so which ones in priority?
It must be checked that the selected implementations do not collide with the selected hibernate cache.

I will take again the modifications made by erikkemperman https://github.com/jhipster/generator-jhipster/pull/6666

thanks

### PR DESCRIPTION
**Pull request by antarus**
Fix #6796 

Sorry I'm doing a wrong manipulation and I deleted my distant branch ...
I pushed her away.
I took into account the last request to use `enableHibernateCache` instead of `cacheProvider! == 'no' && databaseType === 'sql'`

## Tests
- [x] Delete Hibernate cache variable in yo-rc
- [x] test with old variable hibernateCache variable in yo-rc
- [x] With Ehcache + enableHibernateCache= true
- [x] With EhCache + enableHibernateCache= false
- [x] With Hazelcast + enableHibernateCache= true + session clustering
- [x] With Hazelcast + enableHibernateCache= true
- [x] With Hazelcast + enableHibernateCache= false
- [x] With Infinispan + enableHibernateCache= true
- [x] With no cache  + enableHibernateCache= false

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Guys, no worry about Travis. I'm currently working on changing the current tested applications.

So, what is not tested will be in Hipster-Labs, as we can't test everything here -> I need to document https://github.com/hipster-labs/jhipster-travis-build as it becomes more and more important in our system

**Comment by pascalgrimaud** [comment]
This is a compilation error for the 2nd build, app-ng2-cache-nol2

```json
{
  "generator-jhipster": {
    "baseName": "travisNg2",
    "packageName": "io.github.jhipster.travis",
    "packageFolder": "io/github/jhipster/travis",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "448f9a67a8a292c4905a733ec22cc3b78e493c56",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "myPrefix",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "travis": true,
    "serviceDiscoveryType": false,
    "clientPackageManager": "yarn",
    "clientFramework": "angularX"
  }
}
```

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/travis/domain/Operation.java:[42,6] incompatible types: javax.persistence.Cache cannot be converted to java.lang.annotation.Annotation
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/travis/domain/Label.java:[33,6] incompatible types: javax.persistence.Cache cannot be converted to java.lang.annotation.Annotation
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/travis/service/BankAccountQueryService.java:[81,88] cannot find symbol
  symbol:   variable BankAccount_
  location: class io.github.jhipster.travis.service.BankAccountQueryService
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/travis/service/BankAccountQueryService.java:[84,96] cannot find symbol
  symbol:   variable BankAccount_
  location: class io.github.jhipster.travis.service.BankAccountQueryService
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/travis/service/BankAccountQueryService.java:[87,101] cannot find symbol
  symbol:   variable BankAccount_
  location: class io.github.jhipster.travis.service.BankAccountQueryService
```

**Comment by antarus** [comment]
Sorry guys, but how do I push the @deepu changes in my branch?

@pascal, well done to @deepu who did the review and change a lot of things. I just learned a little more about the dev with node;)

I try to reproduce the test that does not work;)

**Comment by deepu105** [comment]
Its already in your branch just do a pull from your fork

`git pull origin spring-cache`

If your forks remote is not origin check using `git remote -v` and change above command accordingly

**Comment by pascalgrimaud** [comment]
Indeed, I'm interesting to know the workflow, used by @deepu105 here :
- how did you do to commit directly to the PR
- then, after, how the user can do for getting the new commits

**Comment by antarus** [comment]
@pascalgrimaud 
Regarding the tests to add, do you do it or do you want i fork and try PR on https://github.com/hipster-labs/jhipster-travis-build?

**Comment by deepu105** [comment]
@pascalgrimaud that's easy. Github gives repo maintainers permission to write to PR branches unless you opt out of it when doing a PR, so to make changes on a PR
```
git checkout -b spring-cache master
git pull https://github.com/antarus/generator-jhipster.git spring-cache
```
Make changes and commit
```
git push https://github.com/antarus/generator-jhipster.git spring-cache
```

Just make sure you use same branch name as the PR and thats it. Now the PR owner can just pull this in from his branch with `git pull origin spring-cache`

**Comment by pascalgrimaud** [comment]
@deepu105 : thanks for the tips, I didn't know that.

@antarus : I already start the work on my computer :-)

**Comment by antarus** [comment]
@deepu105, @pascalgrimaud 

After understanding what the travis script did, I was able to reproduce the anomaly on a windows environment.
the problem is located at the line https://github.com/antarus/generator-jhipster/blob/d03fc9ea66cce319c12f3a0051d90ae5f800c7f5/generators/entity-server/templates/src/main/java/package/domain/_Entity.java#L244 should be `enableHibernateCache` instead of `cacheProvider !== 'no'`
 
I can do the PR tonight after work ;)

**Comment by deepu105** [comment]
@antarus dont do new PR, just commit to this branch after pulling the changes here

**Comment by antarus** [comment]
yes that's what I intended to do .. my poor English: D

**Comment by deepu105** [comment]
@antarus can you tick the items you have tested from then list on the PR description?

**Comment by antarus** [comment]
@deepu105 It seems that there are errors during the upgrade. I need to do more testing but I don't know if I could work on it this weekend.

**Comment by pascalgrimaud** [comment]
Just tested the manual upgrade:
- generate an JHipster project with master branch
- checkout your PR
- merge master into this branch, as it's not up-to-date
- relaunch `jhipster` in the project -> I don't see any issue you mentionned @antarus. For me, it works fine

Here the diff:
```diff
diff --git a/.yo-rc.json b/.yo-rc.json
index 00a36fd..d8b11a8 100644
--- a/.yo-rc.json
+++ b/.yo-rc.json
@@ -37,6 +37,8 @@
     "languages": [
       "en",
       "fr"
-    ]
+    ],
+    "cacheProvider": "ehcache",
+    "enableHibernateCache": true
   }
 }
```

```diff
diff --git a/pom.xml b/pom.xml
index ff864a8..e77f4b9 100644
--- a/pom.xml
+++ b/pom.xml
@@ -99,6 +99,10 @@
     </dependencyManagement>
 
     <dependencies>
+        <dependency>
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-starter-cache</artifactId>
+        </dependency>
         <dependency>
             <groupId>io.github.jhipster</groupId>
             <artifactId>jhipster</artifactId>
```

**Comment by deepu105** [comment]
I tested and fixed some issues here so gonna merge it

**Pull request merged**
