### PR TITLE
use Hibernate initialization to eagerly load user authorities

### PR DESCRIPTION
**Pull request by hdurix**
use Hibernate.initialize() instead of .size() to load relation which may
confuse readers

NB: an other solution could be to load the association in UserRepository but this commited solution is a quicker one and needs less code changes.

### CODE REVIEW

**Comment by jdubois** [comment]
Yes but I didn't want to use Hibernate specific APIs.

**Comment by hdurix** [comment]
Alright, do you want me to have a look on the other solution?

I can add 2 new methods in UserRepository: findOneWithAuthorities and findOneByLoginWithAuthorities as it is done with findAllWithAuthorities.

**Comment by jdubois** [comment]
Oh yes, and I didn't recognize you (sorry, I'm using my phone), great to have you contributing!!

**Comment by pascalgrimaud** [comment]
@hdurix : FYI, I think your local git configuration isn't correct. So github didn't recognize you in commit log -> see here https://github.com/jhipster/generator-jhipster/pull/4463/commits

**Comment by cbornet** [comment]
Yes : either eager load or use a DTO.

**Comment by hdurix** [comment]
@jdubois : Ok I'll do this way, it will be much cleaner. No worries & thanks, happy to be onboard!
@pascalgrimaud : Thanks, I'll have a look at it.

**Comment by jdubois** [comment]
So sorry @hdurix but as you understand I'll keep it the way it is:

- OK it's not very readable code, and yours is better
- But the idea is that we stick to the JPA API as much as possible, and try not to use the Hibernate API

**Comment by hdurix** [comment]
Yes, I'll create a new pull request once I have the other solution with JPA done.

**Pull request closed without merging**
