### PR TITLE
add server-side entity sorting

### LINKED ISSUE #1270: Server-side sorting using Spring Data
I appreciate the fact that jHipster aims to bootstrap users using a plain vanilla AngularJS app, but I was wondering if server-side sorting could be offered.

Server-side pagination (using Spring Data) is already included so I guess adding server-side sorting wouldn't be that more intrusive.

I do realise that include a lot of additional libs and third party stuff i not desirable:

- https://github.com/jhipster/generator-jhipster/issues/668
- https://github.com/jhipster/generator-jhipster/issues/797

But wouldn't it be "simply" a matter of :

- Extend the REST layer to accept an optional sortOrder / sortDirection combo.
- Extend the PaginationUtil to create a Pageable that includes the sorting info
- Adding a ng-click on the column headers
- Add some glue in the controller to link everything together

I don't know what other REST layers / databases are currently support, but if we currently stick with Spring Data this shouldn't be that intrusive.

I can send you a pull request that adds server-side sorting if you want, or upload a sample app that demonstrates the technique.

### PR DESCRIPTION
**Pull request by geraldhumphries**
add server-side sorting on entity lists when pagination is enabled and
table headers are clicked

resolve #1270

### CODE REVIEW

**Comment by geraldhumphries** [comment]
Other things that could/should be done:

Client-side sorting when pagination is not enabled.
Arrows/column styling to indicate when a column is being sorted.
Multi-column sort?

**Comment by deepu105** [comment]
@geraldhumphries looks good to me. Isnt there any java side changes required for this? Have you tested with a generated application?

**Comment by geraldhumphries** [comment]
No Java changes required, `sort` is an attribute of Spring's `pagable`, like `size` and `page`. I've tested an entity with all kinds of pagination as well as without. I didn't test it with a freshly generated application though, only my project.

**Comment by geraldhumphries** [comment]
I have been slacking. The new changes have been tested with all forms of pagination in a newly generated application. I ran the Mocha tests on the repo, and the back/front end tests on the generated app.

TODO: 
User feedback for sorting column/direction
Usability improvements (cursor changes like ngClick does)

**Comment by deepu105** [comment]
Looks good. @jdubois  plz see if you are ok with it,   then ill merge and do some improvements as in todo above

**Comment by jdubois** [comment]
@deepu105 give me some time to test it, but it looks small and well made, this should be a nice update

**Comment by deepu105** [comment]
Sure, since this piggybacks on pagination can we just update the question
to inform user that pagination and sorting is enabled if they opt for
pagination, i don't think its worth adding as a new option

**Comment by geraldhumphries** [comment]
Fixed conflict.

**Comment by deepu105** [comment]
@jdubois im ok with this, plz merge if you are ok

**Comment by jdubois** [comment]
Looks good, I'm merging it

-> @geraldhumphries the only issue is that in the UI we have no indication at all that this works, so maybe you could add a tooltip, or an icon...

**Comment by deepu105** [comment]
Ill add some css rules to the directive

**Pull request merged**
