### PR TITLE
separate EntityManagementController content into separate files

### LINKED ISSUE #2798: Separate EntityManagementController content into EJS files based on pagination type
Discussed in #2657. Important because of how much the pagination types are going to diverge in #2657.

### PR DESCRIPTION
**Pull request by geraldhumphries**
separate EntityManagementController content into EJS files based on pagination type

fix #2798

### CODE REVIEW

**Comment by deepu105** [comment]
:+1: 

but this below is common in all can you keep that in the main template itself
```
 $scope.clear = function () {
             $scope.<%= entityInstance %> = {<%_
                 for (fieldId in fields) {
                         if (fields[fieldId].fieldType == 'Boolean' && fields[fieldId].fieldValidate == true && fields[fieldId].fieldValidateRules.indexOf('required') != -1) { _%>
                 <%= fields[fieldId].fieldName %>: false,<%_
                         } else { _%>
                 <%= fields[fieldId].fieldName %>: null,<%_
                             if (fields[fieldId].fieldType == 'byte[]' && fields[fieldId].fieldTypeBlobContent != 'text') { _%>
                 <%= fields[fieldId].fieldName %>ContentType: null,<%_
                             }
                         }
                     } _%>
                 id: null
             };
         };
         <%_ if (fieldsContainBlob) { _%>
         $scope.abbreviate = DataUtils.abbreviate;
         $scope.byteSize = DataUtils.byteSize;
```

**Comment by geraldhumphries** [comment]
What is `$scope.clear` used for? It turns out like this:
```        
        $scope.clear = function () {
            $scope.address = {
                streetLine1: null,
                streetLine2: null,
                city: null,
                provinceState: null,
                postalCode: null,
                country: null,
                id: null
            };
        };
```
Is it used anywhere? Or would it be okay to just remove it?

**Comment by deepu105** [comment]
Yes it was from old code, you can remove it, it was for create method but
thats moved to another controller now

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I think the refresh method is also not required

Thanks & Regards,
Deepu

**Comment by geraldhumphries** [comment]
Ignore the last commit, I will remove those methods and commit again.

But if I do that, I would like to have `$scope.loadAll()` at the bottom of every controller. That means I will need to move the blob fields back into the EJS files. Is that okay?

**Comment by deepu105** [comment]
ya should be fine

**Comment by deepu105** [comment]
I have stopped the Travis build, once you make next commit it will be started

**Pull request merged**
