### PR TITLE
#2546 Oracle: liquibaseDiffChangelog gradle task enhancement request

### PR DESCRIPTION
**Pull request by mhavrlent**
Oracle: liquibaseDiffChangelog gradle task enhancement request #2546

### CODE REVIEW

**Comment by deepu105** [comment]
Can you add h2memory as well or just put the h2config as the last else condition

**Comment by mipas1** [comment]
Sorry can't do. I don't use h2. Somebody else needs to do another PR...

**Comment by pascalgrimaud** [comment]
As h2memory will not persist, I think it is not usefull to launch a liquibase diff on a h2memory db

**Comment by jdubois** [comment]
Yes, no need to do h2memory, this doesn't make much sense.

**Comment by deepu105** [comment]
oops totally forgot that guys :P

On Fri, Jan 1, 2016 at 10:59 PM, Julien Dubois <notifications@github.com>
wrote:

> Merged #2548 <https://github.com/jhipster/generator-jhipster/pull/2548>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/pull/2548#event-503791919>
> .
>



-- 
thank you,
Deepu.k.s

**Pull request merged**
