### PR TITLE
Prepare CacheConfiguration for Infinispan 12

### PR DESCRIPTION
**Pull request by ecostanzi**
Update Infinispan cache configuration to work with infinispan 11 and 12.

To be merged AFTER https://github.com/jhipster/generator-jhipster/pull/14043 or https://github.com/jhipster/jhipster-bom/pull/201.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
The test failures are caused by a compile error:

```
[ERROR] /home/vsts/app/src/main/java/tech/jhipster/sample/config/CacheConfiguration.java:[182,21] cannot find symbol
  symbol:   method maxCount(long)
  location: class org.infinispan.configuration.cache.MemoryConfigurationBuilder
[ERROR] /home/vsts/app/src/main/java/tech/jhipster/sample/config/CacheConfiguration.java:[197,21] cannot find symbol
  symbol:   method maxCount(long)
  location: class org.infinispan.configuration.cache.MemoryConfigurationBuilder
[ERROR] /home/vsts/app/src/main/java/tech/jhipster/sample/config/CacheConfiguration.java:[210,21] cannot find symbol
  symbol:   method maxCount(long)
  location: class org.infinispan.configuration.cache.MemoryConfigurationBuilder
```

**Comment by ecostanzi** [comment]
@mraible yes I forgot to use my branch in the azure pipelines. Let's see now.

**Comment by pascalgrimaud** [comment]
@ecostanzi : can you update the CI config, so we can merge both PR at the same time plz ?

**Comment by pascalgrimaud** [comment]
thanks @ecostanzi

**Pull request merged**
