### PR TITLE
Upgrade cleanup

### PR DESCRIPTION
**Pull request by mshima**
- Remove all callbacks. Upgrade is much more understandable now.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mshima** [comment]
Hi @pvliss this removes all callbacks, so it is much more readable.
But keeps upgrade as a generator.

**Comment by mshima** [comment]
I can split into smaller PRs too.

**Comment by pascalgrimaud** [comment]
@mshima : can you resolve the conflicts plz

**Comment by mshima** [comment]
@pascalgrimaud done.

**Pull request merged**
