### PR TITLE
Fix Angular suffix issue

### LINKED ISSUE #6732: angularSuffix breaks in JHipster 4.11
##### **Overview of the issue**

When entities are generated with an `angularSuffix`, the imports in the Angular application do not work. 

##### **Motivation for or Use Case**

When an entity is generated with Angular with an `angularSuffix`, the directory as well as the components have a suffix. But when a component `A` depends on `B`, the import statement in Angular are not suffixed.

##### **Reproduce the error**

Take a simple monolith and generate the following entities : 

```
entity A {
    name String
}

entity B {
    name String
}

relationship OneToOne {
    A{b} to B
}

angularSuffix * with mysuffix
```

This will create a structure like this

```
├── entities
│   ├── a-mysuffix
│   │   ├── a-mysuffix-delete-dialog.component.html
│   │   ├── a-mysuffix-delete-dialog.component.ts
│   │   ├── ...
│   │   └── index.ts
│   ├── b-mysuffix
│   │   ├── b-mysuffix-delete-dialog.component.html
│   │   ├── b-mysuffix-delete-dialog.component.ts
```
The problem is that component `A` imports component `B` without any suffix : 

```
import { BMysuffix, BMysuffixService } from '../b';

@Component({ ... })
export class AMysuffixDialogComponent implements OnInit {
```

It should be 

`import { BMysuffix, BMysuffixService } from '../b-mysuffix';
`

So we get:

```
ERROR in ./src/main/webapp/app/entities/a-mysuffix/a-mysuffix-dialog.component.ts
Module not found: Error: Can't resolve '../b' in '/Users/agoncal/Documents/Code/Temp/jhipster411/src/main/webapp/app/entities/a-mysuffix'
 @ ./src/main/webapp/app/entities/a-mysuffix/a-mysuffix-dialog.component.ts 18:10-25
 @ ./src/main/webapp/app/entities/a-mysuffix/index.ts
 @ ./src/main/webapp/app/entities/a-mysuffix/a-mysuffix.module.ts
 @ ./src/main/webapp/app/entities/entity.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in [at-loader] ./src/main/webapp/app/entities/a-mysuffix/a-mysuffix-dialog.component.ts:12:45 
    TS2307: Cannot find module '../b'.
```

##### **Related issues**

* [Same entity name in several MicroServices collide in the Gateway](https://github.com/jhipster/generator-jhipster/issues/6480)
* [Brainstorming on a new Angular directory structure](https://github.com/jhipster/generator-jhipster/issues/6693)
* https://github.com/jhipster/generator-jhipster/pull/6618#issuecomment-345084227

##### **JHipster Version(s)**

```
bugsuf@0.0.0 /Users/agoncal/Documents/Code/Temp/jhipster411
└── generator-jhipster@4.11.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.bugsuf"
    },
    "jhipsterVersion": "4.11.0",
    "baseName": "bugsuf",
    "packageName": "io.bugsuf",
    "packageFolder": "io/bugsuf",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity A (a) {
  name String
}
entity B (b) {
  name String
}

relationship OneToOne {
  A{b} to B
}

angularSuffix A, B with mysuffix

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.15.0

node: v8.9.0

npm: 5.5.1

bower: 1.8.0

gulp:
[15:05:22] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.09.0-ce, build afdb6d4

docker-compose version 1.16.1, build 6d1ac21

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by deepu105**
Fix #6732 
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by adnansenyurt** [comment]
When this fix will be available? I need to re-generate my gateway with entities

**Comment by deepu105** [comment]
@adnansenyurt this is already fixed and released. Us ethe latest generator version

**Comment by adnansenyurt** [comment]
I'm using generator-jhipster@4.11.1 and still getting the error. Is there a later version?

**Comment by deepu105** [comment]
@adnansenyurt if you have an issue please open a ticket with all required details. This issue was fixed and closed and I dont know what you are experiencing

**Comment by agoncal** [comment]
@deepu105 I suppose @adnansenyurt is talking about this issue : https://github.com/jhipster/generator-jhipster/issues/6732. It has been fixed, but not released yet. So we can't re-generate our apps with 4.11.1... and we are waiting for 4.11.2 ;o)

**Comment by jdubois** [comment]
It will be 4.12.0 :-)
Might be released over the week-end but no guarantee, it depends on my free
time.

Le 8 déc. 2017 19:45, "Antonio Goncalves" <notifications@github.com> a
écrit :

@deepu105 <https://github.com/deepu105> I suppose @adnansenyurt
<https://github.com/adnansenyurt> is talking about this issue : #6732
<https://github.com/jhipster/generator-jhipster/issues/6732>. It has been
fixed, but not released yet. So we can't re-generate our apps with
4.11.1... and we are waiting for 4.11.2 ;o)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/pull/6748#issuecomment-350340726>,
or mute the thread

**Pull request merged**
