### PR TITLE
make Heroku sub generator blueprint aware

### PR DESCRIPTION
**Pull request by atomfrede**
This makes the Heroku sub generator extend BaseBlueprintGenerator, such that blueprints can overwrite e.g. generated property files to match their own configuration. A concrete use case can be found in the [micronaut blueprint](https://github.com/jhipster/generator-jhipster-micronaut/pull/85)  where e.g. the datasource properties and the procfile is different from the main generator.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
Thanks for approving. I have problem applying it to the micronaut blueprint (although it worked once during testing this PR).

when doing `jhipster heroku --blueprints micronaut` I get the following:

```
INFO! Executing jhipster:heroku
     info Using blueprint generator-jhipster-micronaut for heroku subgenerator
TypeError: (intermediate value)._initializing is not a function
    at module.exports.get initializing [as initializing] (/home/fred/git/github/jhipster/generator-jhipster-micronaut/generators/heroku/index.js:21:22)
    at module.exports.queueOwnTask (/home/fred/git/github/jhipster/generator-jhipster-micronaut/node_modules/yeoman-generator/lib/index.js:797:65)
    at /home/fred/git/github/jhipster/generator-jhipster-micronaut/node_modules/yeoman-generator/lib/index.js:843:45
    at Array.forEach (<anonymous>)
    at module.exports.queueOwnTasks (/home/fred/git/github/jhipster/generator-jhipster-micronaut/node_modules/yeoman-generator/lib/index.js:843:18)
    at /home/fred/git/github/jhipster/generator-jhipster-micronaut/node_modules/yeoman-generator/lib/index.js:1024:12
    at new Promise (<anonymous>)
    at module.exports.runWithOptions (/home/fred/git/github/jhipster/generator-jhipster-micronaut/node_modules/yeoman-generator/lib/index.js:1004:21)
    at runGenerator (/home/fred/git/github/jhipster/generator-jhipster/node_modules/yeoman-generator/lib/index.js:34:15)
    at Array.forEach (<anonymous>)
```

It looks like some trivial thing I forgot here, but I don't see it. I tried already to replace the heroku subgen in the blueprint with basically a noop generator, but still no luck. I also did change the heroku subgen in the main generator with a subgen that works for micronaut (e.g. service), but when creating the heroku gen in the blueprint via `instantiateBlueprints` I get again that message. So I am a bit confused where the error is, main generator (don't think so), micronaut blueprint (not sure) or in my local testing environment.

I did `npm link` on both projects and `npm link generator-jhipster` on the micronaut blueprint. In the folder I did a `npm link generator-jhipster-micronaut` and `npm link generator-jhipster` and I can see the up-to-date code in the node_modules folder.

**Comment by kaidohallik** [comment]
I also encounter strange `npm link` behaviour (I'm on Windows) when using linked module. My anomaly seems to be different but just in case describing that and workaroud to fix this in my case.

First step:
* going to `generator-jhipster` folder
* running `npm link`

Second step:
* going to `module` folder
* running `npm link`
* running `npm link generator-jhipster`

This second step deletes 38 folders from `generator-jhipster/node_modules` and running `jhipster` gives errors due to missing modules in `node_modules` folder.

If I run this second step in different order:
* first `npm link generator-jhipster`
* second `npm link`

then result is the same, 38 folders are deleted from `generator-jhipster/node_modules`

Third step:
* going to `generator-jhipster` folder again
* running `npm link` again

This restores those 38 deleted folders in `node_modules` and `jhipster` is running successfully after that and local `generator-jhipster` and `module` are used in generation.

**Comment by mshima** [comment]
Those npm link problems are npm 6 problems and can be fixed by running `npm ci` on generator-jhipster every time `npm link` is executed or using yeoman plugin notation.

@atomfrede if that problem persists post you updated branch.
The PR seems right.

**Comment by atomfrede** [comment]
Thanks I did some npm ci but before doing npm link. Will try it later today.

**Comment by atomfrede** [comment]
:tada: Thanks Marcelo for the detailed explanation. I did one npm ci to much inside micronaut blueprint. Now it works.

**Pull request merged**
