### PR TITLE
stub axios with sinon

### LINKED ISSUE #13066: Mock axios with sinon
##### **Overview of the feature request**

Use sinon to mock axios instead of jest

##### **Motivation for or Use Case**

In my project it was useful to mock axios with sinon to have more possibilities to check what was called.
There is not much impact for the services but it makes it easier to add new code for more complicated calls

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by nonomoho**
Fix #13066

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@nonomoho : can you update your git config, to use your email, associated to your GitHub account ? Because the CLA is already signed with this :)

**Comment by nonomoho** [comment]
Bounty claimed

**Comment by pascalgrimaud** [comment]
With the link, it would be better @nonomoho :-D
But it's ok, I got the mail.

Approved ! Thanks for your contribution on Vue.js !

**Comment by nonomoho** [comment]
Sorry, thank you Pascal, thank you JHipster !

**Pull request merged**
