### PR TITLE
Add csp header to allow data urls for image uploads

### LINKED ISSUE #10227: Jhipster doesn't open file uploaded
##### **Overview of the issue**

I have a entity with a blob field generated by JHipster. In the entity form I can upload a file and the form is submited normally.

The problem occurs when I try to open the file in the view page or main page of the entity.

The Browser opens this tab 

https://imgur.com/a/tXjqweT

and prints the following message on the console

> Refused to frame '' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

##### **Motivation for or Use Case**

Because it doens't show the file uploaded

##### **Reproduce the error**

After registered a entity object I can't open the file field uploaded in view page or main entity page

##### **Related issues**

No

##### **Suggest a Fix**

I commented this part in SecurityConfiguration.java and now it works

`.contentSecurityPolicy("default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com data:")
    .and()
        .referrerPolicy(ReferrerPolicyHeaderWriter.ReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN)
    .and()
        .featurePolicy("geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'self'; payment 'none'")
    .and()`

> https://stackoverflow.com/a/57505766/5360385

##### **JHipster Version(s)**

6.1.2

##### **JHipster configuration**

`-- generator-jhipster@6.1.2

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "br.com.renan",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "RenanTest",
    "packageName": "br.com.renan",
    "packageFolder": "br/com/renan",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "yeti",
    "clientThemeVariant": "primary",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": ["pt-br"]
  }
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.10.1.windows.1

node: v10.16.0

npm: 6.9

##### **Browsers and Operating System**

Windows Server 2012 R2

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by SudharakaP**
This pull requests handles csp problem related to image uploads. 

Closes #10227

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by SudharakaP** [comment]
@atomfrede : Trying to understand why some of the tests failed. 😕 Seems like it's related to https://github.com/facebook/jest/issues/8577

**Comment by atomfrede** [comment]
> @atomfrede : Trying to understand why some of the tests failed. confused Seems like it's related to [facebook/jest#8577](https://github.com/facebook/jest/issues/8577) . Can we retry the tests after some time?

Restarted the failed tests.

**Comment by atomfrede** [comment]
Thanks @SudharakaP for fixing this! :+1:

**Comment by SudharakaP** [comment]
@atomfrede : You are welcome 😄

**Comment by ctamisier** [comment]
This https://github.com/jhipster/generator-jhipster/pull/10384 might affect the current behavior of CSP generation...

**Pull request merged**
