### PR TITLE
Use the yo cli script from generator-jhipster node modules 

### PR DESCRIPTION
**Pull request by PierreBesson**
This removes the need to install `yo` globally to use blueprints

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
Copied in Ionic for JHipster! https://github.com/oktadeveloper/generator-jhipster-ionic/pull/112/commits/1bbc23421dcc587a548e91ddfdc667b64b4e8182

**Comment by avdev4j** [comment]
I can only approve this :D

**Comment by pascalgrimaud** [comment]
I updated your PR, by fixing some lint errors

**Comment by PierreBesson** [comment]
Thank you @pascalgrimaud

**Pull request merged**
