### PR TITLE
Allow e2e credentials to be configured

### PR DESCRIPTION
**Pull request by mraible**
This will allow testing OAuth 2.0 against Okta and other Identity providers. Just set `E2E_USERNAME` and `E2E_PASSWORD` as part of the CI process. Of course, you'll also need to configure the OIDC settings:

```
SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI="{issuer-uri}"
SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID="{client-id}"
SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET="{client-secret}"
```

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
It's a very good idea @mraible 
We need to do the same for React and Vue.js too
If you agree, let's merge this after the v6.8.0

**Comment by murdos** [comment]
@mraible : could you resolve the conflict (probably by reverting the unrelated change to `package-lock.json`) ?

**Comment by mraible** [comment]
@murdos Done!

**Comment by murdos** [comment]
LGTM. However I'm not sure we should merge these changes without doing the same thing for react. WDYT?

**Comment by mraible** [comment]
This PR includes React templates. 🙂

**Pull request merged**
