### PR TITLE
Change user id type to match database default type.

### PR DESCRIPTION
**Pull request by mshima**
https://github.com/jhipster/generator-jhipster/pull/12912 kept User id type intact.
This PR changes User id type to match default id for the database.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Cassandra needs more fixes.
Let this as draft for know, if anyone wants to finish it.

**Comment by MathieuAA** [comment]
Isn't it a breaking change? I'm okay with it, but we should be careful about merging it.

**Comment by DanielFran** [comment]
@MathieuAA this is for V7 si we are safe

**Comment by mshima** [comment]
> @mshima this is to fix a bug from #12912, right?

No, I think it's a bug, that I discovered at #12912, not consequence of it.

**Comment by mshima** [comment]
User id needs a refactoring focusing on primaryKey instead of database now that we have it calculated before rendering the template.
https://github.com/jhipster/generator-jhipster/blob/fe0b83e7f351fda211a9dfbbc5890ccabeafde68/generators/server/templates/src/main/java/package/domain/User.java.ejs#L131-L174

**Pull request closed without merging**
