### PR TITLE
[Do not merge] Revert "Revert "Fixed: Browsersync keeps refreshing #8275""

### PR DESCRIPTION
**Pull request by jdubois**
Try to fix the current master branch where React tests fail

### CODE REVIEW

**Comment by vishal423** [comment]
@jdubois , there was no change in dependencies and these were working before. This must not cause any issue.

**Comment by vishal423** [comment]
looking at 2 failure build logs, it seems they are due to type mismatch.

> [INFO]  ERROR  Failed to compile with 63 errors21:55:06
> [INFO]
> [INFO]  error  in /home/travis/app/src/main/webapp/app/entities/entity-with-dto/entity-with-dto-delete-dialog.tsx
> [INFO]
> [INFO] ERROR in /home/travis/app/src/main/webapp/app/entities/entity-with-dto/entity-with-dto-delete-dialog.tsx(12,105):
> [INFO] TS2344: Type '{ id: number; }' does not satisfy the constraint '{ id?: string; }'.
> [INFO]   Types of property 'id' are incompatible.
> [INFO]     Type 'number' is not assignable to type 'string'.

**Comment by jdubois** [comment]
Thanks @vishal423 !
Yes I know, I don't understand why this code would have caused any issue. But in Travis it looks like it broke with this commit, so I'm testing if reverting does anything (and I don't intend to merge this PR at all, of course).
I just deleted the Travis cache, in a desperate attempt to try to find the issue. I'm lost here.

**Comment by vishal423** [comment]
did you try to restart those 2 failed builds to see if they go through?

**Comment by jdubois** [comment]
yes, tons of time.... I'm totally lost here

**Comment by jdubois** [comment]
After more tests: the issue seems to come from a transitive dependency! So I'm closing this

**Comment by pascalgrimaud** [comment]
@jdubois : FYI, Travis cache concerns only `.m2` and `.gradle` because the backend libraries are stable enough and we don't need to download them each builds.
See https://github.com/jhipster/generator-jhipster/blob/master/.travis.yml#L16-L19

Intentionaly, there is no cache for `node_modules`. It could speed up a lot all our builds a lot !!! but we won't detect these transitive dependencies issues. That's why I removed the cache for `node_modules` long time ago.

Really sorry if I didn't communicate about it.

**Comment by jdubois** [comment]
Thanks for the information! Too bad we can't have reproductible builds as easily with NPM as with Maven.

**Pull request closed without merging**
