### PR TITLE
move all ResolvePagingParams to ng-jhipster

### PR DESCRIPTION
**Pull request by azizkhani**
#7403
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
you need to bump the ng-jhipster lib version in the package.json once its released

**Comment by azizkhani** [comment]
Should i change the version in package.json?

**Comment by deepu105** [comment]
you can update it here once I release the library.

Thanks & Regards,
Deepu

**Comment by azizkhani** [comment]
I solved all problem in my  [PR](https://github.com/jhipster/ng-jhipster/pull/65) in  ng-jhipster and waiting for approve . what i will do here to test generator PR?

**Comment by deepu105** [comment]
Dont worry, i'll check this soon

**Comment by deepu105** [comment]
@azizkhani update this PR to use ng-jhipster v0.4.7

**Comment by jdubois** [comment]
This looks finished - @deepu105 can you review and merge?

**Comment by deepu105** [comment]
Yup, some PRs are waiting for me, need to really find some time

**Comment by jdubois** [comment]
@deepu105 Not sure I have time and I'm probably not the best person for this, so no guarantee from me

**Pull request merged**
