### PR TITLE
adding cipher suite SSL for prod 

### PR DESCRIPTION
**Pull request by raiden0610**
strengthen the SSL security with the correct cipher suite
Grade B in SSLlabs (https://www.ssllabs.com/ssltest/) goes to A- with this one

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Awesome - that's what I like with JHipster, lots of people with different backgrounds helping each other!!

**Comment by jdubois** [comment]
Could you add some documentation on what this cipher suite does, etc? Because people will wonder why they have this commented, and what it does when you uncomment it

**Comment by PierreBesson** [comment]
@raiden0610 Maybe add a comment in the source with a link to where this cypher list comes from. Also how often is it updated ?

**Comment by raiden0610** [comment]
yes you're right, but you mean in the comment section of the yml or on the jhipster documentation ?

**Comment by raiden0610** [comment]
I'll try to keep it up to date.
I compile it throught the certbot (Lets encrypt) configuration of apache

**Comment by jdubois** [comment]
Yes just put it into the comments in the yml file

**Comment by raiden0610** [comment]
Okay for me

**Comment by PierreBesson** [comment]
@raiden0610 Congrats for your first contribution !

**Comment by raiden0610** [comment]
Thanks you :)

**Comment by gmarziou** [comment]
Bravo! Waiting for the next one :)

**Comment by jdubois** [comment]
Great! This will be in the next release!

**Pull request merged**
