### PR TITLE
jdl: Support svelte as client framework

### PR DESCRIPTION
**Pull request by vishal423**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Maybe there is a unit test to add somewhere?

**Comment by vishal423** [comment]
> 
> 
> Maybe there is a unit test to add somewhere?

I do see generic tests to verify the application options like https://github.com/jhipster/generator-jhipster/blob/78131e08acade3719bc19368d981c73fac10b40f/test/jdl/jhipster/application-options.spec.js#L25 I don't see a test case for an individual option(s). Do you think that would make sense?

**Comment by pascalgrimaud** [comment]
I don't know, that's why I asked :)
Feel free to merge it, when you think it's ready, so we won't forget it for beta.2

**Comment by MathieuAA** [comment]
Nothing to do really... It's only a value

**Comment by pascalgrimaud** [comment]
Thanks @MathieuAA

**Pull request merged**
