### PR TITLE
Conditionally publish to docker hub.

### PR DESCRIPTION
**Pull request by mshima**
Related to https://github.com/jhipster/generator-jhipster/issues/15881

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@mshima : thanks for your work here. Do I need to add some secret to the project ?

**Comment by mshima** [comment]
@pascalgrimaud yes, DOCKERHUB_USERNAME and DOCKERHUB_TOKEN.

**Comment by DanielFran** [comment]
@pascalgrimaud can you create the variables to merge this PR?

**Comment by mshima** [comment]
The step is conditional on the variable.
No need to create now.

**Comment by DanielFran** [comment]
Yes, I saw it. Just to be ready to create for cker images...

**Comment by pascalgrimaud** [comment]
ok I'm looking into it

**Comment by vishal423** [comment]
@pascalgrimaud , Can you please also make `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` secrets as organizational secrets available to the `svelte` blueprint project?

**Comment by pascalgrimaud** [comment]
Ok, will do it tomorrow.
Ping me if I forget :-)

**Comment by vishal423** [comment]
@pascalgrimaud  ping

**Pull request merged**
