### PR TITLE
Enhance travis entity tests

### PR DESCRIPTION
**Pull request by cbornet**
Please don't merge yet. I am lazy so I will let gh test the tests and add more types one by one

### CODE REVIEW

**Comment by cbornet** [comment]
Thanks to this PR, I found a bug with mongo and blob type :smile: 
#2329

**Comment by jdubois** [comment]
That's really cool!

**Comment by cbornet** [comment]
All green. This can now be merged.
As for mongo and blob type, this can be added later in the fix for #2329

**Comment by deepu105** [comment]
thats awesome

**Comment by pascalgrimaud** [comment]
Great use of travis build !

**Pull request merged**
