### PR TITLE
make gatling scripts compatible with gatling 3

### LINKED ISSUE #9080: Gatling 3 Support
Gatling 3 is already a few month old. We should support gatling 3 at least for jhipster 6. See https://gatling.io/docs/current/migration_guides/2.3-to-3.0/#to-3-0 for details

### PR DESCRIPTION
**Pull request by atomfrede**
The generated gatling scripts are now compatible with gatling 3. I will update the documentation accordingly and how to call gatling. This is a breaking change as the scripts won't work with gatling 2.x anymore.

Tested with jwt and oauth. Will do it for session auth later, but I don't see why that should not work.

closes #9080

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by atomfrede** [comment]
:thinking: Something went wrong when integrating upstream :(

**Comment by pascalgrimaud** [comment]
@atomfrede : I played a lot with Gatling when preparing the Voxxed Microservices so if you need review, ping me when it's finished

**Comment by atomfrede** [comment]
Sure +1 Think I will close this an MR and create a new one, don't know what happend during rebase. The changes are quite small in fact.

**Comment by atomfrede** [comment]
Will close this and start a new MR with only the changes for gatling.

**Pull request closed without merging**
