### PR TITLE
Change blueprint for app generator to jhipster.

### PR DESCRIPTION
**Pull request by mshima**
This change will force blueprint to rename `generators/app` to `generators/jhipster`.

Closes https://github.com/jhipster/generator-jhipster/issues/12052.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by avdev4j** [comment]
I'm not sure to understand the consequences for existing blueprints

**Comment by pascalgrimaud** [comment]
@avdev4j : for me, all existing blueprints are already broken for v7. We need to write a doc to help them upgrading the blueprint. The doc is already started at https://github.com/jhipster/jhipster.github.io/tree/jhipster_7

**Comment by mshima** [comment]
> I'm not sure to understand the consequences for existing blueprints

They need to rename `generators/app` to `generators/jhipster` and adjust tests to new location and namespace.
This change is to allow a module to be a sbs blueprint too.
I would prefer to deprecate modules in favor of sbs blueprint.
- Modules has to register hooks, we are supporting post app an post entity only.
- SBS blueprints you can do the same thing but in any step of the workflow without the need to register hooks.

**Comment by mshima** [comment]
Not sure if this change is worth.

**Comment by mshima** [comment]
I will use jhipster generator to bootstrap logos and configs.

**Pull request closed without merging**
