### PR TITLE
Fix issue #11222 : react in a few scenarios, the entity list page can invoke up to 4 calls to the backend API #11222

### PR DESCRIPTION
**Pull request by qmonmert**
Fix issue #11222

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mshima** [comment]
One unrelated question.
@qmonmert if you click at the failed test. Do you see, at the top-left, a re-run button?

**Comment by qmonmert** [comment]
@mshima no I don't see this button, only the core members see this button :(

**Comment by vishal423** [comment]
@qmonmert 
As current e2e test suite doesn't verify this flow, can you enable the protractor tests under `.github/workflows/react.yml` for following application types:
- `react-maven-psql-es-noi18n-mapsid`
- `react-gradle-psql-es-noi18n-mapsid`

Did you try running e2e on local with configurations that I shared on the ticket?

**Comment by qmonmert** [comment]
@vishal423 I tried your configurations, it's better with my PR but on some entities I have two calls when I navigate to list page of an entity

**Comment by qmonmert** [comment]
@vishal423 I fixed

image

**Comment by qmonmert** [comment]
@vishal423 it works with your .yo-rc.json and your jdl, and tests are ok

**Comment by pascalgrimaud** [comment]
trusting you on this, as @chrisdns approved it
Good job guys

**Comment by qmonmert** [comment]
@pascalgrimaud thanks

**Pull request merged**
