### PR TITLE
Persistence improvements using hypersistence optimizer

### LINKED ISSUE #10650: JPA improvements using Hypersistence Optimizer
##### **Overview of the feature request**

As the title says.

##### **Motivation for or Use Case**

These improvements will make persistence more efficient.
Here is the discussion: https://groups.google.com/forum/#!topic/jhipster-dev/GL-yOZmtlws 

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #10653: Update Mysql dialect to 8.0
##### **Overview of the feature request**

This is not a feature request but rather a question regarding mysql dialect should be updated or not.
While working on #10650 with mysql database, I got a MAJOR warning message as following.

```
MAJOR - DialectVersionEvent - Your application is using the 
[org.hibernate.dialect.MySQL5InnoDBDialect] Hibernate-specific Dialect. Consider using the 
[org.hibernate.dialect.MySQL57Dialect] instead as it's closer to your current database server version 
[MySQL 8.0]. For more info about this event, check out this User Guide link - 
https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#DialectVersionEvent
```
While I can update to `MySQL57Dialect `, it seems there is a new dialect available `org.hibernate.dialect.MySQL8Dialect` for our current hibernate version 5.3.x.

But before updating to either, I was wondering how many people are still on mysql db server 5.x.x.
I was not thinking to upgrade to `org.hibernate.dialect.MySQL8Dialect` but since we already have mysql docker image version 8.0.17, what do you think @jhipster/developers ?

Mysql 8.0 was out in Apr, 2018. https://www.mysql.com/news-and-events/
##### **Motivation for or Use Case**

Have the latest dialect version.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by pmverma**
Fixes #10650 
Fixes #10653 

Please note that all are verified using the `prod` profile only.

- [x] Postgresql
- [x] Mysql
- [x] Mariadb
- [x] Mssql
- [x] Oracle

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by Blackdread** [comment]
For OneToOne, if MapsId is not used then on one side of the relationship (side without foreign key) will always be eager fetched, even if you put Lazy.

**Comment by pmverma** [comment]
@Blackdread Yes you are correct. If it is bidirectional then there will be no effect. But for unidirectional, this will work.

**Comment by pmverma** [comment]
Thanks @DanielFran!

**Comment by cbornet** [comment]
There's a problem here : if we set the fetch strategy to be lazy at hibernate level, then it should be done at controller or service level. With the new behavior, if you call the REST endpoint for an entity, you don't see the related entity in the endpoint (it's `null`) and so it's not displayed in the front-end which is unexpected. It can even be very harmful : if you edit the entity then save without any modification, then the relationship is erased !

**Comment by pmverma** [comment]
Thanks @cbornet for describing the problem. Actually yes, I generated and tested the PR by skipping the client during generation. I will check it.

**Comment by pmverma** [comment]
For the moment, I will revert the lazy load. It is better to have a patch release for this.

**Pull request merged**
