### PR TITLE
Adding workbox for sw management

### LINKED ISSUE #6594: Website not showing latest changes after enabling PWA
##### **Overview of the issue**

If you do any change to your to your web-site and re-release it after enabling Service Worker: site doesn't come up. To fix this I have to clear the local cache data, and then it starts working.

Since I am naive on UI side, my guess is that we are saying in manifest.mf to cache index.html, and index.html have enteries for all css and java-scripts with some random number in its name. And since this random-numbers change with every release, hence site stops responding.

I will really appreciate your help.

##### **Motivation for or Use Case**

To enable PWA for my site, as it makes my site very fast and can be used like app on android.

##### **Reproduce the error**

To reproduce this error perform:
* Enable service worker in your app and release to production
* Everything will work fine, infact reload of site will happen very fast
* Now change anything in index.html or any css and release your site again to production.
* On visiting your website page, you will see blank screen.
To take care of this, you have clear your browser history and cached files.

##### **Related issues**

This issue is discussed here (last few comments): https://github.com/jhipster/generator-jhipster/pull/5880

##### **JHipster Version(s)**

4.7.0

##### **JHipster configuration**

~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "4.7.0",
    "baseName": "testapp",
    "packageName": "com.testapp",
    "packageFolder": "com/testapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
~~~

##### **Browsers and Operating System**

MacOS, Chrome Browser

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by sendilkumarn**
fix #6594

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by sendilkumarn** [comment]
closes #6594

**Comment by deepu105** [comment]
@sendilkumarn will this solve https://github.com/jhipster/generator-jhipster/issues/6594 ?

**Comment by sendilkumarn** [comment]
yes 👍

**Comment by marcelinobadin** [comment]
I would like to leave a comment... I have this situation, when I do update my application it does not come up, the solution was to change the dataCacheName and cacheName strings in sw.js. Then once the app updates, it detects a change on the key name, remove the old cache and use the new one. What would be cool to have is something that updates not only the version on app.constants but also on the sw.js (using the version on the cache name strings).

**Comment by kaidohallik** [comment]
FYI: I encountered same error as @gmarziou pointed in https://github.com/jhipster/generator-jhipster/pull/6841#issuecomment-350587303 (same error is reported also in Gitter):
* in one Windows 10 machine prod build constantly failed with this error
```
Error: workbox-sw is needed by the service worker and could not be copied over to your new site. Error: EPERM: operation not permitted, open 'C:\projects\jhipster-app\build\www\workbox-sw.prod.v2.1.2.js'
    at Promise.all.then.catch (C:\projects\jhipster-app\node_modules\workbox-build\build\lib\utils\copy-workbox-sw.js:17:13)
    at <anonymous>
```
* in one Windows 7 machine prod build constantly succeeded
* in Jenkins in Centos prod build randomly succeeded and randomly failed with error
```
Error: workbox-sw is needed by the service worker and could not be copied over to your new site. Error: ENOENT: no such file or directory, unlink '/var/lib/jenkins/workspace/jhipster-app/build/www/workbox-sw.prod.v2.1.2.js'
    at Promise.all.then.catch (/var/lib/jenkins/workspace/jhipster-app/node_modules/workbox-build/build/lib/utils/copy-workbox-sw.js:17:13)
    at <anonymous>
```

Now I tried to upgrade workbox-webpack-plugin to version 3.0.0-alpha.3 and after that builds in Windows 10 and Jenkins in Centos succeeded. It's possible that version 3 is more stable. Release notes are stating that workbox-webpack-plugin is rewritten in version 3: https://github.com/GoogleChrome/workbox/releases

**Comment by pascalgrimaud** [comment]
@kaidohallik : we discuss about it in our mailing list.
Can you have a look plz ? https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/jhipster-dev/Z_bLfnkMsWY

**Comment by antarus** [comment]
@ kaidohallik i have the same issue.
My directory was on read only mode.
Disable read Only on the directory of your project and apply to all file and directory, it's solve my error

**Comment by gmarziou** [comment]
I confirm that this is failing also all time on Ubuntu with 4.13.2, I'm going to try upgrading  workbox-webpack-plugin to version 3.0.0-alpha.3 as suggested by @kaidohallik

**Pull request merged**
