### PR TITLE
[angular] Fix Angular Sonar coverage and security hotspots

### PR DESCRIPTION
**Pull request by kaidohallik**
Should fix Angular part of #13232

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Arg, it's not fixed yet, because of https://github.com/jhipster/generator-jhipster/runs/1529536946?check_suite_focus=true :-(

```
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project jhipster-sample-application: The directory '/home/runner/work/generator-jhipster/generator-jhipster/app/ src/main/webapp/app/**/*.spec.ts' does not exist for Maven module tech.jhipster.sample:jhipster-sample-application:jar:0.0.1-SNAPSHOT. Please check the property sonar.tests -> [Help 1]
```

**Comment by kaidohallik** [comment]
I'm looking at that.

**Comment by DanielFran** [comment]
@kaidohallik Suggestion:

sonar.tests.inclusions=**/*.spec.ts
sonar.exclusions=src/main/webapp/app/**/*.spec.ts, src/main/webapp/content/**/*.*, src/main/webapp/i18n/*.js, target/classes/static/**/*.*

**Comment by kaidohallik** [comment]
If I looked at SonarCloud docs then suggestion was to define tests locations in `sonar.tests` to get best result.
But if this will not work then `sonar.exclusions` is alternative solution.

**Comment by kaidohallik** [comment]
Created fix in #13235, used `sonar.tests` and `sonar.test.inclusions`.

**Pull request merged**
