### PR TITLE
Add 'not delete state' condition on file when applying prettierTransform

### PR DESCRIPTION
**Pull request by avdev4j**
Files mark as 'deleted' has not content defined.
We have to skip them.

#9211

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by avdev4j** [comment]
I would add a 'delete' method in the private base generator but we should fix this bug first.

**Comment by murdos** [comment]
The fix looks fine to me. Are you sure to want to fix in master, and not in 5x maintenance branch?
BTW, don't worry, I will close PR and re-open this PR in order to force Azure pipeline to run again.

**Comment by avdev4j** [comment]
You're right I should do 2 PR for both v5 and v6. I'll open a new one for v5 👍

**Comment by murdos** [comment]
You can close this PR now, since I've merged the one for maintenance.
This change will indeed be reintegrated in master with https://github.com/jhipster/generator-jhipster/pull/9215

**Pull request closed without merging**
