### PR TITLE
add support for scoped blueprint packages

### LINKED ISSUE #9223: Handling 'scope' in blueprint names
##### **Overview of the issue**
Hello !
You probably know that Jhipster blueprints have a normalized name: generator-jhipster-*
For some reason we sometimes need to add a scope to our packages and named them like this `@hipsterCompany/generator-jhipster-myRedPrint`.

It actually not possible because the blueprint name is normalized by JHipster.
The pros is that when you're generating a new project with blueprint the command is simplified:
`jhipster --blueprint myRedPrint`

If I test by adding a scope the result is not really the result expected : 
`jhipster --blueprint @hipsterCompany/myRedPrint` -> `generator-jhipster-@hipsterCompany/myRedPrint`  

¯\\_(ツ)_/¯

##### **Motivation for or Use Case**
Using [scope](https://docs.npmjs.com/misc/scope) in NPM package.

##### **Suggest a Fix**
generator-base-private.js l. 721
```
    normalizeBlueprintName(blueprint) {
        if(blueprint.startsWith('@')) {
            return blueprint;
        }
        if (blueprint && !blueprint.startsWith('generator-jhipster')) {
            return `generator-jhipster-${blueprint}`;
        }
        return blueprint;
    }
```

I added a dumb condition to skip normalize if start with `@`but I'm sure we can do something better.
For now I prefer to discuss about it with you and to know what do you think about it.

##### **JHipster Version(s)**
5.8.1

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ruddell**
Tested locally with a scoped blueprint and it generated the expected files

Fix #9223

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pvliss** [comment]
Thanks @ruddell

**Comment by avdev4j** [comment]
We will have a strange commit message here ;) : 
https://github.com/jhipster/generator-jhipster/blob/917419bb2c86779834e6271fcbcbcec9087aef8f/generators/app/index.js#L505

`Initial application generated by JHipster-6.0.0  with blueprint: @myCompany/myBlueprint`

**Comment by avdev4j** [comment]
Also @ruddell have you check the blueprint name stored in the .yo-rc.json after this modification ?

**Comment by ruddell** [comment]
I think it complicates things to remove `generator-jhipster-` from the middle of the package name (and re-add it in the same place later), but it's probably possible.

The blueprint name stored in the .yo-rc.json is the full package name.

**Comment by avdev4j** [comment]
The blueprint name in the commit is not really an issue, who care about that ? :D 

About .yo-rc.json I think it's ok. 👍

**Pull request merged**
