### PR TITLE
Try to fix "Bidrectional OneToOne relationship get two entries"

### PR DESCRIPTION
**Pull request by jdubois**
See #6735

### CODE REVIEW

**Comment by deepu105** [comment]
@jdubois does React also have the issue?

**Comment by jdubois** [comment]
@deepu105 not exactly: there is a list with the normal items, with at the top an empty item. As the relationship is required, selecting the empty item gives a validation error `javax.validation.ConstraintViolationException: Validation failed`

**Comment by ruddell** [comment]
Did you try with a snapshot of the `jhipster` server library?  I think this solution requires some of the latest PRs that were merged but not released yet

**Comment by jdubois** [comment]
Thanks @ruddell - I didn't know that, so no I didn't test this. I'll try to do that today.

**Comment by jdubois** [comment]
@ruddell sorry but no, it doesn't change anything

**Comment by kaidohallik** [comment]
I tested it and seems that current `jhipster` server library still doesn't support `specified` on references.  
I tried solution in PR jhipster/jhipster#59 again and this worked again for me.

**Comment by duderoot** [comment]
I add a new comment on my previous PR in [jhipster-framework/#59](https://github.com/jhipster/jhipster/pull/59) for @gzsombor in order to know if there is a possibility to build the query that we need with the latest version of QueryService that hi refactored a few days ago.

**Pull request closed without merging**
