### PR TITLE
Fix/flaky react protractor

### PR DESCRIPTION
**Pull request by sendilkumarn**
This is another attempt to fix the flaky react protractor tests. The protractor best practice is to make the tests independent of each other, but here our tests are depending on each other. (check out style guide [here](http://www.protractortest.org/#/style-guide)).

But the flakiness might continue / resurface in the future(or even in this PR). The correct and long time solution will be to move towards Cypress. 

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
@sendilkumarn it's gonna be a very busy day for me, but I'll try to review it ASAP

**Comment by MathieuAA** [comment]
LGTM @sendilkumarn, I'm testing this against my weird fork

**Comment by sendilkumarn** [comment]
yeah, I changed this on top of your draft PR 👍

**Comment by MathieuAA** [comment]
Except for the usual memcached thing, everything seems to be okay @sendilkumarn. It should be good to go. Only 20 builds remaining

**Comment by MathieuAA** [comment]
Okay, the memcached builds fail for the now known reason, there's also a backend test that fails because of a dependency issue. https://github.com/MathieuAA/private-generator-jhipster/actions

**Comment by MathieuAA** [comment]
@sendilkumarn should your PR fail for the memcached builds? From what I see I'm not so sure

**Comment by sendilkumarn** [comment]
It should not, can you link the failed builds?

**Comment by MathieuAA** [comment]
There you go https://github.com/MathieuAA/private-generator-jhipster/runs/762908894#step:17:224

**Comment by MathieuAA** [comment]
Wait, why does it not fail here? perhaps there's something wrong with my repo

**Comment by sendilkumarn** [comment]
It looks like there is a fake data, but this is interesting.

**Comment by pascalgrimaud** [comment]
@sendilkumarn @MathieuAA : do you think we can merge this?my opinion is : it can be only similar or better than what we currently have

Don't hesitate to merge it !

**Pull request merged**
