### PR TITLE
Remove keycloak.yml inclusion for micoservices with oauth2

### LINKED ISSUE #8674: keycloak being added to app.yml for microservices with oauth2 causes startup errors
##### **Overview of the issue**

When creating a microservice with oauth2 option, keycloak.yml is added as include to app.yml, but no keyycloak.yml is available.

##### **Motivation for or Use Case**

Running into startup errors while starting the microservices with docker-compose -f src/main/docker/app.yml

##### **Reproduce the error**
Create a microservice with oauth2 and start with docker-compose -f src/main/docker/app.yml

##### **Related issues**

PR follows

##### **JHipster Version(s)**
5.4.x, 5.5.0 and master
 
##### **JHipster configuration**

```
jhipster@0.0.0 /home/rhermanns/code/jhipster/service
└── generator-jhipster@5.5.0 
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.service",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "microservice",
    "baseName": "service",
    "packageName": "com.example.service",
    "packageFolder": "com/example/service",
    "serverPort": "8081",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva3VuLXRvLWNoYW5nZS1pbi1wcm9kdVN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true,
    "languages": [
      "en",
      "de"
    ],
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by rainerh**
- updated condition check

Fixes #8674

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
@rainerh many of the tests are failing, i'll restart once to see if its a glicth. If they fail again please take a look

**Comment by mraible** [comment]
@rainerh This PR replaces #8554, correct?

**Comment by rainerh** [comment]
@mraible Yes, it replaces #8554. Only open issue from the discussion there is, if jhipster-registry.yml should be removed as well for microservices, because registry is started together with the gateway and would conflict with the current setup.

**Comment by mraible** [comment]
Yes, I believe jhipster-registry.yml should be removed as well.

**Comment by jdubois** [comment]
Thanks @rainerh !
Not sure about the registry, I know some people use it with just microservices (not sure how they handle the security, as indeed it wouldn't be logical with this PR)

**Pull request merged**
