### PR TITLE
Add Protractor support

### PR DESCRIPTION
**Pull request by mraible**
Integrates Protractor and upgrades Karma to latest version for Gulp and Grunt

### CODE REVIEW

**Comment by deepu105** [comment]
+1 looks good

**Comment by cbornet** [comment]
:+1: Do you think we could run the protractor tests in CI ?

**Comment by deepu105** [comment]
we can trigger grunt tasks via gradle/mvn so it should be possible i guess

On Fri, Nov 20, 2015 at 5:02 PM, Christophe Bornet <notifications@github.com
> wrote:

> [image: :+1:] Do you think we could run the protractor tests in CI ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/pull/2375#issuecomment-158330053>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by cbornet** [comment]
@deepu105 Sorry, I wasn't clear enough : I'm sure it is posssible to run protractor in CI (I've seen it in other projects). The question was should we do it :smile:  ?

**Comment by mraible** [comment]
I think we should as it's a good smoke test to ensure the app loads and
most pages load OK.

**Comment by deepu105** [comment]
Yup the max automation the better

**Pull request merged**
