### PR TITLE
Update spring-boot to 2.2.9 and other dependencies

### PR DESCRIPTION
**Pull request by DanielFran**
Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@atomfrede I do not understand why react-maven-cassandra-session-redis is OK and react-gradle-cassandra-session-redis failed in AccountResourceIT.testGetCurrentSessions !?!

Can you help to identify where could be the issue please?
Thanks

**Comment by atomfrede** [comment]
Will try to help. Maybe some difference what dependency has been resolved eventually but would be strange as we didn't change Gradle version

**Comment by pascalgrimaud** [comment]
That's what @murdos tried to fix here https://github.com/jhipster/generator-jhipster/pull/11803 but we revert his fix here https://github.com/jhipster/generator-jhipster/pull/12155

We need to investigate

**Comment by DanielFran** [comment]
@pascalgrimaud  Thanks for the information, did not realise that PRs could be related to the same issue.
Actually the PR is done and I am stuck only due to this issue... :(

**Comment by pascalgrimaud** [comment]
I found the bugs, fix them and push to this branch.
Should be OK now.

**Comment by DanielFran** [comment]
Thanks @pascalgrimaud 

Will take care to deploy it soon...

**Pull request merged**
