### PR TITLE
Fix HTTP Interceptor when JWT Token Expired

### LINKED ISSUE #5667: After sign-in from facebook, we are not navigating back to home page
##### **Overview of the issue**

When I am doing sign-in from facebook, even-though sign in is successful, I am navigated back to sign-in page.
In console logs, I can see following errors:
```
vendor.dll.js:8 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'destination' of null
TypeError: Cannot read property 'destination' of null
    at AuthService.authThen (auth.service.ts:26)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:365)
    at Object.onInvoke (vendor.dll.js:176)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:364)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (vendor.dll.js:176)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:397)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:165)
    at drainMicroTaskQueue (zone.js:593)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:464)
    at AuthService.authThen (auth.service.ts:26)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:365)
    at Object.onInvoke (vendor.dll.js:176)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:364)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (vendor.dll.js:176)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:397)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:165)
    at drainMicroTaskQueue (zone.js:593)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:464)
    at resolvePromise (zone.js:712) [angular]
    at :8080/polyfills.bundle.js:10995:17 [angular]
    at Object.onInvokeTask (vendor.dll.js:176) [angular]
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:397) [angular]
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:165) [<root> => angular]
    at drainMicroTaskQueue (zone.js:593) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (zone.js:464) [<root>]
```

##### **Motivation for or Use Case**

Looking at code also, and printing this.stateStorageService.getDestinationState(), I see null getting printed followed by error message mentioned above.

```
            const isAuthenticated = this.principal.isAuthenticated();
            console.log(this.stateStorageService.getDestinationState());
            const toStateInfo = this.stateStorageService.getDestinationState().destination;

            // an authenticated user can't access to login and register pages
            if (isAuthenticated && (toStateInfo.name === 'register' || toStateInfo.name === 'social-auth')) {
                this.router.navigate(['']);
                return false;
            }
```

##### **Reproduce the error**

To reproduce error, you can sign-in using facebook.

##### **Suggest a Fix**

Don't know.

##### **JHipster Version(s)**

4.3.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "jhipsterVersion": "4.3.0",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "xxxx",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

Chrome browser, OS is MacOS

- [x] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #5683: On session expired , Login modal window does not open
##### **Overview of the issue**

On session expired, Jhipster doesn't correctly manage the use case and doesn't open the login modal due to error in javascript .

##### **Reproduce the error**
Change the expiration of the token to a short delay.
You authenticate on Jhipster
You wait the delay
You open for exemple Audit in the Administration menu.

##### **Suggest a Fix**
It seems that storeDestinationState method is never called onStateStorageService to set the destination.
The error in the Chrome console is :  

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'destination' of null
TypeError: Cannot read property 'destination' of null
    at AuthService.authThen (auth.service.ts:25)
```   

##### **JHipster Version(s)**

```
jhipster@0.0.0 C:\kids\workspace\jhipster4.3
`-- generator-jhipster@4.3.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folde
r**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "d09b10ea7671b78bf26e0be3cbfc76435a566bdb",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhips
ter` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.9.0.windows.1

node: v6.10.0

npm: 4.5.0

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.11.2, build f963d76f

Windows 7

Tested on last Chrome version

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by wmarques**
So I removed the AuthService and just call logout when we receive a 401 from HTTP request.
Fix #5683 
Fix #5667

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x ] Tests are added where necessary
- [x ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Big issue here, I can't login into the application anymore since this was merged... I don't understand how Travis passed.

Here's my `.yo-rc.json`

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "tmp3",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "authenticationType": "jwt",
    "jwtSecretKey": "49eae40c7debc8bdb689422244a24a1936dbd886"
  }
}

**Comment by pascalgrimaud** [comment]
@jdubois : just tested with your config with **Angular1**, I don't have issue to log into the application. This PR concerned only Angular2, so it can't impact the angular1

The tests I did:
- your config + registry v2.6.0 -> OK
- your config + registry develop -> OK
- your config edited to use Angular2 + registry v2.6.0 -> OK
- your config edited to use Angular2 + registry develop -> OK

**Comment by jdubois** [comment]
Thank you so much @pascalgrimaud - let me test this again

**Comment by jdubois** [comment]
@pascalgrimaud in fact I can reproduce this on a fresh project... And if I regenerate it, it's working... Very strange, but totally blocking our next release :-(

**Comment by pascalgrimaud** [comment]
I will test again, but it is strange indeed.
So it's with Angular1 ?

**Comment by jdubois** [comment]
OK, got it -> forget about this, I'm correcting this :-)

**Comment by pascalgrimaud** [comment]
ok !

**Comment by jdubois** [comment]
No, it's my fault, it's a bug I did some time ago, see https://github.com/jhipster/generator-jhipster/commit/434902d361585d262f7f848a63c7d49667b65661

**Pull request merged**
