### PR TITLE
Integration test for webflux and R2DBC

### PR DESCRIPTION
**Pull request by murdos**
I've also disabled `webflux-couchbase-session` since there are already 2 other webflux-couchbase integration tests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
This one seems to be failing for a similar reason that https://github.com/jhipster/generator-jhipster/pull/11571 is. 

From [the build logs](https://github.com/jhipster/generator-jhipster/pull/11570/checks?check_run_id=582662065#step:14:932):

```
{"timestamp":"2020-04-13T13:25:19.203+0000","path":"/api/field-test-service-class-and-jpa-filtering-entities",
"status":500,"error":"Internal Server Error",
"message":"Blocking call! jdk.internal.misc.Unsafe#park","requestId":"5e408356"}
```

**Comment by mraible** [comment]
@murdos https://github.com/jhipster/generator-jhipster/pull/11571 passed after I merged from master, so you might try updating this branch.

**Comment by atomfrede** [comment]
The react builds are flaky for a longer time, so this can be merged i guess?

**Comment by murdos** [comment]
FYI CI tests are green now

**Pull request merged**
