### PR TITLE
Add oauth2 client details storage support for mongo

### PR DESCRIPTION
**Pull request by cbornet**
Basically, same as #3772 but this time for mongo.

### CODE REVIEW

**Comment by atomfrede** [comment]
:+1: Looks good!

**Comment by jdubois** [comment]
That's such a lot of work!!!!

**Comment by cbornet** [comment]
Nexr : cassandra ? :smile:

**Comment by jdubois** [comment]
there are very few people using OAuth 2, and very few people using Cassandra -> I don't recommend wasting time on this...

**Comment by cbornet** [comment]
Yes, that would probably be not very useful and just for the fun...

**Pull request merged**
