### PR TITLE
Enable fullTemplateTypeCheck for angular compiler

### LINKED ISSUE #7103: Enable fullTemplateTypeCheck for angular compiler
##### **Overview of the issue**

Found while working on #7093.

I added  `"fullTemplateTypeCheck": true` to `angularCompilerOptions` in `tsconfig-aot.json` and it raised few errors on jhipster-sample-app that should be fixed:

~~~
yarn run ngc
$ ngc -p tsconfig-aot.json
src\main\webapp\app\admin\audits\audits.component.html(11,93): : Expected 0 arguments, but got 1.
src\main\webapp\app\admin\audits\audits.component.html(16,93): : Expected 0 arguments, but got 1.
src\main\webapp\app\admin\health\health-modal.component.html(21,25): : Expected 2 arguments, but got 1.
src\main\webapp\app\admin\metrics\metrics.component.html(165,17): : Expected 2 arguments, but got 1.
src\main\webapp\app\admin\metrics\metrics.component.html(200,17): : Expected 2 arguments, but got 1.
src\main\webapp\app\admin\metrics\metrics-modal.component.html(25,22): : Expected 2 arguments, but got 1.
src\main\webapp\app\admin\metrics\metrics-modal.component.html(15,22): : Expected 2 arguments, but got 1.
src\main\webapp\app\entities\operation\operation-detail.component.html(22,80): : Property 'name' does not exist on type 'BaseEntity'.
~~~

##### **Motivation for or Use Case**

Template compilation detects real errors and should be enabled.

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by gmarziou**
Now that related issues have been merged on master, we can enable this useful option.
I have tested it on few samples but not all, let's wait for Travis ;)

Fix #7103

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X] Tests are added where necessary
- [X] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by gmarziou** [comment]
So Travis failed because ng-jhipster has not been released to include https://github.com/jhipster/ng-jhipster/pull/62

**Comment by deepu105** [comment]
@gmarziou patch release made for ng-jhipster

**Comment by gmarziou** [comment]
Thanks

**Comment by gmarziou** [comment]
All builds passed except React one so I guess it's OK to merge.

**Pull request merged**
