### PR TITLE
Use of cucumber jvm

### LINKED ISSUE #2022: Use of cucumber jvm
When generating a project, one can choose to use cucumber-jvm framework (was talked about in #897)

### PR DESCRIPTION
**Pull request by lordlothar99**
Fixed #2022

### CODE REVIEW

**Comment by lordlothar99** [comment]
Replaced PR #2023

**Comment by jdubois** [comment]
As per our guidelines, we should discuss first before adding a new technology, so this should not be merged now.

**Comment by lordlothar99** [comment]
Ok ! I let you guys talk about it, and decide whether or not merging .

**Comment by jdubois** [comment]
Yes, sorry François, but at the moment I don't want to add too much new stuff without the team agreeing on this.
I've had some very bad experience with Cucumber, but your code is optional and looks easy to add.

**Comment by lordlothar99** [comment]
no problem ! :)
actually as i read in issue #897 Cucumber was supposed to be available, i quickly added this as the 16th option (default is false)..

**Comment by jdubois** [comment]
Yes, or having a list of available frameworks would be cool, but maybe hard to maintain ?

**Comment by lordlothar99** [comment]
actually, i think it's better to avoid using too much frameworks in the generator so i won't be too painful to maintain. The fact is, if only 1 BDD framework is available, maybe some developers would say they prefer JBehave... but for now, it seems only 1 guy asked about BDD. so maybe you should consider avoiding to merge this PR for now, waiting for some developers to ask for a BDD framework.
i let you talk about this with other team members..

**Comment by atomfrede** [comment]
Your code seems very clean and easy to maintain. Maybe we could add it to the Tips 'n Tricks section first and start a survey who would like to use a BDD framework.

**Comment by MathieuAA** [comment]
Hi, @lordlothar99. I have two questions concerning [this file](https://github.com/lordlothar99/generator-jhipster/blob/master/app/templates/src/test/java/package/cucumber/_UserStepDefs.java).
First, why do you use the regex delimiters (`^` and `$`)? I know what they are, but I don't understand why you use them here.
The last question is about the naming of the methods. I know having methods named like `the_user_is_found` is an actual naming convention in Ruby (and in other languages), but I wander if you should use the Java naming convention in this case.

**Comment by lordlothar99** [comment]
hello @MathieuAA , the regexp i used are just those cucumber generated in the code snippets; I simply copied/pasted the code snippets as is. About the naming of tests methods : i always try to put a maximum of functional intention and clearest information ; Java's style "testBlaBla" seemed less convenient and explicit..

**Comment by MathieuAA** [comment]
I agree with the fact that prefixing ou appending test methods' name with "test" is not the prettiest choice, especially when the tests are done according to the BDD principle.
However, I'm just wandering whether using underscores in names is a good idea in this language.
The result would then be "searchForUser", or "theUserIsFound" (the names are not *that* important here).

**Comment by jdubois** [comment]
Why did you close it? Aren't we going to merge this??

**Comment by andidev** [comment]
+1 for merging it!

**Comment by jdubois** [comment]
My idea was to have a drop-down list with testing options:

- Gatling tests
- Cucumber tests

And then we could add new tests, like Selenium, etc...

We would only keep JUnit & Karma mandatory.

**Comment by lordlothar99** [comment]
sorry, i didn't intend to close it, it's just that my code was on master instead of dedicated branch...
sure it would be useful to have this drop down..
i will put my changes back on master, i guess the PR may reopen.
I will have a look at the drop down too

**Comment by lordlothar99** [comment]
Hey guys. i implemented the choices list. 
- gatling is activated by default
- cucumber is deactivated by default
I let you guys review my PR, and give me feedback 
:sunglasses:

**Comment by deepu105** [comment]
The use two variables for this seems a bit odd as it will keep increasing of we add more framework.I would rather keep it simple as `testFramework` like our DB options

**Comment by lordlothar99** [comment]
Hi @deepu105 ; I understand and i agree with you about the increasing number of variables, but testFrameworks is a bit different from db options, cause several values can be chosen... so those 2 variables would be merged into an array, which i find a little less convenient 
anyway, i will merge the variables, and commit the changes. i'll let you guys decide which is better.

**Comment by lordlothar99** [comment]
Hi @deepu105 .
If i'm not wrong, i need to use indexOf because testFramework is an array, which may contain several values, such as 'gatling', and/or 'cucumber', as  @jdubois requested previously.
I noted both ```<%_``` and ```<%``` are currently used, depending on the files... so I put the one that were obviously used in each file I modified. Maybe I didn't pay enough attention, but I didn't find any mistake.. can you plz give me a hint on where you want me to replace ?

**Comment by deepu105** [comment]
Oh ok missed that it was an array.

For `<%_` better to use whenever possible as you can write clear conditions
without having to wrap around the javascript code around the target code.
Its not a mistake to use the other form. Its ok we can improve it later as
well.

@jdubois Looks good to me, plz merge if you are ok

**Comment by lordlothar99** [comment]
:+1:

**Pull request merged**
