### PR TITLE
Change active entities menu when the user selected a entity submenu

### PR DESCRIPTION
**Pull request by sgrillon14**
change ui-sref-active="active" by ng-class="{active: $state.includes('entity')}"

### CODE REVIEW

**Comment by jdubois** [comment]
Your PR has some really strange errors, with commits dating from 2014... And you are not linking this to any ticket... I don't know what you are trying to do but this looks like an error?

**Comment by sgrillon14** [comment]
in generator-jhipster/generators/client/templates/src/main/webapp/app/layouts/navbar/navbar.html at line 21: <li **ui-sref-active="active"** ng-switch-when="true" class="dropdown pointer">


with this solution when I select an entity sub- menu , the " entities" menu is selected .

on my application I changed the line 21 with <li **ng-class="{active: $state.includes('entity')}"** ng-switch-when="true" has-authority="ROLE_ADMIN" class="dropdown pointer"> for this to work .

On my application the "entities" menu is only visible to the administrator.

**Comment by jdubois** [comment]
I don't really understand why you want to do this, but anyway your PR is doing something totally different: you are updating libraries, etc, but not modifying the menu.

**Comment by deepu105** [comment]
This is on 1.x branch which is totally outdated

**Comment by deepu105** [comment]
definitely seems like wrongly created. If you are trying to create PR for master choose the correct branch and open new PR

**Pull request closed without merging**
