### PR TITLE
Align dependencies with spring boot 1.5.3

### PR DESCRIPTION
**Pull request by erikkemperman**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Travis passed; https://travis-ci.org/erikkemperman/generator-jhipster/builds/225645021

### CODE REVIEW

**Comment by erikkemperman** [comment]
Is Travis still flaky? Same code [passed](https://travis-ci.org/erikkemperman/generator-jhipster/builds/225645021) on by fork!

**Comment by pascalgrimaud** [comment]
@erikkemperman : did your build success at the first run ?

**Comment by erikkemperman** [comment]
@pascalgrimaud No, I've had to restart one of them, once.

**Comment by erikkemperman** [comment]
Thanks for restarting the failing Travis builds! Still one failing, unfortunately, with the superficially the same error(s). I guess there might be an intermittent bug somewhere, but pretty sure it isn't related to my changes...

**Comment by erikkemperman** [comment]
Thanks!

**Pull request merged**
