### PR TITLE
Remove deps in favor of injectable for http interceptors

### PR DESCRIPTION
**Pull request by fleboulch**
Since Angular 5.2.3 we can use @Injectable for classes which implement HttpInterceptor (without the cyclic dependency error)

Angular thread: https://github.com/angular/angular/pull/19809

I tested it and it seems working fine.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
@fleboulch your changes doesnt have anything do with title, can you make PRs smaller with only relevant changes so that its easy to test and merge. Please dont do multiple unrelated changes in a same PR

**Comment by fleboulch** [comment]
@deepu105 this is just the 1st part of my PR. I do that to check travis tests passed. I have to push other things to complete it you are right.
But if you prefer I can change the title and merge this if you approve this work

**Comment by deepu105** [comment]
Yes please do smaller PRs, its easier to review and merge

**Comment by deepu105** [comment]
also please add small description of what is being done or what issue it addresses

**Comment by fleboulch** [comment]
@deepu105 I updated both title and description.
If you have time could you review it or someone else?
Thanks

**Comment by deepu105** [comment]
@wmarques can you please test this?

**Comment by wmarques** [comment]
@deepu105 ok i'll check this tonight

**Comment by wmarques** [comment]
@deepu105 ok i'll check this tonight

**Comment by wmarques** [comment]
@deepu105 LGTM, if Travis pass I think it's ok to merge, I can still test it manually if you want :) 
@fleboulch Thanks for this, I didn't know it was possible and it's much cleaner !

**Comment by wmarques** [comment]
@deepu105 LGTM, if Travis pass I think it's ok to merge, I can still test it manually if you want :) 
@fleboulch Thanks for this, I didn't know it was possible and it's much cleaner !

**Comment by wmarques** [comment]
@deepu105 LGTM, if Travis pass I think it's ok to merge, I can still test it manually if you want :) 
@fleboulch Thanks for this, I didn't know it was possible and it's much cleaner !

**Comment by fleboulch** [comment]
@wmarques it also allows to catch everything correctly.
Before, some errors were not broadcasted by the eventManager because the service was not injected yet.

**Comment by deepu105** [comment]
I was hoping you would test manually, since our e2e doesn't cover all the
cases

**Comment by wmarques** [comment]
@deepu105 sure, i'll check that tonight

**Pull request merged**
