### PR TITLE
Improve prettier

### LINKED ISSUE #10902: If generator and generated app are using different Prettier version then regeneration can show differences
##### **Overview of the issue**

If generator and generated app Prettier version differ, which is the case ATM:

* generator-jhipster: 1.16.4
* Angular: 1.18.2
* React: 1.18.2

then on regeneration can occur differences if not skipping Git commit hooks, because:

* on initial generation is app committed to Git which runs Prettier in generated app
* on regeneration Git commit is not done and sources are formatted only with generator Prettier

This is the case ATM, in Angular part `.yo-rc.json` and `page-ribbon.component.ts` are formatted differently in Prettier 1.16.4 and 1.18.2

##### **Motivation for or Use Case**

If files are not changed then no differences should be shown.

##### **Reproduce the error**

1. Generate app with the configuration pasted to this issue: `jhipster`
2. Regenerate app: `jhipster --force`

##### **Related issues**

Didn't fine.

##### **Suggest a Fix**

2 solutions:

* Solution 1. Keep generator and generated app Prettier in sync.
* Solution 2. Add the following command to `end()` function in client generator (and maybe make this optional, for example run only if new switch `--prettier` is specified?):
```
this.spawnCommandSync(this.clientPackageManager, ['run', 'prettier:format']);
```

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT C:\projects\teest\strict-shared
`-- generator-jhipster@6.5.1  -> c:\projects\kaido-github\generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "et"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1575892239104,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": ["et", "en", "ru"],
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount {
  name String required,
  bankNumber Integer,
  agencyNumber Long,
  lastOperationDuration Float,
  meanOperationDuration Double,
  balance BigDecimal required,
  openingDay LocalDate,
  lastOperationDate Instant,
  active Boolean,
  accountType BankAccountType,
  attachment AnyBlob,
  description TextBlob
}
entity TheLabel {
  labelName String required minlength(3)
}
entity Operation {
  date Instant required,
  description String,
  amount BigDecimal required
}
entity Department {
  name String required,
  description TextBlob,
  advertisement AnyBlob,
  logo ImageBlob
}
/**
 * JobHistory comment.
 */
entity JobHistory {
  startDate ZonedDateTime,
  endDate ZonedDateTime,
  language Language
}
entity Job {
  title String minlength(5) maxlength(25),
  type JobType,
  minSalary Long,
  maxSalary Long
}
/**
 * The Employee entity.\nSecond line in javadoc.
 */
entity Employee {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate ZonedDateTime,
  salary Long,
  commissionPct Long
}
entity Location {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Task {
  title String,
  description String
}
entity GoldenBadge {
  name String
}
entity SilverBadge {
  name String
}
entity Identifier {
  name String required unique
}
entity Country {
  name String
}
entity Region {
  name String
}
enum BankAccountType {
  CHECKING,
  SAVINGS,
  LOAN
}
enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}
enum JobType {
  BOSS,
  SLAVE
}

relationship OneToOne {
  Department{location} to Location,
  Employee{user(login)} to User with jpaDerivedIdentifier
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)},
  Employee{job} to Job{emp(lastName)},
  /**
   * A relationship
   */
  Department{employee} to
  /**
   * Another side of the same relationship,
   */
  Employee{department},
  Location{country} to Country{location},
  Country{area} to Region{country}
}
relationship ManyToOne {
  BankAccount{user(login)} to User,
  Employee{manager(lastName)} to Employee,
  Employee{sibag(name) required} to SilverBadge,
  Employee{gobag(name) required} to GoldenBadge,
  GoldenBadge{iden(name) required} to Identifier,
  SilverBadge{iden(name) required} to Identifier
}
relationship ManyToMany {
  Operation{theLabel(labelName)} to TheLabel{operation},
  JobHistory{department} to Department{history},
  JobHistory{job} to Job{history},
  JobHistory{emp(firstName)} to Employee{history},
  Job{chore(title)} to Task{linkedJob(title)}
}

dto BankAccount, Department, Employee, Location, GoldenBadge, SilverBadge, Identifier, Country, Region with mapstruct
service BankAccount, Location, Country with serviceImpl
service TheLabel, Department, Employee, GoldenBadge, SilverBadge, Identifier, Region with serviceClass
angularSuffix BankAccount with mySuffix
filter BankAccount, Employee
clientRootFolder BankAccount, TheLabel, Operation with test-root
paginate TheLabel, Job with pagination
paginate Operation, JobHistory, Employee with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

git version 2.24.0.windows.2

node: v12.13.0

npm: 6.11.3

yeoman: 2.0.6

yarn: 1.17.3

Docker version 19.03.5, build 633a0ea

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by kaidohallik**
Fixes #10902 

Contains 2 commits:
* first one formats `.yo-rc.json` after generation and upgrades Prettier version
* second one is the result of the `npm run lint-fix` as without that `npm test` failed (doesn't include `.github/workflows`, opening new issue about these files)

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mshima** [comment]
@kaidohallik I was taking a look at registerTransformStream and found this.
Looks like prettierYeomanConfig is not needed.

Add to '.yo-rc.json'
https://github.com/jhipster/generator-jhipster/blob/578d6e043bc3ddbb799234188f368a7e7cd08211/generators/generator-base-private.js#L1508

`const prettierFilter = filter(['.yo-rc.json', '{,**/}*.{md,json,ts,tsx,scss,css,yml}'], { restore: true });`

**Comment by kaidohallik** [comment]
@mshima, if I remember correctly then this transforms generated files. `.yo-rc.json` is not generated so this is not going through this function (and `.json` extension is already registered so this filter should already now cover also `.yo-rc.json`).

**Comment by mshima** [comment]
Actually `.yo-rc.json` is always generated.

It's generated at:
https://github.com/jhipster/generator-jhipster/blob/578d6e043bc3ddbb799234188f368a7e7cd08211/generators/app/index.js#L497

Added debug at https://github.com/mshima/generator-jhipster/tree/debug
Running `DEBUG=jhipster:transforms npm test`

Before:
```
jhipster:transforms Running prettier on /private/var/folders/fc/hg9dllnx6mb4109gnxzcwxhh0000gn/T/27dd6ec6f912a65ad7c0c7d0c98500ae62c974a4/package.json +0ms
  jhipster:transforms Running prettier on /private/var/folders/fc/hg9dllnx6mb4109gnxzcwxhh0000gn/T/27dd6ec6f912a65ad7c0c7d0c98500ae62c974a4/src/main/docker/app.yml +171ms
```

After:
```
 jhipster:transforms Running prettier on /private/var/folders/fc/hg9dllnx6mb4109gnxzcwxhh0000gn/T/ee345a0880e962653f701879db2b2e23f8831d10/package.json +0ms
  jhipster:transforms Running prettier on /private/var/folders/fc/hg9dllnx6mb4109gnxzcwxhh0000gn/T/ee345a0880e962653f701879db2b2e23f8831d10/.yo-rc.json +176ms
  jhipster:transforms Running prettier on /private/var/folders/fc/hg9dllnx6mb4109gnxzcwxhh0000gn/T/ee345a0880e962653f701879db2b2e23f8831d10/src/main/docker/app.yml +79ms
```

**Comment by kaidohallik** [comment]
Interesting finding, this debug shows that you are right. Would you like to do a PR to clean this? Otherwise I'll try to test it and make PR.

**Comment by mshima** [comment]
I am working on something else now.
Feel free to do it.

**Pull request merged**
