### PR TITLE
Fix couchbase token repository not compiling.

### PR DESCRIPTION
**Pull request by vladNCV**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@tchlyah can you take a look please?

**Comment by tchlyah** [comment]
Thanks @vladNCV, I've prepared the exact same PR. @DanielFran, you can merge it.

**Comment by DanielFran** [comment]
Closing/Reopenning to launch tests again

**Comment by jdubois** [comment]
Merging as tests pass, thanks @vladNCV ! Congrats for your 1st contribution to the project!

**Comment by vladNCV** [comment]
Thank you @DanielFran, @tchlyah, @jdubois (and ofc everyone else) for your work on this awesome project ! This was actually my first PR on an open-source project :), looking forward to spring-boot 2.1 and Java 11. Greetings from Tokyo :D

**Comment by jdubois** [comment]
Oh that's awesome @vladNCV !!! You didn't start with the easiest way to contribute :-)

**Pull request merged**
