### PR TITLE
Skip writing Okta admin password when useOkta false and printing okta admin password at the end of the console

### LINKED ISSUE #16394: Okta password is written to .yo-rc.json even when Okta is not used
##### **Overview of the issue**

When you run `jhipster heroku` with an OAuth 2.0 app, it writes an `oktaAdminPassword` key pair to `.yo-rc.json`. For example:

```
"useOkta": false,
"oktaAdminPassword": "67943b78cd02ef38c41af4cf30fb3fc98dbf0a31"
```

##### **Motivation for or Use Case**

When `useOkta` is false, there should be no other Okta-related values written to `.yo-rc.json`. 

Adding a password when it's not used will give the false impression that sensitive information has been leaked into source control.

##### **Reproduce the error**

Use the latest `main` branch to create an app and select OIDC for authentication. Then, run `jhipster heroku` to deploy it. Even if you select no for Okta, there's a value written for the password to `.yo-rc.json`. 

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/16299

##### **Suggest a Fix**

I tried to fix it but was unable to. I'm not sure what needs to change so this value isn't written.

##### **JHipster Version(s)**

`main` branch.

### PR DESCRIPTION
**Pull request by yuvarajsanjeevi**
Fix #16394 
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by atomfrede** [comment]
Thanks @yuvarajsanjeevi  for taking this. Exactly what I was thinking about

**Comment by mraible** [comment]
Testing this now...

**Comment by mraible** [comment]
The "No to Okta" option seems to work well. However, the "Yes to Okta" option seems to prompt to overwrite and continue adding the add-on while it's waiting for your response.

```
 conflict pom.xml
? Overwrite pom.xml? (ynarxdeH) jsxBracketSameLine is deprecated.
Created Okta addon
? Overwrite pom.xml? overwrite this and all others
```

I believe this is the same as before, so it's probably not an issue. You just have to be quick in demos or it looks funny.

The last line that starts with "Take note of this password!" can probably be removed. It's too dark to read and duplicates the previous message.

Screen Shot 2021-09-22 at 3 49 39 PM

NOTE: I changed my password so I'm not worried about exposing the generated one in this comment.

**Comment by mraible** [comment]
I think it might be a good idea to change this line:

```
Running ./provision-okta-addon.sh to create all required roles and users to use with jhipster.
```

To this:

```
Running ./provision-okta-addon.sh to create all required roles and users for JHipster.
```

**Comment by yuvarajsanjeevi** [comment]
> I think it might be a good idea to change this line:
> 
> ```
> Running ./provision-okta-addon.sh to create all required roles and users to use with jhipster.
> ```
> 
> To this:
> 
> ```
> Running ./provision-okta-addon.sh to create all required roles and users for JHipster.
> ```

Updated message as suggested

**Comment by yuvarajsanjeevi** [comment]
> The "No to Okta" option seems to work well. However, the "Yes to Okta" option seems to prompt to overwrite and continue adding the add-on while it's waiting for your response.
> 
> ```
>  conflict pom.xml
> ? Overwrite pom.xml? (ynarxdeH) jsxBracketSameLine is deprecated.
> Created Okta addon
> ? Overwrite pom.xml? overwrite this and all others
> ```
> 
> I believe this is the same as before, so it's probably not an issue. You just have to be quick in demos or it looks funny.
> 
> The last line that starts with "Take note of this password!" can probably be removed. It's too dark to read and duplicates the previous message.
> 
> Screen Shot 2021-09-22 at 3 49 39 PM
> 
> NOTE: I changed my password so I'm not worried about exposing the generated one in this comment.

we are printing login credentials only if Okta configured successfully. Please confirm is it fine to display credentials only on successful deployment

**Comment by atomfrede** [comment]
I would say it is fine to print it only when everything is successful.

**Review by mraible — APPROVED** [review]

**Comment by DanielFran** [comment]
Seems OK to everyone, let's merge this.

**Pull request merged**
