### PR TITLE
Open collective appeal update

### PR DESCRIPTION
**Pull request by deepu105**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

@jdubois are you ok with this and the wordings?

### CODE REVIEW

**Comment by jdubois** [comment]
I'm worried we push this a bit too far: people will then need to delete this from their app, and it's scattered in several files. I know we already do this, but it's mostly for pushing the documentation, so the goal is to help people.

**Comment by deepu105** [comment]
I thought since we already add the github liking part this was ok as well, I also felt that additing i18n for this and the github liking part might be too much as people would have to delete it anyway. May be we should translate the the last paragraph on home page so that people just can delete it from home page. Wdyt?

**Comment by deepu105** [comment]
I meant we shouldn't translate the last paragraph

**Comment by jdubois** [comment]
Yes, something simple & easy to delete, as this is what people will eventually do.
And next to the documentation -> they will also delete the link to the documentation, so that means they have something very useful (the documentation), and in exchange they have those few lines which are easy to delete. That's a good deal I think.
Anyway, don't worry too much: for me, the voting system is what will make OpenCollective take off. We already have enough advertisement for it, people know about it, it's just a matter of giving them something good in exchange. Yeah, that's not really a "donation", then :-)

**Comment by deepu105** [comment]
I guess you are right, lets not push it too far

**Pull request closed without merging**
