### PR TITLE
replace generated `Archtest` by `TechnicalStructureTest`

### PR DESCRIPTION
**Pull request by codecholeric**
Since the generated application is modelled after a simple layered architecture we can provide a generated [ArchUnit](https://www.archunit.org/) test that uses `Architectures.layeredArchitecture()` as a nice example of a higher abstraction architecture rule. This will assert even more dependencies for correctness than before (for example no dependencies from repositories to services). Furthermore, by specifying an exact list of which layer is allowed to access which other layer, instead of forbidding specific dependencies from one layer to another, we remove one potential source of accidental violation. E.g., by forbidding `service -> web` we can still have accesses like `services -> some_utils_no_one_cares_about -> web`. If we specify that no other layer may access web (because all accesses are via REST, etc., and not from other Java code), we can make sure that there are no accidental dependencies through some unexpected packages.

 I've also replaced the manual import via `new ClassFileImporter()...importPackages(..)` by ArchUnit's JUnit 5 support. The dependency was already correct anyway, and it allows to write the test a little more concisely and automatically brings caching between multiple rules that import the same classes.

Related: #17520

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by codecholeric** [comment]
When I forgot to push `DoNotIncludeTests` on the arch test I noticed that a lot of tests have a dependency `domain -> web.rest.TestUtil.equalsVerifier(java.lang.Class)` which seems a little weird to me :thinking: 
The top level Javadoc says "Utility class for testing REST controllers" but then the Javadoc on `equalsVerifier` suddenly talks about the domain object, i.e. deals with objects from `domain`.
Would feel cleaner to me if this `equalsVerifier` method would reside in test utils within `domain` if it deals with domain objects :man_shrugging: But for now I've added back "ignore tests" so at least the arch test shouldn't fail anymore because of that...

**Comment by codecholeric** [comment]
Hmm, I'm a little stuck I think. Because, the reactive configurations create the following dependency `repository.rowmapper.UserRowMapper -> service.ColumnConverter`. So this is in turn a cyclic constellation `service -> repository -> service`. Was it intended this way? It seems a little strange that logic to convert DB columns resides in the service layer? :thinking: 
Or I was wrong in the first place and this was never supposed to be layered this way, but then I still think a cycle between `repository` and `service` is weird in any case? (I would think one way or the other this should be directed on the static level?)
Anyway, I don't know exactly how I should go on, because I'm not sure what the original intentions were. Maybe somebody who knows why the code was designed like this originally can give me a hint? :pray:

**Comment by pascalgrimaud** [comment]
From my point of view, your arch tests are correct.

If we have `service -> repository -> service`, it's a mistake and it means our ArchTests need to be improved to detect this kind of code.

**Comment by mshima** [comment]
> Or I was wrong in the first place and this was never supposed to be layered this way, but then I still think a cycle between `repository` and `service` is weird in any case? (I would think one way or the other this should be directed on the static level?)
> Anyway, I don't know exactly how I should go on, because I'm not sure what the original intentions were. Maybe somebody who knows why the code was designed like this originally can give me a hint?

It’s open source, unless we have good tests in place and enforce code standards it’s hard to keep good code standards every time.

I think your PR looks correct, we should fix the implementation.
If I may, I will merge to a branch at main repository, so we can continue the work from there.

**Comment by codecholeric** [comment]
@mshima Sure, feel free to do what you want! Does this mean you would take over the change from this PR and adjust the implementation then? In any case, just let me know if you want me to change something / take further action in any direction!

**Comment by mshima** [comment]
Looks like there is only 1 failure. Should be easy to fix.

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/pull/17542 wasn’t enough, moving to a branch at main repository.

**Pull request merged**
