### PR TITLE
#3172 Jpa EntityListener used to synchronize ElasticSearch with database

### PR DESCRIPTION
**Pull request by lordlothar99**
- ElasticSearchConfiguration moved to dedicated config.elasticsearch
package
- ElasticSearchUpdater entityListener installed on JPA entities
- removed useless explicit EntitySearchRepository.save/update/delete
calls

### CODE REVIEW

**Comment by lordlothar99** [comment]
@jdubois @deepu105, what do you think about this ? :)

**Comment by deepu105** [comment]
LGTM this might have some effevt on my entity audit module but thats fine, i will find a way to make that work

**Comment by jdubois** [comment]
- Very good idea indeed. However, I'm not sure of what people want: maybe they like more control on what is searched? As far as I'm concerned this is better than the current solution, but I'm not sure everybody would agree.
- I hate the BeanFactoryHolder that you introduce. I understand you need this for your listener, but there should be a better way of doing this -> we need to study this before merging (and that's why I add the "needs discussion" tag
- Maybe I haven't looked closely enough, but don't you also need to delete all the current save/update/delete code in the entities?

**Comment by lordlothar99** [comment]
- @deepu105 I haven't checked consequences on audit module, please give me your feedback on that
- @jdubois I'm not very proud of `BeanFactoryHolder`, the fact is I wasn't able to find an easier way to get the `EntitySearchRepository`... At least, I will rewrite it using a dedicated `@Configuration` bean, and move `BeanFactoryHolder` to its own file (but anyway it will still contain `static` accessor).
- I indeed removed `EntitySearchRepository.delete()` and `EntitySearchRepository.save()` invocations from `delete_template.ejs` and `save_template` (only when both database is sql, and elasticsearch is present) ; I guess that's what you were talking about ?

**Comment by deepu105** [comment]
I think its impossible to get a spring bean in entity listener as its not
managed by spring, I did something similar in the entity audit module and
not proud of that as well. If someone finds a spring way I would adapt that
as well. Btw your beanholder looks better than my implementation

**Comment by lordlothar99** [comment]
I pretty sure few years ago Spring had some kind of `ApplicationContextHolder` or smthg... but anyway, I tried to apply KISS, and I got a new implementation (`BeanFactoryHolder` has been removed), I will update the PR in few minutes

**Comment by lordlothar99** [comment]
Travis build failed because of phantomjs download error ... 
anyway, the PR is ok

**Comment by deepu105** [comment]
ok this looks cleaner than what I was doing :+1:

**Comment by lordlothar99** [comment]
@deepu105 plz tell me if you rebase/merge these commits

**Comment by deepu105** [comment]
@jdubois LGTM plz merge if you are ok

**Comment by lordlothar99** [comment]
I just changed `ElasticSearchUpdater` log level to `INFO`

**Comment by amitjindal** [comment]
@lordlothar99 We did something similar in a project last year. You mentioned `ApplicationContextHolder`. Here's what we did. See if this is of any use for you.

File: `InjectionHelper.java`
```java
@Component
public class InjectionHelper implements ApplicationContextAware {

    private static ApplicationContext applicationContext;

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        InjectionHelper.applicationContext = applicationContext;
    }
    public static <T> T getBean(Class<T> clazz) { return applicationContext.getBean(clazz); }
    public static <T> T getBeanByName(String clazz) { return (T) applicationContext.getBean(clazz); }
}
```

Usage in EntityListener: `ElasticsearchEntityListener.java`
```java
@Component
public class ElasticsearchEntityListener {

    private final Logger log = LoggerFactory.getLogger(ElasticsearchEntityListener.class);

    private static final String CUSTOM_SEARCH_REPOSITORY = "SearchRepository";

    @PostPersist
    public void save(Object entity) {
        Optional<ElasticsearchCrudRepository> repo = getSearchRepository(entity);
        repo.ifPresent(esCrudRepository -> esCrudRepository.save(entity));
        if(!repo.isPresent()) log.warn("Could not save entity '"+entity.getClass().getSimpleName()+"' in elastic search");
    }

    @PostUpdate
    public void update(Object entity){
        Optional<ElasticsearchCrudRepository> repo = getSearchRepository(entity);
        repo.ifPresent(esCrudRepository -> esCrudRepository.save(entity));
        if(!repo.isPresent()) log.warn("Could not update entity '"+entity.getClass().getSimpleName()+"' in elastic search");
    }

    @PostRemove
    public void delete(Object entity) {
        Optional<ElasticsearchCrudRepository> repo = getSearchRepository(entity);
        repo.ifPresent(esCrudRepository -> esCrudRepository.delete(entity));
        if(!repo.isPresent()) log.warn("Could not delete entity '"+entity.getClass().getSimpleName()+"' from elastic search");
    }

    private Optional<ElasticsearchCrudRepository> getSearchRepository(Object entity){
        String searchRepository = entity.getClass().getSimpleName();
        searchRepository = Character.toLowerCase(searchRepository.charAt(0))+searchRepository.substring(1);
        searchRepository = searchRepository + CUSTOM_SEARCH_REPOSITORY;
        ElasticsearchCrudRepository elasticsearchCrudRepository = null;
        try {
            elasticsearchCrudRepository = InjectionHelper.getBeanByName(searchRepository);
        } catch (BeansException e) {
            log.error("Exception getting Elastic Repo: "+ searchRepository, e);
        }
        return Optional.ofNullable(elasticsearchCrudRepository);
    }
}
```

**Comment by gzsombor** [comment]
We had similar EntityListener, with that ugly static global variable to link Spring with hibernate, but we abandoned this approach totally, as we encountered bugs, which caused by that hibernate called the listeners in a state when some of the ids are not initialized yet, so we ended up creating a home-grown 'entity change event listener' called manually.

**Comment by lordlothar99** [comment]
@amitjindal thks, your version is somewhat close to the first I wrote, but as we discussed earlier with @deepu105 , it was decided to avoid the singleton ..
@gzsombor I'm interested in your feedback about bugs, would you plz give us some more details about your implementation and the bugs ?

**Comment by jdubois** [comment]
I guess we could have some synchronization issues between the database and Elasticsearch, so maybe some people would want more control on their code, and thus would prefer the previous approach to this one.
We are too close to JHipster 3.0 to do such a big change, with nearly 20% of our users working with Elasticsearch -> I'd like to postpone this to another version, as this needs discussion and testing

**Comment by lordlothar99** [comment]
Actually I'm using this implementation in several applications and never
had issues so far... But I will add some more stress tests just to ensure
everything's fine, so it will be ready for next version

Le dim. 20 mars 2016 09:13, Julien Dubois <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
ok lets put this on hold then

**Comment by gzsombor** [comment]
@lordlothar99 : Currently I can't find the exact issue in our issue tracker, but if I remember correctly, the problem was that we had a parent-child-grand child entity structure, which we wanted to index into one ParentEntityDocument. The problem was that, in some cases, the entity listener is called before all the entities are persisted and received a valid id - and this was caused a whole bunch of other problems later. It is entirely possible, that our implementation was flawed, and this solution would work correctly, I just want to share our experiences with the EntityListeners.

**Comment by jdubois** [comment]
What I meant by synchronization issues:

- We need to be sure that commit/rollbacks are working the same way for both the database and ES. And as we have no transactions between them, I'm sure there are some cases where the data isn't correct in one of them
- Anyway ES isn't a true data store, so you can have lost or corrupted data with it

So for both cases, maybe some users would like to have something less magical than the listener, so they can control and correct their data manually in case of error. I do this all the time with Cassandra.

**Comment by lordlothar99** [comment]
@gzsombor @jdubois you are right, this kind of problems may be hard to diagnose ..  I will add some tests soon

**Comment by lordlothar99** [comment]
actually, it seems like both implementations (with explicit `EntitySearchRepository.save`, or with `EntityListener`) have same bug : if transaction is committed, no pb. But if transaction is rollbacked, then ES contains data it shouldn't, as ES call is not wrapped in JPA transaction... :/
Actually, this bug is already in current JHipster version... 
I think we could fix that easily with a transaction listener plugged in `ElasticsearchUpdater`, I'm working on it

**Comment by jdubois** [comment]
yes, indeed! But my point is that it's not possible to achieve this correctly, and that anyway ES gives no guarantee to save an entity, so you will always have consistency issues.
That's why some people might want to have more control, so they can correct this manually.

**Comment by lordlothar99** [comment]
I wasn't aware of theses ES limitations...
Anyway I implemented transaction handling in `ElasticSearchUpdater` (only activated in production mode, cause during integration tests, we have assertions on ElasticSearch containing data, and transaction is rollbacked).
And I also added a new `ElasticSearchUpdaterTest`, which might not be added to jhipster as is, but I found interesting to compare both solutions (with/without `ElasticSearchUpdater`). You can notice I deactivated `should_ES_contain_data_after_commit_without_ElasticSearchUpdater`, as this test demonstrates current JHipster issue on ES desynchronization when rollback occur. If I'm not mistaken, with `ElasticSearchUpdater` activated, the issue is fixed (see `should_ES_not_contain_data_after_rollback_with_ElasticSearchUpdater`).
Just let me know if this improvement might be included in next JHipster version or not, so I would cleanup the explicit `EntitySearchRepository.save()` invocations, in order to make this PR mergeable

**Comment by deepu105** [comment]
@lordlothar99 this is on hold and that means wont be part of 3.0 release we can have this on a minor version later on as enhancement

**Comment by deepu105** [comment]
and Thank you for the patience

**Comment by lordlothar99** [comment]
Yes of course , I just wanted to go deeper into this issue cause I'm using this implementation in my project

**Comment by deepu105** [comment]
@jdubois may be we should revisit this. I kind of think this is ok, there might be some edge cases as @gzsombor highlighted but that should only affect very few people and this should be good enough for common cases.

**Comment by deepu105** [comment]
@jdubois @gzsombor so what are we gonna do here, we should either merge or close this.

**Comment by jdubois** [comment]
- I think that's a very smart approach to have ES in sync with the database "magically"
- But I also think this is going to add 2 major issues:
  - There will be sync issues. There is no way to remove them, that's just the way ES works. So in those cases people will not be happy with the "magical" solution as they need to solve those errors manually.
  - Some people will be more happy with the current solution, as they can tune everything. In fact, this is also why we don't do everything "magically" in the REST controllers using Spring Data REST: people want those methods as placeholders, where they can add their business logic.

So I'm sorry but I'm not convinced by this approach in the end. Still, it's very smart, and should be at least documented, or maybe provided as a JHipster Module?

**Comment by deepu105** [comment]
@lordlothar99 we are very sorry that we couldn't merge this. We highly value your contribution and we will atleast want to see this as a module as @jdubois said. Hope you would understand.

If you are interested to make this into a JHipster module so that others can benefit from this, please check this https://jhipster.github.io/modules/creating-a-module/

**Comment by jdubois** [comment]
yes very sorry @lordlothar99 as I really find this is a very smart idea. I'd love to find another solution.

**Comment by lordlothar99** [comment]
hi ! yeah no problem with that !
I had a lookup at the module API, but I first thought it would be quite hard to create a module..
I have to read once again, but I understood it was easy in a module to add some new logic, but not that much if you need to remove already generated stuff. And in that case, I would have to remove already generated `<%= entityInstance %>SearchRepository` invocations :/

**Comment by deepu105** [comment]
you can always do some regex replace magic :) thats what I did in my entity
audit module

Thanks & Regards,
Deepu

On Tue, May 10, 2016 at 11:57 PM, François Lecomte <notifications@github.com

**Comment by lordlothar99** [comment]
ok! I will have a look at that

**Pull request closed without merging**
