### PR TITLE
Use ejs file extension for all templates

### LINKED ISSUE #7147: Suffixing template files to .ejs
##### **Overview of the issue**

generator-jhipster template files are suffixed by their target extensions (ts, html, scss, ...). 
And some IDE recognize the files by their extension: for example, enabling typescript syntax hightlighting and refactoring because the suffix of the file.
Some IDE have some ejs support, but only for files that are suffixed by .ejs (I'm thinking of Intellij, but there are may be other).
It could be nice to benefit from that capacity to contribute to jhipster faster.

##### **Motivation for or Use Case**

More productivity, syntax highlighting, renaming and so on...

##### **Reproduce the error**

Install the Idea ejs plugin and open a generator-jhipster .ts template => everything is red. rename that file suffixing it by ejs (xxx.ts.ejs), and you've nice syntax highligthing on templates \o/

##### **Related issues**

maybe linting

##### **Suggest a Fix**

suffixing every template file by .ejs (and updating their reference), finding a good extension suffix (pre-ejs) for ejs helpers.

##### **JHipster Version(s)**

4.14.0

##### **JHipster configuration**

The impact happens before generating the code!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A
##### **Browsers and Operating System**

Intellij Idea ultimate (from what I know)

- [x ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by deepu105**
Fix #7147 

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by sendilkumarn** [comment]
This will make JHipster as a `js` project right?  😉

**Comment by deepu105** [comment]
Its already a js project, this might make it an ejs project :wink:

**Comment by deepu105** [comment]
@jhipster/developers does anyone have a concern here? I want to merge it as soon as possible to avoid conflicts as it renames all template files

**Comment by jdubois** [comment]
Well actually it's a "Java" project, but who cares anyway, that doesn't make much sense!!
If it works better in IDEs, it's good for me. For the record, I always use Atom to do the templates, as it's not too smart, so I don't have any completion or anything....

**Comment by deepu105** [comment]
Try vscode with the ejs plugin. its much better


Thanks & Regards,
Deepu

**Comment by gmarziou** [comment]
Yes VS Code is good and also switching from ejs to target language on a template is just a matter of a click in the bottom bar.

**Pull request merged**
