### PR TITLE
disable logstash appender during tests

### PR DESCRIPTION
**Pull request by nonomoho**
cc @pascalgrimaud 

fix https://github.com/jhipster/generator-jhipster/issues/10065

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@nonomoho can you please remove the comment also?

**Comment by DanielFran** [comment]
Thanks @nonomoho

**Comment by pascalgrimaud** [comment]
Cassandra build failed, but it's not related to this PR

**Comment by nonomoho** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/9507

**Comment by DanielFran** [comment]
Restarted it 3 times... But not related

**Pull request merged**
