### PR TITLE
fix bower integration for windows os

### PR DESCRIPTION
**Pull request by paul41979**
Fix bower integration on windows OS as otherwise it errors with a CreateProcess error=2 as it can't find file to launch

### CODE REVIEW

**Comment by jdubois** [comment]
ping @atomfrede looks good to you?

**Comment by atomfrede** [comment]
At first glance it looks good. I can test it after work around 7pm after on a windows machine.

**Comment by jdubois** [comment]
@atomfrede no worries, I just released a new version yesterday, I won't do another one until a couple of days!

**Comment by atomfrede** [comment]
:) Just tested it on windows 8.1 (while waiting for docker builds) and it works fine.

**Comment by jdubois** [comment]
OK, I'll probably do a release soon (for another issue), so I'm merging this

**Comment by atomfrede** [comment]
@jdubois There might be the same issue on windows in ``profile_prod.gradle`` for ``grunt``. Will check it tomorrow  when having a windows laptop again.

**Pull request merged**
