### PR TITLE
add duration format filter to clients

### PR DESCRIPTION
**Pull request by atomfrede**
This PR formats durations in ISO format (`PT10H10M10.1S`) as human readable duration in the list screen and the details scene.

For angular and react it uses moment to parse and format the duration.
For vue it uses https://www.npmjs.com/package/duration-fns to parse durations and date-fns to format durations. 
As duration-fns only parses to milliseconds very small durations (e.g. we create via faker) are only zero and the formatting will return nothing. In that case the ISO string is displayed.

Instead of a number field the edit field is now string so you can enter an iso string which seems more fitting imho.

As a small enhancement the font awesome dependencies are aligned and updated.

closes https://github.com/jhipster/generator-jhipster/issues/11862

image

image

image

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Some conflict here, can you solve them plz @atomfrede ?

**Comment by atomfrede** [comment]
Again 😄 sure will do it today

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/24744

**Comment by pascalgrimaud** [comment]
@atomfrede : approved

**Pull request merged**
