### PR TITLE
Redis: use @DynamicPropertySource to set server url in tests

### LINKED ISSUE #11793: Failing redis-related builds
We can see this in the `react-gradle-cassandra-session-redis` builds

```
 AccountResourceIT > testRegisterDuplicateLogin() FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132
        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException at ConstructorResolver.java:798
            Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException at ConstructorResolver.java:798
                Caused by: org.springframework.beans.factory.BeanCreationException at ConstructorResolver.java:656
                    Caused by: org.springframework.beans.BeanInstantiationException at SimpleInstantiationStrategy.java:185
                        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException at ConstructorResolver.java:798
                            Caused by: org.springframework.beans.factory.BeanCreationException at ConstructorResolver.java:656
                                Caused by: org.springframework.beans.BeanInstantiationException at SimpleInstantiationStrategy.java:185
                                    Caused by: java.lang.IllegalArgumentException at RedisURI.java:42
```

I haven't found any related issue, but I may have not notice it

### PR DESCRIPTION
**Pull request by murdos**
Attempt to fixes #11793

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by MathieuAA** [comment]
You rock @murdos

**Comment by MathieuAA** [comment]
Don't forget to claim the bounty :)

**Comment by pascalgrimaud** [comment]
@murdos : I still don't understand why it passed with Maven and not Gradle... do you understand why ?

**Comment by atomfrede** [comment]
Same question for me, as it worked before. Will try the same for neo later.

**Comment by murdos** [comment]
> 
> 
> @murdos : I still don't understand why it passed with Maven and not Gradle... do you understand why ?

Honestly, no I don't understand exactly why. 
I stumbled upon a similar issue while working on https://github.com/jhipster/generator-jhipster/pull/11753 (since Cassandra is always tested in combination with Redis in our CI tests) and this what fixed the issue I had locally. So I cherry picked the change to master when I saw #11793

**Pull request merged**
