### PR TITLE
Remove trailing comma in entity-management.js

### PR DESCRIPTION
**Pull request by cbornet**
This is a sonar blocker !

### CODE REVIEW

**Comment by cbornet** [comment]
@jdubois did you see the semicolon commit when merging. I think I added it at the same time you merged...

**Comment by jdubois** [comment]
Non I only saw one change... not a big deal anyway, is it?

**Comment by deepu105** [comment]
@cbornet the semicolon are also merged

**Comment by deepu105** [comment]
btw for very minor changes you can add [ci skip] on commit message to skip travis

**Pull request merged**
