### PR TITLE
let bower/wiredep install non compass boostrap files

### LINKED ISSUE #970: Let bower/wiredep install non compass boostrap files
At the moment the bootsrap files for a non compass project is included in the template of the generator rather than it is included in the bower.json (where the bootstrap-sass is for some reason included instead). The installation should be made by bower/wiredep.

Fix this issue after the PR of #956 is merged.

### PR DESCRIPTION
**Pull request by andidev**
replace bootstrap-sass bower dependency with regular bootstrap for non compass config
remove bootstrap assets included in the generator template
configure usemin to change relative paths in css to absolute paths
activate minifyCss in gulp build task
update to latest bootstrap version
remove bower_components from usemin html src

fix #970

### CODE REVIEW

**Comment by andidev** [comment]
Before merging this could someone please just confirm that removing the bootstrap assets from 
`app/templates/src/main/webapp/assets/fonts`
and
`app/templates/src/main/webapp/assets/images`

is okey?

Not sure why they exists there as the ones used should be the ones in the `bower_components` directory

**Comment by andidev** [comment]
`java -jar target/jhipster-0.0.1-SNAPSHOT.war --spring.profiles.active=prod`does not work anymore  since the bootstrap font assets missing from the asset direcotry
screen shot 2015-01-19 at 16 10 07

**Comment by gmarziou** [comment]
@andidev the glyphicon font location is also an issue when customizing bootstrap because the custom SASS partial is located under scss folder and  so in my project I had to change the default value of $icon-font-path as this:

~~~ sass
$icon-font-path: if($bootstrap-sass-asset-helper, "bootstrap/", "../../bower_components/bootstrap-sass/assets/fonts/bootstrap/") !default;
~~~ 

It works in dev but I'm not sure it will work in prod, I have to test it.

**Comment by andidev** [comment]
Thanks @gmarziou, it would be nice to document it.

I'm getting a bit confused now. When I test it now it seems to work in production mode when using the following in main.scss
```
$icon-font-path: "../../bower_components/bootstrap-sass/vendor/assets/fonts/bootstrap/";
```
something is fishy here. I think I need to structure my test.

**Comment by gmarziou** [comment]
I'll do more testing tomorrow.
By the way, I updated bootstrap-sass to 3.3.1 and had to remove `vendor' from the bower components assets folder.

**Comment by andidev** [comment]
Sorry no idea.

**Comment by andidev** [comment]
After doing som digging a can confirm that there seems to be one more problem before this PR can be merged.
The `concat` task that concatenates all css files into one large file does not change the relative paths of static resources. This is why the bootstrap glyphicon font is not found when running the app in production mode.

The solution seems to be to stop using the `concat` task and let the `cssmin` task handle the concatenation. ref https://github.com/yeoman/grunt-usemin/issues/225

**Comment by jdubois** [comment]
Concerning the Bootstrap version: it's just that we didn't upgrade, so if you have time to test, please upgrade to the latest available version!

**Comment by andidev** [comment]
Okey I'll do so after I got everything working. One major benefit from this change is going to be that updating boostrap veriosn will be alot more easier for the non compass version. No need to copy assets since the assets from bower_components will be used. Simply just update the version in bower.json.

**Comment by andidev** [comment]
Finally this feels bugfree and safe to merge

tested configurations:
jhipster default config
jhipster compass
jhipster gulp
jhipster gulp compass

test done:
grunt serve
gulp serve
mvn spring-boot:run -Pprod

**Comment by amr** [comment]
I just tested this nice PR with gulp + compass and it works fine.

**Pull request merged**
