### PR TITLE
GitHub Actions: split Angular and React builds

### PR DESCRIPTION
**Pull request by pascalgrimaud**
As the builds for React are too flacky, compared to Angular, I prefer to split them.
So it will be easier to restart only React builds.

_____

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I'm merging this to help the other next PR

**Comment by vishal423** [comment]
@pascalgrimaud, we can plan to move all `react` builds to azure devops as that supports the restart of an individual job on demand.

**Comment by pascalgrimaud** [comment]
Yes, why not. It could be a temporary solution...

But the real solution is to fix the flacky protractor tests with React, similar to what we did with Vue.js but I know it will require a lot of work. 

I'd like to open a specific ticket for this, with all details and with a big bounty as it's a lot of work to solve all these flacky tests...

**Comment by vishal423** [comment]
I think we can leverage most of code from `vue`, however, if we plan to move to `cypress`, we shouldn't spend more effort on this.

**Pull request merged**
