### PR TITLE
Update spring-boot version to 2.1.8 and dependencies

### PR DESCRIPTION
**Pull request by DanielFran**
Depends on https://github.com/jhipster/jhipster/pull/396

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
Waiting that maven servers are updated. This seems impacting only Travis pipeline!?!
@pascalgrimaud Is this again an issue with Travis cache?

**Comment by pascalgrimaud** [comment]
@DanielFran : Honestly I don't know. I don't understand why the cache system with Travis would be a problem here... I'll try to find time to investigate

**Comment by DanielFran** [comment]
@pascalgrimaud it is very strange that only on Travis side it did not found the dependencies....

**Comment by pascalgrimaud** [comment]
I don't think it won't change anything by restarting.
I need to checkout your branch, and debug our CI scripts to see what lib we have inside our m2 folder.

**Comment by pascalgrimaud** [comment]
The error in your builds is:

```
[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  1.208 s

[INFO] Finished at: 2019-09-08T23:30:06+10:00

[INFO] ------------------------------------------------------------------------

[ERROR] Plugin org.springframework.boot:spring-boot-maven-plugin:2.1.8.RELEASE or one of its dependencies could not be resolved: Failure to find org.springframework.boot:spring-boot-maven-plugin:jar:2.1.8.RELEASE in https://maven-central.storage-download.googleapis.com/repos/central/data/ was cached in the local repository, resolution will not be reattempted until the update interval of google-maven-central has elapsed or updates are forced -> [Help 1]
```

If I tried to do a fresh branch and fresh build, there is no problem... so something related to the cache system in Travis

**Comment by DanielFran** [comment]
@pascalgrimaud Yes thats what I thought! Locally and in Azure everything is OK.

If you remember, this is not the 1st time it happens...

**Comment by pascalgrimaud** [comment]
Just delete the cache PR.10351 on Travis, then I restarted your build
Let's see...

**Comment by DanielFran** [comment]
@pascalgrimaud It seems OK now, the errors are now related with the e2e tests, so it seems we can merge this now.

**Comment by pascalgrimaud** [comment]
The PR for fixing e2e is done: https://github.com/jhipster/generator-jhipster/pull/10375

**Comment by DanielFran** [comment]
@pascalgrimaud Confirmed e2e tests are OK now in Travis, just waiting for Azure to merge it.

**Comment by pascalgrimaud** [comment]
yes, it can be merged once CI passed

**Pull request merged**
