### PR TITLE
Workaround npm bug.

### PR DESCRIPTION
**Pull request by mshima**
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by DanielFran** [comment]
@mshima Can we merge it temporally so we can proceed with other updates?

**Comment by mshima** [comment]
@DanielFran sure. I couldn’t identify the microservice error yet.

**Comment by DanielFran** [comment]
@mshima I relaunch JDL tests, but it did not show what error was on CI

**Comment by mshima** [comment]
> @mshima I relaunch JDL tests, but it did not show what error was on CI

Yep, I couldn’t reproduce locally

**Comment by mshima** [comment]
I got the log from https://github.com/jhipster/generator-jhipster/runs/2632960371.

Looks like an infinite recursion.

**Comment by mshima** [comment]
@DanielFran done.

**Comment by DanielFran** [comment]
Thanks @mshima closed/reopen PRs to test it...

**Pull request merged**
