### PR TITLE
prevent leakage of technical details trough problem message

### LINKED ISSUE #12051: Exception Handling: Leakage of Implementation Details
##### **Overview of the issue**

Some exceptions trigger a leakage of implementation details to the end user. The example shown here relates to Jackson's exception details, but maybe there are other examples that I am not aware of.

##### **Motivation for or Use Case**

We recently underwent security testing -- one of the issues that was caught is that certain exceptions leak inside information. An example is shown below.

##### **Reproduce the error**

Use a malformed JSON request body.

Example Request

```
GET /auth/login

35 {"username":"asd","password":"asd","rememberMe":true} 1
Z
Q
```

Example Response

```json
{
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "Bad Request",
    "status": 400,
    "detail": "JSON parse error: Cannot deserialize instance of 
       `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` out of VALUE_NUMBER_INT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` 
       out of VALUE_NUMBER_INT token\n at [Source: (PushbackInputStream); line: 1, column: 1]", 
    "path": "/auth/login",
    "message": "error.http.400"
}
```

As can be seen above, the error message discloses internal details that could help an attacker understand the system's vulnerabilities better.

In this case, "The input is not valid JSON: expecting a JSON object but found a number instead." is a better message because it better communicates the error without disclosing any implementation details. However, if it is too complicated to implement such detailed error messages, we should simply say that the JSON is malformed (this is what I have done, as I am not familiar enough with Jackson to go any further).

##### **Suggest a Fix**

It is easy to fix this particular exception (I have done so on my end, using if statements in `ExceptionTranslator#process(...)`).

However, there may be other examples that I am not aware. If you have any examples in mind, please comment below or create a new issue!

##### **JHipster Version(s)**

Reproduced on both 6.7.1 Gateway and 6.9.1 micro-service. I haven't seen a fix in recent versions' change logs; correct me if I am wrong.

##### **JHipster configuration**

  <details>
  <summary>.yo-rc</summary>
  <pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.***.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.nxtsens.backend.gateway",
    "packageFolder": "com/nxtsens/backend/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": ["cucumber"],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "clientTheme": "none",
    "blueprints": [],
    "embeddableLaunchScript": false,
    "creationTimestamp": 1579029215188
  }
}
  </pre>
  </details>

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by atomfrede**
This prevents leaking of technical details via the problem message which is by default filled with the message of the exception. Most often the message contain/reveal technical details which should not be leak via an api call to the caller.

closes #12051

**This targets v6.x branch on purpose. I think this should be backported as it impacts security.**

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by AlexandreCassagne** [comment]
This is something I have manually added to my stack. I can confirm it does the job!

**Comment by atomfrede** [comment]
@pascalgrimaud Any idea why some builds are stuck forever? I have seen a similar effect here https://github.com/jhipster/generator-jhipster-micronaut/pull/125

**Comment by pascalgrimaud** [comment]
@avdev4j reported it to me, the last days too.
I think the problem comes from GitHub: we have too much builds in our pipelines, so we must reduce the number of builds. The only way to solve it is to restart the build.

**Comment by avdev4j** [comment]
I confirm, the only solution I found is to restart workflows by workflows without trying to restart them all at the same time.

**Comment by atomfrede** [comment]
Good for this one, the gradle wrapper validation will be fine :)

**Comment by atomfrede** [comment]
Here is the PR for the documentation update https://github.com/jhipster/jhipster.github.io/pull/990

**Pull request merged**
