### PR TITLE
Enhancements for Kubernetes Generator

### PR DESCRIPTION
**Pull request by saturnism**
For #10352 

 * Can choose between NGINX or GKE Ingress Type
 * For GKE Ingress, allow empty domain name, since it's not necessary
 * When using Istio, skip Ingress selection and default to Istio Ingress w/ Gateway generation
 * When using Istio, try to determine the Istio ingress IP, and default it as the Ingress domain

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@saturnism : FYI, I pushed directly to your branch to fix the npm test

**Comment by saturnism** [comment]
Thank you! I was wondering what was going on ;)

**Comment by saturnism** [comment]
/ping @srinivasa-vasu to take a look, thanks!

**Comment by saturnism** [comment]
thnx @PierreBesson !!

**Comment by deepu105** [comment]
Cool. I'll clean this up a little and add support in JDL

**Pull request merged**
