### PR TITLE
Remove spring-data-cassandra and upgrade to datastax driver v3

### PR DESCRIPTION
**Pull request by cbornet**
See #3548 

Also add protocolVersion to cluster settings
Also export the driver metrics.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@cbornet : can you rebase, for npm test with uaa working

**Comment by cbornet** [comment]
Can someone review. Especially the microservice part.

**Comment by jdubois** [comment]
I'm having a look at it.
@cbornet @raphaelbrugier can you have a look at also updating http://jhipster.github.io/using-cassandra/

**Comment by raphaelbrugier** [comment]
Great work @cbornet!
Yes I'll update the page to explains about the auto-migration.

**Comment by jdubois** [comment]
OK and I'll merge the documentation when the release is done (so the documentation matches the code)

**Comment by jdubois** [comment]
@cbornet I'm still have `protocolVersion: V2` in application-dev.yml and application-prod.yml, is that normal?

**Comment by jdubois** [comment]
@raphaelbrugier I've also seen http://jhipster.github.io/docker-compose/#4 but I'm unable to have this working with Docker, and anyway it should work out of the box with the default config, so there's something to improve here

**Comment by cbornet** [comment]
Yes, I didn't upgrade the docker cassandra.
I was thinking of doing that in a second step

**Comment by jdubois** [comment]
Oh sorry that's logical then!

**Comment by raphaelbrugier** [comment]
@jdubois When you said `it should work out of the box with the default config` you were using this branch code right? It should work out of the box with the v3.2.1
Let me know if it doesn't.

**Comment by jdubois** [comment]
@raphaelbrugier yes I'm using your code, but I started Cassandra with Docker and as @cbornet said this was not working yet...
I've installed it manually and:

- I had to switch the protocol to "V4" (see my earlier comment on that)
- The schema isn't automatically created (it is with Docker, but you could also run the create_keyspace.cql script automatically)

**Comment by jdubois** [comment]
@cbornet this is also causing issues with microservices, this is a classpath error as both Cassandra and Netflix Eureka use the same Apache Commons lib:

    java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.<init>(I)V

**Comment by cbornet** [comment]
Regarding Datastax Enterprise, do we still try to follow it ?
In that case, maybe we should use:
* cassandra-driver-dse:3.0.0.rc1
* cassandra v2.1.14

Note that currently, our docker config spawns a cassandra 2.2

Regarding Cassandra v3, you indeed need to use protocol v4

As for the lib conflict, aouch ! @jdubois any idea to overcome this issue ? Excluding org.apache.commons from one of the libs ?

**Comment by jdubois** [comment]
- yes the Docker config should also be updated
- I would use Apache Cassandra, but the same version as the latest DataStax version
- For the version conflict, we must check if there is a version working for both...

**Comment by jdubois** [comment]
For the version conflict, you must remove commons-codec from Cassandra Unit:

    <dependency>
            <groupId>org.cassandraunit</groupId>
            <artifactId>cassandra-unit-spring</artifactId>
            <version>3.0.0.1</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-codec</groupId>
                    <artifactId>commons-codec</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

Still there are 3 big issues here:

- This dependency has the "test" scope, so this shouldn't happen at all
- Now the microservice get registered into the Registry, but it has the "DOWN" status, so something else is wrong
- When I generate the front-end code on the gateway, it doesn't work: it seems that it is because we don't have pagination working. Anyway nothing is generated, so that's totally buggy.

**Comment by cbornet** [comment]
@jdubois would you share your gateway and microservice config ? I'll have a look.

**Comment by pascalgrimaud** [comment]
Bad news!!
I thought the problem with "Down" https://github.com/jhipster/generator-jhipster/issues/3428 was resolved here 
https://github.com/jhipster/generator-jhipster/pull/3469

**Comment by cbornet** [comment]
The driver does indeed use netty so it may be related.
@jdubois do you get the same error as in #3428 ?

As for the pagination issue, you mean pagination on a cassandra entity ? This shouldn't be possible.

**Comment by jdubois** [comment]
@cbornet no I don't think it's the same error as #3428
For the pagination, I haven't checked recently, but originally I coded pagination with "pager" and "infinite scroll" for Cassandra (as you shouldn't make count(), you can't have the "pagination links"). So yes this is supposed to work, but it's currently broken.
You can test my sample project [here](https://www.dropbox.com/s/sw692j6xzm3072u/tmp-microservices2.zip?dl=0)

**Comment by jdubois** [comment]
@raphaelbrugier I haven't checked your code but I have a big doubt that your changelogs can work correctly:

- Liquibase works because it does a transaction and locks a table, which is something you can't do with Cassandra (maybe with Paxos??)
- The problem is that you could launch 10 concurrent instances of one service, so they will all try to update the database schema: with Liquibase, the first one which gets the lock does the update, and the others wait, and then don't need to do the update... I don't think this could work for Cassandra, at least not easily: have you checked this use-case?

**Comment by raphaelbrugier** [comment]
#3469 and #3428 were not related to the DOWN flag in the registry but to the warning message displayed in the console when starting the service. At that point the service ran well, I don't remember seeing something wrong in the registry.

@jdubois:
- yes this is __not__ transactional, but the row in the schema_version table is only inserted after the script from the changelog folder is run with success.
 - So we can assume in worst case the row in schema_version is not inserted and the cql script will be run again next time.
- I'm not following you here. The service (the app) is not doing the actual migration. It's done in a separated docker container, dedicated to run the migration script.
 - good thing is this ensure there are not multiple concurrent migrations launched 
 - bad thing is it only works with docker or by manually launching the script

But it's common to have the migration launched by the deployment tool rather than the app itself.

**Comment by jdubois** [comment]
@raphaelbrugier OK I need to check in detail how it works. It's OK for me if it only works with Docker and/or manually, it's more complex to handle than for an SQL database.
The idea with JHipster is that it's all automatic, that's how it works with Liquibase: not everybody will like this, of course, but it's a lot easier and faster

**Comment by raphaelbrugier** [comment]
We agree then.
As you said, I don't think we can have the same level of automation as for an SQL database.
But relying on docker really simplifies the problem.
You can even launch the docker container locally but pointing to a remote (prod?) cluster to execute the migration.

**Comment by pascalgrimaud** [comment]
The automigration didn't work for cassandra microservice.
I saw it with this log:
```
mscassandra-cassandra-migration    | <stdin>:1:InvalidRequest: code=2200 [Invalid query] message="unconfigured table schema_version"
```
It's because we use 'copy' instead of 'template', so the create-table.cql was empty

**Comment by cbornet** [comment]
I have a hard time testing a full microservice setup on my lame HW. Can someone check the DOWN issue ?
@jdubois if you rollback the driver version, does it work ?

**Comment by pascalgrimaud** [comment]
I confirm the "down" issue on the current master. It's not related to your
PR, @cbornet
Le 11 mai 2016 8:34 AM, "Christophe Bornet" <notifications@github.com> a
écrit :

**Comment by cbornet** [comment]
@pascalgrimaud can you open an issue for the down problem ?

**Comment by pascalgrimaud** [comment]
Yes, as soon as I retry and get the logs, I will open this issue

**Comment by jdubois** [comment]
I'm testing with the current master, and there is currently a bug -> the Docker image doesn't match the Spring Data Cassandra provided driver version.
So both the marster and this PR seem broken :-(

@raphaelbrugier do you have time to validate this PR? I would like it to work:

- on monoliths
- gateways -> have a look at the rate limiting feature
- microservices

I'm going to work on the "DOWN" issue

**Comment by jdubois** [comment]
- I corrected the "commons-codec" issue, and as the current master is broken with Docker, I'm merging this -> as long as it's better than the current code, let's merge!
- @raphaelbrugier can you add some documentation on http://jhipster.github.io/using-cassandra/ ? This isn't obvious, I tried to write something but that's not enough
- @raphaelbrugier with Docker there are lots of error by default because of the 2 nodes -> could you look for a solution? At least catch the errors and document. For a new user the first impression wouldn't be good.
- I'll work on the "down" issue

**Comment by raphaelbrugier** [comment]
Hi,

Yes @jdubois I will work on that:
- update the doc
- prepare a PR to move the create-tables.cql file to the changelog
- test all of this with mono/micro app

@jdubois could you please open an issue or mail me the error message about the problem with a 2nd node?
I've ran into something that sounds similar on my initial setup for tatami and it was because of Docker running inside a VM on OS/X. But since I've configured my laptop I don't see any error anymore with multiple nodes on a Cassandra>Docker cluster.

**Comment by jdubois** [comment]
@raphaelbrugier the error is because the second node has an internal Docker IP:

    2016-05-12 16:47:54.238 DEBUG 6660 --- [uster1-worker-0] com.datastax.driver.core.Host.STATES     : [/172.18.0.3:9042] starting reconnection attempt
    2016-05-12 16:47:54.240  WARN 6660 --- [r1-nio-worker-2] com.datastax.driver.core.Session         : Error creating pool to /172.18.0.3:9042
      com.datastax.driver.core.exceptions.ConnectionException: [/172.18.0.3] Pool was closed during initialization
	at com.datastax.driver.core.HostConnectionPool$2.onSuccess(HostConnectionPool.java:149)

**Comment by raphaelbrugier** [comment]
@jdubois Yes it's the same issue then.
I've documented it on the [docker-compose page](https://github.com/jhipster/jhipster.github.io/blob/master/pages/docker_compose.md#note-for-non-linux-users):

> Cassandra nodes : Because Cassandra nodes are also hosted in the Virtual machine, the Cassandra Java driver will receive an error when trying to contact them after receiving their address from the contact point. To workaround this, you can add a routing rule to your routing table, (source).
> 
> Assuming the containers running the Cassandra nodes have IP address 172.18.0.x:
> 
>  `sudo route -n add 172.18.0.0/16 `docker-machine ip default`

Could you please try this and tell me if it works for you?

Do you think it will be more visible if I move this to the documentation page dedicated to C* ?

**Comment by jdubois** [comment]
Sorry @raphaelbrugier I won't have the time to test, but I'm pretty sure this is the issue, and you can easily reproduce it.

- Yes I've seen your documentation, but it's a bit hidden
- My main problem is that everything is done with JHipster so that it works "out of the box" -> isn't there a solution for this? Like forbidding to connect to that node? To be honest I haven't understood why you need it, yet. If there is no other solution, you could also catch the exception and print a specific log message, pointing to the documentation.

**Comment by raphaelbrugier** [comment]
Ok, np.

I prefer to open a new issue so we can discuss the options there.

**Comment by cbornet** [comment]
@jdubois as for pagination, I confirm that it is currently disabled for cassandra : https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L1315

**Comment by jdubois** [comment]
yes I noticed this @cbornet -> it's probably just me lacking time, because that was meant to work. The only option that should not be implemented is the "pagination links" as you shouldn't do a count() with Cassandra, but the other options should be OK.

**Pull request merged**
