### PR TITLE
WIP - update password reset page to use only react-form capabilities

### PR DESCRIPTION
**Pull request by Tcharl**
need discussion.

Updates standard forms to use wrapped leaf element instead of a form wrapper.

Pro:
 - let the user mix his own components with JH wrapped elements
 - compatible with latest react version (which forbids the use of useState and useEffect within a lib from what I've tested)
 - use something that he better knows to use
 - No need to maintain the react-jhipster forms code which is a bit... difficult to understand

Con:
 - 4 more lines by form entry

To use in combination with https://github.com/jhipster/react-jhipster/pull/87

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by Tcharl** [comment]
@deepu105 @mshima what do you think about this one? A little bit easier to understand than the reflection-intensive former library IMO, but I wanted to know your opinion before going guther

**Comment by mshima** [comment]
I’m not react expert, but looks like it will make react-jhipster more generic and reusable.

**Comment by hide212131** [comment]
I'm hopeful for the resolution of this PR.
To contribute, even in a small way, I have rebased @Tcharl's branches (generator-jhipster, react-jhipster) with the latest main branch and fixed several issues. (I understand that, as they are in the Draft phase, implementations are still underway except for textinput.)
Would it be possible to move forward with this PR?
I would be delighted to apply this solution to the entity's update page once this issue is resolved.

**Comment by DanielFran** [comment]
Please go ahead with a new PR if needed

**Pull request closed without merging**
