### PR TITLE
Enable webpack cache at production builds for react and vue.

### PR DESCRIPTION
**Pull request by mshima**
Related to https://github.com/jhipster/generator-jhipster/issues/14566.

Reduces React and Vue builds by ~1m.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by deepu105 — COMMENTED** [review]
I'm a bit worried about enabling cache for prod TBH. Shouldn't prod builds be as clean as possible? if we are doing this for prod, we should make every attempt to make sure all latest code gets in by enabling a postInstall cleanup of cache as recommended in webpack docs and by making sure all tips/warning [here](https://webpack.js.org/configuration/other-options/#cache) are considered

**Comment by mshima** [comment]
@deepu105 I haven’t enabled on purpose when I introduced the filesystem cache. But we are already using up-2-date at gradle and a custom maven implementation https://github.com/jhipster/generator-jhipster/pull/14799.

IMO is better a webpack solution than the alternative.

**Comment by deepu105** [comment]
I didnt realize we had it or prod builds with maven/gradle

**Comment by vishal423** [comment]
Just to be clear, maven caching of webpack profile tasks does not apply to production build. If you do see that's being applied, then, do raise an issue and I will handle that out.

**Comment by mshima** [comment]
It's right. The only dev.
Anyway seems safe to me.
The caching structure is stored at `target/webpack' and maven removes `target/class/static`.

**Comment by atomfrede** [comment]
> Just to be clear, maven caching of webpack profile tasks does not apply to production build. If you do see that's being applied, then, do raise an issue and I will handle that out.

Same for gradle. On purpose that task is not configured to be cacheable or up-2-date. Is is always executed regardless of the previous build.

**Review by atomfrede — APPROVED** [review]

**Pull request merged**
