### PR TITLE
Implement e2e at cicd generator.

### PR DESCRIPTION
**Pull request by mshima**
Related to https://github.com/jhipster/generator-jhipster/issues/12489.

- Not tested
- The missing ci is gitlab, the implementation is quite different.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I'd prefer to have one additional question in the CI/CD sub generator. Is it possible ?
The question won't be there for GitLab CI / Jenkins, as it depends too much on the environment.
And by default, we won't generate e2e tests.

The main reason is because it won't work out of the box for Gateway:
- the gateway needs other microservices
So we could add a warning when the user selected e2e tests for Gateway

What do you think?

**Comment by mshima** [comment]
> What do you think?

Yes you are right, we should disable e2e for gateway.
Omit or comment?

**Comment by pascalgrimaud** [comment]
Good idea for putting it in comment !
In this case, no need to add a new question

Can you add this in comment too for GitLab CI and Jenkinsfile ?
So the user will have the model to update this part, if he really wants e2e

**Comment by mshima** [comment]
I will change that.
I haven't implemented GitLab, is currently implemented in sections, needs more expertise or time.

**Pull request merged**
