### PR TITLE
Add microfrontend support to jdl.

### PR DESCRIPTION
**Pull request by mshima**
Should be used like:
```
microfrontends [blog, notification, store]
```

Related to https://github.com/jhipster/generator-jhipster/issues/17031.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
@mraible `applicationIndex` is used to increase the port number but I'm sure it is a good name.
Do you have a suggestion?

**Comment by mraible** [comment]
I do admit that this is kinda confusing:

```
microfrontends [blog:1, notification:2, store:3]
```

Currently, you just have to add `clientFramework` to a microservice to invoke microfrontends. Is this making that more strict or is it just an enhancement for validation?

If the number is just to indicate the port, I'd opt to specify the full port like we do for the backend and have something like:

```
microfrontends [blog:9000, notification:9001, store:9002]
```

Or don't make people specify a port and it'll default to ^^.

```
microfrontends [blog, notification, store]
# is ^^ the same as `microfrontends *`?
```

**Comment by mshima** [comment]
> Currently, you just have to add `clientFramework` to a microservice to invoke microfrontends. Is this making that more strict or is it just an enhancement for validation?

I am trying to decouple gateway generation from microfrontend generation.
They can have their own jdl and be generated independently.

> If the number is just to indicate the port, I'd opt to specify the full port like we do for the backend and have something like:
> 
> ```
> microfrontends [blog:9000, notification:9001, store:9002]
> ```

Something like `applicationIndex` would allow to increase every port (`serverPort`, `devServerPort`, `browserSyncPort`).
I will try to find another approach.

**Comment by mshima** [comment]
@mraible the microfrontend port is required for cors at development time.
There are 3 approaches:
- current one passing applicationIndex or the development port. `micronfrontend:1` or `microfrontend:9001`
- allowing ports 9000, (9001 … 9000 + microfrontends.length)
- Adding a jdl config like `microfrotendsDevPorts [9001, 9002, 9003]`.

IMO this looks to small to have a config (option 3).
Maybe we should go with option 3 so we don’t need the add the `:1` at the microfrontend. And add an observation to generated README.

**Comment by mraible** [comment]
@mshima I think the most important thing is to start with _something_. We can always improve it later. I can do a Twitter poll too if you think it'd help.

**Comment by mshima** [comment]
Removed https://github.com/jhipster/generator-jhipster/issues/18200 implementation, related to https://github.com/jhipster/generator-jhipster/pull/18470.

@mraible I've added 9 ports for cors reserved to microfrontends so we can keep the microfrontend ports out of generation process.

**Comment by mraible** [comment]
@mshima How should I modify [`reactive-mf.jdl`](https://github.com/jhipster/jdl-samples/blob/main/reactive-mf.jdl) to test this PR?

**Comment by mraible** [comment]
Tried it with the updated `reactive-mf.jdl`:

1. Started all dependent Docker containers
2. Started all apps with `./gradlew`
3. Ran `npm run e2e` in gateway

```
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  administration/administration.spec.      00:43        5        4        1        -        - │
  │    ts                                                                                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:43        5        4        1        -        -
```

If I run `npm run e2e` in the blog directory, it fails on Swagger too.

```
  1 failing

  1) /admin
       /docs
         should load the page:
     AssertionError: Timed out retrying after 4000ms: expected '<div#swagger-ui>' to be 'visible'

This element `<div#swagger-ui>` is not visible because it has an effective width and height of: `1118 x 0` pixels.
      at Context.eval (http://localhost:8080/__cypress/tests?p=src/test/javascript/cypress/integration/administration/administration.spec.ts:330:132)
```

It could be caused by my M1.

**Comment by mshima** [comment]
JHipster registry is not returning its open api specification and making swagger cypress test to fail.
Added a timeout to wait to missing endpoints to resolve.

**Comment by mraible** [comment]
I tested again this evening on my Intel Mac and everything works as expected! ✅ 

Is there a way to run all the e2e tests when using microfrontends? I ran `npm run e2e` in each project and they all passed.

**Review by mraible — APPROVED** [review]

**Pull request merged**
