### PR TITLE
Replace heroku elasticsearch addon with bonsai

### PR DESCRIPTION
**Pull request by jkutner**
This supports @mraible's changes in https://github.com/jhipster/generator-jhipster/issues/7810

### CODE REVIEW

**Comment by mraible** [comment]
@jkutner Should I do the migration to Jest in a separate PR?

**Comment by jkutner** [comment]
@mraible i would said yes, and we can merge this first (since it doesn't break anything).

**Comment by mraible** [comment]
FYI, I got an email this afternoon from Bonsai saying the following:

```
The usage for your Bonsai cluster, health-by-points-3 has exceeded the limits for its Sandbox ($0/mo) plan.

* Shards: Using 10 out of 6 shards (167% of limit).

What's next?

Your action is required in order to ensure continuity of service and avoid interruption to your cluster traffic. Please upgrade to the appropriate plan, or reduce your cluster's usage to bring it within its current plan's limits.

...

In order to avoid service interruption, please upgrade your plan or modify your usage before Thursday, August 30. If you are still over your limits past that date, your cluster will be placed into read-only mode. Searches will continue to work, and existing data can be deleted to make room, but any new data will not be indexed.
```

I only generated three entities in my project. It looks like it's $10/month to support 10 shards, which seems reasonable.

https://elements.heroku.com/addons/bonsai

**Comment by jdubois** [comment]
@mraible at first I wanted to have sample applications working for free, but it is totally reasonable that if you select this kind of third-party tools (which cost a lot of $$$ to host), you need to pay for something.

**Pull request merged**
