### PR TITLE
microservice+OAuth2: Prevent NPE when user-info doesn't have 'groups' attribute

### LINKED ISSUE #13944: Reactive Gateway + Microservice MVC + OAuth2
##### **Overview of the issue**

Currently, a Reactive Gateway can't communicate with a Microservice MVC, if we use OAuth2.
It works well with JWT.

##### **Motivation for or Use Case**

Our Microservices stack should work.

##### **Reproduce the error**

- generate a Microservice MVC, with Entities
- generate a Reactive Gateway with Entities
- start all
- try to access to the microservice

Or you can use this JDL:

```
application {
 config {
   baseName store
   applicationType gateway
   packageName io.github.pascalgrimaud.store
   serviceDiscoveryType eureka
   authenticationType oauth2
   prodDatabaseType postgresql
   cacheProvider hazelcast
   buildTool maven
   clientFramework angularX
   testFrameworks [cypress]
   reactive true
 }
 entities *
}

application {
 config {
   baseName crm
   applicationType microservice
   packageName io.github.pascalgrimaud.crm
   serviceDiscoveryType eureka
   authenticationType oauth2
   prodDatabaseType mysql
   buildTool maven
   serverPort 8081
   reactive false
 }
 entities *
}

entity Product {
   name String required
   description String
   price BigDecimal required min(0)
   size Size required
   image ImageBlob
}
enum Size {
   S, M, L, XL, XXL
}
entity Customer {
   firstName String required
   lastName String required
   gender Gender required
   email String required pattern(/[a-z0-9._+-]{1,20}@[a-z0-9]{3,15}\.[a-z]{2,4}/)
   phone String required
   addressLine1 String required
   addressLine2 String
   city String required
   country String required
}
enum Gender {
   MALE, FEMALE, OTHER
}
entity ProductOrder {
   placedDate Instant required
   status OrderStatus required
   code String required
   invoiceId String
}
enum OrderStatus {
   COMPLETED, PENDING, CANCELLED
}
entity OrderItem {
   quantity Integer required min(0)
   totalPrice BigDecimal required min(0)
   status OrderItemStatus required
}
enum OrderItemStatus {
   AVAILABLE, OUT_OF_STOCK, BACK_ORDER
}
relationship ManyToOne {
OrderItem{product(name) required} to Product
}
relationship OneToMany {
  Customer{order} to ProductOrder{customer(email) required},
  ProductOrder{orderItem} to OrderItem{order(code) required}
}

service Product, Customer, ProductOrder, OrderItem with serviceClass
paginate Product, Customer, ProductOrder, OrderItem with pagination

/* Entities for Invoice microservice */
entity Invoice {
   code String required
   date Instant required
   details String
   status InvoiceStatus required
   paymentMethod PaymentMethod required
   paymentDate Instant required
   paymentAmount BigDecimal required
}
enum InvoiceStatus {
   PAID, ISSUED, CANCELLED
}
entity Shipment {
   trackingCode String
   date Instant required
   details String
}
enum PaymentMethod {
   CREDIT_CARD, CASH_ON_DELIVERY, PAYPAL
}
relationship OneToMany {
   Invoice{shipment} to Shipment{invoice(code) required}
}
service Invoice, Shipment with serviceClass
paginate Invoice, Shipment with pagination
microservice Customer, Product, ProductOrder, OrderItem, Invoice, Shipment with crm

// will be created under 'docker-compose' folder
deployment {
   deploymentType docker-compose
   appsFolders [store, crm]
   dockerRepositoryName "pascalgrimaud"
   monitoring no
   serviceDiscoveryType eureka
}
```

##### **Related issues**

Following https://github.com/jhipster/generator-jhipster/issues/13855

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by murdos**
Attempt to fix #13944
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by murdos** [comment]
@pascalgrimaud : I would like to test this branch on jhipster-daily-builds, by manually triggering related workflows, but I don't see how.
I don't see any manual action as described [here](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/): am I missing some privileges on this repository?

**Comment by pascalgrimaud** [comment]
I added you to Daily builds team, tell me if it doesn't work

**Comment by pascalgrimaud** [comment]
But I think you need this code before: https://github.com/jhipster/generator-jhipster/pull/13945

Otherwise, the Daily builds will generate default Gateway without Reactive, and will use Zuul+Ribbon which are broken

**Comment by pascalgrimaud** [comment]
Just tested locally the merge of my gateway-reactive branch and this one
It seems to fix all our microservices stack !!!
I'm merging both branch and restart manually all daily builds

**Comment by pascalgrimaud** [comment]
@murdos : could we have a unit test for that?

**Comment by murdos** [comment]
@pascalgrimaud : sure, I'll add one

**Comment by murdos** [comment]
> I added you to Daily builds team, tell me if it doesn't work

It works now, thanks!

> @murdos : could we have a unit test for that?

Done with this PR: https://github.com/jhipster/generator-jhipster/pull/14011

**Comment by murdos** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/43712

**Comment by pascalgrimaud** [comment]
@murdos : approved

**Pull request merged**
