### PR TITLE
Refactor AccountResource, UserResource and EntityResource to use Problem

### PR DESCRIPTION
**Pull request by cbornet**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Throw `Problem` exceptions that will be treated by the `ExceptionTranslator` instead of returning `ResponseEntity` with an unchecked body
See #6404

### CODE REVIEW

**Comment by jdubois** [comment]
LGTM - as this is quite big, does anybody has any comment on this, before merging it?

**Comment by mraible** [comment]
I'd love to get https://github.com/jhipster/generator-jhipster/pull/6361 in first since this touches AccountResource and UserResource quite a bit too. I think it's close to complete.

**Comment by jdubois** [comment]
You are right @mraible - your PR is top priority as it's really a huge work

**Comment by jdubois** [comment]
@cbornet so of course we broke your code, but I don't think it's that bad -> WDYT?

**Comment by cbornet** [comment]
I'll have a look. Shouldn't be too hard

**Comment by cbornet** [comment]
Rebased

**Comment by jdubois** [comment]
You still have a conflict :-P

**Comment by cbornet** [comment]
Yeah, that happens when pushing muliple related PRs 😄 . Not a big deal.

**Comment by cbornet** [comment]
Rebased (will conflict with #6472 :smile: )

**Pull request merged**
