### PR TITLE
Entity view improvements & login improvements

### PR DESCRIPTION
**Pull request by deepu105**
1. Improve login popup behavior
2. Improve entity views to make code more readable
3. improve blob type any handling to make file openable
4. change the entity detail table to `<dl>` so that the view is best on desktop and mobiles

### CODE REVIEW

**Comment by deepu105** [comment]
@andidev are you ok with the blob stuff?

**Comment by deepu105** [comment]
@jhipster/developers guys if you are ok with the entity detail view?

image

image

**Comment by pascalgrimaud** [comment]
lgtm

**Comment by andidev** [comment]
Looks really great!

**Comment by atomfrede** [comment]
:+1: Really cool, I like it!

**Comment by jdubois** [comment]
Yes that's good!

**Pull request merged**
