### PR TITLE
Restructure app/index.js

### LINKED ISSUE #2581: Modularize the main generator to follow yeoman recommended priority names
Modularize the main generator to follow yeoman recommended priority names as per [this](http://yeoman.io/authoring/running-context.html)

This is done for entity generator in this PR https://github.com/jhipster/generator-jhipster/pull/2569
This needs to be done for main generator and remaining subs one by one

make the main generator methods more modular with distinct method names for grouped tasks, if possible abstract into separate sub generators and compose them in the main generator similar to how its done in the yeoman generators and angular full stack generator

This would make Jhipster more compatible as an API and will ease maintanance

### PR DESCRIPTION
**Pull request by deepu105**
Restructure the main generator to follow yeoman guidelines

Similar to entity restructure no logic changes, only grouping of feature to method hash
Have included few checks to skip certain tasks when options are set
the options to support that will be done in a separate PR

fix #2581

### CODE REVIEW

**Comment by deepu105** [comment]
damn this took almost a day :(

**Comment by pascalgrimaud** [comment]
Nice work @deepu105 ! => I will clone your branch and made some tests
What we try to follow : http://yeoman.io/authoring/running-context.html
> The available priorities are (in order):
> 1 - initializing - Your initialization methods (checking current project state, getting configs, etc)
> 2 - prompting - Where you prompt users for options (where you'd call this.prompt())
> 3 - configuring - Saving configurations and configure the project (creating .editorconfig files and other metadata files)
> 4 - default - If the method name doesn't match a priority, it will be pushed to this group.
> 5 - writing - Where you write the generator specific files (routes, controllers, etc)
> 6 - conflicts - Where conflicts are handled (used internally)
> 7 - install - Where installation are run (npm, bower)
> 8 - end - Called last, cleanup, say good bye, etc

**Comment by deepu105** [comment]
@jdubois hope you will be merging this soon. I have 5 more PR waiting (#2594, #2591, #2583, #2582, #2567), which I branched off from this, to submit, but i dont want them to cause merge conflicts, so will submit those once this is merged

**Comment by jdubois** [comment]
Impressive work!!!!!!
It's much too big too review in detail: this is definitely the way to go, and I don't see any issue right now, so I'm merging this, and we will improve it later if that's needed.

**Comment by andidev** [comment]
@deepu105 
These changes introducude the removeOlderVersionFiles function which is never called. My guesses this is not with purpose so I'll add a PR that fixes the issue.

**Comment by andidev** [comment]
Okey sorry it's me not understanding the new structure of index.js. Though the files does not get removed for me for some reason.

**Comment by andidev** [comment]
Sorry my bad, it seems to be working! Forget about these comments.

**Pull request merged**
