### PR TITLE
Fix Protractor tests so they work with Okta {angular, react, vue}

### PR DESCRIPTION
**Pull request by mraible**
It should be possible to set username and password environment variables, then run Protractor tests against Okta.

```
export E2E_USERNAME="foo"
export E2E_PASSWORD="bar"
npm run e2e
```

This PR makes it so Angular, React, and Vue tests all pass against Okta.

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
@jhipster/developers Is it possible to modify the GitHub Actions files to temporarily switch to Protractor for e2e? I'd like to switch, make sure everything passes, then switch back to Cypress before merging.

**Comment by mshima** [comment]
@mraible you would have to change the integration-test config files to protractor.
If you merge https://github.com/hipster-labs/jhipster-daily-builds/pull/81, repository and branch parameters will be added to the manual trigger at https://github.com/hipster-labs/jhipster-daily-builds/actions?query=workflow%3A%22Angular+Maven+SQL%22
Those tests have protractor enabled.

**Comment by mraible** [comment]
@mshima That looks like it's only testing Angular. What if I want to test React and Vue too?

**Comment by mshima** [comment]
@mraible if that works, we could add the parameters to vue and react too.

**Comment by mshima** [comment]
https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/486881222

**Comment by mraible** [comment]
If I want to trigger all builds with this PR's branch and repo, I figure it'd be something like this:

```
https://github.com/hipster-labs/jhipster-daily-builds/actions?query=branch%3Aprotractor-okta&repository%3Agit@github.com:mraible/generator-jhipster.git
```

However, this doesn't seem to work.

**Comment by mshima** [comment]
> If I want to trigger all builds with this PR's branch and repo, I figure it'd be something like this:
> 
> ```
> https://github.com/hipster-labs/jhipster-daily-builds/actions?query=branch%3Aprotractor-okta&repository%3Agit@github.com:mraible/generator-jhipster.git
> ```
> 
> However, this doesn't seem to work.

I think you must have commit rights to trigger a build.

> https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/486881222

I've triggered already.

**Comment by mshima** [comment]
Seems to have worked:
```
*** generator-jhipster: JHI_GEN_REPO=https://github.com/mraible/generator-jhipster.git with JHI_GEN_BRANCH=protractor-okta
762
Cloning into 'generator-jhipster'...
763
Switched to a new branch 'protractor-okta'
764
Branch 'protractor-okta' set up to track remote branch 'protractor-okta' from 'origin'.
765
* 83cc0cb925 - (HEAD -> protractor-okta, origin/protractor-okta) Fix typo (2 hours ago) <Matt Raible>
766
* e5643025d7 - Fix Protractor tests so they work with Okta (2 hours ago) <Matt Raible>
767
* f3a36d0580 - fix-protractor-okta (4 hours ago) <Matt Raible>
768
```

**Comment by mshima** [comment]
@mraible I've triggered a rebuild for the same build.
You can clone daily-builds repo and trigger at your repository.
Do you need help to add the parameters to vue and react workflows?
We probably should discuss with @pascalgrimaud to add the parameter to every workflow or revert.

**Comment by mraible** [comment]
@mshima I can probably figure it out. Thanks!

**Comment by mraible** [comment]
@mshima How do you manually trigger the build? I thought hitting `https://github.com/hipster-labs/jhipster-daily-builds/actions?query=workflow%3A%22Angular+Maven+SQL%22` would do it, but it doesn't appear to do so.

Maybe it's a committer-only action?

**Comment by mshima** [comment]
There is a button to trigger it.
It shows in my fork too.

8E9AD358-823A-41C6-B313-AC6A4D6F75EA

**Comment by mraible** [comment]
I don't see the blue bar. Any chance you can make me a committer on this project? Or maybe @pascalgrimaud can?

**Comment by mshima** [comment]
I don’t have permission.

**Comment by pascalgrimaud** [comment]
just added you to daily-builds team @mraible : tell me if it doesn't work

**Comment by mraible** [comment]
That worked! Thanks @pascalgrimaud. 🙏

**Pull request merged**
