### PR TITLE
Add sort function to user management page

### PR DESCRIPTION
**Pull request by sgrillon14**

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I really don't understand your 3 pull requests:
- same title
- too much commits instead of squash

**Comment by sgrillon14** [comment]
Yes, I had a problem when I created my pull request. This additionnal function is "sort datas" in user management.
1) add init param in controler
2) add param in controler
3) add sort directive in HTML
4) add a new label (in all language)

Sorry for the multiple commit to a single pull request :)

**Comment by deepu105** [comment]
This is third PR for the same thing with #3505 and #3507 plz close all thse and open a single PR with all the changes in clean commits

**Comment by jdubois** [comment]
I also don't understand what's happening here.... I'm closing the other PRs, so we just have this last one.

**Comment by deepu105** [comment]
@sgrillon14 if you want this to be merged please push all your chanages to this PR branch and then squash your commits

**Comment by sgrillon14** [comment]
OK, I put all modifications in a fork and I do a single PR.

**Comment by deepu105** [comment]
Im closing this for now either re-open when its ready or open new PR

**Pull request closed without merging**
