### PR TITLE
Change time and message of kafka heartbeat

### PR DESCRIPTION
**Pull request by DjayDev**
Close feature request #8309 

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DjayDev** [comment]
That's better like that. Thanks @pascalgrimaud

**Comment by sendilkumarn** [comment]
@DjayDev Can you please remove the package-lock.json file? This is good to merge and congrats on your first contribution 👍

**Comment by DjayDev** [comment]
@sendilkumarn Sorry I didn't see I've commited the package-lock.json file.
It should be ok know. Le me know.

**Comment by sendilkumarn** [comment]
Lets merge this once CI is green

**Comment by sendilkumarn** [comment]
@DjayDev No worries 👍

**Comment by pascalgrimaud** [comment]
Just restarted, let's wait

**Comment by DjayDev** [comment]
@pascalgrimaud nice try, but it seems that it's still failing. I don't see why exactly. Let me know if I can help.

**Comment by pascalgrimaud** [comment]
@DjayDev : it's not your fault. See our mailing list https://groups.google.com/forum/#!topic/jhipster-dev/j5Y3TUfgqf4

**Comment by jdubois** [comment]
Indeed that's not your fault - that's why I'm merging this. Then 1 minutes looks a bit too long for me, we'll see if that's good enough for our users in the future.

Oh, and congrats on your 1st contribution!!!

**Comment by DjayDev** [comment]
Thanks all, and it's a pleasure to add a very small stone to the project.

**Pull request merged**
