### PR TITLE
Add null checks and public access modifier

### LINKED ISSUE #13471: A reactive monolith is not AAA in Sonar
##### **Overview of the issue**

If I generate a reactive monolith, the Sonar scores aren't great. Instead of A for Bugs, it's a C. And there's a new Hotspots Reviewed metric that seems to error.

image

##### **Motivation for or Use Case**

It's fun to show Sonar in demos when it scores AAA!

##### **Reproduce the error**

Create an app with the JDL and fixes from #13467. Then, start Sonar and run:

```
./mvnw -Pprod clean verify sonar:sonar -Dsonar.host.url=http://localhost:9001
```

Log in to http://localhost:9001 and view the report.

##### **Related issues**

#13467

##### **Suggest a Fix**

Not sure.

##### **JHipster Version(s)**

7.0 beta 0

### PR DESCRIPTION
**Pull request by Falydoor**
Fix #13471 

image

I'm not too familiar with reactor so let me know if there is a better way to handle this null check:

```java
        if (persistentEntity == null) {
            throw new IllegalArgumentException("Unable to retrieve persisted entity");
        }
```

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by murdos** [comment]
@Falydoor : could you resolve the conflicts?

**Comment by Falydoor** [comment]
@murdos: Sonar check after resolving the conflicts

image

**Comment by murdos** [comment]
@Falydoor : thanks :)

**Comment by Falydoor** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/34246

**Comment by pascalgrimaud** [comment]
@Falydoor : approved

**Pull request merged**
