### PR TITLE
Configuration Annotated with configuration

### PR DESCRIPTION
**Pull request by Tcharl**
As this is a configuration, it should be annotated as if...

- Please make sure the below checklist is followed for Pull Requests.

- [X ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X ] Tests are added where necessary
- [X ] Documentation is added/updated where necessary
- [X ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vishal423** [comment]
It doesn't seems correct as per spring feign docs:

> 
FooConfiguration does not need to be annotated with @Configuration. However, if it is, then take care to exclude it from any @ComponentScan that would otherwise include this configuration as it will become the default source for feign.Decoder, feign.Encoder, feign.Contract, etc., when specified. This can be avoided by putting it in a separate, non-overlapping package from any @ComponentScan or @SpringBootApplication, or it can be explicitly excluded in @ComponentScan.

**Comment by ruddell** [comment]
These were removed in https://github.com/jhipster/generator-jhipster/issues/7756

**Comment by Tcharl** [comment]
I think this is correct: the AuthInterceptor shall be the default RequestInterceptor, no?

**Comment by Tcharl** [comment]
An addition would be to import @Import(FeignClientsConfiguration.class) in FeignConfiguration as well

**Pull request closed without merging**
