### PR TITLE
Fix entity suffix for Entity Test file

### PR DESCRIPTION
**Pull request by pascalgrimaud**
When generating an application with entitySuffix property, the generated test files are not correct:

```
➜ jhjdl jdl/beer.jdl
INFO! Using JHipster version installed globally
INFO! Executing import-jdl jdl/beer.jdl
INFO! The JDL is being parsed.
INFO! Found entities: Beer.
INFO! The JDL has been successfully parsed
INFO! Generating 0 applications.
INFO! Generating 1 entity.
INFO! Generating entities for application undefined in a new parallel process

Found the /home/pgrimaud/projects/app/.jhipster/Beer.json configuration file, entity can be automatically generated!

     info Creating changelog for entities Beer
   create src/test/gatling/user-files/simulations/BeerGatlingTest.scala
   create src/main/resources/config/liquibase/changelog/20210122125559_added_entity_Beer.xml
   create src/main/resources/config/liquibase/fake-data/20210122125559_entity_beer.csv
 conflict src/main/resources/config/liquibase/master.xml
? Overwrite src/main/resources/config/liquibase/master.xml? overwrite this and all others
    force src/main/resources/config/liquibase/master.xml
    force .yo-rc.json
    force .jhipster/Beer.json
   create src/main/java/com/mycompany/app/domain/BeerEntity.java
   create src/main/java/com/mycompany/app/web/rest/BeerResource.java
   create src/main/java/com/mycompany/app/repository/BeerRepository.java
   create src/test/java/com/mycompany/app/web/rest/BeerResourceIT.java
   create src/test/java/com/mycompany/app/domain/BeerTest.java
    force src/main/java/com/mycompany/app/config/CacheConfiguration.java
Entity Beer generated successfully.
INFO! Generator entities succeed
INFO! Congratulations, JHipster execution is complete!
```

:heavy_check_mark: `src/main/java/com/mycompany/app/domain/BeerEntity.java` is correct

:x: `src/test/java/com/mycompany/app/domain/BeerTest.java` is not correct, as it should be `src/test/java/com/mycompany/app/domain/BeerEntityTest.java` instead

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by mshima — APPROVED** [review]
LGTM

**Comment by pascalgrimaud** [comment]
Do not merge it yet, I found another bug related to this one

**Comment by pascalgrimaud** [comment]
Thanks for the 1st review @mshima 
I added this new commit https://github.com/jhipster/generator-jhipster/pull/13685/commits/75245e9e4ad6a05785488c8c501313298ed490eb otherwise, the classname was not correct

**Review by DanielFran — APPROVED** [review]

**Comment by mshima** [comment]
Maybe we should cleanup the old file.

**Comment by pascalgrimaud** [comment]
Yes we could cleanup old file, but not sure it is needed, as for me, this bug is here since months (maybe years).
It means very few people use this specific entitySuffix.

**Pull request merged**
