### PR TITLE
Rename refactoring _EntityDto.java -> _EntityDTO.java

### PR DESCRIPTION
**Pull request by jksoftpro**
As discussed previously unix based systems which are case-sensitive cannot find _EntityDTO.java file thus generation process fails with error.

This refactoring fixes the issue.

### CODE REVIEW

**Comment by jdubois** [comment]
I don't understand, I'm on Mac and I should have the same issue! Let me check...

**Comment by jdubois** [comment]
You are correct, I don't understand what I had done!!! I'll need to issue a bug-fixing release ASAP

**Comment by jksoftpro** [comment]
Alright, no problem at all.

You might have chosen to use case-insensitive file system on your Mac thus you might not have seen this issue previously. Let me know what was the issue on your Mac?

**Comment by jdubois** [comment]
The issue is that I didn't have an issue :-)

**Comment by jksoftpro** [comment]
No worries, it happens in development quite often. We are here to help :)

**Comment by jdubois** [comment]
Thanks again! New release is 2.13.1!

**Pull request merged**
