### PR TITLE
Update Copywrite Headers for 2020

### PR DESCRIPTION
**Pull request by SudharakaP**
Related PRs for updating copy-write headers in other repositories; 

| Repository        | PR           |
| -------------------- |:-------------:|
| jhispter-registry | https://github.com/jhipster/jhipster-registry/pull/406
| jhipster-core      | https://github.com/jhipster/jhipster-core/pull/420
| jhispter-online   | https://github.com/jhipster/jhipster-online/pull/143
| jhipster              | https://github.com/jhipster/jhipster/pull/523
| jhipster-daily-builds | https://github.com/hipster-labs/jhipster-daily-builds/pull/35
| jhipster-vuejs | https://github.com/jhipster/jhipster-vuejs/pull/521
| generator-jhipster-nodejs | jhipster/generator-jhipster-nodejs#80
| ng-jhipster | jhipster/ng-jhipster#120
| generator-jhipster-module | jhipster/generator-jhipster-module#56
| prettier-java | jhipster/prettier-java#344
| jhipster-devbox | jhipster/jhipster-devbox#117
| jhipster-ide | https://github.com/jhipster/jhipster-ide/pull/326
| react-jhipster | jhipster/react-jhipster#39
| jhipster-kotlin | https://github.com/jhipster/jhipster-kotlin/pull/212

Please feel free to let me know if there's anything else needs to be added. :smile: 

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by SudharakaP** [comment]
There's some more to be added; I'll do the rest today evening or tomorrow. :smile:

**Comment by SudharakaP** [comment]
@salaboy : Just fyi, while going through this I noticed that the [jhipster-operator license isn't updated](https://github.com/SudharakaP/jhipster-operator/blob/7599d7019797c6a25e1887e4a250d77193047e32/LICENSE#L189).

**Comment by salaboy** [comment]
@SudharakaP i should update that too.. I will be back to work on Wednesday and try to do that ASAP

**Comment by SudharakaP** [comment]
@salaboy : Thanks; I wasn't sure what name to put there; otherwise would have done a PR. :smile:

**Comment by SudharakaP** [comment]
I believe I've covered everything in [jhipster](https://github.com/jhipster) and [hipster-labs](https://github.com/hipster-labs). If you see anything else feel free to point it out. :smile:

**Pull request merged**
