### PR TITLE
Sonar: Disable S1192 on CacheConfiguration

### PR DESCRIPTION
**Pull request by qmonmert**
Related to #25231 

Fix https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=jhipster-sample-application&open=AXZiLoQ8RzWdFtSYLf2r

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
We should use it for nom jpa applications.
I wonder we should use the meta model for jpa see https://github.com/jhipster/generator-jhipster/pull/25239.

**Comment by qmonmert** [comment]
@mshima `jpaMetamodelFiltering` is true?

**Comment by mshima** [comment]
Hibernate meta model is generated by annotation processor:
https://github.com/jhipster/generator-jhipster/blob/ec5bc1853934035ee2e78242668344655fd4b384/generators/spring-data-relational/internal/dependencies.ts#L101

We add to every jpa application.

**Comment by qmonmert** [comment]
not sure to understand...

**Comment by mshima** [comment]
Hibernate metamodel generator generates something like:
```
package tech.jhipster.sample.domain;

import jakarta.annotation.Generated;
import jakarta.persistence.metamodel.EntityType;
import jakarta.persistence.metamodel.SetAttribute;
import jakarta.persistence.metamodel.SingularAttribute;
import jakarta.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(LabelEntity.class)
@Generated("org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
public abstract class LabelEntity_ {


        /**
         * @see tech.jhipster.sample.domain.LabelEntity#operations
         **/
        public static volatile SetAttribute<LabelEntity, OperationEntity> operations;

        /**
         * @see tech.jhipster.sample.domain.LabelEntity#id
         **/
        public static volatile SingularAttribute<LabelEntity, Long> id;

        /**
         * @see tech.jhipster.sample.domain.LabelEntity#labelName
         **/
        public static volatile SingularAttribute<LabelEntity, String> labelName;

        /**
         * @see tech.jhipster.sample.domain.LabelEntity
         **/
        public static volatile EntityType<LabelEntity> class_;

        public static final String OPERATIONS = "operations";
        public static final String ID = "id";
        public static final String LABEL_NAME = "labelName";

}
```

We use it for filtering and can be used here.

**Pull request merged**
