### PR TITLE
Small fix to bring the action to the past in portuguese

### PR DESCRIPTION
**Pull request by finxster**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks @finxster for your first contribution!

**Comment by finxster** [comment]
@pascalgrimaud I'm glad to help! I hope that this is the first of many :)

**Comment by finxster** [comment]
@pascalgrimaud it seems that the travis build is broken, but I'm not sure why. Can you help me with that?!

**Comment by jdubois** [comment]
Thanks also!
I restarted the build.

**Comment by pascalgrimaud** [comment]
@finxster : no worry, the build was cancelled automatically when I merged your PR

**Comment by finxster** [comment]
Thanks guys!

**Pull request merged**
