### PR TITLE
DO NOT MERGE : Upgrade Netty to 4.1.50 and re-enable Blockhound

### PR DESCRIPTION
**Pull request by cbornet**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by cbornet** [comment]
Still not OK. We need the fix to https://github.com/reactor/reactor-core/issues/2137 or to temporarily whitelist BoundedElasticScheduler.schedule (and probably also BoundedElasticScheduler$BoundedState.dispose)

**Comment by cbornet** [comment]
We should also add a test that verifies that BlockHound is correctly installed : https://github.com/reactor/BlockHound/blob/master/docs/tips.md#adding-blockhound-to-your-tests

**Comment by mraible** [comment]
@cbornet How about a rebase to see if it works now?

**Comment by mraible** [comment]
Is this still needed @cbornet?

**Comment by cbornet** [comment]
No it's not 🙂

**Pull request closed without merging**
