### PR TITLE
ask for table name for entity

### PR DESCRIPTION
**Pull request by mhavrlent**
PR for #2558.

### CODE REVIEW

**Comment by deepu105** [comment]
@mhavrlent you need to rebase against latest master, also plz remove the additional question and make it a command line option `--table-name` so when this is passed the entity name validation against DB keywords can be skipped and this name can be used for tableName, but JHipster reserved word validation should still apply for entity name and the passed table name should be validated against DB keywords

**Comment by deepu105** [comment]
@mhavrlent are you working on this?

**Comment by mhavrlent** [comment]
@deepu105
I am planning to, but I'm a bit busy lately.... :(

**Comment by MathieuAA** [comment]
I've created a thread (right [here](https://github.com/jhipster/jhipster-uml/issues/136)) in the JHipster UML project page in order to keep track of this feature. However, I'm not setting any milestone for this so you guys should tell me when it is safe to add it.

**Comment by mhavrlent** [comment]
I will create another pull request. Closing this one.

**Pull request closed without merging**
