### PR TITLE
[v6] 12072 rollback reactive

### PR DESCRIPTION
**Pull request by joewhite101**
This PR rolls back the reactive Springfox version to something that is closer to compatible with the core jhipster-dependencies version. See associated ticket for details.

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ x] Tests are added where necessary
-   [ x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [x ] Documentation is added/updated where necessary
-   [ x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
cc our webflux experts: @murdos @gzsombor @atomfrede @mraible 
Plz, can you have a look, and test it plz ?
As soon as you merged it, I can start preparing the patch release : v6.10.4

**Comment by cbornet** [comment]
I don't think Springfox 2 works with Webflux.

**Comment by mraible** [comment]
Correct, that's why I upgraded to 3.0 for reactive.

**Comment by mraible** [comment]
What's the best way to move forward on this? Should I try to get Springfox 3.0 working with WebFlux and Spring MVC?

**Comment by joewhite101** [comment]
> What's the best way to move forward on this? Should I try to get Springfox 3.0 working with WebFlux and Spring MVC?

@mraible Nope that work is done in the two PRs below. We just need to review and merge them. And that work is already done on master by @cbornet. The PRs below are a port back to 6.x and we can open them back up if that is the direction we're going.

https://github.com/jhipster/jhipster/pull/874
https://github.com/jhipster/generator-jhipster/pull/12709

Ping me on the JHipster slack and maybe i can clear this up. I may have confused things a bit too much.

**Comment by mraible** [comment]
@joewhite101 Do we still need to rollback things or can this be closed?

**Comment by joewhite101** [comment]
@mraible As far as I know the state is the same. Reactive is broken on 6.x but the set of changes required to fix it is pretty invasive. Could be that this ticket is a "won't fix" and is something that needs to get tested and resolved in 7. 

As we discussed above this is a fairly invasive change and may not be worth it. Closing seems reasonable

**Comment by mraible** [comment]
Closing as suggested by @joewhite101.

**Pull request closed without merging**
