### PR TITLE
replace validation placeholders for React when i18n disabled

### LINKED ISSUE #8476: Validation's placeholders are not replaced in React with translation disabled
##### **Overview of the issue**

Validation's placeholders are not replaced with the corresponding value.

image

##### **Motivation for or Use Case**

The message should display the value to help the user.

##### **Reproduce the error**

Generate a React monolith with no translation.
Generate an entity with validation that requires a value (ex: min, max, pattern, etc).

##### **Suggest a Fix**

I believe it's because in the method `utils.replaceTranslation` the placeholders are never replaced by their values.

##### **JHipster Version(s)**

5.4.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.4.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Person {
  age Integer min(1)
}

</pre>
</details>

##### **Browsers and Operating System**

Chrome 69.0.3497.100 on Mac.

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ciarant**
Fix #8476

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by deepu105** [comment]
I need to check this

**Comment by ciarant** [comment]
I don't understand why Travis failed so I tried kicking off another build that only contained the failing build (JHI_APP=ngx-gradle-fr). It passed (strange), so I've reenabled all the other JHI_APP in Travis.

**Comment by deepu105** [comment]
@jhipster/developers can someone test and merge this

**Comment by ruddell** [comment]
Thanks and congrats on your first contribution to the generator. 👍

**Pull request merged**
