### PR TITLE
Add PipeTest

### PR DESCRIPTION
**Pull request by g-boy05**
the unit test for pipe folder

### CODE REVIEW

**Comment by jdubois** [comment]
Congrats on your first PR @g-boy05 !
And this isn't any easy one :-)

A couple of comments:

- Have a look at the lint output: you have some missing whitespaces, I think you will get warnings
- For your files to be processed, you need to add them to `generators/client/files-angular.js`

**Comment by g-boy05** [comment]
I already added my files on my local version, I will do the pull request now.

**Comment by deepu105** [comment]
Since these files are being moved to the new ng-jhipster library it would be nice if you can do this PR there instead of here

**Comment by deepu105** [comment]
see this https://github.com/jhipster/generator-jhipster/pull/4779

**Comment by g-boy05** [comment]
ok deepu
I will do it now

**Comment by deepu105** [comment]
ok then lest close this

**Pull request closed without merging**
