### PR TITLE
[WIP] Angular 2 - Bootstrap 4 Migration

### PR DESCRIPTION
**Pull request by sendilkumarn**
Based on discussion on #4110

### CODE REVIEW

**Comment by sendilkumarn** [comment]
@deepu105 take a look

**Comment by deepu105** [comment]
ill take a look 2mrw

**Comment by deepu105** [comment]
I haven't tried yet, but is the UI still broken ? If so lets wait for ng2 migration to complete and in the meantime we can keep working on this and merge when ready

**Comment by sendilkumarn** [comment]
That is why pushed it.  lets work on UI here.

UI is broken  😉

**Comment by deepu105** [comment]
@sendilkumarn can you create a branch called `ng2-bs4` on the jhipster repo and merge this there so that we can work on that without having to do PR to each other

**Comment by deepu105** [comment]
@sendilkumarn never mind I have pushed this to a new branch here lets work on that. hence closing this

**Pull request closed without merging**
