### PR TITLE
[Vue] Fix login with websockets enabled

### LINKED ISSUE #15961: Jhipster build with Websocket and Vue, not authenticating or log in
##### **Overview of the issue**

I try to login into the JHipster webapp but the app couldn't authenticating when the build is using this setup;

application type > Monolithic application
base name application > jhipster
spring webflux > N
package name > com.mycompany.myapp
authentication type > HTTP Session Auth (stateful)
database type > SQL
production db > MySQL
development db > MySQL
cache > Ehcache
Hibernate 2nd Lvl cache > Y
lib mgmt > Gradle
JHipster registry > No
Websocket using spring websocket
frontend framework > vue
admin UI > Y
theme > default
int. support > Y
Junit & Jest > cypress, gatling, cucumber

##### **Motivation for or Use Case**

I want to build a monolithic app using Vue and WebSocket with user session management.

##### **Reproduce the error**

use this suggested build:
application type > Monolithic application
base name application > jhipster
spring webflux > N
package name > com.mycompany.myapp
authentication type > HTTP Session Auth (stateful)
database type > SQL
production db > MySQL
development db > MySQL
cache > Ehcache
Hibernate 2nd Lvl cache > Y
lib mgmt > Gradle
JHipster registry > No
Websocket using spring websocket
frontend framework > vue
admin UI > Y
theme > default
int. support > Y
Junit & Jest > cypress, gatling, cucumber

run the server with

gradlew -x webapp

and another open terminal to run the vue front end

npm start

The frontend page open at localhost:9000 and backend at 8080. 

##### **Related issues**

I already post through stackoverflow;
https://stackoverflow.com/questions/68360233/jhipster-build-with-websocket-and-vue-not-authenticating-or-log-in

##### **Suggest a Fix**

So far; I don't have problems logging in (authenticating) with Jhipster build with angular as the front end. 

##### **JHipster Version(s)**

NPM version 7+
JHipster version 7.1.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test-vue-web-socket@0.0.0 D:\WDzul78\Documents\GitHub\TestVueWebSocket
`-- generator-jhipster@7.1.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "TestVueWebSocket",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1628840548581,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "session",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "buildTool": "gradle",
    "serverSideOptions": ["websocket:spring-websocket"],
    "websocket": "spring-websocket",
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "vue",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "in"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

git version 2.20.1.windows.1

node: v16.5.0

npm: 7.19.1

Docker version 20.10.7, build f0df350

docker-compose version 1.29.2, build 5becea4c

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Windows 10
Lq5bM

- [ ] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #16425: jdl does not work. SC 404 on https://raw.githubusercontent.com/jhipster/jdl-samples/main/jhipster-jdl.jh
##### **Overview of the issue**

The JDL generator fails on simple Cassandra and Postgres apps.
In the console looks like an issue on https://raw.githubusercontent.com site.

##### **Motivation for or Use Case**

This is the default JDL execution.

##### **Reproduce the error**

Step 1. create an empty cassandra project.

? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? jhipster
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.mycompany.myapp
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? Cassandra
? Which cache do you want to use? (Spring cache abstraction) No cache - Warning, when using an SQL database, this will disable the Hibernate 2nd level cache!
? Would you like to use Maven or Gradle for building the backend? Maven
? Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? Which other technologies would you like to use?
? Which *Framework* would you like to use for the client? Angular
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? No
? Please choose the native language of the application English
? Besides JUnit and Jest, which testing frameworks would you like to use? Gatling, Cucumber
? Would you like to install other generators from the JHipster Marketplace? No

Step 2. add the following jhipster-jdl.jdl with this content:

entity Employee {
	firstName String,
	lastName String,
	email String,
	phoneNumber String,
	hireDate Instant,
	salary Long,
	commissionPct Long
} 

Step 3. Run entity generator

C:\Temp\jhipster-cassandra>jhipster jdl jhipster-jdl.jh
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Downloading file: https://raw.githubusercontent.com/jhipster/jdl-samples/v7.1.0/jhipster-jdl.jh
INFO! Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/v7.1.0/jhipster-jdl.jh: 404 - Not Found
INFO! Downloading file: https://raw.githubusercontent.com/jhipster/jdl-samples/main/jhipster-jdl.jh
ERROR! Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/main/jhipster-jdl.jh: 404 - Not Found
Error: Error downloading https://raw.githubusercontent.com/jhipster/jdl-samples/main/jhipster-jdl.jh: 404 - Not Found
    at ClientRequest.<anonymous> (C:\Temp\jhipster-cassandra\node_modules\generator-jhipster\cli\download.js:33:25)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:376:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)

##### **Related issues**
-

##### **Suggest a Fix**
no idea.

##### **JHipster Version(s)**
7.1.0
7.2.0
both on windows laptops.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "jhipster",
    "jhipsterVersion": "7.1.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["gatling", "cucumber"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1632472163474,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "cassandra",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "devServerPort": 4200,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
No files generated in the directory `.jhipster`

##### **Environment and Tools**
java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)
git version 2.32.0.windows.2
node: v14.17.0
npm: 6.14.13
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.26.2, build eefe0d31
No change to package.json was detected. No package manager install will be executed.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Unfortunatelly the entities are not created.
The .jhipster directory is empty.

##### **Browsers and Operating System**
Windows.
Latest Chrome.

- [ x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by swarajsaaj**
Fix tracker service which was failing due to missing $cookies reference
needed for X-XSRF-TOKEN

Fix #15961

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mshima** [comment]
Can you enable websocket in 1 jwt and 1 oauth2 vue integration tests samples?

**Comment by swarajsaaj** [comment]
>Can you enable websocket in 1 jwt and 1 oauth2 vue integration tests samples?

@mshima  Sure, I will also add websocket in 1 session sample (probably `vue-gradle-session`). There's just 1 oauth2 test though, shall I convert some other test to oauth2 authentication from jwt?

**Comment by swarajsaaj** [comment]
@mshima  added 1 websocket sample for all 3 auth types and failing test cases fixed.

**Comment by mshima** [comment]
Great thanks.
Tests are green. The fix should be working.
I will let vue developers to take a look.

**Comment by pascalgrimaud** [comment]
Thanks @swarajsaaj !

**Comment by swarajsaaj** [comment]
Bounty claimed :) https://opencollective.com/generator-jhipster/expenses/51415

**Comment by pascalgrimaud** [comment]
@swarajsaaj : approved

**Comment by pascalgrimaud** [comment]
@swarajsaaj : as you updated the test-integration folders, can you update https://github.com/jhipster/jhipster-bom project too plz ? Otherwise, the builds will fail there

**Comment by swarajsaaj** [comment]
@pascalgrimaud Sure, I ll have a look at that today.

**Comment by pascalgrimaud** [comment]
thanks a lot @swarajsaaj : nothing urgent, take your time :-)

**Pull request merged**
