### PR TITLE
All files have been translated into Karakalpak language

### LINKED ISSUE #20758: Adding Karakalpak language
##### **Overview of the feature request**
Add the generator jhipster Karakalpak language. 

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by saylaww**
Fixes #20758. 

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by mraible** [comment]
@saylaww It looks like `MailServiceIT#testSendLocalizedEmailForAllSupportedLanguages()` is failing because it can't find the file that matches the langKey.

**Comment by saylaww** [comment]
For some reason, I get an error when making a pull request. Please help me find the error

**Comment by mraible** [comment]
`npm test` was failing because of formatting in `generators/generator-constants.mjs`. I fixed it in https://github.com/jhipster/generator-jhipster/pull/20799/commits/b84df918908feb4667fbeaecca2166bc3f7ecf89 by running `npm run prettier:format`.

**Comment by saylaww** [comment]
> `npm test` was failing because of formatting in `generators/generator-constants.mjs`. I fixed it in [b84df91](https://github.com/jhipster/generator-jhipster/commit/b84df918908feb4667fbeaecca2166bc3f7ecf89) by running `npm run prettier:format`.

did you fix the error? What should I do now? I don't know that

**Comment by Tcharl** [comment]
Bug fixed on main branch, but it looks like your addition is coming with a small glitch

**Comment by deepu105** [comment]
Ejs extension is for files that has template placeholders, afaik, unless @mshima updated the behaviour

**Comment by Tcharl** [comment]
looking at how the current files are created https://github.com/jhipster/generator-jhipster/tree/main/generators/languages/templates/src/main/resources/i18n, I guess that the file should be named messages_kr_Latin_KR.properties.ejs

**Comment by mshima** [comment]
The behavior should be the same.
Looking at https://www.oracle.com/java/technologies/javase/jdk17-suported-locales.html.
This locale is not officially supported, but the java pattern is Latn instead of Latin.

**Comment by mshima** [comment]
Every new locale file must be renamed.

**Comment by saylaww** [comment]
> Every new locale file must be renamed.

Are all the files fixed? What should I do now?

**Comment by saylaww** [comment]
Another mistake baby. Is it possible to add a new language? Tired of making mistakes. Can you please help me

**Comment by mshima** [comment]
@saylaww you need to rename the i18n folder to match the language tag (value).

**Comment by saylaww** [comment]
> @saylaww you need to rename the i18n folder to match the language tag (value).

what else is wrong? I have corrected the file you mentioned

**Comment by mshima** [comment]
@saylaww angular and dayjs doesn't supports `kr-Latn` language.
https://github.com/jhipster/generator-jhipster/pull/20900 renamed the definitions fields to the match the technology name and added support to set fallbacks.
The languages definitions was moved to https://github.com/jhipster/generator-jhipster/blob/main/generators/languages/support/languages.mts.

So you need to rebase and add fallbacks to angular and days:
https://github.com/jhipster/generator-jhipster/blob/8ade36170cea56ffc1a62c9a496e61e1ad4fe244/generators/languages/support/languages.mts#L78-L87
like
```
{
  ...
  angularLocale: 'en',
  dayjsLocale: 'en',
}
```

**Pull request closed without merging**
