### PR TITLE
MSSQL Support

### LINKED ISSUE #4518: [FEATURE] MSSQL Support
This was brought up in the mailing list and on Twitter - now that Microsoft has open-sourced their driver and released a docker image, we can support MSSQL as a first-class JHipster database type! 🎉   I set up a repository showing the [changes needed for MSSQL](https://github.com/ruddell/jhipster-mssql-example/commit/9b89e3281be7fa47ae6dc5611c97b046f7d2e2a4) (starting from MySQL).

You need to manually create the SQL Server database, I couldn't find any docker settings that create a database on startup.  Would this be an issue for our Travis tests?

Should I go ahead and create a PR for this?

### PR DESCRIPTION
**Pull request by ruddell**
Note: You need to manually create the database table when using the docker image.

Fix #4518

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@ruddell : how can the database be created ?

**Comment by ruddell** [comment]
One way is to use an npm package sql-cli https://www.npmjs.com/package/sql-cli

`mssql -u SA -p 'yourStrong(!)Password' -q 'CREATE DATABASE jhitest'`

**Comment by RishabhTayal** [comment]
Does jhipster supports clob type column for ms sql? I am using following json to generate column in my entity.

```
{
      "fieldName": "myFieldName",
      "fieldType": "byte[]",
      "fieldTypeBlobContent": "text"
    }
```

Getting following error:

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at liquibase.datatype.DataTypeFactory.fromDescription(DataTypeFactory.java:251)
	at liquibase.change.core.CreateTableChange.generateStatements(CreateTableChange.java:70)
	at liquibase.change.AbstractChange.generateStatementsVolatile(AbstractChange.java:287)
	at liquibase.change.AbstractChange.warn(AbstractChange.java:358)
	at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:109)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:269)
	at liquibase.Liquibase.update(Liquibase.java:198)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:353)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:305)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:100)
	at io.github.jhipster.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:80)
	at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ruddell** [comment]
Please open a new issue if it doesn't work as expected.

**Comment by RishabhTayal** [comment]
@ruddell Submitted new issue https://github.com/jhipster/generator-jhipster/issues/13977

**Pull request merged**
