### PR TITLE
Upgrade jib to 1.2.0

### PR DESCRIPTION
**Pull request by PierreBesson**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
Please don't merge this yet. It seems that the built docker image with gradle doesn't work because jib sees that the "war" plugin is declared and executes the war build.

**Comment by atomfrede** [comment]
Should I investigate further here? I think we had the issue before, at least I remember a discussion about this somewhere...

**Comment by PierreBesson** [comment]
I have setup the war profile for gradle. It was not entirely necessary before this upgrade to jib but as war packaging is only kept for compatibility and for the sake of consistency with maven it doesn't seem like a bad solution.

**Comment by DanielFran** [comment]
I relaunch tests in Azure pipeline

**Comment by pascalgrimaud** [comment]
@DanielFran : were you able to relaunch 1 specific build only ?

**Comment by DanielFran** [comment]
Yes, it appears at left in azure page 'rerun failed tests'.
This seems available since few days...

**Comment by pascalgrimaud** [comment]
so you're have the permission to do it ! probably for all core team members
it's perfect !!
thanks for the information

**Pull request merged**
